### ISSUE TITLE
drop `mita` directory

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#100]
We have `mita` directory, likely a configuration of https://github.com/ceph/mita, which we no longer use. It should be safe to drop it.

**Comment by vasukulkarni** [comment]
mita is *not* a configuration but openstack library which will be still valid, I kept the dir name as mita to give *credits* to the original mita project, since thats how we got introduced to libcloud, the mita link you provided is a *jenkins slave orchestration*

**Comment by mbukatov** [comment]
Closing based on [explanation in previous comment](https://github.com/red-hat-storage/ocs-ci/issues/100#issuecomment-496688825).
