### ISSUE TITLE
test_noobaa_db_backup_recovery_locally failing on warps3.run_benchmark

### ISSUE THREAD

**Issue by vkathole** [red-hat-storage/ocs-ci#10046]
RP : https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/21659/1030022/1030025/log
        https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/21271/1016601/1016604/log

**Comment by PrasadDesala** [comment]
This issue was not observed in any of the recent runs.
