### ISSUE TITLE
test_detach_attach_worker_volume and test_detach_attach_2_data_volumes are sometimes failing because OSD crash happens after archive cmd is executed

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#10075]

**Comment by ebenahar** [comment]
Fixed with https://github.com/red-hat-storage/ocs-ci/pull/9671

**Comment by am-agrawa** [comment]
I mis-interpreted that this issue is fixed with pr #9671 but it actually started occurring after 9671 was merged. Re-opening it.
