### ISSUE TITLE
make deployment job work for ODF Provider Mode in one jenkins job

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#10083]
Address issues:

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39396/console
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39553/consoleFull

also:
metallb installation failure

**Comment by petr-balogh** [comment]
@DanielOsypenko can you please put the text of the error (traceback) directly to the issue please, as the jenkins job will disappear in some time, so we will not exactly know which exact issue is there. Thanks
