### ISSUE TITLE
test test_encrypted_pvc_no_expansion_option[v1-vault-False] failing with ResourceWrongStatusException on multistorage cluster

### ISSUE THREAD

**Issue by paraggit** [red-hat-storage/ocs-ci#10100]
test test_encrypted_pvc_no_expansion_option[v1-vault-False] failing with ResourceWrongStatusException on multistorage cluster.

RUN_ID: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/23075/1110916/1111104/log?logParams=history%3D1111104%26page.page%3D1

**Comment by nehaberry** [comment]
@paraggit please set the priority of the issue.
