### ISSUE TITLE
Not able to hit API request to bugzilla site due to admin ban issue

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/ocs-ci#10245]
Not able to hit API request to bugzilla site due to admin ban issue

RP link: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/23601/1135472/1135558/log

**Comment by sagihirshfeld** [comment]
Looks like many if not all of OCS-CI TC's that have the `bugzilla` decorator are affected by this, and not just from Red Squad

**Comment by ebondare** [comment]
Black squad is also affected by this issue: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/23646/1139488/1139516/log

**Comment by petr-balogh** [comment]
We are moving out of bugzilla and we were disabled the bugzilla as of now, so it should not happen anymore in new executions. Closing it.
