### ISSUE TITLE
Add timeout for UPI and VMware deployments

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1024]
We should add timeout of 40mins or whatever is appropriate for VMware and UPI deployments. Follow on PR for https://github.com/red-hat-storage/ocs-ci/pull/831

**Comment by clacroix12** [comment]
We actually aren't using `run_cmd` for the shell execution portion of AWS UPI so I think we are okay there.

**Comment by vasukulkarni** [comment]
Great to hear that :-)

**Comment by clacroix12** [comment]
I see we are using `run_cmd` in the vsphere UPI deployment though, so we might want to keep this open until @vavuthu has had a chance to weigh in on timeouts being necessary. I think we might need it for the waiting for bootstrapping portion at the very least.

**Comment by vavuthu** [comment]
vsphere UPI uses run_cmd which needs to include timeout parameter. I am working on it
