### ISSUE TITLE
Replace AWS UPI shell script execution with our own code

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1025]
Currently we are using a [shell script](http://git.app.eng.bos.redhat.com/git/openshift-misc.git/tree/v3-launch-templates/functionality-testing/aos-4_2/hosts/upi_on_aws-install.sh) and [cloudformation templates](http://git.app.eng.bos.redhat.com/git/openshift-misc.git/tree/v3-launch-templates/functionality-testing/aos-4_2/hosts/upi_on_aws-cloudformation-templates) from the [openshift-misc repository](http://git.app.eng.bos.redhat.com/git/openshift-misc.git) in addition to code in our framework in order to perform an AWS UPI installation of OCP to deploy OCS on.

This process is limiting us in a number of ways: 
- Certain aspects of the deployment are not configurable (all of which are important for our supported deployment configuration matrix)
  - Availability Zones
  - Worker OS type
  - Master/Worker node count
- Needing to translate certain configuration parameters into environment variables in order for the script to function properly.
- Debugging and troubleshooting issues is difficult due to:
  - Testing changes to the script combined with execution from our framework requires more work than necessary if we handled the logic on our own
  - Output (These could probably be fixed from our side but it seems silly when we can fully control logging if we did this in python)
    - Live output doesn't exist
    - When we do get output it is not the complete output from the script
    - Output is not formatted well
    - Difficult to determine what the actual script issue from jenkins test failures:
      - Example: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/588/testReport/

I would like to propose that we replace the need for these external resources by implementing the provisioning ourselves. We can leverage the cloudformation templates and boto in order to achieve the same provisioned infrastructure while offering us a few benefits:

- Improved logging
- Better alignment with our frameworks configuration
  - No need to set env vars for several configuration parameters
  - Allow for more granular configuration defined by our team's requirements
- Easier debugging and troubleshooting
- Easier to make changes to the workflow as we will own the python code as well as the cloudformation templates being used
- Improving the workflow to handle variability in some aspects like AZ count, worker count, AMI being used, etc. is more easily done in python than in bash.
- We do not need to ensure the current workflow is maintained. Currently we do not want to break the script's default behavior as another team is dependent on it.

**Comment by clacroix12** [comment]
@petr-balogh @shylesh If you guys have any feedback/addition to this please add it.

**Comment by vasukulkarni** [comment]
The fact that this is UPI ( user provisioned) , we need something like this yaml to be passed so that user has complete control over what he needs to setup: https://github.com/red-hat-storage/cephci/blob/master/conf/luminous/ansible/sanity-ansible-containerized.yaml#L2-L50 , Obiviously AZ and other needs should be baked in for AWS but not for openstack.

I am +1 for Boto API's with clear logging process that should be easy to debug for everyone and help enhance as well. Soon we will have Openstack Boto API will work with both.

**Comment by vasukulkarni** [comment]
@keesturam @hnallurv FYI

**Comment by petr-balogh** [comment]
Thanks for writeup @clacroix12 , I remember that you've tried to play with boto3 to do the things which are done by openshift-misc script, do you have some time estimation to rewrite what we currently have to our own functionality?  Otherwise it's sound OK to me what you wrote and we will get some advantages and more flexibility for future requirements.

**Comment by clacroix12** [comment]
@petr-balogh I don't anticipate the work to take very long now that we have a working baseline. When I initially tried using boto we did not have a fully functional AWS UPI workflow so there were still a few unknowns I was encountering. I anticipate the additional code to perform what the shell script is doing, along with the cleanup of code that would now be unnecessary to take perhaps a few days. Testing will take a decent amount of time as well just simply due to the turnaround time when encountering issues later on in the deployment process. Optimistically I think I could have an initial PR up within a week. Just also noting here as we previously discussed we won't start to tackle this until after GA as trying to rush this beforehand won't really do us any favors.

**Comment by petr-balogh** [comment]
Thanks for updates

**Comment by clacroix12** [comment]
If we are moving to using flexy as our means of deploying UPI to all platforms we will no longer need this. Once we are committed to using flexy we can close this out.

**Comment by clacroix12** [comment]
Closing as we are using flexy.
