### ISSUE TITLE
test_create_new_project_to_verify_logging is failing with TimeoutExpiredError

### ISSUE THREAD

**Issue by vkathole** [red-hat-storage/ocs-ci#10290]
RP: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/23931/1156340/1156635/log

`request = <SubRequest 'install_logging' for >

@pytest.fixture(scope="class")
def install_logging(request):
    """
    Setup and teardown
    * The setup will deploy openshift-logging in the cluster
    * The teardown will uninstall cluster-logging from the cluster

    """

    def finalizer():
        uninstall_cluster_logging()

    request.addfinalizer(finalizer)

    sub = ocp.OCP(
        kind=constants.SUBSCRIPTION,
        namespace=constants.OPENSHIFT_LOGGING_NAMESPACE,
    )
    logging_sub = sub.get().get("items")
    if logging_sub:
        log.info("Logging is already configured, Skipping Installation")
        return

    log.info("Configuring Openshift-logging")

    # Gets OCP version to align logging version to OCP version
    ocp_version = version.get_semantic_ocp_version_from_config()

    logging_channel = "stable" if ocp_version >= version.VERSION_4_7 else ocp_version

    # Creates namespace openshift-operators-redhat
    ocp_logging_obj.create_namespace(yaml_file=constants.EO_NAMESPACE_YAML)

    # Creates an operator-group for elasticsearch
    assert ocp_logging_obj.create_elasticsearch_operator_group(
        yaml_file=constants.EO_OG_YAML, resource_name="openshift-operators-redhat"
    )

    # Set RBAC policy on the project
    assert ocp_logging_obj.set_rbac(
        yaml_file=constants.EO_RBAC_YAML, resource_name="prometheus-k8s"
    )

    # Creates subscription for elastic-search operator
    subscription_yaml = templating.load_yaml(constants.EO_SUB_YAML)
    subscription_yaml["spec"]["channel"] = logging_channel
    helpers.create_resource(**subscription_yaml)
    assert ocp_logging_obj.get_elasticsearch_subscription()

    # Checks for Elasticsearch operator
    elastic_search_operator = OCP(
        kind=constants.POD, namespace=constants.OPENSHIFT_OPERATORS_REDHAT_NAMESPACE
    )
    elastic_search_operator.wait_for_resource(
        resource_count=1, condition=constants.STATUS_RUNNING, timeout=200, sleep=20
    )

    # Creates a namespace openshift-logging
    ocp_logging_obj.create_namespace(yaml_file=constants.CL_NAMESPACE_YAML)

    # Creates an operator-group for cluster-logging
    assert ocp_logging_obj.create_clusterlogging_operator_group(
        yaml_file=constants.CL_OG_YAML
    )

    # Creates subscription for cluster-logging
    cl_subscription = templating.load_yaml(constants.CL_SUB_YAML)
    cl_subscription["spec"]["channel"] = logging_channel
    helpers.create_resource(**cl_subscription)
    assert ocp_logging_obj.get_clusterlogging_subscription()

    # Creates instance in namespace openshift-logging
    cluster_logging_operator = OCP(
        kind=constants.POD, namespace=constants.OPENSHIFT_LOGGING_NAMESPACE
    )
    cluster_logging_operator.wait_for_resource(
        resource_count=1, condition=constants.STATUS_RUNNING, timeout=200, sleep=20
    )
    if cluster_logging_operator:
        log.info(f"The cluster-logging-operator {cluster_logging_operator.get()}")

      ocp_logging_obj.create_instance()

tests/conftest.py:3307: 

ocs_ci/utility/retry.py:31: in f_retry
    return f(args, *kwargs)
ocs_ci/utility/deployment_openshift_logging.py:321: in create_instance
    assert create_instance_in_clusterlogging()
ocs_ci/utility/deployment_openshift_logging.py:255: in create_instance_in_clusterlogging
    pod_status = pod_obj.wait_for_resource(
ocs_ci/ocs/ocp.py:850: in wait_for_resource
    raise (ex)
ocs_ci/ocs/ocp.py:741: in wait_for_resource
    for sample in TimeoutSampler(

self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7f8298ea15e0>

def __iter__(self):
    if self.start_time is None:
        self.start_time = time.time()
    while True:
        self.last_sample_time = time.time()
        if self.timeout <= (self.last_sample_time - self.start_time):

          raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 800s running get("", True, None)

ocs_ci/utility/utils.py:1445: TimeoutExpiredError

2024-08-10 01:49:44
`

**Comment by Shrivaibavi** [comment]
Looks like elastic search support is extended for OCP 4.17 now and logging installation and tests should pass from now on and the previous test failures are because of the EFK support withdrawal. Can we proceed to close this issue @vkathole @PrasadDesala

**Comment by PrasadDesala** [comment]
After the elastic search support, the test is passing without any issues.
