### ISSUE TITLE
AWS-UPI deployment fail for worker with m5.4xlarge

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#1030]
worker create cmd failed with:- An error occurred (ValidationError) when calling the CreateStack operation: Parameter 'WorkerInstanceType' must be one of AllowedValues

cmd:- aws --region us-east-2 cloudformation create-stack --stack-name pratik-42-ocs-13-no0 --template-body file:///tmp/06_cluster_worker_nodes_2019-11-20-15-10-01_0.yaml --parameters ParameterKey=Index,ParameterValue=0 ParameterKey=InfrastructureName,ParameterValue=pratik-42-ocs-13-lhshw ParameterKey=RhcosAmi,ParameterValue=ami-06c85f9d106577272 ParameterKey=IgnitionLocation,ParameterValue=https://api-int.pratik-42-ocs-13.qe.rh-ocs.com:22623/config/worker ParameterKey=Subnet,ParameterValue=subnet-0707d79791122dec4 ParameterKey=WorkerSecurityGroupId,ParameterValue=sg-09dbae4b41477caeb ParameterKey=WorkerInstanceProfileName,ParameterValue=pratik-42-ocs-13-sg-WorkerInstanceProfile-1EQ6LCRLTWIT7 ParameterKey=WorkerInstanceType,ParameterValue=m5.4xlarge --capabilities CAPABILITY_NAMED_IAM

m5.4xlarge Instance type is not included in AllowedValues in worker_cloudformation_templates
template link [here](http://git.host.prod.eng.bos.redhat.com/git/openshift-misc.git/tree/v3-launch-templates/functionality-testing/aos-4_2/hosts/upi_on_aws-cloudformation-templates/06_cluster_worker_node.yaml#n37l)

**Comment by vavuthu** [comment]
@clacroix12 , I almost submitted PR for this issue and I see issue is assigned to you. let me know if you if you are occupied with high priority work.

**Comment by clacroix12** [comment]
@vavuthu I have a local change that passed testing so I was going to push my branch and create a PR, however I seem to be hitting authentication issues for gerrit. Not sure why as I've pushed branches to this repo before. If I'm unable to resolve this please feel free to open the PR yourself. It was a very small change, I just added `m5.4xlarge` to the `AllowedValues` list in the worker template.

**Comment by clacroix12** [comment]
PR opened here: https://code.engineering.redhat.com/gerrit/#/c/187031/

**Comment by clacroix12** [comment]
Support for `m5.4xlarge` has been merged, closing.
