### ISSUE TITLE
Facing issues while running the run-ci with multicluster

### ISSUE THREAD

**Issue by aditisaxena552** [red-hat-storage/ocs-ci#10319]
**Facing issues while running the run-ci with multicluster**

Currently running the run-ci multicluster command for fusion m07 rack.

Build Details 
OCP : 4.14
DF : 4.14

Command used
run-ci multicluster 2 tests/functional/pv/pv_services/test_pv_creation.py --cluster1 --cluster-name cp4ba-hcp --cluster-path odfclient-path --ocp-version 4.14 --ocs-version 4.14 --ocsci-conf=conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_3w.yaml --cluster2 --cluster-name rackm07 --cluster-path ~/PycharmProjects/Automation/odfcluster-path --ocp-version 4.14 --ocs-version 4.14 --ocsci-conf=conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml

here 
cluster1 has details of the hosted cluster 
cluster2 has details of the host cluster

Output
============================= test session starts ==============================
platform linux -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.5.0
****dir: /home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci, configfile: pytest.ini
plugins: flaky-3.7.0, repeat-0.9.3, progress-1.2.5, order-1.2.0, metadata-1.11.0, logger-0.5.1, jira-0.3.21, marker-bugzilla-0.9.4, html-3.1.1, typeguard-4.3.0, allure-pytest-2.13.5
collected 1 item

tests/functional/pv/pv_services/test_pv_creation.py::TestPvCreation::test_pv_creation 
-------------------------------- live log setup --------------------------------
05:44:42 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - testrun_name: OCS4-14-Downstream-OCP4-12-LSO-MON-HOSTPATH-OSD-NVME-HCI_BAREMETAL-UPI-1AZ-RHCOS-3M-3W
05:44:42 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - testrun_name: OCS4-14-Downstream-OCP4-12-LSO-MON-HOSTPATH-OSD-NVME-HCI_BAREMETAL-UPI-1AZ-RHCOS-3M-3W
05:44:42 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Retrieving the authentication config dictionary
05:44:42 - MainThread - tests.conftest - INFO - C[cp4ba-hcp] - All logs located at /tmp/ocs-ci-logs-1724046270
05:44:43 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Downloading openshift client (4.12.0-0.nightly-2024-08-16-175235).
05:44:43 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Executing command: ldd --version ldd
05:44:43 - MainThread - ocs_ci.utility.utils - ERROR - C[cp4ba-hcp] - Failed to download the openshift client. Exception 'The URL https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.12.0-0.nightly-2024-08-16-175235/openshift-client-linux-amd64-rhel8-4.12.0-0.nightly-2024-08-16-175235.tar.gz is not available! Status: 404.'
05:44:44 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - version 4.12 is GA'ed, use the same version to download oc
05:44:45 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Executing command: ldd --version ldd
05:44:48 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Executing command: tar xzvf openshift-client.tar.gz -C /tmp
05:44:49 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Executing command: ldd --version ldd
05:44:50 - MainThread - ocs_ci.utility.utils - INFO - C[cp4ba-hcp] - Executing command: /tmp/oc adm release extract -a /home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/data/pull-secret --command=oc.rhel8 registry.ci.openshift.org/ocp/release:4.12.0-0.nightly-2024-08-16-175235 --to .
**05:44:50 - MainThread - ocs_ci.utility.utils - WARNING - C[cp4ba-hcp] - Command stderr: error: command "oc.rhel8" does not support the operating system "linux"**

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 94, in pytest_runtest_protocol
INTERNALERROR>     self.runner.pytest_runtest_protocol(item, nextitem)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/_pytest/runner.py", line 120, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 141, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/.venv3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 156, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "/home/jenkins/agent/workspace/Automation/Generic_Pipeline_Fusion/Automation/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 778, in pytest_runtest_makereport
INTERNALERROR>     with open(
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: 'odfclient-path//failed_testcases.txt'
---------------------------- live log sessionfinish ----------------------------
05:44:51 - MainThread - ocs_ci.framework.pytest_customization.reports - INFO - C[cp4ba-hcp] - Test Time report saved to '/tmp/ocs-ci-logs-1724046270/session_test_time_report_file.csv'
05:44:51 - MainThread - ocs_ci.framework - INFO - C[cp4ba-hcp] - Switched to cluster: cp4ba-hcp
05:44:51 - MainThread - ocs_ci.framework.pytest_customization.reports - INFO - C[cp4ba-hcp] - Dump of the consolidated config is located here: /tmp/run-1724046270-cl0-config-end.yaml
05:44:51 - MainThread - ocs_ci.framework - INFO - C[rackm07] - Switched to cluster: rackm07
05:44:51 - MainThread - ocs_ci.framework.pytest_customization.reports - INFO - C[rackm07] - Dump of the consolidated config is located here: /tmp/run-1724046270-cl1-config-end.yaml

============================= 17 warnings in 8.16s =============================

Need help in resolving this issue @vavuthu .

**Comment by vavuthu** [comment]
@aditisaxena552 this issue happens whenever client url is not reachable. could you retry now. PR has been raised for the same.

**Comment by aditisaxena552** [comment]
okay I will retry hope the changes are merged
