### ISSUE TITLE
Async output in the run_cmd()

### ISSUE THREAD

**Issue by Avilir** [red-hat-storage/ocs-ci#1047]
When running in Debug level, the outputs of the command output (only  in debug) are written to the log  not exactly after the command that ran, so it hard to debug.
the command should be printed with the output.

**Comment by gklein** [comment]
Is it possible that the we are collecting stdout/stderr separately and this is causing an out of order log file?

I've implemented a version run_cmd() with live output, which also captures stdout and stderr in order.  You may try the [PR](https://github.com/red-hat-storage/ocs-ci/pull/1096/) locally to see if it might help solve this issue too.

**Comment by Avilir** [comment]
closing on lack of interest
