### ISSUE TITLE
Workaround for collection of external mode ceph logs, command outputs in ocs-ci

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#10543]
Email discussion - ocs-ci results for OCS4-14-Downstream-OCP4-14-VSPHERE6-UPI-1AZ-RHCOS-EXTERNAL-3M-3W-tier1 (BUILD ID: 4.14.10-3 RUN ID: 1724309552)

As per current code design and implementation, ceph outputs and logs are not collected in must-gather, especially since we do not have access to admin-key and mon-ip which is required to run ceph command in toolbox.

However, In our CI tests, where we do create a toolbox pod with the above admin-key and mon-IP, so that our tests do not fail while checking ceph outputs

Few discussions from the email and options to work around this:

1. Can we as a workaround, collect the required ceph outputs in our CI (similar to what is collected in must-gather) whenever a must-gather is called for a an external mode failure?
2. Must-gather itself be enahcned to collect these. However, this needs discussion with support and PM as it might be a security concern for the companies - we can discuss it soon
3. <Please add suggestions if you have any>

**Comment by OdedViner** [comment]
@nehaberry @sidhant-agrawal Can you add the relevant ceph commands you want to add? CC @petr-balogh

**Comment by OdedViner** [comment]
PR mergePR mereged:
https://github.com/red-hat-storage/ocs-ci/pull/10594
Validation job: https://url.corp.redhat.com/fa5af0b
collection content: https://url.corp.redhat.com/e040439d
