### ISSUE TITLE
tests/functional/pv/pvc_clone/test_pgsql_pvc_clone.py::TestPvcCloneOfWorkloads::test_encrypted_pvc_clone[v1] failing on power  ODF Version =4.17

### ISSUE THREAD

**Issue by veerareddylucky** [red-hat-storage/ocs-ci#10557]
**Test cases failed with below error**

self = <ocs_ci.utility.kms.Vault object at 0x7ffe3d948c70>

    def gather_vault_config(self):
        """
        This function populates the vault configuration

        """
        if self.vault_deploy_mode == "external":
            if config.ENV_DATA.get("use_vault_namespace"):
                vault_conf = load_auth_config()["vault_hcp"]
            else:
>               vault_conf = load_auth_config()["vault"]
E               KeyError: 'vault'

ocs_ci/utility/kms.py:606: KeyError
[test_encrypted_pvc_clone[v1].log](https://github.com/user-attachments/files/17109477/test_encrypted_pvc_clone.v1.log)

**Comment by PrasadDesala** [comment]
same as #10556 
It looks like vault details are missing in the auth config file /data/auth.yaml. Please check if that is the case.
You need to have a vault sever configured and added those details in the auth config for this test.

**Comment by PrasadDesala** [comment]
Test failed due to configuration issue. Vault details were missing in the auth.yaml. The test passed successfully after adding the vault details.
