### ISSUE TITLE
Specify default storage class names as provided by OCS in constants.py

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1056]
As of now, OCS provides the following storage classes:
- `ocs-storagecluster-ceph-rbd`
- `ocs-storagecluster-cephfs`
- `openshift-storage.noobaa.io`

It could be useful to specify these in constants.py module.

That said, there is a conflict with values already provided there:

```
DEFAULT_SC_RBD = 'ceph-rbd'
DEFAULT_SC_CEPHFS = "cephfs
```
which are used in deployment or registry modules:

```
ocs_ci/deployment/deployment.py:            sc_name = f"{config.ENV_DATA['storage_cluster_name']}-{constants.DEFAULT_SC_RBD}"
"{config.ENV_DATA['storage_cluster_name']}-{constants.DEFAULT_SC_CEPHFS}"
```

To prevent conflict or breaking already existing functionality, we need to understand:
what are the current storage class names used for exactly, so that we will know whether we should update values there or create set of new constants.

**Comment by mbukatov** [comment]
This issue was created based on Elad's suggestion from review of my pull request https://github.com/red-hat-storage/ocs-ci/pull/1043#discussion_r349767709

**Comment by vasukulkarni** [comment]
In my PR i have default_storageclass function, It creates a ocs object https://github.com/red-hat-storage/ocs-ci/blob/d97a651e0278873edabb1afded9b9c86ab3def8e/tests/helpers.py#L350-L362

The conflicted values are removed in my PR

**Comment by mbukatov** [comment]
Given raising complexity of storage class naming over time, storage class names should not go to constants module, but the names along with related code should be placed in a separate storage class name module.
