### ISSUE TITLE
tests.functional.object.mcg.test_namespace_crd.TestNamespace.test_ns_bucket_unsigned_access

### ISSUE THREAD

**Issue by gayathrimenath-ibm** [red-hat-storage/ocs-ci#10894]
```
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error. Please try again.
```
Testcase: Tier2 test_ns_bucket_unsigned_access
Environment: IBM Cloud managed
testcase URL: https://url.corp.redhat.com/d434244

**Comment by udaysk23** [comment]
@gayathrimenath-ibm This looks like network issue. Can you please confirm that we are hitting this issue continuously with all runs

**Comment by gayathrimenath-ibm** [comment]
@udaysk23 Thanks for the confirmation, I am not able to see the issue on next run. Closing the ticket
