### ISSUE TITLE
tests.ecosystem.deployment.test_deployment.test_deployment doesn't validate noobaa buckets

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#1093]
`tests.ecosystem.deployment.test_deployment.test_deployment` test case doesn't validate if noobaa buckets are present or healthy. The test case is passing even if all noobaa buckets are deleted.

**Comment by mbukatov** [comment]
This looks related to https://github.com/red-hat-storage/ocs-ci/issues/1089

**Comment by MeridianExplorer** [comment]
@fbalak - Can you please update this issue with regards to #1089?

**Comment by fbalak** [comment]
From https://github.com/red-hat-storage/ocs-ci/pull/1220 it looks that Noobaa Operator and Noobaa Core are checked for correct health. There should be also check for NooBaa DB which was added later but is currently not in our code. This was replaced with `if not self.mcg_obj.status: raise exceptions.NoobaaHealthException("Cluster health is NOT OK")` in https://github.com/red-hat-storage/ocs-ci/pull/2011/files which checks `status` command of noobaa.

In description of this issue is that there should be check for NooBaa buckets but during installation is only `first.bucket` bucket if I am not wrong. Presence of this is not checked but I am not sure if it's needed during deployment if NooBaa status is ok.

@MeridianExplorer what do you think?

**Comment by MeridianExplorer** [comment]
If NooBaa is healthy - `first.bucket` isn't necessary. But actually, I think it won't be bad to verify its existence upon deployment (only). So maybe we can edit the issue to reflect that we would like to add a check that `first.bucket` is in place, and healthy, upon deployment only.
