### ISSUE TITLE
Hitting certificate error while putting object into cluster

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/ocs-ci#10962]
Hitting certificate error while putting object into cluster

```
E           botocore.exceptions.SSLError: SSL validation failed for [https://10.1.112.155:443/rgw-uls-9ff8765dd3394645ac5f556f1e805a8c](https://10.1.112.155/rgw-uls-9ff8765dd3394645ac5f556f1e805a8c) [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1133)
```

RP link: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/738/27102/1336197/1336327/log?logParams=history%3D1336327%26page.page%3D1

**Comment by sagihirshfeld** [comment]
This is most likely a duplicate of https://github.com/red-hat-storage/ocs-ci/issues/10701

**Comment by udaysk23** [comment]
Closing this issue as it is duplicate of #10701
