### ISSUE TITLE
Add Choas Monkey from John's Repo in Workloads/Failover

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1103]
Integrate Chaos monkey from John's repo and run in workloads.

**Comment by vasukulkarni** [comment]
@JohnStrunk FYI

**Comment by keesturam** [comment]
@vasukulkarni A couple of questions
what is the goal of having the chaos monkey tests run in ocs-ci?
What would be the frequency of triggering these tests?

**Comment by vasukulkarni** [comment]
@keesturam Because we dont have the similar test and running in workloads when it can find bugs will bring in stability issues. When I saw the bug I had in mind to run this from ocs-ci.
