### ISSUE TITLE
Bring up MDS pods along with other Ceph Pods while deploying OCS 

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#112]
With the merging of PR #58 , OCS deployment is CSI based which creates Ceph pods(MONs, OSD, MGR), CSI pods, rook pods and toolbox pods.

But, In a setup deployed using this method, only  RBD volumes can be created. To have Cephfs volumes, we need MDS pods to be part of deployment.

As the requirement docs lists both RBD and CephFS and default volume types, it would be helpful to have a basic set of MDS pods running in the cluster from day-0 ( as part of OCS deployment).

**Things needed:**
1. [filesystem.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/filesystem.yaml)
2. oc create -f filesystem.yaml

**Comment by nehaberry** [comment]
@red-hat-storage/top-level-reviewers what is your suggestion ?

**Comment by RazTamir** [comment]
@nehaberry I don't think we can just go ahead and add mds.
We need to understand what will be the default deployment and ensure we get the same.
Otherwise, we will have a different deployment from our customers

**Comment by nehaberry** [comment]
@RazTamir in that case it would be useful to get this validated from PMs & devs in a meeting. 
Currently, in our default deployment, one cannot run any cephfs related test case until he/she creates MDS pods. So eventually, if we all agree that both RBD and cephfs are day-0 requirements for OCS, we may have to have MDS pods running as part of default OCS deployment.

**Comment by keesturam** [comment]
@nehaberry @RazTamir - RWX is going to be on cephFS unless explicitly called out.

**Comment by nehaberry** [comment]
@keesturam you mean we would need CephFS by default  ? If thats the case, we may need to run "filesystem.yaml" to create MDS pods. Maybe, we can discuss with dev as well

**Comment by RazTamir** [comment]
@nehaberry @keesturam please do ask pm and dev about this
