### ISSUE TITLE
AWS UPI cluster teardown doesn't wait long enough for stacks to be deleted

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1132]
As observed in [this destroy job](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/1935/console) we intermittently end up raising an exception during the teardown of the cluster when one of the stacks is still in the `DELETE_IN_PROGRESS` status. It seems as if some of the stacks are now taking more time than we were giving them in order to delete fully. We should increase the amount of retries we allow for while monitoring the stack statuses.

**Comment by dahorak** [comment]
Just for the record, [there seems](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/2003/) to be similar issue again, not sure if was before the fix was merged or not.
