### ISSUE TITLE
Workaround - Enable container_use_cephfs SELinux boolean on RHEL based workers

### ISSUE THREAD

**Issue by gklein** [red-hat-storage/ocs-ci#1151]
container_use_cephfs SELinux boolean  is disabled by default on RHEL nodes, and should be enabled as [described on this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1777384)

- container_use_cephfs should be enabled on all RHEL workers (no need to enable it on RHCOS based nodes)
- This is relevant for both VMware and AWS platform when using UPI deployment

**Comment by petr-balogh** [comment]
Opened ticket in our board to take this by someone from Ecosystem team:
https://projects.engineering.redhat.com/browse/OCSQE-142

Actually assigned @clacroix12 .

Thanks

**Comment by gklein** [comment]
> Opened ticket in our board to take this by someone from Ecosystem team:
> https://projects.engineering.redhat.com/browse/OCSQE-142
> 
> Actually assigned @clacroix12 .
> 
> Thanks

Ok, np will move the issue accordingly.

**Comment by gklein** [comment]
An easy way to query for rhel/rhcos node would be:
```
oc get nodes -l "node.openshift.io/os_id=rhcos"
oc get nodes -l "node.openshift.io/os_id=rhel"
```

**Comment by petr-balogh** [comment]
I am pretty sure we already have some function which list you all RHEL nodes in ocs-ci.

**Comment by vavuthu** [comment]
> I am pretty sure we already have some function which list you all RHEL nodes in ocs-ci.

ocs_ci/ocs/node.py:get_typed_worker_nodes(os_id="rhcos") will gives the nodes based on OS

**Comment by RazTamir** [comment]
Hi @red-hat-storage/ocs-qe-ecosystem , this is critical for UPI execution with RHEL.
Can we prioritize this? cause we will need to execute the UPI RHEL again to get real status

**Comment by gklein** [comment]
@RazTamir In case this is urgent here is a quick fix #1180

**Comment by petr-balogh** [comment]
We still need this workaround. The issue is tracked via RHSTOR-787 which is still in TO DO status

**Comment by mbukatov** [comment]
This workaround issue should be kept open as long as a workaround is present in ocs-ci code. Here, it's looks like it was closed by mistake via github automation. Reopening.

**Comment by Rtoax** [comment]
I got the following problem
```
# setsebool -P -N container_user_cephfs on
Boolean container_use_cephfs is not defined
```

how can i fix it.
