### ISSUE TITLE
Method `exec_ceph_cmd()` silently drops list items from the output

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1152]
## Description of the problem

Method `exec_ceph_cmd()` silently drops list items from the output if an item evaluates to False.

## Steps to reproduce

Run:

```
ceph_osd_ls = ct_pod.exec_ceph_cmd(ceph_cmd="ceph osd ls")
```

## Actual Results

```
(Pdb) p ceph_osd_ls
[1, 2]
```

## Expected Results

```
(Pdb) p ceph_osd_ls
[0, 1, 2]
```

## Additional Information

When run from command line, output of `ceph osd ls` looks like this:

```
# ceph osd ls --format json-pretty
[
    0,
    1,
    2
]
#
```

But because `exec_ceph_cmd()` method contains following code:

https://github.com/red-hat-storage/ocs-ci/blob/47ffc61c6146b2f9a04c0e515ca828a9bb7aa630/ocs_ci/ocs/resources/pod.py#L206

The first item from the list is dropped silently. I don't think this makes any sense.

Suggested fix includes:
- logging of the raw output (`out` variable) in DEBUG level
- dropping the filtering altogether

## List of workaround

When this BZ is fixed by dropping the filtering, the following workarounds should be removed:

- [ ] https://github.com/red-hat-storage/ocs-ci/blob/f7b31ee7e1c90430bb8a18dc008981962c269f93/tests/manage/monitoring/conftest.py#L990

This is may not be complete.

**Comment by gklein** [comment]
The reason that first item is drop is because "0" is being evaluated to False under the existing filter. 

```
In: out = [0, 1, 2, 3]

#With a filter:
In: [item for item in out if item]
Out: [1, 2, 3]

#Without any filter:
In: [item for item in out]
Out: [0, 1, 2, 3]

#Filter only an empty string (but not a zero number, empty list or empty dictionary) 
In: [item for item in out if not item == '' ]
Out: [0, 1, 2, 3]
```

**Comment by mbukatov** [comment]
> The reason that first item is drop is because "0" is being evaluated to False under the existing filter.

I understand that, which is why I listed the code line in question. What I don't understand is why is it a good idea to do such filtering in a general method like `exec_ceph_cmd()`.

**Comment by gklein** [comment]
> > The reason that first item is drop is because "0" is being evaluated to False under the existing filter.
> 
> I understand that, which is why I listed the code line in question. What I don't understand is why is it a good idea to do such filtering in a general method like `exec_ceph_cmd()`. I would have dropped that line, if I had time for chasing code which depends on such behavior.

I think the intention was to prevent empty strings in the output, so I suggested a safer alternative to apply such a filter. Another option could be to drop the filter entirely as you already suggested.

**Comment by vasukulkarni** [comment]
definitely the filter should be dropped, It will be a source of pain since we cannot assume all string outputs.

**Comment by gklein** [comment]
> definitely the filter should be dropped, It will be a source of pain since we cannot assume all string outputs.

Fine with me. I thought that the original intention here was to filter empty strings. Let try to remove it entirely and run some testing against this change.
