### ISSUE TITLE
Wait for ansible rhel pod should be more than 60 seconds

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1168]
I see last job failed here:

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/2978//console

I think we should increase the timeout to more seconds. Maybe something like 5 mins.

**Comment by shylesh** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/1169
