### ISSUE TITLE
Remove production vmfs config files

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1184]
We need to remove vmfs config files as they were replaced here:
https://github.com/red-hat-storage/ocs-ci/pull/1183/files

But cause of running jobs which I don't want to affect I didn't just renamed them but copied.

**Comment by clacroix12** [comment]
We no longer want the name of the config file to have VMFS or VSAN in it?

**Comment by petr-balogh** [comment]
Actually it's part of each credential file for specific cluster so no need to have different config files for vmfs and vsan as I discussed with @vavuthu .
