### ISSUE TITLE
Run-ci ignores "region" parameter in config files when using RHEL UPI

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#1185]
workaround: using .aws/config file with default region

**Comment by annagitel** [comment]
![noRegion](https://user-images.githubusercontent.com/57480476/70920662-a14bbf80-202b-11ea-8361-a67bc802bfb1.png)

**Comment by clacroix12** [comment]
This is due to how we are instantiating our cloudformation client. We are not passing the `region_name` so it was defaulting to whatever was configured in `~/.aws/config`. I'll have a fix shortly.
