### ISSUE TITLE
MainThread - ocs_ci.ocs.ocp - INFO - Cannot find resource object ocs-operator.v4.2.0

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#1211]
I am getting the above error when I run run-ci  -m deployment

Output includes:

        if deploy:
            # Deploy cluster
>           deployer.deploy_cluster(log_cli_level)

tests/conftest.py:825:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ocs_ci/deployment/deployment.py:88: in deploy_cluster
    self.deploy_ocs()
ocs_ci/deployment/deployment.py:390: in deploy_ocs
    self.deploy_ocs_via_operator()
ocs_ci/deployment/deployment.py:289: in deploy_ocs_via_operator
    csv.wait_for_phase("Succeeded", timeout=720)
ocs_ci/utility/retry.py:31: in f_retry
    return f(*args, **kwargs)

and ends with

E           ocs_ci.ocs.exceptions.ResourceInUnexpectedState: Resource: ocs-operator.v4.2.0 is not in expected phase: Succeeded

ocs_ci/ocs/ocp.py:651: ResourceInUnexpectedState
================ 287 deselected, 1 error in 5213.45s (1:26:53) =================
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.17.97.38', 42082)>

A full copy of my installation attempt is in: 
https://docs.google.com/document/d/1Rit4oUXoUB4WYR6t5mCx0I0Fwao7m8zraowBZsi15cg/edit?folder=0AMQa11KYc72nUk9PVA

**Comment by wusui** [comment]
Also, openshift-storage does not have any pods after this happens
(venv) [wusui@dhcp-10-17-97-38 ocs-ci]$ oc -n openshift-storage get pods
No resources found.
(venv) [wusui@dhcp-10-17-97-38 ocs-ci]$ oc get namespaces
NAME                                                    STATUS   AGE
default                                                 Active   3h40m
kube-node-lease                                         Active   3h40m
kube-public                                             Active   3h40m
kube-system                                             Active   3h40m
openshift                                               Active   3h35m
openshift-apiserver                                     Active   3h35m
openshift-apiserver-operator                            Active   3h39m
openshift-authentication                                Active   3h39m
openshift-authentication-operator                       Active   3h39m
openshift-cloud-credential-operator                     Active   3h39m
openshift-cluster-machine-approver                      Active   3h39m
openshift-cluster-node-tuning-operator                  Active   3h39m
openshift-cluster-samples-operator                      Active   3h39m
openshift-cluster-storage-operator                      Active   3h39m
openshift-cluster-version                               Active   3h40m
openshift-config                                        Active   3h40m
openshift-config-managed                                Active   3h40m
openshift-console                                       Active   3h33m
openshift-console-operator                              Active   3h33m
openshift-controller-manager                            Active   3h39m
openshift-controller-manager-operator                   Active   3h39m
openshift-dns                                           Active   3h38m
openshift-dns-operator                                  Active   3h39m
openshift-etcd                                          Active   3h40m
openshift-image-registry                                Active   3h39m
openshift-infra                                         Active   3h40m
openshift-ingress                                       Active   3h34m
openshift-ingress-operator                              Active   3h39m
openshift-insights                                      Active   3h39m
openshift-kni-infra                                     Active   3h39m
openshift-kube-apiserver                                Active   3h40m
openshift-kube-apiserver-operator                       Active   3h40m
openshift-kube-controller-manager                       Active   3h40m
openshift-kube-controller-manager-operator              Active   3h40m
openshift-kube-scheduler                                Active   3h40m
openshift-kube-scheduler-operator                       Active   3h39m
openshift-machine-api                                   Active   3h39m
openshift-machine-config-operator                       Active   3h40m
openshift-marketplace                                   Active   3h39m
openshift-monitoring                                    Active   3h39m
openshift-multus                                        Active   3h39m
openshift-network-operator                              Active   3h39m
openshift-node                                          Active   3h35m
openshift-openstack-infra                               Active   3h39m
openshift-operator-lifecycle-manager                    Active   3h39m
openshift-operators                                     Active   3h39m
openshift-sdn                                           Active   3h39m
openshift-service-ca                                    Active   3h38m
openshift-service-ca-operator                           Active   3h39m
openshift-service-catalog-apiserver-operator            Active   3h39m
openshift-service-catalog-controller-manager-operator   Active   3h39m
openshift-storage                                       Active   3h25m

**Comment by vasukulkarni** [comment]
@wusui try with this diff, I dont remember  but there was a problem with alpha channel(fresh install/upgrades)

modify ocs_ci/framework/conf/default_config.yaml to use: ocs_csv_channel: "stable-4.2"

```
diff --git a/ocs_ci/framework/conf/default_config.yaml b/ocs_ci/framework/conf/default_config.yaml
index 9316088..e2d4e6f 100644
--- a/ocs_ci/framework/conf/default_config.yaml
+++ b/ocs_ci/framework/conf/default_config.yaml
@@ -45,7 +45,7 @@ DEPLOYMENT:
   force_download_installer: True
   force_download_client: True
   # You can overwrite csv channel version by following parameter
-  # ocs_csv_channel: "alpha"
+  ocs_csv_channel: "stable-4.2"
```

**Comment by vasukulkarni** [comment]
with stable I am seeing it go in Failed state, @andrewschoen is there any issue with channel?

**Comment by wusui** [comment]
stale issue
