### ISSUE TITLE
Tier4 takes more than 3 days to complete

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1239]
See example here - https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3291/

An option would be to separate the tier4 suite to several sub-suites

**Comment by clacroix12** [comment]
Can we close this one out now? @ebenahar

**Comment by ebenahar** [comment]
@clacroix12 yes but we need to stop running tier4 as a whole
