### ISSUE TITLE
openshift-storage namespace is getting overriden even if we have user-defined namespace

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#125]
Updated custom namespace in 2 locations as below.

1. conf/ocsci/default_config.yaml ==> ROOK_CLUSTER_NAMESPACE: "rook-ceph"
2. ocs/defaults.py ==> ROOK_CLUSTER_NAMESPACE = 'rook-ceph'

After editing in above 2 places still my oc commands are generated with "openshift-storage" namespace.

This param should be overridden from one location.

Workaround: This is not a good suggestion but works for executing tests.
defaults.ROOK_CLUSTER_NAMESPACE = 'rook-ceph'  ==> in the test_case.py

`self = <tests.test_ocs_260.TestCaseOCS260 object at 0x7f7216e1f048>

    def test_run_ocs_260(self):
        """
        Test case OCS-260
    
        """
        pvc_count = 4
        pv_list = []
    
>       create_ceph_block_pool()

tests/test_ocs_260.py:400: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_ocs_260.py:103: in create_ceph_block_pool
    assert CBP.create(yaml_file=TEMP_YAML)
../../ocs-ci/ocs/ocp.py:119: in create
    return self.exec_oc_cmd(command)
../../ocs-ci/ocs/ocp.py:67: in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['oc', '-n', 'openshift-storage', '--kubeconfig', '/home/rperiyas/Documents/tools/OCS4x/auto_frame/cluster/auth/kubeconfig', 'create', ...]
kwargs = {}
r = CompletedProcess(args=['oc', '-n', 'openshift-storage', '--kubeconfig', '/home/rperiyas/Documents/tools/OCS4x/auto_fra...oes not match the namespace "openshift-storage". You must pass \'--namespace=rook-ceph\' to perform this operation.\n')

    def run_cmd(cmd, **kwargs):
        """
        Run an arbitrary command locally
    
        Args:
            cmd (str): command to run
    
        Raises:
            CommandFailed: In case the command execution fails
    
        Returns:
            (str) Decoded stdout of command
    
        """
        log.info(f"Executing command: {cmd}")
        if isinstance(cmd, str):
            cmd = shlex.split(cmd)
        r = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            **kwargs
        )
        log.debug(f"CMD output: {r.stdout.decode()}")
        if r.stderr:
            log.error(f"CMD error:: {r.stderr.decode()}")
        if r.returncode:
            raise CommandFailed(
>               f"Error during execution of command: {cmd}."
                f"\nError is {r.stderr.decode()}"
            )
E           ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'openshift-storage', '--kubeconfig', '/home/rperiyas/Documents/tools/OCS4x/auto_frame/cluster/auth/kubeconfig', 'create', '-f', 'templates/ocs-deployment/temp.yaml', '-o', 'yaml'].
E           Error is error: the namespace from the provided object "rook-ceph" does not match the namespace "openshift-storage". You must pass '--namespace=rook-ceph' to perform this operation.

../../ocs-ci/utility/utils.py:655: CommandFailed`

Version: Form May30th ocs-ci master branch

**Comment by RazTamir** [comment]
@ramkiperiy how you initialized your CBP object?

**Comment by keesturam** [comment]
This is how I use a custom namespace.
Define the following in defaults.py
`TEST_NAMESPACE = 'ocs-qe'`

Use `TEST_NAMESPACE` to initialize OCP objects.

**Comment by vasukulkarni** [comment]
Closing stale issue.
