### ISSUE TITLE
cluster path is not empty in jenkins run

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1265]
Multiple jobs failed due to existing cluster path which shouldn't happen since we are using fresh image from linchpin, we should get to the bottom of this issue

```
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3477//console

built from commit 93c78d09ed9e2badb4bf5dab708152fe6b3b6602
release image registry.svc.ci.openshift.org/ocp/release@sha256:6e9dc61f183d2eb2778cef749bcb283269f78c7a23e08fcdf452c210d93436db

ERROR                                                                    [100%]

==================================== ERRORS ====================================
______________________ ERROR at setup of test_deployment _______________________

request = <SubRequest 'cluster' for <Function test_deployment>>
log_cli_level = 'INFO'

    @pytest.fixture(scope="session", autouse=True)
    def cluster(request, log_cli_level):
        """
        This fixture initiates deployment for both OCP and OCS clusters.
        Specific platform deployment classes will handle the fine details
        of action
        """
        log.info(f"All logs located at {ocsci_log_path()}")
    
        teardown = config.RUN['cli_params']['teardown']
        deploy = config.RUN['cli_params']['deploy']
        factory = dep_factory.DeploymentFactory()
        deployer = factory.get_deployment()
    
        # Add a finalizer to teardown the cluster after test execution is finished
        if teardown:
            def cluster_teardown_finalizer():
                deployer.destroy_cluster(log_cli_level)
            request.addfinalizer(cluster_teardown_finalizer)
            log.info("Will teardown cluster because --teardown was provided")
    
        # Download client
        force_download = (
            config.RUN['cli_params'].get('deploy')
            and config.DEPLOYMENT['force_download_client']
        )
        get_openshift_client(force_download=force_download)
    
        if deploy:
            # Deploy cluster
>           deployer.deploy_cluster(log_cli_level)

tests/conftest.py:826: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/deployment/deployment.py:83: in deploy_cluster
    self.deploy_ocp(log_cli_level)
ocs_ci/deployment/vmware.py:485: in deploy_ocp
    super(VSPHEREUPI, self).deploy_ocp(log_cli_level)
ocs_ci/deployment/deployment.py:130: in deploy_ocp
    self.ocp_deployment.deploy_prereq()
ocs_ci/deployment/vmware.py:263: in deploy_prereq
    super(VSPHEREUPI.OCPDeployment, self).deploy_prereq()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.deployment.vmware.VSPHEREUPI.OCPDeployment object at 0x7f3657b7cf60>

    def deploy_prereq(self):
        """
        Perform generic prereq before calling openshift-installer
        This method performs all the basic steps necessary before invoking the
        installer
        """
        deploy = config.RUN['cli_params']['deploy']
        teardown = config.RUN['cli_params']['teardown']
        if teardown and not deploy:
            msg = f"Attempting teardown of non-accessible cluster: "
            msg += f"{self.cluster_path}"
            pytest.fail(msg)
        elif not deploy and not teardown:
            msg = "The given cluster can not be connected to: {}. ".format(
                self.cluster_path)
            msg += (
                f"Provide a valid --cluster-path or use --deploy to "
                f"deploy a new cluster"
            )
            pytest.fail(msg)
        elif not system.is_path_empty(self.cluster_path) and deploy:
            msg = "The given cluster path is not empty: {}. ".format(
                self.cluster_path)
            msg += (
                f"Provide an empty --cluster-path and --deploy to deploy "
                f"a new cluster"
            )
>           pytest.fail(msg)
E           Failed: The given cluster path is not empty: /home/jenkins/current-cluster-dir/openshift-cluster-dir. Provide an empty --cluster-path and --deploy to deploy a new cluster
```

**Comment by clacroix12** [comment]
@vasukulkarni I created a bug on our ecosystem jira board for this, I'll link this issue to it. Thanks!

**Comment by dahorak** [comment]
This happen only when destroy job of previous cluster (with the same name) didn't pass correctly and the respective Jenkins slave is not destroyed (so it uses the existing Jenkins slave with cluster path existing from previous run).

The reason is, that when the destroy cluster process fails, we don't destroy the respective Jenkins slave intentionally. It is because it is not easily possible to distinguish situation, when the destroy process fails but the cluster was properly deleted (or wasn't previously created at all) - so there are no leftovers and it is safe to delete the rest of the cluster related environment (including the Jenkins slave). And situation when the destroy cluster process fails because of some other reason (service unavailability, bug in the code, ...) and the cluster wasn't cleaned properly. If we will automatically force the deletion of Jenkins slave in the second case, we might end up in situation when we will have number of running clusters without any information about them (as the respective Jenkins slaves will be deleted). 

So as it is now, it requires manual intention - when destroy cluster job fails, check if the respective cluster doesn't exist and if not, clean up the Jenkins slave manually. If the cluster exist, cleanup the cluster firstly and then destroy the Jenkins slave (sometime it helps to rerun the destroy cluster job).

I'm definitely open for any suggestions for improvement, but I'm not sure how to balance between fully automated process with possible issues with leftover clusters and the current situation when it requires manual intervention.

**Comment by petr-balogh** [comment]
Yep, Daniel described it right. Thanks.

- We send the email when the jenkins job fail somewhere in the middle and in case the job fail in the deployment we see this subject:

```
Job 'qe-deploy-ocs-cluster' build '#3467 - jnk-ai3c33-ua' stage 'Install': FAILURE
```
But then we don't know that the job also could fail in the teardown stage.
So I suggest to also add the info about status of `Teardown` stage to the mail subject in case we fail there and we can easily see that we need to take care of it manually instead of going to the job, in console output find the link to the underlaying destroy job and watch for it's status.

- We should have an option in our job to force destroy the jenkins slave.

-  Third suggestion is to add some timestamp in the jenkins slave name and propagate this from production job to all underlaying jobs which will solve the issue partially and we will not fail second execution of job. We still need to take care about destroy of previous failed cluster manually.

**Comment by dahorak** [comment]
> Yep, Daniel described it right. Thanks.
> 
>     * We send the email when the jenkins job fail somewhere in the middle and in case the job fail in the deployment we see this subject:
> 
> 
> ```
> Job 'qe-deploy-ocs-cluster' build '#3467 - jnk-ai3c33-ua' stage 'Install': FAILURE
> ```
> 
> But then we don't know that the job also could fail in the teardown stage.
> So I suggest to also add the info about status of `Teardown` stage to the mail subject in case we fail there and we can easily see that we need to take care of it manually instead of going to the job, in console output find the link to the underlaying destroy job and watch for it's status.

What do you think about sending email directly from destroy job (in case of failure) with different subject clearly suggesting to check the particular destroy job?
Something like: `Destroy job FAILED for cluster "cluster-name"`.

>     * We should have an option in our job to force destroy the jenkins slave.

Agree.

>     * Third suggestion is to add some timestamp in the jenkins slave name and propagate this from production job to all underlaying jobs which will solve the issue partially and we will not fail second execution of job. We still need to take care about destroy of previous failed cluster manually.

This is good idea.

**Comment by petr-balogh** [comment]
> > Yep, Daniel described it right. Thanks.
> > ```
> > * We send the email when the jenkins job fail somewhere in the middle and in case the job fail in the deployment we see this subject:
> > ```
> > 
> > 
> > ```
> > Job 'qe-deploy-ocs-cluster' build '#3467 - jnk-ai3c33-ua' stage 'Install': FAILURE
> > ```
> > 
> > 
> > But then we don't know that the job also could fail in the teardown stage.
> > So I suggest to also add the info about status of `Teardown` stage to the mail subject in case we fail there and we can easily see that we need to take care of it manually instead of going to the job, in console output find the link to the underlaying destroy job and watch for it's status.
> 
> What do you think about sending email directly from destroy job (in case of failure) with different subject clearly suggesting to check the particular destroy job?
> Something like: `Destroy job FAILED for cluster "cluster-name"`.
Main reason to have this failure in the same mail is to reduce the number of mails we have. Everything is basically related to the one failed job and in my opinion it's ok to have only one email about failed job mentioning more stages where it failed.
But let's get some more opinions here: @vavuthu @shylesh @clacroix12 @dahorak .
We are the ppl who will need to analyze the failures of production jobs and cleanup the clusters which failed to be destroyed. Your input is welcomed.

I see as pros:  

- Only one email (we will not spam ocs-ci too much)
- We know directly everything is related to one specific job
- Easier implementation to just add this to existing mail submit

cons:

- we will get notified only when running/re-triggering deploy job

> 
> > ```
> > * We should have an option in our job to force destroy the jenkins slave.
> > ```
> 
> Agree.
> 
> > ```
> > * Third suggestion is to add some timestamp in the jenkins slave name and propagate this from production job to all underlaying jobs which will solve the issue partially and we will not fail second execution of job. We still need to take care about destroy of previous failed cluster manually.
> > ```
> 
> This is good idea.

**Comment by petr-balogh** [comment]
I  created 3 subtasks for the things mentioned above in the ticket opened by Coady:
https://projects.engineering.redhat.com/browse/OCSQE-174

**Comment by vavuthu** [comment]
> > > Yep, Daniel described it right. Thanks.
> > > ```
> > > * We send the email when the jenkins job fail somewhere in the middle and in case the job fail in the deployment we see this subject:
> > > ```
> > > 
> > > 
> > > ```
> > > Job 'qe-deploy-ocs-cluster' build '#3467 - jnk-ai3c33-ua' stage 'Install': FAILURE
> > > ```
> > > 
> > > 
> > > But then we don't know that the job also could fail in the teardown stage.
> > > So I suggest to also add the info about status of `Teardown` stage to the mail subject in case we fail there and we can easily see that we need to take care of it manually instead of going to the job, in console output find the link to the underlaying destroy job and watch for it's status.
> > 
> > 
> > What do you think about sending email directly from destroy job (in case of failure) with different subject clearly suggesting to check the particular destroy job?
> > Something like: `Destroy job FAILED for cluster "cluster-name"`.
> 
> Main reason to have this failure in the same mail is to reduce the number of mails we have. Everything is basically related to the one failed job and in my opinion it's ok to have only one email about failed job mentioning more stages where it failed.
> But let's get some more opinions here: @vavuthu @shylesh @clacroix12 @dahorak .
> We are the ppl who will need to analyze the failures of production jobs and cleanup the clusters which failed to be destroyed. Your input is welcomed.
> 
> I see as pros:
> 
> * Only one email (we will not spam ocs-ci too much)
> * We know directly everything is related to one specific job
> * Easier implementation to just add this to existing mail submit
> 
I like the idea of reporting the failures in stages ( like deployment, teardown etc ) which makes end user to easily identify the failure by seeing the mail. we need force option in jenkins to delete the slaves in case deployment fails which leaves the orphan slaves.

**Comment by vasukulkarni** [comment]
> Yep, Daniel described it right. Thanks.
> 
> * We send the email when the jenkins job fail somewhere in the middle and in case the job fail in the deployment we see this subject:
> 
> ```
> Job 'qe-deploy-ocs-cluster' build '#3467 - jnk-ai3c33-ua' stage 'Install': FAILURE
> ```
> 
> But then we don't know that the job also could fail in the teardown stage.
> So I suggest to also add the info about status of `Teardown` stage to the mail subject in case we fail there and we can easily see that we need to take care of it manually instead of going to the job, in console output find the link to the underlaying destroy job and watch for it's status.
> 
> * We should have an option in our job to force destroy the jenkins slave.
> * Third suggestion is to add some timestamp in the jenkins slave name and propagate this from production job to all underlaying jobs which will solve the issue partially and we will not fail second execution of job. We still need to take care about destroy of previous failed cluster manually.

I am +1 for adding timestamp to jenkins slave node and keep the jobs separate

**Comment by clacroix12** [comment]
+1 for timestamping the slaves as well. This will make sure we aren't blocked due to this issue as well as allow us to properly clean up any environments that still need to be destroyed before we delete the corresponding slave.

+1 for having all relevant information in the same email. A single email per job as long as we make it clear in the contents what the status of each stage was to help with troubleshooting.

**Comment by shylesh** [comment]
> +1 for timestamping the slaves as well. This will make sure we aren't blocked due to this issue as well as allow us to properly clean up any environments that still need to be destroyed before we delete the corresponding slave.
> 
> +1 for having all relevant information in the same email. A single email per job as long as we make it clear in the contents what the status of each stage was to help with troubleshooting.

+1 for the idea.

**Comment by dahorak** [comment]
Closing this ticket, as following ideas are already implemented:
* unique ID (build ID) in the name of jenkins slave for CI jobs ([MR!142](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/merge_requests/142))
* unique ID (build ID) in the cluster name for PR validation jobs([MR!152](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/merge_requests/152))
* report failed stage and failed destroy in email report ([MR!139](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/merge_requests/139))
