### ISSUE TITLE
Required function for add_nodes AWS,VMware UPI

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#1291]

**Comment by petr-balogh** [comment]
Opened task in our ecosystem board: https://projects.engineering.redhat.com/browse/OCSQE-184
And two subtasks, one for AWS, second for vSphere.

**Comment by ebenahar** [comment]
Needed for tests in https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py to run

**Comment by prsurve** [comment]
Already Achived
