### ISSUE TITLE
kubeconfig file is not accessible with aws upi installation 

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#1294]
When a Jenkins job is started with aws upi installation, kubeconfig file is inaccessible from the path provided. 

Looks like a sym link is created from installation path `/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/external/openshift-misc-1578897268/v3-launch-templates/functionality-testing/aos-4_2/hosts/install-dir/auth/kubeconfig` to custer directory `/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig`.

However, the install path is deleted after the installation which leaves the kubeconfig file inaccessible. The contents of `auth` need to be copied instead of using a symlink.

**Comment by vavuthu** [comment]
from the code, it looks like we are creating symlink "/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/external/openshift-misc-1578897268/v3-launch-templates/functionality-testing/aos-4_2/hosts/install-dir to "/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig".

Once installation is completed, we are deleting the "/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/external/openshift-misc-1578897268" which won't effect the actual install-dir ( /home/jenkins/current-cluster-dir/openshift-cluster-dir/ ).

> The reason you are not able to access kubeconfig is due to permission issues for "other" groups

drwxr-x--- 1 zack zack  21182 Jan 13 08:27 auth

> Need to check why its happening on few runs and not all runs.

**Comment by keesturam** [comment]
@vavuthu I haven't run tests on AWS in the recent past. Any idea if this is fixed?

**Comment by vavuthu** [comment]
This issue has been fixed and kubeconfig will be available as soon as it created.

closing this issue
