### ISSUE TITLE
Deploy of internal builds doesn't work cause of conflict with live content

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1305]
Issue described int this mail thread:  **OLM issue: Automation of OCS deployment is blocked after the GA** .

In short: If we add catalogSource with internal builds it's providing packageManifest with the same name ocs-operator which is twice in the list and our command `oc get` for specific ocs-operator name returns one of those two which make troubles in our deployment.

- So one solution is to rename packageManifest and operator with `-dev` suffix, 
- Second option is to select somehow differently the operator, for example using label as selector.
- Third one is disable the `redhat-operators` at all but I think we will have issue in the future for upgrade and local-storage which will be needed for bare-metal deployment.

**Comment by petr-balogh** [comment]
@vasukulkarni  FYI opened this issue for tracking here the discussion from mail.

**Comment by vasukulkarni** [comment]
Thanks for filing, I have third option with patch and disable, it didn't work nor does it look appropriate,  First or Second sounds like a good option (label doesn't except name so the list has to be iterated again, ex: oc get packageManifest -n openshift-marketplace -l catalog!=ocs-catalogsource  -o yaml)

**Comment by vasukulkarni** [comment]
@andrewschoen @zmc FYI
