### ISSUE TITLE
Remove retry in wait_for_state function.

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1309]
Info from mail with subject: `Q: why does 'get csv' taking so long to fail?`

Did some investigation here:

the retry in wait_for_status was introduced here: [1] by Vijay when working on vSphere UPI deployment.

This changed internal logic as this decorator retries the whole function 4 times again. So this means if timeout here [2] is set to 720 sec (12min)

Which means that 4x12 min = 48 mins which is not expected behavior here.

Opening issue here [3]

[1] https://github.com/red-hat-storage/ocs-ci/commit/ebe39226c2c9afddbfffad57ba59f8ef3dba71a5#diff-8c36b5b435f62a7f867c127baf95b2bfR62
[2] https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L391

On Jan 15, 2020, at 1:49 PM, Yaniv Kaul <ykaul@redhat.com> wrote:

Hi,

I'm looking into the tier 1 tests we run on CI, and I'm trying to both ensure they are fast and successful, so this is going to be the first of many 'why' emails...

In this one, I'm wondering why we do not fail after the 10m timeout as we should:

From https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/OCS%204.X%20CI%20CD/job/ocs-ci/280/consoleFull :

18:45:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig cluster/auth/kubeconfig get csv ocs-operator.v4.2.0 -n openshift-storage -o yaml
18:45:27 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: ocs-operator.v4.2.0, Error: Error during execution of command: oc -n openshift-storage --kubeconfig cluster/auth/kubeconfig get csv ocs-operator.v4.2.0 -n openshift-storage -o yaml.
Error is Error from server (NotFound): clusterserviceversions.operators.coreos.com "ocs-operator.v4.2.0" not found

...

19:33:45 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: ocs-operator.v4.2.0, Error: Error during execution of command: oc -n openshift-storage --kubeconfig cluster/auth/kubeconfig get csv ocs-operator.v4.2.0 -n openshift-storage -o yaml.
Error is Error from server (NotFound): clusterserviceversions.operators.coreos.com "ocs-operator.v4.2.0" not found

19:33:45 - MainThread - ocs_ci.ocs.ocp - ERROR - Number of attempts to get resource reached!
19:33:45 - MainThread - ocs_ci.ocs.ocp - INFO - Cannot find resource object ocs-operator.v4.2.0

**Comment by vavuthu** [comment]
Closing this issue and it is 1 year old. we had many improvements in deployment over these years.

Please feel free to re-open if needed.
