### ISSUE TITLE
Cleanup logic in get_registry_pod_obj

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1326]
After checking the logic in this method during review of #1308 I wanted to clean this function up a bit since it isn't very clean.

Current function:
```python
def get_registry_pod_obj():
    ...
    wait_time = 10
    for iteration in range(30):
        pod_data = pod.get_pods_having_label(
            label='docker-registry=default', namespace=constants.OPENSHIFT_IMAGE_REGISTRY_NAMESPACE
        )
        pod_obj = [pod.Pod(**data) for data in pod_data]
        if len(pod_obj) == 1:
            break
        elif len(pod_obj) == 0:
            raise UnexpectedBehaviour("Image-registry pod not present")
        elif iteration == 18:  # 18*10 = 180 secs.
            raise UnexpectedBehaviour("Waited for 3 mins Image-registry pod is not in Running state")
        else:
            logger.info(f"Waiting for {wait_time} seconds for registry pod to be up - iteration {iteration}")
            time.sleep(wait_time)
    return pod_obj
```
As you can see we initially loop for 30 iterations and then end up stopping the iteration after 18 (180 seconds). We are also essentially re-implementing retry logic here when we have the [retry decorator](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/retry.py#L8) that we can use to easily clean this code up.

Example fix:
```python
@retry(UnexpectedBehaviour, tries=18, delay=10, backoff=1)
def get_registry_pod_obj():
    pod_data = pod.get_pods_having_label(
        label='docker-registry=default',
        namespace=constants.OPENSHIFT_IMAGE_REGISTRY_NAMESPACE
    )
    pod_obj = [pod.Pod(**data) for data in pod_data]
    if len(pod_obj) != 1:
        raise UnexpectedBehaviour("Old registry pod not fully terminated")
    return pod_obj
```

This example might not be perfect as it does change the logic slightly(we will retry even if the pod_obj is length 0 instead of immediately raising an error), but this is just to show how we can cut down on unnecessary code that is logically flawed in the first place.

**Comment by vasukulkarni** [comment]
👍
