### ISSUE TITLE
Attempt to run tests fails on missing self.data['status']

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1338]
I'm trying to run particular test with already installed cluster, on ocs-ci 804c332f9039ffb3752627cdb012581db092d8e6:

```
(venv) [ocsqe@localhost ocs-ci]$ run-ci --cluster-path ~/data/cluster-2020-01-13.1 tests/manage/monitoring/test_workload_fixture.py -vvv
Collecting Cluster versions
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/_pytest/main.py", line 192, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/_pytest/config/__init__.py", line 778, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 167, in pytest_configure
INTERNALERROR>     namespace=ocsci_config.ENV_DATA['cluster_namespace']
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/ocs_ci/ocs/resources/ocs.py", line 171, in get_version_info
INTERNALERROR>     csv_name = package_manifest.get_current_csv()
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/ocs_ci/ocs/resources/packagemanifest.py", line 91, in get_current_csv
INTERNALERROR>     channel = channel if channel else self.get_default_channel()
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/ocs_ci/utility/retry.py", line 25, in f_retry
INTERNALERROR>     return f(*args, **kwargs)
INTERNALERROR>   File "/home/ocsqe/projects/ocs-ci/ocs_ci/ocs/resources/packagemanifest.py", line 61, in get_default_channel
INTERNALERROR>     return self.data['status']['defaultChannel']
INTERNALERROR> KeyError: 'status'
```

But it fails during `get_default_channel()` on missing `data['status']` in `PackageManifest` instance.

**Comment by mbukatov** [comment]
This only happens when a cluster installed before a change from last Friday is used to run recent test code (more recent than the change from last Friday).

**Comment by mbukatov** [comment]
@wusui Provide ocs-ci commit you use and type of deployment.

**Comment by wusui** [comment]
The problem I have is with a VMWare deployment on my branch.  the last common commit that I have is: 91fc439336ea293fd626631487ca9cd6deb80dbe from Jan 24.

**Comment by mbukatov** [comment]
I haven't noticed this problem with vmware cluster I installed (via Jenkins) on last Fri, trying to run tests with ocs-ci fd8a2665efff8bf3521936f3cf1bbcc11369b326 (from Tue Feb 4).

**Comment by petr-balogh** [comment]
The issue is that in OCP 4.3 they changed something and now we are not seeing 2 packageManifests of ocs-operator from two different sources.

I have opened bug here:  https://bugzilla.redhat.com/show_bug.cgi?id=1802089

Also have mail thread: http://post-office.corp.redhat.com/archives/aos-devel/2020-February/msg00175.html

Actually do not know what changed in OCP and how to process with this change.

WA for this can be disable Red Hat Operator source as suggested by Kevin:

https://github.com/operator-framework/olm-book/blob/master/docs/openshift/operator-marketplace.md#configuration

Essentially you can just set the default shipped operator source for redhat-operators to disabled via the config object:

```yaml
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  sources:
  - name: "redhat-operators"
    disabled: true
```
So if you create file with content mentioned above and run `oc apply -f file.yaml`
It should disable the Red Hat Operators and shouldn't conflict with internal packageManifest.

**Comment by mbukatov** [comment]
ocs-ci part of the problem fixed via https://github.com/red-hat-storage/ocs-ci/pull/1475, OCP/OCS part of the problem tacked via bz 1802089
