### ISSUE TITLE
Build ID is shown as (BUILD ID: rc ...) in mail subject.

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1365]
I guess we will have to update the mechanism how to report the version here.

1) For live deployment we will need to report only 4.2.0 or 4.2.1 maybe with suffix (-live).  I think that we currently depend on catalog source which is not actually added for live content so if we depend on it we should not.

2) The tag we can use is like  latest-4.2 which is the default one. Before we used tag like 4.2-rc1 or 4.2.1-rc.  So if we used some kind of splitting string based on `-` it cannot depend on that and we should just report whole we are using.

**Comment by shylesh** [comment]
Fixed by https://github.com/red-hat-storage/ocs-ci/pull/1471. I forgot to mention this issue id in PR hence closing this manually.
