### ISSUE TITLE
Add tag to ocs-must-gather image url

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1376]
Since we no longer single `latest` tag, but multiple (eg. `latest-4.2`, `latest-4.3`, ...), we need to update our must gather functionality accordingly.

Right now, I see that sheer url without any tag is used:

```
conf/ocsci/upstream_config.yaml:  ocs_must_gather_image: "quay.io/ocs-dev/ocs-must-gather"
ocs_ci/framework/conf/default_config.yaml:  ocs_must_gather_image: "quay.io/rhceph-dev/ocs-must-gather"
```

Which is prone to failing like this:

```
error: gather did not start for pod must-gather-hv2pl: unable to pull image: ErrImagePull: rpc error: code = Unknown desc = Error reading manifest latest in quay.io/rhceph-dev/ocs-must-gather: unknown: Tag latest was deleted or has expired. To pull, revive via time machine 
```

Since there is no `latest` tag.

ocs-ci version: c8f8ae98

**Comment by petr-balogh** [comment]
@clacroix12 can you send now quick fix please to cover with latest-4.2? @shylesh this will need to be covered then in your PR for 4.3. Thanks
