### ISSUE TITLE
ClusterExp-Tier4-CommonFunctions-BackgroundOps: Run pgsql throughout the test

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#1390]

**Comment by nehaberry** [comment]
Same functionality will be needed for Upgrade tests. So can we have them as some modules which can be called in any execution - tier4, upgrade etc ?

**Comment by nehaberry** [comment]
Also, currently PGSQL is in test_pgsql.py , can we have the logic moved to helpers ?

IMO, we could have a separate helpers for workloads wherein we can have PGSQL, AMQ, CouchBase, etc.

@keesturam @tiffanyn108  please suggest

**Comment by lukaszachy** [comment]
I apologize, but I don't have capacity to work on this.
