### ISSUE TITLE
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/helpers.py#L164 needs update

### ISSUE THREAD

**Issue by shreekarSS** [red-hat-storage/ocs-ci#1399]
pod_dict_path will be None if user does not specify pod dict path while calling the create_pod().  if pod_dict_path == constants.FEDORA_DC_YAML:
cab be updated with  if pod_dict == constants.FEDORA_DC_YAML: where pod_dict gets loaded with pod dict path if pod_dict_path is not specified

**Comment by gklein** [comment]
I guess the best practice for this case would be to use a [sentinel value](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html#best-practice) and initial a default value for this dictionary when it is set to `None`.

Would it solve this problem?
