### ISSUE TITLE
Deployments to vsphere stuck after initializing terraform work directory

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1400]
Multiple vsphere deployments have become stuck after initializing the terraform work directory. Jobs stuck at this point will remain here until aborted or until the jenkins slave is shut down. The nodes that have been brought up do not appear to be in a running state / created successfully by terraform so they will need to be cleaned up manually through the vsphere console. I have experienced this myself on multiple different datacenters so I know the issue isn't isolated to one. I am still unsure if it is a vsphere issue or a jenkins slave issue.

Logs while job is stuck:
```
18:09:45 - MainThread - ocs_ci.deployment.terraform - INFO - Initializing terraform work directory
18:09:45 - MainThread - ocs_ci.utility.utils - INFO - Executing command: terraform init /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/
18:10:04 - MainThread - ocs_ci.utility.utils - INFO - Executing command: terraform apply '-var-file=/home/jenkins/current-cluster-dir/openshift-cluster-dir/terraform_data/terraform.tfvars' -auto-approve '/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/'
```

After shutting down the jenkins slave:
```
Cannot contact temp-slave-jnk-pr1377-b976: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on temp-slave-jnk-pr1377-b976 failed. The channel is closing down or has closed down
```

Jenkins job: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/4128/console

**Comment by vavuthu** [comment]
This might be issue with slow hardware. I have seen this issue in DC7, and DC10 where its not able to clone the template.  Those are very old processors. DC7,DC8 and DC9 are having same processors.

**Comment by vavuthu** [comment]
This issue has been resolved in updated code.

Closing this issue. Please feel free to re-open if needd
