### ISSUE TITLE
move out the code to create/configure logging from 'test_openshift-logging.py' so other tests can call and configure logging

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#1415]
moving the code to create/configure logging from 'test_openshift-logging.py' to ocs_ci/utility/deployment_openshift_logging will help in calling this function from other tests which need logging to be configured as part of entry criteria.

**Comment by Shrivaibavi** [comment]
This issue is addressed in #1558 and got merged. Hence closing
