### ISSUE TITLE
must-gather failing for 4.2

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1445]
@clacroix12 Actually I see issue with 4.2 as we are using RC build and there is no such tag propagated to must-gather image:  https://quay.io/repository/rhceph-dev/ocs-must-gather?tag=latest&tab=tags
```
dir/openshift-cluster-dir/auth/kubeconfig adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:4.2-rc --dest-dir=/home/jenkins/current-cluster-dir/logs/failed_testcase_ocs_logs_1581068201/deployment_ocs_logs/ocs_must_gather.
Error is error: gather did not start for pod must-gather-7zd26: unable to pull image: ErrImagePull: rpc error: code = Unknown desc = Error reading manifest 4.2-rc in quay.io/rhceph-dev/ocs-must-gather: manifest unknown: manifest unknown
```

**Comment by petr-balogh** [comment]
For now it will be fixed if we will fix this issue: #1446 but long term we should ask engineering to propagate our default latest tag to other images or at least to must-gather. Or we will have to have defined special tag for must-gather

**Comment by mbukatov** [comment]
I run into this today, using `OCP_VERSION=4.2-ga`, `OCS_VERSION=4.2`.

**Comment by petr-balogh** [comment]
Oh, I forgot about this. 
Will need to fix that. Adding to my todo list and will fix.
