### ISSUE TITLE
Tier1 Improvements

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1453]
In order to achieve both shorter tier1 running time and a proper test suite to be provided to different engineering teams (OCS, Ceph, OCP), we'd like to improve our tier1 efficiency.
@hnallurv, @keesturam and I had a meeting about this and we have prepared [this list](https://docs.google.com/spreadsheets/d/1_SYAL66lsKItp2U5Om56GiusVS-1TMz3lsa8PvtkrD0/edit?usp=sharing) of tier1 tests that need attention.

The following needs to be done:

- Improve tier1 suite according to the spreadsheet mentioned above
- Provide engineering with our tier1 once it is improved and disable acceptance suite in its current form
- Need to follow up with a story like test for a new form of acceptance suite (see https://github.com/red-hat-storage/ocs-ci/issues/1244 and https://github.com/red-hat-storage/ocs-ci/pull/1317 as a reference)

**Comment by vasukulkarni** [comment]
My biggest concern is Tier1 adds lot of instability for DevCI, the mark name can be teir1 or acceptance and it shouldn't really matter much, we can add/remove more stable tests as acceptance and also parallely fine tune tier1 for QE purpose.
