### ISSUE TITLE
Run oc describe and report results when wait for reaching k8s object state timeouts

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1473]
To provide evidence eg. for BZ  1802186, where I see:

```
2020-02-12 12:10:34,237 - INFO - ocs_ci.ocs.ocp.wait_for_resource.501 - status of  at column STATUS - item(s) were ['Terminating', 'ContainerCreating'], but we were waiting for all 3 of them to be Running
2020-02-12 12:10:34,238 - ERROR - ocs_ci.ocs.ocp.wait_for_resource.505 - timeout expired: Timed Out: (600,)
2020-02-12 12:10:34,238 - ERROR - ocs_ci.ocs.ocp.wait_for_resource.507 - Wait for Pod resource  at column STATUS to reach desired condition Running failed, last actual status was ['Terminating', 'ContainerCreating']
```

But to debug it properly, I need information provided by `oc describe` at the time of the timeout.

**Comment by gklein** [comment]
> To provide evidence eg. for BZ 1802186, where I see:
> 
> ```
> 2020-02-12 12:10:34,237 - INFO - ocs_ci.ocs.ocp.wait_for_resource.501 - status of  at column STATUS - item(s) were ['Terminating', 'ContainerCreating'], but we were waiting for all 3 of them to be Running
> 2020-02-12 12:10:34,238 - ERROR - ocs_ci.ocs.ocp.wait_for_resource.505 - timeout expired: Timed Out: (600,)
> 2020-02-12 12:10:34,238 - ERROR - ocs_ci.ocs.ocp.wait_for_resource.507 - Wait for Pod resource  at column STATUS to reach desired condition Running failed, last actual status was ['Terminating', 'ContainerCreating']
> ```
> 
> But to debug it properly, I need information provided by `oc describe` at the time of the timeout.

This can be implemented here: https://github.com/red-hat-storage/ocs-ci/blob/f3490151150b85a9570621acdd072d02f76dc7fc/ocs_ci/ocs/ocp.py#L504

From the BZ I see it needs the output of `oc describe pod <canary pod name stuck>`

Is there any easy way to figure out the `<canary pod name stuck>` ?

**Comment by mbukatov** [comment]
We could try to run `oc describe` on pods the function is waiting for.

**Comment by mbukatov** [comment]
> Is there any easy way to figure out the <canary pod name stuck>?

I see that the wait loop is running `self.get()` based on resource_name, selector and namespace. Running `self.describe()` in the same way should be enough to get the desired result. See https://github.com/red-hat-storage/ocs-ci/pull/1893 with proposed fix.
