### ISSUE TITLE
the "test_openshift-logging.py" fails on both OCS 4.2 and 4.3

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#1474]
the test fails with following message:
E           yaml.composer.ComposerError: expected a single document in the stream
E             in "<unicode string>", line 1, column 1:
E               apiVersion: rbac.authorization.k ... 
E               ^
E           but found another document
E             in "<unicode string>", line 21, column 1:
E               ---
E               ^
venv/lib/python3.7/site-packages/yaml/composer.py:43: ComposerError

same test was successfully running on OCS 4.2  on OCP 4.2.

More details can be found here: http://pastebin.test.redhat.com/835856

Srivaibhavi is taking a look at this now.

**Comment by Shrivaibavi** [comment]
@hnallurv I tried the same script with just a change in default_config.yaml in the following parameter "logging-version: 4.3" and ran the test, I was successfully able to create logging in OCP 4.3 and OCS 4.3.
The vmware setup was pretty slow, other than that I did not face any issues, Can you please retry ?
```
 oc get pods -n openshift-logging                                                                                                                        localhost.localdomain: Thu Feb 13 20:42:01 2020

NAME                                            READY   STATUS    RESTARTS   AGE
cluster-logging-operator-5456f9fbc5-bdzbs	1/1     Running   0          16m
elasticsearch-cdm-vqbotbt3-1-58b7f4db8-vjfhh    2/2     Running   0          2m4s
elasticsearch-cdm-vqbotbt3-2-76fdf5dbdf-l42px   2/2     Running   0          91s
elasticsearch-cdm-vqbotbt3-3-d879f86c7-4ftl8    2/2     Running   0          88s
fluentd-f7r2q                                   1/1     Running   0          16m
fluentd-fgjk7                                   1/1     Running   0          16m
fluentd-h7mrq                                   1/1     Running   0          16m
fluentd-l7z2q                                   1/1     Running   0          16m
fluentd-r9pzw                                   1/1     Running   0          16m
fluentd-rbn59                                   1/1     Running   0          16m
kibana-d6d5668c5-4bfwr                          2/2     Running   1          16m```


I tried installing logging in the setup shared by harish. 

We can keep this issue open, @hnallurv if you still face any issue, Please update the same issue. Make sure to run the tests in clean env and do a git rebase once.

**Comment by hnallurv** [comment]
This issue is hit with recently 'git clone'd versions also.

**Comment by Shrivaibavi** [comment]
I will update my findings here

Issue:
eo-rbac.yaml has multi document with separated by ---, When create() function internally uses exec_oc_cmd() that uses yaml.safe_load() it cannot load output yaml having multi document. I observed that creation of rbac is success but when loading output it fails. Initially it was working fine not sure what recent changes caused this issue.

Temporary fix:
If we want we can fix it temporarily by splitting eo-rbac.yaml into 2 document and run it, I can send a PR for it. It works I tested. But what changed internally I am not sure.
(or)
instead we can change function yaml.safe_load() into yaml.load_all() to handle multiple document, I am aware we already have a function load_yaml() in utility.templating. 

@petr-balogh @vasukulkarni Can you please have a look at this and let me if i had to do something from my side.

**Comment by Shrivaibavi** [comment]
Failed logs : http://pastebin.test.redhat.com/836127

**Comment by Shrivaibavi** [comment]
Fxed via PR https://github.com/red-hat-storage/ocs-ci/pull/1531
