### ISSUE TITLE
Add pre-commit support in order to speed up the development feedback loop 

### ISSUE THREAD

**Issue by gklein** [red-hat-storage/ocs-ci#1487]
Currently ocs-ci implement several post-commit checks per PR:
-  [ Developer Certificate of Origin (DCO)](https://github.com/apps/dco) 
-  [Travis CI ](https://travis-ci.org/red-hat-storage/ocs-ci/)which checks for flake8 compatibility

Problem is that all checks are done post-commit, and in many cases require re-commiting in order to fix small problems.

Using [pre-commit ](https://pre-commit.com/) it is possible to enforce a set of common rules which will be checked locally, help speed up the feedback loop and prevent wasted Github/Travis-CI check cycles.

**Comment by gklein** [comment]
First configuration is provided with #1483 , It is covering:
1. Prevent any commit to the repo when it is not signed off
2. Check to flake8 compliance and report any errors 
3. [check-docstring-first](https://github.com/pre-commit/pre-commit-hooks#check-docstring-first)
4. [check-json](https://github.com/pre-commit/pre-commit-hooks#check-json)
5. [check-yaml](https://github.com/pre-commit/pre-commit-hooks#check-yaml)
6. [debug-statements](https://github.com/pre-commit/pre-commit-hooks#debug-statements)
7. [end-of-file-fixer](https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer)
8. [trailing-whitespace ](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace)

As soon as it is merged, here is how to use it:

`pip3 install -r requirements-dev.txt`

From the ocs-ci local git repo:
`pre-commit install --hook-type pre-commit --hook-type commit-msg`

This will install pre-commit and the relevant git hooks which will enforce all rules locally before committing.

**Comment by gklein** [comment]
Fixes #1483

**Comment by clacroix12** [comment]
Is there additional work that #1483 didn't cover or can this be closed out?
