### ISSUE TITLE
AWS cleanup script

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#1490]
The AWS cleanup script should have the capability to do the following:
- [x] Remove instances after X hours
- [x] Ignore instances by name prefix
- [x] Avoid deleting instances from unneeded regions 
- [x] treat different prefixes with different uptime hours - with a dictionary of prefixes 
   * a prefix of 'lgvy' for longevity, will remove the instances after 48 hours
   * a prefix of 'dnd' for Do Not Delete, will completely ignore for deletion
   * a prefix for 'scl' for scale will delete after 36 hours 
.... and so on
- [ ] Ability to delete leftovers of resources like volumes and snapshots that are not associated to a cluster
- [ ] Add aws-cleanup usage to OCS CI docs

**Comment by vasukulkarni** [comment]
I think we should not delete longevity and scale suites as well, they can take more time and it would be costly to delete them halfway.

**Comment by ebenahar** [comment]
AWS cleanup addition was done in https://github.com/red-hat-storage/ocs-ci/pull/1458 and  https://github.com/red-hat-storage/ocs-ci/pull/1467

PR https://github.com/red-hat-storage/ocs-ci/pull/1481 will enable the deletion of spared clusters after a larger amount of hours.

**Comment by RazTamir** [comment]
> I think we should not delete longevity and scale suites as well, they can take more time and it would be costly to delete them halfway.

I agree. 
To ensure they will get deleted eventually, maybe we can set the longevity runtime to the maximum time it is currently running + an extra few hours

**Comment by ebenahar** [comment]
Updated https://github.com/red-hat-storage/ocs-ci/pull/1481 to handle treat different prefixes with different uptime hours - with a dictionary of prefixes

**Comment by clacroix12** [comment]
@ebenahar do we have any docs on usage for `aws-cleanup` other than what is in `aws-cleanup --help`? I'm specifically looking for what to expect as far as output goes. What log files are generated and where are they placed?

**Comment by ebenahar** [comment]
@clacroix12 right. Added this to the check list above

**Comment by clacroix12** [comment]
@ebenahar I was going to open another issue but I figure it might just be worth to add to this list since we are already tracking it. It would be useful to convert the interactive prompt for the prefixes to spare into a CLI argument. This way we can easily provide a value from jenkins as well as not making automation of this command difficult due to interactive prompts.
