### ISSUE TITLE
Registry test modifies the user, which leads to other user permissions to readonly mode

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#1547]
Registry [test case](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/e2e/registry/test_registry_image_push_pull.py) execution creates user and adds roles to the user, during this operation other users permissions becomes read_only and they are not able to perform any write operation.

Observed this problem in cluster while executing [PR](https://github.com/red-hat-storage/ocs-ci/pull/1508) after above mentioned registry testcase.

**Comment by RazTamir** [comment]
Hi @ramkiperiy, @tiffanyn108, could you please explore other options rather than remove the test?
This is the only registry test iirc and removing it will remove our confidence around this area. 
I'll be happy to help if you want me to

**Comment by ramkiperiy** [comment]
@RazTamir Initially we automated TC[2] now we have an alternate test case[1] to cover this.

The steps we followed in TC [2] is similar to OCS 3.x, in order to push an image to registry we need some user roles to be added and these roles creates issue in next TC execution.
TC [1] we are achieving the same but in different way without changing the user role using "oc image-build", also this tc does create a pod using that image.

[1]https://github.com/red-hat-storage/ocs-ci/blob/master/tests/e2e/registry/test_pod_from_registry.py
[2]https://github.com/red-hat-storage/ocs-ci/blob/master/tests/e2e/registry/test_registry_image_push_pull.py

@keesturam ^^

**Comment by RazTamir** [comment]
ACK!
Wasn't aware of it.
Thanks for clarfy

**Comment by ramkiperiy** [comment]
Moving this issue closure since the PR is already merged.
