### ISSUE TITLE
Wrapper run-ci doesn't work as described in the docs

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#155]
Since request https://github.com/red-hat-storage/ocs-ci/pull/142/files the docs notes that it should be possible to run the pytest wrapper via comman line tool `run-ci` (which is created via setuptools during pip based installation in a virtual env).

But this doesn't work, because the module `run_ocsci.py` is not installed anywhere (via setuptools), so the `run-ci` wrapper wont work:

```
(venv) [ocsqe@localhost ocs-ci]$ run-ci -h
Traceback (most recent call last):
  File "/home/ocsqe/projects/ocs-ci/venv/bin/run-ci", line 11, in <module>
    load_entry_point('ocs-ci==0.1', 'console_scripts', 'run-ci')()
  File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ocsqe/projects/ocs-ci/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'run_ocsci'
```

While the explicit run of the module works as expected:

```
$ python -m run_ocsci -m deployment --cluster-name mbukatov-ocs-deployment tests
```

Resolution:

 - [ ] revert https://github.com/red-hat-storage/ocs-ci/pull/142/files
 - [ ] make the wrapper executable directly without setuptools (simple and explicit) or make it installed via setuptools

**Comment by vasukulkarni** [comment]
@mbukatov if you are seeing sdist issue then go ahead and fix it, but saying entry-point doesn't work is incorrect, I have been using it for quite some time now.  have you recreated venv and tried?

**Comment by mbukatov** [comment]
> @mbukatov if you are seeing sdist issue then go ahead and fix it, but saying entry-point doesn't work is incorrect, I have been using it for quite some time now. have you recreated venv and tried?

@dahorak also notes that it works for him. But I have no idea why the module is visible for him and in my case, the module is not visible (which is something I would actually expect to happen). And yes, I recreated venv.

**Comment by clacroix12** [comment]
@mbukatov is this still a valid issue?

**Comment by mbukatov** [comment]
Ok, so this is caused by few things:

 * few hacks in our codebase
 * me supposing that non editable installation will work

When we are done with restructure of the repo, it will be possible to:

* drop `run_ocsci.py` from root repo, moving the code into `main` module entirely
* drop `setenv = PYTHONPATH=.` from tox.ini
