### ISSUE TITLE
Rhel deployment is blocked on key error 4.3.1 for repos

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1561]
```
        ))
>       self.ocp_repo = constants.REPO_MAPPING[version]
E       KeyError: '4.3.1'

ocs_ci/deployment/install_ocp_on_rhel.py:77: KeyError
```
Job: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/5033//console

**Comment by shylesh** [comment]
I have a PR here , https://github.com/red-hat-storage/ocs-ci/pull/1503 to dynamically get the version. 
I left this as we were facing VMware UPI issues, I will run a deployment test now and if it works then we can get rid of constatns
