### ISSUE TITLE
tox fails due to ImportError: cannot import name 'ReportPortalServiceAsync'

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#1573]
Observing tox failure on newly cloned files from ocs-ci, due to this travis-ci fails in PR.

ImportError: cannot import name 'ReportPortalServiceAsync'
ERROR: InvocationError for command /home/rperiyas/Documents/tools/OCS4x/my_changes/update/pg_balancer/test/ocs-ci/.tox/py36/bin/py.test --ignore=tests -c pytest_unittests.ini --cov=ocs_ci (exited with code 1)

Complete logs present in pastebin http://pastebin.test.redhat.com/841379

**Comment by petr-balogh** [comment]
New client version was pushed about 1hour ago which broke our import.
https://pypi.org/project/reportportal-client/#history
