### ISSUE TITLE
When running any test case, test case fails due to AssertionError: Couldn't load URL

### ISSUE THREAD

**Issue by Akarsha-rai** [red-hat-storage/ocs-ci#1583]
While running any test case we are facing the following error

`AssertionError: Couldn't load URL: https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.3.0-0.nightly/latest content! Status: 503.`

**Comment by petr-balogh** [comment]
This is not a bug but problem of the server openshift-release.svc.ci.openshift.org that it was down from some reason.

For such issues I suggest to contact aos-devel mailing list.  Anyway I wrote to Vijay's fix how we can prevent this if we already have the client downloaded. So it can be improvement in our infra.
