### ISSUE TITLE
OCP must gather is being collected twice following a failed TC

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1587]
For some reason, there are 2 calls to must gather at the end of a failed TC:

18:23:45 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig cluster/auth/kubeconfig adm must-gather --image=quay.io/openshift/origin-must-gather --dest-dir=/home/jenkins-build/workspace/ocs-ci/logs/failed_testcase_ocs_logs_1583275322/test_data_reduction_ocs_logs/ocp_must_gather
18:32:45 - MainThread - ocs_ci.ocs.utils - INFO - Must gather image: quay.io/openshift/origin-must-gather will be used.
18:32:45 - MainThread - ocs_ci.ocs.utils - INFO - OCS logs will be placed in location /home/jenkins-build/workspace/ocs-ci/logs/failed_testcase_ocs_logs_1583275322/test_data_reduction_ocs_logs/ocp_must_gather
18:32:45 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig cluster/auth/kubeconfig adm must-gather --image=quay.io/openshift/origin-must-gather --dest-dir=/home/jenkins-build/workspace/ocs-ci/logs/failed_testcase_ocs_logs_1583275322/test_data_reduction_ocs_logs/ocp_must_gather -- /usr/bin/gather_service_logs worker

**Comment by vavuthu** [comment]
@ebenahar could you provide the link to jenkins job if possible. I would like to see in which stage its failed.

**Comment by ebenahar** [comment]
@vavuthu I don't see this happening anymore, closing
