### ISSUE TITLE
During deployment, log version of ocs/rook images

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#160]
During deployment, log version of ocs/rook images. It would be useful to include hash along with tag name for each image. Mentioning pull url would be also useful.

References:

 * https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/

**Comment by vasukulkarni** [comment]
Mind taking this up, I see you have something in your email?

**Comment by mbukatov** [comment]
Ack, I'm going to propose a PR for this.

**Comment by mbukatov** [comment]
Addressed by:

- https://github.com/red-hat-storage/ocs-ci/pull/185
- https://github.com/red-hat-storage/ocs-ci/pull/1099
