### ISSUE TITLE
Google API error while updating spreadsheet with 100 writes within 100 sec

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#1620]
Error Message: "Quota exceeded for quota group 'WriteGroup' and limit 'Write requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer

Scenario: Capture 1500 PVC creation time, where you need to add more than 1500 PVC name and creation time data to the google spread sheet, due to above error can't proceed.

**Comment by RazTamir** [comment]
Hi Ram,

That's the limit we have. 
I'm afraid this can't be increased at this point. 
Do we have alternatives for rather than Google spreadsheet?

**Comment by ramkiperiy** [comment]
Yes, for now am dumping data to *.csv file and data can be copied from .csv file, so it's not blocker. 
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/e2e/test_pvc_creation_deletion_scale.py#L96

**Comment by keesturam** [comment]
@ramkiperiy I guess this issue needs to be closed as we are exploring other options?
