### ISSUE TITLE
Function run_cmd() is leaking secrets via stdout debug logs.

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1623]
As noted by @petr-balogh in https://github.com/red-hat-storage/ocs-ci/pull/1611#discussion_r389962628

**Comment by petr-balogh** [comment]
Thanks, not sure why we didn't masked it before maybe was missed.
Maybe for debugging purpose it's worth to have option in our config under REPORTING section something like debug_secrets and update the function for mask secrets to check if this config value is enabled and if so it will ignore the masking secrets at all. WDYT @mbukatov ?

**Comment by mbukatov** [comment]
I proposed a quick fix in  #1626.

Related to a knob to disable secret masking:
- it's worth considering, that said let's check what kind of secrets are being dropped to see if it's worth it
- the knob you describe would be better called something like "disable mask secrets" to better describe what it does
- in jenkins, we would need to do a double checking to prevent having this enabled by mistake in some PR validation job or other CI run

**Comment by mbukatov** [comment]
@MeridianExplorer I see that all usage of secret masking is done related to MCG so far, would a know as explained by @petr-balogh be useful?

**Comment by MeridianExplorer** [comment]
Hi Martin, the knob is great. Thanks for taking care of it.
