### ISSUE TITLE
defaults TEMPLATE_DIR will fail to locate CSI templates

### ISSUE THREAD

**Issue by PrasadDesala** [red-hat-storage/ocs-ci#168]
defaults.py --> TEMPLATE_DIR = os.path.join(TOP_DIR, "templates/ocs-deployment/")

TEMPLATE_DIR is fetching the yamls under "templates/ocs-deplyment", but when we try to call CSI yaml it will fail to find the yaml because  CSI related yamls are placed under "templates/CSI"

Either CSI yamls should be moved under "templates/ocs-deployment/" or TEMPLATE_DIR should be corrected.

**Comment by keesturam** [comment]
@PrasadDesala https://github.com/red-hat-storage/ocs-ci/pull/166 should solve this issue.

**Comment by PrasadDesala** [comment]
> @PrasadDesala #166 should solve this issue.

I think this PR may not solve this issue. Even in this PR, TEMPLATE_DIR is pointing to "templates/ocs-deployment". 
So, CSI yaml when called will fail to locate as it will try to find in templates/ocs-deployment/<CSI>.yaml but the actual CSI yaml is present in templates/CSI

**Comment by vavuthu** [comment]
> s fetching the yamls under "templates/ocs-deplyment", but when we try to call CSI yaml it will fail to find the yaml because CSI related yamls are placed under "tem

If you want to read the yaml files under CSI folder, please add
TEMPLATE_DIR_RBD = os.path.join(TOP_DIR, "templates/CSI/rbd/")
and use like below
```
SC_DICT = load_yaml_to_dict(
    os.path.join(
        TEMPLATE_DIR_RBD, "storageclass.yaml"
    )
)
```

**Comment by vavuthu** [comment]
I have requested to add TEMPLATE_DIR_RBD and TEMPLATE_DIR_CEPHFS in PR #166

**Comment by vasukulkarni** [comment]
I am handling all the template stuff here: https://github.com/red-hat-storage/ocs-ci/pull/164
