### ISSUE TITLE
Modify smallfile workload test to validate against a benchmark 

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#1681]
All smallfile workloads that are run against ripsaw generate perf numbers but there is no validation whether the performance has improved or regressed. Make changes to validate the performance.

**Comment by keesturam** [comment]
@Avilir I believe with the recent developments around smallfile workload, this issue is addressed. can you please confirm the same?

**Comment by Avilir** [comment]
@keesturam , This is almost done. we have validation of the test results, but we don't have validation with comparison to previous build.
