### ISSUE TITLE
Resource Leftovers fails on resources of openshift-kube-apiserver

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1684]
When checking CI results, I see that some tests are failing seemingly randomly on errors like:

```
E           ocs_ci.ocs.exceptions.ResourceLeftoversException: 
E           There are leftovers in the environment after test case:
E           Resources added:
E           - '***pods***':
E             - apiVersion: v1
E               kind: Pod
E               metadata:
E                 annotations:
E                   k8s.v1.cni.cncf.io/networks-status: ''
E                 creationTimestamp: '2020-03-19T02:14:23Z'
E                 labels:
E                   app: installer
E                 name: installer-7-control-plane-1
E                 namespace: openshift-kube-apiserver
```

This makes the test fail, but the reason why this makes the test fail is not clear, as this resource seems to be internal to OCP.

**Comment by RazTamir** [comment]
Hi @mbukatov, could you please send a PR to exclude the openshift-kube-apiserver namespace in the environment_check functionality?

**Comment by mbukatov** [comment]
I could, but looking at the code I think it would be better to just ignore all namespaces with `openshift-` prefix, maybe with exception of openshift-storage, but tests should not deploy any resources there anyway.

**Comment by RazTamir** [comment]
Honestly, I prefer to do it step by step and if we will realize that the list is covering many of the openshit- namespaces, we can go with your approach.
Wdyt?

**Comment by mbukatov** [comment]
Assuming that the purpose of [the leftover check](https://github.com/red-hat-storage/ocs-ci/pull/237) is to detect that:

- resources created during a test case execution weren't properly deleted during teardown
- some problem happened within OCS itself

I don't see any reason to add exceptions for internal openshift namespaces one by one, every time we run into new case of this.

Quite the contrary, I see that this approach creates following problems:

- test cases fail every now on then for unrelated and unclear reasons
- higher cost of log analysis
- decreasing value of test results statistics (esp. combined with issues like https://github.com/red-hat-storage/ocs-ci/issues/1685)

Could you provide me all examples when we discovered a bug because the leftover check failed on something inside some internal openshift namespace? So far I see that every time this happens, people just report that that is not an actual bug, and add an exception into the env. check.

**Comment by ebenahar** [comment]
I tend to agree with ignoring all 'openshift-' NSs but openshift-storage. I just would like to know, doesn't anyone know if we have ever seen leftovers in other 'openshift-' NSs? 
If not, and this is the first time, then there is no real need to ignore all other 'openshift-' as the overhead didn't exist so far.

**Comment by RazTamir** [comment]
@mbukatov, your assumptions are right.
The main reason to have this check is to ensure each test will run in the same initial environment and not after many tests pollute it with leftovers. 
I guess we can go with your approach as we really don't have any action item to take if we'll see something from openshift-  NS

**Comment by mbukatov** [comment]
> If not, and this is the first time, then there is no real need to ignore all other 'openshift-' as the overhead didn't exist so far.

When this feature was introduced in c1267e7fc6490c785c444bd386927064791b71ac, [the assumption was that "OCP will not add new entities just like that without any request"](https://github.com/red-hat-storage/ocs-ci/pull/237#discussion_r294224475), and the code didn't have any namespace exceptions.

Since then, we noticed that the assumption doesn't hold, and gradually introduced exceptions for:
- `openshift-marketplace` in b7cd3f7546476c4c8d157bd09481245dc014d965
- must gather in 7b17dcb71183e63d591e6165f66ab5b274b3d305 (which has nothing to do with namespace filtering I propose though)
- `openshift-monitoring` in e0e712631ddd51ed201e4bbe31921897941175bf
- and now we see that with `openshift-kube-apiserver` namespace
