### ISSUE TITLE
Get Storage capacity

### ISSUE THREAD

**Issue by Avilir** [red-hat-storage/ocs-ci#1696]
This issue is to be able running performance test on different platforms and with different storage capacity automaticly.
the test need to find the storage capacity and modify its parameters accordingly.

**Comment by mbukatov** [comment]
I have a fio job for monitoring testing which can target percentage of user accesible utilization based on MAX AVAIL data. Right now, I'm polishing the code so that this could be used for data verification after a cluster disruptions like shutdown or upgrade.

**Comment by Avilir** [comment]
closed by PR #1968
