### ISSUE TITLE
AWS cleanup job should destroy UPI clusters in AWS

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1716]
Currently, ci-cleanup, used by aws-cleanup, can't delete UPI based clusters.
We need this to happen as in many cases, instances that belong to UPI clusters continue running while they should be deleted

**Comment by ebenahar** [comment]
I see that the functionality for destroying UPI AWS clusters exists in https://github.com/red-hat-storage/ocs-ci/blob/1758576dba12dd142247fb3bfb9c545d03ba48a2/ocs_ci/deployment/aws.py#L859?
But it requires having config.ENV_DATA with the cluster data. 

@clacroix12 @shylesh @petr-balogh Suggestions?

**Comment by clacroix12** [comment]
@ebenahar so I think we need cluster data for a few reasons here.

1. for the cluster name
2. to see if we spun up rhel nodes
3. check number of workers

We can already determine the cluster name from the resources in aws that we want to cleanup. We can also just always check to see if rhel workers exist for the node and if so clean them up too. For checking the number of workers we can most likely use cloudformation and pull stacks containing the cluster name + worker name pattern. 

We can move the code in destroy_cluster to more general utility functions, and with some modifications addressing the points above I think we can make it work for both destroy_cluster and aws_cleanup.

**Comment by ebenahar** [comment]
Ack. Will take it up

**Comment by ebenahar** [comment]
Fixed in https://github.com/red-hat-storage/ocs-ci/pull/1734
