### ISSUE TITLE
[MCG] Bucket Policy OBC initialization error

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#1721]
def __init__(self, mcg, obc):
        """
        Initializer function
    
        Args:
            mcg (obj): Multi cloud gateway object
            obc (str): Name of the Object Bucket Claim
        """
        self.obc_name = obc
        self.namespace = config.ENV_DATA['cluster_namespace']
        obc_obj = OCP(namespace=self.namespace, kind='ObjectBucketClaim', resource_name=self.obc_name)
        obc_results = obc_obj.get()
        self.ob_name = obc_results.get('spec').get('ObjectBucketName')
        self.bucket_name = obc_results.get('spec').get('bucketName')
        ob_obj = OCP(namespace=self.namespace, kind='ObjectBucket', resource_name=self.ob_name).get()
>       self.obc_account = ob_obj.get('spec').get('additionalState').get('account')
E       AttributeError: 'NoneType' object has no attribute 'get'

OBC is initialised immediately after creating it. In some cases it would be still in pending state which results in not getting the object bucket name and account.

**Comment by MeridianExplorer** [comment]
Fixed in #1722 
Since then the logic was moved to the the bucket factory -
https://github.com/red-hat-storage/ocs-ci/blob/896487b5e22a4586543ddb113b4d40abed54c656/tests/conftest.py#L1837
