### ISSUE TITLE
The MCG 1TB object deletion test should be improved

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#1756]
Right now, the test actively retrieves all objects from the test objects bucket for 3175 times, which was equally rough to 1TB.

However, the bucket objects were since changed, and there's no taste in actively downloading the same objects again and again from AWS - we can just download them once and copy them over and over, or alternatively, we can just generate IO (which might also be faster, which is great for the test).

The test was taken out of tier3 until it'll be rewritten - #1755

**Comment by ebenahar** [comment]
will be handled as part of https://github.com/red-hat-storage/ocs-ci/issues/1659
