### ISSUE TITLE
upload the cluster-dir in build artifacts in jenkins

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1758]
We should upload the cluster-dir for all deployments in build artifcats so that its easier to download and teardown if slave disappears.

**Comment by vasukulkarni** [comment]
Looks like openshift cli is deleting the cluster-dir (which exists in our share link), we discussed to just tar the files before delete is invoked to workaround it.

**Comment by dahorak** [comment]
Fix is in [MR!225](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/merge_requests/225) and is already merged.
