### ISSUE TITLE
Scale Tests failure due to "OSError: [Errno 24] Too many open files" error

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#1765]
Observing this problem every time when we run Scale testcase where there is creation of 1500 PVC, in future we are planning to go beyond this value.

This is more like system failure than python failure, One way to handle is to increase the file open limit on the machine where test case is executed but still this is not proper solution.
https://easyengine.io/tutorials/linux/increase-open-files-limit/

Should better close the files we create in /tmp/, i.e. for 1500 PVC creations for each PVC there will be a file create in /tmp/, 

Test execution failure below.
`self = <test_pvc_creation_deletion_scale.TestPVCCreationDeletionScale object at 0x7fd2b361bdd0>, namespace = None, access_mode = 'ReadWriteOnce', interface = 'CephBlockPool'

    @pytest.mark.parametrize(
        argnames=["access_mode", "interface"],
        argvalues=[
            pytest.param(
                *[constants.ACCESS_MODE_RWO, constants.CEPHBLOCKPOOL],
                marks=pytest.mark.polarion_id("OCS-1225")
            ),
            # pytest.param(
            #     *[constants.ACCESS_MODE_RWX, constants.CEPHBLOCKPOOL],
            #     marks=pytest.mark.polarion_id("OCS-2010")
            # ),
            # pytest.param(
            #     *[constants.ACCESS_MODE_RWX, constants.CEPHFS_INTERFACE],
            #     marks=pytest.mark.polarion_id("OCS-2008")
            # ),
        ]
    )
    @pytest.mark.usefixtures(namespace.__name__)
    def test_multiple_pvc_creation_deletion_scale(self, namespace, access_mode, interface):
        """
        Measuring PVC creation time while scaling PVC
        Measure PVC deletion time after creation test
        """
        number_of_pvc = 1500
        log.info(f"Start creating {access_mode}-{interface} {number_of_pvc} PVC")
    
        if interface == constants.CEPHBLOCKPOOL:
            self.sc_obj = constants.DEFAULT_STORAGECLASS_RBD
        elif interface == constants.CEPHFS_INTERFACE:
            self.sc_obj = constants.DEFAULT_STORAGECLASS_CEPHFS
    
        # Create PVC
        pvc_objs = helpers.create_multiple_pvcs(
            sc_name=self.sc_obj,
            namespace=self.namespace,
            number_of_pvc=number_of_pvc,
            size=f"{random.randrange(5, 105, 5)}Gi",
>           access_mode=access_mode
        )

tests/e2e/scale/test_pvc_creation_deletion_scale.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/helpers.py:538: in create_multiple_pvcs
    ) for _ in range(number_of_pvc)
tests/helpers.py:538: in <listcomp>
    ) for _ in range(number_of_pvc)
tests/helpers.py:506: in create_pvc
    created_pvc = ocs_obj.create(do_reload=do_reload)
ocs_ci/ocs/resources/ocs.py:102: in create
    status = self.ocp.create(yaml_file=self.temp_yaml.name)
ocs_ci/ocs/ocp.py:272: in create
    output = self.exec_oc_cmd(command)
ocs_ci/ocs/ocp.py:127: in exec_oc_cmd
    ignore_error=ignore_error, **kwargs
ocs_ci/utility/utils.py:415: in run_cmd
    **kwargs
/usr/lib64/python3.7/subprocess.py:488: in run
    with Popen(*popenargs, **kwargs) as process:
/usr/lib64/python3.7/subprocess.py:800: in __init__
    restore_signals, start_new_session)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x7fd2a09255d0>
args = ['oc', '-n', 'namespace-test-f00616bf1bcd4731ae4ff63d920b840d', '--kubeconfig', '/home/rperiyas/aws2ndApr/auth/kubeconfig', 'create', ...], executable = 'oc'
preexec_fn = None, close_fds = True, pass_fds = (), cwd = None, env = None, startupinfo = None, creationflags = 0, shell = False, p2cread = 1017, p2cwrite = 1018
c2pread = 1019, c2pwrite = 1020, errread = 1021, errwrite = 1022, restore_signals = True, start_new_session = False

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       pass_fds, cwd, env,
                       startupinfo, creationflags, shell,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite,
                       restore_signals, start_new_session):
        """Execute program (POSIX version)"""
    
        if isinstance(args, (str, bytes)):
            args = [args]
        else:
            args = list(args)
    
        if shell:
            # On Android the default shell is at '/system/bin/sh'.
            unix_shell = ('/system/bin/sh' if
                      hasattr(sys, 'getandroidapilevel') else '/bin/sh')
            args = [unix_shell, "-c"] + args
            if executable:
                args[0] = executable
    
        if executable is None:
            executable = args[0]
        orig_executable = executable
    
        # For transferring possible exec failure from child to parent.
        # Data format: "exception name:hex errno:description"
        # Pickle is not used; it is complex and involves memory allocation.
>       errpipe_read, errpipe_write = os.pipe()
E       OSError: [Errno 24] Too many open files

/usr/lib64/python3.7/subprocess.py:1441: OSError`

for more logs please refer jenkins test run failure https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6300/testReport/junit/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_multiple_pvc_creation_deletion_scale_ReadWriteMany_cephfs_/

For complete run logs https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6300/

**Comment by dahorak** [comment]
Fixing in [MR!227](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/merge_requests/227)

**Comment by petr-balogh** [comment]
Closing as ^ got merged
