### ISSUE TITLE
switch centos slaves to rhel

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1769]
for mcg we need to bring the package from subscription manager which can be handled within the tier scripts,

**Comment by dahorak** [comment]
Created  [issue 37](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/issues/37) in ocs4-jenkins for this, please continue any discussion there.

**Comment by dahorak** [comment]
There were no update in this ticket for more than 1 year, we migrated to CentOS8 in the meantime and also I think that the original problem was solved somehow differently, so we can close this ticket.
