### ISSUE TITLE
tests failed with CommandFailed: FIO execution results

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#1772]
In some tier executions, we are seeing intermittent issues where the test fails while fetching the FIO results from a pod:

We would need better logging for pods as well as FIO to narrow down the root cause. The ocp-must-gather also doesn't have any logs about the pods in custom user namespaces. Hence, debugging these issues become tougher.

Suggestions to overcome these issues are welcome!

One e.g. - [logs](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-ai3c33-t4c/jnk-ai3c33-t4c_20200402T114352/logs/ocs-ci-logs-1585831130/tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py/TestResourceDeletionDuringMultipleDeleteOperations/test_disruptive_during_pod_pvc_deletion_and_io-CephFileSystem-osd/logs)

e.g Tier execution - [here](ocs-ci results for OCS4-3-Downstream-OCP4-3-AWS-IPI-3AZ-RHCOS-3M-3W-tier4c (BUILD ID: v4.3.0-394.ci RUN ID: 1585831130))
```

2020-04-02 22:42:21,906 - INFO - tests.manage.pv_services.test_resource_deletion_during_pvc_pod_deletion_and_io.test_disruptive_during_pod_pvc_deletion_and_io.436 - Fetching IO results from the pods.
2020-04-02 22:42:21,906 - INFO - ocs_ci.ocs.resources.pod.get_fio_results.119 - Waiting for FIO results from pod pod-test-cephfs-c195b76399964ba68f2275150b734bd1
2020-04-02 22:42:21,907 - ERROR - ocs_ci.ocs.resources.pod.get_fio_results.127 - FIO failed: FIO execution results: .
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/pod.py", line 124, in get_fio_results
    raise CommandFailed(f"FIO execution results: {result}.")
ocs_ci.ocs.exceptions.CommandFailed: FIO execution results: .

```

**Comment by shylesh** [comment]
I tried couple of times locally and reason I feel is when we run fio with size=1G and runtime=60s for some reason we don't get any output from ```oc rsh``` command hence FIO results are empty. I ran with runtime=30s then it worked.

**Comment by jilju** [comment]
Increasing the priority because this issue is being reproduced more frequent than before.

**Comment by gitsridhar** [comment]
I can reproduce it with a breakpoint. I paused tier test execution with pdb, so that the corresponding pod is not deleted. Then I do oc rsh and enter into the pod and run the same fio command without '--output-format=json' and it works and if I retry again with JSON format, it crashes and pod shell gets terminated as well. This is happening in the IBM ppc64le environment.

**Comment by gitsridhar** [comment]
Not all test cases involving fio are failing though... Most of them pass.

**Comment by jilju** [comment]
> I can reproduce it with a breakpoint. I paused tier test execution with pdb, so that the corresponding pod is not deleted. Then I do oc rsh and enter into the pod and run the same fio command without '--output-format=json' and it works and if I retry again with JSON format, it crashes and pod shell gets terminated as well. This is happening in the IBM ppc64le environment.

In this case, we can assume the issue is not with ocs-ci. But to handle this issue, we might need to remove '--output-format=json' from fio command parameters. I just check the usages. Removing  '--output-format=json'  will require changes in test case modules and helpers.

Still not clear why an exception is not raised from subprocess which is used in ocs_ci.utility.utils.exec_cmd.

**Comment by gitsridhar** [comment]
I thought this problem was reproduced in x86 environment as well back in April when this issue was opened, so it is not limited to ppc64le.

**Comment by zmc** [comment]
On Power, the issue was haproxy timing out k8s api server requests; perhaps it's your root cause as well @nehaberry @jilju

**Comment by gitsridhar** [comment]
This problem got fixed when haproxy client and server timeouts were increased to 4H from 60 seconds on IBM Powr ppc64le.

**Comment by am-agrawa** [comment]
Same issue was seen in `RUN ID: 1649462288`
test-
tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_create_resize_delete_pvc[ocs-storagecluster-ceph-rbd-ReadWriteMany-3-Block]

**Comment by jilju** [comment]
RUN ID 1679235226
Test case :
tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py::TestEncryptedRbdBlockPvcSnapshot::test_encrypted_rbd_block_pvc_snapshot[v2-vault-False]

**Comment by jilju** [comment]
found in https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17618/858374/858413/858417/log
