### ISSUE TITLE
Incorrect aguments used in PVC class constructor

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#178]
[PVC](https://github.com/red-hat-storage/ocs-ci/blob/master/resources/persistent_volume_claim.py) class is inheriting from [OCS](https://github.com/red-hat-storage/ocs-ci/blob/master/resources/ocs.py). In `__init__()` is:
```
        super(PVC, self).__init__(
            self.pvc_data['apiVersion'], self.pvc_data['kind'],
            self.pvc_data['metadata']['namespace']
        )
```
but  [OCS](https://github.com/red-hat-storage/ocs-ci/blob/master/resources/ocs.py) [constructor doesn't take any additional positional arguments](https://github.com/red-hat-storage/ocs-ci/blob/master/resources/ocs.py#L19):
```
class OCS(object):
    """
    Base OCSClass
    """

    def __init__(self, **kwargs):
```
If user creates instance of PVC then there is an error raised:
```
    def __init__(self, interface, **kwargs):
        """
        Initializer function
    
        Args:
            interface (str): The ceph interface to use for creating the
            PVC - 'cephfs', 'rbd', 'rgw'
    
        kwargs:
            Copy of ocs/defaults.py::PVC_DICT dictionary
        """
        self.pvc_data = default.PVC_DICT
        self.pvc_data.update(kwargs)
        super().__init__(
            self.pvc_data['apiVersion'], self.pvc_data['kind'],
>           self.pvc_data['metadata']['namespace']
        )
E       TypeError: __init__() takes 1 positional argument but 4 were given

```

**Comment by RazTamir** [comment]
@fbalak should be fixed with https://github.com/red-hat-storage/ocs-ci/pull/174/files

**Comment by fbalak** [comment]
@RazTamir Ok, I will close PR 179 when PR 174 is merged. Can you add `Fixes issue 178` to your PR description? That way it should automatically close this issue when it is merged (https://help.github.com/en/articles/closing-issues-using-keywords) and it will be clear where it was resolved.

**Comment by RazTamir** [comment]
Thanks - done
