### ISSUE TITLE
Doc generation failing: duplicate object description of ocs_ci.ocs.cluster.CephCluster.cluster_name

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1782]
https://travis-ci.org/github/red-hat-storage/ocs-ci/jobs/671489818?utm_medium=notification&utm_source=github_status

```
/home/travis/build/red-hat-storage/ocs-ci/ocs_ci/ocs/cluster.py:docstring of ocs_ci.ocs.cluster.CephCluster.cluster_name:1:duplicate object description of ocs_ci.ocs.cluster.CephCluster.cluster_name, other instance in apidoc/ocs_ci.ocs, use :noindex: for one of them
```

**Comment by clacroix12** [comment]
This is an issue with Sphinx 3.0.0 which was release yesterday: https://github.com/sphinx-doc/sphinx/issues/7427

To get around this I am going to pin our Sphinx version to `2.4.4` until this is resolved.

**Comment by petr-balogh** [comment]
@clacroix12 do we have workaround issue to track this to really move back with sphinx without pinned version once issue fixed or we would like to stick with this version?

**Comment by clacroix12** [comment]
@petr-balogh #1800

**Comment by petr-balogh** [comment]
> #1800

thx
