### ISSUE TITLE
DC7 and DC8 - IP assignment issue

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1783]
It looks like specific DC7 and DC8 issue, Pratik tried on different DC and control plane IP was assignment issue was not seen

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6420/console
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6422/console

**Comment by vasukulkarni** [comment]
@prsurve FYI

**Comment by vavuthu** [comment]
@vasukulkarni Looks like those failures are caused by network changes made by Elad. From the chat room, I see deployment is passed on above DC after reverting the changes.
