### ISSUE TITLE
Deploying of logging is stuck and says retrying 65610 seconds...  on OCS 4.4 with OCP 4.4 

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1812]
23:24:33 - MainThread - ocs_ci.utility.retry - WARNING - Error during execution of command: oc -n openshift-logging --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig create -f /tmp/ClusterLogginghhiruc91 -o yaml.
Error is error: unable to recognize "/tmp/ClusterLogginghhiruc91": no matches for kind "ClusterLogging" in version "logging.openshift.io/v1"
, Retrying in 65610 seconds...

OCS 4.4 with OCP 4.4 
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6547/console
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6542/console
UPI and IPI deployment with RHEL and RHCOS, the same results.

**Comment by Akarsha-rai** [comment]
Both failed while installing logging. It failed to create instances since OCP 4.4 is not GAed yet, we need to pull the images from Quay to install logging successfully.
@Shrivaibavi had raised issue and working on it #763 #837

For now as quick step we can skip logging test cases on OCP 4.4.

**Comment by petr-balogh** [comment]
@Akarsha-rai @Shrivaibavi  ,  when I just quickly looked during holidays I haven't noticed that the job passed the deployment and got stuck on tier tier executions. Also I thought it was related to first issue https://github.com/red-hat-storage/ocs-ci/issues/1806 to monitoring but now see it's related to logging.  

I created PR: https://github.com/red-hat-storage/ocs-ci/pull/1834 to skip the logging tests if running on OCP 4.4 here and opened WA issue  #1833 .

Once GA or fix for this issue done we can revert the WA.
