### ISSUE TITLE
Test OBC ConfigMap credentials instead of using the master credentials

### ISSUE THREAD

**Issue by Neon-White** [red-hat-storage/ocs-ci#1816]
At the moment, we're using the NB admin credentials to perform IO on buckets. We should automate a scenario where we consume the endpoint, bucketname and credentials from the configmap created with the OBC. I already have a script that does it, feel free to contact me and I'll send it over.

**Comment by MeridianExplorer** [comment]
Already partially tested as part of 
https://github.com/red-hat-storage/ocs-ci/blob/bdb4fce13b5582df09afef9028665554151fb307/tests/manage/mcg/test_bucket_policy.py#L19

It's possible to add tests by utilizing the existing OBC class' `s3_resource` and `s3_client`
