### ISSUE TITLE
Remove "test_registry_image_pull_push" test case out of workloads

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#1829]
Currently, "test_registry_image_pull_push" is skipped due to https://github.com/red-hat-storage/ocs-ci/issues/1547.  The existing issue with users permissions becomes read_only to perform any write operation on this test case, therefore we have decided to remove this test case out of workloads.

**Comment by RazTamir** [comment]
Replied in #1547

**Comment by ramkiperiy** [comment]
Closing the issue, since PR is merged.
