### ISSUE TITLE
[MCG] create a new resource in ocs for Backing Store and Backing Store Secret

### ISSUE THREAD

**Issue by bernerhat** [red-hat-storage/ocs-ci#1854]
Following the pr: https://github.com/red-hat-storage/ocs-ci/pull/1672
as suggested by Filip Balak we need to create a project level resource for both backing store and backing store secret.

**Comment by MeridianExplorer** [comment]
Addressed in #2210

**Comment by bernerhat** [comment]
Closing this issue, created an object for Backing store. 
Secret object will not be created for the project since we are using the cloud manager entity for the backing store secret in the creation process.
