### ISSUE TITLE
aws-cleanup: VPCs without IO tag should not cause exception to be raised

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1856]
We wouldn't want aws-cleanup job to throw and exception as it means no instances are being deleted, we should not throw an exception in https://github.com/red-hat-storage/ocs-ci/blob/259f6bfa1e026d93f6d2674eb0146256cbd18a87/ocs_ci/cleanup/aws/cleanup.py#L198, but skip and continue with other resources deletion

**Comment by clacroix12** [comment]
@ebenahar we have a ticket for this already #1850 that I was working on a fix for. I wanted to add some logging around it instead of simply continuing.

**Comment by clacroix12** [comment]
@ebenahar I see you have a commit that fixes it but I don't see a pull request / that commit isn't in master when i pull from upstream so I opened my PR #1858 which addresses it. Almost identical to yours except we log when we hit this and I removed the custom exception entirely.
