### ISSUE TITLE
[MCG] components should be validated post deployment

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1871]
MCG components, like the default backingstore, bucketclass, noobaa-operator, noobaa-core, noobaa-endpoints, RGW, etc, should be validated post deployment, in https://github.com/red-hat-storage/ocs-ci/blob/90e727a99d5c517d9ba7a6570a8cf43e445d6d51/ocs_ci/ocs/resources/storage_cluster.py#L38

**Comment by MeridianExplorer** [comment]
The matter needs to be discussed with NooBaa to make sure the verification is done properly and covers all the relevant components in the best way possible.
