### ISSUE TITLE
Scale testing 1500 pvc tests fail because open files are not being closed.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#1889]
tests/e2e/scale/test_pvc_creation_deletion_scale.py  contains code that looks like:

        csv_obj = csv.writer(open(file_name, "w"))
        for k, v in data.items():
           csv_obj.writerow([k, v])

This does not close the  open that is performed.

I have tried:

        with open(file_name, "w") as fd:
            csv_obj = csv.writer(fd)
            for k, v in data.items():
                csv_obj.writerow([k, v])

and this seems to work much better.  Tests that ran out of file descriptors in twenty minutes
are now running for hours.  I believe that the second part is currently running as I type.

I found a couple of other issues similar to this in the code:

In ocs_ci/utillity/utils.py, a line reads:

html_data = open(os.path.expanduser(html)).read()

I have replaced that with:

with open(os.path.expanduser(html)) as fd:
      html_data = fd.read;

This affects my current test case.

In tests/manage/storageclass/test_storageclass_invalid.py there is the code

yaml_data = yaml.safe_load(open(yaml_path, 'r'))

which I have similarly fixed.  This code does not affect my  testcase but I think that it should be
fixed anyway.

I am now waiting for this test to finish.  If it passes, I will rerun without some debugging stuff
that I threw in, retest, and then create a pull request for this bug.   The turnaround now is slow.

**Comment by wusui** [comment]
Yay!  It just passed.

**Comment by petr-balogh** [comment]
@wusui Can you link the PR please?

The best way if you put as first comment in pr
`Fixes: #1889`

then it will automatically close this issue once PR merged and will also link it here automatically.
