### ISSUE TITLE
support for workload storage utilization fixtures utilizing fixed abount of data

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1891]
Function `workload_fio_storageutilization()` provides a way how to utilize a target percentage on OCS cluster (which is necessary for some alerting and metrics tests). To implement other metrics tests in less intrusive way, we also need to be able utilize target absolute values (eg. 50GiB).

**Comment by fbalak** [comment]
This is related to https://github.com/red-hat-storage/ocs-ci/issues/1870. https://github.com/red-hat-storage/ocs-ci/issues/1870 could be fixed by using absolute values.
