### ISSUE TITLE
unittest is failing constantly 

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#191]
Please check this failure https://travis-ci.org/red-hat-storage/ocs-ci/jobs/544075367

**Comment by vasukulkarni** [comment]
Looks like was broken during merge of https://github.com/red-hat-storage/ocs-ci/pull/183 , @petr-balogh do you remember if the merge button was green for you? Trying to see if there is still an issue with merging on failed CI tests.

**Comment by vasukulkarni** [comment]
@zmc FYI

**Comment by zmc** [comment]
In #183, the tests didn't properly run. See https://travis-ci.org/red-hat-storage/ocs-ci/jobs/543758242

I'm not sure why yet.

**Comment by zmc** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/190 was merged with failing tests.

**Comment by zmc** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/183 changed the default in one place but not the other (we really need to consolidate)

**Comment by zmc** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/206

**Comment by zmc** [comment]
Should be fixed now. If you still see failures, rebase against master.

**Comment by petr-balogh** [comment]
@vasukulkarni when I submitted the change the PR #165 wasn't merged yet so the test didn't run and the merge button was green. But when I merged today it caused the issue. I saw the issue today, so before I left the office I tried to submit this PR #202 . I tried to explained the problem with the test in the comment in the PR #202 and this specific commit:  https://github.com/red-hat-storage/ocs-ci/commit/f5912f7c3a60db949c2c3d012a9773cc3f6fb6cd .

**Comment by vasukulkarni** [comment]
@petr-balogh got it, thanks, I think we have *killer* confusion here with 2 defaults which we discussed a bit last week but held up for you,  I suggest we kill the defaults from conf(Keep other data there) and use defaults.py for all defaults, Lets discuss once you come back.
