### ISSUE TITLE
Where needed, adjust tests to run on other platforms, such as LSO, AWS UPI vSphere, Azure, etc

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1922]
The following tests can run only on AWS and some of them only on IPI, hence we lack coverage over other platforms, such as vSphere, AWS UPI, Azure and LSO. We need to adjust as many of them to be able to run on these different platforms.

- [x] mcg/test_multi_region.py
- [ ] z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
- [x] z_cluster/nodes/test_disk_failures.py
- [x] z_cluster/nodes/test_node_replacement_proactive.py
- [ ] z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
- [ ] z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
- [x] z_cluster/nodes/test_nodes_maintenance.py
- [ ] z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
- [ ] z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
- [x] tests/manage/z_cluster/nodes/test_nodes_restart.py::TestNodesRestart::test_nodes_restart
- [ ] disconnected / proxy - test upgrade
- [ ] disconnected / proxy - adjust multi cloud tests
- [ ] external mode gaps

**Comment by MeridianExplorer** [comment]
`test_multi_region.py` addressed in #2210

**Comment by ebenahar** [comment]
@hnallurv @nehaberry @dahorak @MeridianExplorer I added disconnected items to the list

**Comment by sidhant-agrawal** [comment]
`tests/manage/z_cluster/nodes/test_nodes_restart.py::TestNodesRestart::test_nodes_restart` addressed in #3793
