### ISSUE TITLE
memory size of compute VM in DC26 is 8GB which is too low

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#1927]
When I try to deploy a new cluster in DC26 It failed because the memory was 8GB which is too low. 
When I tried to use the configuration file 'conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml' which specify  this param: **compute_memory: '32768'** the compute VM still had 8GB instead of 32GB as specified in the file. Also, @OdedViner faced the same issue. Here are the 2 failed builds in Jenkins that relevant to the issue: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7022/, https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7023/. Also we have found this in the logs: `Apr 26 11:47:45.745246 compute-0 hyperkube[2117]: I0426 11:47:45.745026    2117 manager.go:193] Machine: {NumCores:16 CpuFrequency:2095078 MemoryCapacity:8357060608`.  
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/oviner-sqldc26/oviner-sqldc26_20200426T112758/logs/failed_testcase_ocs_logs_1587900991/deployment_ocs_logs/ocp_must_gather/quay-io-openshift-origin-must-gather-sha256-605d33681323ff3d4db3711ec45d223d6b0c882431d571a0c07208868996be55/host_service_logs/workers/kubelet_service.log

**Comment by vavuthu** [comment]
@yitzhak12 Do you have cluster available, so that i will check the memory details

**Comment by Avilir** [comment]
@vavuthu , i think the issue is that the deployment dose not take the : compute_memory: from the deployment yaml file. 
i hit this too, i deploy a cluster with : compute_memory: 65536 
and my cluster create with compute nodes that have only 8GB of memory.

**Comment by vavuthu** [comment]
@Avilir @yitzhak12 @OdedViner : I have deployed with same parameters ( conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml ) and as expected compute nodes are spinup with 64Gb memory
``
 CPU 16 CPU(s)
 Memory  64 GB, 2.56 GB memory active
```
control plane;
```
 CPU 4 CPU(s)
 Memory  16 GB, 2.88 GB memory active
```
/home/vavuthu/Pictures/Screenshot from 2020-05-06 19-59-40.png

/home/vavuthu/Pictures/Screenshot from 2020-05-06 19-57-54.png

**Comment by vavuthu** [comment]
Deploy Job Link: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7316/console

Cluster is still in state if anyone wants to look at.

**Comment by yitzhak12** [comment]
I also deployed a cluster on dc26 with the conf file: **conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml** and it worked fine.

**Comment by vavuthu** [comment]
I faced same issue having 8 GB memory. Working on a fix
