### ISSUE TITLE
Resource StorageClass is broken

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#193]
Class `StorageClass` from `resources.storage_class` have following issues:

- Directory in paths to yaml template is swapped. CephFS uses RBD dir and RBD uses CephFS dir.
- Path to yaml points to not existing file (`{rbd,cephfs}_storageclass.yaml`).
- Class gets `namespace` from template but storage classes don't use namespaces. This will be harder to fix because `OCS` class that is parent for this class expects `namespace` as argument.

**Comment by RazTamir** [comment]
see my comment https://github.com/red-hat-storage/ocs-ci/pull/194#pullrequestreview-248047997

**Comment by fbalak** [comment]
Fixed by https://github.com/red-hat-storage/ocs-ci/pull/213.
