### ISSUE TITLE
Run IO and verify osd tree in test_add_capacity

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#1937]
Test case - tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacity::test_add_capacity

The test case should start IO before adding capacity and ensure that IO is success.
PVCs should be RWO and RWX for both RBD and CephFS.

Check 'ceph osd tree' and ensure that the new osds are under right nodes/hosts.

Follow other steps as in OCS-1191 test case.

**Comment by ebenahar** [comment]
@shreekarSS @hnallurv

**Comment by jilju** [comment]
These checks are now present in the test
