### ISSUE TITLE
We need to make sure all CSRs for all nodes are approved.

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1941]
It can happen that some CSR appear right after we approve all for some node and then we are failing the deployment:

See comment: https://github.com/red-hat-storage/ocs-ci/pull/1938/files#r415868595

**Comment by shylesh** [comment]
This is not yet fixed with latest code from Vijay. As you can see in the output, 1 csr appears in the list after 5 mins of adding an RHCOS node and after approving this it takes another 2 mins for another csr to appear in Pending state. Its after approving this csr we get the node populated in ```oc get nodes```. Hence we might need few more checks.

```
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   87m    v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   99m    v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   100m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   86m    v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   85m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   100m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   87m    v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   100m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   100m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   87m    v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   86m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   100m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   87m    v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   100m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   100m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   87m    v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   86m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   100m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   88m    v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   101m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   101m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   88m    v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   87m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   101m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
No resources found in default namespace.
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   89m    v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   101m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   102m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   88m    v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   87m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   102m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   92m    v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   104m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   105m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   91m    v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   90m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   105m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
NAME        AGE     REQUESTOR                                                                   CONDITION
csr-qv7q2   2m51s   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-qv7q2   11m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   100m   v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   113m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   113m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   100m   v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   99m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   113m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc adm certificate approve csr-qv7q2
certificatesigningrequest.certificates.k8s.io/csr-qv7q2 approved
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-qv7q2   11m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   101m   v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   113m   v1.16.2
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   114m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   100m   v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   99m    v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   114m   v1.16.2
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-dltkr   7s    system:node:ip-10-0-63-213.us-east-2.compute.internal                       Pending
csr-qv7q2   12m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc adm certificate approve csr-dltkr
certificatesigningrequest.certificates.k8s.io/csr-dltkr approved
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-dltkr   27s   system:node:ip-10-0-63-213.us-east-2.compute.internal                       Approved,Issued
csr-qv7q2   12m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-59-185.us-east-2.compute.internal   Ready    worker   101m   v1.16.2
ip-10-0-59-22.us-east-2.compute.internal    Ready    master   114m   v1.16.2
**ip-10-0-63-213.us-east-2.compute.internal   Ready    worker   36s    v1.16.2**===>Newly added
ip-10-0-64-214.us-east-2.compute.internal   Ready    master   114m   v1.16.2
ip-10-0-72-165.us-east-2.compute.internal   Ready    worker   101m   v1.16.2
ip-10-0-81-80.us-east-2.compute.internal    Ready    worker   100m   v1.16.2
ip-10-0-85-167.us-east-2.compute.internal   Ready    master   114m   v1.16.2
```

**Comment by vavuthu** [comment]
@shylesh From the output above, I can see there are 4 workers nodes.  Have you added extra RHOCS after installation completed?
Incase if you added extra node, we have to approve the CSR. 
Do you have job link to take closer look?

**Comment by shylesh** [comment]
@vavuthu ,
Above mentioned sequence of steps are ran after successfully adding a RHCOS node from ocs-ci in which last step was approving csr.

Initially I had 3 workers, as you can see 4th worker didn't show up even after OCS-CI said successful (because csr approval returned success), then csr for the new node appeared 5 minutes later and approving multiple times finally node appears in the list.

The point I was trying to make is approve_csr has to do few more checks as I mentioned in your PR. Mostly checking for new node's IP in the ```oc get nodes``` and repeat approval would work.

**Comment by vavuthu** [comment]
@shylesh : I have chnaged the logic for wait_for_all_nodes_csr ( wait based on number of expected node). 
Coulld you use PR 1981 to verify. Note that if you are adding 3 nodes , it should have genearte 4 CSR including boot-strapper node.

**Comment by shylesh** [comment]
> @shylesh : I have chnaged the logic for wait_for_all_nodes_csr ( wait based on number of expected node).
> Coulld you use PR 1981 to verify. Note that if you are adding 3 nodes , it should have genearte 4 CSR including boot-strapper node.

@vavuthu ,
Looks like it doesn't work.

Check this output
```
NAME        AGE     REQUESTOR                                                                   CONDITION
csr-2d8x2   9m53s   system:node:ip-10-0-61-184.us-east-2.compute.internal                       Approved,Issued
csr-76bdh   9m35s   system:node:ip-10-0-53-107.us-east-2.compute.internal                       Approved,Issued
csr-9jxhv   31s     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-bm2jb   103s    system:node:ip-10-0-48-80.us-east-2.compute.internal                        Approved,Issued
csr-bmphw   10m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-rhxkz   83s     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
```

Here for every node I get one bootstrap csr and according to your PR we have to calculate n + 1 csrs (n nodes, 1 bootstrap) which doesn't work. Atleast its not working with RHCOS node addition. I have added in my PR https://github.com/red-hat-storage/ocs-ci/pull/1859 to check whether actual ip address of the node appears in the ```oc get nodes``` list and blindly do ```approve``` till we see all the nodes which works better for all platforms.

Let me know your thoughts

**Comment by shylesh** [comment]
Just for more info , I am calling like this  
``` wait_for_all_nodes_csr_and_approve(expected_node_num=num_nodes+1)```. Hope this is what you meant.

**Comment by vavuthu** [comment]
@shylesh from the previous o/p, I can see newly added nodes will appear only when we approve bootstraper CSR. If you are adding 3 nodes, we need to expect 4 CSR because https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/csr.py#L113 will give dict of unique node names. 

Yes, https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/csr.py#L139 wil aprove pending CSR for every iteration. so at the end it will approve all CSR.

See below jenkins job logs for PR https://github.com/red-hat-storage/ocs-ci/pull/1995
logs: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7274/console

Newly nodes are added succesfully ( job failed to get old node status after node addition )

**Comment by shylesh** [comment]
> @shylesh from the previous o/p, I can see newly added nodes will appear only when we approve bootstraper CSR. If you are adding 3 nodes, we need to expect 4 CSR because https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/csr.py#L113 will give dict of unique node names.
> 
> Yes, https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/csr.py#L139 wil aprove pending CSR for every iteration. so at the end it will approve all CSR.
> 
> See below jenkins job logs for PR #1995
> logs: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7274/console
> 
> Newly nodes are added succesfully ( job failed to get old node status after node addition )

@vavuthu ,
I was trying to tell that n+1 csr is not the case, In the above output I am trying to add 3 nodes and I could see 6 csrs, for each node I will get one bootstrapper service csr. Hence I said n+1 will not work atleast in case of RHCOS AWS UPI add node.

**Comment by petr-balogh** [comment]
@shylesh Do I understand that correctly that after cluster is installed correctly the CSRs will disappear and you were able to see just 2 CSRs as you mentioned above?
```
(venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-dltkr   27s   system:node:ip-10-0-63-213.us-east-2.compute.internal                       Approved,Issued
csr-qv7q2   12m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
```

So no CSRs found for added nodes from deployment?

Thanks fro explanation.

**Comment by shylesh** [comment]
> @shylesh Do I understand that correctly that after cluster is installed correctly the CSRs will disappear and you were able to see just 2 CSRs as you mentioned above?
> 
> ```
> (venv) [shylesh@localhost ocs-ci]$ ./bin/oc get csr
> NAME        AGE   REQUESTOR                                                                   CONDITION
> csr-dltkr   27s   system:node:ip-10-0-63-213.us-east-2.compute.internal                       Approved,Issued
> csr-qv7q2   12m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
> ```
> 
> So no CSRs found for added nodes from deployment?
> 
> Thanks fro explanation.

@petr-balogh ,

Sorry if I was not clear about my explanation, I am mostly talking about approving csrs after adding a new RHCOS node to an existing OCS cluster.

In my case if I add 1 RHCOS node to cluster, I will see 2 csrs listed in ```get csr``` output. Its always ```2*number_of_newly_added_rhcos_nodes```, hence calculation provided by Vijay doesn't work for RHCOS node addition to AWSUPI (which works for him on VMware). So Just for AWSUPI RHCOS node addition I added other logic of approving  csr assuming that we can't always reliably calculate ```expected_number_of_csr``` . Let me know if I am missing something.

**Comment by petr-balogh** [comment]
@shylesh  I was confused the sam as you with this logic. If you will ask directly `oc get csr` you will get more CSRs for on node but how the function was implemented by Vijay here: https://github.com/red-hat-storage/ocs-ci/pull/1938/files#diff-14072d12d253c891ce29bf52dcda7ac5R120-R125

you can see this structure (dictionary) he is returning:
```python
            {
                'control-plane-1': ['csr-6hx8z'],
                'compute-2': ['csr-blz2n'],
                'compute-0': ['csr-p46bz'],
                'control-plane-2': ['csr-tzhn5'],
                'control-plane-0': ['csr-wm4g5']
                }
```

so which means that length of dict_above will be based on nodes names so if there are multiple csrs in one node there will be entry like `'compute-2': ['csr-blz2n', 'csr-second'] `

So I think that if we still have all the CSRs there and they will not vanish so we should be ok to use number of current nodes before the expansion + 1 cause of bootstrap.  + number of nodes you are now adding in the function.  


So in case we have 6 nodes + 1 bootstrap = 7 ,  you will get this number by oc get node and get length of items before adding any node.    when you adding some specific number of nodes you will use.   `7 + number of new nodes`   ,  In case of one node this case 8, in case of 2 nodes 9.

This still doesn't work for you here?

**Comment by shylesh** [comment]
> @shylesh I was confused the sam as you with this logic. If you will ask directly `oc get csr` you will get more CSRs for on node but how the function was implemented by Vijay here: https://github.com/red-hat-storage/ocs-ci/pull/1938/files#diff-14072d12d253c891ce29bf52dcda7ac5R120-R125
> 
> you can see this structure (dictionary) he is returning:
> 
> ```python
>             {
>                 'control-plane-1': ['csr-6hx8z'],
>                 'compute-2': ['csr-blz2n'],
>                 'compute-0': ['csr-p46bz'],
>                 'control-plane-2': ['csr-tzhn5'],
>                 'control-plane-0': ['csr-wm4g5']
>                 }
> ```
> 
> so which means that length of dict_above will be based on nodes names so if there are multiple csrs in one node there will be entry like `'compute-2': ['csr-blz2n', 'csr-second'] `
> 
> So I think that if we still have all the CSRs there and they will not vanish so we should be ok to use number of current nodes before the expansion + 1 cause of bootstrap. + number of nodes you are now adding in the function.
> 
> So in case we have 6 nodes + 1 bootstrap = 7 , you will get this number by oc get node and get length of items before adding any node. when you adding some specific number of nodes you will use. `7 + number of new nodes` , In case of one node this case 8, in case of 2 nodes 9.
> 
> This still doesn't work for you here?

@petr-balogh ,

This condition always doesn't work.
csrs will be not listed in ```get csr``` after certain time, in my cluster it's around 75 mins.

Initially I brought up a 6 node cluster, added 2 more nodes (Expected_nodes=6+1+2) using Vijay's fix and it works fine. Then I added 3 more nodes (Expected_nodes=6+1+2+3) and it works. 

After this I wanted to add 3 more nodes  (Expected_nodes=6+1+2+3+3), but this didn't work because csrs for initial 6 nodes were not appearing in the ``` get csr``` output hence ```Expected_nodes``` didn't match.  So this approach doesn't work for me in case of RHCOS node addition in AWSUPI.


```
INITIAL CSR and NODES
---------------------------------------
 [shylesh@localhost ocs-ci]$ ./bin/oc --kubeconfig ~/shmohanupi/auth/kubeconfig get csr 
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-7bkz4   46m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-7dm29   56m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-7sx7w   56m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-86scm   44m   system:node:ip-10-0-84-68.us-east-2.compute.internal                        Approved,Issued
csr-8gxlm   45m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-cttg6   44m   system:node:ip-10-0-64-205.us-east-2.compute.internal                       Approved,Issued
csr-gbmmw   56m   system:node:ip-10-0-60-1.us-east-2.compute.internal                         Approved,Issued
csr-nrpzv   56m   system:node:ip-10-0-85-210.us-east-2.compute.internal                       Approved,Issued
csr-pf4dz   45m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-qttt6   45m   system:node:ip-10-0-58-3.us-east-2.compute.internal                         Approved,Issued
csr-rhzgw   56m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-sjtnq   56m   system:node:ip-10-0-69-37.us-east-2.compute.internal                        Approved,Issued



(venv) [shylesh@localhost ocs-ci]$ ./bin/oc --kubeconfig ~/shmohanupi/auth/kubeconfig get nodes
NAME                                        STATUS   ROLES    AGE   VERSION
ip-10-0-58-3.us-east-2.compute.internal     Ready    worker   46m   v1.16.2
ip-10-0-60-1.us-east-2.compute.internal     Ready    master   56m   v1.16.2
ip-10-0-64-205.us-east-2.compute.internal   Ready    worker   44m   v1.16.2
ip-10-0-69-37.us-east-2.compute.internal    Ready    master   56m   v1.16.2
ip-10-0-84-68.us-east-2.compute.internal    Ready    worker   44m   v1.16.2
ip-10-0-85-210.us-east-2.compute.internal   Ready    master   56m   v1.16.2


After few node additions
-------------------------------
[shylesh@localhost ocs-ci]$ ./bin/oc --kubeconfig ~/shmohanupi/auth/kubeconfig get csr 
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-7978w   14m   system:node:ip-10-0-58-8.us-east-2.compute.internal                         Approved,Issued
csr-klqxp   14m   system:node:ip-10-0-56-213.us-east-2.compute.internal                       Approved,Issued
csr-lfbsx   14m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-rscv5   14m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-tmrkz   15m   system:node:ip-10-0-53-216.us-east-2.compute.internal                       Approved,Issued
csr-trlm9   15m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued


Finally my test failed with 
----------------------------------
17:47:01 - MainThread - ocs_ci.utility.csr - WARNING - Some nodes are not generated CSRs. Expected 15 but found 9 CSRs.retrying again
17:47:01 - MainThread - ocs_ci.utility.csr - INFO - Retrieving CSR data
17:47:01 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/shylesh/shmohanupi/auth/kubeconfig get csr  -n default -o yaml
FAILED       
```

Let me know if I missed something here.

**Comment by petr-balogh** [comment]
Good to know @shylesh , that's what I've basically asked here:  https://github.com/red-hat-storage/ocs-ci/issues/1941#issuecomment-624482460  if the CSR will vanish or not :) and seems they will what you explained here.  Thanks for explanation. @vavuthu  Be aware of this.

**Comment by vavuthu** [comment]
> Good to know @shylesh , that's what I've basically asked here: [#1941 (comment)](https://github.com/red-hat-storage/ocs-ci/issues/1941#issuecomment-624482460) if the CSR will vanish or not :) and seems they will what you explained here. Thanks for explanation. @vavuthu Be aware of this.

That the reason why I had https://github.com/red-hat-storage/ocs-ci/pull/1995/files#diff-da5af5766904307b6dcbf4c4ee2a04d9R1093-R1096 and https://github.com/red-hat-storage/ocs-ci/pull/1995/files#diff-da5af5766904307b6dcbf4c4ee2a04d9R1104-R1107

Basically before calling wait_for_all_nodes_csr_and_approve, I am checking whether we have any existing CSRs or not. Based on that data, I am calculating the number of CSRs need to check.
