### ISSUE TITLE
Method wait_for_resource() should be able to abort in case of unrecovereable condition

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#1954]
Method `OCP.wait_for_resource()` should be able to abort waiting in case of a condition when it no longer makes sense to wait, eg. when waiting for a pod to be running, but it ends up in unrecoverable Error state instead.

Since this depends on a caller, it should be implemented via optional argument `abort_condition`, which would specify the state in the same way as condition.

**Comment by RazTamir** [comment]
That's interesting.

How this functionality works in OCP? 
No matter what is the usecase for us as QE, we should stick to OCP behavior to not miss bugs. 

Regarding your example, if the pod reached to unreasonable condition, don't we want to fail on timeout?

**Comment by mbukatov** [comment]
Maybe I should have also noted that the abort of the waiting should be immediately reported as an error in a similar way as a timeout (via exception). This won't go unnoticed.

Whether this feature is suitable depends on a particular use case, as I noted.

For example, I deploy a Job which writes 100GiB and set a timeout accordingly to one hour. Then during this timeout while I'm waiting on it's completion, a problem hits and the job fails. Being able to detect this and abort the waiting early when it's clear that the job can't finish will make the test case to report the problem faster.

**Comment by RazTamir** [comment]
Ok,
Now it is more clear. 
Will be interesting to see the implementation
