### ISSUE TITLE
ocs_ci.ocs.cluster.CephCluster.cluster_health_check should check the storagecluster PHASE

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1962]
Storage cluster phase should be validated as part of cluster health check. It should be 'Ready'

**Comment by AviadP** [comment]
re opening this issue. this need a bit of discussion for some edge cases (or not so edge) such as post upgrade, noobaa only failure, cluster expansion and maybe more. however, it must be addressed, because it could fail many tests without real reason
