### ISSUE TITLE
Tag AWS instances with cleanup rules instead of using cluster-name prefixes

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1975]
Currently we prepend a special prefix to cluster_names to adjust how the clusters are handled during our execution of aws-cleanup. Instead of using the cluster-name (which we already run into name length issues with) it might be more appropriate to tag these clusters with some key/value that we can read in during aws-cleanup to determine if the cluster should live longer than the default value.

This would require changes to:

1. Jenkins job configurations to allow users to set a value for this tag
2. Added capabilities to the deployment process to tag the clusters
3. Changes to aws-cleanup to read in the tag instead of using the cluster_name to make special case determinations.

@ebenahar I'm not sure if you explored this at all during your initial implementation of aws-cleanup, but I'm curious to see what you think about this approach.

**Comment by ebenahar** [comment]
@clacroix12 this sounds like a great idea! this would be much more robust and flexible.
I haven't explored this option as we needed a quick solution for periodic cleanup and therefore, used what we already have, which is the instance names.

**Comment by petr-balogh** [comment]
Looks like a good idea @clacroix12 .
Basically what we need is to tag only the VPC and do it only after successful deployment as it will prevent to have those cluster not be cleaned if the job will fail somewhere in the middle of the deployment and also in teardown and someone will miss that.
