### ISSUE TITLE
Running Rook tests as our tier0

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#199]
In order to get more tests running in a quicker way, we will need to run Rook tests [1] in our CI in OpenShift.
Currently, the tests are running only on K8s but to enable those on OCP I talked with Travis and from his words, it seems not too much needs to be done to enable those on OCP:
"The only differences between running on K8s and OpenShift should be what is described in this topic
https://rook.io/docs/rook/v1.0/openshift.html

The differences are basically:
Create an SCC to grant privileges to the rook operator
Change a setting in the operator definition for running mons privileged.

See the description of the operator-openshift.yaml here. If you use that yaml instead of operator.yaml, it will be configured for OpenShift.
https://rook.io/docs/rook/v1.0/ceph-examples.html

Note that we have an upstream issue for this as well. I just added a comment for how I see this enabled for openshift:
https://github.com/rook/rook/issues/1841#issuecomment-499674012

Sounds like you’d want to submit a PR for the first item in that comment, which would enable you to run it in the downstream CI. Actually enabling the openshift tests in the upstream Jenkins CI could be left as a separate work item."

[1] https://github.com/rook/rook/tree/master/tests/integration

**Comment by vasukulkarni** [comment]
We can discuss in the meeting further, 

a) What tests are part of the tier0
b) disabling the tests that are not required

**Comment by vasukulkarni** [comment]
@dahorak assigning this to you for now, @petr-balogh FYI

**Comment by vasukulkarni** [comment]
As per Petr moved to Engineering, Closing.
