### ISSUE TITLE
Add Polarion ids to the tests added in PR 1977

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1998]
https://github.com/red-hat-storage/ocs-ci/pull/1977

**Comment by RazTamir** [comment]
Hi @Shrivaibavi ,

Added you as assignee to this ticket as this test case added by you - https://github.com/red-hat-storage/ocs-ci/pull/1977/files#diff-973590c31bec9e363a97a3e6bb1c0eb1R31
