### ISSUE TITLE
Add auto reserveration of DC based on freepool

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1999]
Add option to ocs-ci to reserve VMware DC based on availability and free pool

**Comment by clacroix12** [comment]
@vasukulkarni are you looking to add functionality to ocs-ci to somehow interact with the jenkins lockable resources or are you looking for a way to schedule jobs in jenkins without having to specify the precise DC it will execute on?

**Comment by vasukulkarni** [comment]
@clacroix12 I am looking into setting up a db(mongo or similar) and setting up lock/unlock based on DB.

The option I have in my mind is `--use-free-vmware-dc` and `--unlock-vmware-dc`

I am not looking from jenkins or locakable resource plugin.

**Comment by clacroix12** [comment]
Would this not potentially conflict with the lockable resources? If a DC was chosen via this DB then it would still remain 'unlocked' in jenkins, which would allow a job to select that DC and potentially have two deployments going to the same DC at the same time.

**Comment by vasukulkarni** [comment]
worth discussing in our next call, we can use the cli option there in jenkins as well as it will allow better utilization of all resources and keep the DB updated by default for all cases.
