### ISSUE TITLE
modify ocp installer url for downloads

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2002]
From Trevor:  ( He pointed out for clients but I see the installer as well, the directory structure differs from the existing one we have in the code)
```
https://mirror.openshift.com/pub/openshift-v4/clients/ , on the other hand, is something we point customers at, so that (and our other mirrors) should be reliable
```

**Comment by petr-balogh** [comment]
@vasukulkarni we are using mentioned mirror for GAed versions of OCP as you can see in this config:
https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocp_version/ocp-4.3-ga-config.yaml

But we rely on https://openshift-release.svc.ci.openshift.org/ for nightlies:
As we need to somehow get latest nightly version which passed the acceptance tests we are using thise json file:
https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.3.0-0.nightly/latest

Which pointing us to latest nightly build as you can see

```json
{
  "name": "4.3.0-0.nightly-2020-05-04-051714",
  "phase": "Accepted",
  "pullSpec": "registry.svc.ci.openshift.org/ocp/release:4.3.0-0.nightly-2020-05-04-051714",
  "downloadURL": "https://openshift-release-artifacts.svc.ci.openshift.org/4.3.0-0.nightly-2020-05-04-051714"
}
```

In the mirror you mentioned are no nightlies and for GAed version/candidate we already using mentioned. So closing this. If you have any point here please elaborate more but if there are issues in unavailable service how can we solve this from our side?  If you have more details from other place take the nightlies and how other read the latest available version than from mention json please let us know.

Thanks

**Comment by petr-balogh** [comment]
If you or anyone else is blocked by deploying nightly and you really don't care atm to deploy nighly you can use GAed version by passing `OCP_VERSION` parameter in our job like 4.4-ga for example.

Or if deploying locally using --ocp-version parameter and specify this 4.4-ga as its value.
