### ISSUE TITLE
Project directory restructure

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#207]
There have been several concerns about the structure of our project at the moment. A lot of this stems from the origins and evolution of the project. This issue will focus on organizing the directories into a structure that makes sense for us now. 

Proposed changes:

- Contents of `oc` and `mita` move to `ocs` module.
- `Resources` module moves to `ocs` module.
- Removal of `suites` directory.
- Removal of `run.py` (old test runner).
- Rename `ocsci` module to something like `framework` (suggestions welcome) to avoid confusion with `ocs` module. 

This leaves us with something that looks like this:
```
ocs-ci/
    conf/
        examples/
    docs/
    ocs/
        resources/
    framework/
        pytest_customization
    templates/
        CSI/
        ocs-deployment/
        pv_pvc/
        reporting/
    tests/
        e2e/
        ecosystem/
        manage/
    unittests/
    utility/
```

Thoughts, concerns, and suggestions welcome.

**Comment by clacroix12** [comment]
Another idea using a more standard python project approach. Essentially moving all source under `ocs_ci`, keeping only unit tests (for now) and docs at the top level.
```
ocs-ci/
    docs/
    ocs_ci/
        conf/
        ocs/
        framework/
        templates/
        tests/
        utility/
    unittests/ (this eventually gets removed in favor of unit tests localized to their respective modules)
```

**Comment by RazTamir** [comment]
+1 for the first with few questions:
- why docs not under framework? or a similar place?
- conf, the same question
 besides that looks good

**Comment by clacroix12** [comment]
@RazTamir docs are for more than just the framework as they include things like how to write tests, how to contribute to the project as a whole, and coding guidelines that apply everywhere. I don't see them as something that ONLY applies to the framework so I wouldn't put it under that directory. 

`conf` could definitely move somewhere else but I'm not sure framework is the right place either. Once we get rid of the defaults yaml there the only thing that is left is the optional cluster configuration files, but these are really only used for the deployment.

**Comment by clacroix12** [comment]
Something else to add to this is that we have `tests/helpers.py`. As such I think having a `utility` module at the top level is probably unnecessary. These will most likely end up being framework specific functions and as such can be consolidated with the `framework` module as well. 

Note `utility` needs some serious attention as there is a lot of code to be cleaned up here. Lots of remnants of ceph-ci and the old runner. This will be taken up in another issue but I think it's worth mentioning.

**Comment by zmc** [comment]
I'm not sure if we want a separate issue for this, but something we could do either as part of this effort or before it is removing dead code. [vulture](https://pypi.org/project/vulture/) looks like it could be really helpful here.

**Comment by zmc** [comment]
@clacroix12 I like your pythonic approach the most so far. Some of the subdirs might want to get renamed, removed, or split up, but that's less interesting here.

I think it's worth considering leaving the OCS tests (read: not unit tests) outside of the main package.

@RazTamir It's pretty standard practice to place user-facing docs outside of the package directory in a python project

**Comment by clacroix12** [comment]
@zmc I'm leaning towards that approach as well. So with your suggestion we would essentially have three top level dirs: `docs`, `ocs_ci`, and `tests`? This is assuming the `unittests` dir goes away since we will have unit tests inside their respective modules.

**Comment by zmc** [comment]
@clacroix12 yeah, that seems right. #210 already removes the `unittests` dir as well!

**Comment by mbukatov** [comment]
> Something else to add to this is that we have `tests/helpers.py`.

And this module should not be there: https://github.com/red-hat-storage/ocs-ci/issues/120

**Comment by mbukatov** [comment]
> I think it's worth considering leaving the OCS tests (read: not unit tests) outside of the main package.

I agree, and I read the proposal that this idea holds: `ocs-ci` being the root directory of the repository, so `tests` is a top level directory in the same way as `ocs` directory which is a python module.

**Comment by vasukulkarni** [comment]
@clacroix12 +1 for the first one

**Comment by clacroix12** [comment]
> @clacroix12 +1 for the first one

Is there a reason why we shouldn't go with the standard python package approach?

**Comment by vasukulkarni** [comment]
> > @clacroix12 +1 for the first one
> 
> Is there a reason why we shouldn't go with the standard python package approach?

I totally missed that one, but yes to moving them under ocs_ci if it helps for packaging as one, but the goal is still to clone and run tests.

**Comment by vasukulkarni** [comment]
What about the  .py files residing in TOP DIR?

**Comment by clacroix12** [comment]
@vasukulkarni Yeah ideally our usage won't change with this restructure. This is simply to organize the project, not make any functional changes to the workflow.

> What about the .py files residing in TOP DIR?
They can remain where they are, I'm mostly concerned with directories/modules with this. If there are specific files we want to relocate let's identify them but we can always take that up in another issue/PR.

**Comment by mbukatov** [comment]
The first approach looks ok, but I would try to limit number of root python modules minimal so that it's clear what belongs to where.

Wrt 2nd approach, I think that having single `ocs_ci` python module is a good idea, but I would not included `tests` (already mentioned by @zmc ) and `conf` inside. Basically anything which won't be in the end tracked and installed by setuptools.

**Comment by zmc** [comment]
Ah, good point. `conf` doesn't need to be in the python package, and once we move to single-defaults, it will really just be a set of example configs.

**Comment by clacroix12** [comment]
> Basically anything which won't be in the end tracked and installed by setuptools.

Would this also include `templates`?

**Comment by mbukatov** [comment]
> > Basically anything which won't be in the end tracked and installed by setuptools.
> 
> Would this also include `templates`?

Templates would work both ways, because these are basically static files which could be packaged in the python module just fine.

You could either keep templates in root directory of the repo and then access them assuming these files are in the pwd, or keep it in the module and access it referencing to the module.

**Comment by clacroix12** [comment]
Okay so after taking recent comments into consideration we can potentially do the following:
- `unittests` goes away
- `conf` moves to top level
- `tests` moves to top level
- `utilites` are directed to one of two places, either `ocs` or `framework` depending on the nature of the utility.

Which gives us something like this:
```
ocs-ci/
    conf/  (currently custom configuration examples)
    docs/  (user documentation)
    ocs_ci/
        ocs/  (classes and functions that interface with the product)
        framework/  (custom python plugin, reporting, utilities)
        templates/  (templates for deployment, resource creation, reporting, etc.)
    tests/  (OCS tests)
```

**Comment by mbukatov** [comment]
I closed https://github.com/red-hat-storage/ocs-ci/issues/120 noting that this will be done as part of this bigger restructure work. It needs to be aligned anyway and it's good not limit overlapping issues.

**Comment by mbukatov** [comment]
What is the status now? Do we wait for some test cases to be merged and if yes, which are these?

**Comment by zmc** [comment]
Yeah, we should definitely at least get that one merged first.

**Comment by clacroix12** [comment]
> Another question is whether we want to merge #173 first (which seems to be a good idea)

Definitely want to get this one merged first. I'm wondering if we want to do this restructure all at once and cause a big disruption or if we can somehow do it in pieces to lessen the impact.

**Comment by mbukatov** [comment]
> I'm wondering if we want to do this restructure all at once and cause a big disruption or if we can somehow do it in pieces to lessen the impact.

I would like to do this at once, with an agreement on a schedule with all stakeholders.

But maybe we could stage it as well, by:

* creating the future structure all at once, but without moving anything there
* selecting a group of directories and move it to the new place without moving the rest

The grouping could be selected based on work and discussion related to particular move, or to optimize impact on the open pull requests. But if someone has pull request open during few such stages, it could  mean more work for the author in the end.

**Comment by clacroix12** [comment]
> But if someone has pull request open during few such stages, it could mean more work for the author in the end.

This is my fear as well. In trying to avoid conflicts we could potentially cause more if these were delayed enough. 

My thinking is this: create the `ocs_ci` top level module and place all relevant modules under that leaving `conf`, `docs`, and `tests` outside(at the top level). This will be the biggest structural change and will have an impact on open PRs. Following that in subsequent PRs we can perform the tasks of consolidating modules like `oc` -> `ocs`, refactoring `ocsci` into `framework`(still not sure about this name, could use suggestions), migrating things in `utilities` to either `framework` or `ocs` depending on what they do, etc. 

We would have an initial impact due to the directory restructure but I think we could reduce the impact of all the other things if we get that in place first. The other option is to do the complete opposite. Consolidate and refactor the modules where they are now and finalize it with the package restructure under the `ocs_ci` module.

**Comment by mbukatov** [comment]
> My thinking is this: create the `ocs_ci` top level module and place all relevant modules under that leaving `conf`, `docs`, and `tests` outside(at the top level). This will be the biggest structural change and will have an impact on open PRs. Following that in subsequent PRs we can perform the tasks of consolidating modules like `oc` -> `ocs`, refactoring `ocsci` into `framework`(still not sure about this name, could use suggestions), migrating things in `utilities` to either `framework` or `ocs` depending on what they do, etc.

This is very good idea. It strike a right balance between doing all the changes at once vs having long discussion about every refactoring/move/change one by one. There will be some additional plumbing work required in the 1st step (eg. setuptools config, locating static files inside ocs_ci via module, not working directory), but this is negligible compared to consolation and refactoring which will follow in subsequent pull requests.

**Comment by clacroix12** [comment]
Completed in #301
