### ISSUE TITLE
[LSO] test_add_capacity does not work over VMware

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#2074]
`tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacity::test_add_capacity` fails in LSO based deployment over VMware, even though additional disks are present in the workers nodes to be used by the testcase to create additional PVs

One such failed run [here](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/1689/testReport/)

Error message seen:
```
>           f"Current Available PV count is {current_count}"
        )
E       AssertionError: Current Available PV count is 0

ocs_ci/ocs/resources/storage_cluster.py:594: AssertionError
```

Output from 1 worker node where an additional disk was present
```
$ oc debug nodes/rhel1-2.sagrawal-vm-rhel.qe.rh-ocs.com
--snip--
sh-4.2# lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0   120G  0 disk 
|-sda1          8:1    0     1G  0 part /boot
`-sda2          8:2    0   119G  0 part 
  |-rhel-root 253:0    0 117.4G  0 lvm  /
  `-rhel-swap 253:1    0   1.6G  0 lvm  
sdb             8:16   0   1.8T  0 disk 
`-ceph--2772f3ef--74a2--4d61--b543--90541a88244c-osd--block--a2dfed7c--d908--4a63--9a5e--fbdec7e1b0b9
              253:2    0   1.8T  0 lvm  
sdc             8:32   0   1.8T  0 disk 
rbd0          252:0    0    40G  0 disk /var/lib/kubelet/pods/a5a170d6-b87e-4118-af88-9acdd3e4fbdb/volumes/kubernetes.io~csi/pvc-99ec54e1-5b24-408a-8544-487734
loop0           7:0    0   1.8T  0 loop 

```

**Comment by anubhav-here** [comment]
Well, this happened because while initially creating LVCR, use of ```wwn``` disks identifiers were made and the logic for testcase fetches for ```scsi``` identifiers.  
So, even though both identifiers (disk ids) pointed to the same disk, they were treated as different.
I would suggest using ```scsi disk ids``` during deployment to avoid this issue.

**Comment by sidhant-agrawal** [comment]
Closing this issue based on above comment.
