### ISSUE TITLE
requests and urllib packages are not compatibles

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#2086]
when running destroy cluster job, following error accrued:
`requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.9 which is incompatible.`

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/5698/console

**Comment by clacroix12** [comment]
I was able to resolve this locally by upgrading to the latest requests `2.23.0`.
