### ISSUE TITLE
test_ocs_336_346 is failing

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#209]
@shreekarSS please re-test on an up to date branch and send PR to fix this test case

**Comment by RazTamir** [comment]
Also, the test is not cleaning everything and there are few leftovers in case of failure (secret and storageclass)

**Comment by ebondare** [comment]
Also, the names of the test functions are swapped: test_basics_cephfs is using CSI_RBD_SECRET_YAML, CSI_RBD_STORAGECLASS_YAML etc, while test_basics_rbd uses CSI_CEPHFS_SECRET_YAML, CSI_CEPHFS_STORAGECLASS_YAML and CSI_CEPHFS_PVC_YAML

**Comment by vasukulkarni** [comment]
Closing stale issue.
