### ISSUE TITLE
Verifying ceph osd tree output and checking for device set PVC names in the output. fails for LSO setup

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#2097]
failure:- https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7603/console

  def validate(instance, schema, cls=None, *args, **kwargs):
        """
        Validate an instance under the given schema.
    
            >>> validate([2, 3, 4], {"maxItems": 2})
            Traceback (most recent call last):
                ...
            ValidationError: [2, 3, 4] is too long
    
        :func:`validate` will first verify that the provided schema is
        itself valid, since not doing so can lead to less obvious error
        messages and fail in less obvious or consistent ways.
    
        If you know you have a valid schema already, especially if you
        intend to validate multiple instances with the same schema, you
        likely would prefer using the `IValidator.validate` method directly
        on a specific validator (e.g. ``Draft7Validator.validate``).
    
    
        Arguments:
    
            instance:
    
                The instance to validate
    
            schema:
    
                The schema to validate with
    
            cls (IValidator):
    
                The class that will be used to validate the instance.
    
        If the ``cls`` argument is not provided, two things will happen
        in accordance with the specification. First, if the schema has a
        :validator:`$schema` property containing a known meta-schema [#]_
        then the proper validator will be used. The specification recommends
        that all schemas contain :validator:`$schema` properties for this
        reason. If no :validator:`$schema` property is found, the default
        validator class is the latest released draft.
    
        Any other provided positional and keyword arguments will be passed
        on when instantiating the ``cls``.
    
        Raises:
    
            `jsonschema.exceptions.ValidationError` if the instance
                is invalid
    
            `jsonschema.exceptions.SchemaError` if the schema itself
                is invalid
    
        .. rubric:: Footnotes
        .. [#] known by a validator registered with
            `jsonschema.validators.validates`
        """
        if cls is None:
            cls = validator_for(schema)
    
        cls.check_schema(schema)
        validator = cls(schema, *args, **kwargs)
        error = exceptions.best_match(validator.iter_errors(instance))
        if error is not None:
>           raise error
E           jsonschema.exceptions.ValidationError: 'argo005-ceph-redhat-com' is not one of ['ocs-deviceset-0-0-xtvrk', 'ocs-deviceset-1-0-shnl2', 'ocs-deviceset-2-0-9j2bc']
E           
E           Failed validating 'enum' in schema['properties']['name']:
E               {'enum': ['ocs-deviceset-0-0-xtvrk',
E                         'ocs-deviceset-1-0-shnl2',
E                         'ocs-deviceset-2-0-9j2bc']}
E           
E           On instance['name']:
E               'argo005-ceph-redhat-com'

venv/lib/python3.6/site-packages/jsonschema/validators.py:934: ValidationError

**Comment by jilju** [comment]
Deviceset PVC names won't be present in 'ceph osd tree' output. It will be hostnames instead. 
eg:

ID  CLASS WEIGHT  TYPE NAME                            STATUS REWEIGHT PRI-AFF 
 -1       2.72758 root default                                                 
 -8       0.90919     rack rack0                                               
 -7       0.90919         host argo005-ceph-redhat-com                         
  1   ssd 0.90919             osd.1                        up  1.00000 1.00000 
 -4       0.90919     rack rack1                                               
 -3       0.90919         host argo004-ceph-redhat-com                         
  2   ssd 0.90919             osd.2                        up  1.00000 1.00000 
-12       0.90919     rack rack2                                               
-11       0.90919         host argo006-ceph-redhat-com                         
  0   ssd 0.90919             osd.0                        up  1.00000 1.00000 


So ceph osd tree output should be modified to verify in LSO based cluster.

**Comment by vavuthu** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/3816 will fix the issue.
