### ISSUE TITLE
growing list of constants, probably some dont need to be there

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2098]
We can take a look at the constants.py and see if the individual tests are using it when not needed and those can be moved to specific tests.

**Comment by vasukulkarni** [comment]
@clacroix12 FYI based off our small discussion :)

**Comment by clacroix12** [comment]
Another thought I had was reorganizing constants into more granular modules similar to how we are trying to handle utilities. `constants.py`. As an example, the constants module has a lot of directory paths or filepaths. These could all be relocated to their own respective module under constants to help organize things a bit. I'm sure there are other common themes given `constants.py` is over 800 lines long at this point in time and growing.
