### ISSUE TITLE
Sequential Creation of PVC in AWS setup failes to Bound 2 out of 5 times.

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#2102]
Observing this problem consistently during Scale test ocs-ci run for every build.

PVCs are created sequentially without waiting for it to Bound, later validating either PVC Bound or Not and there were failures reported as PVC not bound due to timeout, please note not observing this problem in vmware cluster.

The problem could be due to execution speed, with respect to vmware setup observing bit slowness in execution this leads to proving ample time for PVCs in csi queue and it's getting Bound.

So How to resolve this Problem ? Is it good to change the code like create a PVC wait for it Bound and create next ? or is there some other solution.

Recent aws test run:  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7484/testReport/junit/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_multiple_pvc_creation_deletion_scale_ReadWriteOnce_CephBlockPool_/

Logs: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-ai3cl33-s/jnk-ai3cl33-s_20200513T203517/logs/failed_testcase_ocs_logs_1589405541/test_multiple_pvc_creation_deletion_scale%5bReadWriteMany-CephBlockPool%5d_ocs_logs/

**Comment by ramkiperiy** [comment]
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7824/

**Comment by keesturam** [comment]
@ramkiperiy can you update the latest developments on this issue? I believe we had a discussion and decision around this topic.

**Comment by ramkiperiy** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/2236

**Comment by ramkiperiy** [comment]
Have hit this problem thrice on 3rd July, most of the time we are hitting this problem when we run the tests using Jenkins and not observed when we execute the same test from laptop in same AWS setup. 
Note: Laptop is connected from home network(wifi).
I still suspect the problem could be the speed of execution in Jenkins.
@keesturam @vasukulkarni @petr-balogh @dahorak ^^

**Comment by ramkiperiy** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1812798

**Comment by ramkiperiy** [comment]
Waiting for CSI driver enhancement build in 4.6 in which PVC getting Bound perf improvement are planned.

**Comment by ramkiperiy** [comment]
Closing this issue since PR #3070 is already merged, also there is significant improvement in CSI driver from OCS 4.6 onwards.
