### ISSUE TITLE
restart_ec2_instances() should directly call reboot_instances instead of doing stop and start 

### ISSUE THREAD

**Issue by PrasadDesala** [red-hat-storage/ocs-ci#2103]
We should directly call reboot_instances instead of stop and start.
AWS i3 based OCS deployment, cannot tolerate Node shutdown but can hold node restarts.
Due to the current way of AWS reboot, we are kind of doing shutdown(stop/start) due to which some of the test cases which involves node reboot are failing on AWS i3.

    def restart_ec2_instances(self, instances, wait=False, force=True):
        """
        Stop and start ec2 instances

        Args:
            instances (dict): A dictionary of instance IDs and names to restart
            wait (bool): True in case wait for status is needed,
                False otherwise
            force (bool): True for force instance stop, False otherwise

        """
        logger.info(f"Restarting instances {list(instances.values())}")
        self.stop_ec2_instances(instances=instances, wait=wait, force=force)
        self.start_ec2_instances(instances=instances, wait=wait)

ocs-ci results for OCS4-4-Downstream-OCP4-4-AWS-IPI-3AZ-RHCOS-LSO-3M-3W-workloads (BUILD ID: v4.4.0-420.ci RUN ID: 1589409630

**Comment by ebenahar** [comment]
Ack. As this is an issue for i3 testing, marking as a bug
