### ISSUE TITLE
Test case proposal: post installation health check

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2106]
## Description

In [Chapter 2. Verifying your OpenShift Container Storage installation](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.3/html-single/deploying_openshift_container_storage/index?lb_target=production#verifying-your-openshift-container-storage-installation_rhocs) we list lot of details about the OCS internals for admin to check whether all ocs components were deployed as expected. Esp. table Table 2.1.  contains list of all ocs pods, including expected number of theirs replicas.

To avoid customer confusion when OCS internals changes either with new release, or on a particular platform, we should create a test case which will:

1) check what OCS version is running
2) compare running ocs pods with expected list, which comes from the documentation

Then when this test fails, we would know that:

- either cluster health is actually bad
- ocs internals changed compared to the docs, and doc update is needed

**Comment by ebenahar** [comment]
This is a great idea @mbukatov!
This is good as a test case. 
Is the intention to access the relevant OCS version docs automatically, parse the text and do the comparison based on that?
Also, how about having this validation as a feature in OCS? So this cluster scan will happen post deployment for the user

**Comment by mbukatov** [comment]
>  Is the intention to access the relevant OCS version docs automatically, parse the text and do the comparison based on that?

This would be imho bit overkill, moreover we won't be able to access source code nor yet unpublished draft. That said, I would likely use some script to transform text from the docs into a python structure which will represent the expected of pods during writing or updating of the test code.

Parsing documentation and performing checks is a bit different type of testing, which some  teams are already doing (eg. I'm aware that some rhel docs are checked for names of tools and it's command line arguments, which is then checked on actual machines ...). For OCS, we could something similar (eg. does this CRD exist in OCS?), but it would require us to make sure we follow OCP and doc team's expectations. It would also have to be internal only, integrated to our doc workflow.

>  Also, how about having this validation as a feature in OCS? So this cluster scan will happen post deployment for the user

This depends on the reasoning behind having this included in the docs. I assume that most of problems with pod deployments should be already covered by OCP itself (eg. when replication of given deployment is smaller than expected, pod is restarting over again, ..) as presented on OCP Console dashboard. And so this description in the docs is provided on top of this existing OCP self checking, as added value.

In this proposal, I'm concerned with checking whether the docs are still up to date with the actual reality.
