### ISSUE TITLE
set OC bin path when deployment is skipped

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#211]
I think shylesh noticed that in new terminal oc path is not set and it will fail when deployment test is skipped, It was working for me since I had oc in standard bin path, I think we should set this up when we skip the deployment test.

**Comment by mbukatov** [comment]
I [discussed this](https://github.com/red-hat-storage/ocs-ci/pull/49#discussion_r286123119) with @dahorak some time ago. Since we have a [pytest wrapper](https://github.com/red-hat-storage/ocs-ci/blob/master/run_ocsci.py) now, we could just export the path there.

**Comment by mbukatov** [comment]
After brief discussion with Daniel, I'm going to propose a fix.
