### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by mykaul** [red-hat-storage/ocs-ci#2127]
It seems we do not have any releases here. How do we know there's a 'stable' version of the test suite we can fetch and execute?
Can we have from time to time a tag or release?

**Comment by vasukulkarni** [comment]
Probably we can cut the release name based on match OCS, will discuss within team.

**Comment by mykaul** [comment]
I prefer a bi-weekly (twice a month) release or so. Just per OCS version is not granular enough.

**Comment by vasukulkarni** [comment]
To start with I think we are planning to match with OCS versions as we know the tests will be stable, bi-weekly will incur additional costs and runs to ensure the tests are clean on all platforms, probably better to be taken after we have the first tag based on released OCS versions.

**Comment by vasukulkarni** [comment]
First version is tagged and released, we can further look into how make it more periodic.

**Comment by mbukatov** [comment]
> Probably we can cut the release name based on match OCS, will discuss within team.

What is the purpose of the release versions in ocs-ci btw? If we create releases, does it mean that our CI should use latest release for production test runs? Does it mean that when other teams are running tests, they should use the release? What needs to be fulfilled on ocs-ci side to qualify current master branch to a new release? What is connection of this to OCS releases?

I don't see that noted neither in the docs neither any announcement about it. Without specifying that exactly and making sure everyone follows it I don't see any value in creating "releases".

> First version is tagged and released, we can further look into how make it more periodic.

I see you pushed git tag `v1.0.0` recently:

https://github.com/red-hat-storage/ocs-ci/releases/tag/v1.0.0

But python setuptools metadata hasn't been updated, so python plumbing tools would ignore that:

```
$ git blame setup.py | grep ' version='
c203c049c (Vasu Kulkarni              2016-10-11 10:39:46 -0700 11)     version='0.1',
```

This combined with lack of purpose and rules for ocs-ci releases only creates confusion, see also https://github.com/red-hat-storage/ocs-ci/issues/2351

**Comment by mykaul** [comment]
1. The point of STABLE releases is that we know tests are stable. If you continuously add tests, we have little confidence they are stable, yet they run on our CI continuously. With releases, you provide stability and predictability.
2. You do not need to maintain 'backward compatibility'. If you had workarounds in the tests for version X due to some reason, and now you are running a newer version which doesn't need that workaround, you risk in making your testing code more complex to accommodate both flows.

**Comment by vasukulkarni** [comment]
> > Probably we can cut the release name based on match OCS, will discuss within team.
> 
> What is the purpose of the release versions in ocs-ci btw? If we create releases, does it mean that our CI should use latest release for production test runs? Does it mean that when other teams are running tests, they should use the release? What needs to be fulfilled on ocs-ci side to qualify current master branch to a new release? What is connection of this to OCS releases?

Yaniv already explained it below and we also have it in meeting minutes and recordings,  It provides a record to go back easily to old version of test and run it to figure out if it worked or not (rather than go back to that specific commit and revert to that date and run) .

> 
> I don't see that noted neither in the docs neither any announcement about it. Without specifying that exactly and making sure everyone follows it I don't see any value in creating "releases".
> 
> > First version is tagged and released, we can further look into how make it more periodic.
> 
> I see you pushed git tag `v1.0.0` recently:
> 
> https://github.com/red-hat-storage/ocs-ci/releases/tag/v1.0.0
> 
> But python setuptools metadata hasn't been updated, so python plumbing tools would ignore that:
> 
> ```
> $ git blame setup.py | grep ' version='
> c203c049c (Vasu Kulkarni              2016-10-11 10:39:46 -0700 11)     version='0.1',
> ```
> 
> This combined with lack of purpose and rules for ocs-ci releases only creates confusion, see also #2351

Its a first release cut, so its not perfect, As usual if something is lacking github issue will help to fix them.
