### ISSUE TITLE
Checking for Logging, monitoring and registry during OCP upgrade.

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#2131]
Need to add health check for Logging, monitoring and registry during OCP upgrade as discussed in today's upgrade syncup meeting.

**Comment by AviadP** [comment]
@Shrivaibavi , can we close this issue ?

**Comment by Shrivaibavi** [comment]
Yes Since monitoring, logging and registry tests are part of tier 1 and monitoring and logging are part of post OCP upgrade and health check is also verified during these tests we can close this issue
