### ISSUE TITLE
wait_for_resource() times out even after pod is successfully created.

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#215]
After creating a pod, wait_for_resource() is failing for me even though pods are successfully created. 

With new implementation, when helpers.create_resource(desried_state, True, **dict) is called, it internally calls ocp.wait_for_resource(desired_status,resource_name). when a pod is created through these calls, the wait_for_resource is executing the commad "oc get DeploymentConfig <deploymentconfig name> -o yaml" and checking whether desired_state == sample.get('status').get('phase') which always returns None. Because of this it times out. 

I think expecting sample.get('status').get('phase') to show desired_state is possible only if "oc get" command is executed over "pod" that got created. This is because, oc get deployment does not have the output to scan the fields status followed by phase. 

I tried creating cirros pods and the wait_for_resource failed as mentioned above.

The output of oc get deployment can be found in http://pastebin.test.redhat.com/771119

**Comment by RazTamir** [comment]
Few questions @hnallurv ,
1) what do you expect to happen after creating DeploymentConfig? what are we waiting for? a pod?
2) how do you know if everything is ok? -> how can I know what to wait for if there is no status?

**Comment by vasukulkarni** [comment]
Closing stale issue.
