### ISSUE TITLE
Upgrade of OSD can take more than 10 mins if cluster is unhealthily

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2175]
We have to increase timeout for check OSD got upgraded based on discussion with Travis in BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1840729

**Comment by hnallurv** [comment]
Is this PR needed if this PR https://github.com/red-hat-storage/ocs-ci/pull/2173 merged?

**Comment by petr-balogh** [comment]
Yes, from BZ described it can take 10 mins per OSD to get upgraded so we in my fix I am setting timeout based on number of OSDs which will allow us to have whatever use case in the future.
