### ISSUE TITLE
Check status of quay before deployment

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2189]
With recent outages in quay will be worth to have some check if quay is functional.
https://status.quay.io/
Maybe we can read from this xml:
https://status.quay.io/history.rss

That how it looked during outage:
http://pastebin.test.redhat.com/869637

Also saved HTML how the page looks like:
http://pastebin.test.redhat.com/869644

So we can find the way how to process those data.

**Comment by vasukulkarni** [comment]
also came out of discussion: https://status.quay.io/api

**Comment by petr-balogh** [comment]
There is ticket opened to add this quay to the semaphore here: https://projects.engineering.redhat.com/browse/DEVOPSA-4149

**Comment by petr-balogh** [comment]
Looks like probe is done in semaphore: https://projects.engineering.redhat.com/browse/DEVOPSA-4149 so we can implement in jesnkins job side.

**Comment by petr-balogh** [comment]
We have this check in jenkins job
