### ISSUE TITLE
AWS LSO deployment failed in ceph osd tree verification

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#2192]
AWS LSO deployment failed with below error in verification

===================
>           raise error
E           jsonschema.exceptions.ValidationError: 'ip-10-0-143-151' is not one of ['ocs-deviceset-0-0-mtsk8', 'ocs-deviceset-1-0-f8wbf', 'ocs-deviceset-2-0-fl2pw']
E           
E           Failed validating 'enum' in schema['properties']['name']:
E               {'enum': ['ocs-deviceset-0-0-mtsk8',
E                         'ocs-deviceset-1-0-f8wbf',
E                         'ocs-deviceset-2-0-fl2pw']}
E           
E           On instance['name']:
E               'ip-10-0-143-151'
===================

More info at: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8191//console

**Comment by jilju** [comment]
['ocs-deviceset-0-0-mtsk8', 'ocs-deviceset-1-0-f8wbf', 'ocs-deviceset-2-0-fl2pw']
This is the list from ceph osd tree. For portable osds, we should see host names instead of osd PV names.
