### ISSUE TITLE
[Green Squad] While running IOs on multiple fedora DC pods simultaneously in test_rwo_pvc_fencing_unfencing, fio command fails with exit code 137

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#2205]
In pv_services/test_rwo_pvc_fencing_unfencing.py tests, sometimes while running IOs on multiple DC pods simultaneously, fio command fails with exit code 137

Error message seen:
```
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n namespace-test-3be893a7c1f24cc5b54c6aef912fc987 --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig rsh pod-test-cephfs-a8f80adb1e8a43a1a6604e07090d2529-1-ppk9q fio --name=fio-rand-readwrite --filename=/mnt/io_file1 --readwrite=randrw --bs=4K --direct=1 --numjobs=1 --time_based=1 --runtime=30 --size=1G --iodepth=4 --invalidate=1 --fsync_on_close=1 --rwmixread=75 --ioengine=libaio --rate=1m --rate_process=poisson --output-format=json. Error is command terminated with exit code 137
```
This issue is not consistent but has been observed in two different runs(different tests).

One such recent failure observed in Run ID:1590613343 [here](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8136/testReport/tests.manage.pv_services.test_rwo_pvc_fencing_unfencing/TestRwoPVCFencingUnfencing/test_rwo_pvc_fencing_node_short_network_failure_dedicated_4_3_True_/)

Another failure seen in Run ID:1589031331 [here](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7377/testReport/junit/tests.manage.pv_services.test_rwo_pvc_fencing_unfencing/TestRwoPVCFencingUnfencing/test_rwo_pvc_fencing_node_short_network_failure_colocated_3_1_False_/)

This inconsistent issue needs further analysis for a guaranteed fix that whether the issue is with low memory limits or due to IOs running on multiple pods simultaneously.

**Comment by jilju** [comment]
The pod will be restarted.  I have seen this recently in some test runs. As we develop more test cases which uses fedora pods, the number of failures in test execution will increase. 
```
 Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```
