### ISSUE TITLE
Requirement of a script to collect rook ceph logs upon test run failure

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#221]
Currently, when an automated test case fails (even due to product issue), we only get the run logs saved in /tmp. 

It would be helpful to have rook-ceph container logs also collected so as to be able to use them in raising product bugs.

Please suggest.

**Comment by vavuthu** [comment]
@nehaberry : If I understand correctly, we want to collect container logs when a test case fails and exit from the run, so that we can have cluster in the same state where test case fails?

**Comment by nehaberry** [comment]
@vavuthu yes correct. 
Following logs will be helpful in case of any test failure for raising bugs:
1. Collect all pod logs of openshift-storage product
2. The test run log saved as part of test run
3.  the versions and image names

It would help if tearodwn/cleanup is performed after these logs are collected.

**Comment by vavuthu** [comment]
Assigning to myself.

**Comment by vavuthu** [comment]
PR #327 submitted

**Comment by vavuthu** [comment]
Closing the bug as PR is merged

**Comment by vasukulkarni** [comment]
Closing as its working.
