### ISSUE TITLE
Apply WA mentioned in BZ#1841611 in tests "test_automated_recovery_from_failed_nodes_IPI_reactive[rbd/cephfs-shutdown]"

### ISSUE THREAD

**Issue by PrasadDesala** [red-hat-storage/ocs-ci#2212]
Below two tests are failing because of BZ  https://bugzilla.redhat.com/show_bug.cgi?id=1841611

test_automated_recovery_from_failed_nodes_IPI_reactive[rbd-shutdown]
test_automated_recovery_from_failed_nodes_IPI_reactive[cephfs-shutdown]

We need to apply the WA mentioned in the BZ in both testcases and continue testing the functionality.

**Comment by am-agrawa** [comment]
BUILD ID: 4.11.1-5 RUN ID: 1662653139

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py::TestAutomatedRecoveryFromFailedNodes::test_automated_recovery_from_failed_nodes_IPI_reactive[rbd-terminate]
```
2022-09-08 22:54:44  17:24:41 - MainThread - ocs_ci.ocs.machine - ERROR  - New spun node failed to reach ready state OR Replica count didn't match ready replica count
```

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py::TestAutomatedRecoveryFromFailedNodes::test_automated_recovery_from_failed_nodes_IPI_reactive[cephfs-terminate]
```
2022-09-08 23:25:56  17:55:52 - MainThread - ocs_ci.ocs.machine - ERROR  - New spun node failed to reach ready state OR Replica count didn't match ready replica count
```

Jenkins logs- https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/5353/consoleFull

@PrasadDesala Do you think it's the same bug?
