### ISSUE TITLE
Error after IO thread: fio: pid=0, err=30/file:filesetup.c:138, func=unlink, error=Read-only file system

### ISSUE THREAD

**Issue by shyRozen** [red-hat-storage/ocs-ci#2230]
In pv_services.test_resource_deletion_during_pod_pvc_deletion.TestDeleteResourceDuringPodPvcDeletion::test_disruptive_during_pod_pvc_deletion[CephBlockPool-delete_pvcs-operator]
from this [run](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8209/) After IO there are some pods with exit code 137 which is handled in [issue](https://github.com/red-hat-storage/ocs-ci/issues/2205)

**Comment by mbukatov** [comment]
What you describe here looks like a product bug, fio tries to delete file(s), but can't because the volume is ready only.
