### ISSUE TITLE
Add production and perf lables for VMware DCs

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2232]
when we create the VMware DC we should add Production and Performance label to distinguish the DCs so that tests that involve running Perf or E2E can use that labels to skip if it doesn't meet the requirements.

**Comment by petr-balogh** [comment]
it depends on how much clusters are also up and running in the same DC which we cannot know from any kind of the label.  If this is need to be done, we can require more lockable resources on the DC and can have for such executions parameter in the jenkins, then the job itself will reserve for example 2 or more lockable resources for one execution and will wait for all of those to be free before start of the execution.

**Comment by keesturam** [comment]
@vasukulkarni With the latest changes, do we need any fix here?
