### ISSUE TITLE
test_node_expansion does not apply the workaround of #1151 which causes failures in other tests of tier1

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#2238]
test_node_expansion does not apply the workaround of #1151 after adding RHEL node which causes failures in other tests of tier1.

Error message seen in test_node_maintenance while running fio
```
Error is fio: pid=0, err=13/file:filesetup.c:162, func=open, error=Permission denied command terminated with exit code 1
```

Runs where the issue was observed:

ocs-ci results for OCS4-4-Downstream-OCP4-3-AWS-UPI-3AZ-RHEL7-3M-3W-tier1 (BUILD ID: v4.4.0-437.ci RUN ID: 1590771916)

ocs-ci results for OCS4-4-Downstream-OCP4-4-AWS-UPI-3AZ-RHEL7-3M-3W-tier1 (BUILD ID: v4.4.0-437.ci RUN ID: 1590575283)

**Comment by ebenahar** [comment]
Need to run `'/usr/sbin/setsebool -P container_use_cephfs on'` for the newly added RHEL worker nodes. See reference here https://github.com/red-hat-storage/ocs-ci/blob/07bffd4dd3b62ea54a1f4650e9d5f7eb1ef1b066/ocs_ci/deployment/deployment.py#L150
