### ISSUE TITLE
Option to run command asynchronously

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#225]
It will be helpful to have an option like this -
Run a command locally and ignore. Later, check the status of the command and fetch the result.

**Comment by RazTamir** [comment]
Hi Jilju,
Can you provide a background for this request?

**Comment by jilju** [comment]
> Hi Jilju,
> Can you provide a background for this request?

@RazTamir 
This is to address change request https://github.com/red-hat-storage/ocs-ci/pull/208#discussion_r292865732

**Comment by jilju** [comment]
PR #227 is merged. Hence closing this issue.
