### ISSUE TITLE
Deployment of logging is stuck for long time on OCP 4.5

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2256]
Same story again as here: https://github.com/red-hat-storage/ocs-ci/issues/1812

But for OCP 4.5.

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8466/console

We should prevent this to happen to be stuck for that long time even if it's not suppose to work on this version cause of non GA version it's blocking resources on AWS for long time for retrying.

**Comment by petr-balogh** [comment]
@Akarsha-rai @Shrivaibavi did you take a look and did some AI for fixing this issue or should I create again this skipif we had here: 
https://github.com/red-hat-storage/ocs-ci/pull/1990/files

**Comment by Shrivaibavi** [comment]
@petr-balogh For Now I am trying to pull images and Trying it out manually, In this week we are also syncing up with the OCP team to get a permanent fix as skipping/relying on OCP repos for permission for every GA version is not a permanent remedy for us. For now probably we can skip, If I could get a solution EOW or early next week, I can send a PR to fix and remove this skip.
@hnallurv @PrasadDesala Please suggest.

**Comment by petr-balogh** [comment]
I created WA for this issue https://github.com/red-hat-storage/ocs-ci/pull/2279 but I am not closing this one issue as this needs to be resolved different way. So let's keep this opened and get it fixed by the change @Shrivaibavi is working on.

@Shrivaibavi once fixed we need to revert WA PR.

**Comment by vasukulkarni** [comment]
@Shrivaibavi is there a fix for this? should we remove this workaround and let the test run?

**Comment by petr-balogh** [comment]
I think that OCP 4.5 is not relevant anymore here
