### ISSUE TITLE
[MCG] Remove service-ca workaround

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#2260]
At the moment, we cannot find the `service-ca.crt` file on OCP4.5 clusters, and thus have to copy the Ingress certificate to the AWSCLI pod and use the external NooBaa endpoints.

**Comment by mbukatov** [comment]
Related items:

- BZ  1845188
- https://github.com/red-hat-storage/ocs-ci/pull/2136

**Comment by marun** [comment]
The recommended source for the service ca is documented here:

https://docs.openshift.com/container-platform/4.4/authentication/certificates/service-serving-certificate.html#add-service-certificate-configmap_service-serving-certificate
