### ISSUE TITLE
Creation of openshift-storage-operatorgroup is not mentioned as pre-requisite anymore

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#2266]
When we are installing OCS via ocs-ci (both via yaml and UI), as a pre-requisite we are creating both `openshift-storage` *Namespace* and `openshift-storage-operatorgroup` *OperatorGroup* [[1](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L414),[2](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/templates/ocs-deployment/deploy-with-olm.yaml)]. Both those steps was in the past mentioned as pre-requisites in OpenShift console UI when installing OCS, but now only creation of `openshift-storage` Namespace is there mentioned as prerequisite:
![OCS_install_pre_requisites](https://user-images.githubusercontent.com/4759779/84031063-53d65c80-a995-11ea-8f5f-cdff67e634d3.png)
And also [official installation documentation](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.4/html-single/deploying_openshift_container_storage/index) doesn't mention creation of OperatorGroup as prerequisite.

We should investigate, if creation of `openshift-storage-operatorgroup` OperatorGroup is requirement for installation via UI or yaml and update ocs-ci code accordingly.

**Comment by petr-balogh** [comment]
@dahorak did you have chance to take a look at it? You can easily verify to remove this part from our code and run deployment. So please try next week. I see it has High Priority label which you added, but probably not that high priority if didn't touch so far :)

**Comment by mbukatov** [comment]
Ah, as noted in https://github.com/red-hat-storage/ocs-ci/issues/2553 I believe the whole `deploy-with-olm.yaml` is no longer valid workaround.

**Comment by petr-balogh** [comment]
I see that the deployment failed:

```cmd = ['oc', 'create', '-f', '/tmp/subscription_manifest7duqku3x']
secrets = None, timeout = 600, ignore_error = False, kwargs = {}
masked_cmd = 'oc create -f /tmp/subscription_manifest7duqku3x'
completed_process = CompletedProcess(args=['oc', 'create', '-f', '/tmp/subscription_manifest7duqku3x'], returncode=1, stdout=b'', stderr=b...rver (NotFound): error when creating "/tmp/subscription_manifest7duqku3x": namespaces "openshift-storage" not found\n')
masked_stdout = ''
masked_stderr = 'Error from server (NotFound): error when creating "/tmp/subscription_manifest7duqku3x": namespaces "openshift-storage" not found\n'```

So my guess is that for CLI deployment we still need to do that as this is only created by UI deployment as openshift console create this automatically when you deploy via UI but when you deploy via CLI we need to handle ourself.

Will ask Umanga to confirm that.

**Comment by umangachapagain** [comment]
> I see that the deployment failed:
> 
> ```
> cmd = ['oc', 'create', '-f', '/tmp/subscription_manifest7duqku3x']
> secrets = None, timeout = 600, ignore_error = False, kwargs = {}
> masked_cmd = 'oc create -f /tmp/subscription_manifest7duqku3x'
> completed_process = CompletedProcess(args=['oc', 'create', '-f', '/tmp/subscription_manifest7duqku3x'], returncode=1, stdout=b'', stderr=b...rver (NotFound): error when creating "/tmp/subscription_manifest7duqku3x": namespaces "openshift-storage" not found\n')
> masked_stdout = ''
> masked_stderr = 'Error from server (NotFound): error when creating "/tmp/subscription_manifest7duqku3x": namespaces "openshift-storage" not found\n'
> ```
> 
> So my guess is that for CLI deployment we still need to do that as this is only created by UI deployment as openshift console create this automatically when you deploy via UI but when you deploy via CLI we need to handle ourself.
> 
> Will ask Umanga to confirm that.

The issue here is that "namespace" doesn't exist. If you're on CLI it must be created as the first step.

But, you don't have to create "Operator Group" which was previously listed as required.

**Comment by petr-balogh** [comment]
@umangachapagain when we try to deploy without adding operator group in OLM logs we see:

```
time="2020-11-30T13:39:51Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/openshift-storage/subscriptions/ocs-operator
time="2020-11-30T13:39:51Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/openshift-storage/subscriptions/ocs-operator
time="2020-11-30T13:39:51Z" level=info msg=syncing id=px/HI ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:51.921411       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:51Z" level=info msg=syncing id=WT+5A ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:51.932334       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:51Z" level=info msg=syncing id=PQgEz ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:51.947677       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:51Z" level=info msg=syncing id=f8Sb/ ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:51.973560       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:52Z" level=info msg=syncing id=amArn ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:52.019529       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:52Z" level=info msg=syncing id=6YkQE ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:52.106355       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:52Z" level=info msg=syncing id=TKBmy ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:52.273901       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
time="2020-11-30T13:39:52Z" level=info msg=syncing id=aARMG ip=install-qsw5h namespace=openshift-storage phase=Installing
E1130 13:39:52.600072       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
```

And no CSV appears for OCS.  So my guess is that for CLI deployment we still need to add both as we did. The namespace + operator group.

**Comment by umangachapagain** [comment]
> @umangachapagain when we try to deploy without adding operator group in OLM logs we see:
> 
> ```
> time="2020-11-30T13:39:51Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/openshift-storage/subscriptions/ocs-operator
> time="2020-11-30T13:39:51Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/openshift-storage/subscriptions/ocs-operator
> time="2020-11-30T13:39:51Z" level=info msg=syncing id=px/HI ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:51.921411       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:51Z" level=info msg=syncing id=WT+5A ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:51.932334       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:51Z" level=info msg=syncing id=PQgEz ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:51.947677       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:51Z" level=info msg=syncing id=f8Sb/ ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:51.973560       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:52Z" level=info msg=syncing id=amArn ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:52.019529       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:52Z" level=info msg=syncing id=6YkQE ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:52.106355       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:52Z" level=info msg=syncing id=TKBmy ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:52.273901       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> time="2020-11-30T13:39:52Z" level=info msg=syncing id=aARMG ip=install-qsw5h namespace=openshift-storage phase=Installing
> E1130 13:39:52.600072       1 queueinformer_operator.go:290] sync {"update" "openshift-storage/install-qsw5h"} failed: attenuated service account query failed - no operator group found that is managing this namespace
> ```
> 
> And no CSV appears for OCS. So my guess is that for CLI deployment we still need to add both as we did. The namespace + operator group.

If you are creating Subscription via CLI then you need to create OperatorGroup. If you are creating Subscription via UI then you don't need to create OperatorGroup.

I believe this is how it works. Sorry for confusion.
