### ISSUE TITLE
Modify cluster_expansion.test_add_capacity_with_node_restart to restart OCS nodes

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2276]
While analyzing an ocs-ci failure for tier4a with Itzhak and Prasad, it was seen that as part of the **cluster_expansion.test_add_capacity_with_node_restart** test case, we are restarting a worker node. But in the tier4a execution, the setup ultimately has 6 W nodes, though not all W nodes are OCS nodes 

We select 1 worker node for reboot [here](https://github.com/red-hat-storage/ocs-ci/blob/a806a081a8a1f2e4fda9122c3fead15f5158483a/tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py#L20) but we end up in restarting a non-OCS node. But it is meaningful to restart an OCS node after add capacity.

**Node restart:**
https://github.com/red-hat-storage/ocs-ci/blob/a806a081a8a1f2e4fda9122c3fead15f5158483a/tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py#L91

**Comment by yitzhak12** [comment]
I created a new PR regarding this issue: https://github.com/red-hat-storage/ocs-ci/pull/2280

**Comment by nehaberry** [comment]
Since PR 2280 is MErged, @yitzhak12 can this be closed.
