### ISSUE TITLE
Enhancement get_osd_size() to support LSO cluster

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#2290]
Enhancement to support LSO cluster:
 * Function: osd_size = get_osd_size()
 * Test case used:  TestScaleOSDsRebootNodes

**Comment by ramkiperiy** [comment]
run log: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8246/testReport/junit/tests.e2e.scale.test_pods_are_not_oomkilled_while_running_ios/TestPodAreNotOomkilledWhileRunningIO/test_pods_are_not_oomkilled_while_running_ios_CephBlockPool_/

**Comment by ramkiperiy** [comment]
Not observed this problem in recent runs, also there is consistent improvement around this function, closing this issue
