### ISSUE TITLE
Add a double-dash to the Ceph health check base command

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#2292]
Currently, the `ceph_health_check_base` function uses `oc exec` without a double-dash (`--`), which leads to a deprecation warning - 
```
09:54:44 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-5685c79ff4-7fvg9 ceph health
09:54:47 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
```

I already ran one test where I added a double-dash to the command, and it seems to work properly, so this should be a low hanging fruit.

**Comment by AviadP** [comment]
fixed by https://github.com/red-hat-storage/ocs-ci/pull/2474
closing it
