### ISSUE TITLE
[MCG] Validate RGW pod existence on on-prem clusters and non-existence on cloud based ones

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#2296]
Should be added to https://github.com/red-hat-storage/ocs-ci/blob/08bb1d9e37df8038d48891d79d5192b29c58834e/ocs_ci/ocs/cluster.py#L131

**Comment by ebenahar** [comment]
Edit:
Validation of BM should be added to ocs_ci.ocs.resources.mcg.MCG.__init__

**Comment by MeridianExplorer** [comment]
I believe this is taken care of - https://github.com/red-hat-storage/ocs-ci/blob/062c74a1bf9a697a3bfaa9ff3f836464e3629ed3/ocs_ci/ocs/resources/mcg.py#L127-L144

So I'm allowing myself to close the issue :) 
Please reopen if I missed something
