### ISSUE TITLE
Support multicloud scenarios

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#2304]
This issue *does not* refer to testing NooBaa while it's deployed on one of those.
This issue *does* refer to testing backingstores that use those services as their *target storage* supplies.

Cloud providers and systems that need to be supported. prioritized:
- [x] AWS S3
- [x] PVPool
- [x] IBM COS (S3 compatible)
- [x] Azure Blob Storage
- [x] Google Cloud Storage

**Comment by bernerhat** [comment]
addressed in #3437
