### ISSUE TITLE
OCS deployment fails to create monitoring after ocs uninstall from docs

### ISSUE THREAD

**Issue by shyRozen** [red-hat-storage/ocs-ci#2317]
After uninstalling ocs from documentation, ocs-ci deployment (with skip ocp) fails because the config map is still there. Need to check if there is a config map, change it as needed.
Workaround is to delete configmap manually before deployment.

**Comment by petr-balogh** [comment]
@shyRozen Hey, isn't that documentation bug then? And not something which we should take care of in ocs-ci?

If config map exists from previous deployment I guess it has to be documented that it has to be deleted during the uninstall process as well.
