### ISSUE TITLE
oc_create_aws_backingstore is defined on 2 places

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2344]
Similar function `oc_create_aws_backingstore` is defined in files:

 - ocs_ci/ocs/resources/mcg.py
 - tests/manage/mcg/helpers.py

Those functions have the same functionality and should be defined only on one canonical place.

**Comment by MeridianExplorer** [comment]
Currently, the function only exists under `bucket_utils`, so I'm closing the issue :)
