### ISSUE TITLE
Add root access via securityContext to pods that require it

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#2368]
OCP 4.5 changes the default pod user from root to an underprivileged one.
This causes two known failures:
1. The `awscli_relay_pod` cannot create the `/cert/` dir required for the workaround. Fixed in #2272 
2. `test_deployment` and other tests that rely on our default NGINX pod fail because it enters a `CrashLoopBackOff` since it required root permissions. When I replaced the image with `nginxinc/nginx-unprivileged` it was not sufficient because we try to install `fio` and `git` on the pod as part of `fio.py` and `jenkins.py`.

Using the solution offered by @petr-balogh allows root access once more, and thus the issue title was changed.

**Comment by petr-balogh** [comment]
Can we fix this by adding this:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/templates/app-pods/rhel-7_7.yaml#L15-L17 to the pod CR?

**Comment by petr-balogh** [comment]
Updated question also in BZ.

**Comment by MeridianExplorer** [comment]
@petr-balogh 
I edited `awscli.yaml`, `fedora_dc.yaml`, `nginx.yaml`, `raw_block_pod.yaml` under `ocs_ci/templates/app-pods`, and `pod.yaml` under `CSI/cephfs` and `CCSI/rbd` - `test_deployment` passed successfully.

**Comment by petr-balogh** [comment]
Cool @MeridianExplorer , do you heve PR you can link here?   I think that as quick fix for our CI we should go with this fix and then see status in the BZ and think of better change. But if we need root access in those pods I think it's only one solution if they did some different permission as default one in OCP 4.5.  Thanks

**Comment by MeridianExplorer** [comment]
The SCC change was reverted, rendering this issue obsolete
