### ISSUE TITLE
Test ocs-288 comments

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#241]
Hi @prsurve ,

Few comments on test ocs-288.py
1) the tier level should be changed according to the Polarion
2) usage of delete_all_storageclass and delete_all_pvcs is not good:
In case you want to use such function you have to provide a list of resources to delete and never delete all as it can impact future changes to the product or our deployment (we might want to create few storageclasses after deployment to save time for each test to do that every time?)

**Comment by prsurve** [comment]
Fix for 1st comment is present in #228

**Comment by vasukulkarni** [comment]
Closing stale issue.
