### ISSUE TITLE
Enable debug level for OSDs and other daemons during deployment

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2438]
Currently, many bugs are moved back to QE in the absence of debug logs from ceph daemons.

Hence, after a discussion in chatroom [[1]](https://chat.google.com/room/AAAAREGEba8/Wk-z0qSxI4k), it was proposed that once the [BZ-1852852](https://bugzilla.redhat.com/show_bug.cgi?id=1852852) is ON_QA and part of OCS 4.5 builds, we can enable **debug_osd 30** through toolbox pod after OCS deployment. Current default is 5

**Command to be run in toolbox**
ceph config set osd debug_osd 30
OR
ceph --debug-ms 1 config set osd debug_osd 30

** As per engg, it would be good to enable debugging for MGR and MON as well. We need to check the current level and run the command accordingly.

Rook Issue - https://github.com/rook/rook/issues/5744

[[1]](https://chat.google.com/room/AAAAREGEba8/Wk-z0qSxI4k)

**Comment by nehaberry** [comment]
@vavuthu the bug https://bugzilla.redhat.com/show_bug.cgi?id=1852852 is ON_QA now

We are safe to increase the log level for our benefit in the ocs-ci installs.

**Comment by vavuthu** [comment]
@nehaberry : In current implementation debug logs are enabled by default, raised bug https://bugzilla.redhat.com/show_bug.cgi?id=1877714

**Comment by vavuthu** [comment]
Closing this issue as debug logs for osd are enabled by default. No chnages are requird from ocs-ci perspective
