### ISSUE TITLE
Fix env checker for deployment and destroy

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#246]
Deployment is now broken cause of #237 didn't count with deployment test is adding resources

**Comment by RazTamir** [comment]
Why deployment test is inheriting from the base class?

**Comment by petr-balogh** [comment]
@RazTamir it inherit from ecosystem test which inherit from base test class as other team's tests

**Comment by RazTamir** [comment]
Ohh..
