### ISSUE TITLE
Deployment of vSphere over LSO failed with ceph health warn

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#2463]
When deploying a cluster with vSphere over LSO, with OCP 4.4, OCS 4.4. the deployment has failed with the error:
"ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN clock skew detected on mon.b". Here is the link to Jenkins build: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/9590/.

**Comment by petr-balogh** [comment]
@vavuthu this we saw a lot on DC 25 right? Looks like this one is on DC 27.  Not sure what is happening when the NTP seems to be set correctly on the machines, at least DC 25 which I've checked yesterday.

**Comment by vavuthu** [comment]
@petr-balogh we are seeing this issue on all DC's having VSAN. I am working on DC25 and once that is done, I will revisit all the DC's

**Comment by vavuthu** [comment]
@yitzhak12 DC25, DC26 and DC27 is fixed. Verified DC25 and it working without any ceph health warns.
