### ISSUE TITLE
Document how to use special parameters for Azure

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2464]
in code are required values from config like 
```
config.ENV_DATA.get("azure_subscription_id")
config.ENV_DATA['azure_client_id']
config.ENV_DATA['azure_client_secret']
config.ENV_DATA['azure_tenant_id']
config.ENV_DATA['azure_resourcegroup']
```
but it is not documented or no configuration with those values exist.

**Comment by mbukatov** [comment]
This way of handling Azure credentials were removed in 472b3a5741e70dc166a482ba5511dc0948a6b084, so it's no longer necessary to have this documented.
