### ISSUE TITLE
vSphere runs is not deploying with production values

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#2465]
below jenkins runs uses the production config but vms are not deployed with production values

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/9634/console

**Comment by petr-balogh** [comment]
I see the values are propagated and merged in the config correctly: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/vavuthu-ocs45/vavuthu-ocs45_20200709T073100/logs/run-1594280219-config.yaml

Is this issue that the values are not properly propagated to the terraform?

**Comment by vavuthu** [comment]
> I see the values are propagated and merged in the config correctly: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/vavuthu-ocs45/vavuthu-ocs45_20200709T073100/logs/run-1594280219-config.yaml
> 
> Is this issue that the values are not properly propagated to the terraform?

Yes, from ENV_DATA it has to propagate to terraform which has issue
