### ISSUE TITLE
Allow permission to download kubeconfig even if jenkins run is in progress

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2468]
We get kubeconfig after OCP install. Hence , even though OCS install is in progress and jenkins run is not over, user should be able to download the kubeconfig from Jenkins page, so that if one needs to verify something on the cluster, he can do it.

E.g. while trying to wget the kubeconfig from [this run](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/9652/console) I got permission denied message. OCS install was in progress.

```
[nberry@localhost auth]$ wget http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-pr2466-b2263/jnk-pr2466-b2263_20200709T095543/openshift-cluster-dir/auth/kubeconfig
--2020-07-09 16:10:54--  http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-pr2466-b2263/jnk-pr2466-b2263_20200709T095543/openshift-cluster-dir/auth/kubeconfig
Resolving magna002.ceph.redhat.com (magna002.ceph.redhat.com)... 10.8.128.2, 2620:52:0:880:225:90ff:fefc:2776
Connecting to magna002.ceph.redhat.com (magna002.ceph.redhat.com)|10.8.128.2|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-07-09 16:10:56 ERROR 403: Forbidden.
```

**Comment by petr-balogh** [comment]
Hey Neha,

yep, we know about this and as we are running the installer it's creating auth folder in installer with specific permission. Once the job will finish this stage in the pipeline we have the code which changing the permission of this file to allow you to download it. I added this to the automation mtg agenda today and we will try to come up with some solution.

**Comment by dahorak** [comment]
@petr-balogh are you working on this? I think, that something like following command executed before the `run-ci` command (before line 310 in file `jobs/pipelines/qe_deploy_ocs_cluster/Jenkinsfile`) might work:
```
(until [[ -d ~/current-cluster-dir/openshift-cluster-dir/auth ]]; do sleep 5; done; chmod o+rX -R ~/current-cluster-dir/openshift-cluster-dir/auth)&
```

I didn't try it in jenkins though, so not sure, if it correctly handles the process in background.

**Comment by petr-balogh** [comment]
@petr-balogh I've proposed some similar approach on last automation mtg but haven't started with this yet. Feel free to take it @dahorak ;)
