### ISSUE TITLE
Tar log files for sharing

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2475]
As discussed in the meeting, I just tried to take a  tar without must_gather and for this specific run with few failures it added about 800+ MB (on top of whatever it takes )

```

$ pwd
.../ocsci-jenkins/openshift-clusters/pbalogh-ind2/pbalogh-ind2_20200618T133943

$ tar --exclude='*gather*' -cvf  ~/logs_without_must_gather.tar .
.
.
.

$ du -h ~/logs_without_must_gather.tar 
816M	/home/vasu/logs_without_must_gather.tar

#all logs -  had to cancel the tar command after couple of minutes  :)
$ du -h ~/logs_all.tar 
8.5G	/home/vasu/logs_all.tar

```

**Comment by vasukulkarni** [comment]
Forgot to add -z (to create .gz) , this will further reduce by 1/8th roughly, so 111MB not that bad.

**Comment by ebenahar** [comment]
> Forgot to add -z (to create .gz) , this will further reduce by 1/8th roughly, so 111MB not that bad.

was that done with must gather excluded?

**Comment by vasukulkarni** [comment]
> > Forgot to add -z (to create .gz) , this will further reduce by 1/8th roughly, so 111MB not that bad.
> 
> was that done with must gather excluded?

yes this one is without must gather.

**Comment by shylesh** [comment]
Another thing I have been trying but not succeeded so far
```
1. Have a dedicated PSI instance especially for this log compression purpose, this instance will have NFS mount from magna002.
2. An NGINX sever will be running on this instance
3. NGINX provides few facilities to play with, one of them is taking our own actions whenever a request arrives on a specific directory OR path.
4. for ex a snippet from NGINX conf file:
============================
            location = /logs {
            set $path $arg_logpath;

            content_by_lua_block {
                local args, err = ngx.req.get_uri_args()
                for key, val in pairs(args) do
                    os.execute("/bin/myshellscript.sh " ..val)
                end
            }
            rewrite logs?logpath=$path ^logs/(a-z+)/? break;
        }
==============================

what above lines does is , whenever a request comes on /logs dir we can run arbitrary lua code in our case I am running a shell script with a parameter extracted from URL. so idea is if we get an URL like "http://host/logs?logpath=/ocsci_user_log" , then we can extract log dir name and pass it to shell script which can do whatever we want, like create a gzipped file and put it in a known location. Then we can return this gzipped file to the client.

So far I was able to successfully run all the steps but while returning it to the client there is some problem and browser can't get the proper zipped file. May be if somebody familiar with web stuff can help here.

Advantages
=========
1. Dynamic gzipping saves lot of space
2. On Jenkins side minimal code change, Just generate an URL in the Job page.

Disadvantages
==========
1. Since zipping happens based on requests , it might take longer times based on log file size
2. I am not sure about throught put of this approach if we have multiple requests at the same time

Thoughts??

**Comment by clacroix12** [comment]
@shylesh The goal of this issue is to allow us to download the logs for a particular run easily. The concerns of compressing the logs for each execution is that it adds to the amount of space each execution is taking up on the filesystem. It seems like your approach, while more complex than simply compressing every log directory, provides a solution to the issue while avoiding the major downside.

I can still go ahead with the tarball approach for now to get something working quickly, but I think this is something worth exploring and I'd like to see if @ebenahar and @vasukulkarni have any thoughts or input.

**Comment by vasukulkarni** [comment]
I think here we just want to gzip the mustgather and not every file, the nginx is also fine but I think the timing is not guaranteed. In our case since we know when we collect the logs and have the handle on logs dir we could gzip faster and rm the plain must gather.

**Comment by clacroix12** [comment]
This has been done in our jenkins job definition
