### ISSUE TITLE
TimeoutSampler didn't finish after timeout expired

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2480]
In [check that upgrade is finished](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/ecosystem/upgrade/test_upgrade.py#L45) is used TimeoutSampler. Timeout is set to 750 seconds (12 minutes) but even after more than an hour there is no timeout exception.

**Comment by mbukatov** [comment]
This could happen when a call performed during an iteration takes longer than the timeout itself. That said, when the call finally finishes, TimeoutSampler should raise the TimeoutExpiredError after all.

To fix this, you would need to use a timeout inside a fuction passed to timeout sampler. Or maybe a TimeoutSampler isn't a right way to handle this if you expect that a timeout won't be breached: eg. by running the function in a separate process which you will be (maybe) able to kill after a timeout.

**Comment by mbukatov** [comment]
For a simple stuff, one can use [`threading.Timer`](https://docs.python.org/3.6/library/threading.html#timer-objects).
