### ISSUE TITLE
logs | test_report.html should also include nobba-core internal version (upstream) 

### ISSUE THREAD

**Issue by liranmauda** [red-hat-storage/ocs-ci#2507]
Currently test_report.html report the noobaa core version like this:
`noobaa_cor | mcg-core@sha256:049ba73bee755ebb4503c4beab834f0b95f67df3376257e875a24584866eca0e`

<b>Note: there is TYPO there (spells noobaa-cor)</b> 
This image has the SHA of the quay.io 

We should also like to have the output of `cat package.json | grep version` from the container.
the output should look like: `5.5.0-3dba413`

this output contains 3dba413 which are the 7 digits of the upstream beach commit.

**Comment by mbukatov** [comment]
It would be better if we make sure this internal version is provided in metadata of container image hosted on quay.io, so that anyone could see this version if necessary.

**Comment by ebenahar** [comment]
@petr-balogh should this issue be tracked here or in Jira?
