### ISSUE TITLE
Remove platform specific values from default_config.yaml file

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2523]
Right now, we have 3 different places where some default values for AWS platform are placed (global defaults in `ocs_ci/framework/conf/default_config.yaml`, j2 templates of openshift-installer config files `ocs_ci/templates/ocp-deployment/install-config-aws-*.yaml.j2` and actual deployment config files in `conf/deployment/aws/`).

To be able to support multiple platforms, we need to remove all platform specific values from list of global default values in default_config.yaml file.

## Example of use case which doesn't work

When I create the following config files for another cloud platform (eg. Azure):

- `ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2`
- `conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml`

The OCP installer is still trying to install with AWS defaults, which comes from default_config.yaml file.

**Comment by mbukatov** [comment]
I'm resolving this in my wip branch for Azure deployment support.

**Comment by petr-balogh** [comment]
We had offline conversation with @mbukatov and I've tried to explain that we depend on those variable not just in deployment but also other parts of the code and we cannot just have null or no values for them.

So we thought about implement some dynamic load of config which can by the default option but when we pass production config files we should reflect them in our production runs and not use dynamic config.

**Comment by mbukatov** [comment]
That said, I still believe that we have no choice but to remove all platform related values in default global config.

**Comment by mbukatov** [comment]
Related issue: https://github.com/red-hat-storage/ocs-ci/issues/2527
