### ISSUE TITLE
OCS4.4-->4.5 upgrade: does not create 2nd rook-ceph-rgw pod

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#2532]
fresh OCS 4.5 cluster created 2 rook-ceph-rgw pods, which fails ` verify_image_versions()` during OCS upgrade validation 
workaround might be needed, for more details see: https://bugzilla.redhat.com/show_bug.cgi?id=1857802

**Comment by ebenahar** [comment]
Re opening as the fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1857802 were reverted and we will have 1 RGW post upgrade

**Comment by AviadP** [comment]
@ebenahar, im closing this issue as bug fixed already, and it refer to very OCS versions
