### ISSUE TITLE
OCS-CI Independent Mode setup Failures

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#2545]
Tried Using ocs-ci for executing scale tests to create pvc and pod, adding the failures which I observed during test run. Most of the failures should be common to any tier.

1. default_config.yaml needs changes for independent mode cluster name https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/conf/default_config.yaml#L98
2. constants.py needs changes for independent mode cluster https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py#L156
3. SC names needs update in constants.py https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py#L157
4. Need to ignore all ceph pods related checks in CephCluster class code https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/cluster.py#L34 
5. Ceph RGW pod check needs to be ignored in independent mode.

**Comment by MeridianExplorer** [comment]
Point 2 already partially addressed [here](https://github.com/red-hat-storage/ocs-ci/pull/2322/files#diff-4a13a8b5f9156be9c09612daec5e3587)

**Comment by sidhant-agrawal** [comment]
6. Update `CEPHFILESYSTEM_NAME` in https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/defaults.py#L24

**Comment by shylesh** [comment]
@sidhant-agrawal , do you know if all the necessary changes for Tier1 and other tests for external mode has been merged ?

**Comment by sidhant-agrawal** [comment]
Point 6 will be addressed in #2856

**Comment by sidhant-agrawal** [comment]
@shylesh specific updates to fix/skip the tests will be addressed via these issues #2837, #2838, #2854
