### ISSUE TITLE
Disable workaround deploy-with-olm.yaml

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2553]
We have `deploy-with-olm.yaml` file which contains:
- namespace `openshift-storage`
- `openshift-storage-operatorgroup`

It's no longer necessary to create these entities (as of current OCS 4.4), so the deployment code should not create them for cluster versions which no longer requires such workaround.

**Comment by Avilir** [comment]
That is correct, but, since we are still supporting older version (4.3 for instance) we need the ability to deploy them.
So, IMO, we should have a marker which will said if we need to use this file or not.

**Comment by mbukatov** [comment]
Yes, this needs to be disabled for since particular version of OCS. It has nothing to do with pytest markers.

**Comment by dahorak** [comment]
Based on https://github.com/red-hat-storage/ocs-ci/issues/2266#issuecomment-736320390 creating the Namespace and OperatorGroup is not required for UI installation, for cli installation it is still required.
