### ISSUE TITLE
Consider Collecting must-gather for teardown failures

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2558]
At times, many teardown failures are due to genuine issues with deletion but in the absence of the logs, it becomes difficult to troubleshoot the cause.

Though it will be an overhead and hence we can have a discussion, but IMO, collecting must-gather after teardown failures will be helpful.

**Comment by vasukulkarni** [comment]
I will be surprised if its not collecting must-gather after teardown failures :)

**Comment by vasukulkarni** [comment]
That is true: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/pytest_customization/ocscilib.py#L399

**Comment by vavuthu** [comment]
@nehaberry @vasukulkarni Only teardown or do we need to collect logs for setup failures as well ?

**Comment by ebenahar** [comment]
Sorry @vavuthu just saw you are already assigned to the issue and I already sent a PR
