### ISSUE TITLE
Ensure Add OSDs happen before or after upgrade

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2575]
Based on the PG imbalance issues and bz and the huge timeout it may need, we need to separate out the add osd logic out of upgrade suite to keep it clean for regression runs.

**Comment by petr-balogh** [comment]
We are discussing this with @ebenahar and he created this PR:
https://github.com/red-hat-storage/ocs-ci/pull/2570

I wanted to remove for now this test for upgrade till it will be fixed. And we need to make sure that all the rebalance will really complete before we will continue with upgrade.  Elad is testing it now, so we will see if it solve the issue.

Based on conversation with Elad, this has to be tested and is valid scenario that customer will run upgrade after adding capacity, so this should be part of the upgrade, but we need to make sure to have everything OK after add capacity.

Or did you mean something else @vasukulkarni ?

**Comment by vasukulkarni** [comment]
@petr-balogh I saw that PR and I feel it should be removed from the *base* upgrade regression, it can be a separate upgrade test after add osd, that test is just causing overall upgrade test to fail.

**Comment by petr-balogh** [comment]
If it will be fixed properly and test will wait till all is OK I think it can be part of upgrade if it will not take ages.  @ebenahar or what are your thoughts?

Other option to have this test enabled only when we pass specific config file which will have value  allow_add_capacity_before_upgrade. If this is not specified the test will be skipped, then we will need to think of to execute with this config file at least once to test this.

**Comment by vasukulkarni** [comment]
I am +1 for the cli or config option that will enable this when needed instead of default.
