### ISSUE TITLE
Enable junit XML report for every run by default

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2580]
When I want to have junit xml report for a test run executed by `run-ci`, I specify it's filename via `--junit-xml` option like:

```
$ run-ci --cluster-path ~/data/cluster-azure-2020-07-23a
--ocsci-conf=conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
--ocp-version 4.5-ga --ocs-version 4.4 -m tier1
--junit-xml=azure-4-4-1.tier1.noobaa-wa.xml tests
```
This is a pytest feature, and since we are not using pytest directly, but via `run-ci` wrapper, it should be possible to have this enabled by default so that for every run, appropriately named XML junit report will be generated.

**Comment by clacroix12** [comment]
This can easily be done by adding to our [pytest.ini](https://github.com/red-hat-storage/ocs-ci/blob/master/pytest.ini#L42)

**Comment by mbukatov** [comment]
I'm considering a naming scheme template for this file, so that people would not have to name it themselves. Esp. since this is expected to help others executing our tests.

But if we drop such idea, adding it to pytest.ini would work fine.

**Comment by petr-balogh** [comment]
I will bring this to today's automation agenda ;).  I am ok to have some default value to be there, but we still need to have possibility to overwrite the value by CLI parameter. 

I would add this file to the same as we have the log dir by default which I don't think we can by default define in the pytest.ini file.  I know the default logs are in /tmp so yeah, the default can go to the /tmp as well.

**Comment by vasukulkarni** [comment]
I looked at the xml file output in detail, I think it provides better format for parsing out errors (I am also looking at parsing out errors for some easy analysis and I could use this one too) 

Instead of custom name like azure-x.x.xml can we just stick with simpler name since its going to be unique within that test run? for ex: xunit.xml ?  Also might be helpful to attach to our email results as long as its within some byterange.

**Comment by mbukatov** [comment]
Minimal naming scheme would include a general static name and a timestamp (so that the file is not overwritten in a next run), like: `testrun-2020-07-31T11-20.xml`.
