### ISSUE TITLE
Collect must-gather even after a "Green/Successful" Tier runs/fresh deployment

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2598]
At times, there are no test failures in tier executions/deployment jobs and hence no logs are collected. But , many times, we still need some details about the cluster & the run. In the absence of any must-gather, it becomes difficult to get/provide those details

Some suggestions:
1. Collect ocs-must-gather after a successful deployment (this is a proof how cluster looked immediately after deployment and we would have deployment logs)

2. Collect ocs-must-gather & ocp-must-gather at the end of a tier execution, even in case when there were no failures. This helps in comparison, getting cluster info , etc.

**Comment by nehaberry** [comment]
@petr-balogh ocs-ci issue raised for the discussion about collecting OCS logs even after Green deployments/Tier executions

**Comment by petr-balogh** [comment]
@jimdevops19  can you take this up please?

Thanks

**Comment by jimdevops19** [comment]
@petr-balogh Sure.
