### ISSUE TITLE
OCP must gather is not collected when we fail to deploy OCP UPI AWS

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2617]
See the job:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/10474/console

I see no must-gather collected.

@clacroix12  can you please take a look?

**Comment by clacroix12** [comment]
Looks like this is happening because we are overriding `deploy_ocp` directly instead of `deploy_cluster`. I suspect the same thing is true for vsphere as I'm not seeing a call to `deploy_cluster` or `collect_ocs_logs` there either.

**Comment by clacroix12** [comment]
Must gather was attempted however this is the reason it was not run:

```
06:40:35 - MainThread - ocs_ci.ocs.utils - WARNING - Cannot find $KUBECONFIG or ~/.kube/config; skipping log collection
06:40:36 - MainThread - ocs_ci.ocs.utils - WARNING - Cannot find $KUBECONFIG or ~/.kube/config; skipping log collectio
```

**Comment by petr-balogh** [comment]
That's weird, as once the job was failed I was able to see kubeconfig file and was able to connect to the cluster.

**Comment by petr-balogh** [comment]
Closing this as I think we haven't seen this again or it got already fixed by some other change.
