### ISSUE TITLE
Documentation for setting up a quay.io auth in getting started doc is unclear

### ISSUE THREAD

**Issue by phlogistonjohn** [red-hat-storage/ocs-ci#2632]
As I've been working on learning how to use this ci tool and trying to improve the getting started doc (see PR #2586 ) I've come across difficulties understanding what exactly is needed for the quay.io access token in the "auth.yaml" file.

The document links to https://docs.quay.io/api/ and that document specifically says:
```
All calls to the Quay.io REST API must occur via a token created for a defined Application.
A new application can be created under an Organization in the Applications tab.
```

I tried using my "robot account" access token just for fun but that did not seem to work. I'm currently guessing that to create this access token the user must be a member of a specific organization on quay.io to access (some of?) the OCS images. If that's the case I'd like confirmation from the current team. We can then improve the docs to explain exactly what on quay.io is needed [1].

If not, could anyone make suggestions on where to look because in that case the quay.io documentation is unclear. Any other assistance with this would be appreciated.

[1] - Ideally, any public resources should probably not require membership to a particular organization. But from the quay.io docs I'm not sure if this is possible yet, or if there are any other alternatives.

**Comment by clacroix12** [comment]
From the quay.io doc:

> Note: The generated token will be created on behalf of the currently logged in user.

You are correct in that whoever is generating the token needs to have access to the organization / repositories that they are requesting information from through the API. We can explain this a bit more in our own doc if we think it's necessary, but in the interest of keeping that section concise I elected to not include information that was covered in the linked official doc.

Regarding public resources, quay.io might be public but the repositories that we are using are not. I'm not sure how we get around this (with regards to generating an access token). You can however (which we mention in the docs) use the token that is already generated for our team to use by requesting it if you do not have the ability to generate one yourself.
