### ISSUE TITLE
Test case for OCS-347 is broken

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#264]
The teardown of the test case is accessing `PVC` which is not defined:

```
tests.manage.test_rbd_csi_default_sc.TestCaseOCS347
Time Taken: 56.511s
```

```
def finalizer():
>       teardown()

tests/manage/test_rbd_csi_default_sc.py:21: 


    def teardown():
        """
        Tearing down the environment
        """
        log.info("Deleting PVC")
>       PVC.delete()
E       NameError: name 'PVC' is not defined

tests/manage/test_rbd_csi_default_sc.py:40: NameError
```

**Comment by parikshithb** [comment]
It is working in the latest master. I have attached log.

http://pastebin.test.redhat.com/774704

**Comment by mbukatov** [comment]
> It is working in the latest master. I have attached log.
> 
> http://pastebin.test.redhat.com/774704

Please provide a link to commit which fixed the problem.

**Comment by parikshithb** [comment]
Fixed the problem with teardown.  
Currently test is failing due to this bz : https://bugzilla.redhat.com/show_bug.cgi?id=1724179

**Comment by parikshithb** [comment]
Fixed. PR #393
