### ISSUE TITLE
load_auth_config() doesn't always contain AUTH key

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2648]
Function CloudManager calls [cred_dict = load_auth_config().get('AUTH')](https://github.com/red-hat-storage/ocs-ci/blob/8e153c6be5d4e1449d31f71fe4f391c561fc4b8a/ocs_ci/ocs/resources/cloud_manager.py#L34) and expects that in output of `load_auth_config` is key `'AUTH'`. It is not in AWS setup with OCS 4.5

**Comment by fbalak** [comment]
This function assumes local file configuration and should be configured.

**Comment by MeridianExplorer** [comment]
Please see #2623
