### ISSUE TITLE
configmap "awscli-service-ca" already exists Error

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2657]
There sometimes happens an error `configmap "awscli-service-ca" already exists`.
This happens because configmap `awscli-service-ca` is created from another place in the code. There should be check that `awscli-service-ca` already exists or name should be unique.

**Comment by MeridianExplorer** [comment]
Just to refine the description - 
The configmap isn't created in a different place in the code - it's create right before the AWSCLI pod under the same fixture - `awscli_pod_fixture`. However, if the pod creation fails, it seems like the cleanup never reaches the step in which it cleans up the configmap.
![image](https://user-images.githubusercontent.com/19227853/89730408-e0a99f00-da46-11ea-8f19-7b642a7020d9.png)
