### ISSUE TITLE
Validate PV pool backingstore creation over external clusters

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#2668]
Over external mode cluster, a PV pool is created as this is the fallback in case RGW backingstore doesn't exist.
We should add a validation for that in our automation and also make sure that the correct storageclass is being used

**Comment by nimrod-becker** [comment]
PV pool wil be created as a fallback when one of the following cannot be done:
- Cloud Platform, NooBaa does not create the default backing store for the cloud service (at the time of writing this, GCP is an example)
- Not a cloud platform, so we are on-prem, and there is no CephObjectStoreUser

Those are the cases when the fallback will happen. On external we do have RGW (on the external RHCS cluster) and also have the CephObjectStoreUser so we don't expect a pv pool.
