### ISSUE TITLE
Move wait_for_resource() out of OCP() class 

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#268]
In some cases, when we want to call wait_for_resource() for an existing resource that we don't have its corresponding instance, we must instantiate OCP() class.

For example, when we want to wait for a pod that already exists in the cluster, we need to instantiate OCP() class and only then to call wait_for_resource().

It would be better to have it as a function instead of OCP() class method.

**Comment by RazTamir** [comment]
Hi,

For every resource you have ocp initialization as part of it and you can just use pod_obj.ocp.wait_for_resource() 

Let's try to implement missing pieces in OOP way and not creating a long list of helper functions

**Comment by vasukulkarni** [comment]
Closing stale issue.
