### ISSUE TITLE
Move code from `run_ocsci.py` to `ocsci.main`

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#270]
When is #207 resolved, drop `run_ocsci.py` from root repo, moving the code into `ocsci.main` module entirely.

**Comment by mbukatov** [comment]
@dahorak originally planned to do this in https://github.com/red-hat-storage/ocs-ci/pull/261#discussion_r295866932, but we concluded that it's better to wait for #207 for us to resolve it properly with less work.

**Comment by gklein** [comment]
Is there any more work required here or can we close this issue?

**Comment by mbukatov** [comment]
I see that this hasn't been directly done, and now we has kind of pointless wrapper here:

https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/run_ocsci.py

To resolve this issue, we should drop this file.
