### ISSUE TITLE
Add polarion ID for snapshots test cases

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#2724]
https://github.com/red-hat-storage/ocs-ci/pull/2713

**Comment by agarwal-mudit** [comment]
Thanks @ebenahar, please add one for https://github.com/red-hat-storage/ocs-ci/pull/2680 also

**Comment by jilju** [comment]
This test case can be used.
OCS-251 - FT-CSI-Snapshot-Create: Create and restore snapshot of PVC

**Comment by agarwal-mudit** [comment]
Thanks @jilju Please create oen for CephFS also, above one can be used for RBD
I will be adding test case for CephFS also once current PR is merged.

**Comment by jilju** [comment]
The test case OCS-251 tests both cephfs and rbd PVC snapshot functionality.
Can this be achieved in automated test case ?

**Comment by agarwal-mudit** [comment]
I am planning to add like this in the same test case:

@pytest.mark.parametrize(                                                                                                                       
      argnames=["interface"],                                                                                                                     
      argvalues=[                                                                                                                                 
      ┆   pytest.param(                                                                                                                           
      ┆   ┆   constants.CEPHBLOCKPOOL, marks=pytest.mark.polarion_id("")                                                                          
      ┆   ),                                                                                                                                      
      ┆   pytest.param(                                                                                                                           
      ┆   ┆   constants.CEPHFILESYSTEM, marks=pytest.mark.polarion_id("")                                                                         
      ┆   )                                                                                                                                       
      ]                                                                                                                                           
  )                       

If same ID works for the above two parameters, I am fine.
