### ISSUE TITLE
Increase timeout of 'Machineconfigpool' when deploying a cluster with vSphere

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#2735]
I had a failed OCS deployment when deploying with vSphere with the configurations: OCP 4.4, OCS 4.4.1, DC-CP.
Here is a link to the cluster: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/11129/
and this is the error we got: 
```
08:48:49 - MainThread - ocs_ci.ocs.ocp - INFO - status of worker at column READYMACHINECOUNT was 2, but we were waiting for 3
08:48:49 - MainThread - ocs_ci.ocs.ocp - ERROR - timeout expired: Timed Out: (900,)
08:48:49 - MainThread - ocs_ci.ocs.ocp - ERROR - Wait for MachineConfigPool resource worker at column READYMACHINECOUNT to reach desired condition 3 failed, last actual status was 2
```

It seems to me that increasing the timeout for the 'Machineconfigpool' with vSphere deployment can solve the issue, but I am not sure. Currently, the timeout is 900 as we can see here https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L2391.

**Comment by vavuthu** [comment]
@yitzhak12 Do you know how much its time taking to get the worker nodes up?

**Comment by yitzhak12** [comment]
I see it takes approximately 6-8 minutes for a worker node to come up

**Comment by yitzhak12** [comment]
Here is another Jenkins build that failed with the same error: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/11137/
