### ISSUE TITLE
Observing memory exhaust issue in Jenkins slave while running scale tests for 1500+ pod or pvc creations

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#2744]
The real problem is when there is continuous execution of creating/deleting pvc or pod in parallel, run-ci process memory consumption is increasing and its not dropping down which leads to failed to allocate memory.
Provided top output from a BM machine.

04:47:39 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - ERROR - Failed to collect OCS logs. Error: [Errno 12] Cannot allocate memory
04:47:39 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - ERROR - Failed to collect performance stats. Error: [Errno 12] Cannot allocate memory

Executed the same test in BM machine observed below output on top, and the memory consumption is growing.
    PID  USER    PR  NI  VIRT    RES  SHR   S %CPU  %MEM  TIME+   COMMAND
 589649 root      20   0   22.9g   4.0g  32264 S  106.6     1.1     31:23.51    run-ci

Another Top Output from BM machine
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                               
 589649 root      20   0   33.8g  10.4g  32264 S 105.3   2.8 187:39.56 run-ci    

```

                    # This matches the behavior of os._execvpe().
                    executable_list = tuple(
                        os.path.join(os.fsencode(dir), executable)
                        for dir in os.get_exec_path(env))
                fds_to_keep = set(pass_fds)
                fds_to_keep.add(errpipe_write)
                self.pid = _posixsubprocess.fork_exec(
                        args, executable_list,
                        close_fds, tuple(sorted(map(int, fds_to_keep))),
                        cwd, env_list,
                        p2cread, p2cwrite, c2pread, c2pwrite,
                        errread, errwrite,
                        errpipe_read, errpipe_write,
>                       restore_signals, start_new_session, preexec_fn)
E                       OSError: [Errno 12] Cannot allocate memory
```

Observed this problem in multiple Test runs
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/10814//console
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/10971/console
Weekend run: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/11024/

**Comment by vasukulkarni** [comment]
I will run this in debug mode in jenkins.

**Comment by ramkiperiy** [comment]
Have hit this problem 1 time yesterday in Jenkins slave execution

Behaviour:
In-case of Laptop execution you might see the laptop is getting slower or hung and it's the same with jenkins slave. When this happens run-ci command will either get killed or you will see the above mentioned memory allocator problem.

**Comment by ramkiperiy** [comment]
Started using kube_job for pvc_creation_deletion tests, observing lot of improvement wrt testcase execution time, also it reduced the memory consumption on the run-ci process, but still due to kube_job there will be stress in the OCP which need to be monitored.

Have created PR for PVC-creation-deletion https://github.com/red-hat-storage/ocs-ci/pull/3070 still need to explore on leverage kube_job to POD+PVC scale tests.

**Comment by ramkiperiy** [comment]
FIxed the problem of memory issue in PVC_Create_Delete_scale test using kube jobs, but need to work on implementing the same in pod+pvc creation scale test, so keeping this issue open until we fix the problem in existing automated tests.

**Comment by Avilir** [comment]
I observed the same error when trying to create 512 snapshots.
```08:32:29 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found Exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/pod.py", line 124, in get_fio_results
    result = self.fio_thread.result(FIO_TIMEOUT)
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/workloads/fio.py", line 89, in run
    return io_pod.exec_cmd_on_pod(fio_cmd, out_yaml_format=False)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/pod.py", line 158, in exec_cmd_on_pod
    rsh_cmd, out_yaml_format, secrets=secrets, timeout=timeout, **kwargs
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/ocp.py", line 128, in exec_oc_cmd
    ignore_error=ignore_error, **kwargs
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 415, in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 454, in exec_cmd
    **kwargs
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory```

IMO, we need to consider a different approach for scale tests, instead of using large number of objects (so we can use the teardown in the end), we can create the objects that we need without using fixtures so we will not save a lot of memory for all objects, and it the end of the test run a cleanup function as  teardown.

with this approach we will need memory for only one object.

@ramkiperiy @vasukulkarni WDYT ?
