### ISSUE TITLE
restart_nodes_by_stop_and_start_teardown is not implemented for BM

### ISSUE THREAD

**Issue by Akarsha-rai** [red-hat-storage/ocs-ci#2746]
On BM cluster when running tests `workloads.jenkins.test_jenkins_node_reboot.TestJenkinsNodeReboot::test_run_jenkins_node_reboot[master-3-7]`, it fails with following error:
```
    def restart_nodes_by_stop_and_start_teardown(self):
        raise NotImplementedError(
>           "Restart nodes by stop and start teardown functionality is "
            "not implemented"
        )
E       NotImplementedError: Restart nodes by stop and start teardown functionality is not implemented
```

**Comment by ebenahar** [comment]
@Akarsha-rai dup of https://github.com/red-hat-storage/ocs-ci/issues/2731?

**Comment by Akarsha-rai** [comment]
> @Akarsha-rai dup of #2731?

yes it is. But skipping whole test is not required since it failed on teardown when validating if any nodes are in NotReady state.
