### ISSUE TITLE
Avoid the pattern of doing a deepcopy of global data in tests

### ISSUE THREAD

**Issue by andrewschoen** [red-hat-storage/ocs-ci#276]
The current ``defaults.py`` holds dictionaries that contain data loaded from local yaml files. I.e. https://github.com/red-hat-storage/ocs-ci/blob/master/ocs/defaults.py#L79

These values are then loaded into tests, deep copied, modified and then used in the test. I.e. https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/test_ocs_336_346.py#L37-L48

I think this is not a good pattern because it opens up the possibility of accidentally mutating that global data and failing subsequent tests. I'd like to propose that ``defaults.py`` only store the path to these yaml files and then we'd provide a utility method that would take a path, load the yaml from the path and return the yaml data as a dict it to the caller. This avoids needing to deepcopy this global data.

**Comment by mbukatov** [comment]
I agree that we need to make the test code to use either a function or a fixture, which will construct the dictionary based on the yaml file for the test.

The usage of such utility function could look like:

```
cephfs = get_yaml_dict("CephFileSystem")
cephfs['some']['key'] = 2
```

or:

```
cephfs = get_yaml_dict(defaults.CEPHFILESYSTEM)
cephfs['some']['key'] = 2
```

**Comment by RazTamir** [comment]
+1 on the proposed approach.
Can I take this issue?

**Comment by vasukulkarni** [comment]
@RazTamir it would require modifying some of the existing tests,  I see around 30% failure when I run all tests at once. 

Aslo please provide some rough template of how the interface to utility functions looks like, I am not clear on @mbukatov comment above on create/apply methods.

**Comment by andrewschoen** [comment]
A fixture could be a nice approach too. For instance a fixture that does something like this:

```
@fixture(scope="method")
def ceph_file_system():
    cephfs = get_yaml_dict("CephFileSystem")
    return cephfs

def test_foo(ceph_file_system):
    cephfs = ceph_file_system()
    cephfs['some']['key'] = 2
    ...
```

**Comment by clacroix12** [comment]
@vasukulkarni I believe this is only addressing how tests will access the dictionaries that they modify. Nothing should change around how they use those dictionaries in their tests, including oc create/apply.

**Comment by zmc** [comment]
Might even want to name the utility function something like `get_crd_template()` to reflect what it's going to give you. The caller doesn't necessarily need to know that the source is a yaml file, and the function can't guarantee the object will be a `dict` - many CRDs are `list`s of `dict`s.

**Comment by RazTamir** [comment]
@zmc, in which cases we will get a list of dicts if the intention here is to create a resource based on a yaml file?

**Comment by RazTamir** [comment]
check this and let me know wdyt - https://github.com/red-hat-storage/ocs-ci/pull/279

**Comment by vasukulkarni** [comment]
Closing stale issue.

**Comment by mbukatov** [comment]
Please provide a reference to a general solution in this area, so that this pattern is no longer used.

Just a brief look at `ocs_ci/ocs/defaults.py` file reveals that there still are mutable data in `ocs_ci` modules, which are prone to the issues noted here.
