### ISSUE TITLE
scale/test_pv_scale_and_respin_ceph_pods.py has intermittent Ceph failurs on Vms

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#2761]
The following error sometimes occurs when running test_pv_scale_and respin_ceph_pods.py on Vms.  This problem does not seem to occur on AWS.

E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 MDSs report slow metadata IOs
ocs_ci/utility/utils.py:1360: CephHealthException

**Comment by wusui** [comment]
Currently being investigated.  I am trying to reproduce.

**Comment by ramkiperiy** [comment]
Not observing this problem in the recent times, and the issue is quite old. 
Closing this issue
