### ISSUE TITLE
Teardown should not fail when executed on an empty cluster dir

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2769]
When a teardown is executed with a cluster dir which doesn't contain references to installed cluster, it fails on missing files from cluster dir like:

```
==================================== ERRORS ====================================
_____________________ ERROR at teardown of test_deployment _____________________

    def cluster_teardown_finalizer():
>       deployer.destroy_cluster(log_cli_level)

tests/conftest.py:1047: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/deployment/aws.py:191: in destroy_cluster
    super(AWSIPI, self).destroy_cluster(log_level)
ocs_ci/deployment/deployment.py:748: in destroy_cluster
    self.ocp_deployment.destroy(log_level)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.deployment.cloud.IPIOCPDeployment object at 0x7f10e4c040b8>
log_level = 'INFO'

    def destroy(self, log_level="DEBUG"):
        """
        Destroy OCP cluster specific
    
        Args:
            log_level (str): log level openshift-installer (default: DEBUG)
    
        """
        # Retrieve cluster metadata
        metadata_file = os.path.join(self.cluster_path, "metadata.json")
>       with open(metadata_file) as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/current-cluster-dir/openshift-cluster-dir/metadata.json'

ocs_ci/deployment/ocp.py:179: FileNotFoundError
```

This is a problem for teardown jenkins job executed for a cluster which failed to be actually installed (installation failed so early that there are no cluster installed, leaving the cluster dir without references to a cluster).

**Comment by jimdevops19** [comment]
Avoiding to proceed to cluster destruction if **metadata.json** does not exist in the cluster directory might be a great idea? (Since the installation failure occurs at a very early stage)

**Comment by petr-balogh** [comment]
I think that OCS-CI should fail if the clusterdir is empty as it expect those data.  This logic should be updated in our destroy jenkins job.  This can check if /home/jenkins/current-cluster-dir/openshift-cluster-dir/ is empty or even exists and if it does not exist or is empty we will continue with destroying jenkins slave.

**Comment by mbukatov** [comment]
@petr-balogh makes sense, feel free to close it when you track it on the jenkins side.

**Comment by petr-balogh** [comment]
I did this MR here:  https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/331

**Comment by petr-balogh** [comment]
MR merged. Closing this issue @mbukatov
