### ISSUE TITLE
Add polarion id to test_upgrade

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2803]
tests/ecosystem/upgrade/test_upgrade.py::test_upgrade doesn't have Polarion ID with valid test steps.

**Comment by clacroix12** [comment]
These can be handled the same way we handle deployment polarion_ids: by adding a corresponding polarion_id to the config files ([example](https://github.com/red-hat-storage/ocs-ci/blob/master/conf/examples/polarion_id.yaml)) and have the value added via our [reporting utility](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/reporting.py#L14-L18).

**Comment by petr-balogh** [comment]
@clacroix12 I thinks we didn't want to merge the PR linked here and close this one, right? If so, please reopen?

**Comment by clacroix12** [comment]
@petr-balogh yeah by the time I was aware of the test case changes we had merged it. It doesn't hurt anything really being merged though. I'm reopening this issue and going to raise another PR that will address the config file changes we discussed.
