### ISSUE TITLE
Use lifecycle/deletion policies to clean up objects/buckets that weren't removed as part of the teardown

### ISSUE THREAD

**Issue by Neon-White** [red-hat-storage/ocs-ci#2811]
In some error/failure cases, the MCG tests leave leftovers in the various cloud services.
All the cloud platforms we're working with (AWS, GCP, IBM, Azure) offer some sort of lifecycle management, that should allow us to keep buckets clean from objects, thus avoiding any unnecessary costs.

**Comment by vasukulkarni** [comment]
Doesn't it get get cleaned up by our cleanup runs in jenkins even when its missed by tier run cleanup?

**Comment by MeridianExplorer** [comment]
@vasukulkarni - AFAIK, no. We can add deletion by name patterns (all leftovers are called `aws-uls-<ID>` - but right now, I don't know of any cleanup besides the teardowns.
