### ISSUE TITLE
Ceph RGW endpoint isn't externalized and is inaccessible from outside the cluster

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#2832]
This prevents us from using the Python S3 SDK to perform various actions on RGW, and is also the reason we're currently skipping the RGW multipart upload test (which relies on said SDK)

**Comment by ebenahar** [comment]
@MeridianExplorer is there a reason to keep this test marked as skipped? tests/manage/rgw/test_multipart_upload.py::TestS3MultipartUpload::test_multipart_upload_operations
Is there anything to be done from the product side or from our CI in order to enable the test?

**Comment by MeridianExplorer** [comment]
@ebenahar - Not anymore. This issue was also solved in #3353
