### ISSUE TITLE
Update default ceph full ratios for external mode

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#2838]
For external mode, the backfillful ratio and nearfull ratio are different from internal mode cluster. 

AssertionError: Actual full ratio values does not match expected full ratio values assert {'backfillful..._ratio': 0.75} == {'backfillful..._ratio': 0.85}   Differing items:   {'full_ratio': 0.85} != {'full_ratio': 0.95}   {'nearfull_ratio': 0.75} != {'nearfull_ratio': 0.85}   {'backfillfull_ratio': 0.8} != {'backfillfull_ratio': 0.9}   Full diff:   - {'backfillfull_ratio': 0.8, 'full_ratio': 0.85, 'nearfull_ratio': 0.75}   ?  

Test run: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/11623/

Test case failed: tests.manage.z_cluster.test_ceph_default_values_check.TestCephDefaultValuesCheck.test_ceph_default_values_check

**Comment by mbukatov** [comment]
In external mode, you can't assume anything about the values of the ratios. Storage admin of the external cluster could have configured them as required.

**Comment by shylesh** [comment]
@rachael-george , you want this to be fixed in OCS-CI ? because when user brings up external RHCS cluster then he/she can set it to whatever value required.

@ebenahar @sidhant-agrawal @nehaberry   WDYT ?

**Comment by ramkiperiy** [comment]
@shylesh I would suggest to have one more dict with default ceph param values for external mode. If the user changes the default value then it's difficult.

**Comment by sidhant-agrawal** [comment]
Does it add any value to check the default values for external RHCS cluster when the admin already knows the values?
Even if we use different values for external mode, the test might fail later during the check for PG balancer status.

I modified the test to use following default values from the RHCS cluster:
```
expected_full_ratios = {
            'full_ratio': 0.95,
            'backfillfull_ratio': 0.9,
            'nearfull_ratio': 0.85
 }
```
but still the test failed in my setup with below error:
```
        # Check if PG balancer is active
>       assert get_pg_balancer_status(), "PG balancer is not active"
E       AssertionError: PG balancer is not active
E       assert False
E        +  where False = get_pg_balancer_status()

tests/manage/z_cluster/test_ceph_default_values_check.py:72: AssertionError

```

**Comment by mbukatov** [comment]
Purpose of the affected [test case `test_ceph_default_values_check`](https://github.com/red-hat-storage/ocs-ci/blob/79a7f4d32a9eeefaf60b2758297fce2b089a4281/tests/manage/z_cluster/test_ceph_default_values_check.py#L15) is to make sure that OCS configured the rull ratio values as expected. When we run this test case, we can be sure that the values are configured properly, and that this is the case in new OCS versions as well.

But when this test case was created, we had internal cluster mode only, where OCS was fully responsible for setup of a ceph cluster. Now with external mode, OCS is not setting up or tweaking a ceph cluster. And we simply can't assume anything about it's configuration.

For this reason, I would suggest to skip this test case on external cluster.

But more important question is, *what kind of ceph full ratio values are not acceptable from external mode in OCS*? This should be directly specified in either JIRA or BZ for OCS product. Tthis is something which should be checked by OCS itself during import of such cluster. When we figure out what is expected handling of this case from the product side, and we have JIRAs or BZs to refer to, we can come up with a test case for such scenario.

Creating a predefined set of values to make this test case pass with external cluster doesn't make any sense. Moreover such decision means to ignore a gap in product specs or behviour, just to make a test case pass, which is exact opposite of what a qe team should be doing.
