### ISSUE TITLE
fix storage class name for clusters in external mode

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#2842]
```
fio_pvc_dict = {'apiVersion': 'v1', 'kind': 'PersistentVolumeClaim', 'metadata': {'name': 'fio-target'}, 'spec': {'accessModes': ['ReadWriteOnce'], 'resources': {'requests': {'storage': '10Gi'}}, 'storageClassName': 'ocs-storagecluster-ceph-rbd'}}
```

In external mode clusters, the storage class name for rbd is ocs-external-storagecluster-ceph-rbd.

**Comment by fbalak** [comment]
The problem occurs also for tests.manage.mcg.test_bucket_creation.TestBucketCreation.test_bucket_creation

**Comment by mbukatov** [comment]
I'm working on a fix for fio job code used for monitoring test cases.

**Comment by mbukatov** [comment]
@fbalak could we close this now (I expect monitoring tests work fine with external clusters - as long as it's not MS)?

**Comment by fbalak** [comment]
Ok, I am not aware of any issues with external mode. If there would be then we can reopen.
