### ISSUE TITLE
Investigate black as a python formatting option for pre-commit

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#2848]
It has been identified in [OCS CI gaps for external contributors](https://docs.google.com/document/d/1UZyGunxXyENrdzmIz91UV5AynceQZF3ZT5BC-Fa6gbk/edit?ts=5f404a89#) that we could benefit from implementing something like [black](https://github.com/psf/black) to handle python formatting and coding style automatically for us. In doing so we would significantly reduce the amount of time we spend reviewing and addressing code formatting issues during PRs. If we are willing to accept the way black formats code (which seems very similar to what we have described in our coding guidelines already) we can easily benefit from black by integrating it as a pre-commit hook. We could also implement into our tox execution to ensure all PRs are passing before merging.

I have already started to review black and how it would alter our code. I will be raising a PR to display the wholesale changes but I think it would be good for our @red-hat-storage/top-level-reviewers to weigh in on if this is something we would like to do.

**Comment by mbukatov** [comment]
This is an interesting idea. And it's also a good opportunity to drop all the non canonical rules we have in our code style.

But please note that for that to work, we need to make sure that people don't have to install anything else but `black` tool itself, and that when I have it installed from rpm package on my Fedora machine, the check will work without installing anything.

**Comment by mbukatov** [comment]
> This is an interesting idea. And it's also a good opportunity to drop all the non canonical rules we have in our code style.
> 
> But please note that for that to work, we need to make sure that people don't have to install anything else but `black` tool itself, and that when I have it installed from rpm package on my Fedora machine, the check will work without installing anything.

**Comment by clacroix12** [comment]
> But please note that for that to work, we need to make sure that people don't have to install anything else but black tool itself

This can be handled by `requirements-dev.txt` and execution of black can be handled by `pre-commit` assuming contributors set that up properly.

> when I have it installed from rpm package on my Fedora machine, the check will work without installing anything (including especially ocs-ci itself).

I'm not sure I follow, are you installing `black` or `ocs-ci` through an rpm? The check can happen either manually by the user or through the use of `pre-commit`. Assuming our other `pre-commit` hooks are working for you I would think the `black` hook would as well.

**Comment by mbukatov** [comment]
> This can be handled by requirements-dev.txt and execution of black can be handled by pre-commit assuming contributors set that up properly.

Absolutely not. That is exactly what I wanted to avoid. The pre-commit check should just:

- check if `black` tool is installed
- if not, fails the commit and tells the user that one should install it (whatever way one considers appropriate, eg. via dnf on Fedora)
- if yes, do the check

The 2nd part of my concern was the fact that I wanted to avoid installing ocs-ci dependencies, even if inside a virtual env, before the check itself. In the meantime, I tested this and learned that black works on sheer files, and doesn't require code to have all it's dependencies installed. And this resolves the concern.

**Comment by clacroix12** [comment]
@mbukatov your suggestion still assumes `pre-commit` is setup on the user's development environment and that `black` is installed in order for this check to pass. I'm not sure how leaving `black` out of our development requirements file helps users when we already have an [established and documented](https://github.com/red-hat-storage/ocs-ci/blob/master/docs/getting_started.md#installing) way to configure `pre-commit` and development dependencies. Using `pip` is also the recommended way to install black according to their [readme](https://github.com/psf/black#installation).

Adding black to `requirements-dev.txt` changes nothing for our contributors regarding project setup and allows us to leverage this tool to improve our code formatting.

**Comment by clacroix12** [comment]
As per @vasukulkarni 's suggestion I have also included `autopep8` for consideration. I did some comparisons manually between `black` and `autopep8` as well as reviewed this [fairly thorough comparison](https://www.kevinpeters.net/auto-formatters-for-python) of these two tools as well as `yapf` which is a formatter maintained by google.

The most important thing I'd like to take away from that comparison is this:

> Use one of the auto formatters presented in this article. Your development team will save so much time. It will be incredible. Also, your code will look the same throughout different projects and repositories and everyone will be much happier.

No matter which tool we go with we should definitely implement one of these into our development cycle and PR pipeline so we can focus on more important issues than code style.

Overall, after spending some time with these tools and reviewing comparisons done by other engineers I think `black` would be the best choice for us. The code looks extremely similar to what we already aim for in our documentation and we can use it out of the box with little to no configuration necessary. `yapf` will need some level of configuration to achieve the same, and `autopep8` is more focused on fixing pep8 compliance issues rather than adhering to an overall code style, as well as requiring more configuration.

**Comment by clacroix12** [comment]
Based on the above (and lack of objections) I'm going to create a new issue for tracking the work that needs to be done to actually implement black into our development pipeline. I will be leaving this ticket open for now so others can add any input/suggestions regarding this discussion. I will close this along with the new ticket with the PR.
