### ISSUE TITLE
Use the provided setup and teardown class methods pytest supports

### ISSUE THREAD

**Issue by andrewschoen** [red-hat-storage/ocs-ci#285]
In the following test there is a ``setup`` and ``teardown`` method that should be a part of the class and not used as class fixtures. https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/ocs_288.py

The ``setup`` and ``teardown`` should be a part of ``class TestCaseOCS288``. In this way we can avoid the use of the GLOBAL keyword in those methods. Things like ``RBD_SECRET_OBJ`` and ``CEPHFS_SECRET_OBJ`` should not need to be global data, they can just exist as properties of the class.

For reference: https://docs.pytest.org/en/latest/xunit_setup.html

**Comment by RazTamir** [comment]
In this link, the usage of setup and teardown are from the unittest world and replaced with fixutres in pytest:
"Note
While these setup/teardown methods are simple and familiar to those coming from a unittest or nose background, you may also consider using pytest’s more powerful fixture mechanism which leverages the concept of dependency injection, allowing for a more modular and more scalable approach for managing test state, especially for larger projects and for functional testing. You can mix both fixture mechanisms in the same file but test methods of unittest.TestCase subclasses cannot receive fixture arguments."

**Comment by andrewschoen** [comment]
@RazTamir yeah, fixtures can work here too. My issue is really with the use of ``GLOBAL`` keyword here. Those really feel like state that should exist on the class and not global state.

**Comment by alfredodeza** [comment]
@RazTamir the reference to pytest's documentation explains the usage of teardown (via the finalizer) in a fixture, however the test used as an example is using a fixture to teardown the test - this is an anti-pattern because the fixture isn't providing anything to the test itself except to teardown. I think this is why it has to depend on using `global`.

Using asserts to verify correctness like in the teardown section of the fixture is also not a common workflow in Python (unlike in C and C++). Raising exceptions is usually preferred.

**Comment by RazTamir** [comment]
The only way I can see this work is to use setup fixture that will initialize all those attributes and the class will use it.

**Comment by alfredodeza** [comment]
I don't think there is a need at all to have a fixture to setup/teardown the test methods. That is what setup and teardown are for. If more than one class is going to use the same setup/teardown helpers then it would be OK to use a base class (even though I dislike inheritance).

Perhaps if you could expand more as to why this approach is being preferred?

**Comment by clacroix12** [comment]
I agree that these fixtures that only call setup/teardown don't offer us any value. There is a pytest way of implementing setup and teardown that we should follow if that is the goal of the fixture. 

```python
@pytest.fixture(scope='class')
def test_fixture(request):
    """
    This is a test fixture
    """
    def finalizer():
        teardown()
    request.addfinalizer(finalizer)
    setup()
```

This block of code appears in almost all of our test modules and is completely unnecessary given pytest provides a way for us to implement setup/teardown at basically any level (module, class, etc.).

I'm all for utilizing fixtures for creating and handling the cleanup of particular resources, but that's not what we are doing here. Let's use the correct pytest provided method for performing these actions in our tests without over-complicating them.

Also in regards to the global variables:

> The only way I can see this work is to use setup fixture that will initialize all those attributes and the class will use it.

This is exactly what we should do, and as long as we move the setup/teardown methods to the class as @andrewschoen pointed out, we will no longer need to utilize `global` to share vars across methods.

**Comment by RazTamir** [comment]
So what all of you suggesting?
By mentioning setup and teardown, are you referring to setup and teardown of unittest?

**Comment by clacroix12** [comment]
> So what all of you suggesting?

We are suggesting that instead of creating fixtures like the [block of code in my previous comment](https://github.com/red-hat-storage/ocs-ci/issues/285#issuecomment-507807742), we utilize setup/teardown methods described here: https://docs.pytest.org/en/latest/xunit_setup.html

Since that fixture only exists to kick off setup/teardown methods we should just implement setup/teardown methods correctly without going through a fixture to do so.

> By mentioning setup and teardown, are you referring to setup and teardown of unittest?

We are talking about our functional tests, not unit tests.

**Comment by ebenahar** [comment]
We all should be using fixtures in this way:

```python
@pytest.mark.usefixtures(
    "create_rbd_secret"
    "create_ceph_block_pool"
    "create_rbd_storageclass"
    "create_pvc"
    "create_pod"
)
```

Each of these fixtures has also a finalizer in it so teardown is being taken care of.

The block of code you @clacroix12 have mentioned is not the correct usage of fixtures, I totally agree.
But I disagree that we should stop using pytest fixtures

**Comment by clacroix12** [comment]
> But I disagree that we should stop using pytest fixtures

Nobody is saying we should stop using fixtures, rather we should implement them correctly if we're going to use them.

**Comment by vasukulkarni** [comment]
We can address the Global usage of resources first and fix all test scripts and then address the setup/teardown methods which I see as a thin line of separation based on test cases.

**Comment by andrewschoen** [comment]
I created a PR as an example of what I'm talking about here. https://github.com/red-hat-storage/ocs-ci/pull/374

The issue here is not fixture usage, it's using fixtures and depending on global variable for them to function. Fixtures are powerful and should be used, I'm just not sure we could be forcing ourselves to use them when we need global variables to make them work.

**Comment by petr-balogh** [comment]
As we discussed last time on our automation call the approach of using fixtures, I tried to fix some issue we have with those tests and used approach we were talking about in the call #405 . Can you please take a look if this one is what we were talking about? @red-hat-storage/top-level-reviewers 

Mainly look at pvcs and project. The fixture in first file delete_pvcs is for objects created from the test, so this use case I used decorator usefixtures for it. Or did we talk about different approach should be used for this usecase?

I tried to not change the logic of test itself as I am not owner of this test case just modified for this approach.

Thanks

**Comment by vasukulkarni** [comment]
Closing stale issue.
