### ISSUE TITLE
Fix usage of noobaa cli tool in ocs-ci tests

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2850]
I noticed that the way we use `noobaa` cli tool for tests is not optimal, and causes lot of issues.

I propose that to fix that, we need to have noobaa cli toolbox pod in a similar way we start ceph toolbox pod:

- we will have to create this pod themselves, reusing existing container image `noobaa-opeator` (we need to redefine at least it's entrypoint) which has the tool installed
- test cases will use the noobaa pod in a similar way how we use ceph toolbox pod

**Comment by MeridianExplorer** [comment]
Personal commentary - 
Using an existing image/maintaining an image database is improbable.
NooBaa is continuously changing the CLI tool between (both major, minor and under-active-development) OCS versions, often in ways that are not backward compatible.
It's impossible to have one catch-all image, and I can't imagine a way in which we have an automatic pipeline that creates a Docker image for every CLI that's released.
On top of that, there is no way to match between RPM versions of the tool, and the version currently running on a cluster.
It also means that this pod will have to be updated as part of any cluster updates.

**Comment by mbukatov** [comment]
>  NooBaa is continuously changing the CLI tool between (both major, minor and under-active-development) OCS versions, often in ways that are not backward compatible.

Yes, and for this reason we would need separate container image for each version.

>  It's impossible to have one catch-all image, and I can't imagine a way in which we have an automatic pipeline that creates a Docker image for every CLI that's released.

This would require some effort, but setting this up on quay.io should be possible. I agree it would be additional (but necessary) work, which could be useful for non qe people as well, so I proposed this for OCS via BZ 1874554

On the one hand, the rest of the project is not interested in this, but on the other hand, Nimrod also noted that the noobaa cli tool is present in noobaa-opeator image. This means we don't need to maintain our own container image.

I'm updating the description of the issue based on that.

**Comment by MeridianExplorer** [comment]
The correct flow is as follows:
1. Check the current NB commit_hash by using `oc rsh noobaa-operator-<id> cat commit_hash`
2. Copy the first seven characters of the hash
3. Look for them in the MCG CLI brew job list (ping me for link)
4. Download the RPM that has "mcg-redistributable" in its name
5. Unpack it with `rpm2cpio ./<rpm_name>.rpm | cpio -idmv`
6. Use the relevant CLI binary to run the command

The main issue with this flow is that it cannot be used without access to the Red Hat VPN. We need to find a solution or alternative flow for those cases.
