### ISSUE TITLE
CPU/Mem limits check for critical pods

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2855]
Based on bz + add for nooba

https://bugzilla.redhat.com/show_bug.cgi?id=1781785

**Comment by vasukulkarni** [comment]
for nooba limits:

```
   Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:     2
      memory:  4Gi
```

**Comment by vasukulkarni** [comment]
If we fix in deployment then we have to be 100% sure that the limits wont change as we pass different config..

**Comment by clacroix12** [comment]
@vasukulkarni I'm not seeing any mention of noobaa in that bz or any of the ones they link to. Can you elaborate a bit more on what needs to happen for this issue and why?

**Comment by vasukulkarni** [comment]
@clacroix12 I will ping on gchat, the second comment is for nooba limits check.

**Comment by vasukulkarni** [comment]
To give the full background,  we are trying to verify the limits for "Standard" deployment (Coady pointed out for LSO deployments we are changing CR and setting different limits for few pods for those deployments) , for now we can assume it will not handle those custom modifications for LSO and can skip the check for those cases.

In general we want to verify the limits are set properly for `standard deployments` and verifies
1) https://bugzilla.redhat.com/show_bug.cgi?id=1873200
2) https://bugzilla.redhat.com/show_bug.cgi?id=1781785

for 
  1) mon 2) mds 3) osd 4) mgr  5) rgw 6) nooba-core 6) nooba-db

The limits to verify are in the bz.

Personally I think the best place is new 'tier1' with new 'testcase' so that the failure still brings up the issue but doesn't stop rest of the test execution.
