### ISSUE TITLE
Noobaa verification do so many iterations - looks like a bug

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2864]
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/11940/console

I see it ran 53 times:
```
13:55:25 - MainThread - /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/mcg.py - INFO - Verified: noobaa status does not contain any error.
13:55:25 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 5 seconds before next iteration
```

**Comment by MeridianExplorer** [comment]
According to an analysis I and @bernerhat did, the issue stems from the way the external mode's sanity check works - 
Under `sanity_helpers.py`, `verify_obc` waits for the `noobaa_health_check` function to return True - but it never does. The function only raises an exception in case the status failed.
