### ISSUE TITLE
IO in background fails with external mode cluster

### ISSUE THREAD

**Issue by shylesh** [red-hat-storage/ocs-ci#2869]
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-vsphere-upi-1az-rhcos-external-3m-3w-tier1/4/#showFailuresLink.

IO in Background checks for osd pod's aggregated memory , which is not applicable to external cluster hence run fails.
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/cluster_load.py#L74 .

In case of external cluster how we want to calculate the memory for osds ?

**Comment by vasukulkarni** [comment]
we should disable the option to run via the cli , iIts  controlled by the run-ci options.
