### ISSUE TITLE
Integration with squad analysis

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2920]
Integration of final email results with squad analysis https://github.com/RazTamir/Automation-analysis---squad-model

**Comment by dahorak** [comment]
Based on our discussion on the Thursday's meeting and my later research, there are two options how to integrate the squad analysis to the test reports:

1. Use directly the [`automation_analysis_squads.py`](https://github.com/RazTamir/Automation-analysis---squad-model/blob/master/automation_analysis_squads.py) script in the Jenkins Job, after the test report is generated and send separated email with the output:
  - :heavy_plus_sign: simple implementation
  - :heavy_plus_sign: the squad analysis code can be hidden from the public (it will not be part of upstream `ocs-ci` repo)
  - :heavy_minus_sign: the analysis will be in separated email, anyhow connected to the test report email send by pytest
2. Incorporate the squad analysis into existing pytest email report:
  - :heavy_plus_sign: the analysis will be (might be) part of the email report send by pytest, not rely on execution in jenkins
  - :heavy_minus_sign: it will require reimplement the logic from the existing [`automation_analysis_squads.py`](https://github.com/RazTamir/Automation-analysis---squad-model/blob/master/automation_analysis_squads.py) script into the pytest logic and update the  [`email_reports`](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L937) function.
  - :heavy_minus_sign: the squad analysis code will be published in the `ocs-ci` repo

I would vote for the second option, as it will give us more flexibility and didn't spam us with two unconnected emails for every run.

@RazTamir @clacroix12 @petr-balogh @vavuthu @vasukulkarni What is your option?

**Comment by petr-balogh** [comment]
As we discussed in our Ecosystem chat room, I think that the 2) will be the better option as well as this will be just part of mail report.  By default this will not be part of the report, but based on some configuration/CLI param we will attach this squad analysis part to it.  If we will change the folder structure: I think that the @RazTamir script need to be also changed.

So IMO it's better to maintain it directly under ocs-ci repo and not rely on the jenkins run but directly access those test results from pytest.

**Comment by dahorak** [comment]
I'll work on this, so removing others from assignment.

**Comment by dahorak** [comment]
@RazTamir and others, what do you think about integration to the results email like this? Any suggestion, concern, note?
It will be controlled by cmd argument `--squad-analysis`.

![email-results-squad-analysis-example](https://user-images.githubusercontent.com/4759779/93348609-b9f53a00-f836-11ea-9968-c16f581a40b1.png)

**Comment by ebenahar** [comment]
@dahorak looks really good!

**Comment by vasukulkarni** [comment]
Looks great :+1:

**Comment by vasukulkarni** [comment]
> As we discussed in our Ecosystem chat room, I think that the 2) will be the better option as well as this will be just part of mail report. By default this will not be part of the report, but based on some configuration/CLI param we will attach this squad analysis part to it. If we will change the folder structure: I think that the @RazTamir script need to be also changed.
> 
> So IMO it's better to maintain it directly under ocs-ci repo and not rely on the jenkins run but directly access those test results from pytest.

you mean pulling squal-analysis repo from Raz's personal git to ocs-ci right?
