### ISSUE TITLE
Refactor tests dir hierarchy

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#2939]
There are a few problems with the current structure: 
- The current e2e dir includes tests of both QPAS and E2E team
- The current manage dir should include also customer defects test cases, which are being automated by E2E team memers
- Flow based test cases are currently under e2e dir which includes both perf, scale and workloads

**Comment by AviadP** [comment]
if we going to refactor folders structure, we may want to remove some helper files out of /tests folder
