### ISSUE TITLE
destroy for upgrade job ( ocp 4.5 to ocp 46 ) failed

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#2941]
destroy for upgrade job ( ocp 4.5 to ocp 4.6 ) failed due to choosing of ocp 4.6 as parameter

```
3:29:19 - MainThread - ocs_ci.utility.utils - INFO - Executing command: /home/jenkins/bin/terraform init /home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/
13:29:19 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: 
No provider "ignition" plugins meet the constraint "0.0.0".

The version constraint is derived from the "version" argument within the
provider "ignition" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: no suitable version is available


tests/ecosystem/deployment/test_deployment.py::test_deployment ERROR     [100%]

````

Job: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/9708/consoleFull

**Comment by vavuthu** [comment]
there is a attribute "append"  which exists in OCP 4.5 and doesn't exist in OCP 4.6.

We have to use original installer branch for destroy as well. We are using the original branch in pipelines as well.

**Comment by petr-balogh** [comment]
@vavuthu we plan to add OCP_UPGRADE_VERSION parameter to our jenkins job. So then the job will pass new version to destroy job. I think this still needs to be handled in the destroy itself. If some different branch needs to be used, than we need to dynamically check from what version this cluster was upgraded and if it's needed for destroy, use the origin version for branch.  Or any other issue with that?
