### ISSUE TITLE
Could not deploy OCS using OCS-CI

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#2944]
I wanted to do a check on the pull request. https://github.com/red-hat-storage/ocs-ci/pull/2853 and wanted to remove WIP from the title for final review. However, I found that one of the recently merged pull request has broken our code (https://github.com/red-hat-storage/ocs-ci/pull/2851) 

The details: During run-ci startup 

run-ci -m deployment --deploy --ocsci-conf=conf/ocsci/production_powervs_upi.yaml --cluster-name="MyCluster" --cluster-path=~/.kube/ 

it breaks at 
> res = hook_impl.function(*args)

  /home/svenkat/ocs-ci/tests/conftest.py(134)pytest_collection_modifyitems()

-> if skipif_upgraded_from(skip_args[0]):

  /home/svenkat/ocs-ci/ocs_ci/utility/utils.py(2617)skipif_upgraded_from()

-> ocs_csv = get_ocs_csv()

  /home/svenkat/ocs-ci/ocs_ci/ocs/resources/ocs.py(229)get_ocs_csv()

-> ocs_csv_name = ocs_package_manifest.get_current_csv(channel=channel)

> /home/svenkat/ocs-ci/ocs_ci/ocs/resources/packagemanifest.py(139)get_current_csv()

-> if _channel['name'] == channel:

(Pdb) n

> /home/svenkat/ocs-ci/ocs_ci/ocs/resources/packagemanifest.py(139)get_current_csv()

-> if _channel['name'] == channel:

(Pdb) l

134  	        self.check_name_is_specified()

135  	        channel = channel if channel else self.get_default_channel()

136  	        channels = self.get_channels()

137  	        import pdb; pdb.set_trace()

138  	        for _channel in channels:

139  ->	            if _channel['name'] == channel:

140  	                return _channel['currentCSV']

141  	        channel_names = [_channel['name'] for _channel in channels]

142  	        raise ChannelNotFound(

143  	            f"Channel: {channel} not found in available channels: "

144  	            f"{channel_names}"

(Pdb) p channel

'stable-4.6'

(Pdb) p len(channels)

3

(Pdb) p channels[0]['name']

'stable-4.2'

(Pdb) p channels[1]['name']

'stable-4.3'

(Pdb) p channels[2]['name']

'stable-4.4'

(Pdb)

the 'channel' could not be found in 'channels'. And this error repeats :

23:39:17 - MainThread - ocs_ci.utility.utils - ERROR - Channel: stable-4.6 not found in available channels: ['stable-4.2', 'stable-4.3', 'stable-4.4']

**Comment by petr-balogh** [comment]
Hey @gitsridhar , I hope it got fixed by @vavuthu fix: https://github.com/red-hat-storage/ocs-ci/pull/2898 which got merged today.

Can you please rebase and check if you are OK now? If so please close this issue, if not please let us know.

Thanks

**Comment by petr-balogh** [comment]
@jilju FYI

**Comment by vavuthu** [comment]
> Hey @gitsridhar , I hope it got fixed by @vavuthu fix: #2898 which got merged today.
> 
> Can you please rebase and check if you are OK now? If so please close this issue, if not please let us know.
> 
> Thanks

Yes, above PR will fix the issue, we don't need to get csv during collection for deploy and teardown

**Comment by gitsridhar** [comment]
This issue is now resolved. I verified with latest rebased OCS-CI code on Power.
