### ISSUE TITLE
deployment of ocs on aws using run-ci still reports error

### ISSUE THREAD

**Issue by tmuthamizhan** [red-hat-storage/ocs-ci#296]
Deployment of ocs on AWS still fails with "Unable to connect to Server" error.

Pasting below the log for reference.

(ocs) MacBook-Air:ocs-ci tmuthamizhan$ run-ci -m deployment --ocsci-conf conf/ocsci/default_config.yaml --cluster-conf conf/ocs_basic_install.yml --cluster-name tamil --cluster-path /Users/tmuthamizhan/newt1 --log-level=DEBUG --deploy
The kubeconfig file /Users/tmuthamizhan/newt1/auth/kubeconfig doesn't exist!
============================= test session starts ==============================
platform darwin -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /Users/tmuthamizhan/ocs-ci, inifile: pytest.ini, testpaths: tests
plugins: reportportal-1.0.5
collected 26 items / 25 deselected / 1 selected                                

tests/ecosystem/deployment/test_ocs_basic_install.py::test_cluster_is_running 
-------------------------------- live log setup --------------------------------
20:30:20 - MainThread - root - INFO - All logs are located under /tmp/logs
20:30:20 - MainThread - tests.conftest - INFO - Running OCS basic installation
20:30:20 - MainThread - oc.openshift_ops - INFO - Testing access to cluster with /Users/tmuthamizhan/newt1/auth/kubeconfig
20:30:20 - MainThread - oc.openshift_ops - WARNING - The kubeconfig file /Users/tmuthamizhan/newt1/auth/kubeconfig doesn't exist!
20:30:20 - MainThread - tests.conftest - INFO - A testing cluster will be deployed and cluster information stored at: /Users/tmuthamizhan/newt1
20:30:20 - MainThread - tests.conftest - INFO - Generating install-config
20:30:20 - MainThread - utility.utils - INFO - Executing command: mkdir -p /Users/tmuthamizhan/newt1
20:30:20 - MainThread - tests.conftest - INFO - Install config: 
                                                apiVersion: v1beta4
                                                baseDomain: qe.rh-ocs.com
                                                compute:
                                                - name: worker
                                                  platform: {}
                                                  replicas: 3
                                                controlPlane:
                                                  name: master
                                                  platform: {}
                                                  replicas: 3
                                                metadata:
                                                  creationTimestamp: null
                                                  name: tamil
                                                networking:
                                                  clusterNetwork:
                                                  - cidr: 10.128.0.0/14
                                                    hostPrefix: 23
                                                  machineCIDR: 10.0.0.0/16
                                                  networkType: OpenShiftSDN
                                                  serviceNetwork:
                                                  - 172.30.0.0/16
                                                platform:
                                                  aws:
                                                    region: us-east-2
                                                pullSecret: '{"auths": {"cloud.openshift.com": {"auth": "b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3RtdXRoYW1pcmVkaGF0Y29tMW15Z2U4cmNoOTJkc29tbW90aWdxcXVqM2h0Okw3WVhLQktNRlBHSFhXNVNYRjBGM1k2VThXMTZUUUVGR1owWTk0U1pPUkJYRlkyUEIwT0NYVTI0RzlROFNaSEs=",
                                                  "email": "tmuthami@redhat.com"}, "quay.io": {"auth": "b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3RtdXRoYW1pcmVkaGF0Y29tMW15Z2U4cmNoOTJkc29tbW90aWdxcXVqM2h0Okw3WVhLQktNRlBHSFhXNVNYRjBGM1k2VThXMTZUUUVGR1owWTk0U1pPUkJYRlkyUEIwT0NYVTI0RzlROFNaSEs=",
                                                  "email": "tmuthami@redhat.com"}, "registry.connect.redhat.com": {"auth": "NTEwNzIyMTJ8dWhjLTFNWUdFOHJDaDkyRHNvbW1vVGlHcXFVSjNodDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpOalUxWWpsak5UWTFNelEwWVdGak9EazNNREkyTmpKaE56UmhPR1k1TlNKOS5vcGMxWUt1T3JXbzQ3MGppZkF4YlJwLWc4Q2Vra003cGFGMVoyTXdCeHIxeDVobWJHVnlKUS1OcmpTVVYzY1lVYkRxbVg1LWlUSjNUaFlZUDhhSllEMDZqTlpZMUUxYXluN1RXdGRsLXBCQ1VCX2s0RUhJTUN4TlUwaHlTN3owYnFfWWJxWjBTQy1IbDlRZE9sR1p0M0ZKZlo1Q2lsX0xBejdBSExXc2wwcF9UbTZpQXJBazZPM2lLN0FtVmNOanh1bTJNdy1Zd0lCYTJvRzNHMUN6cUlPZ2dIbEo5RGJyNndjYmluaGgzc0pHOWZITFBmVnZ1M0xJSTh3aUpLakFRUjRDOUNaRUtzeWNVMzlMTFZSWEF5Tm9QVEdoRjV1Zk0xVmtMeDg5T2pST25keEVQYmViYnJrbl9nblR0R050WjJZZTVuTU9xcTFoZDVVTzE5LVBBM2l6QmFydjRUaEhEOV94TENaWHVCSlA0WFpkU3dtWDk0RjFXQ0w2elBrU2pOSE9nRzFSeHVkNGRTMnppZ2lVWW1lMWpXMURvSmtZN0YtREJzTFFkZFFtMlBxY2ktV0licGNHR1RaWHFwTmZnbkprbmZjWG9iZWo1R21aQlFFZ3k0TGxqWVl5d1dCVjVkS3pLcFA4VHQ0VnFGT203QlhxX3NBTzViUVVpMjFydkpNUHVUWjFHLUZoWWYzenlNME5Yb0RMQjFYdnZaOFF3dGtRUE9Td1JMMjUtb0pHd3dfVm1ZeFdiV1VLVkx2WnRVY3NnY1pYcmlNSEJIQXpObXQ0b0FhYkhFODRUejRMWjVaY3MtUkxydi1pc2tsRUdiMFZKR1NsM0VLR0dlbnZfanBJYWFnQlFUZWI2ZUtJWU5vVE92eGRQNTNPbWdGLXI2NllhV0w1SFBHRQ==",
                                                  "email": "tmuthami@redhat.com"}, "registry.redhat.io": {"auth": "NTEwNzIyMTJ8dWhjLTFNWUdFOHJDaDkyRHNvbW1vVGlHcXFVSjNodDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpOalUxWWpsak5UWTFNelEwWVdGak9EazNNREkyTmpKaE56UmhPR1k1TlNKOS5vcGMxWUt1T3JXbzQ3MGppZkF4YlJwLWc4Q2Vra003cGFGMVoyTXdCeHIxeDVobWJHVnlKUS1OcmpTVVYzY1lVYkRxbVg1LWlUSjNUaFlZUDhhSllEMDZqTlpZMUUxYXluN1RXdGRsLXBCQ1VCX2s0RUhJTUN4TlUwaHlTN3owYnFfWWJxWjBTQy1IbDlRZE9sR1p0M0ZKZlo1Q2lsX0xBejdBSExXc2wwcF9UbTZpQXJBazZPM2lLN0FtVmNOanh1bTJNdy1Zd0lCYTJvRzNHMUN6cUlPZ2dIbEo5RGJyNndjYmluaGgzc0pHOWZITFBmVnZ1M0xJSTh3aUpLakFRUjRDOUNaRUtzeWNVMzlMTFZSWEF5Tm9QVEdoRjV1Zk0xVmtMeDg5T2pST25keEVQYmViYnJrbl9nblR0R050WjJZZTVuTU9xcTFoZDVVTzE5LVBBM2l6QmFydjRUaEhEOV94TENaWHVCSlA0WFpkU3dtWDk0RjFXQ0w2elBrU2pOSE9nRzFSeHVkNGRTMnppZ2lVWW1lMWpXMURvSmtZN0YtREJzTFFkZFFtMlBxY2ktV0licGNHR1RaWHFwTmZnbkprbmZjWG9iZWo1R21aQlFFZ3k0TGxqWVl5d1dCVjVkS3pLcFA4VHQ0VnFGT203QlhxX3NBTzViUVVpMjFydkpNUHVUWjFHLUZoWWYzenlNME5Yb0RMQjFYdnZaOFF3dGtRUE9Td1JMMjUtb0pHd3dfVm1ZeFdiV1VLVkx2WnRVY3NnY1pYcmlNSEJIQXpObXQ0b0FhYkhFODRUejRMWjVaY3MtUkxydi1pc2tsRUdiMFZKR1NsM0VLR0dlbnZfanBJYWFnQlFUZWI2ZUtJWU5vVE92eGRQNTNPbWdGLXI2NllhV0w1SFBHRQ==",
                                                  "email": "tmuthami@redhat.com"}}}'
20:30:20 - MainThread - utility.utils - INFO - Executing command: ./bin/openshift-install version
20:30:22 - MainThread - utility.utils - INFO - OpenShift Installer version: ./bin/openshift-install v4.1.1-201906040019-dirty
                                               built from commit 8f7e2e5660af0aa0f26df22797db75938253337e
                                               release image quay.io/openshift-release-dev/ocp-release@sha256:9c5f0df8b192a0d7b46cd5f6a4da2289c155fd5302dec7954f8f06c878160b8b
20:30:22 - MainThread - utility.utils - INFO - Executing command: ./bin/oc version
20:30:29 - MainThread - utility.utils - ERROR - CMD error:: Unable to connect to the server: dial tcp: lookup console.cellett.gce.pixy.io on 10.11.5.19:53: no such host
ERROR                                                                    [100%]

==================================== ERRORS ====================================
__________________ ERROR at setup of test_cluster_is_running ___________________

**Comment by RazTamir** [comment]
@tmuthamizhan I'm not sure if that is the issue but seems like you cli command is wrong.
Try to execute with this (removed: --ocsci-conf conf/ocsci/default_config.yaml):
 run-ci -m deployment --cluster-conf conf/ocs_basic_install.yml --cluster-name tamil --cluster-path /Users/tmuthamizhan/newt1 --log-level=DEBUG --deploy

**Comment by vavuthu** [comment]
Closing this bug due to below reasons. Please open new bug if deployment is still failing.

There are lot changes went into framework and deployment part within last 2 months.
