### ISSUE TITLE
OCS 4.5 to OCS 4.6 upgrade failing with RGW `Found pods: 2 but expected: 1`

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2971]
With this PR https://github.com/red-hat-storage/ocs-ci/pull/2533/files, the RGW count was set to 1 for upgrade checks. This is leading to failure of post_upgrade check for RGW pods for 4.5 to 4.6 upgrades.

Run ID: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/12485/consoleFull
Error message: 
```15:15:07 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found pods: 2 but expected: 1!```

But, for OCS 4.5 to OCS 4.6, the RGW count is expected to be 2 for both pre_upgrade and post_upgrade counts. 

IMO, we need to uncomment [this](https://github.com/red-hat-storage/ocs-ci/blob/073ac9f44111fb182aa75b617faf5cea8a0e58fe/ocs_ci/ocs/ocs_upgrade.py#L128) , but raised a query to Elad [here](https://github.com/red-hat-storage/ocs-ci/pull/2533/files#r490862768) before making this change.

**Comment by ebenahar** [comment]
To fix this, we should do https://github.com/red-hat-storage/ocs-ci/pull/2533/files#r491471793
And also, a change is needed in https://github.com/red-hat-storage/ocs-ci/blob/df272363e94f4a480dc407f5b78a44a38d3a009e/ocs_ci/ocs/resources/storage_cluster.py#L126

From:
```python
    if config.ENV_DATA.get('platform') in constants.ON_PREM_PLATFORMS:
        # Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1857802 - RGW count is 1
        # post upgrade to OCS 4.5. Tracked with
        # https://github.com/red-hat-storage/ocs-ci/issues/2532
        rgw_count = 2 if float(config.ENV_DATA['ocs_version']) >= 4.5 and not (
            post_upgrade_verification
        ) else 1
```

To:
```python
    if config.ENV_DATA.get('platform') in constants.ON_PREM_PLATFORMS:
        if float(config.ENV_DATA['ocs_version']) < 4.5 or float(
            config.ENV_DATA['ocs_version']
        ) == 4.5 and post_upgrade_verification:
            rgw_count = 1
        else:
            rgw_count = 2
```

**Comment by parikshithb** [comment]
@nehaberry  The check in ocs-ci/ocs_ci/ocs/resources/mcg.py verifies whether RGW is not running other than the supported platforms(VMware/BM). This verification was added since we were seeing RGW pods coming up in AWS and other platforms.

**Comment by parikshithb** [comment]
My bad, I referred to different snip. If the same RGW pod count check is handled in storage_cluster.py, I do not see any reason to have it in mcg.py as well.

**Comment by nehaberry** [comment]
> My bad, I referred to different snip. If the same RGW pod count check is handled in storage_cluster.py, I do not see any reason to have it in mcg.py as well.

thanks. But if that is the case, we need to remove the whole of rgw_count from mcg.py

            rgw_count = 2 if float(config.ENV_DATA['ocs_version']) >= 4.5 and not (
                check_if_cluster_was_upgraded()
            ) else 1

            # With 4.4 OCS cluster deployed over Azure, RGW is the default backingstore
            if float(
                config.ENV_DATA['ocs_version']
            ) == 4.4 and config.ENV_DATA.get('platform') == constants.AZURE_PLATFORM:
                rgw_count = 1
            if float(
                config.ENV_DATA['ocs_version']
            ) == 4.5 and config.ENV_DATA.get('platform') == constants.AZURE_PLATFORM and (
                check_if_cluster_was_upgraded()
            ):
                rgw_count = 1
            logger.info(f'Checking for RGW pod/s on {config.ENV_DATA.get("platform")} platform')
            rgw_pod = OCP(kind=constants.POD, namespace=self.namespace)
            assert rgw_pod.wait_for_resource(
                condition=constants.STATUS_RUNNING,
                selector=constants.RGW_APP_LABEL,
                resource_count=rgw_count,
                timeout=60
            )

https://github.com/red-hat-storage/ocs-ci/blob/07fe5b52362df12964ea1db0b533eda32299c629/ocs_ci/ocs/resources/mcg.py#L152-L174

WDYT ? @mbukatov
