### ISSUE TITLE
Upgrade execution ordering is alphabetical and not according to the ordering markers

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#2973]
1) The execution ordering is alphabetical and not according to the ordering markers, and it applies to all other test cases, not only add capacity.

All the tests that are under test/manage are being executed post upgrade, even though some of them have the '@pre_upgrade' marker. 
Also, since the upgrade tests themselves are alphabetical last under tests/ecosystem, all the pre and post upgrade tests that are under tests/ecosystem, are being called before the upgrade test.

For example:

tests/manage/monitoring/test_workload_with_distruptions.py::test_workload_with_checksum 
-------------------------------- live log setup --------------------------------
15:25:02 - MainThread - tests.conftest - INFO - Checking for Ceph Health OK 

This test has the `@pre_upgrade` mark:
While the upgrade test took place before that, started at 14:36:59.

2) The issue isn't new. 
Like in this run (OCS upgrade), from 25 days ago which is the oldest OCS upgrade run that still exists in Jenkins history.

From that run:

tests/ecosystem/upgrade/test_upgrade.py::test_upgrade 
-------------------------------- live log call ---------------------------------
10:19:11 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get CephCluster  -n openshift-storage -o yaml

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacityPreUpgrade::test_add_capacity_pre_upgrade 
-------------------------------- live log call ---------------------------------
10:56:20 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get storagecluster  -n openshift-storage -o yaml

3) I tried executing with same markers (-m "pre_upgrade or ocs_upgrade or post_upgrade") from my laptop and the ordering worked well. 
The only difference between my laptop and the Jenkins slave is the Python version.
My laptop has python 3.7.9 and the Jenkins slave (from this run - #12485) has python 3.6.8.

Both my laptop and the slave also have:
pytest 5.3.5
py 1.9.0
pluggy 0.13.1
pytest-ordering 0.6

4) In the pytest ordering docs, it's mentioned that it's currently an alpha-quality software. 

========================================================================================================================================================

I wonder what could be the reason that the ordering is broken with the Jenkins slaves while it is working fine from my laptop. 
The only difference I could find is the Python version.

We need to find a solution quickly, as there are some test cases that lose their whole purpose if they are not being executed in the intended ordering. 
For example, test_workload_with_checksum and test_workload_with_checksum_verify, which do data integrity before and after an operation, upgrade in this case, and with the current issue both run after upgrade.

**Comment by ebenahar** [comment]
@red-hat-storage/ocs-qe-ecosystem should we maybe try to upgrade the slaves with Python 3.7.9?

**Comment by petr-balogh** [comment]
@ebenahar started looking at this issue.  Weird is that --collect only shows the order we defined :(

Now when we install python 3 via YUM, there is only 3.6.8 available and no 3.7. So I am looking at the way to install it from the source. Will update about it tomorrow.

**Comment by vasukulkarni** [comment]
Not sure how python version can matter, I think we have ordering defined in pytest, I think we should rewrite it so that tests move to /updates and we can have the ability to add more upgrade tests.

**Comment by petr-balogh** [comment]
Looks like that something with IO in bg has something to do with the order. Here is what I found out so far:

Testing with this change:
https://github.com/red-hat-storage/ocs-ci/compare/test_ordering_plugin where I basically just returning right after the test start so nothing is really upgraded in my testing as I would like to run more execution to debug the root cause of the issue.

Testing on new VmWare cluster and see here:  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/12609/consoleFull - the order of tests with IO is wrong

```
13:09:17 - MainThread - tests.conftest - INFO - Ceph health check passed at teardown

tests/ecosystem/upgrade/test_resources.py::test_pod_io SKIPPED           [ 73%]
tests/ecosystem/upgrade/test_upgrade.py::test_upgrade
13:09:27 - MainThread - tests.conftest - INFO - Ceph health check passed at teardown

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacityPreUpgrade::test_add_capacity_pre_upgrade
```

This one without IO in background
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/12618/console
order looks ok at least for add_capacity test
```
13:55:53 - MainThread - tests.conftest - INFO - Ceph health check passed at teardown
tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacityPreUpgrade::test_add_capacity_pre_upgrade 
-------------------------------- live log call ---------------------------------
13:55:53 - MainThread - tests.manage.z_cluster.cluster_expansion.test_add_capacity - INFO - In test
PASSED                                                                   [ 46%]
------------------------------ live log teardown -------------------------------
13:55:53 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-tools -n openshift-storage --timeout=120s
13:55:54 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get pod -l 'app=rook-ceph-tools' -o jsonpath='{.items[0].metadata.name}'
13:55:55 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-5f9d64c99b-wl477 -- ceph health
13:55:56 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
13:55:56 - MainThread - tests.conftest - INFO - Ceph health check passed at teardown

tests/ecosystem/upgrade/test_upgrade.py::test_upgrade 
-------------------------------- live log call ---------------------------------
13:55:56 - MainThread - test_upgrade - INFO - In test
```


Running once more with IO in bg here:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/12619/console
To verify that this is really causing us the issues

**Comment by petr-balogh** [comment]
So I finally found out the issue after two days :( looks like that the issue is in pytest-reportportal @vasukulkarni @ebenahar @clacroix12 

Found this issue:
https://github.com/reportportal/agent-python-pytest/issues/130

we use pretty old version of this plugin:
'pytest-reportportal==1.10.0',
https://github.com/red-hat-storage/ocs-ci/blob/master/setup.py#L29

I see this got already fixed but it's in some newer version of this plugin. So I guess we should update it, or do you remember some issue with newer version @vasukulkarni @clacroix12 ?

**Comment by vasukulkarni** [comment]
Yeah that seems to be the issue :( , The reason it is at 1.10 is latest version doesn't support the reportportal we have running, it would require DB migration from mongo to sql, Maybe its time to run it now.

**Comment by clacroix12** [comment]
@vasukulkarni I agree I think this gives us a good reason to prioritize migrating to the latest version of report portal using a SQL backend.

**Comment by vasukulkarni** [comment]
Lets plan to move it this weekend, I am checking the Dockerfile and there is quite a bit of dependency for migration, worse case we can start fresh 5.0 in our ocs tenant and leave the old one as is.

**Comment by vasukulkarni** [comment]
Also cherry-picked to buy sometime for migration https://github.com/vasukulkarni/agent-python-pytest/releases/tag/v1.10.3 , will see if it can temporarily solve

**Comment by vasukulkarni** [comment]
I just ran some test (directly via py.test) I am not seeing any mess up with order with or without pytest-reportportal installed, The issue mentioned above doesn't specifically talk about pytest-ordering pluggin.
