### ISSUE TITLE
mcg.py RGW pod count checks needs some changes

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#3027]
https://github.com/red-hat-storage/ocs-ci/blob/0fa5b9c73772c11740695a24aa67924e0e130c22/ocs_ci/ocs/resources/mcg.py#L138-L174

e.g. 
```
        elif config.ENV_DATA.get('platform') in constants.ON_PREM_PLATFORMS or (
            config.ENV_DATA.get('platform') == constants.AZURE_PLATFORM
        ):
            rgw_count = 2 if float(config.ENV_DATA['ocs_version']) >= 4.5 and not (
                check_if_cluster_was_upgraded()
            ) else 1
```
---> IIUC, for Azure :
a) This will set RGW count to 1 even for OCS 4.5.0 to 4.5.z upgraded clusters . 
b) RGW=2 for 4.5 and not upgraded clusters. But Azure doesn't get RGW pods starting from OCS 4.5 onwards
Let me know if my understanding is incorrect

```
L152 -L154
           rgw_count = 2 if float(config.ENV_DATA['ocs_version']) >= 4.5 and not (
                check_if_cluster_was_upgraded()
            ) else 1
```

for on-prem clusters upgraded from 4.5.0 to 4.5.z, this condition would not be correct. it will set RGW =1 instead of expected 2. Hence, we need modification.

Since this would not be a small change and need confirmation from MCG squad, not fixing this with PR #3026

**Comment by nehaberry** [comment]
@parikshithb @MeridianExplorer  can MCG team take a look at this ?

**Comment by vasukulkarni** [comment]
I also hit similar issue couple of days back and ping Ben in ocs-infra.
