### ISSUE TITLE
Provide a way to SIGKILL a pod

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#303]

**Comment by shylesh** [comment]
I tried another (not so clean) way of achieving this.
./bin/oc exec -it rook-ceph-mon-a-64fbcdc95f-ssz57  -n openshift-storage --   gdb -p 1 -batch -ex "signal 9"
[New LWP 44]
[New LWP 43]
[New LWP 42]
[New LWP 41]
[New LWP 40]
[New LWP 39]
[New LWP 38]
[New LWP 37]
[New LWP 36]
[New LWP 35]
[New LWP 34]
[New LWP 33]
[New LWP 32]
[New LWP 31]
[New LWP 30]
[New LWP 29]
[New LWP 28]
[New LWP 12]
[New LWP 11]
[New LWP 10]
[New LWP 9]
[New LWP 8]
[New LWP 7]
[New LWP 6]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fb83b077965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
command terminated with exit code 137

Only requirement is we need to do 'yum install gdb' before this invocation. 
Not sure if you are comfortable with this approach.

**Comment by RazTamir** [comment]
@ebenahar , looks like the current implementation is ok - https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
when passing --grace-period=0 --force you basically send SIGKIL

**Comment by ebenahar** [comment]
@RazTamir thanks for checking! @shylesh based on the above, are you ok with closing the issue?

**Comment by shylesh** [comment]
> @RazTamir thanks for checking! @shylesh based on the above, are you ok with closing the issue?

Ya sure, please go ahead.
