### ISSUE TITLE
TypeError - load_auth_config().get('AUTH') returned None

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3033]
https://github.com/red-hat-storage/ocs-ci/blob/0fa5b9c73772c11740695a24aa67924e0e130c22/ocs_ci/ocs/resources/cloud_manager.py#L43

Shouldn't we change it to cred_dict = load_auth_config().get('AUTH', {}) ?

To fix the issue :
 ocs_ci/ocs/resources/cloud_manager.py:44: TypeError - load_auth_config().get('AUTH') returned None .

**Comment by MeridianExplorer** [comment]
This will silence the error, but really, this error shouldn't happen at all. It's an indicator for the fact that we're missing a skip marker, as fixed in #3032

**Comment by petr-balogh** [comment]
@MeridianExplorer if some section is required it should print some more reasonable error like:

`AWS` key is missing in AUTH dict.  But the error ocs_ci/ocs/resources/cloud_manager.py:44: TypeError - load_auth_config().get('AUTH') returned None .

Really shouldn't happen here and this solution is much cleaner.

If something else is required, this should fail at least with key error not like this so I still insist to merge this one and if some error should be printed out, we need to do it in the place where it's required.

WDYT @MeridianExplorer ?

**Comment by MeridianExplorer** [comment]
@petr-balogh - I agree. Let's approve+merge your PR, and leave the issue open in order to add a more descriptive error message for those cases. 
Whatcha think? :)

**Comment by petr-balogh** [comment]
The PR fixed exactly what this issue was about. I think that now if someone will just try to query dictionary with some specific key we will see keyError which will tell us more info which is enough to identify the issue.  If you think that some other issue needs to be opened, please open one. @MeridianExplorer
