### ISSUE TITLE
Fix our packaging

### ISSUE THREAD

**Issue by zmc** [red-hat-storage/ocs-ci#305]
Let's do some work to make sure we can `pip install` the project and have it work as expected.

I expect I'll take this work up, but in case anyone's curious, the discussion started [in the restructure PR](https://github.com/red-hat-storage/ocs-ci/pull/301#issuecomment-506493769).

**Comment by gklein** [comment]
Following the [getting started guide](https://github.com/red-hat-storage/ocs-ci/blob/master/docs/getting_started.md#installing)  it seems pip can now install the project.

Can we close this issue?

**Comment by vasukulkarni** [comment]
Closing stale issue.
