### ISSUE TITLE
IO in background is failing with: ocs_ci/ocs/cluster_load.py:333: IndexError on OCS 4.3/OCP 4.4

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3055]
On OCS 4.3/OCP 4.4
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/12993/ 
```        return float(
            self.prometheus_api.query(
                query, str(timestamp(now())), mute_logs=mute_logs
>           )[0]['value'][1]
        )
E       IndexError: list index out of range

ocs_ci/ocs/cluster_load.py:333: IndexError
```

@ebenahar  can you please take a look?

**Comment by petr-balogh** [comment]
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13560/console
Happened here as well:
OCS/OCP 4.5 

@ebenahar  FYI, this has to be fixed as well with high priority as I see once it happens it kill all the execution.

**Comment by petr-balogh** [comment]
The same issue happened here: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13561/

**Comment by ebenahar** [comment]
So apparently it's not an issue with OCS/OCP 4.3 only.
From what I see, this could happen intermediately so I thought we can retry in case of this IndexError - https://github.com/red-hat-storage/ocs-ci/pull/3159
