### ISSUE TITLE
Add to ocs upgrade test: validation for pod 'ocs-metrics-exporter'

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#3069]
From OCS4.6 and above, new pod added: ocs-metrics-exporter

- Need to add validation for pod itself when running 4.5 to 4.6 upgrade
- Need to add validation for this pod images version

**Comment by nehaberry** [comment]
We also need to add the validation for a fresh OCS 4.6 cluster. hence in deployment.py
