### ISSUE TITLE
must_gather failes to complete in 600sec for scale tests

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#3083]
For scale and long running tests, there will be lot of logs collected in the cluster and due to this must-gather might need to run longer than the normal tier1 or tier2 tests, also this is more of a realistic case for customer environment where must-gather need to run for longer duration to collect complete logs.

Failure observed during a scale test run
```
15:17:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm must-gather --image=quay.io/openshift/origin-must-gather --dest-dir=/home/jenkins/current-cluster-dir/logs/testcases_1602073625/ocp_must_gather
15:27:31 - MainThread - ocs_ci.ocs.utils - ERROR - Timeout 600s for must-gather reached, command exited with error: Command '['oc', '--kubeconfig', '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig', 'adm', 'must-gather', '--image=quay.io/openshift/origin-must-gather', '--dest-dir=/home/jenkins/current-cluster-dir/logs/testcases_1602073625/ocp_must_gather']' timed out after 600 seconds
15:27:31 - MainThread - ocs_ci.ocs.utils - INFO - Must gather image: quay.io/openshift/origin-must-gather will be used.
15:27:31 - MainThread - ocs_ci.ocs.utils - INFO - OCS logs will be placed in location /home/jenkins/current-cluster-dir/logs/testcases_1602073625/ocp_must_gather
```

**Comment by ramkiperiy** [comment]
![image](https://user-images.githubusercontent.com/22941695/95474827-377a1900-09a3-11eb-9669-35145bbf9ab1.png)

**Comment by ramkiperiy** [comment]
FIxed the problem of memory issue in PVC_Create_Delete_scale test using kube jobs, but need to work on implementing the same in pod+pvc creation scale test, so keeping this issue open until we fix the problem in existing automated tests.

**Comment by vasukulkarni** [comment]
We can customize the timeout for scale in the conf file, so that it can use custom value based on the scale nmbers.

**Comment by clacroix12** [comment]
We already support overriding the default timeout value [here](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/utils.py#L736-L738). We simply need to set this config value for our scale test executions.

**Comment by MeridianExplorer** [comment]
From what I've seen, this seems to happen in most tests, regardless of whether they're scale or not.
I could open a semi-duplicate issue that refers to the problem being present in other test suites too, but I feel it'd be rather redundant, and that maybe we could concentrate the discussions around this problem in here.
Opinions?

**Comment by clacroix12** [comment]
@MeridianExplorer If this is happening outside of scale let's open a new issue and discuss it there.
