### ISSUE TITLE
When using the --collect-logs-on-success-run option junit file & html report are not generated

### ISSUE THREAD

**Issue by vi-patel** [red-hat-storage/ocs-ci#3094]
I have been deploying and running OCS 4.5 and 4.6 on OCP 4.6.

We use our own automation to deploy OCP.

Then to deploy OCS I have been using the following:

```
source ~/myvenv/bin/activate; run-ci -m deployment --deploy --ocsci-conf ./default_config.yaml
      --ocsci-conf ./flexy_baremetalpsi_upi.yaml --ocsci-conf ./flexy_default_config.yaml
      --cluster-name={{ OPENSHIFT_CLUSTER_NAME }} --ocs-version {{ OCS_VERSION }}
      --ocp-version {{ OPENSHIFT_VERSION }}
      --cluster-path=~/{{ OPENSHIFT_CLUSTER_NAME }}_install --collect-logs
```

and to run the tests I have been using the following:
`source ~/myvenv/bin/activate; run-ci -m acceptance --ocsci-conf default_config.yaml --ocsci-conf flexy_baremetalpsi_upi.yaml --ocsci-conf flexy_default_config.yaml --cluster-name={{ OPENSHIFT_CLUSTER_NAME }} --cluster-path=~/{{ OPENSHIFT_CLUSTER_NAME }}_install --ocs-version {{ LAYERED_PRODUCT_VERSION }} --ocp-version {{ PLATFORM_VERSION }} --self-contained-html --html=/home/cloud-user/logs/report.html --junit-xml=/home/cloud-user/logs/junit.xml --collect-logs`

After adding the --collect-logs-on-success-run option to both cmds, the junit file was no longer being generated properly (just an xml skeleton) and the html report was not genertated, some examples:

Saved artifacts from build 25-27 shows the empty junit file and no html generated.
https://interop-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocs-4.5-openshift-4-vipatel/27/artifact/.results/artifacts/ocp-driver-vipatel-71owf/

Just in case the jobs get removed the generated xunit file looks like the following:
`<?xml version="1.0" encoding="utf-8"?>`

After removing the --collect-logs-on-success-run option for both deploy and execution (only removing the option from execution did not work) (report and junit file are now generated):
https://interop-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocs-4.5-openshift-4-vipatel/28/artifact/.results/artifacts/ocp-driver-vipatel-z1p5k/

**Comment by petr-balogh** [comment]
Hey @vi-patel ,

I see this error in your jenkins console output:
```
2020-10-07 21:54:48,499 INFO [carbon.ansible_helpers.exec_local_cmd_pipe:528] "    logfile.write(Junit.testsuites([suite_node]).unicode(indent=0))",
2020-10-07 21:54:48,499 INFO [carbon.ansible_helpers.exec_local_cmd_pipe:528] "MemoryError"
```
https://interop-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocs-4.5-openshift-4-vipatel/27/consoleFull

This looks more like an memory issue on your jenkins agent where do you run the code, can you check this, or increase the memory on there?
BTW what memory are you using for jenkins agent?

@shylesh please assist to Vimal.

Petr
