### ISSUE TITLE
collect_ocs_logs function, latest_tag does not match cluster version

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#3114]
I worked on cluster OCS4.5 but the latest_tag is 4.6.('latest-4.6')

Cluster version:
$ oc get clusterserviceversions
NAME                         DISPLAY                       VERSION        REPLACES   PHASE
ocs-operator.v4.5.1-123.ci   OpenShift Container Storage   4.5.1-123.ci              Succeeded

Function Path:
ocs_ci/ocs/utils.py::collect_ocs_logs

![latest_tag](https://user-images.githubusercontent.com/61982127/95735273-473c7a80-0c8d-11eb-896c-9c96bbef80b7.png)

**Comment by petr-balogh** [comment]
@OdedViner the default version is OCS/OCP 4.6 in the ocs-ci. If you are running against something different you have to use --ocs-version 4.5 or --ocp-version 4.5 parameter when running tests.  Have you done that?

I guess no, so it's not the issue and I am closing this one.

If you've passed proper versions when run and still have issue, please comment with details and re-open the issue.

Thanks

**Comment by OdedViner** [comment]
add this  parameters `--ocs-version 4.5`. and latest_tag is 4.5.('latest-4.5')
