### ISSUE TITLE
collect_ocs_logs function, latest_tag does not match cluster version

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#3118]
I worked with cluster OCS4.5 but the latest_tag is 4.6.('latest-4.6')

Cluster version:
$ oc get clusterserviceversions
NAME                         DISPLAY                       VERSION        REPLACES   PHASE
![latest_tag](https://user-images.githubusercontent.com/61982127/95745334-92f72000-0c9d-11eb-9847-3008f1690751.png)

ocs-operator.v4.5.1-123.ci   OpenShift Container Storage   4.5.1-123.ci              Succeeded

Function Path:
ocs_ci/ocs/utils.py::collect_ocs_logs

**Comment by petr-balogh** [comment]
Hey @OdedViner , have you seen my comment here:  https://github.com/red-hat-storage/ocs-ci/issues/3114#issuecomment-707039364. ? I've closed this issue intentionally and asked to reopen if you don't agree ;)

**Comment by OdedViner** [comment]
add  parameter `--ocs-version 4.5` and latest_tag is 4.5.('latest-4.5')
