### ISSUE TITLE
Comment the pv name validation on TC-372

### ISSUE THREAD

**Issue by Akarsha-rai** [red-hat-storage/ocs-ci#314]
If we are validating the presence of PVs in ceph backend using oc "pv_name" parameter, we are facing issue because rbd-image output does not have the exact pv name due to the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1723656. So need to comment the pv validation part on TC-372(test_pvc_delete_verify_size_is_returned_to_backendpool.py) until we find the solution to map the pv name.

**Comment by shreekarSS** [comment]
I have fix for this script,will push

**Comment by vasukulkarni** [comment]
Closing stale issue.
