### ISSUE TITLE
Need change in yaml files in OCS deployment and csi based files

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#317]
Description:
Due to the merged changes in CSI based yamls on  [rook git repo](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/), there are modified yamls for the following. Accordingly, we would have to change our deployment templates in OCS-CI.

Files used for chnage in ocs-ci repo copied from :
PR merged in rook repo (update rook to use ceph-csi canary version): https://github.com/rook/rook/pull/3324/files
PR Waiting to be merged in rook - https://github.com/rook/rook/pull/3358/files

1. Operator-openshift-with-csi.yaml 
2. RBD -  storageclass.yaml , snapshot.yaml and secret.yaml
3. Ceph FS - storageclass.yaml, secret.yaml
3. RBAC files in rbd and cephfs 

Bug list:

https://bugzilla.redhat.com/show_bug.cgi?id=1724179

**Comment by gklein** [comment]
Given the [PR](https://github.com/red-hat-storage/ocs-ci/pull/318) is merged, can we close this issue?
