### ISSUE TITLE
Prometheus module shoudl expect a failure during yaml parting of a query response

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#3189]
Prometheus module should expect a failure during json parting of a query response, catch exception and log the issue properly.

**Comment by petr-balogh** [comment]
FYI I added some retries and covered session scope fixture by try except block here:  https://github.com/red-hat-storage/ocs-ci/issues/3145 , it's fixing the whole execution to fail if it's only some temp issue.
