### ISSUE TITLE
Move away from using templated CRDs

### ISSUE THREAD

**Issue by zmc** [red-hat-storage/ocs-ci#319]
I was reminded of this by https://github.com/red-hat-storage/ocs-ci/issues/317

We're going to keep having to do things like this. Instead, we ought to use CRDs from either the upstream git repo, or from a package (in a downstream context). We can then write a small amount of code to modify those values which differ from the default setting.

This isn't just a matter of convenience. With downstream, some of these files will have been patched. If we use our own copy, we will lack those changes.

**Comment by vasukulkarni** [comment]
Closing stale issue.
