### ISSUE TITLE
installation with 5 worker nodes fail's while check ceph osd tree status

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#3218]
Jenkins run https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13998/

**Comment by yitzhak12** [comment]
If this error is with BM or LSO cluster, it may be a duplicate of this issue https://github.com/red-hat-storage/ocs-ci/issues/3297
