### ISSUE TITLE
automatically generate result report and store it with the logs

### ISSUE THREAD

**Issue by andrewschoen** [red-hat-storage/ocs-ci#322]
Automatically provide the ``--junit-xml`` flag and generate an html report of the test results with ``junit2html`` and store it in the logs directory.

**Comment by mbukatov** [comment]
I would suggest to consider just generating the junit xml report, as the further processing really depends on what one is actually doing.

**Comment by vasukulkarni** [comment]
Closing stale issue.

**Comment by mbukatov** [comment]
> Closing stale issue.

Which means closed as WONTFIX. That said, the functionality has been automatically enabled on a different level: option ` --junit-xml ` is always used in jenkins managed CI runs.
