### ISSUE TITLE
In IBM Power (ppc64le) environment, fio related errors

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#3222]
Found something interesting about these fio test-cases : 

ocs-ci tests cases create temporary pods (could be named cephs, rbd, etc..) and installs fio in them and runs fio.  This bug describes three different scenarios:
1. 
fio gets installed successfully and gets run successfully and test case succeeds. - in this category, the pod image is debian.

2. fio gets installed successfully but when it is executed it fails. with runtime=30 instead of 60 sometimes it succeeds. in this category also, the pod image is debian.

3. fio is not getting installed at all . in this category the pod image is fedora.

In the third case, I can use oc rsh and enter inside the fedora imaged pod and able to install fio using 'yum -y install fio' and able to run fio command.

sample testcase for cases 1 and 2 : tests/manage/pv_services/test_no_space_left.py::TestPVCFullWithIORWO::test_pvc_no_space_left[CephFileSystem]

sample testcase for case 3 : tests/manage/pv_services/test_run_io_multiple_pods.py::TestIOMultiplePods::test_run_io_multiple_pods[CephBlockPool]

Due to this, few of the tier2 test cases are failing.

**Comment by gitsridhar** [comment]
Scenario 2 above is addressed in https://github.com/red-hat-storage/ocs-ci/issues/1772

**Comment by mbukatov** [comment]
It would  make sense to use fedora container image with fio preinstalled. We use `quay.io/fbalak/fio-fedora:latest` and/or `quay.io/multiarch-origin-e2e/fio-fedora:latest` depending on the architecture for metrics testing workloads.

Architecture  ppc64le is included in https://quay.io/repository/multiarch-origin-e2e/fio-fedora?tag=latest&tab=tags

**Comment by AaruniAggarwal** [comment]
@jilju 
I am attaching the log file for the 3rd scenario ie. io is not getting installed at all . in this category the pod image is fedora.
[fio-fedora-error.txt](https://github.com/red-hat-storage/ocs-ci/files/5460873/fio-fedora-error.txt)

**Comment by gitsridhar** [comment]
@mbukatov I tried to use 'quay.io/multiarch-origin-e2e/fio-fedora:latest' but the pod did not come up. I think this is only a base image, with no app is running, so it quits. 

from oc describe output:
Containers:
  web-server:
    Container ID:   cri-o://0b18a184fdd9cfbebce9fd2f47e3ba7a1167e2dba0b51051b9bdac58c9d28fd3
    Image:          quay.io/multiarch-origin-e2e/fio-fedora:latest
    Image ID:       quay.io/multiarch-origin-e2e/fio-fedora@sha256:cc89fc03a7d525a542d7819c7763b2625c3926348f57a835033c72f07c848742

Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               61s               default-scheduler        Successfully assigned namespace-test-efc542aa822044e49bdfeac18fe5f712/pod-test-cephfs-df51317d458e46f5b927943ecb5a2060 to worker-2
  Normal   SuccessfulAttachVolume  60s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-301e0868-c6a7-4aec-9863-b0091533cd7e"
  Normal   AddedInterface          40s               multus                   Add eth0 [10.129.2.78/23]
  Normal   Pulling                 6s (x3 over 40s)  kubelet, worker-2        Pulling image "quay.io/multiarch-origin-e2e/fio-fedora:latest"
  Normal   Pulled                  5s (x3 over 22s)  kubelet, worker-2        Successfully pulled image "quay.io/multiarch-origin-e2e/fio-fedora:latest"
  Normal   Created                 5s (x3 over 21s)  kubelet, worker-2        Created container web-server
  Normal   Started                 4s (x3 over 21s)  kubelet, worker-2        Started container web-server
  Warning  BackOff                 4s (x3 over 18s)  kubelet, worker-2        Back-off restarting failed container

The yaml file used is :
ocs_ci/templates/CSI/cephfs/pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
spec:
  containers:
   - name: web-server
     image: quay.io/multiarch-origin-e2e/fio-fedora:latest
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: cephfs-pvc
       readOnly: false

I temporarily modified pod.yaml and if it works, I planned to create ibmpod.yaml in this directory with this content and modify tests/helpers.py to use this for the IBM ppc64le platform. 

The testcase I am using is : 

run-ci -m "tier2 and manage" --ocsci-conf conf/ocsci/production_powervs_upi.yaml --cluster-name ocstest --cluster-path /home/test tests/manage/pv_services/test_no_space_left.py::TestPVCFullWithIORWX::test_pvc_no_space_left

**Comment by vasukulkarni** [comment]
If its consistent on IBM platform, can you set a debug point in the test and login to pod and try to run those steps manually? I think that will give some more clue to what we are missing.

**Comment by gitsridhar** [comment]
Vasu, I did that with pdb. Under debug environment if I run fio it works.

**Comment by zmc** [comment]
The problem was haproxy timing out requests to the k8s api server. Our fix is: https://github.com/RedHatOfficial/ocp4-helpernode/pull/178
