### ISSUE TITLE
osd encryption verification failed on external cluster

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#3227]
osd encryption verification failed on external cluster

```
    def get_osd_size():
        """
        Get osd size from Storage cluster
    
        Returns:
            int: osd size
    
        """
        sc = get_storage_cluster()
        return int(
>           sc.get().get('items')[0].get('spec').get('storageDeviceSets')[0].get(
                'dataPVCTemplate'
            ).get('spec').get('resources').get('requests').get('storage')[:-2]
        )
E       TypeError: 'NoneType' object is not subscriptable

ocs_ci/ocs/resources/storage_cluster.py:517: TypeError
```

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13979//console

**Comment by petr-balogh** [comment]
@OdedViner FYI

**Comment by vavuthu** [comment]
@OdedViner @ebenahar Looks like encryption is not supported on external cluster. Could you please confirm?

**Comment by OdedViner** [comment]
@petr-balogh @vavuthu 
Encryption support on external cluster
The test failed because the function `get_osd_size` does not support on External  cluster.

**Comment by vavuthu** [comment]
> @petr-balogh @vavuthu
> Encryption support on external cluster
> The test failed because the function `get_osd_size` does not support on External cluster.

I have spend some time on friday and deployed external cluster with encryption enabled. i didn't see encryption enabled on external cluster. Since all ceph process ( like osd, mgr, mon etc ) are dependent on RHCS, not sure of above statement. Do you have any successful deployment on external cluster ?

**Comment by petr-balogh** [comment]
I asked Sebastien to add his input here, to confirm the support.

**Comment by leseb** [comment]
Encryption on external cluster is transparent, whether the external cluster is encrypted or not, we cannot tell. So turning on encryption server side is not possible. Only the ceph-csi layer can have it enabled. So editing the CephCluster spec will do nothing.

**Comment by vavuthu** [comment]
From the above comment, closing the issue
