### ISSUE TITLE
Must gather is not collected 

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#3240]
As described in https://github.com/red-hat-storage/ocs-ci/issues/3083#issuecomment-717784422 by @MeridianExplorer, must gather is not collected upon test failures and all we have is a file called `timestamp`.

**Comment by OdedViner** [comment]
OCS4.6 must_gather failes to complete in 600sec 

1.Collect must_gather:
oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.6

2.Failes to complete in 600sec 
```image=quay.io/rhceph-dev/ocs-must-gather:latest-4.6 --dest-dir=/home/jenkins/current-cluster-dir/logs/deployment_1603639721/ocs_must_gather
17:07:50 - MainThread - ocs_ci.ocs.utils - ERROR - Timeout 600s for must-gather reached, command exited with error: Command '['oc', '--kubeconfig', '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig', 'adm', 'must-gather', '--image=quay.io/rhceph-dev/ocs-must-gather:latest-4.6', '--dest-dir=/home/jenkins/current-cluster-dir/logs/deployment_1603639721/ocs_must_gather']' timed out after 600 seconds```


@crombus 
Why collection time on OCS4.6 longer than OCS4.5?

**Comment by ebenahar** [comment]
Closed via https://github.com/red-hat-storage/ocs-ci/pull/3245
