### ISSUE TITLE
exec_cmd consume a lot of memory

### ISSUE THREAD

**Issue by Avilir** [red-hat-storage/ocs-ci#3256]
the function exec_cmd at ocs_ci/utility/utils.py (line 419) consume ~70M of memory only by importing it.

my suspicion is that the use of shlex.split(cmd), but this need some more investigation

**Comment by clacroix12** [comment]
@Avilir can you elaborate on this issue? How are you determining 70M from importing and what do you propose we do with this information? `exec_cmd` is very heavily used throughout ocs-ci and as such should be treated very carefully.

**Comment by Avilir** [comment]
@clacroix12 , i found the amount of memory that used by this function buy creating new test (locally) which is calling to this function that is running the sleep command and monitored it with `top`.
i replaced the `shlex.split(cmd)` with regular split command and see that it consume 70MB less of memory while i used regular split.

i do not know if there is a specific reason to use the `shlex.split(cmd)` command, but for performance test we have now the `ocs_ci.helpers.performance_lib.run_command()` function which use the regular split.

**Comment by Avilir** [comment]
closing after implementing function for performance used : ocs_ci.helpers.performance_lib.run_command()
