### ISSUE TITLE
test_pv_scale_out_create_pvcs_and_respin_ceph_pods is not collected even it's running on vSphere

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3262]
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14197/console

In this job I see it's been scheduled on vSphere but I see this error:

```
16:44:18 - MainThread - conftest - INFO - Test <Function test_pv_scale_out_create_pvcs_and_respin_ceph_pods[mgr]> is removed from the collected items since it does not run on vSphere
16:44:18 - MainThread - conftest - INFO - Test <Function test_pv_scale_out_create_pvcs_and_respin_ceph_pods[mon]> is removed from the collected items since it does not run on vSphere
16:44:18 - MainThread - conftest - INFO - Test <Function test_pv_scale_out_create_pvcs_and_respin_ceph_pods[osd]> is removed from the collected items since it does not run on vSphere
16:44:18 - MainThread - conftest - INFO - Test <Function test_pv_scale_out_create_pvcs_and_respin_ceph_pods[mds]> is removed from the collected items since it does not run on vSphere
```

I see it's probably cause of this code:
https://github.com/red-hat-storage/ocs-ci/blame/e3807af1f265b55eee7a35a54597a130276a0bb4/tests/e2e/scale/conftest.py#L21

Done by @wusui .  Can you please take a look at it?
Also adding @ramkiperiy as he is author of the tests.

It's from deployment, so these tests shouldn't run that. But the message is confusing.

Thanks

**Comment by wusui** [comment]
What would be a better way of wording this?  Something like:

Deployment test <...> does not run on vSphere ?

**Comment by petr-balogh** [comment]
@wusui seeing this old issue when doing cleanup on old issues. I would suggest to change it to something like:
```
is removed from the collection as the test is not supported on vSphere platform
```
