### ISSUE TITLE
test_disruptive_during_pod_pvc_deletion[CephFileSystem-delete_pods-cephfsplugin] failure

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#3269]
The test `test_disruptive_during_pod_pvc_deletion[CephFileSystem-delete_pods-cephfsplugin]` fails with the following error:

TimeoutError: Timeout when waiting for pvc-3ab45599-79cb-4dc7-a699-49b19576a57b to delete. 

`Warning  VolumeFailedDelete  0s (x9 over 2m8s)  openshift-storage.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-98d99f679-f5lsx_0d5c1925-2cae-4d35-b9b8-27537f30143f  persistentvolume pvc-3ab45599-79cb-4dc7-a699-49b19576a57b is still attached to node compute-2`

This issue was seen in two tier4c runs:
- https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14059/ (RUN ID: 1604060449)
- https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14111/ (RUN ID: 1604250748)

The test case passed when executed locally.

**Comment by jilju** [comment]
Seen in [RUN ID: 160491811](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14408/testReport/tests.manage.pv_services.test_resource_deletion_during_pod_pvc_deletion/TestDeleteResourceDuringPodPvcDeletion/test_disruptive_during_pod_pvc_deletion_CephFileSystem_delete_pods_cephfsplugin_/)

**Comment by jilju** [comment]
Opened OCS bug https://bugzilla.redhat.com/show_bug.cgi?id=1898521

**Comment by jilju** [comment]
This is not an ocs-ci issue. The product bug is fixed. Hence cllosing this issue.
