### ISSUE TITLE
New uninstall is breaking the destroy job

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3274]
https://github.com/red-hat-storage/ocs-ci/blame/master/ocs_ci/deployment/deployment.py#L863 this is problematic line:

```
11:13:49 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "storageclusterinitializations.ocs.openshift.io" not found

11:13:49 - MainThread - ocs_ci.deployment.deployment - ERROR - Failed to uninstall OCS. Exception is: <class 'Exception'>
```

We should print specific exception and not trying to print Class of Exception in the log.

**Comment by vavuthu** [comment]
@petr-balogh Do you have jenkins job link

**Comment by petr-balogh** [comment]
@vavuthu  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/11257/console
