### ISSUE TITLE
ocs-operator with selector: ocs-operator-internal=true not found!

### ISSUE THREAD

**Issue by shreekarSS** [red-hat-storage/ocs-ci#3285]
We are seeing 
E               ocs_ci.ocs.exceptions.ResourceNotFoundError: Requested packageManifest: ocs-operator with selector: ocs-operator-internal=true not found!
In run https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14224/testReport/junit/tests.e2e.workloads.couchbase.test_couchbase_pod_respin/TestCouchBasePodRespin/test_run_couchbase_respin_pod_mon_/

from  self.sanity_helpers = Sanity() class,  which checks for noobaa_health_check(), checks for check_if_cluster_was_upgraded() which is throwing  E               ocs_ci.ocs.exceptions.ResourceNotFoundError: Requested packageManifest: ocs-operator with selector: ocs-operator-internal=true not found! 

By adding wait before checking the packageManifest or by adding couple of retries to get the desired output may solve this prob lem

**Comment by shreekarSS** [comment]
@petr-balogh what do you think?

**Comment by jimdevops19** [comment]
I saw this error appearing here as well https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci/184
I'll look forward to adding a couple of retries for this.

**Comment by Akarsha-rai** [comment]
We are again hitting this issue, most of the tests here failed with below errors
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16656/testReport/


```
ocs_ci.ocs.exceptions.ResourceNotFoundError: Requested packageManifest: ocs-operator with selector: ocs-operator-internal=true not found!
```

@petr-balogh @jimdevops19 increasing retries did not help much here, any idea?

**Comment by Akarsha-rai** [comment]
> @Akarsha-rai have you seen this issue again recently or it's now OK?

Last we hit the issue on the run where two of the test case failed after the node reboot(_BUILD ID: v4.7.0-294.ci RUN ID: 1615640332_)

Test case: 
- tests/e2e/workloads/jenkins/test_jenkins_node_reboot.py::TestJenkinsNodeReboot::test_run_jenkins_node_reboot[worker-2-15]
- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py::TestMonitoringBackedByOCS::test_monitoring_when_one_of_the_prometheus_node_down

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/186/testReport/junit/tests.e2e.monitoring.test_monitoring_on_negative_scenarios/TestMonitoringBackedByOCS/test_monitoring_when_one_of_the_prometheus_node_down/

**Comment by MeridianExplorer** [comment]
This is still happening, last observed here - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/3440/
Specifically, in
`tests.manage.mcg.test_host_node_failure.TestNoobaaSTSHostNodeFailure.test_noobaa_sts_host_node_failure[noobaa-db-pg-True]
tests.manage.mcg.test_mcg_resources_disruptions.TestMCGResourcesDisruptions.test_delete_noobaa_resources[noobaa_core]`
