### ISSUE TITLE
Leftover Ceph debug pods cause a false teardown failure in our automation runs

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#3290]
[Example run](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14409/)
[Example leftover](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14409/testReport/junit/tests.manage.mcg.test_bucket_deletion/TestBucketDeletion/test_bucket_delete_with_objects_OC_/)

The issue started to appear after we started collecting Ceph crash info.

**Comment by ebenahar** [comment]
Is this the same as https://github.com/red-hat-storage/ocs-ci/issues/3237?

**Comment by MeridianExplorer** [comment]
Duplicate of #3237
