### ISSUE TITLE
Add node for vmware UPI fails 

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#3294]
Logs:- http://pastebin.test.redhat.com/917147

**Comment by yitzhak12** [comment]
I got a timeout error when trying to add a new node from the cli. Cluster conf: vSphere UPI, NON-LSO, OCP 4.6, OCS 4.6. 
I used this conf file: https://github.com/red-hat-storage/ocs-ci/blob/master/conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml

Logs: http://pastebin.test.redhat.com/924758
