### ISSUE TITLE
Destroy job fails during post-destroy checks

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#3299]
Destroy job link: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/11441/console

E            pyVmomi.VmomiSupport.vmodl.fault.ManagedObjectNotFound: (vmodl.fault.ManagedObjectNotFound) {
E               dynamicType = <unset>,
E               dynamicProperty = (vmodl.DynamicProperty) [],
E               msg = "The object 'vim.Folder:group-v36873' has already been deleted or has not been completely created",
E               faultCause = <unset>,
E               faultMessage = (vmodl.LocalizableMessage) [],
E               obj = 'vim.Folder:group-v36873'
E            }

.venv/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py:1647: vmodl.fault.ManagedObjectNotFound

**Comment by vavuthu** [comment]
mostly someone deleted the resource pool manually and ran destroy job so that its not able to get the target resource pool.

Closing this issue as we didn't see this issue recently.
