### ISSUE TITLE
Docker rate limt

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#3320]
Looks like we will hit the docker rate limit, IBM platform testing is hitting it and 500 pull per 6 hour for free users seems too low

```
Warning  Failed          <invalid>  kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/library/nginx: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

```

**Comment by vasukulkarni** [comment]
https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=increase%20rate%20limit&utm_budget=

**Comment by mbukatov** [comment]
Let's solve this by not using docker hub. Why are we doing this?

**Comment by vasukulkarni** [comment]
> Let's solve this by not using docker hub. Why are we doing this?

We should be able to use quay, what other options are you thinking about? I think most of the images are available in docker by default with new rate limit its just what makes sense now, nginx  as Venkat pointed out gets pulled by all tests.

**Comment by vasukulkarni** [comment]
It actually gets consumed from master/worker node and since we are rotating names we aren't really hitting it that hard internally.

**Comment by mbukatov** [comment]
> We should be able to use quay, what other options are you thinking about?

Yes, I have [quay.io](https://quay.io/) in mind.

**Comment by vasukulkarni** [comment]
@gitsridhar @Avilir @ramkiperiy FYI

**Comment by vasukulkarni** [comment]
got the amd64 in quay https://quay.io/repository/ocsci/nginx?tab=info

**Comment by vasukulkarni** [comment]
Now we have all arch https://quay.io/repository/ocsci/nginx?tab=tags
