### ISSUE TITLE
Test case test_add_capacity failed due to timeout on zVM cluster.

### ISSUE THREAD

**Issue by chidanandbh** [red-hat-storage/ocs-ci#3336]
tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacity::test_add_capacity

test_add_capacity failed due to time of 300 seconds on zVM cluster and below the verbose output, where it trying to bring 3 more `osd` pods to `Running` state and its not able to bring within specified timeout and test case getting failed on zVM cluster.

```
09:28:44 - MainThread - ocs_ci.ocs.ocp - INFO - status of  at column STATUS - item(s) were ['Running', 'Running', 'Running'], but we were waiting for all 6 of them to be Running
09:28:44 - MainThread - ocs_ci.ocs.ocp - ERROR - timeout expired: Timed Out: (300,)
09:28:44 - MainThread - ocs_ci.ocs.ocp - ERROR - Wait for Pod resource  at column STATUS to reach desired condition Running failed, last actual status was ['Running', 'Running', 'Running']
09:28:44 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /root/ocp4-workdir/auth/kubeconfig describe Pod  --selector=app=rook-ceph-osd
09:28:44 - MainThread - ocs_ci.ocs.ocp - WARNING - Description of the resource(s) we were waiting for:
```

**Comment by vasukulkarni** [comment]
can you submit a PR if increasing timeout is working for you?

**Comment by chidanandbh** [comment]
Even after increasing the time it pods did not come , I did more investigation and discussed with few people from Redhat, got to know that it has to skip for s390x architecture (Z Hardware) and also got know that its need platform specific code in platform.py file.

**Comment by chidanandbh** [comment]
> can you submit a PR if increasing timeout is working for you?

are you talking about this test case for raise PR https://github.com/red-hat-storage/ocs-ci/issues/3335
