### ISSUE TITLE
Need to figure out what is the maximum number of OSD's in vSphere cluster

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3352]
I saw a lot of failures when testing the cluster expansion with vSphere. When we have 9 OSD's, and we try to add 3 more, only 11 OSD's reach status "Running" instead of 12, while in AWS, they can reach 15 OSD's. 
Here is an example of such a test run: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13975/.
And here is the test: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13975/testReport/tests.manage.z_cluster.cluster_expansion.test_delete_pod/TestAddCapacityWithResourceDelete/test_add_capacity_with_resource_delete_workload_storageutilization_rbd1_operator_0_False_/

I think there is a chance that it is related to the amount of memory in vSphere or the hardware - also, it may depend on the OSD size. 
One workaround is to limit the number of OSD's when we use specific configurations.

**Comment by petr-balogh** [comment]
Do we know exact product limit how many OSDs it can handle for 3w/3m setup on recommended configuration?

**Comment by shreekarSS** [comment]
> Do we know exact product limit how many OSDs it can handle for 3w/3m setup on recommended configuration?

I think 3 osds per Node , total 9 osds is recommended

**Comment by ebenahar** [comment]
I discussed this with @yitzhak12 and we came up with an approach of setting a limit of OSD per node (probably 3) and once this is reached during the execution, a new worker node will be added prior to the next test that does add capacity.

@petr-balogh @shreekarSS what do you think?

**Comment by shreekarSS** [comment]
> I discussed this with @yitzhak12 and we came up with an approach of setting a limit of OSD per node (probably 3) and once this is reached during the execution, a new worker node will be added prior to the next test that does add capacity.
> 
> @petr-balogh @shreekarSS what do you think?

Sounds good @ebenahar

**Comment by yitzhak12** [comment]
Currently, this can't be accomplished because the PR https://github.com/red-hat-storage/ocs-ci/pull/2504 is not merged yet. 
We need to wait for this PR to be merged, or maybe to use this conf https://github.com/red-hat-storage/ocs-ci/blob/master/conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_6w.yaml when running the test.

**Comment by ebenahar** [comment]
@yitzhak12 this PR is quite old..not sure it's still relevant. @vavuthu?

**Comment by vavuthu** [comment]
@yitzhak12 @ebenahar above PR is not relevant now. I will close that  PR.

**Comment by yitzhak12** [comment]
We can see from this test run https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15363/, that this attitude really worked, and the test `tests.manage.z_cluster.cluster_expansion.test_delete_pod.TestAddCapacityWithResourceDelete.test_add_capacity_with_resource_delete` has finished successfully with all 15 OSD's up and running
