### ISSUE TITLE
Update CRD list based on OCS 4.6 version

### ISSUE THREAD

**Issue by venkat-pinisetti** [red-hat-storage/ocs-ci#3356]
In OCS 4.6 , CRD storageclusters.ocs.openshift.io has been removed. Thus, CRD list has to be updated for successful un-installation of OCS.

Ref : https://bugzilla.redhat.com/show_bug.cgi?id=1897555

Current list:

[root@ocsci ocs-ci]# cat ocs_ci/ocs/uninstall.py |grep "crd_list =" -A 13
    crd_list = [
        "backingstores.noobaa.io",
        "bucketclasses.noobaa.io",
        "cephblockpools.ceph.rook.io",
        "cephfilesystems.ceph.rook.io",
        "cephnfses.ceph.rook.io",
        "cephobjectstores.ceph.rook.io",
        "cephobjectstoreusers.ceph.rook.io",
        "noobaas.noobaa.io",
        "ocsinitializations.ocs.openshift.io",
        "storageclusterinitializations.ocs.openshift.io",
        "storageclusters.ocs.openshift.io",
        "cephclusters.ceph.rook.io",
    ]

@annagitel, please try if you can fix this as part of https://github.com/red-hat-storage/ocs-ci/pull/3345

**Comment by annagitel** [comment]
this list is not final, some crds were added and some removed. still waiting for finalization

**Comment by venkat-pinisetti** [comment]
Sure. Thanks for the update.

**Comment by vasukulkarni** [comment]
We also have https://github.com/red-hat-storage/ocs-ci/pull/3346/
