### ISSUE TITLE
Performance test run handles only x86 images

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#3362]
For example, while executing the test case tests/e2e/performance/test_fio_benchmark.py::TestFIOBenchmark::test_fio_workload_simple[CephFileSystem-sequential]

the test is trying to create a pod in my-ripsaw namespace and the images for various containers in it are:

quay.io/benchmark-operator/benchmark-operator:master and 
k8s.gcr.io/redis:v1

These are available only for x86 platform and not for other platforms like ppc64le or IBM Z. Because of this, the pods are not coming up and during debug session found that:

[svenkat@nx123 logs]$ oc logs  benchmark-operator-6d9b9797f-4rmdk -n my-ripsaw -c ansible
standard_init_linux.go:219: exec user process caused: exec format error
[svenkat@nx123 logs]$ oc logs  benchmark-operator-6d9b9797f-4rmdk -n my-ripsaw -c benchmark-operator
standard_init_linux.go:219: exec user process caused: exec format error
[svenkat@nx123 logs]$ oc logs  benchmark-operator-6d9b9797f-4rmdk -n my-ripsaw -c redis-master
standard_init_linux.go:219: exec user process caused: exec format error
[svenkat@nx123 logs]$

Looked into quay.io: https://quay.io/repository/benchmark-operator/benchmark-operator?tab=tags it is not available for multiple architectures. I could not check k8s.gcr.io.

Because of this, ocs-ci performance test run is not possible. I understand the same issue exists for system Z as well.

**Comment by chidanandbh** [comment]
Even on Z hardware I have seen this while running `tier2` test , below to are 2 test which getting failed

1. tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py::TestPvcCloneOfWorkloads::test_pvc_clone 
2. tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py::TestPvcSnapshotOfWorkloads::test_pvc_snapshot


```
[root@m13lp43 ~]# oc get pods
NAME                                 READY   STATUS             RESTARTS   AGE
benchmark-operator-6d9b9797f-vmc6q   0/3     CrashLoopBackOff   6          80s
postgres-0                           1/1     Running            0          79s
postgres-1                           1/1     Running            0          51s
postgres-2                           1/1     Running            0          29s
[root@m13lp43 ~]#
```
```
[root@test1-bbrrm-worker-0-k52f6 ~]# podman images | grep "benchmark-operator"
quay.io/benchmark-operator/benchmark-operator                        master       362d3465660c   2 days ago     519 MB
[root@test1-bbrrm-worker-0-k52f6 ~]# podman inspect 362d3465660c | grep architecture
                "architecture": "x86_64",
            "architecture": "x86_64",
[root@test1-bbrrm-worker-0-k52f6 ~]# 
```

**Comment by Sarah-Kriesch** [comment]
Or specific for ripsaw:

```
[root@m1308001 ~]#  kubectl get pods -n my-ripsaw 
NAME                                 READY   STATUS             RESTARTS   AGE
benchmark-operator-6d9b9797f-j4d7c   0/3     CrashLoopBackOff   801        22h
```
```
[root@m1308001 ~]# oc get sa -n my-ripsaw  
NAME                 SECRETS   AGE
benchmark-operator   2         22h
builder              2         23h
default              2         23h
deployer             2         23h

```

**Comment by gitsridhar** [comment]
Here is the entire pod details in my-ripsaw namespace:

[svenkat@nx123-ahv logs]$ oc describe pod benchmark-operator-6d9b9797f-6qj55
Name:         benchmark-operator-6d9b9797f-6qj55
Namespace:    my-ripsaw
Priority:     0
Node:         worker-2/192.168.88.23
Start Time:   Thu, 19 Nov 2020 10:12:40 -0600
Labels:       name=benchmark-operator
              pod-template-hash=6d9b9797f
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.128.2.69"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.128.2.69"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: restricted
Status:       Running
IP:           10.128.2.69
IPs:
  IP:           10.128.2.69
Controlled By:  ReplicaSet/benchmark-operator-6d9b9797f
Containers:
  ansible:
    Container ID:  cri-o://c35793a44db135aa8955d64437260820e24873988278e66de26bb6bfc901379a
    Image:         quay.io/benchmark-operator/benchmark-operator:master
    Image ID:      quay.io/benchmark-operator/benchmark-operator@sha256:d71174cc049ebb00c001390f747374ed78d5310a800c91c0dc75d96f816cf0c2
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/ao-logs
      /tmp/ansible-operator/runner
      stdout
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 19 Nov 2020 10:15:59 -0600
      Finished:     Thu, 19 Nov 2020 10:15:59 -0600
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /tmp/ansible-operator/runner from runner (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from benchmark-operator-token-tlpl4 (ro)
  benchmark-operator:
    Container ID:   cri-o://cced1317233228894ca38e93081069ef0b9420e98f71868bfd9f837d50eff32d
    Image:          quay.io/benchmark-operator/benchmark-operator:master
    Image ID:       quay.io/benchmark-operator/benchmark-operator@sha256:d71174cc049ebb00c001390f747374ed78d5310a800c91c0dc75d96f816cf0c2
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 19 Nov 2020 10:16:01 -0600
      Finished:     Thu, 19 Nov 2020 10:16:01 -0600
    Ready:          False
    Restart Count:  5
    Environment:
      WATCH_NAMESPACE:                            my-ripsaw (v1:metadata.namespace)
      POD_NAME:                                   benchmark-operator-6d9b9797f-6qj55 (v1:metadata.name)
      OPERATOR_NAME:                              benchmark-operator
      WORKER_BENCHMARK_RIPSAW_CLOUDBULLDOZER_IO:  1
      ANSIBLE_VERBOSITY:                          4
    Mounts:
      /tmp/ansible-operator/runner from runner (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from benchmark-operator-token-tlpl4 (ro)
  redis-master:
    Container ID:   cri-o://18c44209e92c959fea55bad09f7724af20759a9c4568089b345ae55945cc9676
    Image:          k8s.gcr.io/redis:v1
    Image ID:       k8s.gcr.io/redis@sha256:ae4699b8f330d61665125cd381942fc1c57613f2753c5ee6879aff173a8ccb52
    Port:           6379/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 19 Nov 2020 10:16:02 -0600
      Finished:     Thu, 19 Nov 2020 10:16:02 -0600
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:  100m
    Requests:
      cpu:  100m
    Environment:
      MASTER:  true
    Mounts:
      /redis-master-data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from benchmark-operator-token-tlpl4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  runner:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  benchmark-operator-token-tlpl4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  benchmark-operator-token-tlpl4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                 role=workload:NoSchedule
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       5m28s                  default-scheduler  Successfully assigned my-ripsaw/benchmark-operator-6d9b9797f-6qj55 to worker-2
  Normal   AddedInterface  5m26s                  multus             Add eth0 [10.128.2.69/23]
  Normal   Pulled          5m25s                  kubelet            Successfully pulled image "quay.io/benchmark-operator/benchmark-operator:master" in 795.020915ms
  Normal   Pulled          5m23s                  kubelet            Successfully pulled image "quay.io/benchmark-operator/benchmark-operator:master" in 719.808177ms
  Normal   Pulled          5m19s                  kubelet            Successfully pulled image "quay.io/benchmark-operator/benchmark-operator:master" in 708.668896ms
  Normal   Pulling         5m19s (x2 over 5m25s)  kubelet            Pulling image "quay.io/benchmark-operator/benchmark-operator:master"
  Normal   Created         5m18s (x2 over 5m24s)  kubelet            Created container ansible
  Normal   Started         5m17s (x2 over 5m23s)  kubelet            Started container ansible
  Normal   Pulling         5m17s (x2 over 5m23s)  kubelet            Pulling image "quay.io/benchmark-operator/benchmark-operator:master"
  Normal   Pulled          5m17s                  kubelet            Successfully pulled image "quay.io/benchmark-operator/benchmark-operator:master" in 813.57337ms
  Normal   Created         5m16s (x2 over 5m22s)  kubelet            Created container benchmark-operator
  Normal   Pulled          5m16s (x2 over 5m21s)  kubelet            Container image "k8s.gcr.io/redis:v1" already present on machine
  Normal   Started         5m16s (x2 over 5m21s)  kubelet            Started container benchmark-operator
  Normal   Started         5m15s (x2 over 5m20s)  kubelet            Started container redis-master
  Normal   Created         5m15s (x2 over 5m20s)  kubelet            Created container redis-master
  Warning  BackOff         5m14s                  kubelet            Back-off restarting failed container
  Warning  BackOff         5m14s                  kubelet            Back-off restarting failed container
  Warning  BackOff         21s (x26 over 5m14s)   kubelet            Back-off restarting failed container
[svenkat@nx123-ahv logs]$ oc logs benchmark-operator-6d9b9797f-6qj55
error: a container name must be specified for pod benchmark-operator-6d9b9797f-6qj55, choose one of: [ansible benchmark-operator redis-master]
[svenkat@nx123-ahv logs]$ oc logs benchmark-operator-6d9b9797f-6qj55 -c ansible
standard_init_linux.go:219: exec user process caused: exec format error
[svenkat@nx123-ahv logs]$ oc logs benchmark-operator-6d9b9797f-6qj55 -c benchmark-operator
standard_init_linux.go:219: exec user process caused: exec format error
[svenkat@nx123-ahv logs]$ oc logs benchmark-operator-6d9b9797f-6qj55 -c redis-master
standard_init_linux.go:219: exec user process caused: exec format error
[svenkat@nx123-ahv logs]$

**Comment by vasukulkarni** [comment]
We have to check with ripsaw team on how to handle it.

**Comment by vasukulkarni** [comment]
we have the following images for ppl64e from @piyushgupta1551 and I see @jtaleric  has offered to upload them to benchmark-operator but we need someone to maintain them if it changes in future, so we could use those images for pl64 but similar images have to be uploaded for Z and someone has to signup for that.



```
, yes I will raise the PR for ppc64le Dockerfiles. In my opinion all dockerfiles except iperf will need these additions to be ppc64le compliant.
So far I've created 4 images for ppc64le -

    quay.io/piyushgupta1551/benchmark-operator:master (this needs recreation after yesterday's uperf sa issue. The template needs to be updated)
    quay.io/piyushgupta1551/uperf:master
    quay.io/piyushgupta1551/iperf:master
    quay.io/piyushgupta1551/fio:master

How do you want me to add in the python packages that I added in setup.cfg? Should I add them in the Dockerfiles directly? Adding them in setup.cfg might create a conflict as they are not really required for x86.
```

**Comment by gitsridhar** [comment]
Another image quay.io/strimzi/operator:latest has the same issues, it is only x86.  I do not see this anywhere in the ocs-ci source code, so must be getting pulled indirectly. We see this during workloads run.

**Comment by chidanandbh** [comment]
quay.io/multi-arch/benchmark-operator:latest  is now available for s390x but as ripsaw code look for image `quay.io/benchmark-operator/benchmark-operator:master`  As a workaround before running the test I removed this images (quay.io/benchmark-operator/benchmark-operator:master),from all worker and then pulled s390x "benchmark-operator" image from multi-arch and tagged with image name "ripsaw" code is looking. Still seeing same issue. 


podman rmi -f 362d3465660c
podman pull quay.io/multi-arch/benchmark-operator
podman tag quay.io/multi-arch/benchmark-operator:latest quay.io/benchmark-operator/benchmark-operator:master

I see during the test its cloning the `ripsaw` from https://github.com/cloud-bulldozer/ripsaw

**Comment by Sarah-Kriesch** [comment]
In my case, ripsaw was not found and I followed the instructions of:
https://www.openshift.com/blog/benchmarking-openshift-network-performance-part-1-basics

That is using ripsaw from the repository https://github.com/cloud-bulldozer/ripsaw.git

**Comment by Sarah-Kriesch** [comment]
> I see during the test its cloning the `ripsaw` from https://github.com/cloud-bulldozer/ripsaw

Which test is cloning ripsaw? There are multiple test suites using this benchmark operator.

**Comment by chidanandbh** [comment]
> In my case, ripsaw was not found and I followed the instructions of:
> https://www.openshift.com/blog/benchmarking-openshift-network-performance-part-1-basics
> 
> That is using ripsaw from the repository https://github.com/cloud-bulldozer/ripsaw.git
> 
> > I see during the test its cloning the `ripsaw` from https://github.com/cloud-bulldozer/ripsaw
> 
> Which test is cloning ripsaw? There are multiple test suites using this benchmark operator.

https://github.com/red-hat-storage/ocs-ci/issues/3362#issuecomment-730443800

**Comment by gitsridhar** [comment]
This image is also available only on x86 : registry.redhat.io/jboss-eap-7-tech-preview/eap-cd-openshift-rhel8:latest

**Comment by gitsridhar** [comment]
@chidanandbh I see ripsaw cloning errors in 'performance' run of run-ci.

**Comment by Sarah-Kriesch** [comment]
@chidanandbh That is the reason for asking "where" it is cloned in the test. So we can replace the link.

**Comment by gitsridhar** [comment]
@Sarah-Kriesch look at the beginning of this issue, i mentioned the actual test case in 'performance' run : 
tests/e2e/performance/test_fio_benchmark.py::TestFIOBenchmark::test_fio_workload_simple[CephFileSystem-sequential]

**Comment by chidanandbh** [comment]
> @chidanandbh I see ripsaw cloning errors in 'performance' run of run-ci.
@gitsridhar  : I am not seeing any error while cloning the ripsaw code

While executing `tier2` test cases mentioned below.
    tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py::TestPvcCloneOfWorkloads::test_pvc_clone
    tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py::TestPvcSnapshotOfWorkloads::test_pvc_snapshot

```
08:31:52 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc new-project my-ripsaw
08:31:52 - MainThread - ocs_ci.ocs.ripsaw - INFO - cloning ripsaw in /tmp/ripsaw_2auq5u3k
-------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------
```
```
[root@m1307001 ripsaw_2auq5u3k]# ls
ripsaw
[root@m1307001 ripsaw_2auq5u3k]# ls ripsaw/
build          deploy  group_vars       LICENSE  playbook.yml  requirements.yml  roles        templates  test.sh
CONTRIBUTE.md  docs    image_resources  meta     README.md     resources         run_test.sh  tests      watches.yaml
[root@m1307001 ripsaw_2auq5u3k]# pwd
/tmp/ripsaw_2auq5u3k
[root@m1307001 ripsaw_2auq5u3k]# 
```

**Comment by Sarah-Kriesch** [comment]
Cloning ripsaw is not the bug. Building/ deploying of ripsaw does not work. Using another build for multi-arch instead of the integrated ripsaw should fix the issue.

**Comment by gitsridhar** [comment]
registry.redhat.io/jboss-eap-7-tech-preview/eap-cd-openshift-rhel8:latest  is another image that is x86 only.

**Comment by gitsridhar** [comment]
@vasukulkarni what needs to be done next for this problem? Along with ripsaw, there are also issues with registry.redhat.io/jboss-eap-7-tech-preview/eap-cd-openshift-rhel8:latest and also quay.io/strimzi/operator:latest .

**Comment by vasukulkarni** [comment]
@gitsridhar , For the ppc64 we have the image in 

```
    quay.io/piyushgupta1551/benchmark-operator:master (this needs recreation after yesterday's uperf sa issue. The template needs to be updated)
    quay.io/piyushgupta1551/uperf:master
    quay.io/piyushgupta1551/iperf:master
    quay.io/piyushgupta1551/fio:master
```

but we haven't got the response from piyush yet here: https://github.com/cloud-bulldozer/benchmark-wrapper/issues/228 

Once that PR is raised, I think bunch of issues on ppc64 will be resolved, I am not sure jboss and eap is required but can be looked after above(main issue) is resolved.

**Comment by piyushgupta1551** [comment]
@vasukulkarni - I will be having a discussion with Joe from perf-scale team regarding a permanent solution for ppc64le work for ripsaw sometime this week hopefully. My last comment on #228 issue was rather a question on on the PR. I was looking to get a response on that so that I can raise the PR accordingly. I'm hoping all this should be sorted once we have

**Comment by Sarah-Kriesch** [comment]
We are speaking about performance tests for ocs-ci in this issue.
The log file for performance tests for s390x is referencing errors with the following 3 images:
- ansible
- benchmark-operator
- redis-master

Additionally, we have got problems with fio (ERROR at teardown of TestFIOBenchmark.test_fio_workload_simple[CephFileSystem-random]):

```
21:25:30 - ThreadPoolExecutor-40_0 - ocs_ci.utility.workloads.fio - INFO - Running cmd: fio --name=fio-fillup --filename=/var/lib/www/html/pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973-0 --rw=write --bs=1m --direct=1 --numjobs=1 --time_based=0 --runtime=36000 --size=25600M --ioengine=libaio --output-format=json
21:25:30 - MainThread - ocs_ci.ocs.workload - INFO - Done submitting..
21:25:30 - ThreadPoolExecutor-40_0 - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-e74933b8f0a749a1b9ba84c17ca7912d --kubeconfig ../ocp4-workdir/auth/kubeconfig rsh pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973 fio --name=fio-fillup --filename=/var/lib/www/html/pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973-0 --rw=write --bs=1m --direct=1 --numjobs=1 --time_based=0 --runtime=36000 --size=25600M --ioengine=libaio --output-format=json
21:25:30 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973
21:35:30 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found Exception:
Traceback (most recent call last):
  File "/root/ocs-ci/ocs_ci/ocs/resources/pod.py", line 124, in get_fio_results
    result = self.fio_thread.result(timeout)
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

```

**Comment by chidanandbh** [comment]
I am able bring up `benchmark-operator` pod but seeing other issue, need to investigate still  

```
[root@m13lp43 z-ocs-auto]# oc get pods
NAME                                  READY   STATUS    RESTARTS   AGE
benchmark-operator-54777c84b8-vj44x   3/3     Running   0          58s
postgres-0                            1/1     Running   0          57s
postgres-1                            1/1     Running   0          50s
postgres-2                            1/1     Running   0          39s
[root@m13lp43 z-ocs-auto]# 
```

**Comment by vasukulkarni** [comment]
> We are speaking about performance tests for ocs-ci in this issue.
> The log file for performance tests for s390x is referencing errors with the following 3 images:
> 
> * ansible
> * benchmark-operator
> * redis-master
> 
> Additionally, we have got problems with fio (ERROR at teardown of TestFIOBenchmark.test_fio_workload_simple[CephFileSystem-random]):
> 
> ```
> 21:25:30 - ThreadPoolExecutor-40_0 - ocs_ci.utility.workloads.fio - INFO - Running cmd: fio --name=fio-fillup --filename=/var/lib/www/html/pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973-0 --rw=write --bs=1m --direct=1 --numjobs=1 --time_based=0 --runtime=36000 --size=25600M --ioengine=libaio --output-format=json
> 21:25:30 - MainThread - ocs_ci.ocs.workload - INFO - Done submitting..
> 21:25:30 - ThreadPoolExecutor-40_0 - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-e74933b8f0a749a1b9ba84c17ca7912d --kubeconfig ../ocp4-workdir/auth/kubeconfig rsh pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973 fio --name=fio-fillup --filename=/var/lib/www/html/pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973-0 --rw=write --bs=1m --direct=1 --numjobs=1 --time_based=0 --runtime=36000 --size=25600M --ioengine=libaio --output-format=json
> 21:25:30 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-rbd-f1b6260537264c47a4ac6b317d9fb973
> 21:35:30 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found Exception:
> Traceback (most recent call last):
>   File "/root/ocs-ci/ocs_ci/ocs/resources/pod.py", line 124, in get_fio_results
>     result = self.fio_thread.result(timeout)
>   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 434, in result
>     raise TimeoutError()
> concurrent.futures._base.TimeoutError
> ```

can you file a separate issue for s390? not sure who can own that since the container images have to be generated and tested on that platform and we dont have access to hardware, I can speak to Joe and check next week.

**Comment by gitsridhar** [comment]
Another image used in performance runs - quay.io/cloud-bulldozer/smallfile:master.

**Comment by keesturam** [comment]
@gitsridhar is this issue still valid?
