### ISSUE TITLE
test_upgrade fails with "AssertionError: Config file /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/conf/ocs_version/ocs-4.6.yaml doesn't exist!"

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#3379]
ocs and ocp version conf files now reside under ocs_ci/framework/conf instead of conf/ following this change  - https://github.com/red-hat-storage/ocs-ci/pull/3322

For some reason, the new location is not updated on the test executor

**Comment by jimdevops19** [comment]
That is the location where this should be updated as well.
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocs_upgrade.py#L227
