### ISSUE TITLE
Cleanup pod and pvc resources in test_fio_workload

### ISSUE THREAD

**Issue by shylesh** [red-hat-storage/ocs-ci#338]
pod and pvc resources needs cleanup in test_fio_workload to avoid ResourceLeftOverException. Also need a function to find PV for a given PVC

**Comment by RazTamir** [comment]
I will start working on this today

**Comment by RazTamir** [comment]
Ok ignore. 
I see Shylesh already on this

**Comment by shylesh** [comment]
Done by Elad, closing this.https://github.com/red-hat-storage/ocs-ci/pull/396
