### ISSUE TITLE
Add "wait" parameter for function "restart_nodes" in BM 

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3385]
When running this test https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py in BM platform at this line https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py#L69 when calling "restart_nodes" function the param **wait** is not defined in BM. Also, it seems we need to define the param **timeout** when using Bare Metal

**Comment by prsurve** [comment]
@yitzhak12 I have already raised a pr #2771 will update the pr shortly

**Comment by yitzhak12** [comment]
Ok, I see. Thanks
