### ISSUE TITLE
Need to check if "add_capacity" is compatible with BM

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3388]
According to this test output https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14765/consoleFull, it seems that after executing the function `add_capacity`, we still have only 3 OSD's at the end of the test. It will be a good idea to check if the function `add_capacity` https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/resources/storage_cluster.py#L419 is compatible with BM

**Comment by prsurve** [comment]
+1 we need to check if add capacity will work or not if no skip the testcase

**Comment by yitzhak12** [comment]
I have tested `add_capacity` in my local with vSphere LSO, and it failed at this line https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/resources/storage_cluster.py#L455 with the error: 

> 18:41:02 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get localvolume local-block -n openshift-local-storage 
18:41:04 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): localvolumes.local.storage.openshift.io "local-block" not found

I think it's the same error in BM. So need to update the `add_capacity` function https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/resources/storage_cluster.py#L419 to be compatible with BM 
and with vSphere LSO. I can see that we need to change "localvolume local-block" to "localvolumeset localblock". 
But I guess there are also other changes to be made.
