### ISSUE TITLE
Fixture workload_idle should pause io bg workload during it's runtime

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#3400]
Fixture workload_idle should ~skip itself (and all test cases which uses it)~ pause io bg workload if this workload is running.

Most test cases use this workload to measure idle state of OCS cluster, and when we run some workload at the same time, expectations of the test could conflict with actual results.

**Comment by fbalak** [comment]
[pause_and_resume_cluster_load fixture](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L1282) could help to not utilize cluster by background io.

**Comment by mbukatov** [comment]
> [pause_and_resume_cluster_load fixture](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L1282) could help to not utilize cluster by background io.

I can't use such fixture directly, but I can fail the test case when a workload is running alongside test cases. This taints monitoring tests for obvious reason completely.

**Comment by mbukatov** [comment]
But the remaining question is: how to detect that a test case is executed after upgrade? @petr-balogh @dahorak

**Comment by mbukatov** [comment]
@petr-balogh you would also need to make sure monitoring tests are scheduled without background IO or any other workload running along with the tests, otherwise the results are tainted and can't be used.

**Comment by ebenahar** [comment]
@mbukatov we can detect whether the test execution is running with IO in the background or not using `config.RUN['io_in_bg']`


As for:

> > [pause_and_resume_cluster_load fixture](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L1282) could help to not utilize cluster by background io.
> 
> I can't use such fixture directly, but I can fail the test case when a workload is running alongside test cases. This taints monitoring tests for obvious reason completely.

Why can't this fixture be used as follows? 

```python
def test_mcg_cpu_usage(pause_and_resume_cluster_load fixture, workload_idle):
```

**Comment by mbukatov** [comment]
I can't use the fixture directly, but I can try to carefully use the same approach and stop the workload in workload_idle fixture (because I need to the workload to be stopped during the run of the fixture only, test itself doesn't care, but at the same time, I need to have some additional margin and checks within the fixture itself. I will try that, and see how it works.
