### ISSUE TITLE
Report portal integration gaps

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3416]
Here are some improvements we should do and improve in order to move to RP

- [x] Update integration with RP5 - using newer version of RP plugin which supports RP5
- [x] We need to add squad markers for test cases
- [x] Squads should go also to xunit report for each test case
- [x] Add squad tag to the RP Launch for the execution if there was failure/skip for that squad
- [x] Separate deployment jobs for production jobs - currently with the same launch name there is execution reported for deployment only, then for specific tier suite which makes mess in report and history.
- [x] Add links to the logs for particular failed test case to its description

**Comment by petr-balogh** [comment]
@clacroix12 can you please take first 2 for now as we discussed them last time we met?
Thanks

**Comment by clacroix12** [comment]
Squad markers on test cases and in junit properties have been added in #4500

**Comment by clacroix12** [comment]
Launch names are also "unique" between deployment and test runs, this was done in this [merge request](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/593)

**Comment by clacroix12** [comment]
The rest of these AIs have been completed with our transition to rp_preproc and with the enhancements made afterwards.
