### ISSUE TITLE
Code of NooBaa related test cases should not use AWS as a default platform

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#3424]
Code of NooBaa related test cases should not use AWS as a default hard coded platform choice for object storage.

This is a problem for non AWS cloud platforms, on which the meaning of such test cases is not comparable to the same test cases executed on AWS platform. This means that until this is fixed, test run results of noobaa test cases from other cloud IPI platforms are not comparable to runs on AWS, and as such makes the results invalid/incomplete for a platform qualification.

Created based on discussion under https://github.com/red-hat-storage/ocs-ci/issues/2774#issuecomment-680744856 where the problem was spotted on Azure runs.

**Comment by mykaul** [comment]
I do believe there are 2 kinds of tests we need to consider:
1. 'native' - on every platform, Noobaa gives you an S3 endpoint, abstracting the underlying platform.
2. 'AWS' (and also others, but let us focus on AWS right now) - on every platform, you should be able to work against an AWS bucket as well. 

We should test both, regardless of the platform.
