### ISSUE TITLE
Failure due to module 'ocs_ci.ocs.constants' has no attribute 'RGW_SERVICE'

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#3434]
secret_ocp_obj = OCP(kind=constants.SECRET, namespace=self.namespace)
        route_ocp_obj = OCP(
            kind=constants.ROUTE, namespace=config.ENV_DATA["cluster_namespace"]
        )
        creds_secret_obj = secret_ocp_obj.get(secret_name)
>       endpoint = route_ocp_obj.get(resource_name=constants.RGW_SERVICE)
E       AttributeError: module 'ocs_ci.ocs.constants' has no attribute 'RGW_SERVICE'

**Comment by MeridianExplorer** [comment]
Closed in #3435
