### ISSUE TITLE
test_scale_osds_fill_75%_reboot_workers boto credential error -- may be caused by pvc creation timeouts.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3457]
See attached log
[test_scale_75.log](https://github.com/red-hat-storage/ocs-ci/files/5625896/test_scale_75.log)

**Comment by wusui** [comment]
3455, 3456, 3457 are all different problems but these may be caused by similar timeout issues.

**Comment by ramkiperiy** [comment]
Not observed this issue for quite sometime, will check in another couple of runs and decide to fix or close this issue.

**Comment by ramkiperiy** [comment]
Closing this issues, since the problem is not observed in last 3 month test runs.
