### ISSUE TITLE
test_pods_are_not_oomkilled_while_running_ios  failure  -- Nonetype not subscriptable

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3458]
E           TypeError: 'NoneType' object is not subscriptable
[test_pods_are_not_oomkilled_while_running_ios.log](https://github.com/red-hat-storage/ocs-ci/files/5626383/test_pods_are_not_oomkilled_while_running_ios.log)

This error appears at the end of a run.  It may be the result of _ TestPodAreNotOomkilledWhileRunningIO.test_pods_are_not_oomkilled_while_running_ios[CephBlockPool] _
but I am a little confused.  Are these pods supposed to be killed or not?

Anyway, there is a log attached.

[test_pods_are_not_oomkilled_while_running_ios.log](https://github.com/red-hat-storage/ocs-ci/files/5626385/test_pods_are_not_oomkilled_while_running_ios.log)

**Comment by ramkiperiy** [comment]
Expectation is pods not be killed.

**Comment by ramkiperiy** [comment]
Not observed this issue for long time, will check in another couple of runs and decide to fix or close the issue.

**Comment by ramkiperiy** [comment]
Closing this issues, since its not observed in last 3 months.
