### ISSUE TITLE
Run OCS and OCP must-gather commands in parallel

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3460]
As @mykaul pointed out in one of the execution it will be worth if we run must gather commands OCP/OCS in parallel to save some time.

**Comment by jimdevops19** [comment]
@petr-balogh 
I remember that the fixture that collects the logs was commented by the contributor with the following sentence:
**Tracking both logs separately reduce changes of collision** [link](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L3182)

We could try two things to test again if there will be a collision:

1) We could just pass to grab on both OCS+OCP:
```python
collect_ocs_logs("testcases", ocs=True, ocp=True, status_failure=False)
```

2) We could divide the executions into two different threads, so it will look like:
```python
                success_run_args = {"dir_name" : "testcases", "status_failure" : False}
                t1 = threading.Thread(target=collect_ocs_logs, kwargs={**{"ocs": False}, **success_run_args})
                t2 = threading.Thread(target=collect_ocs_logs, kwargs={**{"ocp": False}, **success_run_args})
                t1.start()
                t2.start()
```

**Comment by petr-balogh** [comment]
This is still good to have, removing stale label
