### ISSUE TITLE
Allow lower instance types only with specific configuration and disable it by default

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3463]
We see many issues with noobaa cause in some configs we miss to set the allow_lower_instance_requirements under DEPLOYMENT section to false.

This leads to some issues with the cluster like OOM kill .

So I think we should enable lower instance types not by default, but only when we use specific config.

**Comment by ebenahar** [comment]
+1 on setting this value to false as the default. Just one note - in Jenkins, the default PLATFORM_CONF is conf/ocsci/vsphere_upi.yaml, which uses lower specs than the minimum required. If we set this value to false by default, we may face other issues
