### ISSUE TITLE
pull image fedora:latest  from quay instead of docker to avoid rate limit issue

### ISSUE THREAD

**Issue by Akarsha-rai** [red-hat-storage/ocs-ci#3468]
- tests/e2e/registry/test_pod_from_registry.py::TestRegistryImage::test_run_pod_local_image

Failed to pull image **fedora:latest with error toomanyrequests: You have reached your pull rate limit**. 

We may need to use quay instead of docker to avoid rate limit issue

**Comment by vasukulkarni** [comment]
@PrasadDesala said he will look into this one.

**Comment by PrasadDesala** [comment]
duplicate of #3495
