### ISSUE TITLE
hard coded ip address for codespeed server in constants.py for performance test test_pvc_deletion_performance.py::TestPVCDeletionPerformance::test_pvc_deletion_measurement_performance

### ISSUE THREAD

**Issue by Sarah-Kriesch** [red-hat-storage/ocs-ci#3471]
We have received the following error message during executing performance tests:
```
20:26:35 - MainThread - ocs_ci.utility.performance_dashboard - INFO - Trying to push {'json': '[{"commitid": "4.6.1", "project": "OCS4.6", "branch": "stable-4.6", "executable": "4.6", "benchmark": "cephfs-pvc-deletion-time", "environment": "BAREMETAL", "result_value": 2.920778}]'} to codespeed server:  http://10.0.78.167:8000/result/add/json/
20:28:45 - MainThread - ocs_ci.utility.performance_dashboard - ERROR - Failed to push data to codespeed, make sure the server is up
```

It seems that a codespeed server is required for performance tests. That isn't written down anywhere in the ocs-ci documentation. Alternatively, no codespeed server setup is integrated into the ocs-ci installation. Additionally, a internal IP address is preconfigured.

Path to the file with the hard coded ip address:
ocs_ci/ocs/constants.py:CODESPEED_URL = "http://10.0.78.167:8000/"

Used performance test:
tests/e2e/performance/test_pvc_deletion_performance.py::TestPVCDeletionPerformance::test_pvc_deletion_measurement_performance

**Comment by Avilir** [comment]
@Sarah-Kriesch can you post the output of `oc version -o yaml` from IBM platform (ppc / z) so we can disable the codespeed for thous platform.
