### ISSUE TITLE
Generalise ES/Codespeed URLs

### ISSUE THREAD

**Issue by manojnkumar** [red-hat-storage/ocs-ci#3492]
Currently ocs-ci, has these constants in several places:

```
./ocs_ci/ocs/constants.py:CODESPEED_URL = "http://10.0.78.167:8000/"
./ocs_ci/ocs/constants.py:ES_SERVER_IP = "10.0.78.167"
./ocs_ci/ocs/constants.py:ES_SERVER_URL = "https://10.0.78.167:9200"
./ocs_ci/templates/workloads/fio/benchmark_fio.yaml:    server: 10.0.78.167
./ocs_ci/templates/workloads/smallfile/SmallFile.yaml:    server: 10.0.78.167
```

The use of a private IP means, that these cannot be used in other platforms/architectures, where this internal URL is not accessible. This issue is being opened to find a generic solution that would available for all platforms/architectures.

**Comment by Avilir** [comment]
@manojnkumar performance and scale test results are pushing to codespeed / elasticsearch server and also reported in the test log.
if the test can not push results to codespeed (while running in different network)the test will not failed and just warn about it.
regarding the using of elasticsearch, we are working on a solution which will export all data from internal (in the test deployed) elasticserch server as a raw data for analysis.
