### ISSUE TITLE
ocs_ci.utility.utils.run_cmd() should log output as it is generated

### ISSUE THREAD

**Issue by zmc** [red-hat-storage/ocs-ci#350]
The current implementation of `run_cmd()` uses `subprocess.run()` instead of `subprocess.Popen`. As a result, it has to wait for the command to finish executing in order to log any output.

For short-running commands, this is hardly noticeable; for longer ones like `openshift-install`, it's problematic. We should write the output of the command to stdout/stderr as normal, while buffering internally.

**Comment by zmc** [comment]
An example that also shows how the logging ends up out-of-order:
```
$ cat cmd_test.sh
#!/bin/bash

out () {
  echo "stdout"
  echo "stderr" >&2
}

out
sleep 1
out sleep 2
out
sleep 1
out
```

```
$ ./cmd_test.sh
stdout
stderr
stdout
stderr
stdout
stderr
stdout
stderr
```

```
$ python cmd_test.py
INFO:ocs_ci.utility.utils:Executing command: ./cmd_test.sh
DEBUG:ocs_ci.utility.utils:Command output: stdout
stdout
stdout
stdout

WARNING:ocs_ci.utility.utils:Command warning:: stderr
stderr
stderr
stderr
```

**Comment by gklein** [comment]
It seems we have a [run_async() method](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L778) that can be used for the similar case [as described](https://github.com/red-hat-storage/ocs-ci/issues/350#issue-463936265).

Does it answers this request ? Can we close the issue?

**Comment by clacroix12** [comment]
I don't think `run_async` solves this issue. Unless I'm missing something, executing `run_async` doesn't wait for the command to finish, but it seems that `run_async.async_communicate()` still does. What we want to get out of this is the live output from long running commands in real time without having to wait for the process to end in order to log it.

**Comment by gklein** [comment]
> I don't think `run_async` solves this issue. Unless I'm missing something, executing `run_async` doesn't wait for the command to finish, but it seems that `run_async.async_communicate()`(which is how we get the return code, stdout, and stderr of the cmd) still does. What we want to get out of this is the live output from long running commands in real time without having to wait for the process to end in order to log it.

Yes, you are right.  run_async()  does not solve the live output requirement, which might be handy for real time debugging especially for long running tests and the OCP/OCS deployment phase.

Here is a possible implementation for live output which captures both stdout  and stderr.

https://github.com/red-hat-storage/ocs-ci/pull/1096/
