### ISSUE TITLE
CephHealthException - HEALTH_WARN Degraded

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#3522]
Log location: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15539/testReport/junit/tests.e2e.scale.test_scale_osds_fill_75__reboot_workers/TestScaleOSDsRebootNodes/test_scale_osds_reboot_nodes_CephBlockPool_/

**Error Message**
ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN Degraded data redundancy: 3639/145008 objects degraded (2.510%), 23 pgs degraded, 25 pgs undersized

**Stacktrace**
self = <test_scale_osds_fill_75%_reboot_workers.TestScaleOSDsRebootNodes object at 0x7fb54fbce3c8>
interface = 'CephBlockPool'
project_factory = <function project_factory_fixture.<locals>.factory at 0x7fb47e6f16a8>
multi_pvc_factory = <function multi_pvc_factory_fixture.<locals>.factory at 0x7fb625ab6d08>
dc_pod_factory = <function dc_pod_factory.<locals>.factory at 0x7fb625ab6400>

    def test_scale_osds_reboot_nodes(
        self, interface, project_factory, multi_pvc_factory, dc_pod_factory
    ):
        """
        Check storage utilization, if its less then runs IO,
        Scale osds from 3-6, check for rebalance and reboot workers
        """
        current_osd_count = count_cluster_osd()
        proj_obj = project_factory()
        if current_osd_count == 3:
            while not validate_osd_utilization(osd_used=10):
                # Create pvc
                pvc_objs = multi_pvc_factory(
                    project=proj_obj,
                    interface=interface,
                    size=self.pvc_size,
                    num_of_pvc=self.num_of_pvcs,
                )
    
                dc_pod_objs = list()
                for pvc_obj in pvc_objs:
                    dc_pod_objs.append(dc_pod_factory(pvc=pvc_obj))
    
                wait_for_dc_app_pods_to_reach_running_state(dc_pod_objs, timeout=1200)
    
                for pod_obj in dc_pod_objs:
                    pod_obj.run_io(
                        storage_type="fs",
                        size="3G",
                        runtime="60",
                        fio_filename=f"{pod_obj.name}_io",
                    )
    
        # Add capacity
        osd_size = storage_cluster.get_osd_size()
        count = storage_cluster.add_capacity(osd_size)
        pod = OCP(kind=constants.POD, namespace=config.ENV_DATA["cluster_namespace"])
        pod.wait_for_resource(
            timeout=300,
            condition=constants.STATUS_RUNNING,
            selector="app=rook-ceph-osd",
            resource_count=count * 3,
        )
        assert ceph_health_check(
            delay=120, tries=50
        ), "New OSDs failed to reach running state"
    
        cluster = CephCluster()
    
        # Get rebalance status
        rebalance_status = cluster.get_rebalance_status()
        logger.info(rebalance_status)
        if rebalance_status:
            time_taken = cluster.time_taken_to_complete_rebalance()
            logger.info(f"The time taken to complete rebalance {time_taken}")
    
        # Rolling reboot on worker nodes
        worker_nodes = get_nodes(node_type="worker")
    
        factory = platform_nodes.PlatformNodesFactory()
        nodes = factory.get_nodes_platform()
    
        for node in worker_nodes:
            nodes.restart_nodes(nodes=[node])
            wait_for_nodes_status()
    
>       assert ceph_health_check(
            delay=180
        ), "Failed, Ceph health bad after nodes reboot"

tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py:120: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/utility/utils.py:1581: in ceph_health_check
    )(ceph_health_check_base)(namespace)
ocs_ci/utility/retry.py:31: in f_retry
    return f(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

namespace = 'openshift-storage'

    def ceph_health_check_base(namespace=None):
        """
        Exec `ceph health` cmd on tools pod to determine health of cluster.
    
        Args:
            namespace (str): Namespace of OCS
                (default: config.ENV_DATA['cluster_namespace'])
    
        Raises:
            CephHealthException: If the ceph health returned is not HEALTH_OK
            CommandFailed: If the command to retrieve the tools pod name or the
                command to get ceph health returns a non-zero exit code
        Returns:
            boolean: True if HEALTH_OK
    
        """
        namespace = namespace or config.ENV_DATA["cluster_namespace"]
        run_cmd(
            f"oc wait --for condition=ready pod "
            f"-l app=rook-ceph-tools "
            f"-n {namespace} "
            f"--timeout=120s"
        )
        tools_pod = run_cmd(
            f"oc -n {namespace} get pod -l 'app=rook-ceph-tools' "
            f"-o jsonpath='{{.items[0].metadata.name}}'",
            timeout=60,
        )
        health = run_cmd(f"oc -n {namespace} exec {tools_pod} -- ceph health")
        if health.strip() == "HEALTH_OK":
            log.info("Ceph cluster health is HEALTH_OK.")
            return True
        else:
>           raise CephHealthException(f"Ceph cluster health is not OK. Health: {health}")
E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN Degraded data redundancy: 3639/145008 objects degraded (2.510%), 23 pgs degraded, 25 pgs undersized

ocs_ci/utility/utils.py:1617: CephHealthException

**Comment by ramkiperiy** [comment]
@tiffanyn108 Do we still see this issue ? can this be closed if not observed in recent executions ?

**Comment by tiffanyn108** [comment]
@ramkiperiy Not seen this issue recently on scale execution.  Close this PR.
