### ISSUE TITLE
IBM Scale: get_memory_leak_median_value() raise UnexpectedBehaviour failure

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#3523]
Failure log: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15539/testReport/junit/tests.e2e.scale.test_pv_scale_and_respin_ceph_pods/

**Error Message**
ocs_ci.ocs.exceptions.UnexpectedBehaviour

**Stacktrace**
self = <test_pv_scale_and_respin_ceph_pods.TestPVSTOcsCreatePVCsAndRespinCephPods object at 0x7fb554ff1ac8>
namespace = None, storageclass = None, setup_fixture = None
resource_to_delete = 'mgr', memory_leak_function = None

    def test_pv_scale_out_create_pvcs_and_respin_ceph_pods(
        self,
        namespace,
        storageclass,
        setup_fixture,
        resource_to_delete,
        memory_leak_function,
    ):
        pvc_count_each_itr = 10
        scale_pod_count = 120
        size = "10Gi"
        test_run_time = 180
        self.all_pvc_obj, self.all_pod_obj = ([] for i in range(2))
    
        # Identify median memory value for each worker node
>       median_dict = helpers.get_memory_leak_median_value()

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py:181: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def get_memory_leak_median_value():
        """
        Function to calculate memory leak Median value by collecting the data for 180 sec
        and find the median value which will be considered as starting point
        to evaluate memory leak using "RES" value of ceph-osd daemon i.e. list[7] in code
    
        Returns:
            median_dict (dict): dict of worker nodes and respective median value
        """
        median_dict = {}
        timeout = 180  # wait for 180 sec to evaluate  memory leak median data.
        logger.info(f"waiting for {timeout} sec to evaluate the median value")
        time.sleep(timeout)
        for worker in node.get_worker_nodes():
            memory_leak_data = []
            if os.path.exists(f"/tmp/{worker}-top-output.txt"):
                with open(f"/tmp/{worker}-top-output.txt", "r") as f:
                    data = f.readline()
                    list = data.split(" ")
                    list = [i for i in list if i]
                    memory_leak_data.append(list[7])
            else:
                logging.info(f"worker {worker} memory leak file not found")
>               raise UnexpectedBehaviour
E               ocs_ci.ocs.exceptions.UnexpectedBehaviour

ocs_ci/helpers/helpers.py:2163: UnexpectedBehaviour
Standard Output
tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py::TestPodAreNotOomkilledWhileRunningIO::test_pods_are_not_oomkilled_while_running_ios[CephFileSystem] #x1B[31mERROR#x1B[0m#x1B[31m [ 37%]#x1B[0m
tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py::TestPVSTOcsCreatePVCsAndRespinCephPods::test_pv_scale_out_create_pvcs_and_respin_ceph_pods[mgr] #x1B[31mFAILED#x1B[0m#x1B[31m                                                                   [ 40%]#x1B[0m
Standard Error
Exception in thread Thread-170:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/tests/conftest.py", line 1533, in run_memory_leak_in_bg
    str(oc.exec_oc_cmd(command=top_cmd, out_yaml_format=False))
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/ocp.py", line 144, in exec_oc_cmd
    **kwargs,
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 451, in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 506, in exec_cmd
    f"Error during execution of command: {masked_cmd}."
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage debug nodes/ip-10-0-219-22.us-east-2.compute.internal -- chroot /host top -n 2 b.
Error is Starting pod/ip-10-0-219-22us-east-2computeinternal-debug ...
To use host binaries, run `chroot /host`

Removing debug pod ...
error: unable to create the debug pod "ip-10-0-219-22us-east-2computeinternal-debug"

**Comment by ramkiperiy** [comment]
Observing this problem in IBM clusters consistently, should troubleshoot more to isolate the problem. 
P.S We are not observing this problem in AWS/Vmware platform executions.

**Comment by wusui** [comment]
I saw this issue in the 4.8 scale regression test on AWS.   It looks like
this may be timeout related.  Are we seeing that some operations are taking
more time to execute in the 4.8 versions?

I attached a copy of the stack trace of one of the runs

**Comment by ramkiperiy** [comment]
We are planning to add more enhancement to memory_leak function to support more than 3 OSD's. For now most of the failures are due to support only 3 OSDs in the cluster.
