### ISSUE TITLE
Add memory usage checks to small_file_workload scaling code.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3530]
The performance test_small_file_workload.py script can be modified to also run scale tests.  In order to detect potential memory leaks in ceph storage code, the following shell script was performed:

for i in `seq 1 30`; do
    run-ci -m scale --cluster-name lr4-wusui-awsfive --cluster-path /home/wusui/ocs-ci tests/e2e/scale/test_small_file_workload.py;
    sleep 10;
    ~/collect_data/collector.sh $i;
done

collector.sh ran ps and saved that output locally.  collector.sh's contents are:

echo $1
for i in `oc -n openshift-storage get pods | sed 's/ .*//'`; do
echo "xxx " $i " xxx";
oc -n openshift-storage rsh $i ps aux;
done 2>&1 | tee ~/collect_data/testAfter$1

After that, a python script was run to collect the data.

This all needs to be implemented in a manner that can be run from run-ci.  The last test should be one where the test fails if the memory usage for any ceph pod grows at a rate beyond a certain threshold.

**Comment by ramkiperiy** [comment]
PR is already merged https://github.com/red-hat-storage/ocs-ci/pull/3707, closing this issue
