### ISSUE TITLE
Update drain and OCP upgrade scenarios to check for PDB states

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#3557]
PDB for OSDs have undergone design change in ocs 4.7 and it would be helpful to add automation around it. So that we can check the state and functionality in the cases which affect OSD PDBs.

Reference email - PDB re-design for OSDs from OCS 4.7(to be backported to 4.6.z as well)

Instead of one PDB per OSD, normally the cluster would have 1 PDB for all OSDs... if a drain is detected, then rook deletes the single PDB and 2 blocking PDBs get created in the other 2 zones.  More details added in above referenced email.

**Comment by Shrivaibavi** [comment]
We have few PRs merged to check OSD PDBs, drain and OCP upgrades, Hence this issue is safe to be closed.
https://github.com/red-hat-storage/ocs-ci/pull/3888
