### ISSUE TITLE
Need option to either enable or disable "Collecting Cluster versions" during test run

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#356]
As a user, it would be good to have an option in run-ci to enable/disable the "Collecting Cluster versions" while running any test case. 

Also, it would be helpful if we could use "Collecting Cluster versions" independent of any test case in run-ci, so that we can collect version information of our running cluster at any required time (e.g before raising a bug)

Thanks

**Comment by nehaberry** [comment]
@vavuthu please suggest

**Comment by mbukatov** [comment]
I plan to rewrite this code anyway, as part of https://github.com/red-hat-storage/ocs-ci/pull/185 (which we agreed in https://github.com/red-hat-storage/ocs-ci/pull/298#discussion_r298140306).

**Comment by mbukatov** [comment]
@nehaberry I will take your suggestion into account in #185

>  it would be good to have an option in run-ci to enable/disable the "Collecting Cluster versions"

I believe that this won't be necessary when softer approach is used (without direct interaction with ceph, rook or other storage components).

> Also, it would be helpful if we could use "Collecting Cluster versions" independent of any test case in run-ci, so that we can collect version information of our running cluster at any required time (e.g before raising a bug)

In #185, I suggested to create a plain text file with version report, which could be copy pasted into bugzilla. That said, I will also think about a way to report versions without running any test.
