### ISSUE TITLE
A secondary solution to download OCP installer/client when release-artifacts is down

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#3574]
At times, we experience downtime from https://openshift-release-artifacts.svc.ci.openshift.org.
That is something that interrupts the executions and forces us to have a local binary, as well as using in `run-ci`:
```
force_download_installer: False
force_download_client: False
```
We should look for a way for a cleaner approach, without forcing ourselves to pass additional config, in addition, when we experience downtime from release artifacts, deployment from Jenkins becomes unusable.

Some solutions we thought until now from offline discussions with @shyRozen and @ebenahar :

1) An internal HTTP server that will have both installer&client where we could easily download, when we see that release-artifacts website is down, we could have the server using cronjobs, to being updated with the latest installer&client binaries and pull them when it is possible.
With this approach, we need to maintain an HTTP server with those binaries accessible from some URL.

2) We could have them in ocs-ci, and update them with the latest binary once a while. (Will require to check if it is legal to have a copy of it in our repo)

3) We could create a container image with the tarballs in it, they could be downloaded to the Jenkins agent once we identify that release-artifacts is down, we could execute those containers temporarily on the Jenkins agent, and execute a sort of `docker cp` command from **the host**, and stop the containers.
With this approach, we will need to maintain an image on quay.io

How do you think we should continue with this problem?

**Comment by shyRozen** [comment]
Although option 3 has many steps (copy, create the image, upload to quay and reverse) and looks like implementation is more complex - we don't need to maintain our own server.
I think option 1 we'll have legal problems as it is exposed to public.

**Comment by prsurve** [comment]
I can suggest 1 more solution and it works

1. get the ocp version tag
2. Download the binary using this cmd 
    a. `oc adm release extract --tools registry.svc.ci.openshift.org/ocp/release:<image-tag> -a <pull-secret>` 
3. Extract the binary and we are good to go with the installation
