### ISSUE TITLE
test_fio_benchmark fails on creation internal ElasticSearch server

### ISSUE THREAD

**Issue by ypersky1980** [red-hat-storage/ocs-ci#3575]
The ValidatingWebhookConfiguration "elastic-webhook.k8s.elastic.co" is invalid: 
* webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun

The error messages: 

* webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[1].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[1].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[2].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[2].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[3].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[3].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[4].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[4].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[5].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[5].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[6].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[6].admissionReviewVersions: Required value: must specify one of v1, v1beta1
* webhooks[7].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[7].admissionReviewVersions: Required value: must specify one of v1, v1beta1

The relevant logs are found in the /tmp in qpas server ( 10.70.39.233 ) 
log names: 
-rw-rw-r--. 1 ypersky ypersky  337734 Dec 20 15:49 log_test_fio_bench_including_compression_azure1
-rw-rw-r--. 1 ypersky ypersky  316473 Dec 20 19:00 log_test_fio_bench_including_compression_azure11
-rw-rw-r--. 1 ypersky ypersky   41356 Dec 21 03:29 log_test_fio_bencchmark_compress_random_1024_60_azure1
-rw-rw-r--. 1 ypersky ypersky   41369 Dec 21 16:13 log_test_fio_bencchmark_compress_random_64_60_azure1

**Comment by wusui** [comment]
This may be the same issue that is seen in 3580
