### ISSUE TITLE
Unit tests are failing on master

### ISSUE THREAD

**Issue by zmc** [red-hat-storage/ocs-ci#3578]
See https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci/155/execution/node/40/log/

For some reason, unit tests are trying to access the network (login.microsoftonline.com specifically).

Are unit tests not gating PRs anymore? Why not?

**Comment by zmc** [comment]
The offending test is here: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/tests/test_azure_utils.py#L49-L63

**Comment by vasukulkarni** [comment]
@mbukatov can you look into this one?

**Comment by mbukatov** [comment]
This test case actually sends (invalid) requests to azure api. It can be skipped when we don't want to communicate with outside world.
