### ISSUE TITLE
Optional parameter for PAUSE BEFORE TEXT EXECUTION for our production jobs

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#3584]
As part of the new IBM production jobs we execute lately, I was asked if we could split the deploy&test execution. (For applying a ConfigMap when deploy finishes, and before we test tier1)

I am not sure if this is something we will need consistently, but it could help for this request to create a parameter as same as PAUSE_BEFORE_UPGRADE, just PAUSE_BEFORE_TEST_EXECUTION.

Although it is a unique case for this IBM execution, but we could use it for other means in the future I guess.

**Comment by dahorak** [comment]
Yes, I agree that it might be useful in other cases as well.

**Comment by petr-balogh** [comment]
It can be generally useful as Daniel stated, but I think that this is not related to ocs-ci repository but our ocs4-jobs repository as it will be implemented there so I would go and close this issue here and open it in our jobs repository or as a ticket in our board ;)
