### ISSUE TITLE
tests/e2e/performance/test_pvc_snapshot_performance.py test failes on timeout when writing IO to 100 GB PVC    ( both RBD and Ceph) 

### ISSUE THREAD

**Issue by ypersky1980** [red-hat-storage/ocs-ci#3598]
tests/e2e/performance/test_pvc_snapshot_performance.py test failes on timeout when writing IO to 100 GB PVC  ( both RBD and Ceph)  

The error in the log: 

17:44:31 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-rbd-fffe3d84be094271bc3c9989552
17:54:31 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found Exception: 
Traceback (most recent call last):
  File "/home/ypersky/ocs-ci/ocs_ci/ocs/resources/pod.py", line 129, in get_fio_results
    result = self.fio_thread.result(timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 441, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by keesturam** [comment]
This issue is not seen anymore. It was probably fixed already.
