### ISSUE TITLE
Missing License in project.

### ISSUE THREAD

**Issue by kshithijiyer** [red-hat-storage/ocs-ci#36]

**Comment by mbukatov** [comment]
Hm, this would not be easy to fix as the project is based on [cephci](https://github.com/red-hat-storage/cephci), which doesn't have a licence either.

**Comment by RazTamir** [comment]
So maybe we can just cut the relation to cephci and have it separately?
This option is now more reasonable as we are moving to pytest so I don't see any must connection between the 2 projects?

**Comment by kshithijiyer** [comment]
> So maybe we can just cut the relation to cephci and have it separately?
> This option is now more reasonable as we are moving to pytest so I don't see any must connection between the 2 projects?
If that so then which license should be applied to the project?

**Comment by vasukulkarni** [comment]
Fixed here: https://github.com/red-hat-storage/ocs-ci/pull/124
