### ISSUE TITLE
Deployment is broken because of https://github.com/red-hat-storage/ocs-ci/pull/230

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#360]

**Comment by clacroix12** [comment]
@RazTamir do you have a stacktrace or logs for this failure?

**Comment by Shrivaibavi** [comment]
@RazTamir The fix for this patch is sent and got it merged too. Please check this PR
https://github.com/red-hat-storage/ocs-ci/pull/359

**Comment by RazTamir** [comment]
Yes,

(.venv) [~/git/ocs-ci]$ run-ci -m deployment -vrA --no-print-logs --cluster-conf conf/ocs_basic_install.yml --cluster-name ratamir-ocs-new --log-level DEBUG --cluster-path /home/ratamir/ocs_autmation --capture=no tests/ --deploy
The kubeconfig file /home/ratamir/ocs_autmation/auth/kubeconfig doesn't exist!
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.11.0 -- /home/ratamir/git/ocs-ci/.venv/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.7.3', 'Platform': 'Linux-5.0.16-100.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight', 'Packages': {'pytest': '4.5.0', 'py': '1.8.0', 'pluggy': '0.11.0'}, 'Plugins': {'reportportal': '1.0.5', 'cov': '2.7.1', 'metadata': '1.8.0', 'logger': '0.5.0', 'html': '1.21.1'}}
rootdir: /home/ratamir/git/ocs-ci, inifile: pytest.ini
plugins: reportportal-1.0.5, cov-2.7.1, metadata-1.8.0, logger-0.5.0, html-1.21.1
collecting ... 
------------------------------------------------------------------------------------ live log collection ------------------------------------------------------------------------------------
18:10:54 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ratamir/ocs_autmation/auth/kubeconfig get CephCluster  -o yaml
collected 33 items / 1 errors / 32 deselected                                                                                                                                               

========================================================================================== ERRORS ===========================================================================================
_______________________________________________________________ ERROR collecting tests/manage/test_remove_mon_from_cluster.py _______________________________________________________________
tests/manage/test_remove_mon_from_cluster.py:26: in <module>
    HEALTH = CephCluster()
ocs_ci/ocs/cluster.py:60: in __init__
    self.cluster_resource_config = self.CEPHCLUSTER.get().get('items')[0]
ocs_ci/ocs/ocp.py:107: in get
    return self.exec_oc_cmd(command)
ocs_ci/ocs/ocp.py:69: in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd)
ocs_ci/utility/utils.py:381: in run_cmd
    f"Error during execution of command: {cmd}."
E   ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'openshift-storage', '--kubeconfig', '/home/ratamir/ocs_autmation/auth/kubeconfig', 'get', 'CephCluster', '-o', 'yaml'].
E   Error is error: stat /home/ratamir/ocs_autmation/auth/kubeconfig: no such file or directory
================================================================================== short test summary info ==================================================================================
FAILED tests/manage/test_remove_mon_from_cluster.py - ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'openshift-storage', '--kubeconfig', '/home/rat...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 32 deselected, 1 error in 0.42 seconds ===========================================================================

The issue is here https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/test_remove_mon_from_cluster.py#L26

Call to CephCluster() before you have one is breaking the deployment
