### ISSUE TITLE
tests/e2e/scale/test_pvc_creation_deletion_scale.py fails second time it is run.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3639]
On a fresh AWS deployment, the following command runs to completion:

run-ci -m scale --cluster-name lr2-wusui-scale --cluster-path /home/wusui/ocs-ci tests/e2e/scale/test_pvc_creation_deletion_scale.py

If you run the same program again, it fails with:

=================================== FAILURES ===================================
_ TestPVCCreationDeletionScale.test_multiple_pvc_creation_deletion_scale[ReadWriteMany-cephfs] _

self = <test_pvc_creation_deletion_scale.TestPVCCreationDeletionScale object at 0x7feb7579c3d0>
namespace = None
tmp_path = PosixPath('/tmp/pytest-of-wusui/pytest-17/test_multiple_pvc_creation_del2')
access_mode = 'ReadWriteMany', interface = 'cephfs'

    @pytest.mark.parametrize(
        argnames=["access_mode", "interface"],
        argvalues=[
            pytest.param(
                *[constants.ACCESS_MODE_RWO, constants.CEPHBLOCKPOOL],
                marks=pytest.mark.polarion_id("OCS-1225"),
            ),
            pytest.param(
                *[constants.ACCESS_MODE_RWX, constants.CEPHBLOCKPOOL],
                marks=pytest.mark.polarion_id("OCS-2010"),
            ),
            pytest.param(
                *[constants.ACCESS_MODE_RWX, constants.CEPHFS_INTERFACE],
                marks=pytest.mark.polarion_id("OCS-2008"),
            ),
        ],
    )
    @pytest.mark.usefixtures(namespace.__name__)
    def test_multiple_pvc_creation_deletion_scale(
        self, namespace, tmp_path, access_mode, interface
    ):
        """
        Measuring PVC creation time while scaling PVC
        Measure PVC deletion time after creation test
        """
        scale_pvc_count = 1500
        log.info(f"Start creating {access_mode}-{interface} {scale_pvc_count} PVC")
        if interface == constants.CEPHBLOCKPOOL:
            sc_name = constants.DEFAULT_STORAGECLASS_RBD
        elif interface == constants.CEPHFS_INTERFACE:
            sc_name = constants.DEFAULT_STORAGECLASS_CEPHFS
    
        # Get pvc_dict_list, append all the pvc.yaml dict to pvc_dict_list
        pvc_dict_list1 = scale_lib.construct_pvc_creation_yaml_bulk_for_kube_job(
            no_of_pvc=int(scale_pvc_count / 2), access_mode=access_mode, sc_name=sc_name
        )
        pvc_dict_list2 = scale_lib.construct_pvc_creation_yaml_bulk_for_kube_job(
            no_of_pvc=int(scale_pvc_count / 2), access_mode=access_mode, sc_name=sc_name
        )
    
        # There is 2 kube_job to reduce the load, observed time_out problems
        # during delete process of single kube_job and heavy load.
        job_file1 = ObjectConfFile(
            name="job_profile_1",
            obj_dict_list=pvc_dict_list1,
            project=self.namespace,
            tmp_path=tmp_path,
        )
        job_file2 = ObjectConfFile(
            name="job_profile_2",
            obj_dict_list=pvc_dict_list2,
            project=self.namespace,
            tmp_path=tmp_path,
        )
    
        # Create kube_job
        job_file1.create(namespace=self.namespace)
        job_file2.create(namespace=self.namespace)
    
        # Check all the PVC reached Bound state
        pvc_bound_list = scale_lib.check_all_pvc_reached_bound_state_in_kube_job(
            kube_job_obj=job_file1,
            namespace=self.namespace,
            no_of_pvc=int(scale_pvc_count / 2),
        )
        pvc_bound_list.extend(
            scale_lib.check_all_pvc_reached_bound_state_in_kube_job(
                kube_job_obj=job_file2,
                namespace=self.namespace,
                no_of_pvc=int(scale_pvc_count / 2),
            )
        )
    
        logging.info(f"Number of PVCs in Bound state {len(pvc_bound_list)}")
    
        # Get PVC creation time
>       pvc_create_time = helpers.measure_pvc_creation_time_bulk(
            interface=interface,
            pvc_name_list=pvc_bound_list,
            wait_time=300,
        )

tests/e2e/scale/test_pvc_creation_deletion_scale.py:109: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

interface = 'cephfs'
pvc_name_list = ['pvc-test-a659a912a30a46caad419ff2d7c76bb', 'pvc-test-ba4de40a68884ebdaef810c23c1d260', 'pvc-test-f7eb9781da9947d5825...5ad0749d48e44b7e3fcbf7a5', 'pvc-test-0ab98cbff61a4d35a43ad6723c39088', 'pvc-test-96214c97ffa647b68664ff5fa93850e', ...]
wait_time = 300

    def measure_pvc_creation_time_bulk(interface, pvc_name_list, wait_time=60):
        """
        Measure PVC creation time of bulk PVC based on logs.
    
        Args:
            interface (str): The interface backed the PVC
            pvc_name_list (list): List of PVC Names for measuring creation time
            wait_time (int): Seconds to wait before collecting CSI log
    
        Returns:
            pvc_dict (dict): Dictionary of pvc_name with creation time.
    
        """
        # Get the correct provisioner pod based on the interface
        pod_name = pod.get_csi_provisioner_pod(interface)
        # due to some delay in CSI log generation added wait
        time.sleep(wait_time)
        # get the logs from the csi-provisioner containers
        logs = pod.get_pod_logs(pod_name[0], "csi-provisioner")
        logs += pod.get_pod_logs(pod_name[1], "csi-provisioner")
        logs = logs.split("\n")
    
        loop_counter = 0
        while True:
            no_data_list = list()
            for name in pvc_name_list:
                # check if PV data present in CSI logs
                start = [i for i in logs if re.search(f"provision.*{name}.*started", i)]
                end = [i for i in logs if re.search(f"provision.*{name}.*succeeded", i)]
                if not start or not end:
                    no_data_list.append(name)
    
            if no_data_list:
                # Clear and get CSI logs after 60secs
                logging.info(f"PVC count without CSI create log data {len(no_data_list)}")
                logs.clear()
                time.sleep(wait_time)
                logs = pod.get_pod_logs(pod_name[0], "csi-provisioner")
                logs += pod.get_pod_logs(pod_name[1], "csi-provisioner")
                logs = logs.split("\n")
                loop_counter += 1
                if loop_counter >= 3:
                    logging.info("Waited for more than 3mins still no data")
>                   raise UnexpectedBehaviour(
                        f"There is no pvc creation data in CSI logs for {no_data_list}"
                    )
E                   ocs_ci.ocs.exceptions.UnexpectedBehaviour: There is no pvc creation data in CSI logs for ['pvc-test-a659a912a30a46caad419ff2d7c76bb', and 1499 more pvc-test-* listed

ocs_ci/helpers/helpers.py:1387: UnexpectedBehaviour
--------------------------- Captured stdout teardown ---------------------------
FAILED                                                                   [ 75%]
================== 1 failed, 3 passed in 11386.32s (3:09:46) ===================

This problem will not be seen on single tests that destroy the cluster on completion.

A copy of the console output, and a must-gather tarfile has been collected in 10.70.39.233:/teamshare/jan8

**Comment by ramkiperiy** [comment]
PR https://github.com/red-hat-storage/ocs-ci/pull/3070 is merged which solved lot of issues wrt PVC creation/deletion scale.
