### ISSUE TITLE
Create a function for full flow pod creation

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#364]
The function should take care of all dependencies for pod creation: secret, interface (blockpool, filesyste), storageclass, pvc.

This flow is very basic and should save a lot of lines of code

**Comment by gklein** [comment]
It seems that the Pod class now supports many of the functions required by many tests:
https://github.com/red-hat-storage/ocs-ci/blob/9debf031e4916dd05b499b0e72faee3c0a252cd8/ocs_ci/ocs/resources/pod.py#L44

 Is there any more work required here or can we close this issue?

**Comment by vasukulkarni** [comment]
I think we have the fixture, closing for now, feel free to reopen.
