### ISSUE TITLE
tests/e2e/performance/test_small_file_workload.py timeouts -- smallfile-client pod never started.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3645]
tests/e2e/performance/test_small_file_workload.py fails with:

        # wait for benchmark pods to get created - takes a while
        import pdb; pdb.set_trace()
>       for bench_pod in TimeoutSampler(
            240,
            10,
            get_pod_name_by_pattern,
            "smallfile-client",
            constants.RIPSAW_NAMESPACE,
        ):

tests/e2e/performance/test_small_file_workload.py:443: 

i ran oc -n my-ripsaw get pods on another window while this was running and it appears that smallfile-client never starts

This is blocking a scale testing issue because I am trying to adapt a scale test to use this code as well.

**Comment by Avilir** [comment]
i hit the same issue with the FIO test.
some changes have been made in the ripsaw CRD file.
i will update the CRD for Smallfiles and FIO.
