### ISSUE TITLE
create a new namespace (and switch to it) per test as part of class fixture - top level

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#365]
We should create a new namespace for each new test and switch to it so all new resources will be created in it.
The teardown should take care of retrieving to the original state

**Comment by jilju** [comment]
Fixture for creating new project is present in PR #368

**Comment by mbukatov** [comment]
> Fixture for creating new project is present in PR #368

I don't like the approach used there, when you inject namespace into test class. This is error prone hack, please don't do that.

It would be much better to have a simple namespace fixture which just creates a namespace during setup, and removes it during teardown,  like in my old branch here:  https://github.com/mbukatov/ocs-ci/blob/608266ba4de38e028aa579fa5c442d8548e7c314/tests/test_ocp_pv_resize.py#L45 (example here is parametrized, which we may or may not use, and also we may want to set namespace prefix based on some default values from config or defaults module).

**Comment by vasukulkarni** [comment]
This requires agreement from every test owner, @mbukatov can you send an email to ocs-qe to get agreement/disagreement on this one?
