### ISSUE TITLE
RHEL worker deployemtn failures

### ISSUE THREAD

**Issue by shylesh** [red-hat-storage/ocs-ci#3684]
==================================================================
TASK [openshift_node : Wait for node to report ready] **************************
FAILED - RETRYING: Wait for node to report ready (36 retries left).
FAILED - RETRYING: Wait for node to report ready (35 retries left).
FAILED - RETRYING: Wait for node to report ready (34 retries left).
FAILED - RETRYING: Wait for node to report ready (33 retries left).
FAILED - RETRYING: Wait for node to report ready (32 retries left).
FAILED - RETRYING: Wait for node to report ready (31 retries left).
FAILED - RETRYING: Wait for node to report ready (30 retries left).
FAILED - RETRYING: Wait for node to report ready (29 retries left).
FAILED - RETRYING: Wait for node to report ready (28 retries left).
FAILED - RETRYING: Wait for node to report ready (27 retries left).
FAILED - RETRYING: Wait for node to report ready (26 retries left).
ok: [x.x.x.x] => {"attempts": 12, "changed": false, "cmd": ["oc", "get", "node", "j004vu1rs33-um-2bs55-rhel-0", "--kubeconfig=/tmp/kubeconfig", "--output=jsonpath={.status.conditions[?(@.type==\"Ready\")].status}"], "delta": "0:00:00.186223", "end": "2021-01-13 16:39:45.206513", "rc": 0, "start": "2021-01-13 16:39:45.020290", "stderr": "", "stderr_lines": [], "stdout": "True", "stdout_lines": ["True"]}

TASK [openshift_node : fail] ***************************************************
fatal: [x.x.x..236]: FAILED! => {"changed": false, "msg": "Ignition apply failed"}
fatal: [x.x.x..240]: FAILED! => {"changed": false, "msg": "Ignition apply failed"}

PLAY RECAP *********************************************************************
x.x.x.208               : ok=39   changed=30   unreachable=0    failed=0    skipped=8    rescued=0    ignored=0   
x.x.x..236               : ok=36   changed=28   unreachable=0    failed=1    skipped=8    rescued=1    ignored=0   
x.x.x.240               : ok=36   changed=28   unreachable=0    failed=1    skipped=8    rescued=1    ignored=0   
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
====================================================================
Reference: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16319/

**Comment by shylesh** [comment]
Could be a temporary node issue

**Comment by petr-balogh** [comment]
@vavuthu can you please take a look as this issue is seen consistently? Thanks

**Comment by vavuthu** [comment]
from the logs, it looks  like 2 nodes are not up after reboot. 

triggered another job to check its temp issue or not and deployment is successfull 
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16464/console

I will keep this issue open to identify the re-ocuurences
