### ISSUE TITLE
fio setup fails on fedora pod

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#370]
fio setup fails on fedora pod with error message mentioned below. It appears that setting up of fio is failing when it tries to do "yum install fio" on fedora pod. This command requires root access which is not available on fedora pod.

tests/manage/test_expand_cluster_by_adding_backend_vol.py:427: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/manage/test_expand_cluster_by_adding_backend_vol.py:125: in run_fio_from_pods
    fpod.run_io('block', '256M', 'rw', 50, 1, 600)
ocs_ci/ocs/resources/pod.py:216: in run_io
    assert wl.setup(), "Setup up for FIO failed"
ocs_ci/ocs/workload.py:67: in setup
    return self.work_load_mod.setup(**setup_conf)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by clacroix12** [comment]
@hnallurv what branch are you seeing this on? That test file is not in latest master.

**Comment by hnallurv** [comment]
@Coady LaCroix <clacroix@redhat.com> my script is still under
development(local copy). not merged yet.

**Comment by clacroix12** [comment]
We should probably reserve creating issues for things that are affecting public branches since we can't troubleshoot this issue fully without the code changes. If you're looking for assistance with this issue you may want to push a WIP PR.

**Comment by vasukulkarni** [comment]
@hnallurv please set the priority for this one once you speak to PM

**Comment by hnallurv** [comment]
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: fedorapod
spec:
  template:
    metadata:
      labels:
        name: fedorapod
    spec:
      restartPolicy: Always
      volumes:
      - name: fedora-vol
        persistentVolumeClaim:
          claimName: pvcClaimFedora
      containers:
      - name: fedora
        image: fedora
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt
          name: fedora-vol
        livenessProbe:
          exec:
            command:
            - 'sh'
            - '-ec'
            - 'df /mnt'
          initialDelaySeconds: 3
          periodSeconds: 3
  replicas: 1
  triggers:
    - type: ConfigChange
  paused: false
~

**Comment by hnallurv** [comment]
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: fedorapod
spec:
  template:
    metadata:
      labels:
        name: fedorapod
    spec:
      restartPolicy: Always
      volumes:
      - name: fedora-vol
        persistentVolumeClaim:
          claimName: pvcClaimFedora
      containers:
      - name: fedora
        image: fedora
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt
          name: fedora-vol
        livenessProbe:
          exec:
            command:
            - 'sh'
            - '-ec'
            - 'df /mnt'
          initialDelaySeconds: 3
          periodSeconds: 3
  replicas: 1
  triggers:
    - type: ConfigChange
  paused: false
~

**Comment by hnallurv** [comment]
http://pastebin.test.redhat.com/781016

**Comment by prsurve** [comment]
if we create privileged pod then we are able to setup fio on fedora pod
