### ISSUE TITLE
Elastic search exception on tests/e2e/performance/test_small_file_workload.py

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3705]
I am getting the following on tests/e2e/[performance/test_small_file_workload.py

E           elasticsearch.exceptions.ConnectionError: ConnectionError((<urllib3.connection.HTTPConnection object at 0x7f2d945182e0>, 'Connection to 172.30.161.247 timed out. (connect timeout=10)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7f2d945182e0>, 'Connection to 172.30.161.247 timed out. (connect timeout=10)'))

../venv/lib64/python3.8/site-packages/elasticsearch/connection/http_urllib3.py:245: ConnectionError
---------------------------- Captured stderr setup -----------------------------
Cloning into 'benchmark-operator'...
----------------------------- Captured stdout call ----------------------------

The reason why I am concerned about this is because I am trying not to duplicate code for a new scale test by moving some of the code here to an ocs_ci/ocs file and calling it from both here and from the new scale test.  However, I do not want to make this change to performance/test_small_file_workload.py and confuse this issue which occurred before the change.

**Comment by ramkiperiy** [comment]
@Avilir do we need to fix anything here for performance ? Please close the issue it we already addressed this problem

**Comment by wusui** [comment]
I think that this issue has been fixed by changes for  #4173.  I am closing this as resolved.
