### ISSUE TITLE
Move PV existence validation to PVC class

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#372]
We should validate that the PV was deleted as part of PVC.delete()
The implementation should be taken from tests.manage.test_pv_creation.verify_pv_exist and moved to ocs_ci.ocs.resources.pvc.PVC

**Comment by keesturam** [comment]
Just to be explicit,
PV should be released if reclaim policy is 'retain' and PV + underlying ceph volume should be deleted if retain policy is 'delete'.

**Comment by vasukulkarni** [comment]
Closing stale issue.
