### ISSUE TITLE
SanityExternalCluster does not have an attribute obj_objs

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#3752]
This error is being appeared in external cluster deployment in Test Deployment:
An example for a deployment we faced this: [link](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16653/consoleFull)
```
E       AttributeError: 'SanityExternalCluster' object has no attribute 'obc_objs'
ocs_ci/helpers/sanity_helpers.py:97: AttributeError
```

**Comment by petr-balogh** [comment]
This is the dup of this issue: https://github.com/red-hat-storage/ocs-ci/issues/3746 , so closing this one.
