### ISSUE TITLE
Installation fails on Fedora 33

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#3768]
I tried to reinstall ocs-ci on my Fedora 33 virtual machine executing `pip install -r requirements.tx` in new virtualenv, and it fails spicy build:

```
error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/tmp/pip-build-env-cynnq9m5/overlay/lib64/python3.9/site-packages/numpy/core/include -c -c scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f -o build/temp.linux-x86_64-3.9/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.o" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
```

To fix this:

- update docs with full requirements (I tried to install `dnf builddep python3-scipy` but it didn't help)
- make sure ocs-ci is usable on Fedora

**Comment by Avilir** [comment]
you need to run:
pip install --upgrade setuptools

**Comment by vasukulkarni** [comment]
I am on fedora32, not seeing any failures on F32. The package I have is
python3-scipy.x86_64                                                       1.4.1-1.fc32

**Comment by petr-balogh** [comment]
Hey @mbukatov it looks similar to https://github.com/red-hat-storage/ocs-ci/issues/3698 I've opened. I started to see issue with scipy on python 3.9 which I have installed on my laptop. 

What version of python do you have Martin?

I opened this PR https://github.com/red-hat-storage/ocs-ci/pull/3699 but then I saw it broke support for python 3.6 which is still used on jenkins agents. We are going to drop support for 3.6 soon, I am going to bring that out tomorrow in automation meeting.

Try to workaround creation of venv for now by changing those values in setup.py and let me know if it helped or not.

@dahorak please have you tried to change the version of python to 3.8 on the jenkins agents?

**Comment by mbukatov** [comment]
> Hey @mbukatov it looks similar to #3698 I've opened. I started to see issue with scipy on python 3.9 which I have installed on my laptop.

Right, this looks similar.
 
> What version of python do you have Martin?

python3-3.9.1-1.fc33.x86_64
 
> I opened this PR #3699 but then I saw it broke support for python 3.6 which is still used on jenkins agents. We are going to drop support for 3.6 soon, I am going to bring that out tomorrow in automation meeting.

ack

The problem is that the suggested installation procedure basically tries to compile scipy from source independently from what you may have installed, but this itself requires you to install lot of compilers and devel libraries (eg. fortran compiler). So that in the end, it's not independent from your system, and it makes you to compile and install lot of stuff you have already packaged in fedora or rhel.

> Try to workaround creation of venv for now by changing those values in setup.py and let me know if it helped or not.

I can confirm that the workaround works.

**Comment by petr-balogh** [comment]
@dahorak never mind, I created MR for jenkins repository here: https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/526 and now running verification.
