### ISSUE TITLE
Implement elastic-search from OCP catalog for performance ripsaw / benchmark-operator testing

### ISSUE THREAD

**Issue by lukebrowning** [red-hat-storage/ocs-ci#3770]
Elastic search for ripsaw is currently implemented as an operator from docker.elastic.co/eck/eck-operator, but this operator is only supported on x86.   We need a common solution that works across all OCP platforms, including IBM Power and Z.  OCP logging utilizes elastic search (ES) and is multi-arch, so the underlying ES images could be re-used for the benchmark operator.

**Comment by lukebrowning** [comment]
@Avilir @zmc FYI, can you help get this assigned and prioritized.

**Comment by Avilir** [comment]
from the ElastiSearch installation page on the OCP operators Hub:

The Elasticsearch Operator for OCP provides a means for configuring and managing an Elasticsearch cluster for use in tracing and cluster logging as well as a Kibana instance to connect to it. This operator only supports OCP Cluster Logging and Jaeger. It is tightly coupled to each and is not currently capable of being used as a general purpose manager of Elasticsearch clusters running on OCP.

so, we can not use this operator, and need to find a different way.

**Comment by lukebrowning** [comment]
I wasn't suggesting that we use the elastic search operator in the OCP Catalog.   Rather, I was suggesting that we use the underlying elastic search power image and specify a config yaml which would be provided by ocs-ci.   I am assuming that the elastic search capabilities used by ocs-ci / ripsaw are basic.   Perhaps, we could decompose the eck-operator to determine which settings are applied by default.

**Comment by lukebrowning** [comment]
@Avilir ^^

**Comment by lukebrowning** [comment]
The best option would be for us to host the eck-operator at quay.io/multi-arch

**Comment by yselkowitz** [comment]
Easy for you to say, I'm the one that would be expected to build it. :-)

Is there really no way of using OCP's Elasticsearch for this?
