### ISSUE TITLE
Remove creation of Cephblockpool for Cephfs Storageclass creation in test_verify_all_fields_in_sc_yaml_with_oc_describe_sc

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#3778]
In https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/storageclass/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py, when the test is run for cephfs storageclass, a new cephblockpool is also created, which is not required for the storageclass. 

Since cephfs storageclass does not require a cephblockpool, having this as part of the test case might cause it to fail, if there was an issue creating the cephblockpool (which is not relevant to the test) as seen in the test run below:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16777/testReport/tests.manage.storageclass.test_verify_all_fields_in_sc_yaml_with_oc_describe_sc/TestVerifyAllFieldsInScYamlWithOcDescribe/test_verify_all_fields_in_sc_yaml_with_oc_describe_CEPHFS_/

**Comment by ebenahar** [comment]
@rachael-george I marked you as assignee. Please add this to your backlog
