### ISSUE TITLE
rgw_obj_fixture returns None when running on external-mode clusters

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#3784]
Because the cluster is external, the RGW deployment cannot be found - leading OCS-CI to think the deployment isn't there.
Thus, some tests are skipped for no reason.

We need to find a way to verify the existence of an RGW deployment even when running in external mode, or to replace the check.

**Comment by ebenahar** [comment]
@sidhant-agrawal @rachael-george how can we validate that RGW service is running on the RHCS cluster?

**Comment by rachael-george** [comment]
If the external mode OCS cluster is configured with RGW, it would have the RGW storageclass created. 
If we want to check on the RHCS cluster, we can try running `ceph status` and check for active rgw daemon. But there can be cases where RGW is running on the RHCS cluster but was not configured to be run on the OCS cluster. I don't know if there is a specific `radosgw` command to check the same.

**Comment by sidhant-agrawal** [comment]
I agree with @rachael-george 
As of now, RGW is optional for external mode OCS and hence the presence of RGW daemon does not guarantee that OCS is configured to use it.
A storage class with name `ocs-external-storagecluster-ceph-rgw` will be present in OCS cluster if `rgw-endpoint` was passed during external mode deployment.
