### ISSUE TITLE
VMware UPI Deployment workaround for BZ 1834966

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#3794]
When ocs-ci is used to deploy a cluster on VMware UPI platform, it is affected by BZ 1834966:

- there are lot of alerts related to openshift machine api (`MachineWithNoRunningPhase` and `MachineWithoutValidNode` ), so that it's easy to miss single new alert among these (with 3 master and 3 worker cluster, there would be 12 alerts caused by this issue)
- openshift machine api objects are present

This is a bug in openshift, with a possible workaround as explained in:

- https://github.com/openshift/installer/pull/3619/files
- https://access.redhat.com/solutions/5086271

We should investigate this and try to workaround the issue so that machinesets are not created on VMware UPI clusters, as it's really confusing and makes us likely to miss actual issues.

The issue was identified by Pratik.

**Comment by petr-balogh** [comment]
@vavuthu can you please take a look when you have time? Thanks
