### ISSUE TITLE
Check if "node replacement" and "add capacity" tests can run on PSI UPI

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3798]
Currently, the tests "node replacement" and "add capacity" had failed, as you can see here https://interop-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocs-4.6-openshift-4/15/testReport/. From what I see, the tests have failed because the following reasons:

- In the "node replacement" test, the new node didn't create successfully, 
- In the "add capacity" test, it failed to create new OSD's. 

The tests ran on PSI UPI. We need to figure out if the tests are adjusted to run on this platform, and if not, to fix them

**Comment by ebenahar** [comment]
@yitzhak12 I marked you as assignee. Please add this to your backlog
