### ISSUE TITLE
--cred <cred_file> doesn't exist in run.py

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#38]
Couldn't find --cred option in run.py:

(ocs-venv) [ebenahar@localhost ocs-ci]$ python3.7 run.py --suite suites/ocs_basic_install.yml --cred ~/.aws/config --log-level info
Usage:
run.py --suite FILE
[--conf ]
[--store]
[--reuse ]
[--post-results]
[--report-portal]
[--log-level ]
[--cluster-name ]
[--no-email]
run.py --cleanup=NAME [--osp-cred ]
[--log-level ]

**Comment by ebenahar** [comment]
Couldn't find --cred option in run.py:

(ocs-venv) [ebenahar@localhost ocs-ci]$ python3.7 run.py --suite suites/ocs_basic_install.yml --cred ~/.aws/config --log-level info
Usage:
  run.py --suite FILE
        [--conf <FILE>]
        [--store]
        [--reuse <FILE>]
        [--post-results]
        [--report-portal]
        [--log-level <LEVEL>]
        [--cluster-name <NAME>]
        [--no-email]
  run.py --cleanup=NAME [--osp-cred <FILE>]
        [--log-level <LEVEL>]

**Comment by ebenahar** [comment]
Last commit:

(ocs-venv) [ebenahar@localhost ocs-ci]$ git log
commit a5aa031f29d8d381be90e009e7b310443182c3e5 (HEAD -> master, origin/master, origin/HEAD)
Merge: 8518587 613b953
Author: vasukulkarni <vasu@redhat.com>
Date:   Fri May 10 12:14:09 2019 -0700

    Merge pull request #28 from petr-balogh/ignore-venv-in-flake8
    
    Ignore venv for flake8 in tox

**Comment by clacroix12** [comment]
To elaborate on this, we are calling `--cred` out in the usage documentation as a required argument. This is not true any more and we need to update our doc to reflect the correct usage.

**Comment by petr-balogh** [comment]
Fixed by #41
