### ISSUE TITLE
Need fix in /tests/manage/test_create_pvc_random_storage_class.py

### ISSUE THREAD

**Issue by shreekarSS** [red-hat-storage/ocs-ci#380]
In teardown(), need fix in
delete_cephblockpool() -->to accept list of pools created while testing, else it would delete all pools,
 delete_all_cephfilesystem() --> we may no need this anymore for this script

**Comment by prsurve** [comment]
hi @shreekarSS as per pr #284 i am using list of object for deletion in delete_cephblockpool()

**Comment by petr-balogh** [comment]
I am also looking to this teardown as I saw the issue when tried to push this PR #405 , we shouldn't use assertion like this in teardown:  https://github.com/red-hat-storage/ocs-ci/blob/d11d3829c3500f56972f1f6bb23e03fbddf48946/tests/manage/test_create_pvc_random_storage_class.py#L53-L63

Instead you should put the errors to some list of errors, and check at the end of teardown where you can do assert, but only once at the end as if some of assertion fail, you will never continue and the cleanup of other objects won't be done.

**Comment by vasukulkarni** [comment]
Closing stale issue.
