### ISSUE TITLE
Review and clean up logging across ocs-ci

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#3800]
ocs-ci is a complex application and having useful logging is a very important part of ensuring that the application is working properly as well as providing the right information to those who need to troubleshoot issues. Due to the nature of how some processes are handled in our code, I feel as though our logs get cluttered with a ton of information that is simply just noise.

I would like to take some time and review logs from a number of different deployment/test scenarios and identify some of the key offenders. One of which I already know of is `run_cmd`, especially when utilized in a loop or status check. Logging the command being executed each and every iteration is redundant and just creates a lot of noise for users to parse through so they can find the information they actually need.

A few ideas around how we can leverage logging in a much more efficient way while not removing important information from our logs:

- Leverage logging levels more (utilize debug level for information that doesn't need to always be present in logs, yet can be accessed if desired)
- Change lower level functions that get used widely across the project (`run_cmd`, `exec_cmd`, etc.) and suppress the logging when being used in a loop, resource status check, or other similar processes.
- Be more strict about logging practices during PR review. We can use the PR verification jobs to identify any new "noise" that is created by the PR.

Any other input or opinions on this would be greatly appreciated so please feel free to comment here if you want to weigh in.

**Comment by shylesh** [comment]
> ocs-ci is a complex application and having useful logging is a very important part of ensuring that the application is working properly as well as providing the right information to those who need to troubleshoot issues. Due to the nature of how some processes are handled in our code, I feel as though our logs get cluttered with a ton of information that is simply just noise.
> 
> I would like to take some time and review logs from a number of different deployment/test scenarios and identify some of the key offenders. One of which I already know of is `run_cmd`, especially when utilized in a loop or status check. Logging the command being executed each and every iteration is redundant and just creates a lot of noise for users to parse through so they can find the information they actually need.
> 
> A few ideas around how we can leverage logging in a much more efficient way while not removing important information from our logs:
> 
> * Leverage logging levels more (utilize debug level for information that doesn't need to always be present in logs, yet can be accessed if desired)
> * Change lower level functions that get used widely across the project (`run_cmd`, `exec_cmd`, etc.) and suppress the logging when being used in a loop, resource status check, or other similar processes.
> * Be more strict about logging practices during PR review. We can use the PR verification jobs to identify any new "noise" that is created by the PR.
> 
> Any other input or opinions on this would be greatly appreciated so please feel free to comment here if you want to weigh in.

I second this. Its bit painful to go through the logs as of now, we could see that log is full of retry messages. Definitely suppression of repeated logs is one of the features we want. Ofcourse I agree with remaining points as well. Thanks for bringing this up.
