### ISSUE TITLE
teardown failed with leftover label must-gather on BM

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#3815]
Summary:
Many test cases are failing during teardown with leftover label error.

Environment:
Config: Baremetal
Arch : s390 (z)

Sample tier: tier3
Reference logs : [tier3-21jan2021.zip](https://github.com/red-hat-storage/ocs-ci/files/5926209/tier3-21jan2021.zip)

```
exclude_labels = ['must-gather']

    def get_status_after_execution(exclude_labels=None):
        """
        Set the environment status and assign it into ENV_STATUS_PRE dictionary.
        In addition compare the dict before the execution and after using DeepDiff
    
        Args:
            exclude_labels (list): App labels to ignore leftovers
    
        Raises:
             ResourceLeftoversException: In case there are leftovers in the
                environment after the execution
        """
        get_environment_status(ENV_STATUS_POST, exclude_labels=exclude_labels)
    
        pod_diff = compare_dicts(
            ENV_STATUS_PRE['pod'], ENV_STATUS_POST['pod']
        )
        sc_diff = compare_dicts(
            ENV_STATUS_PRE['sc'], ENV_STATUS_POST['sc']
        )
        cephfs_diff = compare_dicts(
            ENV_STATUS_PRE['cephfs'], ENV_STATUS_POST['cephfs']
        )
        cephbp_diff = compare_dicts(
            ENV_STATUS_PRE['cephbp'], ENV_STATUS_POST['cephbp']
        )
        pv_diff = compare_dicts(
>           ENV_STATUS_PRE['pv'], ENV_STATUS_POST['pv']
        )

ocs_ci/utility/environment_check.py:166: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

before = None, after = None

    def compare_dicts(before, after):
        """
        Comparing 2 dicts and providing diff list of [added items, removed items]
    
        Args:
            before (dict): Dictionary before execution
            after (dict): Dictionary after execution
    
        Returns:
            list: List of 2 lists - ('added' and 'removed' are lists)
        """
        added = []
        removed = []
        uid_before = [
            uid.get('metadata').get(
                'generateName', uid.get('metadata').get('name')
>           ) for uid in before
        ]
E       TypeError: 'NoneType' object is not iterable

ocs_ci/utility/environment_check.py:53: TypeError
```

**Comment by abdulkandathil** [comment]
@RazTamir Can you please have a look into this?

**Comment by gitsridhar** [comment]
We see this issue in Power as well. 
exclude_labels = ['must-gather']

    def get_status_after_execution(exclude_labels=None):
        """
        Set the environment status and assign it into ENV_STATUS_PRE dictionary.
        In addition compare the dict before the execution and after using DeepDiff
    
        Args:
            exclude_labels (list): App labels to ignore leftovers
    
        Raises:
             ResourceLeftoversException: In case there are leftovers in the
                environment after the execution
        """
        get_environment_status(ENV_STATUS_POST, exclude_labels=exclude_labels)
    
        pod_diff = compare_dicts(ENV_STATUS_PRE["pod"], ENV_STATUS_POST["pod"])
        sc_diff = compare_dicts(ENV_STATUS_PRE["sc"], ENV_STATUS_POST["sc"])
        cephfs_diff = compare_dicts(ENV_STATUS_PRE["cephfs"], ENV_STATUS_POST["cephfs"])
        cephbp_diff = compare_dicts(ENV_STATUS_PRE["cephbp"], ENV_STATUS_POST["cephbp"])
>       pv_diff = compare_dicts(ENV_STATUS_PRE["pv"], ENV_STATUS_POST["pv"])

ocs_ci/utility/environment_check.py:161: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

before = None, after = None

    def compare_dicts(before, after):
        """
        Comparing 2 dicts and providing diff list of [added items, removed items]
    
        Args:
            before (dict): Dictionary before execution
            after (dict): Dictionary after execution
    
        Returns:
            list: List of 2 lists - ('added' and 'removed' are lists)
        """
        added = []
        removed = []
        uid_before = [
            uid.get("metadata").get("generateName", uid.get("metadata").get("name"))
>           for uid in before
        ]
E       TypeError: 'NoneType' object is not iterable

ocs_ci/utility/environment_check.py:52: TypeError
 ----------------------------Captured stderr teardown---------------------------- 
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "/root/ocs-upi-kvm/src/ocs-ci/ocs_ci/utility/environment_check.py", line 93, in assign_get_values
    ns = item.get("spec").get("claimRef").get("namespace")
AttributeError: 'NoneType' object has no attribute 'get'
2021-02-08T19:09:09Z (<ThreadPoolWorker at 0x7fff78d0c048 thread_ident=0x7fff71fbf170 threadpool-hub=<Hub at 0x7fff78d1c198 thread_ident=0x7fff98d35740>>, <function assign_get_values at 0x7fff80238158>) failed with AttributeError

**Comment by gitsridhar** [comment]
One of the dictionaries passed to the compare_dict method is None.

**Comment by gitsridhar** [comment]
In the compare_dicts method, if either before or after is None, the method can return None. But need to know if these two variables can be None, is it valid?

**Comment by lsmcfadden** [comment]
@RazTamir @abdulkandathil @gitsridhar 
Any updates?  Sridhar is it still relevant?

**Comment by gitsridhar** [comment]
Yes, seeing this in tier1 results.  @lsmcfadden

**Comment by lsmcfadden** [comment]
@RazTamir @abdulkandathil any idea who can answer Sridhar's questions and perhaps we can propose a fix and get some better tier 1 test results.

**Comment by abdulkandathil** [comment]
@lsmcfadden We were observing this error in different tiers on IBMZ.

**Comment by gitsridhar** [comment]
I will propose a PR for this problem based on my comment above. This will fix a significant number of teardown errors in tier1,2,3,4a,4b, and 4c.

**Comment by gitsridhar** [comment]
I submitted the final commit of PR #3960. This should reduce a large number of errors in various tier tests.

**Comment by lsmcfadden** [comment]
@gitsridhar we still need this to reduce errors in tier testing or alternative was devised?

**Comment by lsmcfadden** [comment]
Your PR merged so infer we can close this?

**Comment by lsmcfadden** [comment]
@abdulkandathil is the merge PR sufficient to close this or you are doing additional investigation?

**Comment by abdulkandathil** [comment]
@lsmcfadden I started seeing below error during the test execution. Looks like related to changes we made in this issue

```
11:09:37 - Dummy-7 - ocs_ci.utility.utils - INFO - Executing command: oc get StorageClass  -A -o yaml
Traceback (most recent call last):
  File "/root/ocs-ci/.venv/lib64/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "/root/ocs-ci/ocs_ci/utility/environment_check.py", line 98, in assign_get_values
    ns = item.get("spec").get("claimRef").get("namespace")
AttributeError: 'NoneType' object has no attribute 'get'
2021-04-23T09:09:38Z (<ThreadPoolWorker at 0x3ff914e7b40 thread_ident=0x3ff8a7fc910 threadpool-hub=<missing>>, <function assign_get_values at 0x3ff925ad790>) failed with AttributeError
```

**Comment by lsmcfadden** [comment]
@gitsridhar are you seeing this?

**Comment by abdulkandathil** [comment]
We are not seeing this error anymore.
