### ISSUE TITLE
Enhancements for disruptive PVC tests

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#382]
As suggested by @nehaberry, @sidhant-agrawal and @RazTamir, we should improve the PVC disruptive tests we have under tests/manage/test_pvc_disruptive.py. 
- [Neha/Sidhant] Create multiple PVCs instead of one
- [Raz] Validate that the pod can still run IO after deleting OSD/MON/MGR/MDS
- [Raz] Ensure that another pod can use the same PVC after resources deletion
- [Elad] Add Stop instance to the disruptive operations
- [Elad] Add detach resource disk to the disruptive operations

Please add more,
Thanks

**Comment by keesturam** [comment]
I'm not sure if this is the right place but adding my thoughts here. 

Failures to be introduced at the following phases.

1) Failure to be introduced just before PVC creation
2) PVC creation and failure introduced concurrently
3) PVC creation immediately followed by failure(s)

A similar set of operations with mapping PVC to app pod + Failures.

**Comment by ebenahar** [comment]
Thanks @keesturam!
Marking this issue as a tracker and let's open an issue for each suggestion implementation

**Comment by ebenahar** [comment]
Validate that the pod can still run IO after deleting OSD/MON/MGR/MDS - https://github.com/red-hat-storage/ocs-ci/pull/388

**Comment by jilju** [comment]
> I'm not sure if this is the right place but adding my thoughts here.
> 
> Failures to be introduced at the following phases.
> 
> 1. Failure to be introduced just before PVC creation
> 2. PVC creation and failure introduced concurrently
> 3. PVC creation immediately followed by failure(s)

If failure is introduced while creation of multiple PVC is in progress(requirement 2 mentioned above), it will also cover requirement 1 and 3.
@keesturam thoughts ?

**Comment by jilju** [comment]
> * [Neha/Sidhant] Create multiple PVCs instead of one
> * [Raz] Ensure that another pod can use the same PVC after resources deletion

PR #401

**Comment by jilju** [comment]
> 2. PVC creation and failure introduced concurrently
PR #401

**Comment by keesturam** [comment]
> > I'm not sure if this is the right place but adding my thoughts here.
> > Failures to be introduced at the following phases.
> > 
> > 1. Failure to be introduced just before PVC creation
> > 2. PVC creation and failure introduced concurrently
> > 3. PVC creation immediately followed by failure(s)
> 
> If failure is introduced while creation of multiple PVC is in progress(requirement 2 mentioned above), it will also cover requirement 1 and 3.
> @keesturam thoughts ?

Maybe. But, It would be good to run a definite test which gives the same result every time. By running the test with multiple pvc creation + failure, we may see different results based on the time of failure introduced.

**Comment by jilju** [comment]
> > * [Neha/Sidhant] Create multiple PVCs instead of one
> > * [Raz] Ensure that another pod can use the same PVC after resources deletion
> 
> PR #401

Completed.

**Comment by jilju** [comment]
> > 1. PVC creation and failure introduced concurrently
> >    PR #401

Completed

**Comment by jilju** [comment]
With reference to [comment](https://github.com/red-hat-storage/ocs-ci/pull/493#discussion_r310465532), these additional requirements has to be satisfied in Tier 4 test cases.
1. The script should be creating the RWX and RWO based PVCs as expected by test cases.
- Random choice of RWX and RWO can be used for bulk PVC creation scenarios.

2. The FIO needs to verify the data integrity of the data it wrote. The PR #412 has specific yaml and small code changes to do so.

3. Pod restarts count need to be checked before and after to make sure there is no unexpected pod restart happening.
-- PR #412 is having this code.

**Comment by jilju** [comment]
> With reference to [comment](https://github.com/red-hat-storage/ocs-ci/pull/493#discussion_r310465532), these additional requirements has to be satisfied in Tier 4 test cases.
> 
> 1. The script should be creating the RWX and RWO based PVCs as expected by test cases.
> 
Test cases updated to  create both RWO and RWX PVCs.

test_disruptive_during_pod_pvc_deletion_and_io, test_disruptive_during_pod_pvc_deletion - PR #672 
test_pvc_disruptive - PR #686 
test_resource_deletion_during_pvc_pod_creation_and_io - PR #693

**Comment by ebenahar** [comment]
@jilju are all enhancements now addressed?

**Comment by jilju** [comment]
> @jilju are all enhancements now addressed?

@ebenahar 
These are pending:

1. https://github.com/red-hat-storage/ocs-ci/issues/382#issuecomment-511219226
The risk involved in this is assumed to be covered in existing pv_services tier4 tests. But separate test cases are not present. Should we add new tests or stick to the existing tests only ?

2. PR [#412](https://github.com/red-hat-storage/ocs-ci/pull/412) is not merged.

3.  
[Elad] Add Stop instance to the disruptive operations
[Elad] Add detach resource disk to the disruptive operations

in https://github.com/red-hat-storage/ocs-ci/issues/382#issue-466285490

**Comment by ebenahar** [comment]
thanks @jilju 
@hnallurv @keesturam how do we proceed with the above?
