### ISSUE TITLE
IBM Scale test --  test_cephfs_many_files.py throws AlreadyExists when creating a pvc

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3835]
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage create -f /tmp/PersistentVolumeClaimfvqmy526 -o yaml.
E           Error is Error from server (AlreadyExists): error when creating "/tmp/PersistentVolumeClaimfvqmy526": persistentvolumeclaims "cephfs-pvc" already exists

**Comment by ramkiperiy** [comment]
Closing the issues, since PR is already merged
