### ISSUE TITLE
hard restrict the creation of cluster in vSphere to 2

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#3836]
hard restrict the creation of cluster in vSphere to 2

**Comment by petr-balogh** [comment]
@vavuthu who requested this?

**Comment by vavuthu** [comment]
> @vavuthu who requested this?

It came up while I am talking with @nehaberry

**Comment by petr-balogh** [comment]
Do we really have such issue like that people have 4 clusters at once?  Not sure if we should somehow prioritize on this as I don't think it's that often problem. Or is it @nehaberry ?

**Comment by vavuthu** [comment]
closing this as its not valid in current scenarios
