### ISSUE TITLE
IBM Scale: test_scale_pvc_expand run_cmd error during teardown

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#3843]
Logs: https://s3.upshift.redhat.com/ocs_ibm_power_tests/test_scale_02_report.html
Error:
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc label node  scale-label-.
E           Error is error: resource(s) were provided, but no name, label selector, or --all flag specified
---------------------------

def teardown():
>       resize_pvc.cleanup()

tests/e2e/scale/test_scale_pvc_expand.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/ocs/scale_lib.py:322: in cleanup
    node_list=scale_workers, label_key="scale-label"
ocs_ci/helpers/helpers.py:2368: in remove_label_from_worker_node
    command=f"label node {' '.join(node_list)} {label_key}-", out_yaml_format=False
ocs_ci/ocs/ocp.py:144: in exec_oc_cmd
    **kwargs,
ocs_ci/utility/utils.py:451: in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cmd = ['oc', 'label', 'node', 'scale-label-'], secrets = None, timeout = 600
ignore_error = False, kwargs = {}, masked_cmd = 'oc label node  scale-label-'
completed_process = CompletedProcess(args=['oc', 'label', 'node', 'scale-label-'], returncode=1, stdout=b'', stderr=b'error: resource(s) were provided, but no name, label selector, or --all flag specified\n')
masked_stdout = ''
masked_stderr = 'error: resource(s) were provided, but no name, label selector, or --all flag specified\n'

    def exec_cmd(cmd, secrets=None, timeout=600, ignore_error=False, **kwargs):
        """
        Run an arbitrary command locally
    
        Args:
            cmd (str): command to run
            secrets (list): A list of secrets to be masked with asterisks
                This kwarg is popped in order to not interfere with
                subprocess.run(``**kwargs``)
            timeout (int): Timeout for the command, defaults to 600 seconds.
            ignore_error (bool): True if ignore non zero return code and do not
                raise the exception.
    
        Raises:
            CommandFailed: In case the command execution fails
    
        Returns:
            (CompletedProcess) A CompletedProcess object of the command that was executed
            CompletedProcess attributes:
            args: The list or str args passed to run().
            returncode (str): The exit code of the process, negative for signals.
            stdout     (str): The standard output (None if not captured).
            stderr     (str): The standard error (None if not captured).
    
        """
        masked_cmd = mask_secrets(cmd, secrets)
        log.info(f"Executing command: {masked_cmd}")
        if isinstance(cmd, str):
            cmd = shlex.split(cmd)
        completed_process = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            timeout=timeout,
            **kwargs,
        )
        masked_stdout = mask_secrets(completed_process.stdout.decode(), secrets)
        if len(completed_process.stdout) > 0:
            log.debug(f"Command stdout: {masked_stdout}")
        else:
            log.debug("Command stdout is empty")
    
        masked_stderr = mask_secrets(completed_process.stderr.decode(), secrets)
        if len(completed_process.stderr) > 0:
            log.warning(f"Command stderr: {masked_stderr}")
        else:
            log.debug("Command stderr is empty")
        log.debug(f"Command return code: {completed_process.returncode}")
        if completed_process.returncode and not ignore_error:
            raise CommandFailed(
>               f"Error during execution of command: {masked_cmd}."
                f"\nError is {masked_stderr}"
            )
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc label node  scale-label-.
E           Error is error: resource(s) were provided, but no name, label selector, or --all flag specified

ocs_ci/utility/utils.py:506: CommandFailed
 ----------------------------Captured stdout teardown---------------------------- 
FAILED                                                                   [100%]

**Comment by ramkiperiy** [comment]
We need to discuss with IBM team to check if they are able to overcome this problem.
As per github issue https://github.com/red-hat-storage/ocs-ci/issues/4526 they are labeling the nodes before start of scale tests, which is kind of WA.

**Comment by ramkiperiy** [comment]
Fixed in PR https://github.com/red-hat-storage/ocs-ci/pull/4795
