### ISSUE TITLE
measure_pvc_deletion_time(interface, pv_name) measures negative time in case the deletion of pvc started on one day and ended on the following day 

### ISSUE THREAD

**Issue by ypersky1980** [red-hat-storage/ocs-ci#3844]
1) measure_pvc_deletion_time(interface, pv_name) measures negative time in case the deletion of pvc started on one day and ended on the following day . 

This needs to be fixed, otherwise we'll might have the following measure in performance tests : 

01:59:59 - MainThread - ocs_ci.ocs.ocp - INFO - PersistentVolumeClaim pvc-test-a8acc7233ee246038e738a6d6919c19 got deleted successfully
02:00:29 - MainThread - root - INFO - Inteface type: CephFileSystem: PVC number 10 deleted in -86398.566805 seconds

2) Probably the same will happen with measuring pvc creation time when the operation of creation starts on one day and ends on the following day.

**Comment by wusui** [comment]
Is there any reason why we don't just use the time.time() value?

Uh, Scratch that -- I see that we extract the data from log text.  Looking
at that data, I see that:

>>> logs[0]
'I0204 20:57:43.848435       1 feature_gate.go:243] feature gates: &{map[]}'
>>> logs[1]
'I0204 20:57:43.848629       1 csi-provisioner.go:132] Version:
v4.7.0-202101300133.p0-0-gd13a114-dirty'
>>> logs[-1]
''
>>> logs[-2]
'I0210 20:47:57.211610       1 leaderelection.go:273] successfully renewed
lease openshift-storage/openshift-storage-rbd-csi-ceph-com'

It looks like there is a month and day value (0210) before the time.  This
should be parsed out by get_start_creation_time
and get_end_creation_time.

This still will not work across year boundaries, but that's probably not
too big an issue.
