### ISSUE TITLE
AttributeError - test test_pvc_expand_expanded_pvc is failing 

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#3846]
The test case tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expand_expanded_pvc is failing with the below error.
```
for df_out in TimeoutSampler( 240, 3, pod_obj.exec_cmd_on_pod, command="df -kh" ):> df_out = df_out.split()E AttributeError: 'NoneType' object has no attribute 'split'tests/manage/pv_services/pvc_resize/test_pvc_expansion.py:110: AttributeError
```
The output of df command on the app pod did not return any value.
Test result - https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/204/testReport/tests.manage.pv_services.pvc_resize.test_pvc_expansion/TestPvcExpand/test_pvc_expand_expanded_pvc/

This issue was seen in two different executions.

**Comment by sidhant-agrawal** [comment]
Same issue observed in different test `test_resource_deletion_during_pvc_expansion` in `RUN ID: 1626452315`
```
>               df_out = df_out.split()
E               AttributeError: 'NoneType' object has no attribute 'split'

tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py:134: AttributeError
```
