### ISSUE TITLE
Examine if test_add_node could be enabled on VMware, now that bug 1844521 is closed

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#3855]
Hi @shreekarSS, @sidhant-agrawal https://bugzilla.redhat.com/show_bug.cgi?id=1844521 is closed and could be that we can re-enable tests.manage.z_cluster.cluster_expansion.test_node_expansion.TestAddNode on VMware

**Comment by sidhant-agrawal** [comment]
Yes, test_add_node can be enabled on VMware.
The tests will be enabled via PR #3823

**Comment by sidhant-agrawal** [comment]
PR #3823 is merged.
Closing this issue.
