### ISSUE TITLE
Pod is not being deleted as part of test_run_io teardown which causes the test teardown to stuck during PVC deletion

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#386]
tests.manage.test_pvc_deletion_during_io.TestDeletePVCWhileRunningIO#test_run_io

tests/manage/test_pvc_deletion_during_io.py::TestDeletePVCWhileRunningIO::test_run_io 
------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------
19:27:36 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod --selector=app=rook-ceph-tools -o yaml
19:27:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh rook-ceph-tools-76c7d559b6-6zmpg ceph auth get-key client.admin --format json-pretty
19:27:40 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding Secret with name secret-test-1019274019
19:27:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/Secretrjhpxjd6 -o yaml
19:27:41 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding CephBlockPool with name cbp-test-1019274107
19:27:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/CephBlockPoolg220d3hh -o yaml
19:27:41 - MainThread - tests.helpers - INFO - Verifying that block pool cbp-test-1019274107 exists
19:27:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod --selector=app=rook-ceph-tools -o yaml
19:27:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh rook-ceph-tools-76c7d559b6-6zmpg ceph osd lspools --format json-pretty
19:27:45 - MainThread - tests.helpers - INFO - POOLS are [{'poolnum': 1, 'poolname': 'rbd'}, {'poolnum': 2, 'poolname': 'ocsci-cephfs-metadata'}, {'poolnum': 3, 'poolname': 'ocsci-cephfs-data0'}, {'poolnum': 5, 'poolname': 'cbp-test-1019274107'}]
19:27:45 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding StorageClass with name storageclass-test-1019274595
19:27:45 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/StorageClassffxc2fx7 -o yaml
19:27:46 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding PersistentVolumeClaim with name pvc-test-1019274684
19:27:46 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/PersistentVolumeClaimn2vcpfjf -o yaml
19:27:47 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1019274684 -o yaml
19:27:48 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1019274684 -o yaml
19:27:52 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1019274684 -o yaml
19:27:53 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding Pod with name pod-test-1019275342
19:27:53 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/POD_quc_fn5j -o yaml
19:27:54 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:27:55 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:27:59 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:03 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:07 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:11 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:15 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:19 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:23 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
19:28:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod pod-test-1019275342 -o yaml
-------------------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------------------
19:28:29 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh pod-test-1019275342 which apt-get
19:28:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh pod-test-1019275342 apt-get update
19:28:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh pod-test-1019275342 apt-get -y install fio
19:28:45 - MainThread - ocs_ci.utility.utils - WARNING - Command warning:: debconf: delaying package configuration, since apt-utils is not installed
19:28:45 - ThreadPoolExecutor-1_0 - ocs_ci.utility.workloads.fio - INFO - Running cmd: fio --name=fio-rand-readwrite --filename=/var/lib/www/html/fio-rand-readwrite --readwrite=randrw --bs=4K --direct=1 --numjobs=1 --time_based=1 --runtime=60 --size=1G --iodepth=4 --invalidate=1 --fsync_on_close=1 --rwmixread=75 --ioengine=libaio --output-format=json
19:28:45 - MainThread - ocs_ci.ocs.workload - INFO - Done submitting..
19:28:45 - ThreadPoolExecutor-1_0 - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh pod-test-1019275342 fio --name=fio-rand-readwrite --filename=/var/lib/www/html/fio-rand-readwrite --readwrite=randrw --bs=4K --direct=1 --numjobs=1 --time_based=1 --runtime=60 --size=1G --iodepth=4 --invalidate=1 --fsync_on_close=1 --rwmixread=75 --ioengine=libaio --output-format=json
19:28:45 - MainThread - root - INFO - Waiting for results
19:30:12 - MainThread - root - INFO - IOPs after FIO:
19:30:12 - MainThread - root - INFO - Read: 1165.694477
19:30:12 - MainThread - root - INFO - Write: 388.987034
PASSED
------------------------------------------------------------------------------------------------ live log teardown ------------------------------------------------------------------------------------------------
19:30:12 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig delete PersistentVolumeClaim pvc-test-1019274684

**Comment by RazTamir** [comment]
My fault

**Comment by RazTamir** [comment]
Should be fixed with - https://github.com/red-hat-storage/ocs-ci/pull/387

**Comment by ebenahar** [comment]
Closed with https://github.com/red-hat-storage/ocs-ci/pull/387
