### ISSUE TITLE
New changes in naming convention of ES pods causing testcases to fail

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#3862]
Test Cases:
tests/e2e/logging/test_openshiftlogging.py::Testopenshiftloggingonocs::test_respin_osd_pods_to_verify_logging
tests/e2e/logging/test_openshift-logging.py::Testopenshiftloggingonocs::test_respin_elasticsearch_pod

Failed Logs:
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-logging rsh elasticsearch-im-infra-1613151900-s45vk es_util --query=*/_count?pretty -d '{"query": {"match":{"kubernetes.namespace_name": "openshift-storage"}}}'. Error is error: cannot exec into a container in a completed pod; current phase is Succeeded

Analysis:
Both the test cases failed because it was unable to rsh into ES pod
Usually there will be 9 ES pods--- 3 ES pods, 3 ES rollover and 3 ES delete pods, we won't be able to rsh into rollover and delete pods as they will be in completed state
But in the above test cases, I see some different names for ES pod with the label as "infra", But should be because of some new changes in naming conventions in  logging ES pods.

**from elasticsearch-operator.4.6.0-202101300140.p0, The change in the index management jobs was effective from Feb 08
along with OCP 4.6.16**

**Comment by PrasadDesala** [comment]
Fixed with https://github.com/red-hat-storage/ocs-ci/pull/3883
