### ISSUE TITLE
Baremetal: ocs deploy failes due to missing image-registry deployment

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#3879]
By default in an OCP bare-metal cluster, image-registry deployment is in a removed state.
```
(.venv) [root@m1301015 ocs-ci]# oc get configs.imageregistry.operator.openshift.io cluster -ojson | jq .spec.managementState
"Removed"
(.venv) [root@m1301015 ocs-ci]#
```
Because of this ocs deployment fails as the image registry operator cannot find image-registry deployment after ocs deployment.
```
19:54:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-image-registry get deployment image-registry -n openshift-image-registry -o yaml
19:54:43 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): deployments.apps "image-registry" not found

19:54:43 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: image-registry of kind: deployment, selector: None, Error: Error during execution of command: oc -n openshift-image-registry get deployment image-registry -n openshift-image-registry -o yaml.
Error is Error from server (NotFound): deployments.apps "image-registry" not found

19:54:43 - MainThread - ocs_ci.ocs.ocp - WARNING - Number of attempts to get resource reached!
19:54:43 - MainThread - ocs_ci.deployment.deployment - ERROR - Error during execution of command: oc -n openshift-image-registry get deployment image-registry -n openshift-image-registry -o yaml.
Error is Error from server (NotFound): deployments.apps "image-registry" not found
```

[ocs-deploy.log](https://github.com/red-hat-storage/ocs-ci/files/6005303/ocs-deploy-imageregistry.log)

**Comment by abdulkandathil** [comment]
Changing image-registry operator `managementState` to `Managed` on bare-metal before the PVC creation for image registry should solve the problem.

**Comment by petr-balogh** [comment]
Hey @abdulkandathil  we already have function implemented for this:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L179

but it requires to run OCP deployment by ocs-ci.

Function is implemented here:
https://github.com/red-hat-storage/ocs-ci/blob/7f638dc46cbb4d864fc945729f2531de3f9375be/ocs_ci/utility/utils.py#L2791

So we can add probably one more logic to OCS deployment to check the status of managementState and if it's not Managed we can change it there as well.
