### ISSUE TITLE
vSphere UPI - Add the cluster name as a prefix to the VM names

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#3884]
With vSphere UPI deployment, there could be cases in which the cluster VMs are no longer part of the cluster resource pool. This can happen, for example, in case the vcenter is being restored from a snapshot. In such a case, some of the vSphere resources, associated with the OCS clusters that were created prior to the snapshot restore, are being deleted since they did not exist at the point in time when the snapshot was taken. The cluster VMs on the other hand, remain running on the hypervisors, so the OCS clusters remain running.

In those cases, when the VMs are no longer part of their resource pool, they do not contain the indication for which resource pool they were part of. Their name is generic such as `compute-0` or `control-plane-0`.

We need a way of identifying the cluster name in the VMs name, for such cases.

So if it is possible, a solution would be to add the cluster name as a prefix to the VM names.

With vSphere IPI, this is not the case, as the VMs contain the cluster name

**Comment by petr-balogh** [comment]
@shylesh maybe you can take a look at this issue if you have some time? Thanks

**Comment by petr-balogh** [comment]
But not sure if we can easily change this as we are using some terraform templates from installer repository and this case we will need to do some tweaks which I would like to avoid if possible. @vavuthu maybe you can give here some of your thoughts. Thanks

**Comment by vasukulkarni** [comment]
Also we should check why restore from snapshot is not creating the original resource pool, In which case we should avoid the restore, I also lot my resource group and vm's due to this. we should avoid this disruption.
