### ISSUE TITLE
Add Ceph version check for OCS Upgrade test

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#3886]
checking for expected ceph version might be tricky, but we can print out before and after ceph version by using toolbox command

**Comment by PrasadDesala** [comment]
From 4.7, there is a new section in the StorageCluster.Status called "images", with a list of desired and actual images. I think we can make use of it for the validation of ceph version post upgrade, we need to  compare these images values and they should remain same.
I checked with Jose on this https://bugzilla.redhat.com/show_bug.cgi?id=1830215#c37. Please refer to the comment for more details.

**Comment by AviadP** [comment]
`oc get storagecluster -o jsonpath='{.items[].status.images}{"\n"}' |jq` will display images

**Comment by PrasadDesala** [comment]
@AviadP This is already implemented with PR #4334 
Please take a look.
