### ISSUE TITLE
We should have a platform wrapper (AWS, VMWare, PSI)

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#389]
ocs_ci.utility.aws.AWS and future VMWare and PSI classes should be wrapped in order to allow interaction with an abstraction layer for operations on the nodes during the tests.
For example, stopping a node (stop_instance() in AWS case) should be a generic class method for any kind of deployment

**Comment by ebenahar** [comment]
Implementation is done in https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py

**Comment by RazTamir** [comment]
@ebenahar are we going to have another issue for covering PSI too?

**Comment by ebenahar** [comment]
Thanks @RazTamir - here https://github.com/red-hat-storage/ocs-ci/issues/1920
