### ISSUE TITLE
amount attribute in nss_dict used in namespace_store_factory is not used

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#3943]
All calls to `namespace_store_factory` return one instance even when more are selected.
E.g.
```
$ nss_tup = ("oc", {"rgw": [(2, None)]})
$ ns_stores = namespace_store_factory(*nss_tup)
$ print(ns_stores)
 [<ocs_ci.ocs.resources.namespacestore.NamespaceStore object at 0x7fac38651320>]
```
CC @MeridianExplorer  @parikshithb

**Comment by MeridianExplorer** [comment]
Great catch, it's an implementation detail that had to be ditched due to time constraints between versions, should've been documented, but was forgotten.
Thank you very much

**Comment by MeridianExplorer** [comment]
Important catch!
I see you assigned it to yourself - I'll be glad to help and take the task if it helps

**Comment by MeridianExplorer** [comment]
The issue is still important and needs to be taken care of
