### ISSUE TITLE
ocs_ci/helper/helpers.py code duplication -- format defined in multiple places.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3952]
In eight separate locations in ocs_ci/helper/helpers.py, the variable format is defined to the same value and later used as a parameter to a datetime.datetime.strptime call.   The routines are slightly different but it appears that this code could probably be consolidated.

**Comment by clacroix12** [comment]
I would simply move this to a global variable `FORMAT`. If other modules in ocs-ci need the same format then it may be worth creating a constant out of it but initially I would just make it a global.

**Comment by wusui** [comment]
I made this change in 3868.  I will close this and open another bug on the code duplication in the helper routines.
