### ISSUE TITLE
helper/helper.py time code duplication

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3966]
The log time extraction functions duplicate a lot of code.  Coady has suggested the following:

get_start_creation_time and get_end_creation_time could call a generic function and pass 'start' or 'end' to it.
Same thing goes with get_start_deletion_time and get_end_deletion_time. Furthermore if that generic function took 'provision' or 'delete' as an argument you could call the same function from all four of those to cut down on a lot of code duplication.

**Comment by ramkiperiy** [comment]
@wusui Is this issue already resolved ? if so can you close it

**Comment by ramkiperiy** [comment]
Closing this issue, since PR is already merged.
