### ISSUE TITLE
Problem in generating a new machine name with AWS IPI

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3990]
When trying to add a new OCS worker node, the new node created successfully. 
But when searching for the old machine name at this line https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/node.py#L840 to know the new machine set, it didn't find it.
We probably need to change the method of searching the machine name.

Here is the failed test https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/187/testReport/tests.manage.z_cluster.nodes.test_node_replacement_proactive/TestNodeReplacement/test_nodereplacement_proactive/, and this is the Jenkins job: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/187/. We also need to notice that we added in this test infra worker nodes.

**Comment by yitzhak12** [comment]
The test above uses infra worker nodes. This is the conf file that is used: https://github.com/red-hat-storage/ocs-ci/blob/master/conf/deployment/aws/ipi_3az_rhcos_3m_3w_3i.yaml

**Comment by shylesh** [comment]
@yitzhak12 , @prsurve ,
 I submitted a PR #4045 which fixes the pattern matching issue, but looks like another failure at the line https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/node.py#L848 where we are trying to label the node but it already exists, I guess because of machine set

```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc label node ip-10-0-220-113.us-east-2.compute.internal cluster.ocs.openshift.io/openshift-storage=''.
E           Error is error: 'cluster.ocs.openshift.io/openshift-storage' already has a value (), and --overwrite is false

ocs_ci/utility/utils.py:507: CommandFailed

```

is this the expected behavior ?

**Comment by shylesh** [comment]
Ok, I found the behavior . If newly spun node is of type `worker` then there will not be `cluster.ocs.openshift.io/openshift-storage` label but if node is of type `Infra` then label will be already present. I made the necessary changes in the PR. I request you to review.
