### ISSUE TITLE
ocs-ci does not upgrade the openshift client after an update of the config.yaml

### ISSUE THREAD

**Issue by Sarah-Kriesch** [red-hat-storage/ocs-ci#3999]
I had an installation of OCP and OCS with the version 4.6 before the installation of 4.7.
I run ocs-ci with both versions. After an update of the config.yaml with the version 4.7, I expect that the openshift client will be used with 4.7 (or 4.7.1 in my case) will be used.

But ocs-ci is looking only for any existing openshift client and is using this one. Therefore, the openshift client with the version 4.6.11 is used in my case, what is wrong.

ocs-ci should check the existing version of the openshift client before using it. If that is the wrong one (not matching with the config.yaml), then it should be updated.

**Comment by petr-balogh** [comment]
Currently the client is downloaded during the installation deployment.
https://github.com/red-hat-storage/ocs-ci/blob/9f2a231a3fdd8ae677a0b1b64620dcfb4964c470/tests/conftest.py#L1118-L1122

Or when it does not exist.

You can delete the client from bin folder so then it should download new client next run-ci execution.

But you are right that we could have better check for particular version of the client. So if someone have still 4.6 and running 4.7 that it will rather delete that binary and download new one matching the OCP version passed to ocs-ci.

@clacroix12 can you take a look at this please?

**Comment by clacroix12** [comment]
@petr-balogh @Sarah-Kriesch Just wanted to update on this. I have a fix locally but I still need to do a bit of testing to make sure the scenario you described is covered correctly. I'll have a PR up once I verify that.

**Comment by Sarah-Kriesch** [comment]
Thank you, @clacroix12! One hint for you. That was one of my last feature requests / bug reports as an IBMer. My colleagues have to pick my tasks up, because I can not live without own open-source contributions. I will leave IBM.

Good luck and continue with your good work!
