### ISSUE TITLE
arch-specific acceptance test: test_jenkins_simulation

### ISSUE THREAD

**Issue by zmc** [red-hat-storage/ocs-ci#4027]
This test always fails on non-amd64 platforms because `quay.io/ocsci/git-alpine-image` isn't multi-arch. We should either:

* Use a different image
* Build the image on all arches
* Exclude the test from platforms it won't run on
* Remove the acceptance marker from the test

**Comment by PrasadDesala** [comment]
May be we can create a multi-arch based image so that it can run on different platforms. I will check on this.

**Comment by zmc** [comment]
@PrasadDesala I'm actually testing a fix now; I'll update when I have results. A quay.io outage meant I couldn't get it tested yesterday.
