### ISSUE TITLE
use a container image with fio pre-installed

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#403]
utility/workloads/fio.py installs fio within a container. one shouldn't run yum install within a container. That's not the way containers are designed. 

 We should rather build a container image with fio configured and use that image for running fio.

**Comment by vasukulkarni** [comment]
I completely agree that we should't do this, but working from testing point, we will need tools on pods which will not be shipped as standard packages, how are we going to handle that? maintain custom images?

**Comment by keesturam** [comment]
Yes, we will have to maintain the images as long as we use fio or similar test tools within the container.

**Comment by vasukulkarni** [comment]
Its actually more work considering the distro and other packages that have to be installed + configured. Standard templates provide quite a few deployment pods, Trying to clone them and add our packages is quite a lot of work(and dont forget ongoing catchup when the deployment pods are updated)

**Comment by vasukulkarni** [comment]
@ktdreyer whats your suggestion here?

**Comment by ktdreyer** [comment]
Maintaining an existing image on top of Ceph sounds like an incredible amount of work and places where things could go wrong.

What are the exact problems you are having with `utility/workloads/fio.py` ?

**Comment by vasukulkarni** [comment]
@ktdreyer If you look at the pod here(just one example): https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/templates/CSI/rbd/pod.yaml#L10 , the nginx pod will have to be replace with custom pod with fio preinstalled. likewise for other deployment pods that come shipped with ocp.

**Comment by vasukulkarni** [comment]
> Maintaining an existing image on top of Ceph sounds like an incredible amount of work and places where things could go wrong.
> 
> What are the exact problems you are having with `utility/workloads/fio.py` ?
The test script above tries to install fio and it works atleast for ubuntu/centos, but if the pod is changed to fedora, the above mentioned script fails during 'yum install'

**Comment by ktdreyer** [comment]
Why does fio have to be in the nginx container, instead of putting FIO into its own dedicated container?

**Comment by vasukulkarni** [comment]
> Why does fio have to be in the nginx container, instead of putting FIO into its own dedicated container?

So the idea is we just want to be able to configure a pod to add IO tools and use it for multiple uses,  if thats not possible, then for every tool(fio,dbench, mysql etc), we basically have to create our own Image and I can see us easily maintaining 10+ custom images for such tools.

Is there not an easy way to configure them on the fly with standard images ?

**Comment by ktdreyer** [comment]
It sounds like you're asking for a standard image with FIO preinstalled.

Have you asked the FIO upstream project to provide their own container image? Or you could volunteer to maintain such an image for them.

I think you're going to have to do some level of maintenance either way.

**Comment by RazTamir** [comment]
What is the overhead with creating "testing" image that will be used by QE for testing?
I see we will need more pre-installed on such image and don't think we should do it as part of our tests (it can take a lot of time to install fio every time). 
I started to work on doing multiple git clones from a pod as part of some test and was needed to install git. 
I think we will need to have such QE images

**Comment by vasukulkarni** [comment]
@ktdreyer @RazTamir this is not one time thing *just for* FIO(its one example here),  there are standard deployment-templates that come with bare minimum to run the the app that the template supports, let's take an example of postgresql app template that ships with openshift, since it doesn't come with say iostat or a client to stress db, then essentially one has to clone the image and add software layers and keep maintaining those instead of just configuring the same image on the fly - for FIO itself ( distro + version combination would be huge ) and for others again catching up with master image and updating as needed.

**Comment by vasukulkarni** [comment]
same could also happen later with ceph-tools-pod if we detect that we need something it doesn't have, previously in teuthology/cephci we just configured it on the fly.

**Comment by RazTamir** [comment]
I see,
Thanks for clarifying.

**Comment by mbukatov** [comment]
During debugging of OCS-530, I noticed behaviour related to this discussion.

In 3 of our 6 test runs with a single OCS-530 test, I see that installation of fio tool failed:

```
$ ls cluster-2019-08-19.1.testrun*
cluster-2019-08-19.1.testrun-001.log  cluster-2019-08-19.1.testrun-002.log  cluster-2019-08-19.1.testrun-003.log  cluster-2019-08-19.1.testrun-004.log  cluster-2019-08-19.1.testrun-005.log  cluster-2019-08-19.1.testrun-006.log
$ grep -i 'CommandFailed.*fio' cluster-2019-08-19.1.testrun* 
cluster-2019-08-19.1.testrun-002.log:E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'namespace-test-04a6e6e2ca674c75af9ad5e9c2edc5bc', '--kubeconfig', '/home/ocsqe/data/cluster-2019-08-19.1/auth/kubeconfig', 'rsh', 'pod-test-rbd-57a59d96ef81400e81d069b9d7ce1089', 'apt-get', '-y', 'install', 'fio'].
cluster-2019-08-19.1.testrun-003.log:E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'namespace-test-5b58a3c4c96e4ab79738ee7c42cf3c70', '--kubeconfig', '/home/ocsqe/data/cluster-2019-08-19.1/auth/kubeconfig', 'rsh', 'pod-test-rbd-802739fed22746d48cad666210952aea', 'apt-get', '-y', 'install', 'fio'].
cluster-2019-08-19.1.testrun-004.log:E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'namespace-test-e8dc8bbb1e034bec8de863e9e4b2343a', '--kubeconfig', '/home/ocsqe/data/cluster-2019-08-19.1/auth/kubeconfig', 'rsh', 'pod-test-rbd-0152890e29ae4f2199786b36cc9a646d', 'apt-get', '-y', 'install', 'fio']
```

So I would say that maintaining QE images for particular workloads such as fio will have additional effect of making our test runs in CI more stable.

**Comment by gklein** [comment]
Based on the discussion, I think we should consider to use a mix of both solution suggested:
1. For simple workloads such as fio, vdbench etc, it makes sense to maintain a container images on quay so it will save both time and trouble during test runtime.
2. For more complex scenarios such as PostgreSQL  + pgbench etc, we can keep the yum/apt/dnf flow in order to avoid maintaining a complex matrix of images.

What do you think?

**Comment by keesturam** [comment]
Please have a look at the function introduced in this PR #1460 . With the introduction of this function, one can create custom images on the fly and stored in the local registry of the openshift cluster. I believe this should solve this issue.
