### ISSUE TITLE
Few e2e test issues - pgsql run and Amq Cleanup issue for e2e_aggresive tests

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#4040]
1) Fix Pgsql test run
   https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/284/testReport/junit/tests.e2e.lifecycle.pvc_clone.test_pgsql_pvc_clone/TestPvcCloneOfWorkloads/test_pvc_clone/

2) Fix the amq cleanup issue seen here

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/284/testReport/junit/tests.e2e.workloads.test_new_sc_rbd_e2e_workloads/TestCreateNewScWithNeWRbDPoolE2EWorkloads/test_new_sc_new_rbd_pool_e2e_wl_3_aggressive_/

2) Mark the test for appropriate tier

3) Ensure its run with right disk size

**Comment by shreekarSS** [comment]
Regarding the appropriate tier for this testcase, tests are not 'failure and recovery' kinds of tests,  they do not belong to tier4. They are +ve tests (Feature Integration test) but with a bit more specific and slightly complicated than tier1 and hence they are in tier2.
About disk size, pvcs created for amq, pgsql  and coucbase workloads vary from 5-10G size, hence these tests can be run on any cluster.
