### ISSUE TITLE
Scale: TestPVCCreationDeletionScale.test_all_4_type_pvc_creation_deletion_scale failed to measure creation time

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#4042]
Logs: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/235/testReport/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_all_4_type_pvc_creation_deletion_scale/
Stacktrace
self = <test_pvc_creation_deletion_scale.TestPVCCreationDeletionScale object at 0x7fd6f352f040>
namespace = None
tmp_path = PosixPath('/tmp/pytest-of-jenkins/pytest-0/test_all_4_type_pvc_creation_d0')

    @polarion_id("OCS-1885")
    @pytest.mark.usefixtures(namespace.__name__)
    def test_all_4_type_pvc_creation_deletion_scale(self, namespace, tmp_path):
        """
        Measuring PVC creation time while scaling PVC of all 4 types,
        A total of 500 times the number of worker nodes
        will be created, i.e. 375 each pvc type
        Measure PVC deletion time in scale env
        """
        scale_pvc_count = scale_lib.get_max_pvc_count()
        log.info(f"Start creating {scale_pvc_count} PVC of all 4 types")
        cephfs_sc_obj = constants.DEFAULT_STORAGECLASS_CEPHFS
        rbd_sc_obj = constants.DEFAULT_STORAGECLASS_RBD
    
        # Get pvc_dict_list, append all the pvc.yaml dict to pvc_dict_list
        rbd_pvc_dict_list, cephfs_pvc_dict_list = ([] for i in range(2))
        for mode in [constants.ACCESS_MODE_RWO, constants.ACCESS_MODE_RWX]:
            rbd_pvc_dict_list.extend(
                scale_lib.construct_pvc_creation_yaml_bulk_for_kube_job(
                    no_of_pvc=int(scale_pvc_count / 4),
                    access_mode=mode,
                    sc_name=rbd_sc_obj,
                )
            )
            cephfs_pvc_dict_list.extend(
                scale_lib.construct_pvc_creation_yaml_bulk_for_kube_job(
                    no_of_pvc=int(scale_pvc_count / 4),
                    access_mode=mode,
                    sc_name=cephfs_sc_obj,
                )
            )
    
        # There is 2 kube_job for cephfs and rbd PVCs
        job_file_rbd = ObjectConfFile(
            name="rbd_pvc_job",
            obj_dict_list=rbd_pvc_dict_list,
            project=self.namespace,
            tmp_path=tmp_path,
        )
        job_file_cephfs = ObjectConfFile(
            name="cephfs_pvc_job",
            obj_dict_list=cephfs_pvc_dict_list,
            project=self.namespace,
            tmp_path=tmp_path,
        )
    
        # Create kube_job
        job_file_rbd.create(namespace=self.namespace)
        job_file_cephfs.create(namespace=self.namespace)
    
        # Check all the PVC reached Bound state
        rbd_pvc_name = scale_lib.check_all_pvc_reached_bound_state_in_kube_job(
            kube_job_obj=job_file_rbd,
            namespace=self.namespace,
            no_of_pvc=int(scale_pvc_count / 2),
        )
        fs_pvc_name = scale_lib.check_all_pvc_reached_bound_state_in_kube_job(
            kube_job_obj=job_file_cephfs,
            namespace=self.namespace,
            no_of_pvc=int(scale_pvc_count / 2),
        )
    
        # Get pvc objs from namespace, which is used to identify backend pv
        rbd_pvc_obj, cephfs_pvc_obj = ([] for i in range(2))
        pvc_objs = pvc.get_all_pvc_objs(namespace=self.namespace)
        for pvc_obj in pvc_objs:
            if pvc_obj.backed_sc == constants.DEFAULT_STORAGECLASS_RBD:
                rbd_pvc_obj.append(pvc_obj)
            elif pvc_obj.backed_sc == constants.DEFAULT_STORAGECLASS_CEPHFS:
                cephfs_pvc_obj.append(pvc_obj)
    
        # Get PVC creation time
        fs_pvc_create_time = helpers.measure_pvc_creation_time_bulk(
            interface=constants.CEPHFS_INTERFACE, pvc_name_list=fs_pvc_name
        )
>       rbd_pvc_create_time = helpers.measure_pvc_creation_time_bulk(
            interface=constants.CEPHBLOCKPOOL, pvc_name_list=rbd_pvc_name
        )

tests/e2e/scale/test_pvc_creation_deletion_scale.py:237: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

interface = 'CephBlockPool'
pvc_name_list = ['pvc-test-7837d5d5a5e44cfeb944646963966ab', 'pvc-test-2518de267eb24622b2919f0da1db386', 'pvc-test-4e73983a85214537b87...2ff17412398fdc1b0082537f', 'pvc-test-dc170eef8f1143c487b9eda55472adc', 'pvc-test-2ad6434c38ad41dc968e5b81673cf89', ...]
wait_time = 60

    def measure_pvc_creation_time_bulk(interface, pvc_name_list, wait_time=60):
        """
        Measure PVC creation time of bulk PVC based on logs.
    
        Args:
            interface (str): The interface backed the PVC
            pvc_name_list (list): List of PVC Names for measuring creation time
            wait_time (int): Seconds to wait before collecting CSI log
    
        Returns:
            pvc_dict (dict): Dictionary of pvc_name with creation time.
    
        """
        # Get the correct provisioner pod based on the interface
        pod_name = pod.get_csi_provisioner_pod(interface)
        # due to some delay in CSI log generation added wait
        time.sleep(wait_time)
        # get the logs from the csi-provisioner containers
        logs = pod.get_pod_logs(pod_name[0], "csi-provisioner")
        logs += pod.get_pod_logs(pod_name[1], "csi-provisioner")
        logs = logs.split("\n")
    
        loop_counter = 0
        while True:
            no_data_list = list()
            for name in pvc_name_list:
                # check if PV data present in CSI logs
                start = [i for i in logs if re.search(f"provision.*{name}.*started", i)]
                end = [i for i in logs if re.search(f"provision.*{name}.*succeeded", i)]
                if not start or not end:
                    no_data_list.append(name)
    
            if no_data_list:
                # Clear and get CSI logs after 60secs
                logging.info(f"PVC count without CSI create log data {len(no_data_list)}")
                logs.clear()
                time.sleep(wait_time)
                logs = pod.get_pod_logs(pod_name[0], "csi-provisioner")
                logs += pod.get_pod_logs(pod_name[1], "csi-provisioner")
                logs = logs.split("\n")
                loop_counter += 1
                if loop_counter >= 3:
                    logging.info("Waited for more than 3mins still no data")
>                   raise UnexpectedBehaviour(
                        f"There is no pvc creation data in CSI logs for {no_data_list}"
                    )
E                   ocs_ci.ocs.exceptions.UnexpectedBehaviour: There is no pvc creation data in CSI logs for ['pvc-test-7837d5d5a5e44cfeb944646963966ab', 'pvc-test-2518de267eb24622b2919f0da1db386', ...]

**Comment by ramkiperiy** [comment]
This needs to be monitored with up-coming executions, if we observe this problem consistently then should report bz, since it's problem that we can't respective PVC logs in CSI

**Comment by keesturam** [comment]
@wusui @tiffanyn108 Let's raise a bug as Ram suggested on the next occurrence of this issue

**Comment by ramkiperiy** [comment]
We have hit this problem again https://github.com/red-hat-storage/ocs-ci/issues/4201
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/559/

**Comment by ramkiperiy** [comment]
@tiffanyn108 we need to analyse logs and report bz for this issue.

**Comment by ramkiperiy** [comment]
Observed this problem again https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/638/testReport/junit/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_all_4_type_pvc_creation_deletion_scale/
Need more debugging to understand why this problem is observed in 4th test, i.e. before this test 3 TC passed for capturing creation and deletion time from CSI logs i.e. 4500 PVCs created/deleted and captured creation/deletion time for all those 4500.
Everytime it's test_all_4_type_pvc_creation_deletion_scale fails where we are creating all 4types of PVCs.

**Comment by ramkiperiy** [comment]
We have increase the wait time in test script for PVC create/delete log to be takes some time to add in CSI logs.
Again this issue is in-consistent, if observed again have to report bug.

**Comment by ramkiperiy** [comment]
Based on 4.9 test run output will be closing this issue.

**Comment by ramkiperiy** [comment]
Observed this issue in 4.9 Vsphere UPI platform 
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1875/testReport/junit/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_multiple_pvc_creation_deletion_scale_ReadWriteMany_CephBlockPool_/
