### ISSUE TITLE
All version comparison should be converted to use semantic version

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#4066]
As we are comparing a lot of versions once the version will go to 4.10 and higher then we will have serious issue with the most of comparison we have. See example below.

```
In [1]: from semantic_version import Version

In [2]: Version.coerce("4.7") < Version.coerce("4.11")
Out[2]: True

In [3]: "4.7" < "4.11"
Out[3]: False

In [4]: 4.7 < 4.11
Out[4]: False
```

**Comment by clacroix12** [comment]
@petr-balogh I think this is another good reason for us to move to version specific branches. That won't remove the need for this change as we will most likely still have to deal with version discrepancies regarding OCP, but it should cut down the need for it significantly.

**Comment by petr-balogh** [comment]
Not fully fixed by previous PR, hence re-opening till fully fixed.

**Comment by clacroix12** [comment]
I believe we still have places in the code where we need to do this so I am removing the stale label.

**Comment by petr-balogh** [comment]
> #4872



> I believe we still have places in the code where we need to do this so I am removing the stale label.
