### ISSUE TITLE
move helpers.py under utils

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#408]
So that other components tests can resuse those fixtures.

**Comment by clacroix12** [comment]
@vasukulkarni just for clarity I don't think we have any fixtures in `helpers.py`. Also any of the utilities here can be imported directly with `from tests.helpers import <function>`

**Comment by vasukulkarni** [comment]
yeah agree,  closing this one.

**Comment by mbukatov** [comment]
Right, the functions there are not fixtures, but  still I consider move of helpers.py into utils to be a good idea, so that all utils will be stored in a single place, while tests directory will contain only fixtures and actual tests.

**Comment by RazTamir** [comment]
If we are going that direction, we will also need to remove everything from utils that is not in use today.

**Comment by clacroix12** [comment]
> I consider move of helpers.py into utils to be a good idea, so that all utils will be stored in a single place, while tests directory will contain only fixtures and actual tests.

I agree, I think this would help organize things a bit more.

> If we are going that direction, we will also need to remove everything from utils that is not in use today.

Is this a hard requirement? It should definitely happen, but I'm not sure if it should block moving helpers from `tests` to the `utility` module.

**Comment by RazTamir** [comment]
Not hard requirement

**Comment by mbukatov** [comment]
Note that when addressing this issue, now we have multiple `*_helpers.py` files in the test directory.

**Comment by vasukulkarni** [comment]
reorganize utils properly under specific folders (eg: e2e, logging etc)

**Comment by mbukatov** [comment]
This causes issues like https://github.com/red-hat-storage/ocs-ci/issues/2639

**Comment by mbukatov** [comment]
Enough of this.

**Comment by mbukatov** [comment]
I'm going to propose to move all non test code from tests directory tree to `ocs_ci/helpers` module. Consequently, we can move it to other more fitting locations within ocs_ci module, but at least it will fix the main problem.

**Comment by mbukatov** [comment]
In e3807af1f265b55eee7a35a54597a130276a0bb4 the 1st part of the work has been done: all non test code was moved out of tests directory.
