### ISSUE TITLE
In case of deployment test failure, must gather is being collected twice

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#4092]
We have double collection - both in here (which is called from test_deployment:
https://github.com/red-hat-storage/ocs-ci/blob/c78b21697d728bd67e8c17b2e31876a7b8ae574e/ocs_ci/deployment/deployment.py#L137

And here:
https://github.com/red-hat-storage/ocs-ci/blob/c78b21697d728bd67e8c17b2e31876a7b8ae574e/ocs_ci/framework/pytest_customization/ocscilib.py#L520

**Comment by vavuthu** [comment]
@ebenahar Do you have any job link where its collected twice , from the code i can see we have check for not collecting twice

**Comment by petr-balogh** [comment]
I also think that this one was fixed already. @jimdevops19 did some code changes in this area IIRC.  Closing this one. @ebenahar if you still see this issue, please re-open.
