### ISSUE TITLE
openshift client download issues

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#4093]
A few different issues were brought up around how we are handling the openshift client download:

- [x] handling of the client should be skippable via configuration
- [x] we should verify the downloaded binary runs before moving on
- [x] we should not delete existing binaries until new ones have been verified
- [x] we should support downloading of binaries for different architectures. (right now we are only downloading x86 clients)

**Comment by clacroix12** [comment]
@vasukulkarni @zmc

**Comment by clacroix12** [comment]
First three issues have been addressed by #4094

**Comment by petr-balogh** [comment]
@clacroix12 isn't the forth one fixed in this documentation:
https://ocs-ci.readthedocs.io/en/latest/usecases/using_alternative_ocp_mirrors.html?highlight=arch 
?

If so, please close.

**Comment by clacroix12** [comment]
Yes it looks like we can specify a mirror that hosts other architecture binaries. Closing this out.
