### ISSUE TITLE
Allow OCS-CI Tiers to run without a Elastic Search Environment

### ISSUE THREAD

**Issue by tstober** [red-hat-storage/ocs-ci#4103]
Add to OCS-CI the ability to detect if no Elastic Search is configured and ready.
Gracefully continue the test execution in that case withus using Elastic Search and its dependencies.

@RazTamir mentioned that this work is currently going on.
This issue should help to track the progress.

**Comment by tstober** [comment]
@keesturam @Avilir

**Comment by Avilir** [comment]
fixed with #4127
