### ISSUE TITLE
AMQ failed to create kafkatopics.kafka.strimzi.io

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#4128]
Full log: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/398/testReport/tests.e2e.scale.test_scale_amq/TestAMQBasics/test_install_amq_scale_CephBlockPool_/

Error log:
>           raise CommandFailed(
                f"Error during execution of command: {masked_cmd}."
                f"\nError is {masked_stderr}"
            )
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc create -f /tmp/KafkaTopicl0q1ols2 -o yaml.
E           Error is Error from server (AlreadyExists): error when creating "/tmp/KafkaTopicl0q1ols2": kafkatopics.kafka.strimzi.io "my-topic" already exists

**Comment by ramkiperiy** [comment]
Closing this issue, since we are planning to re-work on this test
