### ISSUE TITLE
Noobaa autoscale failed to validate autoscale endpoint count

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#4129]
Full log: 
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/398/testReport/junit/tests.e2e.scale.noobaa.test_scale_endpoint/TestScaleEndpointAutoScale/test_scale_endpoint_and_respin_ceph_pods_mds_/

Error log:
# Validate autoscale endpoint count
>       self._assert_endpoint_count(desired_count=2)

tests/e2e/scale/noobaa/test_scale_endpoint.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/e2e/scale/noobaa/test_scale_endpoint.py:65: in _assert_endpoint_count
    assert pod.wait_for_resource(
ocs_ci/ocs/ocp.py:648: in wait_for_resource
    raise (ex)
ocs_ci/ocs/ocp.py:538: in wait_for_resource
    for sample in TimeoutSampler(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7fed06313f40>

    def __iter__(self):
        if self.start_time is None:
            self.start_time = time.time()
        while True:
            self.last_sample_time = time.time()
            if self.timeout <= (self.last_sample_time - self.start_time):
>               raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 500s running get("", True, "noobaa-s3=noobaa")

ocs_ci/utility/utils.py:989: TimeoutExpiredError

**Comment by ramkiperiy** [comment]
@tiffanyn108 its duplicate of issue https://github.com/red-hat-storage/ocs-ci/issues/4044, please close either of the one.

**Comment by tiffanyn108** [comment]
Did some investigate on this issue.  There was some changes in cluster that cause this issue compare to 4.6 release.  Look like FIO workload generated was not enough to trigger 80% of CPU usage.  Therefore autoscale endpoint didn't create additional noobaa-endpoint pod.
``` 
$ oc get hpa noobaa-endpoint -n openshift-storage -w
NAME              REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          107m
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          108m
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          108m
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          109m
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          109m
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          110m
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          110m
noobaa-endpoint   Deployment/noobaa-endpoint   9%/80%    1         2         1          111m
noobaa-endpoint   Deployment/noobaa-endpoint   17%/80%   1         2         1          111m
noobaa-endpoint   Deployment/noobaa-endpoint   12%/80%   1         2         1          112m
noobaa-endpoint   Deployment/noobaa-endpoint   13%/80%   1         2         1          112m
noobaa-endpoint   Deployment/noobaa-endpoint   9%/80%    1         2         1          113m
noobaa-endpoint   Deployment/noobaa-endpoint   10%/80%   1         2         1          113m
noobaa-endpoint   Deployment/noobaa-endpoint   12%/80%   1         2         1          114m
noobaa-endpoint   Deployment/noobaa-endpoint   9%/80%    1         2         1          114m
noobaa-endpoint   Deployment/noobaa-endpoint   10%/80%   1         2         1          115m
noobaa-endpoint   Deployment/noobaa-endpoint   10%/80%   1         2         1          115m
noobaa-endpoint   Deployment/noobaa-endpoint   6%/80%    1         2         1          116m
noobaa-endpoint   Deployment/noobaa-endpoint   11%/80%   1         2         1          116m
```

Need to revisit FIO workload and modify FIO parameters to create heavy load on cluster to reach to >80% CPU usage.

**Comment by MeridianExplorer** [comment]
Duplicate of #4002, closed 4002.

**Comment by ramkiperiy** [comment]
Observed this Issue again 

Error Message

ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 500s running get("", True, "noobaa-s3=noobaa")

Stacktrace

self = <test_scale_endpoint.TestScaleEndpointAutoScale object at 0x7fa31ea7d970>
mcg_job_factory = <function mcg_job_factory.<locals>._factory at 0x7fa388fdbd30>
resource_to_delete = 'mgr'

    def test_scale_endpoint_and_respin_ceph_pods(
        self, mcg_job_factory, resource_to_delete
    ):
        """
        Generate S3 workload to trigger autoscale to increase from 1 to 2 endpoint
        then respin ceph pods
        """
        # Add workers node to cluster
        scale_pgsql.add_worker_node()
    
        # Check autoscale endpoint count before start s3 load
        self._assert_endpoint_count(desired_count=1)
    
        # Create s3 workload using mcg_job_factory
        job = mcg_job_factory(custom_options=options)
    
        # Validate autoscale endpoint count
>       self._assert_endpoint_count(desired_count=2)

tests/e2e/scale/noobaa/test_scale_endpoint.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/e2e/scale/noobaa/test_scale_endpoint.py:65: in _assert_endpoint_count
    assert pod.wait_for_resource(
ocs_ci/ocs/ocp.py:648: in wait_for_resource
    raise (ex)
ocs_ci/ocs/ocp.py:538: in wait_for_resource
    for sample in TimeoutSampler(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7fa353d717f0>

    def __iter__(self):
        if self.start_time is None:
            self.start_time = time.time()
        while True:
            self.last_sample_time = time.time()
            if self.timeout <= (self.last_sample_time - self.start_time):
>               raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 500s running get("", True, "noobaa-s3=noobaa")

ocs_ci/utility/utils.py:989: TimeoutExpiredError

Standard Output

tests/e2e/scale/noobaa/test_hsbench.py::TestHsBench::test_s3_benchmark_hsbench #x1B[31mERROR#x1B[0m#x1B[31m [ 84%]#x1B[0m
tests/e2e/scale/noobaa/test_scale_endpoint.py::TestScaleEndpointAutoScale::test_scale_endpoint_and_respin_ceph_pods[mgr] #x1B[31mFAILED#x1B[0m#x1B[31m                                                                   [ 86%]#x1B[0m

Test run: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/638/
Test case failure: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/638/testReport/junit/tests.e2e.scale.noobaa.test_scale_endpoint/TestScaleEndpointAutoScale/test_scale_endpoint_and_respin_ceph_pods_mgr_/

**Comment by tiffanyn108** [comment]
fixed is merged.  Closing this PR.
