### ISSUE TITLE
Move our deployment to 4.2

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#413]
We need to deploy OCS on top of OCP 4.2 ASAP.
There are many features we are missing just by running on 4.1 today.

Let's pick some stable image from here https://openshift-release.svc.ci.openshift.org/ for example 4.2.0-0.ci-2019-07-12-102949

**Comment by clacroix12** [comment]
We are tracking this work in [JIRA](https://projects.engineering.redhat.com/browse/OCSQE-11)

**Comment by clacroix12** [comment]
Closing as #494 is merged
