### ISSUE TITLE
Remove scale pymark from old test that block jenkins run

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#4138]
From email thread with Vijay

http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j002ai3c33-s/j002ai3c33-s_20210415T062407/logs/ocs-ci-logs-1618471561/tests/e2e/scale/

**Comment by ramkiperiy** [comment]
PR #4111 should solve this problem, also the PR has skip marker added for PVC-Expand TC which uses old method of scaling.
PR is in final stages, has jenkins validation run passed and comments addressed if there is no much new review comments then I would suggest to merge this as high priority.

**Comment by ramkiperiy** [comment]
Passed Jenkins validation run result of PR #4111 Complete execution logs can be found in https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/1866/console

**Comment by ramkiperiy** [comment]
@vasukulkarni PR is merged let me know if more work required for this issue.

**Comment by vasukulkarni** [comment]
Thanks @ramkiperiy closing this one based on https://github.com/red-hat-storage/ocs-ci/pull/4111
