### ISSUE TITLE
Fixtures create_rbd_storageclass and create_cephfs_storageclass uses same attribute name "sc_obj"

### ISSUE THREAD

**Issue by PrasadDesala** [red-hat-storage/ocs-ci#417]
Fixtures create_rbd_storageclass and create_cephfs_storageclass uses same attribute name "sc_obj".

create_rbd_storageclass
create_cephfs_storageclass
 
Since we are using same attribute name "sc_obj"  in both these fixtures, if we use both these fixtures in a same test case the attribute will get overrided with the later fixture.

**Comment by mbukatov** [comment]
@RazTamir  Is it a bug or a feature in this particular case? :)

**Comment by RazTamir** [comment]
Neither.
just slight alignment on that and you'll have rbd_sc_obj and fs_sc_ob

**Comment by ramkiperiy** [comment]
I had this situation in my test case automation. Have tried something like below which worked.

    @pytest.fixture()
    def storageclass(self, storageclass_factory):
        """
        Create Storage class for rbd and cephfs
        """
        self.rbd_sc_obj = storageclass_factory(interface=constants.CEPHBLOCKPOOL)
        self.cephfs_sc_obj = storageclass_factory(interface=constants.CEPHFILESYSTEM)

**Comment by vasukulkarni** [comment]
Closing stale issue.

**Comment by mbukatov** [comment]
> Closing stale issue.

Brief look in `tests/fixtures.py` reveals that this hasn't been addressed.
