### ISSUE TITLE
Registry.svc is deprecated

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#4172]
I see here:
https://github.com/red-hat-storage/ocs-ci/blob/6ecc96ca640e96448a16e2271f5553a7a6248c12/conf/ocsci/flexy_baremetalpsi_upi.yaml#L10

We still have defined deprecated registry:
`registry.svc.ci.openshift.org` it should be renamed to: `registry.ci.openshift.org`.

@shylesh can you please check, update?

**Comment by mbukatov** [comment]
Besides that, I also see these references to `svc.ci`:
```
$ rg svc.ci
ocs_ci/utility/utils.py
571:            f"https://openshift-release.svc.ci.openshift.org/api/v1/"
851:        "https://openshift-release-artifacts.svc.ci.openshift.org/"

ocs_ci/framework/conf/default_config.yaml
41:  # ocp_url_template: "https://openshift-release-artifacts.svc.ci.openshift.org/{version}/{file_name}-{os_type}-{version}.tar.gz"
```

**Comment by petr-balogh** [comment]
> Besides that, I also see these references to `svc.ci`:
> 
> ```
> $ rg svc.ci
> ocs_ci/utility/utils.py
> 571:            f"https://openshift-release.svc.ci.openshift.org/api/v1/"
> 851:        "https://openshift-release-artifacts.svc.ci.openshift.org/"
> 
> ocs_ci/framework/conf/default_config.yaml
> 41:  # ocp_url_template: "https://openshift-release-artifacts.svc.ci.openshift.org/{version}/{file_name}-{os_type}-{version}.tar.gz"
> ```

@mbukatov I saw the email about deprecating only registry (registry.svc.ci.openshift.org), not the other services under this svc.ci .

Email:
https://mailman-int.corp.redhat.com/archives/aos-devel/2021-February/msg00057.html

Other services like  openshift-release-artifacts.svc.ci.openshift.org still works well.
