### ISSUE TITLE
Some scale tests should record information in the es database.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#4185]
tests/e2e/scale/test_osd_node_balancing.py produces some output that can be stored in the es database and reports should be generated from there.

**Comment by ramkiperiy** [comment]
Closing this issue since PR is already merged. 
here is the TC https://github.com/red-hat-storage/ocs-ci/blob/master/tests/e2e/scale/test_osd_node_balancing.py
