### ISSUE TITLE
OSDs sometimes do not evenly balance, even with topology constraint values set.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#4186]
Scenario:
3 Worker nodes with an OSD on each node.

Storage capacity is increased (adds OSD to each node)
Storage capacity is increased again (adds another OSD to each node)

At this point, there are 3 nodes with 3 OSDs on each.

Now 3 new worker nodes are added.
Storage capacity is increased (adds OSD to each node) -- do this 3 times

At this point there are 6 nodes with 3 OSDs each

Now 3 new worker nodes are added.
Storage capacity is increased (again 3 times)

At this point there should be 9 nodes with 3 OSDs each.

This sometimes works.  However, on some occasions, there are OSDs added to the nodes with 3 OSDs on them.
The information below was taken from a case where this happened when the number of Nodes went from 6 to 9.
The first increase in nodes resulted in the imbalance noted.

If you look at this data, after a balanced set of 6 nodes with 18 osds was achieved, 3 new nodes were added.  When the
number of OSDs were increased to 21, one of nodes with three OSDs got a fourth OSD, (ip-10-0-219-150.us-east-2.compute.internal), and one of the new nodes did not have any (ip-10-0-158-100.us-east-2.compute.internal).

The pod information seems to indicate that we should be balancing on hostname toplogyKey values (which I assume are nodes):

topologySpreadConstraints:
  - labelSelector:
      matchExpressions:
      - key: ceph.rook.io/pvc
        operator: Exists
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway

(venv) wusui@localhost:~/ocs-ci$ oc -n openshift-storage get pod -o wide | grep rook-ceph-osd | grep -v prepare 
rook-ceph-osd-0-65f75cc6bc-nrjvn                                  2/2     Running     0          8h      10.129.2.24    ip-10-0-168-147.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-6b9bfbf876-v7pfz                                  2/2     Running     0          8h      10.131.0.26    ip-10-0-134-5.us-east-2.compute.internal     <none>           <none>
rook-ceph-osd-10-69d5c5445c-k66l7                                 2/2     Running     0          4h10m   10.131.2.8     ip-10-0-137-46.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-11-64fc865fcd-kbd75                                 2/2     Running     0          4h9m    10.130.2.10    ip-10-0-187-254.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-12-665cd686cf-zhn54                                 2/2     Running     0          4h4m    10.130.2.13    ip-10-0-187-254.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-13-64456b549c-76d72                                 2/2     Running     0          4h4m    10.128.4.11    ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-14-5cfd79f7d7-44c2h                                 2/2     Running     0          4h4m    10.131.2.10    ip-10-0-137-46.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-15-7689c74958-qbd5k                                 2/2     Running     0          3h59m   10.130.2.19    ip-10-0-187-254.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-16-669d7d74b9-5nxrm                                 2/2     Running     0          3h59m   10.128.4.14    ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-17-5f8747fb75-zk57w                                 2/2     Running     0          3h59m   10.131.2.12    ip-10-0-137-46.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-18-66cb77d46c-d2vk5                                 2/2     Running     0          3h43m   10.128.4.16    ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-19-5478598867-t4ldf                                 2/2     Running     0          3h43m   10.131.4.9     ip-10-0-140-53.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-2-6588448759-cmn8h                                  2/2     Running     0          8h      10.128.2.20    ip-10-0-197-253.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-20-8546c4668f-x5xjv                                 2/2     Running     0          3h43m   10.129.4.10    ip-10-0-169-154.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-3-55466fd86f-vjgks                                  2/2     Running     0          4h29m   10.128.2.98    ip-10-0-197-253.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-4-5cd7899d56-5f6wv                                  2/2     Running     0          4h29m   10.131.0.55    ip-10-0-134-5.us-east-2.compute.internal     <none>           <none>
rook-ceph-osd-5-696c984875-pfh5x                                  2/2     Running     0          4h29m   10.129.2.30    ip-10-0-168-147.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-6-556ff59d87-hhpfh                                  2/2     Running     0          4h24m   10.128.2.102   ip-10-0-197-253.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-7-6996ccfcc6-9jq7p                                  2/2     Running     0          4h24m   10.131.0.57    ip-10-0-134-5.us-east-2.compute.internal     <none>           <none>
rook-ceph-osd-8-6b5756dbf6-brrq2                                  2/2     Running     0          4h24m   10.129.2.32    ip-10-0-168-147.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-9-56d98db8dc-b6gnr                                  2/2     Running     0          4h10m   10.128.4.9     ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
(venv) wusui@localhost:~/ocs-ci$ 
(venv) wusui@localhost:~/ocs-ci$ oc get nodes | grep worker
ip-10-0-134-5.us-east-2.compute.internal     Ready    worker   9h      v1.20.0+7d0a2b2
ip-10-0-137-46.us-east-2.compute.internal    Ready    worker   4h15m   v1.20.0+7d0a2b2
ip-10-0-140-53.us-east-2.compute.internal    Ready    worker   3h46m   v1.20.0+7d0a2b2
ip-10-0-158-100.us-east-2.compute.internal   Ready    worker   3h49m   v1.20.0+7d0a2b2
ip-10-0-168-147.us-east-2.compute.internal   Ready    worker   9h      v1.20.0+7d0a2b2
ip-10-0-169-154.us-east-2.compute.internal   Ready    worker   3h52m   v1.20.0+7d0a2b2
ip-10-0-187-254.us-east-2.compute.internal   Ready    worker   4h18m   v1.20.0+7d0a2b2
ip-10-0-197-253.us-east-2.compute.internal   Ready    worker   9h      v1.20.0+7d0a2b2
ip-10-0-219-150.us-east-2.compute.internal   Ready    worker   4h12m   v1.20.0+7d0a2b2
(venv) wusui@localhost:~/ocs-ci$ 
(venv) wusui@localhost:~/ocs-ci$ 
(venv) wusui@localhost:~/ocs-ci$ 
(venv) wusui@localhost:~/ocs-ci$ oc -n openshift-storage get pod -o wide | grep rook-ceph-osd | grep -v prepare | grep ip-10-0-219-150
rook-ceph-osd-13-64456b549c-76d72                                 2/2     Running     0          4h5m    10.128.4.11    ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-16-669d7d74b9-5nxrm                                 2/2     Running     0          4h      10.128.4.14    ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-18-66cb77d46c-d2vk5                                 2/2     Running     0          3h44m   10.128.4.16    ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-9-56d98db8dc-b6gnr                                  2/2     Running     0          4h11m   10.128.4.9     ip-10-0-219-150.us-east-2.compute.internal   <none>           <none>
(venv) wusui@localhost:~/ocs-ci$ oc -n openshift-storage get pod -o wide | grep rook-ceph-osd | grep -v prepare | grep ip-10-0-158-100

**Comment by ramkiperiy** [comment]
PR is already merged https://github.com/red-hat-storage/ocs-ci/pull/4133, closing this issue
