### ISSUE TITLE
Add signed-off check for commit message in CI

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#419]

**Comment by vasukulkarni** [comment]
Something similar to https://github.com/ceph/ceph-build/blob/master/ceph-pr-commits/config/definitions/ceph-pr-commits.yml#L52-L65

**Comment by zmc** [comment]
https://github.com/probot/dco ?

**Comment by zmc** [comment]
I've installed DCO on the project

**Comment by mbukatov** [comment]
Would you also update the [documentation of ocs-ci project](https://github.com/red-hat-storage/ocs-ci/tree/master/docs) and explain:

* what is the meaning of "sing off" entries in our project exactly
* how to use it

**Comment by gklein** [comment]
> Would you also update the [documentation of ocs-ci project](https://github.com/red-hat-storage/ocs-ci/tree/master/docs) and explain:
> 
> * what is the meaning of "sing off" entries in our project exactly (you probably have the meaning explained in https://probot.github.io/apps/dco/ in mind, but without stating that clearly in the project docs and making sure everyone working on the project understands that, sing off itself is meaningless)
> * how to use it

Should be addressed by https://github.com/red-hat-storage/ocs-ci/pull/1031

**Comment by gklein** [comment]
@mbukatov Can we close this issue based on the recent [PR](https://github.com/red-hat-storage/ocs-ci/pull/1031) that made it in?

**Comment by mbukatov** [comment]
I guess so.
