### ISSUE TITLE
UnexpectedBehaviour during PVC creation error

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#4201]
Full log: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/559/testReport/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_all_4_type_pvc_creation_deletion_scale/

logging.info("Waited for more than 3mins still no data")
>                   raise UnexpectedBehaviour(
                        f"There is no pvc creation data in CSI logs for {no_data_list}"
                    )

**Comment by ramkiperiy** [comment]
We have existing issue Scale: TestPVCCreationDeletionScale.test_all_4_type_pvc_creation_deletion_scale failed to measure creation time #4042 Closing this issue as duplicate
