### ISSUE TITLE
Verification steps for node_replacement_verification_steps_user_side  need's improvement 

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#4207]
If it's dynamic cluster osd can move across rack labeled node only 

eg:- rook-ceph-osd-0-56bdd5dd45-289sq was on compute-5 and now moved to compute-1(old_node)

as per code it's expected that it should move to new node only 

The osd pod, that associated to the new node, has the id 10 instead of the expected osd id 0

oc get pods :- http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j029vuf1cs36-t4a/j029vuf1cs36-t4a_20210420T223455/logs/failed_testcase_ocs_logs_1618962810/test_nodereplacement_proactive_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-0c61617e2ae8d332167ab4bc86dfa9e7b74e002a8c344eee25700ea2069df6a0/namespaces/openshift-storage/oc_output/pods_-owide

oc get nodes :- http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j029vuf1cs36-t4a/j029vuf1cs36-t4a_20210420T223455/logs/failed_testcase_ocs_logs_1618962810/test_nodereplacement_proactive_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-0c61617e2ae8d332167ab4bc86dfa9e7b74e002a8c344eee25700ea2069df6a0/cluster-scoped-resources/oc_output/get_nodes_-o_wide_--show-labels

console logs :- https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/481/consoleFull

**Comment by yitzhak12** [comment]
@prsurve Do you want to assign the issue to me, or will you handle it?
