### ISSUE TITLE
test_multiple_sc_comp_rep_data_deletion fails in tier 2 runs

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#4226]
The test [test_multiple_sc_comp_rep_data_delete](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py) has been failing in the recent tier 2 runs with the following error message:

```E                   ocs_ci.ocs.exceptions.PoolDataNotErased: Pool cbp-test-a289ae73f26d486793a00d180ba45fc has 3226927104 bytes which were not deleted```

The cause of failure is still unknown. The test case passed when run individually and the data was erased from the cephblockpool.
Creating this issue to track the failure and for further investigation.

Runs in which the test failed:
---------------------------------------
ocs-ci results for OCS4-8-Downstream-OCP4-8-VSPHERE-UPI-1AZ-RHCOS-VSAN-3M-3W-tier2 (BUILD ID: v4.8.0-357.ci RUN ID: 1619278639)
ocs-ci results for OCS4-7-Downstream-OCP4-7-VSPHERE-UPI-1AZ-RHCOS-VSAN-3M-3W-tier2 (BUILD ID: v4.7.0-360.ci RUN ID: 1619202240)
ocs-ci results for OCS4-8-Downstream-OCP4-8-VSPHERE-UPI-1AZ-RHCOS-VSAN-3M-3W-tier2 (BUILD ID: v4.8.0-354.ci RUN ID: 1618709702)
ocs-ci results for OCS4-8-Downstream-OCP4-8-AWS-IPI-3AZ-RHCOS-3M-3W-tier2 (BUILD ID: v4.8.0-350.ci RUN ID: 1618504169)
ocs-ci results for OCS4-7-Downstream-OCP4-7-VSPHERE-UPI-1AZ-RHCOS-VSAN-3M-3W-tier2 (BUILD ID: v4.7.0-344.ci RUN ID: 1618294537)

**Comment by jilju** [comment]
This issue is not resolved. Observed the failure in RUN ID: 1644956070.
```
                if ceph_pool_byte_used > MAX_BYTES_IN_POOL_AFTER_DATA_DELETE:
>                   raise PoolDataNotErased(
                        f"Pool {cbp_name} has {ceph_pool_byte_used} bytes which were not deleted"
                    )
E                   ocs_ci.ocs.exceptions.PoolDataNotErased: Pool cbp-test-7ee46a3a05344e2496f252d1cb7428c has 1622556672 bytes which were not deleted

tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py:107: PoolDataNotErased
```

**Comment by Sravikaz** [comment]
This issue is not resolved , also observed on s390x with the latest odf build` 4.12.0-130`.
The pool data erasing time is higher than the timeout value ocs-ci has.


```

 for sc_obj in sc_obj_list:
            pvc_list = get_all_pvcs_in_storageclass(sc_obj.name)
            if len(pvc_list) == 0:
                cbp_name = sc_obj.get()["parameters"]["pool"]
                ceph_pool_byte_used = get_byte_used_by_pool(cbp_name)
                log.info(f"pool {cbp_name} has {ceph_pool_byte_used} bytes used")
                if ceph_pool_byte_used > MAX_BYTES_IN_POOL_AFTER_DATA_DELETE:
>                   raise PoolDataNotErased(
                        f"Pool {cbp_name} has {ceph_pool_byte_used} bytes which were not deleted"
                    )
E                   ocs_ci.ocs.exceptions.PoolDataNotErased: Pool cbp-test-fe1a95ba13c3493eb873f63ff3066bb has 1621454380 bytes which were not deleted

tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py:107: PoolDataNotErased
```

`ocs_ci.ocs.exceptions.PoolDataNotErased: Pool cbp-test-fe1a95ba13c3493eb873f63ff3066bb has 1621454380 bytes which were not deleted`

**Comment by rachael-george** [comment]
Observed this in run: ocs-ci results for OCS4-12-Downstream-OCP4-12-BAREMETAL-UPI-1AZ-RHCOS-NVME-INTEL-COMPACT-MODE-3M-0W-tier2 (BUILD ID: 4.12.0-122 RUN ID: 1669980540)

**Comment by jilju** [comment]
@sidhant-agrawal @keemano The wait time given is 15 seconds. Can we try increasing the wait time as a work around ?

**Comment by keemano** [comment]
> @sidhant-agrawal @keemano The wait time given is 15 seconds. Can we try increasing the wait time as a work around ?

Yes, we can try

**Comment by keemano** [comment]
Hitting the issue again in 4.12.6. 

Logs - http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-047vi1cs33-t2/j-047vi1cs33-t2_20230808T054622/logs/

Report Portal Link - https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/13364/608898/609063/609064/log

Run ID - 1691477861
