### ISSUE TITLE
Add an option to run IO in the background during tests execution

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#423]
Thinking about creating a session scope fixture in conftest.py that will create a pod and run FIO during the entire test execution

**Comment by hnallurv** [comment]
Couple of things to consider:
1) This should have facility to run (all or selected) OCS supported workloads and fio.
2) Should be able to verify the data integrity (before and after a certain operation)
3) Should be able to run IOs for a certain time and also throughout the test (without time restriction)

**Comment by ebenahar** [comment]
Thanks @hnallurv 
Created https://github.com/red-hat-storage/ocs-ci/pull/426
For now, as an MVP, FIO is being used

**Comment by ebenahar** [comment]
Closed with https://github.com/red-hat-storage/ocs-ci/pull/426
