### ISSUE TITLE
Teardown failure to clean up PVC created in TC test_pods_are_not_oomkilled_while_running_ios[CephFileSystem] 

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#4234]
Failed in teardown due to resource left-over, there is a PVC left over in the cluster, it's strange that not observing this problem when executing the test separately also  PVC is created using factory so need more debug to resolve this issue.

Test run: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/638/
Test case: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/638/testReport/junit/tests.e2e.scale.test_pods_are_not_oomkilled_while_running_ios/TestPodAreNotOomkilledWhileRunningIO/test_pods_are_not_oomkilled_while_running_ios_CephFileSystem_/

Failure:
`Error Message

test teardown failure

Stacktrace

exclude_labels = ['must-gather']

    def get_status_after_execution(exclude_labels=None):
        """
        Set the environment status and assign it into ENV_STATUS_PRE dictionary.
        In addition compare the dict before the execution and after using DeepDiff
    
        Args:
            exclude_labels (list): App labels to ignore leftovers
    
        Raises:
             ResourceLeftoversException: In case there are leftovers in the
                environment after the execution
        """
        get_environment_status(ENV_STATUS_POST, exclude_labels=exclude_labels)
    
        pod_diff = compare_dicts(ENV_STATUS_PRE["pod"], ENV_STATUS_POST["pod"])
        sc_diff = compare_dicts(ENV_STATUS_PRE["sc"], ENV_STATUS_POST["sc"])
        cephfs_diff = compare_dicts(ENV_STATUS_PRE["cephfs"], ENV_STATUS_POST["cephfs"])
        cephbp_diff = compare_dicts(ENV_STATUS_PRE["cephbp"], ENV_STATUS_POST["cephbp"])
        pv_diff = compare_dicts(ENV_STATUS_PRE["pv"], ENV_STATUS_POST["pv"])
        pvc_diff = compare_dicts(ENV_STATUS_PRE["pvc"], ENV_STATUS_POST["pvc"])
        namespace_diff = compare_dicts(
            ENV_STATUS_PRE["namespace"], ENV_STATUS_POST["namespace"]
        )
        diffs_dict = {
            "pods": pod_diff,
            "storageClasses": sc_diff,
            "cephfs": cephfs_diff,
            "cephbp": cephbp_diff,
            "pvs": pv_diff,
            "pvcs": pvc_diff,
            "namespaces": namespace_diff,
        }
        leftover_detected = False
    
        leftovers = {"Leftovers added": [], "Leftovers removed": []}
        for kind, kind_diff in diffs_dict.items():
            if not kind_diff:
                continue
            if kind_diff[0]:
                leftovers["Leftovers added"].append({f"***{kind}***": kind_diff[0]})
                leftover_detected = True
            if kind_diff[1]:
                leftovers["Leftovers removed"].append({f"***{kind}***": kind_diff[1]})
                leftover_detected = True
        if leftover_detected:
>           raise exceptions.ResourceLeftoversException(
                f"\nThere are leftovers in the environment after test case:"
                f"\nResources added:\n{yaml.dump(leftovers['Leftovers added'])}"
                f"\nResources "
                f"removed:\n {yaml.dump(leftovers['Leftovers removed'])}"
            )
E           ocs_ci.ocs.exceptions.ResourceLeftoversException: 
E           There are leftovers in the environment after test case:
E           Resources added:
E           []
E           
E           Resources removed:
E            - '***pvs***':
E             - apiVersion: v1
E               kind: PersistentVolume
E               metadata:
E                 annotations:
E                   pv.kubernetes.io/provisioned-by: openshift-storage.cephfs.csi.ceph.com
E                 creationTimestamp: '2021-04-29T08:27:31Z'
E                 finalizers:
E                 - kubernetes.io/pv-protection
E                 managedFields:
E                 - apiVersion: v1
E                   fieldsType: FieldsV1
E                   fieldsV1:
E                     f:metadata:`

**Comment by ramkiperiy** [comment]
We didn't see this problem in any of the recent execution runs, reducing the priority to fix.

**Comment by ramkiperiy** [comment]
Based on 4.9 test executions we should plan to close this or fix the problem

**Comment by tiffanyn108** [comment]
Issue has seen with recent scale run: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/113/2779/116954/116960

raise exceptions.ResourceLeftoversException(
            f"\nThere are leftovers in the environment after test case:"
            f"\nResources added:\n{yaml.dump(leftovers['Leftovers added'])}"
            f"\nResources "
            f"removed:\n {yaml.dump(leftovers['Leftovers removed'])}"
        )
E           ocs_ci.ocs.exceptions.ResourceLeftoversException:
E           There are leftovers in the environment after test case:
E           Resources added:
E           []
E
E           Resources removed:
E            - 'pvs':
E             - apiVersion: v1
E               kind: PersistentVolume
E               metadata:
E                 annotations:
E                   pv.kubernetes.io/provisioned-by: openshift-storage.cephfs.csi.ceph.com
E                 creationTimestamp: '2022-04-29T12:37:27Z'
E                 finalizers:
E                 - kubernetes.io/pv-protection
E                 name: pvc-8c93e0b2-5d30-4d64-a345-57f3362506fe
E                 resourceVersion: '45904'
E                 uid: d217d7e8-fc51-40f6-a9be-47ed888a43d6
E               spec:
E                 accessModes:
E                 - ReadWriteOnce
E                 capacity:
E                   storage: 20Gi
E                 claimRef:
E                   apiVersion: v1
E                   kind: PersistentVolumeClaim
E                   name: cephfs-pvc58e8bcf0-30ce-4338-a816-faf08880b5cf
E                   namespace: openshift-storage
E                   resourceVersion: '45896'
E                   uid: 8c93e0b2-5d30-4d64-a345-57f3362506fe
E                 csi:
E                   controllerExpandSecretRef:
E                     name: rook-csi-cephfs-provisioner
E                     namespace: openshift-storage
E                   driver: openshift-storage.cephfs.csi.ceph.com
E                   nodeStageSecretRef:
E                     name: rook-csi-cephfs-node
E                     namespace: openshift-storage
E                   volumeAttributes:
E                     clusterID: openshift-storage
E                     fsName: ocs-storagecluster-cephfilesystem
E                     storage.kubernetes.io/csiProvisionerIdentity: 1651234799825-8081-openshift-storage.cephfs.csi.ceph.com
E                     subvolumeName: csi-vol-209fa384-c7b9-11ec-97b2-0a580a830018
E                     subvolumePath: /volumes/csi/csi-vol-209fa384-c7b9-11ec-97b2-0a580a830018/4bde0340-5842-4f56-b652-5e407bc3c7fb
E                   volumeHandle: 0001-0011-openshift-storage-0000000000000001-209fa384-c7b9-11ec-97b2-0a580a830018
E                 persistentVolumeReclaimPolicy: Delete
E                 storageClassName: ocs-storagecluster-cephfs
E                 volumeMode: Filesystem
E               status:
E                 phase: Bound



ocs_ci/utility/environment_check.py:206: ResourceLeftoversException
