### ISSUE TITLE
Convert existing tests in manage to use new fixtures 

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#425]
I know there are quiet a few, I will try to take one or 2 and raise PR too.

**Comment by clacroix12** [comment]
Should we wait for #418 before really getting started on converting other test cases? I think we would save a lot of effort if the basic set of shareable fixtures was in place before converting everything.

**Comment by vasukulkarni** [comment]
Sure, makes sense to wait for #418, once that is finalized for some use cases we could reuse them.

**Comment by vasukulkarni** [comment]
Closing stale issue.
