### ISSUE TITLE
Scale test  fails on baremetal as it is unsupported to add new worker nodes to scale up the cluster

### ISSUE THREAD

**Issue by Sravikaz** [red-hat-storage/ocs-ci#4251]
**Description:**

Scale test "tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py" fails on the baremetal with the following error 

`E               ocs_ci.ocs.exceptions.UnsupportedPlatformError: Unsupported Platform to add worker
`

Following condition is hit during the test execution:

**ocs_ci/ocs/scale_lib.py**

```
elif (
	 config.ENV_DATA["deployment_type"] == "upi"
	            and config.ENV_DATA["platform"].lower() == "baremetal"
	        ):
	            raise UnsupportedPlatformError("Unsupported Platform to add worker")
```

[test_pv_scale_out_create_pvcs_and_respin_ceph_pods_mgr.zip](https://github.com/red-hat-storage/ocs-ci/files/6419983/test_pv_scale_out_create_pvcs_and_respin_ceph_pods_mgr.zip)

Test Description: Test case to scale PVC+POD with multi projects and reach expected PVC count 

**Expected Result:**

On baremetal (based on platform) include a check such that this test needs to be run on an already scaled-up cluster.

**Comment by ramkiperiy** [comment]
@Sravikaz There is WA to continue the execution of this Test in BM platform.
Scale tests will try to find nodes labelled with scale label and if there is enough nodes with that label test will not try to add more nodes. i.e. scale test will continue to use the labelled nodes to scale app pods and continue the test.

In-case of scale label is not present code will try to add more nodes to the cluster again this feature needs support to add more nodes, and especially we don't support for adding nodes in any UPI platforms but for IPI we have support in AWS, Azure, RHV, (vmware in-progress).

As I mentioned above still we can execute the scale tests in unsupported platforms by adding the scale label in the nodes, i.e. code just checks if there is enough scale labelled nodes in cluster before proceeding to add more workers. if there is enough nodes adding more worker nodes will be skipped. For the count how many nodes required with scale label please refer "SCALE_WORKER_DICT" in https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py#L1164 , please note the scale PVC count here based on the PVC count there should be enough labelled nodes. 

Scale label can be found here https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py#L1153

**Comment by ramkiperiy** [comment]
@Sravikaz hope above comment helps to WA the problem, and would request to close this issue if it solved the problem. Adding enhancement to support BM IPI will solve the problem but again this required lot of work in OCP
