### ISSUE TITLE
Teardown can fail on problem with openshift-release API

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#4261]
I started a teardown and it failed on a problem related to communication with openshift release API:

```
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openshift-release.apps.ci.l2s4.p1.openshiftapps.com', port=443): Max retries exceeded with url: /api/v1/releasestream/4.7.0-0.nightly/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbbb415ffd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

This kind of issue should not happen during teardown. Why is ocs-ci try to communicate with  `openshift-release.apps.ci.l2s4.p1.openshiftapps.com` during teardown? I don't believe there is a valid reason for this to be happening during teardown. Moreover it makes teardown more prone to failure, which is not a good thing considering a cleanup issues it can cause.

**Comment by petr-balogh** [comment]
It's related to this issue https://github.com/red-hat-storage/ocs-ci/issues/4231 so we can maybe close this and fix as part of mentioned. WDYT @mbukatov

**Comment by mbukatov** [comment]
@petr-balogh Agreed. Thanks for looking into the issue.
