### ISSUE TITLE
fix nodes labeling in test_delete_pod.py::TestAddCapacityWithResourceDelete::test_add_capacity_with_resource_delete

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#4289]
1. in test setup, need to add validation that all nodes have `cluster.ocs.openshift.io/openshift-storage` label (if cluster contains more than 3 worker nodes)
2. in test teardown, need to remove this extra labels from nodes other than first 3 workers

**Comment by AviadP** [comment]
reopening it for this test: `TestAddCapacityWithResourceDelete.test_add_capacity_with_resource_delete[workload_storageutilization_rbd0-osd-0-False]`

logs are here: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1170/

**Comment by yitzhak12** [comment]
I think we can take the fixture here https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/cluster_expansion/test_delete_pod.py#L32 and export it to the conftest file `tests/manage/z_cluster/cluster_expansion/conftest.py`. Then we can use this fixture in all the "add capacity" tests.

**Comment by ebenahar** [comment]
> I think we can take the fixture here https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/cluster_expansion/test_delete_pod.py#L32 and export it to the conftest file `tests/manage/z_cluster/cluster_expansion/conftest.py`. Then we can use this fixture in all the "add capacity" tests.

+1
