### ISSUE TITLE
Deployment failure - error configuring storage for image registry

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#4320]
Deployment is failing on baremetal with the below error.
```
09:50:38 - MainThread - ocs_ci.deployment.baremetal - INFO - configuring storage for image registry
09:50:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig patch configs.imageregistry.operator.openshift.io cluster --type merge --patch  '{"spec":{"storage":{"emptyDir":{}}}}' 
09:50:38 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): configs.imageregistry.operator.openshift.io "cluster" not found

09:50:38 - MainThread - ocs_ci.deployment.deployment - ERROR - Error during execution of command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig patch configs.imageregistry.operator.openshift.io cluster --type merge --patch  '{"spec":{"storage":{"emptyDir":{}}}}' .
Error is Error from server (NotFound): configs.imageregistry.operator.openshift.io "cluster" not found
```
Similar to https://github.com/red-hat-storage/ocs-ci/issues/3013

**Comment by petr-balogh** [comment]
@jilju is this temp issue happening from time to time or permanent blocker issue?  @prsurve have you seen this before in BM deployment?

**Comment by jilju** [comment]
> @jilju is this temp issue happening from time to time or permanent blocker issue? @prsurve have you seen this before in BM deployment?

@petr-balogh This issue is not consistent. I see this 2 times in last 4 deployment attempts I did.

**Comment by petr-balogh** [comment]
> > @jilju is this temp issue happening from time to time or permanent blocker issue? @prsurve have you seen this before in BM deployment?
> 
> @petr-balogh This issue is not consistent. I saw this 2 times in last 4 deployment attempts I did.

Thanks for clarification @jilju !
