### ISSUE TITLE
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#4352]
Execution of `run-ci` recently failed on Mac with following error:
```
ImportError while loading conftest '/Users/pbalogh/Code/OCS/ocs-ci/tests/conftest.py'.
tests/conftest.py:16: in <module>
    from ocs_ci.deployment import factory as dep_factory
ocs_ci/deployment/factory.py:13: in <module>
    from .rhv import RHVIPI
ocs_ci/deployment/rhv.py:10: in <module>
    from ocs_ci.utility.rhv import RHV as RHVUtil
ocs_ci/utility/rhv.py:8: in <module>
    import ovirtsdk4 as sdk
.venv/lib/python3.9/site-packages/ovirtsdk4/__init__.py:22: in <module>
    import pycurl
E   ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)
```
We should investigate it more (if it is only issue on Mac OS or if it might occur also on CentOS or Fedora) and try to find better fix than following workaround:
```
pip uninstall pycurl
pip install --compile --install-option="--with-openssl" pycurl
```

**Comment by tiffanyn108** [comment]
I ran into semilar issue on mac env.  
``` ImportError while loading conftest '/Users/tunguyen/OCS/fork/ocs-ci/tests/conftest.py'.
tests/conftest.py:24: in <module>
    from ocs_ci.ocs import constants, defaults, fio_artefacts, node, ocp, platform_nodes
ocs_ci/ocs/platform_nodes.py:11: in <module>
    import ovirtsdk4.types as types
../../myenv/lib/python3.9/site-packages/ovirtsdk4/__init__.py:22: in <module>
    import pycurl
E   ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other) ```

With workaround below works for my env.
``` pip3 uninstall pycurl
 export PYCURL_SSL_LIBRARY=openssl
 pip3 install pycurl --no-cache-dir ```

**Comment by clacroix12** [comment]
Similar to what @tiffanyn108 had to do, on OSX i needed to export a couple more env vars before I was able to get pycurl installed using openssl correctly:

```bash
pip uninstall pycurl
export PYCURL_SSL_LIBRARY=openssl
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
pip install pycurl --compile --no-cache-dir
```

**Comment by mbukatov** [comment]
>  We should investigate it more (if it is only issue on Mac OS or if it might occur also on CentOS or Fedora) and try to find better fix than following workaround:

This is a build problem. If we expect OSX users to install ocs-ci as noted in the docs from source via pip, we may need to improve installation instructions for them to use system installed libraries.

Slightly related: it would make sense to select single base system (eg. Fedora, RHEL) so that we could reuse all core libraries provided by the os, without any need to compile basic stuff like xml or openssl python wrappers during installation. But that would require one to use ocs-ci in a vm or container with the selected os.

**Comment by ramkiperiy** [comment]
Thanks @sidhant-agrawal for pointing to this url https://stackoverflow.com/questions/47888757/importerror-pycurl-libcurl-link-time-ssl-backend-openssl-is-different-from-c/70914890#70914890

For M1 mac chip following WA helped

_brew install curl-openssl
pip uninstall pycurl

PYCURL_SSL_LIBRARY=openssl \
    LDFLAGS="-L$(brew --prefix openssl)/lib" \
    CPPFLAGS="-I$(brew --prefix openssl)/include" 

pip install --compile --install-option="--with-openssl" pycurl_

**Comment by avd-sagare** [comment]
Below solution worked for my  Macbook pro  having chip- Apple M1 Pro and macOS - 13.4.1 (22F82)

pip3 uninstall pycurl  
brew install curl-openssl
export PYCURL_SSL_LIBRARY=openssl
pip3 install --no-cache-dir --ignore-installed --compile pycurl
