### ISSUE TITLE
Remove workaround: Rook mon crashloop and pod disappearance

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#438]
When original issue is fixed (TODO: add tracker reference for the original issue), revert commit bcfde8e28f3d0e907a097c7c4569b9effc203dbe introducing the workaround (via https://github.com/red-hat-storage/ocs-ci/pull/433).

**Comment by MeridianExplorer** [comment]
PARTIAL REMOVAL: rook-ceph image was restored to master via #445.
Namespace remains 'rook-ceph'.

**Comment by mbukatov** [comment]
@red-hat-storage/top-level-reviewers please make sure that this issue is updated as needed

**Comment by ebenahar** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/445/files is merged

**Comment by mbukatov** [comment]
> PARTIAL REMOVAL: rook-ceph image was restored to master via #445.
> Namespace remains 'rook-ceph'.

Removal of namespace hack tracked in #469

**Comment by mbukatov** [comment]
> #445 is merged

This hasn't been resolved, namespace is still set to `rook-ceph` as Ben notes above.

**Comment by mbukatov** [comment]
Namespace revert is proposed in #470.

**Comment by mbukatov** [comment]
Namespace is "openshift-storage" again, since commit f1906b5139cc8bdd58f1a3411cdcdf2e818a7ece.
