### ISSUE TITLE
Separate out requirements for RHV/Azure/Nova

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#4380]
Some of the setup.py dependency might not be required for regular users on AWS and vSphere, we could separate them out and keep it smaller for faster local testing.

**Comment by petr-balogh** [comment]
@vasukulkarni I am opening this draft PR:  https://github.com/red-hat-storage/ocs-ci/pull/4437/files
This is not fixing the installed dependencies but partially it fixing the issue with the imports from conftest.py which is currently loading all the modules.  This will then load just required modules for specific platform.  If we will change the requirements per platform, it will require much more changes and all such imports of the modules can lead to the issues if it's not covered in conditions.   Do we really want to separate those? @clacroix12 @shylesh @dahorak @vavuthu @jimdevops19 , please add your input.

**Comment by shylesh** [comment]
> @vasukulkarni I am opening this draft PR: https://github.com/red-hat-storage/ocs-ci/pull/4437/files
> This is not fixing the installed dependencies but partially it fixing the issue with the imports from conftest.py which is currently loading all the modules. This will then load just required modules for specific platform. If we will change the requirements per platform, it will require much more changes and all such imports of the modules can lead to the issues if it's not covered in conditions. Do we really want to separate those? @clacroix12 @shylesh @dahorak @vavuthu @jimdevops19 , please add your input.

@petr-balogh , In the future when we have to support multicluster we might have to rearrange the imports as well in case if 2 cluster are deployed on heterogeneous platforms.

**Comment by vasukulkarni** [comment]
One more issue with libcurl pkg on rhel with venv

```
ImportError while loading conftest '/home/ypersky/ocs-ci/tests/conftest.py'.
tests/conftest.py:16: in <module>
    from ocs_ci.deployment import factory as dep_factory
ocs_ci/deployment/factory.py:13: in <module>
    from .rhv import RHVIPI
ocs_ci/deployment/rhv.py:10: in <module>
    from ocs_ci.utility.rhv import RHV as RHVUtil
ocs_ci/utility/rhv.py:8: in <module>
    import ovirtsdk4 as sdk
../.venv/lib/python3.8/site-packages/ovirtsdk4/__init__.py:22: in <module>
    import pycurl
E   ImportError: pycurl: libcurl link-time ssl backend (nss) is different from compile-time ssl backend (none/other)
(.venv) [ypersky@qpas ocs-ci]$
```

**Comment by petr-balogh** [comment]
@vasukulkarni do we really want to continue with this issue? As Shylesh wrote  about multi cluster support I think that it will just add complexity to our installation process.
