### ISSUE TITLE
VSPHEREIPINode class and class map required for the create_and_attach_nodes_to_cluster functionality

### ISSUE THREAD

**Issue by shylesh** [red-hat-storage/ocs-ci#4398]
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1025/console.
Above run failed with

=====================

tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/manage/z_cluster/cluster_expansion/conftest.py:85: in factory
    add_new_node_and_label_upi(
ocs_ci/ocs/node.py:386: in add_new_node_and_label_upi
    node_util.create_and_attach_nodes_to_cluster(node_conf, node_type, num_nodes)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.ocs.platform_nodes.VMWareNodes object at 0x7f4862628970>
node_conf = {}, node_type = 'RHCOS', num_nodes = 3

    def create_and_attach_nodes_to_cluster(self, node_conf, node_type, num_nodes):
        """
        Create nodes and attach them to cluster
        Use this function if you want to do both creation/attachment in
        a single call
    
        Args:
            node_conf (dict): of node configuration
            node_type (str): type of node to be created RHCOS/RHEL
            num_nodes (int): Number of node instances to be created
    
        """
>       node_cls = self.nodes_map[
            f"{self.platform.upper()}{self.deployment_type.upper()}Node"
        ]
E       KeyError: 'VSPHEREIPINode'

ocs_ci/ocs/platform_nodes.py:407: KeyError
=====================

we need VSPHEREIPINode class required in ocs_ci/ocs/platform_nodes.py for this to work

**Comment by prsurve** [comment]
@shylesh this pr has made the required changes https://github.com/red-hat-storage/ocs-ci/pull/4351 but this commit is not present in stable branch yet that's the reason test failed

**Comment by vavuthu** [comment]
re-opening this issue as it is still relevant
