### ISSUE TITLE
Please add ability to deploy ceph-csi based rook installation as part of ocs-ci

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#44]
Currently, the OCS-CI deploys OCP along with rook+ceph , which is flexvolume based.
Requesting to add an option for deploying rook based ceph-csi on similar OCP 4.x environment.  

The high-level steps for deployment will be: ( once an OCP cluster is UP)

cd /root/rook/cluster/examples/kubernetes/ceph
oc create -f common.yaml
oc apply -f ./csi/rbac/rbd/ ; oc apply -f ./csi/rbac/cephfs/
oc create -f operator-openshift-with-csi.yaml
oc create -f cluster.yaml
oc create -f toolbox.yaml
oc create -f filesystem.yaml
oc create -f object.yaml

-----------------------

cd ./csi/example/rbd
oc create -f pool.yaml  (copy pool.yaml from cluster/examples/kubernetes/ceph
oc create -f secret.yaml
oc create -f storageclass.yaml #make sure to edit base64 secret and rbd pool name
oc create -f pvc.yaml
oc create -f pod.yaml

CephFS -sc and security key creation
--------------------------------------
cd ./csi/example/cephfs
oc create -f secret.yaml
oc create -f storageclass.yaml #make sure to edit base64 secret and fs data pool name
oc create -f pvc.yaml
oc create -f pod.yaml

Thanks,
Neha

**Comment by vavuthu** [comment]
submitted PR #58 

Not handling of creation of mds since that needs to handle in test  cases

**Comment by vavuthu** [comment]
Closing the issue as PR #58 was merged.
