### ISSUE TITLE
mcg-cli status says noobaa-db service not found

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4415]
On ppc64le environment ; 

# oc version
Client Version: 4.8.0-0.nightly-ppc64le-2021-06-01-100250
Server Version: 4.8.0-0.nightly-ppc64le-2021-06-01-100250
Kubernetes Version: v1.21.0-rc.0+4b2b6ff
# 

# ./mcg-cli status -n openshift-storage
I0609 15:00:21.944294  488492 request.go:645] Throttling request took 1.032802505s, request: GET:https://api.nx123-48-5444.ibm.com:6443/apis/operator.openshift.io/v1alpha1?timeout=32s
INFO[0001] CLI version: 5.8.0                           
INFO[0001] noobaa-image: quay.io/rhceph-dev/mcg-core@sha256:68832b8afaf01e49f418e67cec1e3def3a86cd967f8ea6fa4728045484cfd69f 
INFO[0001] operator-image: quay.io/rhceph-dev/mcg-operator@sha256:f73d206c0e206ca9d83bd90d0a9c37a580bf94aca5819cba431876ad8f549e6c 
INFO[0001] noobaa-db-image: registry.redhat.io/rhel8/postgresql-12@sha256:03a1e02a1b3245f9aa0ddd3f7507b915a8f7387a1674969f6ef039a5d7fd8bf0 
INFO[0001] Namespace: openshift-storage                 
INFO[0001]                                              
INFO[0001] CRD Status:                                  
INFO[0001] ✅ Exists: CustomResourceDefinition "noobaas.noobaa.io" 
INFO[0001] ✅ Exists: CustomResourceDefinition "backingstores.noobaa.io" 
INFO[0001] ✅ Exists: CustomResourceDefinition "namespacestores.noobaa.io" 
INFO[0001] ✅ Exists: CustomResourceDefinition "bucketclasses.noobaa.io" 
INFO[0001] ✅ Exists: CustomResourceDefinition "objectbucketclaims.objectbucket.io" 
INFO[0001] ✅ Exists: CustomResourceDefinition "objectbuckets.objectbucket.io" 
INFO[0001]                                              
INFO[0001] Operator Status:                             
INFO[0001] ✅ Exists: Namespace "openshift-storage"      
INFO[0001] ✅ Exists: ServiceAccount "noobaa"            
INFO[0001] ✅ Exists: ServiceAccount "noobaa-endpoint"   
INFO[0001] ✅ Exists: Role "ocs-operator.v4.8.0-406.ci-noobaa-57f545b54" 
INFO[0001] ✅ Exists: Role "ocs-operator.v4.8.0-406.ci-noobaa-endpoint-7b65fb4775" 
INFO[0001] ✅ Exists: RoleBinding "ocs-operator.v4.8.0-406.ci-noobaa-57f545b54" 
INFO[0001] ✅ Exists: RoleBinding "ocs-operator.v4.8.0-406.ci-noobaa-endpoint-7b65fb4775" 
INFO[0001] ✅ Exists: ClusterRole "ocs-operator.v4.8.0-406.ci-7cc8d6b58d" 
INFO[0001] ✅ Exists: ClusterRoleBinding "ocs-operator.v4.8.0-406.ci-7cc8d6b58d" 
INFO[0001] ✅ Exists: Deployment "noobaa-operator"       
INFO[0001]                                              
INFO[0001] System Wait Ready:                           
INFO[0001] ✅ System Phase is "Ready".                   
INFO[0001]                                              
INFO[0001]                                              
INFO[0001] System Status:                               
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: StatefulSet "noobaa-core"          
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Service "s3"                       
INFO[0001] ✅ Exists: Secret "noobaa-db"                 
INFO[0001] ✅ Exists: StatefulSet "noobaa-db-pg"         
INFO[0001] ✅ Exists: Service "noobaa-db-pg"             
INFO[0001] ❌ Not Found: Service "noobaa-db"             
INFO[0001] ✅ Exists: Secret "noobaa-server"             
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-endpoints"          
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✅ Exists: Secret "noobaa-root-master-key"    
INFO[0001] ✅ Exists: StorageClass "openshift-storage.noobaa.io" 
INFO[0001] ✅ Exists: BucketClass "noobaa-default-bucket-class" 
INFO[0001] ✅ Exists: Deployment "noobaa-endpoint"       
INFO[0001] ✅ Exists: HorizontalPodAutoscaler "noobaa-endpoint" 
INFO[0001] ✅ (Optional) Exists: BackingStore "noobaa-default-backing-store" 
INFO[0001] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-aws-cloud-creds" 
INFO[0001] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-azure-cloud-creds" 
INFO[0001] ⬛ (Optional) Not Found: Secret "noobaa-azure-container-creds" 
INFO[0001] ⬛ (Optional) Not Found: Secret "noobaa-gcp-bucket-creds" 
INFO[0001] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-gcp-cloud-creds" 
INFO[0001] ✅ (Optional) Exists: PrometheusRule "noobaa-prometheus-rules" 
INFO[0001] ✅ (Optional) Exists: ServiceMonitor "noobaa-mgmt-service-monitor" 
INFO[0001] ✅ (Optional) Exists: ServiceMonitor "s3-service-monitor" 
INFO[0001] ✅ (Optional) Exists: Route "noobaa-mgmt"     
INFO[0001] ✅ (Optional) Exists: Route "s3"              
INFO[0001] ✅ Exists: PersistentVolumeClaim "db-noobaa-db-pg-0" 
INFO[0001] ✅ System Phase is "Ready"                    
INFO[0001] ✅ Exists:  "noobaa-admin"                    

#------------------#
#- Mgmt Addresses -#
#------------------#

ExternalDNS : [https://noobaa-mgmt-openshift-storage.apps.nx123-48-5444.ibm.com]
ExternalIP  : []
NodePorts   : [https://192.168.90.55:30880]
InternalDNS : [https://noobaa-mgmt.openshift-storage.svc:443]
InternalIP  : [https://172.30.111.83:443]
PodPorts    : [https://10.129.2.49:8443]

#--------------------#
#- Mgmt Credentials -#
#--------------------#

email    : admin@noobaa.io
password : GgGB8rAb0G4/d3hQuJb8eQ==

#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : [https://s3-openshift-storage.apps.nx123-48-5444.ibm.com]
ExternalIP  : []
NodePorts   : [https://192.168.90.231:32203 https://192.168.90.55:32203]
InternalDNS : [https://s3.openshift-storage.svc:443]
InternalIP  : [https://172.30.119.74:443]
PodPorts    : [https://10.131.0.53:6443 https://10.129.2.120:6443]

#------------------#
#- S3 Credentials -#
#------------------#

AWS_ACCESS_KEY_ID     : 5gKQeHf201LRAhlZbtjR
AWS_SECRET_ACCESS_KEY : dG2GDFr2PoTPKDsuBGnSa8YTeYSs9Oj1Pc46//NP

#------------------#
#- Backing Stores -#
#------------------#

NAME                           TYPE            TARGET-BUCKET                                 PHASE   AGE          
noobaa-default-backing-store   s3-compatible   nb.1622556871049.apps.nx123-48-5444.ibm.com   Ready   196h45m51s   

#------------------#
#- Bucket Classes -#
#------------------#

NAME                          PLACEMENT                                                        NAMESPACE-POLICY   PHASE   AGE          
noobaa-default-bucket-class   {"tiers":[{"backingStores":["noobaa-default-backing-store"]}]}   null               Ready   196h45m51s   

#-----------------#
#- Bucket Claims -#
#-----------------#

No OBCs found.

#

# ./mcg-cli version
INFO[0000] CLI version: 5.8.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:5.8.0-20210418 
INFO[0000] operator-image: noobaa/noobaa-operator:5.8.0 
#  

Due to this, the test case 
run-ci -v --cluster-name ocstest --ocp-version 4.8 --ocs-version=4.8 --ocsci-conf conf/ocsci/production_powervs_upi.yaml --ocsci-conf conf/ocsci/lso_enable_rotational_disks.yaml --ocsci-conf ~/ocs-ci-conf.yaml --cluster-path /root tests/manage/mcg/test_verify_noobaa_status.py::test_verify_noobaa_status_cli

is failing.

**Comment by gitsridhar** [comment]
Any idea why noobaa-db service is not available? Is this an install problem or known problem? I want to check here before opening a BZ against OCS.

**Comment by lsmcfadden** [comment]
@RazTamir anyone on your team has input here?

**Comment by petr-balogh** [comment]
@MeridianExplorer can you please take a look?

**Comment by MeridianExplorer** [comment]
This seems like a product bug.
I filed a new bug. Seeing as this is assumed to be a product bug for the time being, I'm closing this issue, and suggest tracking the bug.
I'll reopen the issue if it turns out to be an OCS-CI problem.

BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1974573
