### ISSUE TITLE
UI tests: Take screenshots upon failures only if `--collect-logs` is set to True

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#4418]
The same as if someone doesn't want to collect logs upon failures, screenshots should not be collected as well. 
So suggest tieing `--collect-logs` with the screenshots collection upon UI test failures. 
In that way, if  `--collect-logs` is False, screenshots won't be collected

**Comment by petr-balogh** [comment]
@OdedViner are you going to take this issue?
