### ISSUE TITLE
[vSphere] cluster folders in vSphere not properly cleaned

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#4428]
There seems to be some issue with cluster teardown or cleanup process, because there are lot of empty _folders_ (or what is the name) in vSphere console:
![2021-06-11_11-47](https://user-images.githubusercontent.com/4759779/121669419-94871b00-caac-11eb-851e-9177c432e789.png)

**Comment by petr-balogh** [comment]
@dahorak, @vavuthu  is this still happening?

**Comment by dahorak** [comment]
I see number of empty folders in `DC-CP`, but not sure how long they are there. I'll clean up the empty folders and let's see in about one or two weeks.

**Comment by vavuthu** [comment]
opening this as issue still exists
