### ISSUE TITLE
Test getting skipped with no explanation.

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4429]
When I run 
run-ci -s --cluster-name ocstest --ocp-version 4.8 --ocs-version=4.8 --ocsci-conf conf/ocsci/production_powervs_upi.yaml --ocsci-conf conf/ocsci/lso_enable_rotational_disks.yaml --ocsci-conf ~/ocs-ci-conf.yaml --cluster-path /root tests/manage/mcg/test_object_integrity.py::TestObjectIntegrity::test_check_multi_object_integrity[1-large]

it is getting skipped:
2021-06-11 08:40:00,495 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - INFO - Dump of the consolidated config file is located here: /root/logs-ocs-ci/4.8/run-1623415195-config.yaml
Collecting Cluster versions
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.8.6, pytest-5.3.5, py-1.10.0, pluggy-0.13.1
rootdir: /root/ocs-upi-kvm/src/ocs-ci, inifile: pytest.ini
plugins: metadata-1.11.0, ordering-0.6, marker-bugzilla-0.9.4, logger-0.5.1, html-2.1.1, reportportal-1.10.3
collected 1 item                                                                                                                                                       

tests/manage/mcg/test_object_integrity.py::TestObjectIntegrity::test_check_multi_object_integrity[1-large] SKIPPED

========================================================================== 1 skipped in 0.03s ==========================================================================

What is the reason for this skip? I see the corresponding mark:
            pytest.param(
                *[1, "large"],
                marks=[pytest.mark.polarion_id("OCS-1944"), tier2, FILESIZE_SKIP],
            ),
Is this hardcoded to be skipped? If so, why? and how to make it not to skip?

**Comment by petr-balogh** [comment]
@MeridianExplorer can you please check?

**Comment by MeridianExplorer** [comment]
@petr-balogh, @gitsridhar -
Yes, the test is hardcoded to be skipped, as you've noted with `FILESIZE_SKIP`.
I do not know why no explanation is shown - the mark is a simple, common pytest skip - 
`FILESIZE_SKIP = pytest.mark.skip("Current test filesize is too large.")`
Maybe pytest needs to be run with the `-rs` parameters - but this is not at the test scope.

The test should not be unskipped or run - it transfers several terabytes of data, and cannot be reliably run as it currently is. The test is currently destined for deletion.

**Comment by gitsridhar** [comment]
Thanks for the explanation. I am closing this issue.
