### ISSUE TITLE
Test case test_verify_rwo_using_replicated_pod failed

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#4431]
Test case
```tests.manage.pv_services.test_verify_rwo_using_dc_pod.TestVerifyRwoUsingReplicatedPod.test_verify_rwo_using_replicated_pod[CephBlockPool]```
failed due to the error given below.

```
>               raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 360s running get("pod-test-rbd-75591c00bd8e480ebcc91d33c9a-1-deploy", True, None)

ocs_ci/utility/utils.py:1002: TimeoutExpiredError
```
The test case creates DC with replica value 5 and expects at least one replica pod to be Pending and deploy pod be in Running state. This expectation is set because an RWO PVC is used. So among the 5 replica pods, only the pods which are residing on the same node will reach the Running state. So the deploy pod should remain in Running state. 

But in this case, all the 5 replicas were scheduled on the same node and the deploy pod reached the Completed state.
```
12:40:01 - MainThread - ocs_ci.ocs.ocp - INFO - status of pod-test-rbd-75591c00bd8e480ebcc91d33c9a-1-deploy at column STATUS was Completed, but we were waiting for Running
```
This situation is not handled in the test case.

Failed in RUN ID: 1622715438

**Comment by petr-balogh** [comment]
PR is up , waiting for review #4811
