### ISSUE TITLE
Teardown should not fail when openshift ci web can't be reached

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#4439]
## Description of a problem
As long as oc client and other tools are present in expected versions, there is no need to try to download them again.
Moreover it's not ok for a teardown to fail on this.

## Version

ocs-ci commit ae95f3b9   stable-ocs-4.8-202106130431

## Observation
I run teardown of a cluster which was deployed before [change in installer url](https://github.com/red-hat-storage/ocs-ci/issues/2002), and when I run teardown now (when the url is different), the teardown failed on:

```
>           raise ConnectionError(e, request=request)
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openshift-release.svc.ci.openshift.org', port=443): Max retries exceeded with url: /api/v1/releasestream/4.8.0-0.nightly/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f06ccb24070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
There is no need to fail on this, since all tools (oc, installer) are locally available since the deployment.

**Comment by petr-balogh** [comment]
@vavuthu was this fixed by your recent PR?
