### ISSUE TITLE
Add V2 vault support for OCS deployment.

### ISSUE THREAD

**Issue by shyRozen** [red-hat-storage/ocs-ci#4441]
Today we only support V1 of vault. Need to add support for version 2.
That include adding manually VAULT_BACKEND: v2 to ocs-kms-connection-details
and the vault setup should be:

vault secrets enable -ca-cert /certs/cert.pem -path=v2ocs kv-v2

echo '
  path "v2ocs/*" {
    capabilities = ["create", "read", "update", "delete", "list"]
  }
  path "sys/mounts" {
  capabilities = ["read"]
  }'| vault policy write -ca-cert /certs/cert.pem v2ocs -
vault token create -policy=v2ocs -format json -ca-cert /certs/cert.pem

**Comment by shylesh** [comment]
@shyRozen submitting a PR for this, incase if you have already have PR I can take this off.

**Comment by shyRozen** [comment]
@shylesh Go ahead. Thanks
