### ISSUE TITLE
[RHV] Add ability to use custom vCPU configuration for master and worker nodes

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#4442]
Currently, ocs-ci doesn't support using custom cores & sockets values for vCPUs of master and worker nodes in RHV platform.
This RFE is for adding support for custom values.

**Comment by petr-balogh** [comment]
Pr is up https://github.com/red-hat-storage/ocs-ci/pull/4443 and waiting for review
