### ISSUE TITLE
ocs-ci deploys cluster with replica = 1 but add capacity test cases expect replica to be 3

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4474]
While working on implementing various add_capacity test cases under tests/manage/z_cluster/cluster_expansion, I found that the test case code increments the storageDeviceSets -> count by one but expects 3 additional osds to be created. In real, I found that only one osd is created on top of existing osds. 
ocs-ci code deploys storage cluster with the replica set to 1 and count set to 3. 

        if (
            config.DEPLOYMENT.get("local_storage")
            and Version.coerce(ocs_version) >= Version.coerce("4.7")
            and zone_num < 3
        ):
            cluster_data["spec"]["flexibleScaling"] = True
            # https://bugzilla.redhat.com/show_bug.cgi?id=1921023
            cluster_data["spec"]["storageDeviceSets"][0]["count"] = 3
            cluster_data["spec"]["storageDeviceSets"][0]["replica"] = 1

(from ocs_ci/deployment/deploy_ocs_via_operator method in deplyment.py)

In our environment (ppc64le), we deeply OCS using ocs-ci with 3 worker nodes with 500 GB storage each. Storage cluster gets created with 3 osds.  Then add capacity tries to add one more storage device.

All three add capacity test cases expect 12 ( (3+1) times 3) osds when one additional capacity is required.

    pod.wait_for_resource(
        timeout=300,
        condition=constants.STATUS_RUNNING,
        selector="app=rook-ceph-osd",
        resource_count=result * 3,
    )

Instead of resource_count = result * 3, it should be 
1. get replica count from storage count. Then use it while checking resource_count
2. resource_count = result * replicacount

Let me know if this is a good approach and I will put together a PR to proceed.

**Comment by Sravikaz** [comment]
The same behaviour has been observed on IBM Z as well, where the add capacity test case expects 12 osds to up and running when the count value has changed to 4 while patching the storage cluster  .

```
09:34:15 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get storagecluster  -n openshift-storage -o yaml
09:34:15 - MainThread - ocs_ci.ocs.ocp - INFO - Command: patch storagecluster ocs-storagecluster -n openshift-storage -p '[{ "op": "replace", "path": "/spec/storageDeviceSets/0/count",
                    "value": 4}]' --type json
09:34:15 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage patch storagecluster ocs-storagecluster -n openshift-storage -p '[{ "op": "replace", "path": "/spec/storageDeviceSets/0/count",
                    "value": 4}]' --type json
09:34:15 - MainThread - root - INFO - Adding one new set of OSDs was issued without problems
```
```
09:38:34 - MainThread - ocs_ci.ocs.ocp - INFO - status of  at column STATUS - item(s) were ['Running', 'Running', 'Running', 'Running'], but we were waiting for all 12 of them to be Running
09:38:34 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 3 seconds before next iteration
09:38:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-osd -o yaml
09:38:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get Pod rook-ceph-osd-0-fd6ffd4bc-6zqm6 -n openshift-storage
09:38:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get Pod rook-ceph-osd-1-7789f58d87-qvxzn -n openshift-storage
09:38:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get Pod rook-ceph-osd-2-748bdccb57-2hndz -n openshift-storage
09:38:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get Pod rook-ceph-osd-3-697596fb45-dqpr2 -n openshift-storage
09:38:38 - MainThread - ocs_ci.ocs.ocp - INFO - status of  at column STATUS - item(s) were ['Running', 'Running', 'Running', 'Running'], but we were waiting for all 12 of them to be Running
```

Uploading the test execution log

[test_add_capacity.zip](https://github.com/red-hat-storage/ocs-ci/files/6768543/test_add_capacity.zip)

**Comment by lsmcfadden** [comment]
@RazTamir who can review/help?

**Comment by abdulkandathil** [comment]
We are still facing this error.

**Comment by Sravikaz** [comment]
This issue is still open in ODF4.10 and the following test in tier2 fails with the same reason.

> tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py::TestAddCapacity::test_add_capacity[10]

```
        osd_pods_after = pod_helpers.get_osd_pods()
        number_of_osds_added = len(osd_pods_after) - len(osd_pods_before)
        logger.info(
            f"### number_of_osds_added = {number_of_osds_added}, "
            f"before = {len(osd_pods_before)}, after = {len(osd_pods_after) }"
        )
        # If the difference b/w updated count of osds and old osd count is not
        # 3 then expansion failed
>       assert (
            number_of_osds_added == 3
        ), "Exit criteria verification FAILED: osd count mismatch"
E       AssertionError: Exit criteria verification FAILED: osd count mismatch
E       assert 1 == 3
E         +1
E         -3

tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py:246: AssertionError

AssertionError: Exit criteria verification FAILED: osd count mismatch
assert 1 == 3
  +1
  -3
```
