### ISSUE TITLE
Couchbase pods are not coming up 

### ISSUE THREAD

**Issue by shreekarSS** [red-hat-storage/ocs-ci#4488]
From https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1173/testReport/junit/tests.e2e.workloads.couchbase.test_couchbase/TestCouchBaseWorkload/test_cb_workload_simple/

E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 1800s running get_pod_name_by_pattern("cb-example", "couchbase-operator-namespace")

cb-example pods are not coming up

**Comment by Akarsha-rai** [comment]
We are seeing couchbase workload failing to run from OCP 4.8 onward, i.e cb-example pod fails to come with Readiness probe failure as shown below:

From the events of cb-example-0000 pod in 4.8:
```
Normal   AddedInterface          22s   multus                   Add eth0 [10.129.2.153/23] from openshift-sdn
Normal   Pulled                  22s   kubelet                  Container image "registry.connect.redhat.com/couchbase/server:6.0.1-1" already present on machine
...
...
...
Normal   Created                 20s   kubelet                  Created container couchbase-server
Normal   Started                 20s   kubelet                  Started container couchbase-server
Warning  Unhealthy               7s    kubelet                  Readiness probe failed:
```

From cb-example-0000 pod log in 4.8:
```
[ns_server:warn,2021-07-23T06:58:29.126Z,ns_1@127.0.0.1:<0.549.0>:ns_memcached:connect:1227]Unable to connect: {error,{badmatch,{error,econnrefused}}}.
[ns_server:warn,2021-07-23T06:58:29.130Z,ns_1@127.0.0.1:<0.554.0>:ns_memcached:connect:1227]Unable to connect: {error,{badmatch,{error,econnrefused}}}
```
Seems like memcahed issue, not able to connect. Need to check with OCP and couchbase team on it
For more info: https://bugzilla.redhat.com/show_bug.cgi?id=2005281
