### ISSUE TITLE
OCS nodes drain issues.

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4505]
Setup OCP and OCS on ppc64le environment. Checked pods in openshift-storage, and ceph health etc and all are fine. Then tried this command to drain couple of nodes:
oc adm drain worker1 worker2 --force=true --ignore-daemonsets --delete-local-data
and it hangs for ever. These two lines are printed in a loop:
evicting pod openshift-storage/rook-ceph-osd-1-5bbc499485-llqsh
error when evicting pods/"rook-ceph-osd-1-5bbc499485-llqsh" -n "openshift-storage" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod openshift-storage/rook-ceph-mon-a-b697f8ccc-r4z75
error when evicting pods/"rook-ceph-mon-a-b697f8ccc-r4z75" -n "openshift-storage" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.

If I drain only one node, it works. Sounds like this is supposed to fail but it should timeout. This is invoked via ocs-ci wrappter (run-ci) and it crashes with rc=255, so the test case is not able to process timeout to handle this failure gracefully. This is the ocs-ci test case (tier3)
tests/manage/z_cluster/nodes/test_nodes_maintenance.py::TestNodesMaintenance::test_2_nodes_maintenance_same_type[worker]
This test case is part of tier3 suite and run-ci crashes with rc = 255.

**Comment by gitsridhar** [comment]
This is in ppc64le environment. This is not seen in OCS 4.7 on OCP 4.7 environment.

**Comment by gitsridhar** [comment]
I am experimenting with this change:

def drain_nodes(node_names):
    """
    Drain nodes

    Args:
        node_names (list): The names of the nodes

    Raises:
        TimeoutExpired: in case drain command fails to complete in time

    """
    ocp = OCP(kind="node")
    node_names_str = " ".join(node_names)
    log.info(f"Draining nodes {node_names_str}")
    try:
        ocp.exec_oc_cmd(
            f"adm drain {node_names_str} --force=true --ignore-daemonsets "
            f"--delete-local-data **--timeout=1800**",
            timeout=1800,
        )
    except TimeoutExpired:
        ct_pod = pod.get_ceph_tools_pod()
        ceph_status = ct_pod.exec_cmd_on_pod("ceph status", out_yaml_format=False)
        log.error(f"Drain command failed to complete. Ceph status: {ceph_status}")
        # TODO: Add re-balance status once pull/1679 is merged
        raise

I am adding --timeout=1800 to the oc and drain command as well. I will see if it helps.

**Comment by gitsridhar** [comment]
Did not help. after 1800 seconds, oc adm command completed (timed out), but run-ci did not move to Timeout section of code,  it got stuck.

**Comment by lukebrowning** [comment]
Either change ocs-ci to perform single node drains by calling oc adm drain twice.   Or configure the relevant pod disruption budgets to specify minimum number available equals one.   There may be something that you can do with taints and tolerations, but I doubt it.

**Comment by lukebrowning** [comment]
The question is what is the testcase intent of draining two nodes at the same time.   Is ocs supposed to stay up when 2 out of 3 nodes are disabled from an ocs perspective?

**Comment by gitsridhar** [comment]
The test case is designed to drain two nodes at once and it is expected to fail and proceed to uncordon them through timeout mechanism. I will try sequential node drains and check anyway.

**Comment by lukebrowning** [comment]
You could also dynamically patch the pod disruption budget's setting the minimum available to 1 also.

**Comment by lukebrowning** [comment]
So your understanding is that the testcase intends to crash ocs within a specific timeout window.   If that is the case, then changing ocs-ci to workaround the crash as I described is not a solution.   There is another problem that needs to be investigated.   Why is it taking so long to fail?

**Comment by gitsridhar** [comment]
I made this code change and now I see it working:

try:
    ocp.exec_oc_cmd(
        f"adm drain {node_names_str} --force=true --ignore-daemonsets "
        f"--delete-local-data --timeout=1810",
        timeout=1800,
    )
except TimeoutExpired:
    ct_pod = pod.get_ceph_tools_pod()
    ceph_status = ct_pod.exec_cmd_on_pod("ceph status", out_yaml_format=False)
    log.error(f"Drain command failed to complete. Ceph status: {ceph_status}")
    # TODO: Add re-balance status once pull/1679 is merged
    raise

I set the oc adm drain timeout to 1810 seconds and ocs-ci framework timeout left at original value 1800.

**Comment by gitsridhar** [comment]
a slightly larger timeout for oc adm drain than the ocs-ci framework timeout helped.

**Comment by gitsridhar** [comment]
I will create a PR to propose this fix.

**Comment by lsmcfadden** [comment]
@gitsridhar since https://github.com/ocp-power-automation/ocs-upi-kvm/pull/54 is merged does it mean this issue is reslved and you can run tier 3 testing?

**Comment by gitsridhar** [comment]
We are still seeing this problem with this fix. But if this test is run manually, it goes through. Investigating.

**Comment by lsmcfadden** [comment]
@gitsridhar did this ever get resolved?

**Comment by gitsridhar** [comment]
We are seeing this problem occassionally. In fact in the automation run of tier3 it happened today at 95% level. I will continue to investigate.
