### ISSUE TITLE
Use linter for docstrings

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#4514]
https://www.reddit.com/r/Python/comments/77b1h7/googlestyle_docstring_linter/

Add linter for google style docstrings to our CI and commit hooks.

**Comment by clacroix12** [comment]
This is a good idea and definitely something we should still do. Just out of curiosity I ran `darglint` against a few of our modules and there are a lot of docstrings to address. Adding this tool should be quick and easy but addressing all of the issues it raises will take some time (but should be done).
