### ISSUE TITLE
Automate BZ-1933715: Multiple MON pods stays on one OCS node

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#4521]
Automate BZ-1933715. The BZ also reproduced lately, as you can see in [BZ-1974204](https://bugzilla.redhat.com/show_bug.cgi?id=1974204). To reproduce the issue, I think we can use this comment: https://bugzilla.redhat.com/show_bug.cgi?id=1974204#c7. But now we need to test it with OCS 4.7, 4.8: 

> The original cause of this was basically the following:
> 1. Install 4.5 in AWS or VWMware (where mons are on a portable PV)
> 2. Drain a node with a mon
> 3. The mon will move to another node with a mon if the mon nodes are the only ones available, since it was using preferred anti-affinity instead of required anti-affinity.
> 
> To cause this in recent releases will be difficult since OCS specifies "required" anti-affinity to schedule new mons. I was able to test on upstream by using the preferred anti-affinity instead of required for the placement on the CephCluster CR.

Also, we can have a look at this comment here https://bugzilla.redhat.com/show_bug.cgi?id=1974204#c15 for additional information to reproduce the issue. 
So in summarize, to reproduce the issue, we need to follow these steps:

1. Deploy a cluster with 6 OCS worker nodes - Both with AWS and VMWare(LSO also be tested). 
2. Check the Only one MON pod is running on every node, and in the case of AWS, check that they spread on different zones.
3. Multiple times, single node drains, wait till 10 mins(or another amount of time).
4. Simultaneous two-node drain with and without delays between each node.
5. Shutdown and recovery of the nodes after 10 mins

**Comment by hnallurv** [comment]
Itzhak, this BZ will be covered as part of close loop automation process by Akarsha. She is working on getting a set of reliable  steps to reproduce the issue. It was not reproducible till now. See https://bugzilla.redhat.com/show_bug.cgi?id=1974204#c15.

**Comment by yitzhak12** [comment]
Yes, I see. So currently there is no need to automate the BZ @hnallurv?
