### ISSUE TITLE
CSV version gets changed automatically

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4523]
Deployed OCP and OCS and got the csv version as say:

openshift-storage                      ocs-operator.v4.8.0-443.ci                                     OpenShift Container Storage   4.8.0-444.ci                                       Succeeded

During the course of time when tier tests are run, etc, The version moves to 443. The package manifest contains 444 and ocs-ci test case startup code looks for it and does not find it. 

Why does the csv version go back? When this happens, I have to redeploy everything to continue.

**Comment by gitsridhar** [comment]
Looks like the currentCSV value in the packagemanifest goes out of sync with actual csv.

**Comment by gitsridhar** [comment]
These two go out of sync sometimes. Not sure what triggers it. This is from a working healthy environment:
[cpratt@nx122-ahv logs-cron]$ oc get packagemanifest -A -o yaml | grep -i currentcsv | grep ocs | grep 4.8
    - currentCSV: ocs-operator.v4.8.0-444.ci

[cpratt@nx122-ahv logs-cron]$ oc get csv -A | grep ocs | grep 4.8
openshift-storage                      ocs-operator.v4.8.0-444.ci                                     OpenShift Container Storage   4.8.0-444.ci                                       Succeeded

The CSV version goes backward by one level.

**Comment by vasukulkarni** [comment]
@gitsridhar can you paste the full cli you used to run via ocs-ci ? did you create own csv file ?

**Comment by petr-balogh** [comment]
Hello @gitsridhar , what image do you use in catalogSource for OCS?

If you are using moving tag like:  `latest-stable-4.8` or `latest-4.8` than they are moving tags and once the new build is produced, the new build will get the latest-stable-4.8  if it passed acceptance or latest-4.8 only when new build is produced.

By default the subscription has automatic approval strategy and once the catalog source is reloaded for new tag image then you will automatically get new build.

If you see it flipped the older version I can think only that they removed the image or tag.  If that's not the case then it's for opening bug, but not OCS-CI issue.

You will need to share more information about catalog source image used here. But I don't see the reason why CSV should flip to previous version as it should not be like that and OLM upgrading only to new one.

**Comment by gitsridhar** [comment]
HI @petr-balogh we use quay.io/rhceph-dev/ocs-registry:latest-4.8 image, so we are using latest-4.8 images (this is from ocs-ci deployment code).

**Comment by petr-balogh** [comment]
This is floating tag so it can be moved once new build is created. So if you would like to avoid it you should use some specific build with id. So we can probably close this issue.

**Comment by gitsridhar** [comment]
I am closing this issue.
