### ISSUE TITLE
Bug in check_and_add_enough_worker

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4526]
Deployed OCP and OCS and prepared it to run scale tests. But check_and_add_enough_worker failed due to this bug:

This method 
retrieves a list of worker nodes. (A)
retrieves a list of worker nodes labelled for ocs. (B)
retrieves a list of worker nodes labelled for scale tests. (C)
if use_ocs_worker_for_scale is configured to true in ocs-ci config, then all workers are labeled for scale tests. In our case, this is NOT set.
else:
    if no node is labeled for scale tests (C), all items from ocs worker list (B) are removed from the worker node list (A).Then if any worker node is left in A, then they are labeled for scale tests. In our case, A becomes empty due to previous step.

    worker_list = node.get_worker_nodes()
    ocs_worker_list = machine.get_labeled_nodes(constants.OPERATOR_NODE_LABEL)
    scale_worker = machine.get_labeled_nodes(constants.SCALE_LABEL)
    if config.RUN.get("use_ocs_worker_for_scale"):
        if not scale_worker:
            helpers.label_worker_node(
                node_list=worker_list, label_key="scale-label", label_value="app-scale"
            )
    else:
        if not scale_worker:
            for node_item in ocs_worker_list:
                worker_list.remove(node_item)
            if worker_list:
                helpers.label_worker_node(
                    node_list=worker_list,
                    label_key="scale-label",
                    label_value="app-scale",
                )
    scale_worker_list = machine.get_labeled_nodes(constants.SCALE_LABEL)
    logging.info(f"Print existing scale worker {scale_worker_list}")

I am not sure why worker_list is emptied ... 

We overcome this problem by pre-labelling all ocs worker nodes for scale tests.

**Comment by vasukulkarni** [comment]
@ramkiperiy FYI

**Comment by ramkiperiy** [comment]
This is expected. For now adding more worker nodes does supported in IPI platforms only, again for IBM IPI we have add support.
**We overcome this problem by pre-labelling all ocs worker nodes for scale tests.** --> This also expected, since test case will expect scale label on existing worker nodes and if the label is present for enough workers for scaling then adding more worker nodes is skipped.

**Comment by ramkiperiy** [comment]
So what is the next step here ? Better to add IBM IPI support to close this github issue.

**Comment by gitsridhar** [comment]
I am closing this issue. When IPI is available for IBM Powervs, we will revisit this area.
