### ISSUE TITLE
RHV OCP 4.8 deployment failing due to default setting of Affinitygroup

### ISSUE THREAD

**Issue by suchita-g** [red-hat-storage/ocs-ci#4539]
Problem: OCP-4.8 deployment is failing with error `failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Provisioning Check": Affinity Group compute cannot be fulfilled, oVirt cluster doesn'thave enough hosts: found 1 hosts but 3 replicas assigned to affinity group%!(EXTRA ovirt.AffinityGroup={compute 3 AffinityGroup for spreading each compute machine to a different host true})`

Analysis: 
As per the new OCP 4.8, Affinitygroup is getting enabled by default. 
It is recommended to add a non-enforcing affinity group to distribute the control plane and workers,  to use as much of the cluster as possible.
On the RHV platform we have 2 live setups,
     
1. cluster name `rhv1` i.e credential file `rhv-DC1` and 
2. cluster name `rhv2` i.e credential file `rhv-DC2`.
 Both these setups use a single host.
 
Since it doesn't have a different host, deployment is failing with error: 
`failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Provisioning Check": Affinity Group compute cannot be fulfilled, oVirt cluster doesn't have enough hosts: found 1 host but 3 replicas assigned to affinity group%!(EXTRA ovirt.AffinityGroup={compute 3 AffinityGroup for spreading each compute machine to a different host true})`

Fix: We need to disable Affinitygroup in install-config while provisioning the RHV cluster.

**Comment by prsurve** [comment]
More details about AffinityGroup and how to disable AffinityGroup are listed here https://docs.openshift.com/container-platform/4.8/installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-example-install-config-yaml_installing-rhv-customizations
