### ISSUE TITLE
Tier 4b -- Delete Pod is taking more than expected timeout of 180 seconds

### ISSUE THREAD

**Issue by sameshai** [red-hat-storage/ocs-ci#4541]
test_ceph_daemon_kill_during_pod_pvc_deletion  -- 

Delete Pod is taking more than 180 seconds. Is this known issue on other platforms ? 
Should we consider doubling this timeout to 360 seconds ? In on case this fails 

1.) due to race condition where describe command fails as pod is already deleted
2.) It fails as the pod is not yet deleted.

pod_obj.ocp.wait_for_delete(
                pod_obj.name, 180
            ), f"Pod {pod_obj.name} is not deleted"
        log.info("Verified: Pods are deleted.")

Error 1 :- 

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/view/Tier4/job/qe-trigger-ibmcloud-managed-1az-rhel-3w-tier4b/3/testReport/tests.manage.pv_services.test_ceph_daemon_kill_during_resource_deletion/TestDaemonKillDuringPodPvcDeletion/test_ceph_daemon_kill_during_pod_pvc_deletion_CephFileSystem_delete_pvcs_mgr_/

ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n namespace-test-ce36ec94ba4d4a7a8a3aac02a describe Pod pod-test-cephfs-904c0eda9e014b58a3c16638.
E           Error is Error from server (NotFound): pods "pod-test-cephfs-904c0eda9e014b58a3c16638" not found

Error 2 :- 

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/view/Tier4/job/qe-trigger-ibmcloud-managed-1az-rhel-3w-tier4b/3/testReport/tests.manage.pv_services.test_ceph_daemon_kill_during_resource_deletion/TestDaemonKillDuringPodPvcDeletion/test_ceph_daemon_kill_during_pod_pvc_deletion_CephFileSystem_delete_pods_mds_/
   if timeout < (time.time() - start_time):
                describe_out = self.describe(resource_name=resource_name)
                msg = (
                    f"Timeout when waiting for {resource_name} to delete. "
                    f"Describe output: {describe_out}"
                )
>               raise TimeoutError(msg)
E               TimeoutError: Timeout when waiting for pod-test-cephfs-7868806f1be04774b0eacfe1 to delete. Describe output: Name:                      pod-test-cephfs-7868806f1be04774b0eacfe1
E               Namespace:                 namespace-test-7b23781d001941988536dc7b0
E               Priority:                  0
E               Node:                      10.243.128.215/10.243.128.215
E               Start Time:                Sat, 26 Jun 2021 20:51:35 +0000
E               Labels:                    <none>
E

**Comment by sameshai** [comment]
Also we have another issue when we wait for 60 second when pod deletion starts 

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/view/Tier4/job/qe-trigger-ibmcloud-managed-1az-rhel-3w-tier4b/3/testReport/tests.manage.pv_services.test_ceph_daemon_kill_during_resource_deletion/TestDaemonKillDuringPodPvcDeletion/test_ceph_daemon_kill_during_pod_pvc_deletion_CephFileSystem_delete_pods_mgr_/
if operation_to_disrupt == "delete_pods":
            ret = wait_for_resource_count_change(
                get_all_pods, initial_num_of_pods, self.namespace, "decrease", 1, 60
            )
>           assert ret, "Wait timeout: Pods are not being deleted."
E           AssertionError: Wait timeout: Pods are not being deleted.
E           assert False
Seems that we have given 60 second timeout for multiple pod deletion

**Comment by petr-balogh** [comment]
If the test is used to pass on different platform and you need to increase timeout for only for IBM Cloud platform, then I would make this timeout like variable:

timeout = 180 if platform == "ibm_cloud" else 60

So the timeout will be higher in the case of ibm cloud platform.

**Comment by sameshai** [comment]
@petr-balogh  any reference if other platforms are working with this timeout ? I tried to find one but want to make sure before increase timeout for IBM cloud

**Comment by sidhant-agrawal** [comment]
@sameshai 
Green squad is analyzing the issue and will report back with our findings soon.

**Comment by petr-balogh** [comment]
> @petr-balogh any reference if other platforms are working with this timeout ? I tried to find one but want to make sure before increase timeout for IBM cloud

I am not sure I follow, I was just saying that if the timeout is ibm cloud platform specific you should increase needed timeouts just for this specific platform if the timeout is ok for the other platforms.

**Comment by sidhant-agrawal** [comment]
We observed these kind of error messages in the pod events
```
  message: 'error killing pod: failed to "KillContainer" for "web-server" with KillContainerError: "rpc error: code = Unknown desc = failed to get container ''stopped'' status 0953bf51c35d17ae518a865102afadc8b1adccdcdd7b77739bd484d24fe08c45: failed to get container stopped status: 30s timeout reached"'
```

Hence, raised a bug here https://bugzilla.redhat.com/show_bug.cgi?id=1980873
