### ISSUE TITLE
UI helper functions for UI Automation

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#4569]
Hi All,

I think we need to have a separate ui_helpers.py file where we have common methods for e.g. Pod Creation via UI, PVC Creation via UI, etc. and use them in UI automation wherever required.

This seems to be required as we use a lot of CLI functions and miss UI validation. UI automation is all about performing actions via UI and then validating it.

Please share your thoughts on this.

Thanks

**Comment by ebenahar** [comment]
good idea Aman, I would say this should be done with a dedicated PR

**Comment by shyRozen** [comment]
About Pod I don't think we need to automate it via UI as it is not our responsibility. Other objects like PVC are done in the PvcUI class. We can open a helpers if you think that some code is not meant to be in the class itself under ocs_ci/ocs/ui directory.

**Comment by shyRozen** [comment]
Addressed in [#4576 ]
