### ISSUE TITLE
RFE: Decrease usage of cluster_namespace while overriding rook parameters

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#46]
Currently, to override cluster_namespace for rook we need to specify cluster_namespace for each file it will good if we make cluster_namespace as generic so all rook pods will come under that namespace

Currently, I am using this conf:

https://paste.fedoraproject.org/paste/B-XgA0b0sfDgN3OCEuWMiw

**Comment by petr-balogh** [comment]
In all of our templates we are using {{ cluster_namespace | default(openshift-storage) }}, so you can in the config file overwrite this variable to whatever you want like rook-ceph.  I used this new namespace openshift-storage as I saw also in [metal3 dev scripts](https://github.com/openshift-metal3/dev-scripts/blob/master/10_deploy_rook.sh) they are using this one.  

If you want something else in your execution you can then just pass cluster_namespace in you config like https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocs_basic_install.yml under env_data section.

Of course while rendering those data you need to use same approach as we have now in installation to propagate those data to the template.

**Comment by petr-balogh** [comment]
If anyone else (@RazTamir @shylesh @vavuthu @ebenahar @dahorak @clacroix12 ) don't have any other objections I would close this issue as **won't do**.

**Comment by RazTamir** [comment]
+1 on closing
