### ISSUE TITLE
Missing 'ocpnetsplit' module in ocs-ci

### ISSUE THREAD

**Issue by Sravikaz** [red-hat-storage/ocs-ci#4601]
Ocs-ci execution reports the following error with the newly pulled changes from this [commit](https://github.com/red-hat-storage/ocs-ci/commit/75a2e8126f5abd28c84ecbe017222ce5000d5194#diff-7c5f8cdadc65b3e1bc243699c9bafee9e568f355cdfe2c1922bcf2c5deaf742a) 

```
ImportError while loading conftest '/root/ocs-ci/tests/conftest.py'.
tests/conftest.py:24: in <module>
    from ocs_ci.ocs import constants, defaults, fio_artefacts, node, ocp, platform_nodes
ocs_ci/ocs/platform_nodes.py:14: in <module>
    from ocs_ci.deployment.vmware import (
ocs_ci/deployment/vmware.py:63: in <module>
    from .deployment import Deployment
ocs_ci/deployment/deployment.py:34: in <module>
    from ocs_ci.deployment.netsplit import setup_netsplit
ocs_ci/deployment/netsplit.py:6: in <module>
    import ocpnetsplit.main
E   ModuleNotFoundError: No module named 'ocpnetsplit'
```

**Comment by mbukatov** [comment]
You need to install ocs-ci dependencies as explained in the [docs](https://ocs-ci.readthedocs.io/en/latest/getting_started.html#installing) via:

```
pip install -r requirements.txt
```

**Comment by Sravikaz** [comment]
Thanks @mbukatov  , I have actually done a` git pull`  to fetch the latest changes on an already working ocs-ci environment with the dependencies installed. It works now after rerunning the above command with the new dependencies.

**Comment by mbukatov** [comment]
Good to hear it worked for you, I'm closing the issue now.
