### ISSUE TITLE
test_validate_ceph_config_values_in_rook_config_override fails because of incomplete expectations

### ISSUE THREAD

**Issue by schaefm-ibm** [red-hat-storage/ocs-ci#4602]
I see `tests/manage/z_cluster/test_ceph_default_values_check.py::TestCephDefaultValuesCheck::test_validate_ceph_config_values_in_rook_config_override` failing because of an assertion error. However, this is a false negative. Assertion checks on count of elements in respective configurations, but actually the given reference `constants.ROOK_CEPH_CONFIG_VALUES` misses entries which are given in the configmap:

In `ocs_ci/ocs/constants.py`:
```
ROOK_CEPH_CONFIG_VALUES = """
[global]
mon_osd_full_ratio = .85
mon_osd_backfillfull_ratio = .8
mon_osd_nearfull_ratio = .75
mon_max_pg_per_osd = 600
[osd]
osd_memory_target_cgroup_limit_ratio = 0.5
"""
```

In `oc get cm/rook-config-override -o yaml`:
```
    [global]
    bdev_flock_retry = 20
    mon_osd_full_ratio = .85
    mon_osd_backfillfull_ratio = .8
    mon_osd_nearfull_ratio = .75
    mon_max_pg_per_osd = 600
    mon_pg_warn_max_object_skew = 0
    [osd]
    osd_memory_target_cgroup_limit_ratio = 0.5
```

The two additional items in the "real" configmap let the assertion on counting elements fail.

**Comment by mbukatov** [comment]
This boils down to a question, whether we have introduced change in the default configmap by mistake, or whether this is a deliberate decision.

Either way, there should be a bug or JIRA Epic for that. Until that, it's quite premature to say that this is a false negative, quite the contrary: the test helps us notice a discrepancy between expected and actual configuration.

**Comment by mbukatov** [comment]
And I see that `bdev_flock_retry = 20` was added to the rook-config-override config map as part of BZ 1977121. This means that the ocs-ci needs to be updated accordingly.

**Comment by mbukatov** [comment]
This should not be closed without a clear evidence that we don't setup invalid test environment because for this.
