### ISSUE TITLE
Require new Performance and Scale tiers in Jenkins

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#4625]
After merge of below 2 PR's we have new tier names added in Performance and Scale.
These new tiers are not required to be part of the Pipeline job, since the plan is to execute these tier tests on demand but we need these new tiers to be added in Jenkins to run PR validation job.

Performance PR: https://github.com/red-hat-storage/ocs-ci/pull/4552
Scale PR: https://github.com/red-hat-storage/ocs-ci/pull/4543

**Comment by vavuthu** [comment]
@ramkiperiy created MR for the same

**Comment by ramkiperiy** [comment]
@vavuthu Any update on the MR, is it merged ?

**Comment by vavuthu** [comment]
@ramkiperiy yes, it was merged. You can see new markers in test pr jobs

**Comment by ramkiperiy** [comment]
Thanks Vijay
