### ISSUE TITLE
Data integrity check for fio workload should be done with fio's 'verify=...' parameter, not externally via sha1 command

### ISSUE THREAD

**Issue by mykaul** [red-hat-storage/ocs-ci#4663]
Currently, it seems the code does post IO some sha1 calcualtion and verification, instead of using fio's built-in data integrity feature (enabled via 'verify=<method>' parameter). It's more efficient to use fio's.

**Comment by OdedViner** [comment]
@mykaul 
Which method do you think is best to use?
Allowed values are:
md5 crc16 crc32 crc32c crc32c-intel crc64 crc7 sha256 sha512 sha1

**Comment by mykaul** [comment]
From its man:
```
crc32c Use a crc32c sum of the data area and store it in the header of each block. This will automatically use hardware acceleration (e.g. SSE4.2 on an x86 or CRC crypto extensions on ARM64) but will  fall  back
                            to software crc32c if none is found. Generally the fastest checksum fio supports when hardware accelerated.
```

**Comment by vasukulkarni** [comment]
@mykaul do_verify=True is default for FIO workloads
