### ISSUE TITLE
External vault config fails

### ISSUE THREAD

**Issue by shyRozen** [red-hat-storage/ocs-ci#4684]
run: 1628278373
tests/manage/pv_services/test_rbd_pv_encryption.py::TestRbdPvEncryption::test_rbd_pv_encryption[v1]
tests/manage/pv_services/test_rbd_pv_encryption.py::TestRbdPvEncryption::test_rbd_pv_encryption[v2]
Test is failing to set vault.
`self = <tests.manage.pv_services.test_rbd_pv_encryption.TestRbdPvEncryption object at 0x7f9034384250>
kv_version = 'v1'
request = <SubRequest 'setup' for <Function test_rbd_pv_encryption[v1]>>

    @pytest.fixture(autouse=True)
    def setup(self, kv_version, request):
        """
        Setup csi-kms-connection-details configmap
    
        """
        # Initialize Vault
        self.vault = kms.Vault()
>       self.vault.gather_init_vault_conf()

tests/manage/pv_services/test_rbd_pv_encryption.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/utility/kms.py:128: in gather_init_vault_conf
    self.vault_conf = self.gather_vault_config()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.utility.kms.Vault object at 0x7f90361004c0>

    def gather_vault_config(self):
        """
        This function populates the vault configuration
    
        """
        if self.vault_deploy_mode == "external":
>           vault_conf = load_auth_config()["vault"]
E           KeyError: 'vault'`

**Comment by petr-balogh** [comment]
Hey Shay, have you provided proper value in specific jenkins KMS parameter? It's mandatory.  Config file is not enough. As info about specific vault instance has to be provided. I am not on VPN now to tell you exact parameter, but if you will search kms in deploy job you will find it.

**Comment by sidhant-agrawal** [comment]
The testrun `1628278373` was not run via jenkins. The `vault` details were not provided and therefore the tests failed.
Closing the issue as the failure is due to missing values.

**Comment by shyRozen** [comment]
[run 1629461196](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1663)
As kms is tier1 runs I don't see in parameters that KMS_DEPLOYMENT config file was passed. 
Please check @petr-balogh
