### ISSUE TITLE
TimeoutExpired on noobaa obc related scale regression runs

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#4688]
The following appears on regression runs of test_scale_obc_creation.TestScaleOCBCreation.test_scale_mcg_obc_creation,tests.e2e.scale.noobaa.test_scale_obc_creation.TestScaleOCBCreation.test_scale_rgw_obc_creation, and TestScaleOCBCreation.test_scale_rgw_obc_creation

>           raise TimeoutExpired(
                    self.args, orig_timeout,
                    output=b''.join(stdout_seq) if stdout_seq else None,
                    stderr=b''.join(stderr_seq) if stderr_seq else None)
E           subprocess.TimeoutExpired: Command '['oc', 'delete', 'obc', 'obc-test-e1114454b0b2417f9ab589762a3aa00', '-n', 'openshift-storage']' timed out after 600 seconds

/usr/lib64/python3.8/subprocess.py:1068: TimeoutExpired

**Comment by tiffanyn108** [comment]
obc creation is passed on AWS run: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/5175/testReport/

**Comment by ramkiperiy** [comment]
Closing this issues, not observed in recent runs.
