### ISSUE TITLE
Noobaa & AWS bucket ownership issue. Scale regression test.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#4689]
In tests.e2e.scale.noobaa.test_scale_endpoint.TestScaleEndpointAutoScale.test_scale_endpoint_and_respin_ceph_pods[mgr]

  >           raise error_class(parsed_response, operation_name)
E           botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).

**Comment by tiffanyn108** [comment]
Detail logs: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/4512/testReport/junit/tests.e2e.scale.noobaa.test_scale_endpoint/TestScaleEndpointAutoScale/test_scale_endpoint_and_respin_ceph_pods_mon_/

**Comment by ramkiperiy** [comment]
Waiting for Ben's comment to identify the issue.

**Comment by tiffanyn108** [comment]
Existing product bug on this issue:
- https://bugzilla.redhat.com/show_bug.cgi?id=1944236
- https://bugzilla.redhat.com/show_bug.cgi?id=1955109
