### ISSUE TITLE
tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py -- fio.py KeyError

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#4695]
This was seen on a regression run:

kwargs = {'pod': <ocs_ci.ocs.resources.pod.Pod object at 0x7f270435df50>}
io_pod = <ocs_ci.ocs.resources.pod.Pod object at 0x7f270435df50>, distro = None

    @retry(CommandFailed, tries=10, delay=10, backoff=1)
    def setup(**kwargs):
        """
        setup fio workload
    
        Args:
            **kwargs (dict): fio setup configuration.
                At this point in time only argument present in kwargs will be
                'pod' on which we want to setup. In future if we move to
                containerized fio then pod.yaml will be presented in kwargs.
    
        Returns:
            bool: True if setup succeeds else False
        """
        io_pod = kwargs["pod"]
        # For first cut doing simple fio install
        distro = find_distro(io_pod)
>       pkg_mgr = DISTROS[distro]
E       KeyError: None

ocs_ci/utility/workloads/fio.py:43: KeyError

**Comment by ramkiperiy** [comment]
Closing this issue, since we are planning to repro the issue part of https://github.com/red-hat-storage/ocs-ci/issues/2752
