### ISSUE TITLE
Noobaa rpc scale tests -- bucket creation failure, bucket not found

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#4696]
tests.e2e.scale.noobaa.test_scale_namespace_rpc.TestScaleNamespace.test_scale_namespace_bucket_creation[aws]

Failed due to bucket not found

E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage get obc mcg-namespace-bucket-03d6876d52614cdcaa3 -n openshift-storage -o yaml.
E           Error is Error from server (NotFound): objectbucketclaims.objectbucket.io "mcg-namespace-bucket-03d6876d52614cdcaa3" not found

This bug was also seen in:
tests.e2e.scale.noobaa.test_scale_namespace_rpc.TestScaleNamespace.test_scale_namespace_bucket_creation[azure]
tests.e2e.scale.noobaa.test_scale_namespace_rpc.TestScaleNamespace.test_scale_namespace_bucket_creation_with_rgw

**Comment by tiffanyn108** [comment]
Added failure logs: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/4512/testReport/junit/tests.e2e.scale.noobaa.test_scale_namespace_rpc/TestScaleNamespace/test_scale_namespace_bucket_creation_aws_/

**Comment by ramkiperiy** [comment]
Test need to be reproduced in vmware LSO platform cluster and based on the reproducer have to take call either to fix issue in testcase or this issue to be closed.
