### ISSUE TITLE
Increase rebalance timeout in the "add capacity" tests

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#4748]
In this run https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1661/ in the test https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1661/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity_with_node_restart/TestAddCapacityNodeRestart/test_add_capacity_node_restart_1_workload_storageutilization_rbd0_/, we can see it failed because the rebalance failed to complete in the given timeout. 
Here is a snippet from the console output:

> 12:00:14 - MainThread - ocs_ci.ocs.cluster - INFO - {'checks': {}, 'status': 'HEALTH_OK'}
12:00:14 - MainThread - ocs_ci.ocs.cluster - INFO - [{'state_name': 'active+clean', 'count': 223}, {'state_name': 'active+remapped+backfill_wait', 'count': 64}, {'state_name': 'active+remapped+backfilling', 'count': 1}]
12:00:14 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 10 seconds before next iteration
12:00:24 - MainThread - ocs_ci.ocs.cluster - ERROR - Data re-balance failed to complete within the given timeout of 1800 seconds

The ceph health was "HEALTH OK" at the end of the test.
I think it also happened in some of the previous runs. We need to increase the rebalance timeout for the "add capacity" tests so that it won't fail on the timeout issue.

**Comment by yitzhak12** [comment]
I have noticed that the ceph rebalance timeout issue is in AWS and not in VSPHERE. Is it possible that the ceph rebalance timeout in vSphere is faster than AWS?

**Comment by ebenahar** [comment]
I have done some evaluation in the past, after we have got and deployed our vSphere HW. The Overall IO performance of our vSphere environment was better than AWS with EBS volumes.
