### ISSUE TITLE
Where needed, delete PVC with validate_pv_deleted as True

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#475]
* After https://github.com/red-hat-storage/ocs-ci/pull/465 gets merged

In cases where PVCs were created with retaining policy set to delete, and we can wait for their deletion, PVC.delete() should be sent with validate_pv_deleted as True.

**Comment by RazTamir** [comment]
Should be fixed with https://github.com/red-hat-storage/ocs-ci/pull/476

**Comment by ebenahar** [comment]
Fixed with https://github.com/red-hat-storage/ocs-ci/pull/476
