### ISSUE TITLE
"unknown error: net::ERR_SSL_PROTOCOL_ERROR" trying to login to UI

### ISSUE THREAD

**Issue by shyRozen** [red-hat-storage/ocs-ci#4790]
ocs-ci results for OCS4-6-Downstream-OCP4-6-VSPHERE6-UPI-FIPS-1AZ-RHCOS-VSAN-3M-3W-tier1 (BUILD ID: v4.6.7-189.ci RUN ID: 1629972342) 
[build url](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1698/)

`tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_create_resize_delete_pvc[ocs-storagecluster-cephfs-test-pvc-fs-ReadWriteMany-2-Filesystem]
tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_create_resize_delete_pvc[ocs-storagecluster-ceph-rbd-test-pvc-rbd-ReadWriteMany-3-Block]
tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_cre! ate_resiz e_delete_pvc[ocs-storagecluster-cephfs-test-pvc-fs-ReadWriteOnce-10-Filesystem]
tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_create_resize_delete_pvc[ocs-storagecluster-ceph-rbd-test-pvc-rbd-ReadWriteOnce-11-Block]
tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_create_resize_delete_pvc[ocs-storagecluster-ceph-rbd-test-pvc-rbd-ReadWriteOnce-13-Filesystem]`
Tests fail because of : 
`response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"unknown error: net::ERR_SSL_PROTOCOL_ERROR\\n  ...wn>\\n#22 0x55be45d3fe58 \\u003Cunknown>\\n#23 0x55be45d59dfd \\u003Cunknown>\\n#24 0x7f2cdcf6714a start_thread\\n"}}'}`

**Comment by shyRozen** [comment]
@petr-balogh @dahorak Do we any ntp setup on slaves?

**Comment by vavuthu** [comment]
@shyRozen yes for vsphere jobs
https://github.com/red-hat-storage/ocs-ci/blob/b07598860d34987f860bda86ff49095ae98c9053/ocs_ci/deployment/vmware.py#L400

**Comment by shyRozen** [comment]
@vavuthu I'm talking about time sync in the slaves operating system that run OCS-CI.
Is the slave setup include some NTP setting to sync the time?
My worry is that time is not on the spot in slave system and therefore we have lots of SSL errors in selenium.

**Comment by vavuthu** [comment]
ahh, you are asking for jenkins agents. I thought you are looking in cluster.

**Comment by petr-balogh** [comment]
Hey @shyRozen , yes we do at the start of each jenkins agent via this playbook and chrony role I highlighted in this link:
https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/blob/master/ansible/playbooks/jenkins-slave/playbook.yml#L109-115

**Comment by shyRozen** [comment]
Thanks @petr-balogh
