### ISSUE TITLE
Could not access s3-cli-with-test-objects-multiarch

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4797]
On IBM System P and System Z we are not able to execute some tier tests due to the problem below:

This is after https://github.com/red-hat-storage/ocs-ci/pull/3754 was merged. 

Normal   Scheduled       63s                default-scheduler  Successfully assigned openshift-storage/session-awscli-relay-pod-ef60d869284b470 to worker-0.ocsm4205001.lnxne.boe
  Normal   AddedInterface  62s                multus             Add eth0 [10.131.1.2/23] from openshift-sdn
  Normal   BackOff         30s (x2 over 59s)  kubelet            Back-off pulling image "quay.io/ocsci/s3-cli-with-test-objects-multiarch:1.0"
  Warning  Failed          30s (x2 over 59s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling         16s (x3 over 61s)  kubelet            Pulling image "quay.io/ocsci/s3-cli-with-test-objects-multiarch:1.0"
  Warning  Failed          14s (x3 over 60s)  kubelet            Failed to pull image "quay.io/ocsci/s3-cli-with-test-objects-multiarch:1.0": rpc error: code = Unknown desc = Error reading manifest 1.0 in quay.io/ocsci/s3-cli-with-test-objects-multiarch: unauthorized: access to the requested resource is not authorized
  Warning  Failed          14s (x3 over 60s)  kubelet            Error: ErrImagePull

I understand we do have access to quay.io/ocsci as we pull nginx image from it. 

Can you give us updated secret for us to include it in auth.yaml?

**Comment by bernerhat** [comment]
does this issue still happening to you? @gitsridhar

**Comment by gitsridhar** [comment]
I am closing this issue. We are not seeing this issue in tier2 anymore.
