### ISSUE TITLE
RFE: Create an OCP resource to execute 'oc' cammands

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#48]

**Comment by petr-balogh** [comment]
@RazTamir few tips, assign the issue to yourself on the right side. Put the label for RFE.  I will do some presentation soon how to contribute to OCS-CI with all the tips and stuff about fork, branches PR, reviewers, coding guidelines and so on.

**Comment by RazTamir** [comment]
Done - Thanks!

**Comment by RazTamir** [comment]
Basic functionality implemented here - https://github.com/red-hat-storage/ocs-ci/pull/43
Please review

**Comment by RazTamir** [comment]
Closing as the main functionality is in place
