### ISSUE TITLE
test_fio_workload_simple-CephBlockPool-sequential stuck in loop for 7 days on status.phase with timeout of 600

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#4807]
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1719/

running for 7 days

and it's still trying to run this command over and over

07:14:15 - MainThread - ocs_ci.helpers.performance_lib - INFO - Going to run oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n benchmark-operator get pod --no-headers -o custom-columns=:metadata.name,:status.phase with timeout of 600

Problematic case is:
15:14:12 - MainThread - test_fio_benchmark - INFO - Logs file path name is : /home/jenkins/current-cluster-dir/logs/ocs-ci-logs-1630335194/tests/e2e/performance/test_fio_benchmark.py/TestFIOBenchmark/test_fio_workload_simple-CephBlockPool-sequential

Logs: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-011vu1cs33-pn/j-011vu1cs33-pn_20210830T125630

**Comment by petr-balogh** [comment]
The same happened on AWS cluster here:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1725/consoleFull but here it also deleted the cluster later on and it's stuck there.

We should disable the test till it's fixed. And make sure we will not get to such situation again.

**Comment by Avilir** [comment]
I found 2 reasons for this issue :

1. the function which identify benchmark restart  is not working as expected when more then one pod is used in the benchmark - PR is WIP
2. it is look like out of resources make the FIO benchmark to failed.
