### ISSUE TITLE
Openstack IPI deployment

### ISSUE THREAD

**Issue by renan-campos** [red-hat-storage/ocs-ci#4822]
The skeleton for Openstack IPI deployments were added in a PR in order to run tier1 tests  (https://github.com/red-hat-storage/ocs-ci/pull/3489). 

Adding this issue for the deployment implementation, as requested by @petr-balogh.

**Comment by petr-balogh** [comment]
@renan-campos you probably won't continue with the rest as you closed the issue. Right?

**Comment by renan-campos** [comment]
@petr-balogh correct.
