### ISSUE TITLE
test_ceph_metrics_available fails on [IBM P/Z] .

### ISSUE THREAD

**Issue by AaruniAggarwal** [red-hat-storage/ocs-ci#4855]
`tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py::test_ceph_metrics_available ` on errors like : 

```
05:25:43 - MainThread - ocs_ci.ocs.metrics - ERROR - failed to get results for ceph_pg_incomplete
05:25:44 - MainThread - ocs_ci.ocs.metrics - ERROR - failed to get results for ceph_pg_degraded
05:25:44 - MainThread - ocs_ci.ocs.metrics - ERROR - failed to get results for ceph_pg_backfill_unfound
05:25:45 - MainThread - ocs_ci.ocs.metrics - ERROR - failed to get results for ceph_pg_stale
05:25:46 - MainThread - ocs_ci.ocs.metrics - ERROR - failed to get results for ceph_rocksdb_submit_transaction_sync
```

Which leads to the failure of the test:

```
>       assert list_of_metrics_without_results == [], msg
E       AssertionError: OCS Monitoring should provide some value(s) for all tested metrics, so that the list of metrics without results is empty.
E       assert ['ceph_pg_inc...overing', ...] == []
E         Left contains 30 more items, first extra item: 'ceph_pg_incomplete'
E         Full diff:
E           [
E         +  ,
E         -  'ceph_pg_incomplete',
E         -  'ceph_pg_degraded',
E         -  'ceph_pg_backfill_unfound',
E         -  'ceph_pg_stale'...
E         
E         ...Full output truncated (29 lines hidden), use '-vv' to show

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py:155: AssertionError
```

**Comment by AaruniAggarwal** [comment]
run-ci command used for running the above testcase : 

`run-ci -m "tier1" --ocs-version 4.9 --ocsci-conf=conf/ocsci/production_powervs_upi.yaml --ocsci-conf conf/ocsci/lso_enable_rotational_disks.yaml --ocsci-conf /root/ocs-ci-conf.yaml --ocsci-conf conf/ocsci/manual_subscription_plan_approval.yaml --cluster-name "ocstest" --cluster-path /root/openstack-upi --collect-logs tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py::test_ceph_metrics_available`

logfile : 
[ceph-metrics-available.log](https://github.com/red-hat-storage/ocs-ci/files/7195503/ceph-metrics-available.log)

**Comment by AaruniAggarwal** [comment]
ceph status : 

```
[root@rdr-odf49-mon01-bastion-0 ocs-ci]# oc rsh rook-ceph-tools-6758c45f44-2qlpd
sh-4.4$ ceph status
  cluster:
    id:     63bcfa0f-25a3-47eb-87f0-ab97f485c0b5
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 5d)
    mgr: a(active, since 5d)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 5d), 3 in (since 5d)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   13 pools, 241 pgs
    objects: 18.86k objects, 71 GiB
    usage:   214 GiB used, 1.3 TiB / 1.5 TiB avail
    pgs:     241 active+clean
 
  io:
    client:   1.2 KiB/s rd, 19 KiB/s wr, 2 op/s rd, 2 op/s wr

```

Tried running the queries related to `ceph_pg_*` and `ceph_rocksdb_submit_*` from OCP console , but got No datapoints found. 

eg.
![metrics-ceph-pg](https://user-images.githubusercontent.com/47731267/133999435-15dd4e6b-4afe-40c0-bf50-ba9d46b4c4d4.png)

**Comment by AaruniAggarwal** [comment]
FYI, @gitsridhar

**Comment by mbukatov** [comment]
> Tried running the queries related to ceph_pg_* and ceph_rocksdb_submit_* from OCP console , but got No datapoints found.

This means that the test failed as expected, and without further references, there is nothing to be changed in ocs-ci. You need to open a product bug and start a discussion with engineering team to figure out whether this is expected behaviour or a bug.

**Comment by AaruniAggarwal** [comment]
Thanks Martin, I will open a product bug for the same.

**Comment by AaruniAggarwal** [comment]
BZ : https://bugzilla.redhat.com/show_bug.cgi?id=2011173
