### ISSUE TITLE
Workload test case fails to create a pod

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4904]
While executing the testcase:
<Module tests/e2e/workloads/quay/test_quay_operator.py>
<Class TestQuayWorkload>
<Function test_quay>

We see this error:
=================================== FAILURES ===================================
__________________________ TestQuayWorkload.test_quay __________________________

self = <test_quay_operator.TestQuayWorkload object at 0x7fff6f950280>
quay_operator = <ocs_ci.ocs.quay_operator.QuayOperator object at 0x7fff6fec1130>
mcg_obj = <ocs_ci.ocs.resources.mcg.MCG object at 0x7fff6feb02b0>

    @bugzilla("1947796")
    @bugzilla("1959331")
    @pytest.mark.polarion_id("OCS-2596")
    @skipif_ocs_version("<4.7")
    def test_quay(self, quay_operator, mcg_obj):
        """
        Test verifies quay operator deployment and
        whether single OB/OBC are created/bound.
        """
        # Deploy quay operator
>       quay_operator.setup_quay_operator()

tests/e2e/workloads/quay/test_quay_operator.py:40:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ocs_ci/ocs/quay_operator.py:51: in setup_quay_operator
    for quay_pod in TimeoutSampler(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7fff56805d60>

    def __iter__(self):
        if self.start_time is None:
            self.start_time = time.time()
        while True:
            self.last_sample_time = time.time()
            if self.timeout <= (self.last_sample_time - self.start_time):
>               raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 300s running get_pod_name_by_pattern("quay-operator", "openshift-operators")

ocs_ci/utility/utils.py:994: TimeoutExpiredError
---------------------------- Captured stderr setup -----------------------------
Traceback (most recent call last):
  File "/root/venv/lib64/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "/root/ocs-upi-kvm/src/ocs-ci/ocs_ci/utility/environment_check.py", line 98, in assign_get_values
    ns = item.get("spec").get("claimRef").get("namespace")
AttributeError: 'NoneType' object has no attribute 'get'
2021-09-23T21:29:13Z (<ThreadPoolWorker at 0x7fff6f7b77d0 thread_ident=0x7fff6e3af170 threadpool-hub=<Hub at 0x7fff740e7ac0 thread_ident=0x7fff8e3b5e60>>, <function assign_get_values at 0x7fff74708040>) failed with AttributeError

--------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):
  File "/root/venv/lib64/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "/root/ocs-upi-kvm/src/ocs-ci/ocs_ci/utility/environment_check.py", line 98, in assign_get_values
    ns = item.get("spec").get("claimRef").get("namespace")
AttributeError: 'NoneType' object has no attribute 'get'
2021-09-23T21:34:43Z (<ThreadPoolWorker at 0x7fff4ec623b0 thread_ident=0x7fff6e3af170 threadpool-hub=<Hub at 0x7fff740e7ac0 thread_ident=0x7fff8e3b5e60>>, <function assign_get_values at 0x7fff74708040>) failed with AttributeError

=============================== warnings summary ===============================
/root/venv/lib64/python3.8/site-packages/_pytest/mark/structures.py:323
  /root/venv/lib64/python3.8/site-packages/_pytest/mark/structures.py:323: PytestUnknownMarkWarning: Unknown pytest.mark.magenta_squad - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    warnings.warn(

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================== 1 failed, 1 warning in 347.11s (0:05:47) ===================
                                                                                                                                                                        2130,1        Bot

Is this test case passing for other components? We find that the pod named quad_operator.

**Comment by parikshithb** [comment]
Fixed in: https://github.com/red-hat-storage/ocs-ci/pull/4942
