### ISSUE TITLE
ocs-ci performance test fails to find image

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4928]
Tried to execute 
tests/e2e/performance/test_fio_benchmark.py::TestFIOBenchmark::test_fio_workload_simple[CephBlockPool-sequential]

and it failed to find elastic-operator-0 pod: 

oc describe pod elastic-operator-0 -n elastic-system

Events:
  Type     Reason          Age                  From               Message
  ----     ------          ----                 ----               -------
  Normal   Scheduled       2m16s                default-scheduler  Successfully assigned elastic-system/elastic-operator-0 to rdr-sri-26f5-syd04-worker-2
  Normal   AddedInterface  2m15s                multus             Add eth0 [10.129.2.28/23] from openshift-sdn
  Normal   Pulling         45s (x4 over 2m14s)  kubelet            Pulling image "docker.elastic.co/eck/eck-operator:1.7.1"
  Warning  Failed          42s (x4 over 2m12s)  kubelet            Failed to pull image "docker.elastic.co/eck/eck-operator:1.7.1": rpc error: code = Unknown desc = choosing image instance: no image found in manifest list for architecture ppc64le, variant "", OS linux
  Warning  Failed          42s (x4 over 2m12s)  kubelet            Error: ErrImagePull
  Warning  Failed          16s (x6 over 2m12s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff         3s (x7 over 2m12s)   kubelet            Back-off pulling image "docker.elastic.co/eck/eck-operator:1.7.1"

This is happening from ppc64le environment. Is there a workaround?

**Comment by Avilir** [comment]
This is not elasticsearch issue, it is codespeed issue, and we need to remove the codespeed since we are not using it anymore.
