### ISSUE TITLE
ODF 4.9 deploy is failing.

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#4951]
ODF deploy is failing due to missign ocs-operator csv.

The code is now trying to deploy 4.9.1 as latest 4.9. And it is looking for ocs-operator csv.

12:20:32 - MainThread - ocs_ci.ocs.ocp - INFO - Cannot find resource object ocs-operator.v4.9.1
12:20:32 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 5 seconds before next iteration
12:20:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get csv ocs-operator.v4.9.1 -n openshift-storage -o yaml
12:20:37 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): clusterserviceversions.operators.coreos.com "ocs-operator.v4.9.1" not found

12:20:37 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: ocs-operator.v4.9.1 of kind: csv, selector: None, Error: Error during execution of command: oc -n openshift-storage get csv ocs-operator.v4.9.1 -n openshift-storage -o yaml.
Error is Error from server (NotFound): clusterserviceversions.operators.coreos.com "ocs-operator.v4.9.1" not found

[root@nx124-49-145c-syd04-bastion-0 ~]# oc get csv -A
NAMESPACE                              NAME                                        DISPLAY                     VERSION              REPLACES   PHASE
openshift-local-storage                local-storage-operator.4.9.0-202110012022   Local Storage               4.9.0-202110012022              Succeeded
openshift-operator-lifecycle-manager   packageserver                               Package Server              0.18.3                          Succeeded
openshift-storage                      odf-operator.v4.9.1                         OpenShift Data Foundation   4.9.1                           Succeeded
[root@nx124-49-145c-syd04-bastion-0 ~]#

**Comment by gitsridhar** [comment]
@petr-balogh we are not overwriting what ocs-ci does: 

16:04:09 - MainThread - ocs_ci.utility.templating - INFO - apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    ocs-operator-internal: 'true'
  name: ocs-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: Openshift Container Storage
  icon:
    base64data: ''
    mediatype: ''
  image: quay.io/rhceph-dev/ocs-registry:latest-4.9
  priority: 100
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 15m

So answer to your question: latest-4.9

Subscription used is:
16:05:03 - MainThread - ocs_ci.utility.templating - INFO - apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: stable-4.9
  installPlanApproval: Manual
  name: odf-operator
  source: ocs-catalogsource
  sourceNamespace: openshift-marketplace

**Comment by gitsridhar** [comment]
What I mentioned above must be a temporary issue, on another deployment I do not see above error. But the code is still looking for ocs-operator and it is not found. 

[root@nx124-49-1d60-syd04-bastion-0 ~]# oc get csv -A
NAMESPACE                              NAME                                        DISPLAY                     VERSION              REPLACES   PHASE
openshift-local-storage                local-storage-operator.4.9.0-202110121402   Local Storage               4.9.0-202110121402              Succeeded
openshift-operator-lifecycle-manager   packageserver                               Package Server              0.18.3                          Succeeded
openshift-storage                      odf-operator.v4.9.0                         OpenShift Data Foundation   4.9.0                           Installing
[root@nx124-49-1d60-syd04-bastion-0 ~]# oc get pods -n openshift-storage
NAME                                              READY   STATUS             RESTARTS         AGE
odf-console-5d8c99fcb-7rv2c                       1/1     Running            0                41m
odf-operator-controller-manager-864978c95-smd94   1/2     CrashLoopBackOff   11 (4m39s ago)   41m
[root@nx124-49-1d60-syd04-bastion-0 ~]# oc logs odf-operator-controller-manager-864978c95-smd94 -n openshift-storage manager
I1013 18:40:47.308894       1 request.go:655] Throttling request took 1.007398173s, request: GET:https://172.30.0.1:443/apis/console.openshift.io/v1alpha1?timeout=32s
2021-10-13T18:40:48.619Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
2021-10-13T18:40:48.619Z        INFO    setup   starting console
2021-10-13T18:40:48.649Z        INFO    setup   starting manager
I1013 18:40:48.701277       1 leaderelection.go:243] attempting to acquire leader lease openshift-storage/4fd470de.openshift.io...
2021-10-13T18:40:48.701Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
I1013 18:41:06.162066       1 leaderelection.go:253] successfully acquired lease openshift-storage/4fd470de.openshift.io
2021-10-13T18:41:06.162Z        INFO    controller-runtime.manager.controller.storagecluster    Starting EventSource    {"reconciler group": "ocs.openshift.io", "reconciler kind": "StorageCluster", "source": "kind source: /, Kind="}
2021-10-13T18:41:06.162Z        INFO    controller-runtime.manager.controller.storagesystem     Starting EventSource    {"reconciler group": "odf.openshift.io", "reconciler kind": "StorageSystem", "source": "kind source: /, Kind="}
2021-10-13T18:41:06.162Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ConfigMap","namespace":"openshift-storage","name":"4fd470de.openshift.io","uid":"448c822c-854f-4951-a797-a5240fe13b23","apiVersion":"v1","resourceVersion":"49028"}, "reason": "LeaderElection", "message": "odf-operator-controller-manager-864978c95-smd94_b533a83a-9d29-46b2-a97d-83a9ecd2fc4f became leader"}
2021-10-13T18:41:06.162Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"Lease","namespace":"openshift-storage","name":"4fd470de.openshift.io","uid":"9a90c9ff-535d-40f7-82ae-7eb76fabdd92","apiVersion":"coordination.k8s.io/v1","resourceVersion":"49029"}, "reason": "LeaderElection", "message": "odf-operator-controller-manager-864978c95-smd94_b533a83a-9d29-46b2-a97d-83a9ecd2fc4f became leader"}
I1013 18:41:07.212918       1 request.go:655] Throttling request took 1.045836982s, request: GET:https://172.30.0.1:443/apis/admissionregistration.k8s.io/v1?timeout=32s
2021-10-13T18:41:08.566Z        ERROR   controller-runtime.source       if kind is a CRD, it should be installed before calling Start   {"kind": "StorageCluster.ocs.openshift.io", "error": "no matches for kind \"StorageCluster\" in version \"ocs.openshift.io/v1\""}
github.com/go-logr/zapr.(*zapLogger).Error
        /remote-source/deps/gomod/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/source/source.go:117
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:167
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:223
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:681
2021-10-13T18:41:08.566Z        ERROR   controller-runtime.manager      error received after stop sequence was engaged  {"error": "Timeout: failed waiting for *v1alpha1.StorageSystem Informer to sync"}
github.com/go-logr/zapr.(*zapLogger).Error
        /remote-source/deps/gomod/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:530
2021-10-13T18:41:38.567Z        ERROR   setup   problem running manager {"error": "[no matches for kind \"StorageCluster\" in version \"ocs.openshift.io/v1\", failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]", "errorCauses": [{"error": "no matches for kind \"StorageCluster\" in version \"ocs.openshift.io/v1\""}, {"error": "failed waiting for all runnables to end within grace period of 30s: context deadline exceeded"}]}
github.com/go-logr/zapr.(*zapLogger).Error
        /remote-source/deps/gomod/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
        /remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.main
        /remote-source/app/main.go:150
runtime.main
        /usr/lib/golang/src/runtime/proc.go:225
[root@nx124-49-1d60-syd04-bastion-0 ~]# 

We are now seeing redhat-operators in CatalogSource:
14:03:24 - MainThread - ocs_ci.utility.templating - INFO - apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    ocs-operator-internal: 'true'
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  displayName: Openshift Container Storage
  icon:
    base64data: ''
    mediatype: ''
  image: quay.io/rhceph-dev/ocs-registry:latest-4.9
  priority: 100
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 15m

**Comment by gitsridhar** [comment]
As you can see in the previous comment
[root@nx124-49-1d60-syd04-bastion-0 ~]# oc get pods -n openshift-storage
NAME READY STATUS RESTARTS AGE
odf-console-5d8c99fcb-7rv2c 1/1 Running 0 41m
odf-operator-controller-manager-864978c95-smd94 1/2 CrashLoopBackOff 11 (4m39s ago) 41m
[root@nx124-49-1d60-syd04-bastion-0 ~]

the odf operator pod is crashing. And its logs are in the above comment.

**Comment by petr-balogh** [comment]
Hey @gitsridhar I am still curious why you are getting latest-4.9 tag in catalog source.  Are you passing that specific image:latest-4.9 tag to run-ci command via --ocs-registry-image argument?  By default as I pointed out we should use: `latest-stable-4.9` and there is a reason why we are using those. The `latest-4.9` build can be broken one build. `latest-stable-4.9` is tagged only when the build passes the deployment/acceptance testing on AWS platform. So you can be at least sure that the build was deployable on this platform.

From your comments I see that the issues mentioned above were maybe some temp issues.

I have few questions, are you trying the deployment on fresh OCP cluster? Or you are doing uninstall and trying new deployment on the same cluster?

If not, can you please check on fresh new OCP cluster?

Worth to not use latest-4.9 build, it doesn't have to be even specified via --ocs-registry-image and ocs-ci if it has proper token for quay in auth.yaml (Please do not share here!) file it should query quay.io to translate latest tag to some specific build - which is better option.

Anyway, this is now looks like more some product issue instead of ocs-ci issue so I would close this after your reply. We can take the discussion offline in google chat or have some meeting to discuss.

**Comment by mbukatov** [comment]
I run into a similar issue yesterday:

```
13:22:46 - MainThread - ocs_ci.ocs.ocp - INFO - Cannot find resource object ocs-operator.v4.9.0
13:22:46 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 5 seconds before next iteration
13:22:51 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get csv ocs-operator.v4.9.0 -n openshift-storage -o yaml
13:22:52 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): clusterserviceversions.operators.coreos.com "ocs-operator.v4.9.0" not found
```

Since I suspected some ocs-ci issue behind this, I just run teardown and upgraded ocs-ci to latest stable `stable-ocs-4.9-202110131057` and then it worked fine.

Problem described in BZ 2009531 seems not directly related.
