### ISSUE TITLE
storagesystem name on UI reflects a different name when an ODF 4.9 cluster is deployed via ocs-ci (Jenkins)

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#4969]
If the installation is done via UI, the storagesystem name is shown as 'ocs-storagecluster-storagesystem' whereas, if we deploy the cluster via Jenkins, the name is displayed as 'storagesystem-odf'. We need to keep it consistent as it may be the cause of many UI automation test failures due to name mismatch.

@vavuthu @jilju @OdedViner @ebenahar

**Comment by vavuthu** [comment]
PR : https://github.com/red-hat-storage/ocs-ci/pull/4952
