### ISSUE TITLE
Add a check in tox that validates logging library is not used directly

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#4975]
There were some occurrences in the repository where the logging library is used directly rather than using the singleton instantiation in each file.
For i.e
```python
import logging
logger = logging.getLogger(__name__)

# Should be:
logger.info('log')

# Where as sometimes it is:
logging.info('log')
```

A fix for this will include a fix in `tox.ini`.
Also, we will fix the current occurrences where it uses the library directly in the entire repository

**Comment by clacroix12** [comment]
This is something we should still do
