### ISSUE TITLE
noobaa-endpoint pod deployment with unsupport memory allocation 100M

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#4995]
The current default memory allocate for noobaa-endpoint pod is 100Mi which is not supported.  In order to perform I/O activity and other noobaa tests, we need to deploy noobaa-endpoint with 2GB of memory.
https://github.com/red-hat-storage/ocs-operator/blob/d7eab855e07aa6be099ff45e1ad6cee6d7167e6e/controllers/defaults/resources.go#L97

With the current deployment, we are seeing noobaa-endpoints is in CrashLoopBackOff while creating OBCs.
https://bugzilla.redhat.com/show_bug.cgi?id=2015756
https://bugzilla.redhat.com/show_bug.cgi?id=2015728

**Comment by tiffanyn108** [comment]
@vavuthu With 100M memory, noobaa-endpoint restarts and in CrashLoopBackOff when performing noobaa testing.  We need to set memory request and limit to a higher number.

**Comment by tiffanyn108** [comment]
@vavuthu I dont have a number.  According to Nimbrod, "ODF deployment comes with 2GB request and limit".  What number did we use before reduce to 100M?

**Comment by tiffanyn108** [comment]
@vavuthu We will use production deployment for scale testing.

**Comment by bernerhat** [comment]
@tiffanyn108 this was discussed a long time ago with a bug i've opened and was handled at the time by Ohad, when testing noobaa in the future please use a cluster configuration where allow_lower_instance_requirements is not enabled
