### ISSUE TITLE
RFE: Create a common place for basic functionalities

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#50]
For example, functions like pv create and delete, which are currently implemented in tests/test_pv_creation.py [1], should be in a commonplace.

[1] https://github.com/red-hat-storage/ocs-ci/pull/43/files/dbf2d5d41b69c9a032385cca66c549a3a8f3a032#diff-2b4e26e7e510a40da374e0d8ece59f04

**Comment by vasukulkarni** [comment]
Yeah once the functionalities move to proper class, I think it will only get better and there will be no duplication.
