### ISSUE TITLE
Q-PAS pipeline job requirements

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#5009]
**1. Performance IO_Workload/CSI pipeline job**
**Requirements**

**a)** This pipeline is planned to execute selected IO_Workload and CSI tests for a week on same setup.

**b)** How this pipeline will be used?
        We wanted this to be fully automated i.e. auto trigger test based on flow but again need some flexibility to start manually and to change params like DC, platform conf, etc (Default this can be DC_PS VSAN UPI)

**c)** Tests to be executed 
        It will be used mostly for IO_Workload test and CSI tests, we are not going to create multiple tier markers here since in future we might add more scenario and the markers will keep increasing so we decided to use directory structure instead of multiple markers.

>      tests/e2e/performance/IO_workload
>      tests/e2e/performance/csi

**Note:** Directories are yet to be created, again would like to keep this flexible so in future if we create new dir we should be able to use them

**d)** OCP/ODF Version -- Latest Stable version
       We would like to fix this default to 4.9 for now but again require flexibility so that this can be used for n-1 or n+1 configs too i.e. OCP 4.8 + ODF 4.9 and vice versa

**e)** Flow of pipeline -- Want this pipeline to be executed for 1 week (7 days) with below breakup, as we discussed in the Automation meeting it will require cron job to auto trigger once the pipeline started.
```
    Day-1: Deploy cluster and Start tests/e2e/performance/IO_workload tests
    Day-2: Execute tests/e2e/performance/csi tests 
    Day-3: Execute tests/e2e/performance/csi tests 
    Day-4: Execute tests/e2e/performance/csi tests 
    Day-5: Execute tests/e2e/performance/csi tests 
    Day-6: Execute tests/e2e/performance/csi tests 
    Day-7: Execute tests/e2e/performance/IO_workload tests and destroy cluster.
```
**Note:** In Automation meeting we discussed about triggering the CSI test twice in a day, we checked the test run-time which is exceeding 12hrs, that's the reason we changed the req to execute one time in a day.

**d)** During above entire flow we would like to use the same cluster with same version, on 8th day(i.e. next week) again above flow starts so plan is to run this continuously during the release.

**e)** Good to get options/flexibility in the flow, eg: In 7 days, test dir can be executed 3 times and more, or it can be open text box where we can mention the flow with space i.e. _test-dir1 test-dir2 test-dir2 test-dir2 test-dir2 test-dir2 test-dir1_

==============================================================================================

**2. Performance Flexible pipeline job**
**Requirements**

**a)** This pipeline will be used for executing same test repeatedly(or given number of time) in same setup i.e. setup deployed one time and execute same test n times and destroy setup.

**b)** This should be something similar to PR validation job with params like TEST_PATH, OCP/OCS Version, OSD_SIZE, EMAIL, CREDENTIAL_CONF, PLATFORM_CONF, FULL_PLATFORM_CONF, COLLECT_LOGS(default can be disabled), USE_EXISTING_CLUSTER, SKIP_CLUSTER_VALIDATION, etc.

**c)** Require this new param TEST_EXECUTION_COUNT default can be 1 but user should have option to specify the required count.

**d)** This job will be used on need basis something similar to PR validation job and doesn't require to be part of any nightly auto execution.

==============================================================================================

**Comment by dahorak** [comment]
Hey @ramkiperiy,

> **1. Performance IO_Workload/CSI pipeline job** **Requirements**
> 
> **a)** This pipeline is planned to execute selected IO_Workload and CSI tests for a week on same setup.
> 
> **b)** How this pipeline will be used? We wanted this to be fully automated i.e. auto trigger test based on flow but again need some flexibility to start manually and to change params like DC, platform conf, etc (Default this can be DC_PS VSAN UPI)

How often do you expect this to be changed (the DC, platform conf,...)? For manually triggered job, it is easy to change any parameter directly when launching the job, but for automatically triggered job via cron, any change has to be done in the job configuration (which means: create merge request in the ocs4-jenkins repository and apply the changes - regenerate the jobs, it is easy, but just not directly possible via Jenkins UI).
This apply also to other parameter changes.

> 
> **c)** Tests to be executed It will be used mostly for IO_Workload test and CSI tests, we are not going to create multiple tier markers here since in future we might add more scenario and the markers will keep increasing so we decided to use directory structure instead of multiple markers.
> 
> > ```
> >  tests/e2e/performance/IO_workload
> >  tests/e2e/performance/csi
> > ```
>
> **Note:** Directories are yet to be created, again would like to keep this flexible so in future if we create new dir we should be able to use them
 
The same question and note as above.

> **d)** OCP/ODF Version -- Latest Stable version We would like to fix this default to 4.9 for now but again require flexibility so that this can be used for n-1 or n+1 configs too i.e. OCP 4.8 + ODF 4.9 and vice versa
 
The same question and note as above.

> **e)** Flow of pipeline -- Want this pipeline to be executed for 1 week (7 days) with below breakup, as we discussed in the Automation meeting it will require cron job to auto trigger once the pipeline started.
> 
> ```
>     Day-1: Deploy cluster and Start tests/e2e/performance/IO_workload tests
>     Day-2: Execute tests/e2e/performance/csi tests 
>     Day-3: Execute tests/e2e/performance/csi tests 
>     Day-4: Execute tests/e2e/performance/csi tests 
>     Day-5: Execute tests/e2e/performance/csi tests 
>     Day-6: Execute tests/e2e/performance/csi tests 
>     Day-7: Execute tests/e2e/performance/IO_workload tests and destroy cluster.
> ```

If I understand it correctly, all the jobs should be triggered via cron, but it should be possible to do it also manually (e.g. re-trigger the daily pipeline with different test suite or reinstall the whole cluster in the middle of the week with different configuration), right?

> 
> **Note:** In Automation meeting we discussed about triggering the CSI test twice in a day, we checked the test run-time which is exceeding 12hrs, that's the reason we changed the req to execute one time in a day.
> 
> **d)** During above entire flow we would like to use the same cluster with same version, on 8th day(i.e. next week) again above flow starts so plan is to run this continuously during the release.
> 
> **e)** Good to get options/flexibility in the flow, eg: In 7 days, test dir can be executed 3 times and more, or it can be open text box where we can mention the flow with space i.e. _test-dir1 test-dir2 test-dir2 test-dir2 test-dir2 test-dir2 test-dir1_

I just find out, that it should be possible to trigger job via cron, with different parameters (not only the defaults), but still this have to be configured in the job itself (via merge request to ocs4-jenkins repo as mentioned above), not possible to do it from Jenkins UI.

> 
> ==============================================================================================
> 
> **2. Performance Flexible pipeline job** **Requirements**
> 
> **a)** This pipeline will be used for executing same test repeatedly(or given number of time) in same setup i.e. setup deployed one time and execute same test n times and destroy setup.
> 
> **b)** This should be something similar to PR validation job with params like TEST_PATH, OCP/OCS Version, OSD_SIZE, EMAIL, CREDENTIAL_CONF, PLATFORM_CONF, FULL_PLATFORM_CONF, COLLECT_LOGS(default can be disabled), USE_EXISTING_CLUSTER, SKIP_CLUSTER_VALIDATION, etc.
> 
> **c)** Require this new param TEST_EXECUTION_COUNT default can be 1 but user should have option to specify the required count.
> 
> **d)** This job will be used on need basis something similar to PR validation job and doesn't require to be part of any nightly auto execution.
> 

If I understanding it correctly, this job should (by default) install new cluster, run the test there n-times and then destroy the cluster. But it should be possible to just run the test n-times on existing cluster defined by name - the same way how it is for PR validation job, right?

**Comment by ramkiperiy** [comment]
@dahorak I replied in-line

> Hey @ramkiperiy,
> 
> > **1. Performance IO_Workload/CSI pipeline job** **Requirements**
> > **a)** This pipeline is planned to execute selected IO_Workload and CSI tests for a week on same setup.
> > **b)** How this pipeline will be used? We wanted this to be fully automated i.e. auto trigger test based on flow but again need some flexibility to start manually and to change params like DC, platform conf, etc (Default this can be DC_PS VSAN UPI)
> 
> How often do you expect this to be changed (the DC, platform conf,...)? For manually triggered job, it is easy to change any parameter directly when launching the job, but for automatically triggered job via cron, any change has to be done in the job configuration (which means: create merge request in the ocs4-jenkins repository and apply the changes - regenerate the jobs, it is easy, but just not directly possible via Jenkins UI). This apply also to other parameter changes.
> 

Yes, I understand the problem in case of Completely automated, I added the requirements for other tests executions but for now we are good with only CSI and IO workload tests.
For cron all the test execution should be in DC_PS and vmware UPI.

> > **c)** Tests to be executed It will be used mostly for IO_Workload test and CSI tests, we are not going to create multiple tier markers here since in future we might add more scenario and the markers will keep increasing so we decided to use directory structure instead of multiple markers.
> > > ```
> > >  tests/e2e/performance/IO_workload
> > >  tests/e2e/performance/csi
> > > ```
> > 
> > 
> > **Note:** Directories are yet to be created, again would like to keep this flexible so in future if we create new dir we should be able to use them
> 
> The same question and note as above.

For now we are good with only CSI and IO workload tests for cron automation.

> 
> > **d)** OCP/ODF Version -- Latest Stable version We would like to fix this default to 4.9 for now but again require flexibility so that this can be used for n-1 or n+1 configs too i.e. OCP 4.8 + ODF 4.9 and vice versa
> 
> The same question and note as above.

This release we planned only OCP 4.9 and ODF 4.9 for corn automation consider the same.

> 
> > **e)** Flow of pipeline -- Want this pipeline to be executed for 1 week (7 days) with below breakup, as we discussed in the Automation meeting it will require cron job to auto trigger once the pipeline started.
> > ```
> >     Day-1: Deploy cluster and Start tests/e2e/performance/IO_workload tests
> >     Day-2: Execute tests/e2e/performance/csi tests 
> >     Day-3: Execute tests/e2e/performance/csi tests 
> >     Day-4: Execute tests/e2e/performance/csi tests 
> >     Day-5: Execute tests/e2e/performance/csi tests 
> >     Day-6: Execute tests/e2e/performance/csi tests 
> >     Day-7: Execute tests/e2e/performance/IO_workload tests and destroy cluster.
> > ```
> 
> If I understand it correctly, all the jobs should be triggered via cron, but it should be possible to do it also manually (e.g. re-trigger the daily pipeline with different test suite or reinstall the whole cluster in the middle of the week with different configuration), right?



> 
> > **Note:** In Automation meeting we discussed about triggering the CSI test twice in a day, we checked the test run-time which is exceeding 12hrs, that's the reason we changed the req to execute one time in a day.
> > **d)** During above entire flow we would like to use the same cluster with same version, on 8th day(i.e. next week) again above flow starts so plan is to run this continuously during the release.
> > **e)** Good to get options/flexibility in the flow, eg: In 7 days, test dir can be executed 3 times and more, or it can be open text box where we can mention the flow with space i.e. _test-dir1 test-dir2 test-dir2 test-dir2 test-dir2 test-dir2 test-dir1_
> 
> I just find out, that it should be possible to trigger job via cron, with different parameters (not only the defaults), but still this have to be configured in the job itself (via merge request to ocs4-jenkins repo as mentioned above), not possible to do it from Jenkins UI.

I added above point based on future request, for now we will be following the flow mentioned in section "e" but above param or flow is to run different tests in future.

> 
> > ==============================================================================================
> > **2. Performance Flexible pipeline job** **Requirements**
> > **a)** This pipeline will be used for executing same test repeatedly(or given number of time) in same setup i.e. setup deployed one time and execute same test n times and destroy setup.
> > **b)** This should be something similar to PR validation job with params like TEST_PATH, OCP/OCS Version, OSD_SIZE, EMAIL, CREDENTIAL_CONF, PLATFORM_CONF, FULL_PLATFORM_CONF, COLLECT_LOGS(default can be disabled), USE_EXISTING_CLUSTER, SKIP_CLUSTER_VALIDATION, etc.
> > **c)** Require this new param TEST_EXECUTION_COUNT default can be 1 but user should have option to specify the required count.
> > **d)** This job will be used on need basis something similar to PR validation job and doesn't require to be part of any nightly auto execution.
> 
> If I understanding it correctly, this job should (by default) install new cluster, run the test there n-times and then destroy the cluster. But it should be possible to just run the test n-times on existing cluster defined by name - the same way how it is for PR validation job, right?

Yes, that's right

**Comment by ramkiperiy** [comment]
@dahorak would like to know where are we with the jenkins job, wrt tests movement to directories, stability and dashboard integration are already covered from Q-PAS members and it's in good shape.

**Comment by dahorak** [comment]
Hi @ramkiperiy, sorry for no update before the last year's shutdown, I was quite busy with all the unexpected releases.

[This is the initial version of the job](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/dahorak-qe-q-pas-deploy-destroy/build?delay=0sec) which will be triggered once a week (please do not trigger it yet, it doesn't trigger the actual cluster deployment) - I called it `Q-PAS Deploy-Destroy` (now it have prefix `dahorak` just to make clear, that it is in WIP state and nobody will trigger it by accident).

By default, the job firstly destroy the existing (old) cluster and then trigger deployment of a new one. For some corner/not automatic cases, it is possible to trigger only the destroy old cluster part (parameter `DESTROY_OLD_CLUSTER`) or only the deployment of a new cluster (parameter `DEPLOY_NEW_CLUSTER`, this expect, that the old cluster doesn't exists).

The parameters in the job can be split to following 4 sections:
* The two parameters mentioned above (something like general parameters).
* Parameters for old cluster (those parameters controls, which tests will be executed on the old cluster before teardown - they have `OLD_` prefix)
* Parameters for newly installed cluster (those are similar parameters as what you can find on normal Deploy OCS cluster job, there you can control installed OCP/ODF versions, credentials conf, platform conf etc. and also the tests which will be executed on the freshly installed cluster.
* Job related parameters (ocs-ci repository and branch and job repository and branch).

I would like to separate those sections of parameters visually, so it will be clear which parameter is related to old cluster and which to the new one (and which are general for the whole job) - you can see it on the following screenshot (it is not yet visible on job I linked above, because of some issues with the automatic generation of the job, hopefully I'll be able to find a way how to fix it):
![2022-01-10_q-pas_pipeline](https://user-images.githubusercontent.com/4759779/148747851-ab5ed138-60af-4968-8bf8-a58b64fcd9d4.png)

Could you please review the list of parameters in the job and let me know, if there are some parameters unnecessary (e.g. you will newer use some option) or some other missing? And could you also write me there what should be the default values for the parameters (those values will be used, for the automatic execution via cron)?

And [this is the second job](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/dahorak-qe-q-pas-daily/build?delay=0sec) - triggering the every day tests. The `CLUSTER_CONF` and `YAML_TEXT_CONFIG` parameter there are not for configuration files related to the deployment type, platform etc., but for some additional configuration which might be required for some tests (mainly ad-hoc). The deployment and platform related configuration files will be loaded automatically from what was provided during the cluster deployment.

**Comment by ramkiperiy** [comment]
Thanks for the update @dahorak, will review with team and update it here.

**Comment by ramkiperiy** [comment]
@dahorak we have reviewed and jenkins job looks good :) Thanks for your efforts on developing this.

Below are some the param related comments:

1. In deploy-destroy pipeline we might need one more param to execute same test(or the set of tests) repeatedly for n times.
2. TEST_MARK_EXPRESSION --> Param can be default to **Performance**
3. IO_IN_BACKGROUND --> Param can be removed since most of IO's are ran in controlled way
4. TEST_PATH --> This can be changed to tests/e2e/performance as default but even tests/ would do due to the marker 

@Avilir @ypersky1980 @keesturam ^^

**Comment by dahorak** [comment]
>     1. In deploy-destroy pipeline we might need one more param to execute same test(or the set of tests) repeatedly for n times.
I'm now reviewing possible solution for this, will update about my findings later.

>     2. TEST_MARK_EXPRESSION --> Param can be default to **Performance**
This should be set to `performance` for all the jobs? In other words all `performance` tests will be executed in all following cases:
1. after new cluster is installed,
2. in the daily job,
3. before the cluster is destroyed?

My initial understanding was, that it in each phase will be triggered different tests, so I want to confirm that. 

>     4. TEST_PATH --> This can be changed to tests/e2e/performance as default but even tests/ would do due to the marker

Same question as for `2. TEST_MARK_EXPRESSION ...` - of course it depends if we will select the tests via mark or path or combination.

**Comment by ramkiperiy** [comment]
> > ```
> > 2. TEST_MARK_EXPRESSION --> Param can be default to **Performance**
> > ```
> 
> This should be set to `performance` for all the jobs? In other words all `performance` tests will be executed in all following cases:
> 
>     1. after new cluster is installed,
> 
>     2. in the daily job,
> 
>     3. before the cluster is destroyed?
> 
Yes, Fill the text box with Performance as default we are planning only for perf tests, but it will be editable option right? In-case in future can be used for other tiers as well.
> 
> My initial understanding was, that it in each phase will be triggered different tests, so I want to confirm that.
> 
> > ```
> > 4. TEST_PATH --> This can be changed to tests/e2e/performance as default but even tests/ would do due to the marker
> > ```
> 
> Same question as for `2. TEST_MARK_EXPRESSION ...` - of course it depends if we will select the tests via mark or path or combination.
So we will have options like tests can be started with marker/tier/path like we have cluster deploy job now? combination meaning updating all param will run specific tests, is my understanding correct here?

In-case of daily job execution since it's auto triggered won't it be better to specify the right folder ? since there are tests with same marker in other folders too. In that case better update it with default **tests/e2e/performance/csi_tests/**

**Comment by dahorak** [comment]
@ramkiperiy

> Yes, Fill the text box with Performance as default we are planning only for perf tests, but it will be editable option right? In-case in future can be used for other tiers as well.

* When it will be triggered automatically via cron, it will use the default value (`performance`), if you will trigger it manually, you can fill there anything you want,
* the default vale (`performance`) can be easily changed in the future (via merge request in our ocs4-jenkins repository).

> So we will have options like tests can be started with marker/tier/path like we have cluster deploy job now? combination meaning updating all param will run specific tests, is my understanding correct here?

Yes for the first question. By combination I meant, that you can select all tests with particular mark but just from some specific path, exactly like you mentioned below: _all tests marked as `performance` from `tests/e2e/performance/csi_tests/` folder.

> In-case of daily job execution since it's auto triggered won't it be better to specify the right folder? since there are tests with same marker in other folders too. In that case better update it with default **tests/e2e/performance/csi_tests/**

Yes, if you want to run daily only `performance` tests from `tests/e2e/performance/csi_tests/` folder, than it will make sense to configure this path as default for the daily job -> I'll do it.

One more question - should be the job for reinstalling the cluster triggered once a week also automatically via cron? Or would you like to always trigger it always manually? (If it will be triggered automatically via cron, then you can of course trigger it also manually - you will just have to count with the time, when it is triggered via cron, so it will for example not destroy the cluster you just created manually.)

**Comment by dahorak** [comment]
@ramkiperiy One more question come into my mind - what should be default value for `EMAIL` parameter - where should be send the tests results and job failures?

**Comment by ramkiperiy** [comment]
@dahorak sorry for late reply, please check my replies in-line hope this helps.

>     * When it will be triggered automatically via cron, it will use the default value (`performance`), if you will trigger it manually, you can fill there anything you want,
> 
>     * the default vale (`performance`) can be easily changed in the future (via merge request in our ocs4-jenkins repository).
> 

+1 

> 
> Yes, if you want to run daily only `performance` tests from `tests/e2e/performance/csi_tests/` folder, than it will make sense to configure this path as default for the daily job -> I'll do it.

yes, this will help especially on the auto triggering.
> 
> One more question - should be the job for reinstalling the cluster triggered once a week also automatically via cron? Or would you like to always trigger it always manually? (If it will be triggered automatically via cron, then you can of course trigger it also manually - you will just have to count with the time, when it is triggered via cron, so it will for example not destroy the cluster you just created manually.)

Yes, let's plan for automatic execution via cron and as you mentioned have to be handled carefully if we are triggering it manually, may be Resource locking will help here to queue the request.
Hope killing the job would be similar way we have now in Jenkins

> @ramkiperiy One more question come into my mind - what should be default value for `EMAIL` parameter - where should be send the tests results and job failures?

Default set it to `ocsqe-qpas@redhat.com`

**Comment by dahorak** [comment]
Hey @ramkiperiy,
I moved little bit closer to the final state. 

Those are the job:
* [Q-PAS Deploy-Destroy](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-q-pas-deploy-destroy/build?delay=0sec) - it will be triggered once a week to destroy existing cluster and deploy new one (including the tests executed on the old cluster before the destroy and on the new cluster after the deployment),
* [Q-PAS Daily](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-q-pas-daily/build?delay=0sec) - this job will be triggered every day (except the day when will be triggered the Deploy-Destroy job) and will launch the daily test suite.

Could you please review the jobs parameters and default values (if there is everything you might need and if it is configured correctly)?
(Please ignore the values in `JOBS_REPOSITORY` and `JOBS_REPOSITORY_BRANCH` parameters, those will be updated just before the merge.)
Also we still didn't fully solved the issue with Parameters Separator plugin, so all the parameters in _Q-PAS Deploy-Destroy_ job are together (not visibly separated parameters for the old cluster, new cluster and others).

All the changes are in this [MR!874](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/874) in ocs4-jenkins repository.

**Comment by dahorak** [comment]
@ramkiperiy please review the jobs and questions from previous comment and provide your input.

**Comment by ramkiperiy** [comment]
@dahorak I have reviewed it and got it reviewed by team members too, job params are looking good.
