### ISSUE TITLE
[IBM Z] Benchmark-operator related tests in tier2 fails due to timeout

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#5018]
Below mentioned tests under tier2 related to benchmark-operator are failing due to timeout.

@yselkowitz helped us preparing multi-arch images for IBM Z. But ocs-ci tests are Failing due to Timeout. I can see all pods are up and running.

Tests:
```
tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py::TestCompressedSCAndSupportSnapClone::test_compressed_sc_and_support_snap_clone[2-aggressive]

tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py::TestPvcCloneOfWorkloads::test_pvc_clone

tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py::TestPvcSnapshotOfWorkloads::test_pvc_snapshot

tests/e2e/workloads/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py::TestPvcResizeOfClonedAndRestoredPVC::test_pvc_resize

tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py::TestCompressedSCAndSupportSnapClone::test_compressed_sc_and_support_snap_clone[3-aggressive]
```

Error:
```
E               ocs_ci.ocs.exceptions.UnexpectedBehaviour: pgbench-1-dbs-client-1-343b1c1e-wzfcv did not reach to Completed state after 900 sec
E               Init Database postgres-2.postgres/testdb
E               dropping old tables...
E               NOTICE:  table "pgbench_accounts" does not exist, skipping
E               NOTICE:  table "pgbench_branches" does not exist, skipping
E               NOTICE:  table "pgbench_history" does not exist, skipping
E               NOTICE:  table "pgbench_tellers" does not exist, skipping
E               creating tables...
E               generating data...
E               100000 of 200000 tuples (50%) done (elapsed 0.05 s, remaining 0.05 s)
E               200000 of 200000 tuples (100%) done (elapsed 0.93 s, remaining 0.00 s)
E               vacuuming...
E               creating primary keys...
E               done.
E               Waiting for start signal...
E               3
```

Pods:
```
[root@m4204001 ~]# oc -n benchmark-operator get pod
NAME                                           READY   STATUS    RESTARTS   AGE
benchmark-controller-manager-bcdcbc584-5xhsk   2/2     Running   0          3m49s
pgbench-1-dbs-client-1-0ed0b6fb--1-qsprd       1/1     Running   0          2m11s
pgbench-1-dbs-client-1-df340ab8--1-9zkzj       1/1     Running   0          2m12s
pgbench-1-dbs-client-1-e5ede263--1-zb2vd       1/1     Running   0          2m12s
postgres-0                                     1/1     Running   0          3m27s
postgres-1                                     1/1     Running   0          3m4s
postgres-2                                     1/1     Running   0          2m52s
[root@m4204001 ~]#
```

Actually the command `redis-cli -h <benchmark-controller-manager pod ip> get pgb_start` is returning False. Where the job is expecting it to be True to continue.

Please find below the logs (along with must-gather) collected for the test `tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py::TestCompressedSCAndSupportSnapClone::test_compressed_sc_and_support_snap_clone[2-aggressive]`.

[Logs](https://drive.google.com/file/d/1T0SpfuuoLUgkHGuQ7OucAICDopZzMp45/view?usp=sharing)

On ocs 4.8, the tests related to benchmark-operator were passed when ran in July 2021. But currently, with the latest commit from master branch, the test is failing on 4.8 as well.

**Comment by PrasadDesala** [comment]
I have narrowed down this issue. Pgbench is getting stuck at running state if we pass more than one replicas of pgbench. I have brought this issue to perfscale forum in Slack channel and they are looking into it, this needs further investigation from the benchmark-operator folks to understand and fix the issue. The fix from them might take some time.

I tried running the tests with a single pgbench pod and the tests are passing every time. Considering above and also the fact that these tests are functional tests, until the replica issue is fixed,  these tests can be run with a single Pgbench pod.
The linked PR is to modify the number of pgbench pods count to 1 which should fix this issue.
