### ISSUE TITLE
Verify RBD image deletion

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#502]
As https://bugzilla.redhat.com/show_bug.cgi?id=1723656 is now ON_QA, it should be possible to validate RBD image deletion when deleting a PV.
For example, https://github.com/red-hat-storage/ocs-ci/blob/042226b5e158459d767b84a11bb54175f84f5ea4/tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py#L298 should be addressed

**Comment by gklein** [comment]
Can we closed this issue given the [merged PR](https://github.com/red-hat-storage/ocs-ci/pull/543) ?

**Comment by ebenahar** [comment]
Thanks @gklein, yes, fixed with https://github.com/red-hat-storage/ocs-ci/pull/543
