### ISSUE TITLE
Add the static values of rook ceph Configmap for OCS 4.9 in ocs-ci

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#5022]
The test `test_validate_ceph_config_values_in_rook_config_override` failed with the error:

> E       AssertionError: The Ceph config, set by rook-config-override is different than the expected. Please inform OCS-QE about this discrepancy. The expected values are:
> E         ['', '[global]', 'bdev_flock_retry = 20', 'mon_osd_full_ratio = .85', 'mon_osd_backfillfull_ratio = .8', 'mon_osd_nearfull_ratio = .75', 'mon_max_pg_per_osd = 600', 'mon_pg_warn_max_object_skew = 0', '[osd]', 'osd_memory_target_cgroup_limit_ratio = 0.5', '']
> E         The cluster's Ceph values are:['', '[global]', 'bdev_flock_retry = 20', 'mon_osd_full_ratio = .85', 'mon_osd_backfillfull_ratio = .8', 'mon_osd_nearfull_ratio = .75', 'mon_max_pg_per_osd = 600', 'mon_pg_warn_max_object_skew = 0', 'mon_data_avail_warn = 15', '[osd]', 'osd_memory_target_cgroup_limit_ratio = 0.5', '']
> E       assert Counter({'': ...io = 0.5': 1}) == Counter({'': ...io = 0.5': 1})
> E         Omitting 10 identical items, use -vv to show
> E         Left contains 1 more item:
> E         {'mon_data_avail_warn = 15': 1}

as you can see here https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/7051/testReport/tests.manage.z_cluster.test_ceph_default_values_check/TestCephDefaultValuesCheck/test_validate_ceph_config_values_in_rook_config_override/ and here https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/7106/testReport/tests.manage.z_cluster.test_ceph_default_values_check/TestCephDefaultValuesCheck/test_validate_ceph_config_values_in_rook_config_override/. From what I see the error occurred because we need to add the static values of rook ceph Configmap in the `constants` file https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py for OCS 4.9. 
Currently, we use these values in the line https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py#L1374: 

> ROOK_CEPH_CONFIG_VALUES = """
[global]
mon_osd_full_ratio = .85
mon_osd_backfillfull_ratio = .8
mon_osd_nearfull_ratio = .75
mon_max_pg_per_osd = 600
[osd]
osd_memory_target_cgroup_limit_ratio = 0.5
"""

**Comment by ebenahar** [comment]
There seems to be a new value added in 4.9:
```'mon_data_avail_warn = 15'```

**Comment by ebenahar** [comment]
The new value was added as part of https://issues.redhat.com/browse/KNIP-1706.
The new key and value should be added in constants.py's ROOK_CEPH_CONFIG_VALUES
