### ISSUE TITLE
Wrong usage of [rl]strip(...) methods

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#5024]
Today, when working on PR https://github.com/red-hat-storage/ocs-ci/pull/5008, I spotted [incorrect usage](https://github.com/red-hat-storage/ocs-ci/pull/5008#issuecomment-956155868) of `lstrip(...)` method. Method [`lstrip([chars])`](https://docs.python.org/3.9/library/stdtypes.html#bytes.lstrip) (and similarly `rstrip()` is removing subset of individual characters, not whole string prefix, which might cause various issues and unexpected behavior.
 
There are more issues like the above in the _ocs-ci_ code:
* [ocs_ci/deployment/helpers/vsphere_helpers.py#L216](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/helpers/vsphere_helpers.py#L216)
* [ocs_ci/utility/utils.py#L581](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L581)
* [ocs_ci/utility/utils.py#L2501](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L2501)
* [ocs_ci/ocs/fio_artefacts.py#L46](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/fio_artefacts.py#L46)
* [ocs_ci/ocs/ocp.py#L1183](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocp.py#L1183)
* [ocs_ci/ocs/ocp.py#L1303](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocp.py#L1303)

**Comment by dahorak** [comment]
In python 3.9, there is nice new methods introduced exactly for this usage: [`removeprefix(prefix)`](https://docs.python.org/3.9/library/stdtypes.html#str.removeprefix) and [`removesuffix(suffix)`](https://docs.python.org/3.9/library/stdtypes.html#str.removesuffix), but we can't used them now, because ocs-ci supports Python from 3.7.

**Comment by clacroix12** [comment]
> In python 3.9, there is nice new methods introduced exactly for this usage: [`removeprefix(prefix)`](https://docs.python.org/3.9/library/stdtypes.html#str.removeprefix) and [`removesuffix(suffix)`](https://docs.python.org/3.9/library/stdtypes.html#str.removesuffix), but we can't used them now, because ocs-ci supports Python from 3.7.

Personally I think this is good motivation for us to move to supporting and using more recent versions of python. 3.7 isn't EOL yet (2023) but it is far from the latest and greatest version of python. We already support 3.8 and 3.9 through our unit tests and we could probably get 3.10 into that list easily.

Something to consider is that we have many external dependencies. If we are to move to something like 3.9 we will need to make sure that all of our dependencies support running on that version or we might run into issues. Still, it may be worth investigating and seeing if there are other features released in the more recent python versions that we could benefit from and leverage if we moved our minimum supported version up.
