### ISSUE TITLE
cluster2 tier1 test failure logs

### ISSUE THREAD

**Issue by MonicaLemay** [red-hat-storage/ocs-ci#5044]
We are having multiple problems running tier1 on cluster2.  
I am trying to upload the ocs-ci logs tar.gz but it is failing to load to github.  Likewise with report.html and the faiiled testcase log. tar.GZ  

Additionally, On cluster2 it looks like the ocs-ci is trying to add hosts and this is causeing other problems.  Is it possible to disable this ?

Is it possible to have a meeting to discuss this.

**Comment by petr-balogh** [comment]
@MonicaLemay I created the skipif marker you can use also in other tests you identify will be problematic.
Used it now for add node test.

PR is here: https://github.com/red-hat-storage/ocs-ci/pull/5045

**Comment by petr-balogh** [comment]
@MonicaLemay I also added one more commit with config file:
conf/ocsci/ibm_flash.yaml

So you can also pass this one with `--ocsci-conf` when you have latest changes of the PR.

**Comment by yitzhak12** [comment]
While disabling the "add node" test can be a temporary solution, the right solution is to add a new class in the `platform_nodes` file https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py for adding a node with IBM Flash. 
You can use the class IBMCloud as a reference https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py#L2350. For adding a new node you need to implement the function `create_and_attach_nodes_to_cluster`.

**Comment by petr-balogh** [comment]
@yitzhak12 yes, I agree it's kind of WA here to just unblock them quickly from such issue to not break the whole cluster.

For platfomr_nodes it will be a bit tricky as the cluster is platform vsphere IPI IIUC and hence there will need to be some logic to check if it's IBM Flash and if so do it differently but I think it's about their infra issue as also disused in one of mail thread.

**Comment by yitzhak12** [comment]
Okay, no problem.
