### ISSUE TITLE
test_encrypted_rbd_pvc_clone.py failing when vault data are not provided

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#5048]
```
tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py:55:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/conftest.py:3931: in factory
    vault.gather_init_vault_conf()
ocs_ci/utility/kms.py:129: in gather_init_vault_conf
    self.vault_conf = self.gather_vault_config()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ocs_ci.utility.kms.Vault object at 0x7f9a4415e4c0>

    def gather_vault_config(self):
        """
        This function populates the vault configuration

        """
        if self.vault_deploy_mode == "external":
>           vault_conf = load_auth_config()["vault"]
E           KeyError: 'vault'
```

I guess that we should not require the vault data to be in config. Rather if they are not in config - we should skip the vault related tests or delete them from collection.

I think that we can have some decorator like kms_config_required and if some test requires it and user does not provide vault config - not everyone who runs ocs-ci has vault instance, then those tests should be skipped or removed from collection.

**Comment by rachael-george** [comment]
I think the decorator ` kms_config_required` would be mostly required by PV encryption tests. I'll work on this and also look into the error above.
