### ISSUE TITLE
Remove RBD thick provisioning coverage for ODF 4.10

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#5059]
Following https://github.com/red-hat-storage/ocs-ci/pull/5038/, we will need to disable the following tests:

tests/manage/pv_services/test_rbd_thick_provisioning.py
tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
tests/manage/pv_services/test_verify_thick_pvc_utilization.py

**Comment by jilju** [comment]
@ebenahar 
Should we disable the tests or delete the test file itself ?

**Comment by ebenahar** [comment]
I think we can disable for now
