### ISSUE TITLE
fix test_simultaneous_drain_of_two_ocs_nodes to run on VMWARE IPI

### ISSUE THREAD

**Issue by annagitel** [red-hat-storage/ocs-ci#5065]
this test failes on vmware IPI runs in `nodes.terminate_nodes` because this method is built for AWS (terminating EC2). a suitable method needs to be created at the same file ocs_ci/ocs/platform_nodes.py under `class VSPHEREUPINode(VMWareNodes):` on order to pass.
and ofcourse the test itself should be updated to have a condition for the platform and therefore create the right node object

**Comment by yitzhak12** [comment]
Just one note. I think the implementation of the function `terminate_nodes` should be under the class: `VMWareNodes`

**Comment by yitzhak12** [comment]
Also, we have the same issue in this test https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/7393/testReport/tests.manage.z_cluster.nodes.test_automated_recovery_from_failed_nodes_reactive_IPI/TestAutomatedRecoveryFromFailedNodes/test_automated_recovery_from_failed_nodes_IPI_reactive_cephfs_terminate_/.
