### ISSUE TITLE
Botocore client error when performing delete object operation on S3 bucket

### ISSUE THREAD

**Issue by Sravikaz** [red-hat-storage/ocs-ci#5066]
This test case performs different object actions and verifies cross account access to buckets .

`tests/manage/mcg/test_bucket_policy.py::TestS3BucketPolicy::test_object_actions`

During the delete object operation with the cross account, 403 status code is raised due to invalid access.

```
10:29:31 - MainThread - ocs_ci.ocs.resources.bucket_policy - INFO - status code: 403
10:29:31 - MainThread - ocs_ci.ocs.resources.bucket_policy - INFO - Error: {'Code': 'AccessDenied', 'Message': 'Access Denied', 'Resource': '/oc-bucket-09412bdfbb0c439db2ff417b8d3ed9/ObjKey-968c661a94fe410c8d4c503693985bcb'}
10:29:31 - MainThread - tests.manage.mcg.test_bucket_policy - INFO - Delete action has been denied access
```

Due to 403 error , a botocore client exception has been raised due to which the testcase fails, attaching the log for reference

```
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied

.venv/lib/python3.8/site-packages/botocore/client.py:656: ClientError
```
[tier1_test_object_actions.zip](https://github.com/red-hat-storage/ocs-ci/files/7503798/tier1_test_object_actions.zip)

**Comment by vasukulkarni** [comment]
@MeridianExplorer @parikshithb

**Comment by MeridianExplorer** [comment]
@Sravikaz - I believe the issue you're facing was fixed in #5035.
Is your local repo up-to-date?

**Comment by Sravikaz** [comment]
@MeridianExplorer : thanks for the info, itseems the commit has been merged recently after the issue has been opened. 
I have verified the test and it has PASSED now, the issue can be closed.

[tier1_test_object_actions 2.zip](https://github.com/red-hat-storage/ocs-ci/files/7526764/tier1_test_object_actions.2.zip)

**Comment by MeridianExplorer** [comment]
Sorry, @Sravikaz, I did not notice that the issue was opened a while ago - I just noticed the time of my assignment.
I'm happy to hear that the tests now pass successfully :)

Issue closed.
