### ISSUE TITLE
Add "wait" param in the function "stop_nodes" for class VMWareNodes

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#5067]
We need to add the `wait` param for the vSphere IPI test. As you can see the test https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/7393/testReport/tests.manage.z_cluster.nodes.test_node_replacement_reactive_aws_ipi/TestNodeReplacement/test_node_replacement_reactive_aws_ipi_rbd_power_off_/ is failed because we are missing the `wait` param in the function `stop_nodes` https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py#L245.

**Comment by vasukulkarni** [comment]
As per @vavuthu and @clacroix12 this test should not be running on vSphere and maybe the decorator is causing this test to be run.

**Comment by clacroix12** [comment]
Just for reference these are the decorators being used for the test class.
```
@ignore_leftovers
@tier4
@tier4b
@aws_based_platform_required
@ipi_deployment_required
class TestNodeReplacement(ManageTest):
```

**Comment by petr-balogh** [comment]
https://github.com/red-hat-storage/ocs-ci/commit/a42a58b1335c2e9dc1d741d8065962113c54bffb
@suchita-g can you please check if your commit didn't make any issue here?

**Comment by ebenahar** [comment]
@vasukulkarni this test was running on vsphere IPI because I executed the job with a PR that removes the skipif aws.

From what I can see, the scenario is supposed to be supported on vSphere IPI too. I think that since the test was written when IPI was available only with AWS, it was assumed that it is relevant to AWS only

**Comment by ebenahar** [comment]
@PrasadDesala what do you think?

**Comment by PrasadDesala** [comment]
> @vasukulkarni this test was running on vsphere IPI because I executed the job with a PR that removes the skipif aws.
> 
> From what I can see, the scenario is supposed to be supported on vSphere IPI too. I think that since the test was written when IPI was available only with AWS, it was assumed that it is relevant to AWS only

Yes, this is correct.  IPI is only supported on AWS at that time when the test was developed.
Since now we have IPI support on VMware we have to adjust this test to make it run on Vmware too.
