### ISSUE TITLE
RFE: create an app pod and attach pvc

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#51]
Most of our test cases will have a step to attach one or more PVC to application pod. It is a good idea to implement this functionality as a common function.

**Comment by keesturam** [comment]
I'm going to pick this up and try

**Comment by vasukulkarni** [comment]
@shylesh FYI, @keesturam can you post the flow details?

**Comment by keesturam** [comment]
This is what I'm planning to implement. 

1) create two template files for PVC and pod creation. 
   a) pvc.yaml file will have jinja template 

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ pvc_name | 'test-rbd-device' }}
spec:
  accessModes:
    - {{access_mode | "ReadWriteOnce"}}
  resources:
    requests:
      storage: {{ storage_capacity | "10Gi" }}
  storageClassName: {{storage_class | "rook-ceph-block" }}

  b)app_pod.yaml file will have jinja template to configure the following params

apiVersion: v1
kind: Pod
metadata:
  name: {{pod_name | "nginx1" }}
  namespace: {{ namespace | "openshift-storage"}}
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: {{ claim_name | "test-rbd-device " }}
       readOnly: false

2) create pvc using the create method in ocs.ocp object and validate if the pvc is actually created using get method & wait method in ocs.ocp object.

3) For creation of app pod, validate if the pvc being mapped is actually in bound state and then use app_pod.yaml file to attach the pvc and validate once again using ocs.ocp object.

**Comment by RazTamir** [comment]
Great @keesturam , let me know if you need my help

**Comment by keesturam** [comment]
closing this pretty old PR. This feature was made available already.
