### ISSUE TITLE
Add author info to tier tests

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#512]
When tests fails, its easy to have the contact info in the tier and assign issue to the author.

**Comment by RazTamir** [comment]
I'm not sure if that's will be the approach for the long term.
We need to have a process automation analysis (cc Elad and Tamil)

**Comment by vasukulkarni** [comment]
I can speak about this one tomorrow's call.

**Comment by vasukulkarni** [comment]
Closing due to Elad's excel sheet.
