### ISSUE TITLE
Backport following pr for 4.8

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#5127]
Need to backport this for 4.8 as the test is broken and run only in e2e suite https://github.com/red-hat-storage/ocs-ci/pull/5108 ( and needs backporting to 4.7 as well)

**Comment by petr-balogh** [comment]
Hey @vasukulkarni , we are not responsible for backporting PRs for people. Person who open the PR is responsible to do that if needed by opening new PR for specific release branch.

**Comment by PrasadDesala** [comment]
This is fixed with #5108. Hence closing this issue.
