### ISSUE TITLE
`skip_ocs_deployment` causes OCS-CI to ignore various test markers

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#5148]
Due to the flow here - 
https://github.com/red-hat-storage/ocs-ci/blob/a8c4a806c295677be565cba42e33a747b5908bca/tests/conftest.py#L171

Several `skipif` markers are not being respected.
However, it makes sense to set `skip_ocs_deployment` to `True` in cases where the cluster already has OCS installed, and users just want to run the OCS-CI test suite.

One problematic scenario that this led to, has been a user which set the variable to true, since he deployed ODF separately, and then ran the test suite. Tests that should've been skipped, weren't skipped.

The relevant changed was introduced in #4051 in order to handle cases of OCP-only deployments, but the flag might also be set to true in cases where OCS was already deployed beforehand.

**Comment by MeridianExplorer** [comment]
@vavuthu - can you please take a look?

**Comment by vavuthu** [comment]
@MeridianExplorer skip_ocs_deployment is used when we want to skip OCS deployment for deployments ( --deploy ). If the cluster is already installed with OCS, we don't need to use skip_ocs_deployment.

**Comment by MeridianExplorer** [comment]
@vavuthu - Then this needs to be clarified in the docs; Everything that the docs note, points to it not being clear enough - 
1. `Skip the OCS deployment step or not (Default: false)`. 
2. ` Option skip_ocs_deployment
Installation of OCS will be skipped when in ENV_DATA section of ocs-ci
configuration file, option skip_ocs_deployment is set to `true`.
If you don't need to change anything else in ocs-ci configuration file, you
can just use conf/ocsci/skip_ocs_deploy.yaml file instead of creating your
own config file.`

People can rightfully think (and have thought) that OCSCI installs OCS by default, regardless of `--deploy`.
I believe we should do the following:
1. Note in our docs that `skip_ocs_deployment` disables `pytest_collection_modifyitems`
2. Add a verification that `skip_ocs_deployment` is **only** respected in conjunction with `--deploy` use

**Comment by petr-balogh** [comment]
Hey @MeridianExplorer .

> 1. Note in our docs that skip_ocs_deployment disables pytest_collection_modifyitems

That's not the true, the skip applies only for the if block you pointed out here:
https://github.com/red-hat-storage/ocs-ci/blob/a8c4a806c295677be565cba42e33a747b5908bca/tests/conftest.py#L171

The if block is mainly for the purpose of the deployment that some of those operations called in this block requires OCS or OCP to be installed. If some code does not require it. It doesn't have to be in this block and hence I don't  think we need to document anything about it as depends on each individual implementation and where the people added the things in this pytest hook. But I think that we can improve the condition which I will point out later in this comment.


I think that in this file: https://github.com/red-hat-storage/ocs-ci/blob/643ce73aceef3f92b695fda1bafdea83f6fb0402/docs/usage.md

We describe the deployment commands and test execution commands, and after reading it is quite clear to me that if I want to deploy the cluster I have to use `--deploy` parameter. 
Other section there describes `Running tests on deployed environment` which doesn't mention this --deploy parameter.

The parameter is also descriptive enough but if you would like to be more clear and something is confusing you think you are always welcomed to send PR to improve the documentation ;)

> 2. Add a verification that skip_ocs_deployment is only respected in conjunction with --deploy use

 I think that condition can be changed to :
 
 ```python
if not (teardown or deploy or (deploy and skip_ocs_deployment)):
 ```
 This will make sure that the code in this block is skipped only in --deploy scenario.

**Comment by MeridianExplorer** [comment]
> Hey @MeridianExplorer .
> 
> > 1. Note in our docs that skip_ocs_deployment disables pytest_collection_modifyitems
> 
> That's not the true, the skip applies only for the if block you pointed out here:
> 
> https://github.com/red-hat-storage/ocs-ci/blob/a8c4a806c295677be565cba42e33a747b5908bca/tests/conftest.py#L171

You're right, I was inaccurate, my bad. I edited the comment to reflect that. 
> 
> The if block is mainly for the purpose of the deployment that some of those operations called in this block requires OCS or OCP to be installed. If some code does not require it. It doesn't have to be in this block and hence I don't think we need to document anything about it as depends on each individual implementation and where the people added the things in this pytest hook. But I think that we can improve the condition which I will point out later in this comment.
> 
> I think that in this file: [`643ce73`/docs/usage.md](https://github.com/red-hat-storage/ocs-ci/blob/643ce73aceef3f92b695fda1bafdea83f6fb0402/docs/usage.md)
> 
> We describe the deployment commands and test execution commands, and after reading it is quite clear to me that if I want to deploy the cluster I have to use `--deploy` parameter. Other section there describes `Running tests on deployed environment` which doesn't mention this --deploy parameter.
> 
> The parameter is also descriptive enough but if you would like to be more clear and something is confusing you think you are always welcomed to send PR to improve the documentation ;)

Sounds good, will do :)
> 
> > 2. Add a verification that skip_ocs_deployment is only respected in conjunction with --deploy use
> 
> I think that condition can be changed to :
> 
> ```python
> if not (teardown or deploy or (deploy and skip_ocs_deployment)):
> ```
> 
> This will make sure that the code in this block is skipped only in --deploy scenario.

I think that's perfect. It's less prone to user error, regardless of the docs

**Comment by petr-balogh** [comment]
Send the PR with suggested improvement here: https://github.com/red-hat-storage/ocs-ci/pull/5219
