### ISSUE TITLE
Add ability to search specific test history

### ISSUE THREAD

**Issue by AviadP** [red-hat-storage/ocs-ci#5182]
Add ability to search or filter by specific test name, so it would be easy to compare its performance over time / different platform etc.

**Comment by MeridianExplorer** [comment]
For now, [this link](https://reportportal-ocs4.apps.ocp4.prod.psi.redhat.com/ui/#ocs/launches/5/list?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26launchesLimit%3D50%26isLatest%3Dfalse%26filter.in.status%3DPASSED%252CFAILED%252CSKIPPED%252CINTERRUPTED%252CIN_PROGRESS%26page.page%3D1) can be used for searching by test name across 4.9.0-249 launches.
The `History` button at the top-right can be used for a nicer view of all past runs of the found test, too.
When I attempted to refine the search in the same way over all of our runs, it seemed to simply discard many of the results, so I'm not sure that'd be possible with the tools that are available at the moment.
