### ISSUE TITLE
test_raw_block_pv failed

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#5216]
Test case test_raw_block_pv failed due to the error given below.
```
        logger.info(f"Waiting for FIO results from pod {self.name}")
        try:
>           result = self.fio_thread.result(timeout)
E           AttributeError: 'NoneType' object has no attribute 'result'

ocs_ci/ocs/resources/pod.py:140: AttributeError
```
This check was done before the start of fio. The primary reason for the failure is the first attempt to install fio failed. There will be maximum 10 re-attempts to install fio. The fio install and run was done in separate thread. So while the retry was on-going , fio_thread.result was called in the main thread assuming that fio already started.

**Comment by jilju** [comment]
Before calling fio_thread.result , a check should be added to verify that fio already started. Waiting for the presence of the attribute pod.fio_thread will work.

**Comment by sidhant-agrawal** [comment]
Issue observed in RUN ID: 1657228396
tests.manage.pv_services.test_raw_block_pv.TestRawBlockPV.test_raw_block_pv[Delete]
```
        logger.info(f"Waiting for FIO results from pod {self.name}")
        try:
>           result = self.fio_thread.result(timeout)
E           AttributeError: 'NoneType' object has no attribute 'result'

ocs_ci/ocs/resources/pod.py:141: AttributeError
```
