### ISSUE TITLE
Fix test_cephfilesystem_creation

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#522]
Following test is constantly failing in CI, could you please check it and fix it?
`tests.manage.cluster.test_add_mds_to_cluster.TestCephFilesystemCreation.test_cephfilesystem_creation`

Example failure: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-us-tier1-tests-master/63/testReport/tests.manage.cluster.test_add_mds_to_cluster/TestCephFilesystemCreation/test_cephfilesystem_creation/

**Comment by RazTamir** [comment]
Fixed here - https://github.com/red-hat-storage/ocs-ci/pull/531
We have a regression in the product https://bugzilla.redhat.com/show_bug.cgi?id=1738833
