### ISSUE TITLE
Fix test_rbd_based_rwo_pvc

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#523]
Teardown of following test is constantly failing in CI, could you please evaluate and fix it?
`tests.manage.pv_services.test_verify_rbd_based_rwo_pvc.TestRbdBasedRwoPvc.test_rbd_based_rwo_pvc[Retain]`

Example failure: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-us-tier1-tests-master/63/testReport/tests.manage.pv_services.test_verify_rbd_based_rwo_pvc/TestRbdBasedRwoPvc/test_rbd_based_rwo_pvc_Retain_/

**Comment by jilju** [comment]
Leftovers are seen in the project. The project is being deleted in teardown part on the test case, but deletion is not verified. The environment status check might be done before the project is actually removed. Project deletion has to be verified in teardown.

**Comment by jilju** [comment]
> Leftovers are seen in the project. The project is being deleted in teardown part on the test case, but deletion is not verified. The environment status check might be done before the project is actually removed. Project deletion has to be verified in teardown.

Updated test case to use create_project fixture which will verify project deletion after test case.
PR #532
