### ISSUE TITLE
Fix test_create_pvc_with_random_sc

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#524]
Teardown of following test is constantly failing in CI, could you please evaluate and fix it?
`tests.manage.pv_services.test_create_pvc_random_storage_class.TestCreatePVCRandomStorageClass.test_create_pvc_with_random_sc`

Example failure: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-us-tier2-tests-master/4/testReport/tests.manage.pv_services.test_create_pvc_random_storage_class/TestCreatePVCRandomStorageClass/test_create_pvc_with_random_sc/

**Comment by dahorak** [comment]
@prsurve I still see that this test is constantly failing in CI, could you please check it and fix it ASAP?

**Comment by prsurve** [comment]
@dahorak sure will fix this ASAP

**Comment by prsurve** [comment]
Fix in #760

**Comment by dahorak** [comment]
Closing as #760 is merged.
