### ISSUE TITLE
IO in BG failing in teardown of live upgrade tests 

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#5241]
```ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 360s running get("pod-test-rbd-XXX-deploy", True,)```

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-vsphere-upi-1az-rhcos-vsan-3m-3w-live-upgrade-ocs-manual-acceptance/22/ 

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-vsphere-upi-1az-rhcos-vsan-3m-3w-live-upgrade-ocs-manual-acceptance/21/

**Comment by ebenahar** [comment]
The failure is on waiting for the deployment config pod to reach to `Completed` state:

2021-12-16 16:36:38  14:36:37 - MainThread - ocs_ci.ocs.ocp - INFO - status of pod-test-rbd-bf22d3b725164712ab1b386adc7-1-deploy at column STATUS was Running, but we were waiting for Completed
2021-12-16 16:36:38  14:36:37 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 3 seconds before next iteration
2021-12-16 16:36:42  14:36:40 - MainThread - ocs_ci.ocs.ocp - ERROR - timeout expired: Timed out after 360s running get("pod-test-rbd-bf22d3b725164712ab1b386adc7-1-deploy", True, None)

The pod reaches `Running` which sounds right. 
I can see that the place in code where we define we wait for `Completed` for DC pods is in:

https://github.com/red-hat-storage/ocs-ci/blob/fd2b23da7ea709773e105d1bc678dfbc4fc67118/ocs_ci/helpers/helpers.py#L141
https://github.com/red-hat-storage/ocs-ci/blob/fd2b23da7ea709773e105d1bc678dfbc4fc67118/ocs_ci/helpers/helpers.py#L299

**Comment by ebenahar** [comment]
@jilju @sidhant-agrawal @prsurve is `Completed` the expected status we should wait for in this case?

**Comment by jilju** [comment]
> @jilju @sidhant-agrawal @prsurve is `Completed` the expected status we should wait for in this case?

Yes, ```Completed``` is the success state of a ```**-deploy``` pod.

**Comment by petr-balogh** [comment]
@ebenahar hello, I see this is still happening. E.g.:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/3093/testReport/tests.ecosystem.upgrade/test_upgrade/test_upgrade/
