### ISSUE TITLE
ODF Deployment via UI doesn't work if OCP and OCS version are not same

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#5261]

**Comment by am-agrawa** [comment]
Tagging @ebenahar @petr-balogh @vavuthu @hnallurv for any inputs on this.

**Comment by petr-balogh** [comment]
I think it was discussed here: https://chat.google.com/room/AAAAEDRLC3U/aJq_faKYo4w
And there is actually no way to prevent it if we are using custom catalog source which allow us to add ODF 4.9 even on OCP 4.8. SO closing this one for now.

**Comment by am-agrawa** [comment]
@petr-balogh Re-opening this as this is a different issue than whatever we discussed in the thread.
@OdedViner As discussed offline, could you please help others understand what is happening with UI deployment when, say for e.g. OCP version is 4.9 and OCS version is 4.8 and we deploy an OCS cluster via Jenkins with option UI_DEPLOY enabled.

The current validation skips the deployment and falls back to CLI when OCP and OCS version isn't the same.

**Comment by am-agrawa** [comment]
Hi, do we need to prioritize this?
@hnallurv @ebenahar
