### ISSUE TITLE
Fix test_remove_mon_pod_from_cluster

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#528]
Teardown of following test is constantly failing in CI, could you please evaluate and fix it?
`tests.manage.cluster.test_remove_mon_from_cluster.TestRemoveMonFromCluster.test_remove_mon_pod_from_cluster`

Example failures:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-us-tier4-tests-master/4/testReport/tests.manage.cluster.test_remove_mon_from_cluster/TestRemoveMonFromCluster/test_remove_mon_pod_from_cluster_2/

**Comment by dahorak** [comment]
This test seems to sometime pass and sometime fails (based on the results from last few CI tier4 tests runs), will keep this issue open for some more results to decide if it can be closed or not.

**Comment by Shrivaibavi** [comment]
This issue can be closed as we no longer hitting this.
