### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#5336]
Test case test_snapshot_at_different_usage_level failed due to the error:
```
        mount_point = pod_obj.exec_cmd_on_pod(command="df -kh")
>       mount_point = mount_point.split()
E       AttributeError: 'NoneType' object has no attribute 'split'

ocs_ci/ocs/resources/pod.py:1295: AttributeError
```
The output of df command on the app pod did not return any value.

**Comment by jilju** [comment]
Same issue #3846 which was seen in different other test cases were fixed by adding retry within the test case. As this is not particular to any test case, a generic solution is needed.

**Comment by clacroix12** [comment]
The retry might work to get an actual return value from the pod but that doesn't fix the issue of trying to perform a split on a NoneType if nothing is returned. The solution here is to validate whether or not you have a mount_point value or except that AttributeError and raise an an appropriate exception that explains no mount point was found.

**Comment by jilju** [comment]
> The retry might work to get an actual return value from the pod but that doesn't fix the issue of trying to perform a split on a NoneType if nothing is returned. The solution here is to validate whether or not you have a mount_point value or except that AttributeError and raise an an appropriate exception that explains no mount point was found.

The problem is not getting the actual return value from the pod. Df on pod will have an output. I am not sure about the reason of not returning the output but adding retry helped in other test cases.

**Comment by clacroix12** [comment]
What I am trying to say is regardless of what is supposed to come back from the pod this code should be robust enough to handle the case when that doesn't happen and raise an informative error to help troubleshooting.
