### ISSUE TITLE
tests.manage.z_cluster.nodes.test_node_replacement_proactive.TestNodeReplacement 

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#5351]
When running or doing verification we need to check there are no extra ocs node if there are verifcation steps need to be updated

**Comment by prsurve** [comment]
run_id:1641825677

**Comment by yitzhak12** [comment]
Need to fix the 2 tests: `test_check_pods_status_after_node_failure`, `test_nodereplacement_proactive`. They both have the same issue described above.

**Comment by yitzhak12** [comment]
We need to check how many osd pods per osd node(if there are more than 1 per osd node), were in the test. I think that the expected behavior is that one of the osd pods should move to the new OCS node.
