### ISSUE TITLE
Cleanup AWS resources

### ISSUE THREAD

**Issue by Avilir** [red-hat-storage/ocs-ci#5369]
performance test can take a log time, and in our last test with gp3 after 60 hours of run (via Jenkins pipeline) the cluster was deleted, and the lats test in the pipeline failed to run.

we need to make sure that the cleanup process does not delete cluster which used by Jenkins pipeline.

**Comment by petr-balogh** [comment]
@dahorak  haven't you done already some similar change for some specific particular job?

@Avilir what is the expected time to finish this performance suite? 60 hours is quite a lot to me already :(

Any way how we can think of decreasing the time here? @keesturam @ebenahar @hnallurv  ?

Petr

**Comment by Avilir** [comment]
The time changed regarding the storage class, on gp2 it finished in less than 60 hours but on gp3 it looked like 60 hours is not enough.

I think that the only way to change it is by splitting the pipeline to 2 different runs

**Comment by dahorak** [comment]
> @dahorak haven't you done already some similar change for some specific particular job?

Sorry for late reply, I don't remember any such particular change (except of extending the default to 60 hours https://github.com/red-hat-storage/ocs-ci/pull/4785).

If it is not possible to decrease the time run, we can think about splitting it as Peter mentioned or it might be possible to change the prefix for the cluster to `lr4` or `lr5` (96 or 120 hours limit). But I'm not sure, if it is directly possible to change it in the job definition, or if we will have to do some changes to allow this change for one particular job.

**Comment by clacroix12** [comment]
@dahorak right now we generate all of the production jobs using the [default_cluster_prefix](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/blob/master/jobs/qe_ci_production_job_triggers.groovy#L88) of `j` but we can easily change this to `lr4`/`lr5` for performance jobs if we move defining this param into the [job_types](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/blob/master/jobs/qe_ci_production_job_triggers.groovy#L128) loop.

Something like this:
```groovy
default_cluster_prefix = job_type == "performance" ? "lr5": "j"
```

That being said I think splitting up performance tests into "smaller" chunks if they are running for too long when combined is the best route, but for those tests that still run for longer than 60 hours when run alone I think this would be an easy way to extend the life of clusters spun up for performance testing.
