### ISSUE TITLE
Run tier1 tier4a tier4b on the new storage classes gp2-csi, gp3-csi with AWS 4.10

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#5376]
As a continuation of the PR https://github.com/red-hat-storage/ocs-ci/pull/5292 we need to run the tests tier1, tier4a, tier4b on the new storage classes gp2-csi, gp3-csi with AWS 4.10. The configuration should be AWS, OCP 4.10, ODF 4.10. 
In order to deploy a cluster with `gp2-csi` we need to pass the conf file `conf/deployment/aws/gp2_csi_storage_class.yaml` and with `gp3-csi` we need to pass the conf file `conf/deployment/aws/gp3_csi_storage_class.yaml`.

**Comment by yitzhak12** [comment]
I think that for now we can test it with the AWS conf files: `conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml`, `conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml`.

**Comment by petr-balogh** [comment]
Hey Yitzhak.  Will the GP3 be default in ODF/OCP 4.10 ? If so, then I think that we should just update logic to by default to use GP3 if not specified in configuration and then no change will be needed in production jobs. I think that's what @ebenahar told me about this week. 

And if someone will need to deploy with GP2 they can provide the config file to overwrite the default behavior. 
https://github.com/red-hat-storage/ocs-ci/pull/5292/files#r788742731 
Here I pointed out that those files should be moved outside of prod configuration folder.

**Comment by yitzhak12** [comment]
From what I understand the default SC is still `gp2`. 
About the second point... I will move the SCs files to `conf/ocsci`. Also, I will change their names to `aws_gp2_csi_storage_class.yaml`, `aws_gp3_csi_storage_class.yaml` as they are no longer under the `aws` dir.
@petr-balogh @ebenahar WDYT?

**Comment by petr-balogh** [comment]
Yes, sounds good. But I can imagine that at some point we would like to default from some version of ODF to `gp3` this case the logic will need to be updated to automatically switch.

And if in 4.10 there will still be the default gp2 then we really need to create production jobs for gp3 scenario which wich will be the same AWS jobs we had just extra passing the  conf/ocsci/aws_gp3_csi_storage_class.yaml file via CLUSTER_CONF .

**Comment by yitzhak12** [comment]
Yes, I will consider it.

**Comment by petr-balogh** [comment]
Hello @yitzhak12 , have you moved the config files out of `conf/deployment/aws/` to `conf/ocsci/` ?

Thanks
