### ISSUE TITLE
--delete-local-data has been deprecated for oc drain command, need to update drain_nodes() accordingly

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#5386]
while running `oc drain` in our tests we get:
```
2022-01-23 21:48:17  19:48:16 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Flag --delete-local-data has been deprecated, This option is deprecated and will be deleted. Use --delete-emptydir-data.
```
seems like we need to update ocs_ci.ocs.node.drain_nodes()

**Comment by ebenahar** [comment]
fixed with https://github.com/red-hat-storage/ocs-ci/pull/5387#pullrequestreview-860803439

**Comment by jimdevops19** [comment]
@ebenahar Can you share the execution you've faced this warning, please? So I can take a look to the params.
As @petr-balogh mentioned in the PR, it might be worth checking if we need to condition the flag change depending on the oc version.

**Comment by petr-balogh** [comment]
@jimdevops19 you can try download the oc client for specific OCP version https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/ and you can check help command for that: e.g.
`oc adm drain --help`

You can check for more versions to see where it changed.

**Comment by ebenahar** [comment]
it is not depending on the oc version but rather on ODF.

**Comment by agarwal-mudit** [comment]
> it is not depending on the oc version but rather on ODF. I don't really know starting which version it should take effect. I see there is a previous issue about it - #4659 @agarwal-mudit any idea?

This is an oc command, code for oc command is with OCP team. I am not sure if this has anything to do with ODF.
You need to check with maszulik@redhat.com (I don't know his github id)

**Comment by jimdevops19** [comment]
After checking in some clusters in different versions, I found out it is deprecated in 4.7 and above. I'll change my PR accordingly.
