### ISSUE TITLE
MON and OSD pods were stuck at pending state and the cluster went to unhealthy state

### ISSUE THREAD

**Issue by barakda** [red-hat-storage/ocs-ci#5447]
@PrasadDesala analyzing report:
I have looked at the logs and can confirm that the issue you are hitting is not a product issue.
Due to issues in the test script MON and OSD pods were stuck at pending state and the cluster went to unhealthy state.

The expected behavior of this automatic failure and recovery test is, if there are more than 3 worker nodes in the cluster and when we fail a node, the MON and OSD pods running on that node will automatically failover to the other healthy node in the same rack/zone.

From the test logs, it looks like the newly added node 'cluster7-z7w2v-worker-h5w89' was assigned with a rack label: rack0.
Test script picked worker node 'cluster7-z7w2v-worker-tlslx' for failure which is in rack: rack1. Since we do not have any other redundant node in rack1 to failover the pods,  the MON and OSD pods stayed at pending state.

If the test script would have picked worker node "cluster7-z7w2v-worker-h5w89 " in rack0 for failure, we might have seen a successful failover of MON and OSD pods from the failed node to the newly added node.

root@cluster7-inf tmp]# oc get nodes -l [cluster.ocs.openshift.io/openshift-storage=](https://urldefense.proofpoint.com/v2/url?u=http-3A__cluster.ocs.openshift.io_openshift-2Dstorage-3D&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=qAGReYnfv8foqXI_XJNINJ1m4x0VNeiU2-EqGB44BMw&m=m-gyUjRjOGWm35XsmkYrOT7HgC_zZ8FOPmjp5-ut9h8&s=z58UfifK1x0X-pVDhcILCHoh1TbSgkJXasASRyJ8XZA&e=) --show-labels
NAME                          STATUS   ROLES    AGE   VERSION           LABELS
cluster7-z7w2v-worker-h5w89   Ready    worker   16h   v1.22.3+ffbb954   [beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cluster.ocs.openshift.io/openshift-storage=,kubernetes.io/arch=amd64,kubernetes.io/hostname=cluster7-z7w2v-worker-h5w89,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos,topology.rook.io/rack=rack0](https://urldefense.proofpoint.com/v2/url?u=http-3A__beta.kubernetes.io_arch-3Damd64-2Cbeta.kubernetes.io_os-3Dlinux-2Ccluster.ocs.openshift.io_openshift-2Dstorage-3D-2Ckubernetes.io_arch-3Damd64-2Ckubernetes.io_hostname-3Dcluster7-2Dz7w2v-2Dworker-2Dh5w89-2Ckubernetes.io_os-3Dlinux-2Cnode-2Drole.kubernetes.io_worker-3D-2Cnode.openshift.io_os-5Fid-3Drhcos-2Ctopology.rook.io_rack-3Drack0&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=qAGReYnfv8foqXI_XJNINJ1m4x0VNeiU2-EqGB44BMw&m=m-gyUjRjOGWm35XsmkYrOT7HgC_zZ8FOPmjp5-ut9h8&s=vsbZJ9uXP981UipztxvMqHJZBMcx9Vf8yXDrYLIj6yo&e=)
cluster7-z7w2v-worker-th7ms   Ready    worker   87d   v1.22.3+ffbb954   [beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cluster.ocs.openshift.io/openshift-storage=,kubernetes.io/arch=amd64,kubernetes.io/hostname=cluster7-z7w2v-worker-th7ms,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos,topology.rook.io/rack=rack0](https://urldefense.proofpoint.com/v2/url?u=http-3A__beta.kubernetes.io_arch-3Damd64-2Cbeta.kubernetes.io_os-3Dlinux-2Ccluster.ocs.openshift.io_openshift-2Dstorage-3D-2Ckubernetes.io_arch-3Damd64-2Ckubernetes.io_hostname-3Dcluster7-2Dz7w2v-2Dworker-2Dth7ms-2Ckubernetes.io_os-3Dlinux-2Cnode-2Drole.kubernetes.io_worker-3D-2Cnode.openshift.io_os-5Fid-3Drhcos-2Ctopology.rook.io_rack-3Drack0&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=qAGReYnfv8foqXI_XJNINJ1m4x0VNeiU2-EqGB44BMw&m=m-gyUjRjOGWm35XsmkYrOT7HgC_zZ8FOPmjp5-ut9h8&s=_kydivuDn8VtnibQZmckaferc88kB0FfaQR0_QjnHes&e=)
cluster7-z7w2v-worker-vfdvl   Ready    worker   25d   v1.22.3+ffbb954   [beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cluster.ocs.openshift.io/openshift-storage=,kubernetes.io/arch=amd64,kubernetes.io/hostname=cluster7-z7w2v-worker-vfdvl,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos,topology.rook.io/rack=rack2](https://urldefense.proofpoint.com/v2/url?u=http-3A__beta.kubernetes.io_arch-3Damd64-2Cbeta.kubernetes.io_os-3Dlinux-2Ccluster.ocs.openshift.io_openshift-2Dstorage-3D-2Ckubernetes.io_arch-3Damd64-2Ckubernetes.io_hostname-3Dcluster7-2Dz7w2v-2Dworker-2Dvfdvl-2Ckubernetes.io_os-3Dlinux-2Cnode-2Drole.kubernetes.io_worker-3D-2Cnode.openshift.io_os-5Fid-3Drhcos-2Ctopology.rook.io_rack-3Drack2&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=qAGReYnfv8foqXI_XJNINJ1m4x0VNeiU2-EqGB44BMw&m=m-gyUjRjOGWm35XsmkYrOT7HgC_zZ8FOPmjp5-ut9h8&s=TgbZ2bRo2TolsW-HsV20vSYGZOr7-e_hGtvAz5LJPqc&e=)

**Comment by PrasadDesala** [comment]
IBM flash team are hitting this issue while running test_automated_recovery_from_failed_nodes_proactive_IPI

**Comment by yitzhak12** [comment]
Yes, I am familiar with the test. Is it the test `test_automated_recovery_from_stopped_node_and_start`?

**Comment by barakda** [comment]
In our case, it was reproduced through test TestAutomatedRecoveryFromFailedNodes

**Comment by yitzhak12** [comment]
Okay, I see.
