### ISSUE TITLE
Resolve configuration discrepancies

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#55]
I see few minor issues with configuration, which includes:

 - [x] There are 2 directories: [conf](https://github.com/red-hat-storage/ocs-ci/tree/7a9d56c333357e1243223346eba0f8dd60dd15a6/conf) and [config](https://github.com/red-hat-storage/ocs-ci/tree/7a9d56c333357e1243223346eba0f8dd60dd15a6/config), it would be nice to unify them into single directory or drop one if one is not needed.
 - [x] Directory `osp` contains 2 yaml files with some configuration, without much explanation. Could this be dropped or moved somewhere?
 - [x] File [conf/ocs_basic_install.yml](https://github.com/red-hat-storage/ocs-ci/blob/7a9d56c333357e1243223346eba0f8dd60dd15a6/conf/ocs_basic_install.yml) seems to have no effect, as it notes that 6 worker and 6 master nodes are created in aws, but when one runs the installation, only 3 of each are created. We may either drop the file to fix the setup so that values from there are followed. Resoved by #57 and 07b5eec769d1d332c3d99d8fd1e4d86faab1fe54
 - Another config file is `.ocs-ci.yaml` created via `cp ocs-ci.yaml.template ~/.ocs-ci.yaml` as noted in [docs/getting_started.md](https://github.com/red-hat-storage/ocs-ci/blob/master/docs/getting_started.md) but I don't see problem with that.

I'm reporting this in a single issue, as the problems listed above are intertwined.

**Comment by clacroix12** [comment]
@mbukatov `conf/ocs_basic_install.yml` will only have an effect if you specify to use it with `--conf`. Since 3 workers and 3 masters is what is defaulted to in our template, that's why you are seeing 3 instead of 6.

**Comment by petr-balogh** [comment]
@mbukatov I found the issue here why workers weren't taken from ocs_basic_install.yml , I did change in this structure recently and counting that ppl will define variables exactly like names in templates.

So it should be fixed here: https://github.com/red-hat-storage/ocs-ci/pull/61/commits/07b5eec769d1d332c3d99d8fd1e4d86faab1fe54  in pytest related patch.

**Comment by mbukatov** [comment]
I consider this addressed.
