### ISSUE TITLE
OCP+ODF 4.9 deployment on AWS UPI is failing

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#5511]
Discussed with Vijay and opening this issue-
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/10292/console

**Comment by petr-balogh** [comment]
At a glance I see there is missing some new dependency: yq binary or package. Checking where we will add requirement, if in jenkins agent or to the venv.

**Comment by petr-balogh** [comment]
Testing the PR where I added it as pip dependency for ocs-ci project. @am-agrawa FYI
