### ISSUE TITLE
 Update `test_log_reader_writer_parallel` to handle restart of a container during rsync fetching phase

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#5526]
During rsync data fetching phase of `test_log_reader_writer_parallel`, it sometimes happen (in about 10% of cases in production runs)  that container of the workload pod is restarted (likely because of cpu utilization?), and so it's not available for brief period of time.

For this reason, rsync should be able to handle such error, and retry after a short waiting period.

## Example

```
$ oc get pods
NAME                                READY   STATUS    RESTARTS      AGE
reproducer-cephfs-d86c768c8-hr9nb   1/1     Running   3 (51m ago)   143m
reproducer-cephfs-d86c768c8-nzgqf   1/1     Running   3 (12m ago)   143m
reproducer-cephfs-d86c768c8-vfr89   1/1     Running   3 (83m ago)   143m
```

Pod `reproducer-cephfs-d86c768c8-nzgqf` was restarted 3 times, the last time 12 minutes ago, which aligns with this prometheus chart:

![Screenshot_20220228_221234](https://user-images.githubusercontent.com/4759819/156059591-3ad3f04d-d0ce-4e9d-a16f-63825ab902f6.png)

```
sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="reproducer", pod="reproducer-cephfs-d86c768c8-nzgqf", cluster=""}) by (container)
```

**Comment by abdulkandathil** [comment]
@mbukatov The image for this test is not multi-arch. Could you please build for other architectures as well? especially for Z and power.
