### ISSUE TITLE
When running a test with multiple clusters the config auth has no attribute "pagerduty"

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#5534]
When running the example test as defined here https://github.com/red-hat-storage/ocs-ci/pull/5415/files with multiple clusters I got this error:
```
self = <ocs_ci.utility.pagerduty.PagerDutyAPI object at 0x7febbdfb9950>, token = None

    def __init__(self, token=None):
        """
        Constructor for PagerDutyAPI class.
        """
         self._token = token or config.AUTH["pagerduty"]["api_key"]
E       KeyError: 'pagerduty'

ocs_ci/utility/pagerduty.py:95: KeyError
```

When trying to print the `config.AUTH` I got this value: 
`{'test_quay_auth': 'test_secret', 'quay': {'access_token': '******'}}`

**Comment by yitzhak12** [comment]
The command I ran from the cli was:
```
run-ci multicluster 2 tests/manage/z_cluster/nodes/test_temp_muliplecluster.py \
--ocsci-conf  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml \
--cluster1 --cluster-path path_to_cluster_sgatfane-1-pr --cluster-name sgatfane-1-pr --ocp-version 4.9 \
--cluster2 --cluster-path path_to_cluster_sgatfane-1-c1 --cluster-name sgatfane-1-c1 --ocp-version 4.9 --ocsci-conf conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
```

**Comment by dahorak** [comment]
Hi @yitzhak12, sorry for late response, I completely miss the notification here. Is this issue still valid?
In jenkins, this configuration is done in `ocm-credentials-stage` and `ocm-credentials-prod` files like this (filtered only for this key):
```
AUTH:
  pagerduty:
    api_key: "..."
```

For local execution, you can configure it in separated file like this or place it to `data/auth.yaml` (without the `AUTH` section).

I don't have more info about when is this key required and if it should be made optional. Maybe @fbalak have answer for that.

**Comment by jilju** [comment]
Using _--ocsci-conf=conf/ocsci/disable_pagerduty.yaml_ in run-ci command will skip this check.
