### ISSUE TITLE
Noobaa bucket quota alert verification test fails with incorrect number of alerts

### ISSUE THREAD

**Issue by Sravikaz** [red-hat-storage/ocs-ci#5539]
`tests/manage/monitoring/prometheus/test_noobaa.py::test_noobaa_bucket_quota 
`

The above ocs-ci test in teir4a fails with  incorrect number of alerts, although there is no "pending" or "firing" alert with the label "NooBaaBucketReachingQuotaState"

Attaching the logs for reference:
[tier4a_test_noobaa_bucket_quota.zip](https://github.com/red-hat-storage/ocs-ci/files/8177578/tier4a_test_noobaa_bucket_quota.zip)

**Comment by AbhishekMundada** [comment]
Can we re-open this issue?

**Comment by fbalak** [comment]
Ok, reopening

**Comment by ebenahar** [comment]
@fbalak would you be able to take a look?

**Comment by ebenahar** [comment]
@fbalak I guess this is failing due to https://bugzilla.redhat.com/show_bug.cgi?id=2154250.

Can you please add a BZ decorator?

**Comment by schaefm-ibm** [comment]
This issue still exists. Please reopen.
The alert is defined as  `NooBaaBucketReachingQuantityQuotaState`, but in https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/constants.py, the value is `NooBaaBucketReachingQuotaState`.
