### ISSUE TITLE
Minor fixes to docs

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#556]
I noticed this when I was trying to help Svetlana during 4.2 deployment

a) git clone mentions git:// url for cloning ocs-ci, fix to use https instead ( for passwordless clone)
b) discourage use of sudo for any operations during docs - explicitly mention that in docs not to use sudo and run as local user.

**Comment by clacroix12** [comment]
> a) git clone mentions git:// url for cloning ocs-ci, fix to use https instead ( for passwordless clone)

Would you rather we point out that you need to have an ssh key setup in your github account as well as have git configured locally. If people clone with https they will still need to do those steps before they will be able to contribute.

> b) discourage use of sudo for any operations during docs - explicitly mention that in docs not to use sudo and run as local user.

Agreed.

**Comment by vasukulkarni** [comment]
> > a) git clone mentions git:// url for cloning ocs-ci, fix to use https instead ( for passwordless clone)
> 
> Would you rather we point out that you need to have an ssh key setup in your github account as well as have git configured locally. If people clone with https they will still need to do those steps before they will be able to contribute.

For contribution I think they don't have to be part of qe group, with forked repo *anyone* can raise a PR. I think we can make it more general now?

> 
> > b) discourage use of sudo for any operations during docs - explicitly mention that in docs not to use sudo and run as local user.
> 
> Agreed.

**Comment by clacroix12** [comment]
@vasukulkarni Not talking about qe group, more about first time git setup for pushing to github:
https://kbroman.org/github_tutorial/pages/first_time.html

**Comment by vasukulkarni** [comment]
> @vasukulkarni Not talking about qe group, more about first time git setup for pushing to github:
> https://kbroman.org/github_tutorial/pages/first_time.html

I see, yeah I think we should add that too, thanks

**Comment by gklein** [comment]
I think it can help if we point the ocs-ci doc to GitHub's instructions on [how to switch remotes from https to ssh](https://help.github.com/en/github/using-git/changing-a-remotes-url#switching-remote-urls-from-ssh-to-https). This way anyhow how cloned with https will be able to switch smoothly.
