### ISSUE TITLE
OCP/OCS MG collection on failure tests

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#5565]
- As part of the "Improve testing suites" group one of the tasks is to optimize the tests that take more than 30 mins to execute.

- We found that we collect OCP Must-Gather and OCS Must-Gather when the test fails.
> 

For Example on this tier1 job, we collected 40 OCS MG + 40 OCP MG 
- For_ each failure test, we collect ocp_mg+ocs_mg and noobaa_db_dump [only for MCG tests].
-  Estimated time for must gather collection in this job[tier1] is:
Time=40_OCS_MG * 5 min + 40_OCP_MG * 5 min ~ 6.67 hours

**Tasks:**

- Create a mechanism to enable/disable OCS/OCP must-gather collection:

For example:
```
@disable_ocs_mg_collection_on_failure
@enable_ocp_mg_collection_on_failure
def test_abc():
  	pass

```

- Enable OCS mg collection on failure by default 

- Disable OCP mg collection on failure by default 

-  Collect the OCP MG only on the end of the suite..

**Comment by ebenahar** [comment]
IIUC, setting OCP MG collection to False by default should be done in ocs_ci.framework.pytest_customization.ocscilib.pytest_runtest_makereport

**Comment by mykaul** [comment]
- Any reason the OCP and OCS must gather are not running in parallel?
- Is it really taking 5 minutes(!) to collect logs? Wow. What is that time spent on?

**Comment by OdedViner** [comment]
> * Any reason the OCP and OCS must gather are not running in parallel? --> I agree, we can use threads
> * Is it really taking 5 minutes(!) to collect logs? Wow. What is that time spent on? -->
$ time oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.10
real	4m43.058s
user	0m11.509s
sys	0m5.029s

http://pastebin.test.redhat.com/1050439

@agarwal-mudit
