### ISSUE TITLE
MCG CLI isn't upgraded alongside a cluster

### ISSUE THREAD

**Issue by Neon-White** [red-hat-storage/ocs-ci#5577]
At the moment, there's a bug that causes `test_noobaa_postupgrade` to fail when checking the status of an OBC with the 4.9 CLI over a cluster running 4.10

[For more information](https://bugzilla.redhat.com/show_bug.cgi?id=2062128)

**Comment by sagihirshfeld** [comment]
Was recently encountered [here](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/446/9197/407519/407542/407545/log), as discussed [here](https://mail.google.com/chat/#chat/space/AAAAFpL8OIs/DZI1bycE_Eg)

**Comment by sagihirshfeld** [comment]
Fixed by #8181
