### ISSUE TITLE
Adjustments to provisioner name change in storageclass.yaml 

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#562]
Copy-pasting @nehaberry update:

The name of the provisioner itself has changed and maybe we shall face issue in PVC creation if we deploy a fresh setup ( I tested manually, hence not sure about ocs-ci). if it breaks, we may need the following:

The change is - https://github.com/rook/rook/pull/3373/files

The provisoner name is changed to "provisioner: rook-ceph.cephfs.csi.ceph.com"  (the namespace is added in the name as a suffix)

The required format is:

The format for cephfs: provisioner: <cluster_namespace>.cephfs.csi.ceph.com
The format for rbd: provisioner:  <cluster_namespace>.rbd.csi.ceph.com

Confirmed that rbd pvc gets BOUND with above provisoner.

test-pvcs           rbd-pvc             Bound    pvc-daa440f2-bddb-11e9-8acb-0ab82a351f8c   1Gi        RWO
           rbd-csi        8m40s

$ oc get sc|grep rbd-csi
rbd-csi           openshift-storage.rbd.csi.ceph.com   10m

**Comment by RazTamir** [comment]
Fixed here - https://github.com/red-hat-storage/ocs-ci/pull/576
