### ISSUE TITLE
Modify rosa cli command in jenkins consumer to specify correct size

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#5664]
RequestedCapacity is 1 Byte when consumer is installed using the ocs-ci job

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/11326/console
```
    Requested Capacity:         1
    Storage Provider Endpoint:  10.0.145.155:31659
    Storage Provider Kind:      ocs
```

Executing command: rosa install addon --cluster=nberry-pr-c1 --size 1 ocs-consumer-qe --yes --onboarding-ticket "eyJpZCI6ImNmYWE3ZDFjLTMwOGQtNDI4ZC1hMDY1LWMxNDdiZTk5NDU2MyIsImV4cGlyYXRpb25EYXRlIjoiMTY0ODk3OTUyNiJ9.EUO1O9+orec1MOQPRUI5XqZauSBP1pR4uSWUJFHurGJP7NzEArG1G7CkOdSHSB04D3rREIHh6v/rmr1lMxxbRxf9tCFK2HNVb38d2ftTdNIVlbqnd+AySu3cjkTEWItB0fPcXm3co+NKYwuXZvJecSW0BCk1vLZ2X7hAVHFYfTUrSt+ICKEXgGN82g9n86GuTOiXofxZlJEYic6u/llycVniakMYAo/nbT5J7ftMz4wkzK93A0NLsIcK8a8Pq/RoOHhpIk1PZJv3p+JhMXL6iysCm1D1vXZXPPY6oMxRswdU1s6x0XzmEi3iRfc72rWvubcOfA3k3vXTa+dFAfvVYyWMKqH3+nL58hstnDQM4znjAXM/vcLkzSKWnDLSmwcHXYRRBvoFV82a0TmWbCaTE5Hp3Okq9BXd0fvJuMTE6U5wstFerPur3ZQAZU9u6ug0Ymft/OBrZVLB8c7RZ7jakmdhd6YEtzgxy0mvY5E3P5B5O5hA/mqzKIWj0LKpC/S2hR57MdbP8vnnlJlUzcJjik8Y2rpf4LU10oLkxkgqLA4PWtXxIQcyzwk2Tix8zOzqlciwb8S1w7Tf0KlbFZMIHKyTWKyNP5cHl774WUEQridD5E609/NpVKIEZWabSBIoCtW15YsXXaYW8IlkQ5F2Ydq2ygidF873osjMinYTIBo=

**Comment by nehaberry** [comment]
Also, how are we handling sizes? We need to decide on being able to pass the size using jenkins
@suchita-g @fbalak

**Comment by fbalak** [comment]
Fixed via https://github.com/red-hat-storage/ocs-ci/pull/5675
