### ISSUE TITLE
Following test cases are failing / not applicable for external mode cluster

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#5720]
Run id- 1649734847
`tests/manage/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_recovery_from_volume_deletion`

It is trying to look cephfs and rbd pvc's in the `openshift-storage` namespace whereas only noobaa pvc is available.

And for test-
`tests/manage/z_cluster/nodes/test_nodes_restart.py::TestNodesRestart::test_nodes_restart[True]`

Mon Pod is not available in the `openshift-storage` on the external mode cluster-

Output from must-gather
NAME                                              READY   STATUS            RESTARTS   AGE    IP            NODE        NOMINATED NODE   READINESS GATES
csi-addons-controller-manager-76b844ccd8-hv2qk    2/2     Running           3          172m   10.129.2.10   compute-1   <none>           <none>
csi-cephfsplugin-bzmgm                            3/3     Running           6          171m   10.1.160.44   compute-0   <none>           <none>
csi-cephfsplugin-fbdfk                            3/3     Running           3          171m   10.1.160.71   compute-1   <none>           <none>
csi-cephfsplugin-lxttq                            3/3     Running           3          171m   10.1.160.80   compute-2   <none>           <none>
csi-cephfsplugin-provisioner-bb6fb9c58-9v8zx      6/6     Running           6          171m   10.129.2.13   compute-1   <none>           <none>
csi-cephfsplugin-provisioner-bb6fb9c58-n2kfv      6/6     Running           9          171m   10.131.0.16   compute-2   <none>           <none>
csi-rbdplugin-bfdxh                               4/4     Running           4          171m   10.1.160.80   compute-2   <none>           <none>
csi-rbdplugin-l4c7k                               4/4     Running           8          171m   10.1.160.44   compute-0   <none>           <none>
csi-rbdplugin-provisioner-844d89c566-kl6c9        7/7     Running           7          171m   10.131.0.9    compute-2   <none>           <none>
csi-rbdplugin-provisioner-844d89c566-tb929        7/7     Running           7          105m   10.129.2.8    compute-1   <none>           <none>
csi-rbdplugin-tbw2k                               4/4     Running           4          171m   10.1.160.71   compute-1   <none>           <none>
must-gather-dhvr9-helper                          1/1     Running           0          64s    10.128.2.7    compute-0   <none>           <none>
noobaa-core-0                                     1/1     Running           1          104m   10.131.0.19   compute-2   <none>           <none>
noobaa-db-pg-0                                    0/1     PodInitializing   1          171m   <none>        compute-1   <none>           <none>
noobaa-endpoint-555c888f59-4gsrn                  1/1     Running           1          166m   10.129.2.6    compute-1   <none>           <none>
noobaa-endpoint-555c888f59-n6g58                  1/1     Running           1          105m   10.131.0.17   compute-2   <none>           <none>
noobaa-operator-6fb856cc56-l4djq                  1/1     Running           1          172m   10.131.0.4    compute-2   <none>           <none>
ocs-metrics-exporter-7d94d969d5-ppttc             1/1     Running           1          172m   10.129.2.7    compute-1   <none>           <none>
ocs-operator-644f587c7c-sww22                     1/1     Running           2          105m   10.129.2.3    compute-1   <none>           <none>
odf-console-57b594fd67-4dmdk                      1/1     Running           1          105m   10.131.0.12   compute-2   <none>           <none>
odf-operator-controller-manager-f78456dfc-fcqdh   2/2     Running           4          172m   10.129.2.2    compute-1   <none>           <none>
rook-ceph-operator-6b86d4677-x4rss                1/1     Running           1          105m   10.131.0.20   compute-2   <none>           <none>
rook-ceph-tools-external-7f4fc7d45f-d59cb         1/1     Running           1          105m   10.1.160.80   compute-2   <none>           <none>
session-awscli-relay-pod-77b3956b3e354e8          1/1     Running           1          153m   10.131.0.2    compute-2   <none>           <none>

And for
`tests/manage/z_cluster/nodes/test_nodes_maintenance.py::TestNodesMaintenance::test_pdb_check_simultaneous_node_drains`

There will be no effect of node drain over external cluster, so this test case might not be relevant here.

**Comment by yitzhak12** [comment]
The second failure of the test `tests/manage/z_cluster/nodes/test_nodes_restart.py::TestNodesRestart::test_nodes_restart[True]` should be resolved by the pr https://github.com/red-hat-storage/ocs-ci/pull/6257.

**Comment by yitzhak12** [comment]
I have created a new issue about the first test failure: https://github.com/red-hat-storage/ocs-ci/issues/6256.

**Comment by yitzhak12** [comment]
Issue #6256 is resolved by the pr https://github.com/red-hat-storage/ocs-ci/pull/6344. Therefore I am closing this issue.
