### ISSUE TITLE
Need to figure out how to get the ocs nodes when using external mode and managed service

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#5730]
Currently, we have an issue getting the OCS worker nodes when using external mode and managed service.
We don't have the OCS label on the provider with managed service, so we need to find another way to get the OCS nodes(maybe we can get the OSD running node instead). 
With external mode, I am not sure of the solution yet. Maybe we need to skip the tests that use the `get_ocs_nodes` function.

**Comment by sidhant-agrawal** [comment]
For External mode also, we don't have label on the node. The decision to skip the test should be decided based on the nature of test.
If the test case requires ceph related pods such as `mon, osd, mgr, mds, rgw` to be present on OCP/ODF cluster then the test case can be skipped.
If the test doesn't require the above mentioned pods, then the test can be run on external mode as we do have other pods in openshift-storage namespace.
