### ISSUE TITLE
tests/manage/z_cluster/test_ceph_default_values_check.py::TestCephDefaultValuesCheck::test_noobaa_postgres_cm_post_ocs_upgrade

### ISSUE THREAD

**Issue by musoni123** [red-hat-storage/ocs-ci#5738]
This Tc is failing in 4.9 build runs as well as the postgres max connections should be changed to 600 instead of 300 .

This issue is fixed with " https://github.com/red-hat-storage/ocs-ci/commit/22125d8f2f6a29333f494796df9fc4d848c77fbc# for 4.10 and higher versions but this fix needs to be back ported to 4.9 versions as well !

**Comment by am-agrawa** [comment]
Discussed here- https://chat.google.com/room/AAAAzrvtvTI/eTWybEy5gjQ
