### ISSUE TITLE
VSPHERE UPI OCP 4.10 nightly failed on No such file or directory: .../terraform_data/terraform.tfstate

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#5756]
Recently we have two failures of OCP 4.10 nightly deployment on vSphere UPI (jobs: [1](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/3988/console),[2](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/3985/console), logs: [1](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-018vue1cslv33-d/j-018vue1cslv33-d_20220420T082138), [2](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-017vue1cslv33-d/j-017vue1cslv33-d_20220419T182352)):

```
2022-04-19 20:39:47  18:39:35 - MainThread - ocs_ci.utility.utils - INFO - Executing command: /home/jenkins/bin/openshift-install wait-for bootstrap-complete --dir /home/jenkins/current-cluster-dir/openshift-cluster-dir --log-level INFO
2022-04-19 20:47:09  18:47:02 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: level=info msg=Waiting up to 20m0s (until 6:59PM) for the Kubernetes API at https://api.j-017vue1cslv33-d.qe.rh-ocs.com:6443/...
2022-04-19 20:47:09  level=info msg=API v1.23.5+9ce5071 up
2022-04-19 20:47:09  level=info msg=Waiting up to 30m0s (until 7:10PM) for bootstrapping to complete...
2022-04-19 20:47:09  level=info msg=It is now safe to remove the bootstrap resources
2022-04-19 20:47:09  level=info msg=Time elapsed: 7m26s
2022-04-19 20:47:09  
2022-04-19 20:47:09  18:47:02 - MainThread - ocs_ci.deployment.deployment - ERROR - [Errno 2] No such file or directory: '/home/jenkins/current-cluster-dir/openshift-cluster-dir/terraform_data/terraform.tfstate'
```

It was on two different nightly OCP builds:
* 4.10.0-0.nightly-2022-04-18-172132
* 4.10.0-0.nightly-2022-04-19-145842
Deployment of OCP 4.10 GA passed correctly and also we have successful OCP deployment of those nightly builds.

It might be some temporary issue, lets see if we will face it again.

**Comment by dahorak** [comment]
There is another occurrence of this issue - [job](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/4009/console), [log](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-062vu1cs33s-a/j-062vu1cs33s-a_20220421T134331/openshift-cluster-dir/).

**Comment by clacroix12** [comment]
This has also occurred here: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/4263/console

**Comment by am-agrawa** [comment]
Multiple failures are seen with the same issue-
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/14506/console
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/14502/console

**Comment by Akarsha-rai** [comment]
observed multiple failures -
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15158/
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15141/
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15146/
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15145/
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15151/
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15149/

**Comment by petr-balogh** [comment]
Today I saw it here:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-vsphere-upi-1az-rhcos-vsan-3m-3w-upgrade-ocs-auto/273/

And here:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-vsphere-upi-1az-rhcos-vsan-3m-3w-stage-acceptance/86/testReport/tests.ecosystem.deployment/test_deployment/test_deployment/

**Comment by dahorak** [comment]
Another occurrence: https://url.corp.redhat.com/b9bb857
