### ISSUE TITLE
No default CephFS - ocsci-cephfs

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#577]
For some reason, ocsci-cephfs is not created post deployment, which causes tests that rely on the existence of this CephFS, to fail. An example:

____________________________________________________________________ ERROR at setup of TestCephFilesystemCreation.test_cephfilesystem_creation ____________________________________________________________________

request = <SubRequest 'test_fixture' for <Function test_cephfilesystem_creation>>

    @pytest.fixture(scope='class')
    def test_fixture(request):
        """
        Create disks
        """
        self = request.node.cls
    
        def finalizer():
            teardown(self)
        request.addfinalizer(finalizer)
>       setup(self)

tests/manage/cluster/test_add_mds_to_cluster.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/manage/cluster/test_add_mds_to_cluster.py:41: in setup
    self.fs_data = CEPHFS.get(defaults.CEPHFILESYSTEM_NAME)
ocs_ci/ocs/ocp.py:108: in get
    return self.exec_oc_cmd(command)
ocs_ci/ocs/ocp.py:70: in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['oc', '--kubeconfig', '/home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig', 'get', 'CephFileSystem', 'ocsci-cephfs', ...], kwargs = {}
r = CompletedProcess(args=['oc', '--kubeconfig', '/home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig', 'get', 'CephFileSystem...urncode=1, stdout=b'', stderr=b'Error from server (NotFound): cephfilesystems.ceph.rook.io "ocsci-cephfs" not found\n')

    def run_cmd(cmd, **kwargs):
        """
        Run an arbitrary command locally
    
        Args:
            cmd (str): command to run
    
        Raises:
            CommandFailed: In case the command execution fails
    
        Returns:
            (str) Decoded stdout of command
    
        """
        log.info(f"Executing command: {cmd}")
        if isinstance(cmd, str):
            cmd = shlex.split(cmd)
        r = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            **kwargs
        )
        log.debug(f"Command output: {r.stdout.decode()}")
        if r.stderr and not r.returncode:
            log.warning(f"Command warning:: {r.stderr.decode()}")
        if r.returncode:
            raise CommandFailed(
>               f"Error during execution of command: {cmd}."
                f"\nError is {r.stderr.decode()}"
            )
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig', 'get', 'CephFileSystem', 'ocsci-cephfs', '-o', 'yaml'].
E           Error is Error from server (NotFound): cephfilesystems.ceph.rook.io "ocsci-cephfs" not found

ocs_ci/utility/utils.py:383: CommandFailed

============
(ocs-venv) [ebenahar@localhost ocs-ci]$ oc get cephfilesystem -n openshift-storage
No resources found.
(ocs-venv) [ebenahar@localhost ocs-ci]$ oc get cephfilesystem
No resources found.

**Comment by RazTamir** [comment]
Hi @ebenahar ,
Any chance you used the ceph_pool_factory or deleted this by mistake?

**Comment by ebenahar** [comment]
@RazTamir Found it. It was deleted here:

tests/e2e/test_io_performance.py::TestIOPerformance::test_run_io[CephFS-1GB-rw-1-60-4-1] 
------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------
18:58:59 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc new-project namespace-test-1518585958
18:59:01 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Pod --selector=app=rook-ceph-tools -o yaml
18:59:02 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig rsh rook-ceph-tools-5f5dc75fd5-hn86d ceph auth get-key client.admin --format json-pretty
18:59:04 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding Secret with name secret-test-cephfs-1518590498
18:59:04 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/Secretemxv1lbw -o yaml
18:59:05 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Secret secret-test-cephfs-1518590498 -o yaml
18:59:06 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get CephFileSystem ocsci-cephfs -o yaml
18:59:07 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get CephFileSystem  -o yaml
18:59:08 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding StorageClass with name storageclass-test-cephfs-1518590847
18:59:08 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/StorageClass6q5xnlj1 -o yaml
18:59:09 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get StorageClass storageclass-test-cephfs-1518590847 -o yaml
18:59:10 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Adding PersistentVolumeClaim with name pvc-test-1518591021
18:59:10 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig create -f /tmp/PersistentVolumeClaim11blnp7u -o yaml
18:59:11 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:14 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:23 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:34 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:46 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:50 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:54 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
18:59:58 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
19:00:01 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
19:00:05 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
19:00:09 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
19:00:13 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
19:00:14 - MainThread - tests.helpers - ERROR - PersistentVolumeClaim pvc-test-1518591021 failed to reach Bound
19:00:14 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get PersistentVolumeClaim pvc-test-1518591021 -o yaml
19:00:15 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig describe PersistentVolumeClaim pvc-test-1518591021
ERROR
------------------------------------------------------------------------------------------------ live log teardown ------------------------------------------------------------------------------------------------
19:00:16 - MainThread - ocs_ci.ocs.ocp - INFO - Switching to project openshift-storage
19:00:16 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc project openshift-storage
19:00:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig delete Project namespace-test-1518585958
19:00:19 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Project namespace-test-1518585958 -o yaml
19:00:23 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Project namespace-test-1518585958 -o yaml
19:00:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Project namespace-test-1518585958 -o yaml
19:00:30 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Project namespace-test-1518585958 -o yaml
19:00:34 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-1518585958 --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Project namespace-test-1518585958 -o yaml
19:00:35 - MainThread - ocs_ci.ocs.ocp - INFO - Project namespace-test-1518585958 got deleted successfully
19:00:35 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig delete StorageClass storageclass-test-cephfs-1518590847
19:00:36 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get StorageClass storageclass-test-cephfs-1518590847 -o yaml
19:00:37 - MainThread - ocs_ci.ocs.ocp - INFO - StorageClass storageclass-test-cephfs-1518590847 got deleted successfully
19:00:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig delete Secret secret-test-cephfs-1518590498
19:00:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get Secret secret-test-cephfs-1518590498 -o yaml
19:00:39 - MainThread - ocs_ci.ocs.ocp - INFO - Secret secret-test-cephfs-1518590498 got deleted successfully
19:00:39 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig delete CephFilesystem ocsci-cephfs
19:00:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig get CephFilesystem ocsci-cephfs -o yaml
19:00:41 - MainThread - ocs_ci.ocs.ocp - INFO - CephFilesystem ocsci-cephfs got deleted successfully

**Comment by ebenahar** [comment]
Fixed by https://github.com/red-hat-storage/ocs-ci/pull/572
