### ISSUE TITLE
[WA]: Revert PR 5797

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#5798]
Revert PR 5797 once bug https://bugzilla.redhat.com/show_bug.cgi?id=2075422 is fixed

**Comment by petr-balogh** [comment]
As I am working on another W/A I created this issue: https://github.com/red-hat-storage/ocs-ci/issues/5812

Before I noticed this one but in the new one issue I am covering both PRs.

So if this one is needed as well:
https://github.com/red-hat-storage/ocs-ci/pull/5813

We will need to revert both PRs

**Comment by petr-balogh** [comment]
I will close this issue as we have another issue here: https://github.com/red-hat-storage/ocs-ci/issues/5812 to track both W/A PRs to be reverted
