### ISSUE TITLE
tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-CLI-DEFAULT-BACKINGSTORE]

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#5816]
tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-CLI-DEFAULT-BACKINGSTORE]

Test deletion of bucket using the S3 SDK, MCG CLI and OC

OCP version 4.10.9
OC_OCS_VERSION: '4.9'

Steps to reproduce:
Run prep steps from [ocs-ci.readthedocs.io/en/latest/usage.html](https://ocs-ci.readthedocs.io/en/latest/usage.html)

sed -i 's/ocs_csv_channel:./ocs_csv_channel: "stable-4.9"/' ocs_ci/framework/conf/default_config.yaml
sed -i 's/default_ocs_must_gather_latest_tag:./default_ocs_must_gather_latest_tag: "latest-4.9"/' ocs_ci/framework/conf/default_config.yaml
sed -i 's/ocs_version:.*/ocs_version: "4.9"/' ocs_ci/framework/conf/default_config.yaml

run-ci tests/ --html report.html -m acceptance --cluster-path /home/kni/ocs-ci/cluster/ --cluster-name spk-factory-0 --ocs-version 4.9 --ocp-version 4.10 --collect-logs --collect-logs-on-success-run --junit-xml junit.xml --ocsci-conf=ocs_ci/framework/conf/default_config.yaml --ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml

**Comment by achuzhoy** [comment]
Reproduced on another environment:
=========================== short test summary info ============================                                                                                       
FAILED tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-CLI-DEFAULT-BACKINGSTORE]

The full output from the run is here:
[ceph_test_log.gz](https://github.com/red-hat-storage/ocs-ci/files/8612519/ceph_test_log.gz)

**Comment by petr-balogh** [comment]
As we discussed in other issue, can you please also include must gather logs? And basically all logs from the log path you set? As the console output you added is only info level, the logs we then store in logs folder are the debug level logs.  Also I suggest to put it to some RH location and not share in public as it might contains some sensitive data ;) 

@red-hat-storage/red-squad is owner of this test case. So we will need to have a look from some team member.

**Comment by MeridianExplorer** [comment]
Duplicates #5815
