### ISSUE TITLE
Upgrade from ODF4.10.0 to ODF4.10.1 is failing on IBM Power platform

### ISSUE THREAD

**Issue by AaruniAggarwal** [red-hat-storage/ocs-ci#5842]
CSVs are getting upgraded but some of the pods are not getting restarted. The upgrade is failing with the following error: 

```
        if timeout < (time.time() - start_time):
>           raise TimeoutException(msg)
E           ocs_ci.ocs.exceptions.TimeoutException: Timeout 60 reached! Error: Waiting for 5 pods with selector: app=noobaa to be running and upgraded.
```

**Comment by petr-balogh** [comment]
I suggest you to open a bug in bugzilla and attaching the logs there as ocs-ci waits and check pods to be upgraded which in your case was not the case looks like.

As automation shows that at least one of mcg pod didn't get the new upgraded image.

I didn't checked the logs as I am on iPhone only. Is this reproducible? Or was one time error?

**Comment by AaruniAggarwal** [comment]
Yes, `noobaa-default-backing-store-noobaa-pod-*` didn't get the new upgraded image. 

It is reproducible. Yesterday also, I tried upgrading from ODF4.10.0 to ODF4.10.1 and it failed with the same error. 

Sure, I will open a BZ. 
Thanks Petr.

**Comment by petr-balogh** [comment]
Ok, close then the issue with link to bug please as it doesn't look like ocs-ci issue.
Thanks

**Comment by AaruniAggarwal** [comment]
Created BZ for the same: https://bugzilla.redhat.com/show_bug.cgi?id=2082210

Sure Petr
Thanks.
