### ISSUE TITLE
Add subnet_id per region as constants in auth file per 

### ISSUE THREAD

**Issue by suchita-g** [red-hat-storage/ocs-ci#5870]
Managed service consumer for now utilized provider name to get subnet id used by the provider to deploy the consumer cluster in the same vpc as the provider. Now with appliance model deployment, the vpc has been created separately and both consumers and rosa create service command utilizes this subnet_id input as a part of rosa deployment command.  We need to make this fix on priority because:
1. subnet id doesn't get detected by code when the provider is created using the appliance model. hence consumer deployment for appliance mode provider failed due to empty string return value of getting subnet id function
2. We have to make the ci deployment flexible for both the type of deployment add-on mode deployment as well as appliance mode deployment

**Comment by dahorak** [comment]
I would propose to put this information to configuration file under `ENV_DATA` section like this:
```
ENV_DATA:
  ms_provider_subnet_ids_per_region:
    us-east-1: "<subnet-ids>"
    us-east-2: "<subnet-ids>"
    ...
```
Then the subnet IDs will be available via following code: 
```
config.ENV_DATA["ms_provider_subnet_ids_per_region"][config.ENV_DATA["region"]]
```
(It would be good to handle prospective `KeyError` exception with some descriptive log message what should be configured.)

@suchita-g WDYT?

**Comment by suchita-g** [comment]
Yes, I agree. I think this is the best way

**Comment by dahorak** [comment]
Created [ocs4-jenkins MR!1036](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/1036) with the update.

**Comment by dahorak** [comment]
The [ocs4-jenkins MR!1036](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/1036) was already merged, closing this issue.
