### ISSUE TITLE
test_create_delete_pool fails with "TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#5885]
[tests/ui/test_create_pool_block_pool.py](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/ui/test_create_pool_block_pool.py) contains following 4 tests:
```
tests/ui/test_create_pool_block_pool.py::TestPoolUserInterface::test_create_delete_pool[3-True]
tests/ui/test_create_pool_block_pool.py::TestPoolUserInterface::test_create_delete_pool[3-False]
tests/ui/test_create_pool_block_pool.py::TestPoolUserInterface::test_create_delete_pool[2-True]
tests/ui/test_create_pool_block_pool.py::TestPoolUserInterface::test_create_delete_pool[2-False]
```

All above mentioned tests fail with below error in OCS 4.8 test runs:

```
failed on setup with "TypeError: 'NoneType' object is not callable"

Stack Trace
self = <test_create_pool_block_pool.TestPoolUserInterface object at 0x7f420820c970>
storageclass_factory_ui = None, replica = 3, compression = True

    @pytest.fixture()
    def storage(self, storageclass_factory_ui, replica, compression):
>       self.sc_obj = storageclass_factory_ui(
            create_new_pool=True, replica=replica, compression=compression
        )
E       TypeError: 'NoneType' object is not callable

tests/ui/test_create_pool_block_pool.py:52: TypeError
```

These failures have been observed in multiple runs. Few Run IDs for reference: 1649916068, 1651826789, 1651826457

**Comment by sidhant-agrawal** [comment]
Latest failures observed in RUN ID: 1653899829
@shyRozen can you please take a look as this issue? Thanks

**Comment by shyRozen** [comment]
The return from the factory was run down by another PR https://github.com/red-hat-storage/ocs-ci/commit/3f59097bf30b583b861c355c51fe85392a2f1dc4?diff=unified . Need to commit the return factory again.
