### ISSUE TITLE
Selenium UI Crashes in Automation of Creating clusters via ACM

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#5904]
Here is the [link to the job ](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-multi-ocs-cluster-x3/385/consoleFull) and the main exception:
```
2022-05-16 15:49:34  E       selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
2022-05-16 15:49:34  E         (unknown error: DevToolsActivePort file doesn't exist)
2022-05-16 15:49:34  E         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
2022-05-16 15:49:34  
2022-05-16 15:49:34  venv/lib64/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
2022-05-16 15:49:34  =========================== short test summary info ============================
2022-05-16 15:49:34  ERROR tests/ecosystem/deployment/test_deployment.py::test_deployment - seleni...
2022-05-16 15:49:34  ====================== 947 deselected, 1 error in 19.16s =======================
```

Some arguments need to be added I guess to the Selenium in order to fix that, according to[ this SO Poll](https://stackoverflow.com/questions/22424737/unknown-error-chrome-failed-to-start-exited-abnormally).

**Comment by jimdevops19** [comment]
I am thinking of some **chrome_options** that are necessary in order to cover this one. Mentioning you guys in case you have any consults, thanks. @am-agrawa @petr-balogh @shylesh @sidhant-agrawal @OdedViner

**Comment by am-agrawa** [comment]
@jimdevops19 you may refer this- https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t
however-
```
A common cause for Chrome to crash during startup is running Chrome as root user (administrator) on Linux. While it is possible to work around this issue by passing --no-sandbox flag when creating your WebDriver session, such a configuration is unsupported and highly discouraged. You need to configure your environment to run Chrome as a regular user instead.
```

adding options like this would help-
```
options.addArguments("--disable-dev-shm-usage"); // overcome limited resource problems
options.addArguments("--no-sandbox"); // Bypass OS security model
```

**Comment by jimdevops19** [comment]
@am-agrawa 
Just confirming that combining both args `--no-sandbox`, `--disable-dev-shm-usage` did not do the trick.
@shylesh Did you face any similar challenges with the Selenium when you tested this one? 

Something similar happened when @AviadP was working on automating copying the **kubeconfig** content to the textbox of the import page in the ACM, but `--disable-dev-shm-usage` solved it, as it was annoyed by memory limitation.

This time it does not seem like this is the case, because the failure happens quite early as the driver gets initialized.

**Comment by shylesh** [comment]
> @am-agrawa Just confirming that combining both args `--no-sandbox`, `--disable-dev-shm-usage` did not do the trick. @shylesh Did you face any similar challenges with the Selenium when you tested this one?
> 
> Something similar happened when @AviadP was working on automating copying the **kubeconfig** content to the textbox of the import page in the ACM, but `--disable-dev-shm-usage` solved it, as it was annoyed by memory limitation.
> 
> This time it does not seem like this is the case, because the failure happens quite early as the driver gets initialized.

@jimdevops19 , I didn't face any issues during my local testing on chrome browser.

**Comment by petr-balogh** [comment]
@shylesh was this tested locally with headless mode?

**Comment by petr-balogh** [comment]
I think that this is the issue:
https://github.com/red-hat-storage/ocs-ci/blob/2dd59d11b5081444fee6909c1c4a15725eb6eaeb/conf/ocsci/multicluster_acm_ocp_deployment.yaml#L4

The headless mode should be enabled and changed to True here.

**Comment by jimdevops19** [comment]
#5940 The headless flag was turned on in the `yaml` configuration file we passed.
