### ISSUE TITLE
When we create an RHEL node there are some issues

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#5926]
1. compute nodes are not removed
2. LB is not updated with rhel ips
3. aws routes for computes are not removed

**Comment by vavuthu** [comment]
> 1. compute nodes are not removed
> 
Compute nodes will be removed during teardown. From the OCP cluster, compute nodes are removed once rhel nodes are added

>     2. LB is not updated with rhel ips

There is no issue here, already it taken care in automation.

>     3. aws routes for computes are not removed

these will be removed as part of teardown

**Comment by vavuthu** [comment]
closing this issue as there is no pending actions
