### ISSUE TITLE
(NotFound): routes.route.openshift.io "ocs-storagecluster-cephobjectstore"

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#5951]
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/4289/testReport/junit/tests.manage.rgw.test_bucket_creation/TestRGWBucketCreation/test_bucket_creation_3_RGW_OC_/
RGW bucket creation and deletion passed but obc class checks for non existing route.

@MeridianExplorer Seems to be due to changes in https://github.com/red-hat-storage/ocs-ci/pull/4643

**Comment by MeridianExplorer** [comment]
Indeed, it seems like in some ODF version, the RGW route name was changed from `rook-ceph-rgw-ocs-storagecluster-cephobjectstore` to `ocs-storagecluster-cephobjectstore`
