### ISSUE TITLE
`test_multiregion_mirror` is too fragile and needs more retry mechanisms

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#5969]
At the moment, the test is testing IO in a disruptive case. The scenario oftentimes causes race conditions that do not necessarily reflect real-life usage.
Thus, functions such as `sync_object_directory` need to be wrapped with a `retry()` to make sure that the test doesn't fail due to such race conditions

**Comment by nik-redhat** [comment]
What should be `tries` and `delay` count in this case?
Will the default values of `tries=4` and `delay=3`, do here?

**Comment by MeridianExplorer** [comment]
`tries=3, delay=10`
