### ISSUE TITLE
(Improvement) Use a logic to setback cluster ctx if some testcase changed it

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#6041]
I and @yitzhak12 discussed a scenario where the cluster context might change during single test execution, and the next test case is going to kickstart with the current index which might change.

Consider the following scenario:
10 tests are needed to execute in one `run-ci` trigger.
The first test needs to run on a consumer cluster **only**, so the function `config.switch_ctx(i)` must be called.
Once the second test enters, it's going to run on a consumer cluster, **unless** the function `config.switch_ctx(i)` is called in order to run the test in the desired cluster.

This can lead to hundreds of calls for the `switch_ctx()` function in the future, which we might want to avoid (?)

Possible solution:
We might want to create a function scope fixture that after each test, will setback the current ctx to the `default-cluster-context-index`.
That way, I can be sure that the current ctx before each test enters, is the ctx that was given in `--default-cluster-context-index`.

Not sure if this is the perfect solution but just looking for a way to avoid using multiple **ifs** and **skipifs** in the future.
@shylesh

**Comment by yitzhak12** [comment]
In addition to what @jimdevops19 mentioned, the solution above will make it easier to organize and analyze the tests.
For example, if we want to run the tests in tier1 with two consumers and a provider. If some of the tests run on one consumer and the other on a provider, it will be complicated to analyze and focus on the problems. 
Instead, when every test starts with the same cluster, it will be easier to analyze the tests and focus on the relevant issues related to the cluster

**Comment by shylesh** [comment]
> 

@jimdevops19 ack, it makes sense to restore the ctx.

**Comment by dahorak** [comment]
Initially I was thinking about simple autouse fixture for function level, which will switch back to the default cluster context. But I'm afraid that, it will conflict with some other fixtures, like `@runs_on_provider`.
Now I'm thinking if it might be possible to solve it via autouse fixture with finializer and switch the context to default cluster context at the end of each test, but still not sure, if it might conflict with some other fixtures?
