### ISSUE TITLE
Drop python 3.7 support, add 3.10

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#6158]
The numpy package needs to be updated in order to resolve a dependency security risk. The new version is not supported on python 3.7 so we will need to drop python 3.7 support. In addition to that since python 3.10 is the latest stable version we should add it to our tox envlist.

- [x] Drop python 3.7 support
- [ ] Add pythton 3.10 support
- [x] Update documentation to reflect changes

**Comment by petr-balogh** [comment]
Related issue: https://github.com/red-hat-storage/ocs-ci/issues/5997
