### ISSUE TITLE
Fix the MS markers to refer to the "default-cluster-context-index" instead of checking the current cluster

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#6162]
Currently, the MS markers such as `skipif_ms_consumer`, `skipif_ms_provider`, `ms_provider_required`, etc., do not work as expected - which means it sometimes checks the first cluster and sometimes it checks the last cluster. 
This can result in skipping or running unnecessary tests on the wrong cluster.

The solution is to refer to the "default-cluster-context-index" instead of checking the current cluster.
By default, it should be the first cluster as defined in the code here: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/main.py#L132. 

For example, in the marker `skipif_ms_consumer` instead of writing `config.ENV_DATA["cluster_type"].lower() == "consumer"`, we change it into `config.clusters["default-cluster-context-index"].ENV_DATA["cluster_type"].lower() == "consumer"` 

We can also define a new var like `config.default_cluster` to make it easier to check.

**Comment by yitzhak12** [comment]
This may relate also to the issue https://github.com/red-hat-storage/ocs-ci/issues/5776.

**Comment by fbalak** [comment]
It makes sense. Other way to fix it would be to ensure that context is always on the default cluster when those markers are evaluated.
I think that context should be changed to different cluster only during a test. Changed context shouldn't persist for multiple clusters (that being said, there is also a problem with fixtures and what context they are applied to).
