### ISSUE TITLE
inconsistent failuer in Provider or consumer post deployment test for node status, need an workarounf in ocs-ci for MS deployements

### ISSUE THREAD

**Issue by suchita-g** [red-hat-storage/ocs-ci#6189]
Reason: The OCM cluster status is ready even before nodes reach ready status and hence it causes failure in the post-deployment test. 
Related platform fix from OCM: [SDA-6346](https://issues.redhat.com/browse/SDA-6346),[ SDA-6341](https://issues.redhat.com/browse/SDA-6341) story [SDA-5349](https://issues.redhat.com/browse/SDA-5349)

---------------------------------------------------------------------------------------
Error Details: 
2022-07-12 12:37:36  ocs_ci/helpers/sanity_helpers.py:41: in health_check
2022-07-12 12:37:36      node.wait_for_nodes_status(timeout=300) 
in 
tests/ecosystem/deployment/test_deployment.py:52:
----------------------------------------------------------------------------------------
Job Reference:
Consumer: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/14499/consoleFull
Provider: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/14662/
----------------------------------------------------------------------------------------
OCS-CI post-deployment workaround till story [SDA-5349](https://issues.redhat.com/browse/SDA-5349) get resolved is to change the error/to warning for managed service.

**Comment by fbalak** [comment]
Workaround PR: https://github.com/red-hat-storage/ocs-ci/pull/6197/
