### ISSUE TITLE
Timed out after 240s running get("ocs-storagecluster-cephfs", True, None) | operators.operators.coreos.com "odf-operator.openshift-storage" not found

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#6195]
OCP: 4.10.20
ocs-operator.v4.10.4

=========================== short test summary info ============================
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephFileSystem]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephFileSystem]
FAILED tests/manage/rgw/test_rgw_pod_existence.py::TestRGWPodExistence::test_rgw_pod_existence

ERROR tests/manage/mcg/test_bucket_creation.py::TestBucketCreation::test_bucket_creation[3-OC-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_creation.py::TestBucketCreation::test_bucket_creation[3-CLI-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-S3-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-CLI-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-OC-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_write_to_bucket.py::TestBucketIO::test_write_file_to_bucket[DEFAULT-BACKINGSTORE]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Delete]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Delete]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephFileSystem]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephFileSystem]
ERROR tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephFileSystem]
= 3 failed, 13 passed, 7 skipped, 917 deselected, 13 errors in 6385.35s (1:46:25) =

The executed command was:
run-ci tests/ --html report.html -m acceptance --cluster-path /home/kni/ocs-ci/cluster/ --cluster-name spk-factory-0 --ocs-version 4.10 --ocp-version 4.10 --collect-logs --collect-logs-on-success-run --junit-xml junit.xml --ocsci-conf=ocs_ci/framework/conf/default_config.yaml --ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml --ocsci-conf=/home/kni/ocs-ci/sasha.yaml|tee ocs_test.log

sasha.yaml content:

REPORTING:
  default_ocs_must_gather_latest_tag: 'latest-4.10'
ENV_DATA:
  ocs_version: '4.10'
RUN:
  log_dir: "/tmp/sasha"
DEPLOYMENT:
  ocs_csv_channel: "stable-4.10"

**Comment by achuzhoy** [comment]
[ocs_test.log.gz](https://github.com/red-hat-storage/ocs-ci/files/9132508/ocs_test.log.gz)

**Comment by achuzhoy** [comment]
@MeridianExplorer Do you think we need several issue for what seems like several different errors or is this one ticket enough?

**Comment by achuzhoy** [comment]
I just executed a set of tests against a re-deployed setup.
The "data" directory was in the root of the clone.

the mcg failures are still there.
=========================== short test summary info ============================
ERROR tests/manage/mcg/test_bucket_creation.py::TestBucketCreation::test_bucket_creation[3-S3-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_creation.py::TestBucketCreation::test_bucket_creation[3-OC-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_creation.py::TestBucketCreation::test_bucket_creation[3-CLI-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-S3-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-CLI-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-OC-DEFAULT-BACKINGSTORE]
ERROR tests/manage/mcg/test_write_to_bucket.py::TestBucketIO::test_write_file_to_bucket[DEFAULT-BACKINGSTORE]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Delete]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Delete]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Delete]
ERROR tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
ERROR tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephFileSystem]
ERROR tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephBlockPool]
ERROR tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephFileSystem]
ERROR tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Retain]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephFileSystem]
ERROR tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephBlockPool]
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephFileSystem]
ERROR tests/manage/rgw/test_bucket_creation.py::TestRGWBucketCreation::test_bucket_creation[3-RGW-OC]
ERROR tests/manage/rgw/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-RGW-OC]
ERROR tests/manage/rgw/test_rgw_pod_existence.py::TestRGWPodExistence::test_rgw_pod_existence
========== 7 skipped, 912 deselected, 28 errors in 2208.67s (0:36:48) ==========



`
the following command was executed:
run-ci tests/ \
-m acceptance \
--html logs/report.html \
--self-contained-html \
--cluster-path /home/kni/ocs-ci/cluster/ \
--cluster-name \"spk-factory-0\" \
--ocs-version \"4.10\" \
 --ocp-version \"4.10\" \
--collect-logs \
--collect-logs-on-success-run \
--junit-xml logs/junit.xml \
--ocsci-conf=ocs_ci/framework/conf/default_config.yaml \
--ocsci-conf=conf/deployment/baremetal/up i_1az_rhcos_nvme_intel_3m_3w.yaml \
--ocsci-conf=conf/custom.yaml 2>&1 |tee logs/test_odf_output.log
`

**Comment by achuzhoy** [comment]
@MeridianExplorer let me know if a new bug is needed based on the errors. There's 4.4GB of data under the  logs dir. If there's anything of interest - I'll attach it to the issue.
Thanks.

**Comment by achuzhoy** [comment]
[test_odf_output.log.gz](https://github.com/red-hat-storage/ocs-ci/files/9193587/test_odf_output.log.gz)

**Comment by achuzhoy** [comment]
attached the console output for the tests execution.

**Comment by achuzhoy** [comment]
latest rerun shows:

```
=========================== short test summary info ============================
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Retain]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]
ERROR tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephBlockPool]
```

The full output log is attached.

**Comment by achuzhoy** [comment]
[test_odf_output.log.gz](https://github.com/red-hat-storage/ocs-ci/files/9229542/test_odf_output.log.gz)

**Comment by achuzhoy** [comment]
any updates on this one? the errors seem to reproduce.

**Comment by achuzhoy** [comment]
Executed the same test today against:

OCP4.10.34

local-storage-operator.4.10.0-202209080237                                   
mcg-operator.v4.10.6                              NooBaa Operator                                     
ocs-operator.v4.10.6                              OpenShift Container Storage
odf-csi-addons-operator.v4.10.6                   CSI Addons
odf-operator.v4.10.6                              OpenShift Data Foundation



```
=========================== short test summary info ============================
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Retain]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]
ERROR tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephBlockPool]
= 3 failed, 18 passed, 6 skipped, 948 deselected, 7 errors in 5852.89s (1:37:32) =
```

**Comment by achuzhoy** [comment]
```
oc exec -n openshift-storage rook-ceph-tools-7659d89cb6-xqvgc -- ceph status
  cluster:
    id:     32e936cc-f3e1-4502-94f3-3a8eb519083b
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 21h)
    mgr: a(active, since 21h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 9 osds: 9 up (since 21h), 9 in (since 21h)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   11 pools, 273 pgs
    objects: 6.02k objects, 21 GiB
    usage:   70 GiB used, 1010 GiB / 1.1 TiB avail
    pgs:     273 active+clean
 
  io:
    client:   937 B/s rd, 4.8 KiB/s wr, 1 op/s rd, 0 op/s w```

**Comment by achuzhoy** [comment]
[ocs_test.log.gz](https://github.com/red-hat-storage/ocs-ci/files/9767488/ocs_test.log.gz)
logs

**Comment by achuzhoy** [comment]
This issue is open for almost 3 months. How do we expedite this?

**Comment by ebenahar** [comment]
@MeridianExplorer @achuzhoy sorry, missed this issue and notification.

Looking at the logs, I can see that the default RBD storageclass is not found - `ocs-storagecluster-ceph-rbd`.

Could you please paste the output of `oc get storageclass`?

Thanks

**Comment by achuzhoy** [comment]
@ebenahar  Thanks.
Re-executed the test on 4.10.38:
```
=========================== short test summary info ============================
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Retain]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]
ERROR tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephBlockPool]
= 3 failed, 18 passed, 6 skipped, 950 deselected, 7 errors in 6574.52s (1:49:34) =
(.venv) [kni@provisionhost-0-0 ocs-ci]$ 

```



```
(.venv) [kni@provisionhost-0-0 ocs-ci]$ oc get storageclass
NAME                                    PROVISIONER                             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
localstorage-sc-block                   kubernetes.io/no-provisioner            Delete          WaitForFirstConsumer   false                  19h
ocs-storagecluster-ceph-rbd (default)   openshift-storage.rbd.csi.ceph.com      Delete          Immediate              true                   18h
ocs-storagecluster-ceph-rgw             openshift-storage.ceph.rook.io/bucket   Delete          Immediate              false                  19h
ocs-storagecluster-cephfs               openshift-storage.cephfs.csi.ceph.com   Delete          Immediate              true                   18h
openshift-storage.noobaa.io             openshift-storage.noobaa.io/obc         Delete          Immediate              false                  18h
```

**Comment by ebenahar** [comment]
This time the failures are different with the pv_services test cases that previously failed, due to the missing default RBD SC, now pass.

We have these failures this time:
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool


@achuzhoy please attach the logs. Thanks

**Comment by achuzhoy** [comment]
[ocs_test.log.gz](https://github.com/red-hat-storage/ocs-ci/files/9870141/ocs_test.log.gz)

**Comment by ebenahar** [comment]
Thanks @achuzhoy 
Could you please send an email to ocs-qe@redhat.com with the results breakdown and the log file?

**Comment by achuzhoy** [comment]
> Thanks @achuzhoy Could you please send an email to [ocs-qe@redhat.com](mailto:ocs-qe@redhat.com) with the results breakdown and the log file?

Sent.
Thanks.

**Comment by achuzhoy** [comment]
Rachael George is working on a fix.
Basically it comes down to having a check for ocs-storagecluster-ceph-rbd storageclass. 
If it's configured to be the default sc  (like in my case)- then the check doesn't match it properly:

Below is from the same cluster:
oc get storageclass ocs-storagecluster-ceph-rbd
OUTPUT:
NAME                                    PROVISIONER                          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ocs-storagecluster-ceph-rbd (default)   [openshift-storage.rbd.csi.ceph.com](http://openshift-storage.rbd.csi.ceph.com/)   Delete          Immediate           true                   20h

vs

oc get storageclass ocs-storagecluster-ceph-rbd --no-headers -o custom-columns=":[metadata.name](http://metadata.name/)"
OUTPUT:
ocs-storagecluster-ceph-rbd
