### ISSUE TITLE
 ocs-ci/docs/getting_started.md: "python3.7 -m .venv <path/to/venv>" does not work

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#62]
ocs-ci/docs/getting_started.md: "python3.7 -m .venv <path/to/venv>" does not work. It fails with error message "/usr/local/bin/python3.7: Relative module names not supported".

Fix: remove "." in ".venv" in above command.

Correct command: "python3.7 -m venv <path/to/venv>"

**Comment by petr-balogh** [comment]
Fixed in #65
