### ISSUE TITLE
Remove usage of check_clusters() function from pytest plugin code

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#6214]
## Problem description

In https://github.com/red-hat-storage/ocs-ci/pull/6038/files PR, function `check_clusters()` was introduced into [ocscilib.py](https://github.com/red-hat-storage/ocs-ci/pull/6038/files#diff-81dd75ca7912048f20e991916771e11b16203494498849a39b6189401b3ac974) module.

This is not a good idea, because the plugin code is executed during all use cases of pytest run, from running `run-ci --help`, to running unit tests, where we don't expect cluster to exist.

This already breaks other PRs, eg. unit tests of these are failing because of that:

- https://github.com/red-hat-storage/ocs-ci/pull/6051 (removing check_clusters import from the ocscilib.py file fixes the problem with circular dependency there)

It also causes confusing errors, eg.:

- when toolbox pod is not properly initialized on a bare metal cluster, pytest or run-ci fails during internal initialization, with `Error is error: the server doesn't have a resource type "lvmcluster"` which is confusing

## Possible solutions

- The import and usage of this function needs to be removed, and the functionality placed somewhere else.
- The function would need to be moved into a dedicated module, and updated so that it properly handles errors.

**Comment by shyRozen** [comment]
Hi Martin. `check_clusters` was change in #6163 and polished in #6162 .
The main thing was to move from classes init for CephCluster And LVM to query the OCP kind. There was work also to silent the none existing cluster.
