### ISSUE TITLE
Fix or skip the test "test_recovery_from_volume_deletion" with external mode

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#6256]
In the test "test_recovery_from_volume_deletion" in the file `ocs_ci/ocs/osd_operations.py` in the function `get_deviceset_pvs` when using the external mode cluster, it didn't find the device set PVCs as you can see in the test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/4875/testReport/tests.manage.z_cluster.nodes.test_disk_failures/TestDiskFailures/test_recovery_from_volume_deletion/. 
The error above happens because with the external mode cluster we don't have the device set PVCs in the cluster. We have only the following PVCs: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-042vu1ce33-t4a/j-042vu1ce33-t4a_20220727T061528/logs/failed_testcase_ocs_logs_1658905258/test_recovery_from_volume_deletion_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-0f2930840e319c4aa409cc32d0f2a2b4e2fc1ffd4055ffee15b3d4fe599ab145/namespaces/all/pvc_all_namespaces. 

We have two options to fix it:

1. Skip the test when using external mode.
2. Modify the test to run on the external mode cluster(I am not sure yet about the best solution).

**Comment by sidhant-agrawal** [comment]
Failure is expected because in case of external mode cluster, we don't have OSD pods and PVCs in ODF side. The test can be skipped when using external mode.

**Comment by yitzhak12** [comment]
Thanks @sidhant-agrawal. So I will create a new pr to skip this test with external mode.
