### ISSUE TITLE
Add check for collection of tests

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#628]
Add --collect-only to tox to prevent issues like we had today #626

**Comment by zmc** [comment]
Would it be enough to check "Include Administrators" [here](https://github.com/red-hat-storage/ocs-ci/settings/branch_protection_rules/5068680) ?

**Comment by petr-balogh** [comment]
@zmc How does it help in case I am fixing? The ci passed for case mentioned in issue. This will ensure we are still able to collect all tests and there are no critical failures in imports and so on. See the example of failure in comment.
