### ISSUE TITLE
fix get_pool_name()

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#6289]
Function `get_pool_name()` assumes OCS pool naming scheme, but this may not hold on an external cluster. So for external cluster, it should *be given* expected pool names to avoid this problem, since with an external cluster we can't guess the names anymore.

For some reason, external clusters we used were following the naming scheme, so it seemed to work.

## Examples of error messages caused by this

```
>       assert ceph_pool is not None, f"Pool: {ceph_pool_name} doesn't exist!"
E       AssertionError: Pool: ocs-storagecluster-cephblockpool doesn't exist!

ocs_ci/ocs/fiojob.py:69: AssertionError
```

```
2022-08-07 23:01:37Message: failed on setup with "AssertionError: Pool: ocs-storagecluster-cephblockpool doesn't exist!"
```

**Comment by mbukatov** [comment]
Or, maybe we should try to get this info from the storage class? There is a pool parameter.

**Comment by DanielOsypenko** [comment]
still happens https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/401/7918/346192/346328/346329/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1h7tquhpjupuu%252Cti_u7ukrfvrt1yu%252Cti_qxkzvw4t6ipf%252Cti_1h7u8s8jf8tvb&logParams=history%3D282548%26page.page%3D1

**Comment by DanielOsypenko** [comment]
add new failure: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8982/397276/397277/397279/log?logParams=history%3D397279%26page.page%3D1
