### ISSUE TITLE
Test case test_clone_pvc[ocs-storagecluster-cephfs-ReadWriteMany-ReadWriteOnce] failing

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#6302]
Test case given below is failing.
tests/ui/test_pvc_ui.py::TestPv cUserInterface::test_clone_pvc[ocs-storagecluster-cephfs-ReadWriteMany-ReadWriteOnce]

```
# Clone PVC from UI
        clone_pvc_name = f"{pvc_name}-clone"
        pvc_ui_obj.pvc_clone_ui(
            project_name=project_name,
            pvc_name=pvc_name,
            cloned_pvc_access_mode=clone_access_mode,
            cloned_pvc_name=clone_pvc_name,
        )
    
        teardown_factory(
>           get_pvc_objs(pvc_names=[clone_pvc_name], namespace=project_name)[0]
        )
E       IndexError: list index out of range

tests/ui/test_pvc_ui.py:286: IndexError
```
Actual name of the cloned PVC was "pvc-test-ea0741296ae34a8dab7bb9127fafb0c-clonepvc-test-ea0741296ae34a8dab7bb9127fafb0c-clone"

RUN ID: 1659899878

Note:
The test case tests/ui/test_pvc_ui.py::TestPvcUserInterface::test_clone_pvc[ocs-storagecluster-ceph-rbd-ReadWriteOnce-ReadWriteOnce] passed in the same run.

**Comment by rachael-george** [comment]
The test case failed with the same error in RUN ID: 1666391000

**Comment by am-agrawa** [comment]
Looks like the cloned_pvc name was sent twice in the text box right before we click on the Clone button. 
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-212ai3c33-ua/j-212ai3c33-ua_20221021T131042/logs/ui_logs_dir_1666391000/screenshots_ui/test_clone_pvc%5bocs-storagecluster-ceph-rbd-ReadWriteOnce-ReadWriteOnce%5d/2022-10-22T13-00-38.367599.png

For the fix, we should always ensure that we clear the textbox before sending a text. No matter if it's already empty or not.

**Comment by am-agrawa** [comment]
@sidhant-agrawal Do we still see this issue?

**Comment by am-agrawa** [comment]
Assigned to Elena after discussion

**Comment by am-agrawa** [comment]
Hi @ebondare Did you get a chance to look into this issue?

**Comment by ebondare** [comment]
Hi! I've just started working on it, sorry for the delay
