### ISSUE TITLE
No need to wait for rook-ceph-tools pods when ODF uses mcg/noobaa

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#6351]
I have a deployment of ODF that uses MCG/Noobaa.
There's no ceph.

Yet the test log shows an error related to waiting for rook-ceph-tools

```
test_write_file_to_bucket[DEFAULT-BACKINGSTORE] failed (1 runs remaining out of 2).
        <class 'ocs_ci.ocs.exceptions.CommandFailed'>
        Error during execution of command: oc wait --for condition=ready pod -l app=rook-ceph-tools -n openshift-storage --timeout=120s.
Error is error: timed out waiting for the condition on pods/rook-ceph-tools-787676bdbd-mtqhc
```

OCP version 4.10.27
ODF 4.10

**Comment by achuzhoy** [comment]
@ebenahar

**Comment by achuzhoy** [comment]
[test_odf_output.log.gz](https://github.com/red-hat-storage/ocs-ci/files/9377762/test_odf_output.log.gz)

**Comment by achuzhoy** [comment]
@ebenahar any comments on this one?
Thanks.

**Comment by petr-balogh** [comment]
Hello @achuzhoy , how the whole execution command look like? 

Have you passed this configuration file: https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocsci/mcg_only_deployment.yaml
via `--ocsci-conf` cli argument?

This is the must when running over MCG only deployment.

**Comment by achuzhoy** [comment]
@petr-balogh 
Below is the execution command, "conf/ocsci/mcg_only_deployment.yaml" wasn't pased.
So to clarify, in case of mcg/noobaa usage, we need to add this additional arg, correct?

`run-ci tests/ \
-m "acceptance" \
--html logs/report.html \
--self-contained-html \
--cluster-path "/home/kni/ocs-ci/cluster/" \
--cluster-name "spk-factory-0" \
--ocs-version "4.10" \
--ocp-version "4.10" \
--collect-logs \
--collect-logs-on-success-run \
--junit-xml logs/junit.xml \
--ocsci-conf=ocs_ci/framework/conf/default_config.yaml \
--ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml \
--ocsci-conf=conf/custom.yaml`

**Comment by achuzhoy** [comment]
@petr-balogh 

Indeed, with:

```run-ci tests/ -m "acceptance" --html logs/report.html --self-contained-html --cluster-path "/home/kni/ocs-ci/cluster/" --cluster-name "spk-factory-0" --ocs-version "4.10" --ocp-version "4.10" --collect-logs --collect-logs-on-success-run --junit-xml logs/junit.xml --ocsci-conf=ocs_ci/framework/conf/default_config.yaml --ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml --ocsci-conf=conf/ocsci/mcg_only_deployment.yaml --ocsci-conf=conf/custom.yaml```

seeing:
```
13:37:30 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-tools -o yaml
13:37:30 - MainThread - ocs_ci.ocs.utils - INFO  - Skipping Ceph toolbox setup due to running in MCG only mode
13:37:30 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-tools -o yaml
```

**Comment by achuzhoy** [comment]
Feel free to close this issue (you might want to update the doc)
