### ISSUE TITLE
Managed service cluster deployment job error - pagerduty

### ISSUE THREAD

**Issue by ebondare** [red-hat-storage/ocs-ci#6356]
Managed service cluster deployment jobs fail with KeyError: 'escalation_policies' in ocs_ci/utility/pagerduty.py:201. 
Example job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/15798/console

**Comment by fbalak** [comment]
I am manually testing the code and it seems to be working. There might be a misconfiguration in our CI or there was a downtown in pagerduty. We can reopen this when we hit it again.
