### ISSUE TITLE
test_nodereplacement_proactive steps need to be fixed as per official documentation

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#6366]
It's a repetative failure, an instance of which is seen here-
ocs-ci results for OCS4-11-Downstream-OCP4-11-VSPHERE6-UPI-KMS-VAULT-V2-1AZ-RHCOS-VSAN-3M-3W-tier4a (BUILD ID: 4.11.0-137 RUN ID: 1660477488)

```
2022-08-14 18:13:20  12:43:20 - MainThread - ocs_ci.ocs.resources.pod - ERROR  - The pod rook-ceph-osd-0-5b8c7f867c-nlxws is in Init:0/9 state. Expected = Running
```

A relevant thread-
https://chat.google.com/room/AAAAzrvtvTI/_hARbq-jxQo

Jenkins logs- https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/5058/consoleFull
RP- https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/206/list?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti_qxkzvw4t6ipf%26launchesLimit%3D50%26isLatest%3Dfalse

One may also refer- https://bugzilla.redhat.com/show_bug.cgi?id=2116791

**Comment by yitzhak12** [comment]
The failure was a little different. In the end, all the pods reached the Ready state. The error was that the new osd node compute-3 was not found in the `ceph osd status` output: 

> ID  HOST        USED  AVAIL  WR OPS  WR DATA  RD OPS  RD DATA  STATE 0  compute-2   601M   511G      0     2457       3      105   exists 1  compute-0   891M   511G      0     2457       3      105   exists,up 2  compute-1   999M   511G      0     4914       1        0   exists,up

**Comment by yitzhak12** [comment]
In the automation code, we missed step 5:  `Log in to vSphere and terminate the identified VM.`. 
We need to add this step for vSphere UPI. For IPI deployment, we don't need this step, as we can see in the docs https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.10/html/replacing_nodes/openshift_data_foundation_deployed_using_dynamic_devices#replacing-an-operational-vmware-node-upi_rhodf
