### ISSUE TITLE
Test case test_rbd_space_reclaim_cronjob failed

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#6431]
The test case given below failed in RUN ID: 1661847016.

tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py::TestRbdSpaceReclaim::test_rbd_space_reclaim_cronjob

```
[tests.manage.pv_services.space_reclaim.test_rbd_reclaimspace_cronjob.TestRbdSpaceReclaim.test_rbd_space_reclaim_cronjob](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/5204/testReport/tests.manage.pv_services.space_reclaim.test_rbd_reclaimspace_cronjob/TestRbdSpaceReclaim/test_rbd_space_reclaim_cronjob/)
[ Error Details](javascript:hideFailureSummary('id3131791-error'))
ocs_ci.ocs.exceptions.UnexpectedBehaviour: Actual 76.5215 and expected size 73.718 not matching. Retrying
```

The expected value is the used size after I/O. Looks like extra 2.8 GB is added by some other operation during the test run.

**Comment by rachael-george** [comment]
Same issue seen in run: ocs-ci results for OCS4-12-Downstream-OCP4-12-VSPHERE6-UPI-ENCRYPTION-1AZ-RHCOS-VSAN-LSO-VMDK-3M-3W-tier1-or-tier_after_upgrade-post-upgrade (BUILD ID: 4.12.0-120 RUN ID: 1669952976)
