### ISSUE TITLE
Test test_overprovision_level_policy_control failed

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#6491]
Test test_overprovision_level_policy_control failing with the errors  viven below:

tests.manage.pv_services.test_overprovision_level_policy_control.TestOverProvisionLevelPolicyControl.test_over_provision_level_policy_control[ocs-storagecluster-ceph-rbd-CephBlockPool]
```

 Error Details
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc describe clusterresourcequota ocs-storagecluster-ceph-rbd-quota-sc-test.
Error is Error from server (NotFound): clusterresourcequotas.quota.openshift.io "ocs-storagecluster-ceph-rbd-quota-sc-test" not found
```

tests.manage.pv_services.test_overprovision_level_policy_control.TestOverProvisionLevelPolicyControl.test_over_provision_level_policy_control[ocs-storagecluster-cephfs-CephFileSystem]
```
 Error Details
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc describe clusterresourcequota ocs-storagecluster-cephfs-quota-sc-test.
Error is Error from server (NotFound): clusterresourcequotas.quota.openshift.io "ocs-storagecluster-cephfs-quota-sc-test" not found
```

RUN ID: 1662410931

**Comment by sidhant-agrawal** [comment]
Recently a fix was provided in PR #6402 , but tests are still failing due to Quota resource not exist.
For eg. RUN ID: 1669807992
tests.manage.pv_services.test_overprovision_level_policy_control.TestOverProvisionLevelPolicyControl.test_over_provision_level_policy_control[ocs-storagecluster-ceph-rbd-CephBlockPool]
```
ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed Out: Quota resource ocs-storagecluster-ceph-rbd-quota-sc-test does not exist after 60 seconds Name:		ocs-ocs-storagecluster-ceph-rbd-quota-sc-test
Created:	About a minute ago
Labels:		<none>
Annotations:	<none>
Namespace Selector: ["ocs-quota-sc-test"]
Label Selector: openshift-quota=quota-sc-test
AnnotationSelector: map[]
Resource									Used	Hard
--------									----	----
ocs-storagecluster-ceph-rbd.storageclass.storage.k8s.io/requests.storage	0	8Gi
```

@OdedViner Can you please take a look? Thanks.
