### ISSUE TITLE
Enable monitoring by default

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#651]
Since we just merged alerting test case OCS-1052, which requires monitoring to be enabled, we need to have the alerting enabled by default. When the deployment is handled by OCS operator, monitoring will be always enabled (OCS-954), so this change aligns us a bit with us expected OCS featureset.

So far, it was possible to enable monitoring via `monitoring_enabled` option, as shown in [`ocs-ci/conf/examples/monitoring.yaml`](https://github.com/red-hat-storage/ocs-ci/blob/master/conf/examples/monitoring.yaml) example file.

**Comment by mbukatov** [comment]
@petr-balogh Do I understand it right that it should be added into [`defaults.py`](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/defaults.py)?

**Comment by petr-balogh** [comment]
> @petr-balogh Do I understand it right that it should be added into [`defaults.py`](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/defaults.py)?

@mbukatov no, It has to be added here: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/conf/default_config.yaml
