### ISSUE TITLE
Fix OCP().new_project()

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#6512]
This condition https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocp.py#:~:text=if%20f%27Now%20using,)%3A would never be reached in scenarios such as below:

> Scenario:
> 
> - lets say the current project we're working on is "cosbench-project"
>   $ oc project
>   Using project "cosbench-project" on server "https:/".
> 
> - Now delete the `cosbench-project` project
>   $ oc delete project cosbench-project
>   project.project.openshift.io "cosbench-project" deleted
> 
> - Now again create the project `cosbench-project` using oc
>   $ oc new-project cosbench-project
>   Already on project "cosbench-project" on server "https:/".
>   
>   You can add applications to this project with the 'new-app' command. For example, try:
>   
>       oc new-app rails-postgresql-example
>   
>   to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:
>   
>       kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname

In step 3, When you recreate the same project without before switching to some other project, command execution outputs says "Already on project" instead of "Now using project" and hence this piece of code https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocp.py#:~:text=if%20version.,%3Dlabel) would never be executed even on successful creation of new projects in scenarios like this.  and the code mentioned is a fix for https://github.com/red-hat-storage/ocs-ci/issues/6332

Test failures seen because of this:
https://url.corp.redhat.com/4e8b72b

Logs:
https://url.corp.redhat.com/cdcff5d

**Comment by rachael-george** [comment]
Isn't the recommended way of deleting a project is to switch to a different project and then delete it? 
There could be situations where the project deletion could have failed and hence the message `Already on project...`

**Comment by mashetty330** [comment]
> Isn't the recommended way of deleting a project is to switch to a different project and then delete it? There could be situations where the project deletion could have failed and hence the message `Already on project...`

@rachael-george I dont think its mandatory to switch to other project before deleting the project (?)
You would get `Error from server (AlreadyExists): project.project.openshift.io "test-project" already exists` something like this if the project isn't deleted!
