### ISSUE TITLE
Revert back logging channel to "stable"

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#6523]
For now logging channel is set to stable-5.3 due to issue https://issues.redhat.com/browse/LOG-2789, revert back to stable once the issue is fixed

**Comment by PrasadDesala** [comment]
@Shrivaibavi @avd-sagare The issue is closed, should we set it back to stable channel?

**Comment by avd-sagare** [comment]
@PrasadDesala Yes, we can set it back to stable channel.

**Comment by avd-sagare** [comment]
reverted back to stable as https://issues.redhat.com/browse/LOG-2789 issue is fixed.
