### ISSUE TITLE
Improve the non ocs taint and toleration testing

### ISSUE THREAD

**Issue by bkunal** [red-hat-storage/ocs-ci#6531]
Here are a few improvement suggestions for the test case[1]

1) confirm the toleration by checking the pod yaml, just checking if the pod is running or not is not sufficient

It can be simply checked as below
#oc describe pod noobaa-db-pg-0 -n openshift-storage | grep "xyz=true:NoSchedule"

Here ""xyz=true:NoSchedule" is the taint. 
In the pod yaml, it should be listed in the Toleration section.

2)  Hardcode the list of pod, Just checking the pods which are listed by #oc get pods are not enough
     There might be a situation where the pod is not showing up. We may miss checking those pods if we are relying on pods list at run time.  toolbox and osd-prepare pods are a few examples. 

3)  Do not forcefully restart the pods, rather wait for pods to be restarted automatically. 

4) Consider adding the test for standalone MCG deployment as well. 

[1] https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py

**Comment by PrasadDesala** [comment]
@Shrivaibavi Please take a look and work on the suggested improvements.

**Comment by Shrivaibavi** [comment]
@bkunal Can we check the number of pods before adding toleration and number of pods after adding toleration so we dont miss any pods?  instead of hardcoding the pod_names ? After respin the pods would not have the same name.

**Comment by bkunal** [comment]
yeh, that should be even fine. Keep in mind if we scale( up or out) the number of pods would change.

One more thing to consider is that by default we have osd-prepare pod in the complete state, we need to exclude those pods as they will disappear on deletion. 

and 

On expansion, new osd prepare pod will come, and this will change the count.

So we need a better way to ensure that we are not missing any pods.

**Comment by PrasadDesala** [comment]
#6571 fixed this issue
