### ISSUE TITLE
OCS must gather folder only contains one file named `timestamp`

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#6539]
[Example](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/5590/)

**Comment by sagihirshfeld** [comment]
Encountered again in:

 https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/427/9272/411637/411653/411655/log?logParams=history%3D411655%26page.page%3D1
