### ISSUE TITLE
Collect OCP logs for the following test cases

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#6554]
For RUN ID 1664525414

tests/manage/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_recovery_from_volume_deletion
tests/manage/z_cluster/nodes/test_node_replacement_proactive.py::TestNodeReplacement::test_nodereplacement_proactive
tests/manage/z_cluster/nodes/test_node_replacement_proactive.py::TestNodeReplacementTwice::test_nodereplacement_twice

We don't have the OCP logs to further analyze these failures, especially the last two.

The last two tests failed with a similar message `Some nodes are not generated CSRs. Expected 4 but found 5 CSRs.retrying again` Just the count is different for each test.
Looks like more number of csr's were found in these tests, there is a chance that it could be some left over from a previous test. OCP logs would help to confirm it.

**Comment by AviadP** [comment]
Hi @am-agrawa , some of the logs from this run can be found [here](https://url.corp.redhat.com/8a746e4), is that help ?

**Comment by am-agrawa** [comment]
@AviadP No, we need OCP logs for that particular test case and the OCP logs you are pointing to gets collected at the end of the run so it won't help.
