### ISSUE TITLE
test_rgw_kafka_notifications.py fails with exception: Error: Messages are not recieved from Kafka side.

### ISSUE THREAD

**Issue by Akarsha-rai** [red-hat-storage/ocs-ci#6559]
The test `test_rgw_kafka_notifications.py` fails sometime with the below error and rerun again the same tests passes.
For more info:  https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/5674/testReport/tests.e2e.workloads.app.amq.test_rgw_kafka_notifications/TestRGWAndKafkaNotifications/test_rgw_kafka_notifications/

```
      raise Exception(
            "Error: Messages are not recieved from Kafka side."
            "RGW bucket notification is not working as expected."
        )
E           Exception: Error: Messages are not recieved from Kafka side.RGW bucket notification is not working as expected.
```

**Comment by PrasadDesala** [comment]
Closing it as a Duplicate of #8529
