### ISSUE TITLE
The MCG UI tests only work over ODF 4.8

### ISSUE THREAD

**Issue by Neon-White** [red-hat-storage/ocs-ci#6592]
The tests weren't checked or reworked for other ODF versions, and thus only run on ODF 4.8 in the moment

**Comment by keesturam** [comment]
I brought this up with @am-agrawa and this will be discussed in the UI automation group.

**Comment by am-agrawa** [comment]
The test name is `ocs_ci/ocs/ui/mcg_ui.py`

**Comment by am-agrawa** [comment]
@avd-sagare Any progress on fixing this?
