### ISSUE TITLE
Need to update templates to match with Yaml changes in rook repo

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#661]
Hi,

As observed in rook, most of the yamls for deployment have undergone changes. Hence, till we keep using the saved templates instead of fresh rook repo from data/rook folder, we would need to update the templates in [ocs-ci ](https://github.com/red-hat-storage/ocs-ci/tree/master/ocs_ci/templates).

Changed yamls:
common.yaml
filesystem.yaml
cluster.yaml/cluster-on-pvc.yaml 

Due to the old templates, yesterday a few people hit the following BZ (pvc creations failed as an impact):

https://bugzilla.redhat.com/show_bug.cgi?id=1746081

**Comment by nehaberry** [comment]
@petr-balogh correct me if I am wrong. But PR #585 is already merged. So are we still using the old template method for deployment ? I cam to know from Madhu that our common.yaml was not updated, hence the issue. So I assumed we need template updation.

Please suggest

**Comment by petr-balogh** [comment]
@nehaberry I provided this functionality in PR #585 for other guys to use some files from rook repository if need but as we are on the way to move the deployment using operator I didn't put the effort to change the code to change everything in the deployment as we are moving to the deployment via operator in #640 . So we will need to update the templates accordingly to latest changes as it will take some time till we will have DS operator for DS deployment and maybe it will take also some time till #640 get's merged as the operator is broken from Monday.

**Comment by nehaberry** [comment]
> @nehaberry I provided this functionality in PR #585 for other guys to use some files from rook repository if need but as we are on the way to move the deployment using operator I didn't put the effort to change the code to change everything in the deployment as we are moving to the deployment via operator in #640 . So we will need to update the templates accordingly to latest changes as it will take some time till we will have DS operator for DS deployment and maybe it will take also some time till #640 get's merged as the operator is broken from Monday.

Thanks a lot @petr-balogh  for the clarifications.

**Comment by ebenahar** [comment]
@shreekarSS @nehaberry are all the yamls mentioned in the [first comment](https://github.com/red-hat-storage/ocs-ci/issues/661#issue-486184116) updated in https://github.com/red-hat-storage/ocs-ci/pull/665?

**Comment by vavuthu** [comment]
@nehaberry I see you have mentioned "filesystem.yaml" and "cluster.yaml/cluster-on-pvc.yaml" requires changes.

From the PR https://github.com/rook/rook/pull/3642/ , I didn't see any chnages for above mentioned files.

Could you clarify

**Comment by vavuthu** [comment]
PR #665 merged
