### ISSUE TITLE
get_fio_results fails with E    AttributeError: 'NoneType' object has no attribute 'running'

### ISSUE THREAD

**Issue by shreekarSS** [red-hat-storage/ocs-ci#662]
While collecting IO results:
08:27:38 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-75977162eddf46cd8a3fae3f9f60611d
08:28:11 - MainThread - root - INFO - IOPs after FIO:
08:28:11 - MainThread - root - INFO - Read: 316.195587
08:28:11 - MainThread - root - INFO - Write: 104.826345
08:28:11 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-7f06047826b945f1880af9ae80ffd841
08:28:38 - MainThread - root - INFO - IOPs after FIO:
08:28:38 - MainThread - root - INFO - Read: 443.677816
08:28:38 - MainThread - root - INFO - Write: 147.742613
08:28:38 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-163ad725bf6f43429f5bc99caa4e994c
08:28:38 - MainThread - root - INFO - IOPs after FIO:
08:28:38 - MainThread - root - INFO - Read: 335.977469
08:28:38 - MainThread - root - INFO - Write: 111.586982
08:28:38 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-ad545ff3328e4045b2b940d1850b4377
08:28:39 - MainThread - root - INFO - IOPs after FIO:
08:28:39 - MainThread - root - INFO - Read: 452.220278
08:28:39 - MainThread - root - INFO - Write: 150.745647
08:28:39 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-50c014ceec9a4e3a9bc20b698a97c673
08:28:42 - MainThread - root - INFO - IOPs after FIO:
08:28:42 - MainThread - root - INFO - Read: 509.840847
08:28:42 - MainThread - root - INFO - Write: 170.219148
08:28:42 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-cfd5436e0bb3452c937c4312775a8840
08:28:42 - MainThread - root - INFO - IOPs after FIO:
08:28:42 - MainThread - root - INFO - Read: 372.02986
08:28:42 - MainThread - root - INFO - Write: 123.521178
08:28:42 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-3bfb78722b6045a9b5cf64563497f44d
08:28:42 - MainThread - root - INFO - IOPs after FIO:
08:28:42 - MainThread - root - INFO - Read: 468.999417
08:28:42 - MainThread - root - INFO - Write: 156.277597
08:28:42 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-eef641868d0c4e03b194ed5735fd9198
08:28:42 - MainThread - root - INFO - IOPs after FIO:
08:28:42 - MainThread - root - INFO - Read: 505.916075
08:28:42 - MainThread - root - INFO - Write: 168.916442
08:28:42 - MainThread - root - INFO - Waiting for IO results from pod pod-test-rbd-0e115b0bf8dc4a9399438043f7a6d34c
08:28:42 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found Exception: 'NoneType' object has no attribute 'running'
Traceback (most recent call last):
  File "/root/shreekar/ocs-ci/ocs_ci/ocs/resources/pod.py", line 113, in get_fio_results
    elif self.fio_thread.running():
AttributeError: 'NoneType' object has no attribute 'running'
FAILED

**Comment by shreekarSS** [comment]
@RazTamir can u have look?

**Comment by RazTamir** [comment]
@shreekarSS , could you please share more info?
which test is failing with link please.
It seems like this pod obj doesn't have 'fio_thread' initiated.  Could you please share the code that failed?

**Comment by shreekarSS** [comment]
@RazTamir prob was with list slicing, so one pod was missed run_io, so pod did not have fio_thread . Closing this issue. Thanks
