### ISSUE TITLE
PV encryption tests via UI does not skip for ODF > 4.8

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#6626]
According to the test https://github.com/red-hat-storage/ocs-ci/blob/master/tests/ui/test_pv_encryption_ui.py, the test is expected to be skipped for ODF > 4.8.  However the test is run in ODF 4.12 as seen from this run:

ocs-ci results for OCS4-12-Downstream-OCP4-12-VSPHERE6-UPI-KMS-VAULT-V1-1AZ-RHCOS-VSAN-3M-3W-tier1 (BUILD ID: 4.12.0-91 RUN ID: 1668107034)

**Comment by ebenahar** [comment]
@am-agrawa @OdedViner could you please take a look?
