### ISSUE TITLE
MCG test fails due to invalid command option `--full_permission`

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#6653]
Test:
```
FAILED tests/manage/mcg/test_nsfs.py::TestNSFSObjectIntegrity::test_nsfs_object_integrity[CLI-25Gi]
FAILED tests/manage/mcg/test_nsfs.py::TestNSFSObjectIntegrity::test_nsfs_object_integrity[OC-20Gi-Export]
```

Error:
```
19:38:01 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: /opt/app-root/src/ocs-ci/data/mcg-cli account create nsfs-integrity-test-54 --full_permission=True --default_resource nsfs-ns-store-59cfb0c398e34f29b9992377f6 --uid 5678 --gid 1234 --new_buckets_path / --nsfs_only=False --nsfs_account_config=True -n openshift-storage
19:38:01 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: Error: unknown flag: --full_permission
See 'noobaa account create --help' for usage.

```

**Comment by abdulkandathil** [comment]
Not sure what got changed, now these tests are failing with below error.

```
time="2022-12-05T17:38:20Z" level=info msg="❌ Invalid: NooBaaAccount \"nsfs-integrity-test-59False\": NooBaaAccount.noobaa.io \"nsfs-integrity-test-59False\" is invalid: metadata.name: Invalid value: \"nsfs-integrity-test-59False\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n"
time="2022-12-05T17:38:20Z" level=fatal msg="❌ Could not create noobaaAccount \"nsfs-integrity-test-59False\" in Namespace \"openshift-storage\" (conflict)"
```

**Comment by petr-balogh** [comment]
This looks like there is the boolean value exposed in the name of the noobaaAccount from some reason: `nsfs-integrity-test-59False` and it complains about it has to be lowercase. So the boolean value should not be propagated here most likely - or if it should it has to be changed to lowercase.

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6289/256499/256595/256596/log
Run ID: 1668069131
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-91
OCP Version: 4.12
Job name: AWS IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6029/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-060ai3c33-t1/j-060ai3c33-t1_20221110T073408/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/mcg-cli account create nsfs-integrity-test-45 --full_permission=True --default_resource nsfs-ns-store-374a22e8282948c794e5807130 --uid 5678 --gid 1234 --new_buckets_path / --nsfs_only=False --nsfs_account_config=True -n openshift-storage.```

**Comment by abdulkandathil** [comment]
@keesturam Currently this test is failing due permission error to `/nsfs` path.

```
13:09:45 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage rsh deployment-nsfs-interface-2e07af2be8a546-85c6fd67f6-lp582 chmod -R 777 /nsfs
13:09:45 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: chmod: changing permissions of '/nsfs': Permission denied
chmod: cannot read directory '/nsfs': Permission denied
command terminated with exit code 1
```

**Comment by abdulkandathil** [comment]
Created new issue https://github.com/red-hat-storage/ocs-ci/issues/6826
