### ISSUE TITLE
ocs-storagecluster-cephfs not found running the tests on SNO

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#6670]
The following error is thrown repeatedly to STDOUT while running tests:
12:12:33 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: Error from server (NotFound): storageclasses.storage.k8s.io "ocs-storagecluster-cephfs" not found

12:12:33 - MainThread - ocs_ci.ocs.ocp - WARNING  - Failed to get resource: ocs-storagecluster-cephfs of kind: storageclass, selector: None, Error: Error during execution of command: oc get storageclass ocs-storagecluster-cephfs -o yaml.
Error is Error from server (NotFound): storageclasses.storage.k8s.io "ocs-storagecluster-cephfs" not found

12:12:33 - MainThread - ocs_ci.ocs.ocp - WARNING  - Number of attempts to get resource reached!
12:12:33 - MainThread - ocs_ci.utility.utils - ERROR  - Exception raised during iteration: Error during execution of command: oc get storageclass ocs-storagecluster-cephfs -o yaml.
Error is Error from server (NotFound): storageclasses.storage.k8s.io "ocs-storagecluster-cephfs" not found
Traceback (most recent call last):
  File "/home/kni/ocs-ci/ocs_ci/utility/utils.py", line 1174, in __iter__
    yield self.func(*self.func_args, **self.func_kwargs)
  File "/home/kni/ocs-ci/ocs_ci/ocs/ocp.py", line 270, in get
    return self.exec_oc_cmd(command, silent=silent)
  File "/home/kni/ocs-ci/ocs_ci/ocs/ocp.py", line 163, in exec_oc_cmd
    out = run_cmd(
  File "/home/kni/ocs-ci/ocs_ci/utility/utils.py", line 473, in run_cmd
    completed_process = exec_cmd(
  File "/home/kni/ocs-ci/ocs_ci/utility/utils.py", line 636, in exec_cmd
    raise CommandFailed(
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc get storageclass ocs-storagecluster-cephfs -o yaml.
Error is Error from server (NotFound): storageclasses.storage.k8s.io "ocs-storagecluster-cephfs" not found

**Comment by achuzhoy** [comment]
The executed command:

run-ci tests/ \
-m "acceptance" \
--html logs/report.html \
--self-contained-html \
--cluster-path "/home/kni/ocs-ci/cluster/" \
--cluster-name "spk-factory-0" \
--ocs-version "4.10" \
--ocp-version "4.10" \
--collect-logs \
--collect-logs-on-success-run \
--junit-xml logs/junit.xml \
--ocsci-conf=ocs_ci/framework/conf/default_config.yaml \
--ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml \
--ocsci-conf=conf/ocsci/mcg_only_deployment.yaml \
--ocsci-conf=conf/custom.yaml 2>&1 |tee -a "logs/test_odf_output.log"

**Comment by achuzhoy** [comment]
OCP version: 4.10.42
mcg-operator.v4.10.8
ocs-operator.v4.10.8
odf-csi-addons-operator.v4.10.8
odf-lvm-operator.v4.10.8
odf-operator.v4.10.8

**Comment by achuzhoy** [comment]
cc @ebenahar @petr-balogh

**Comment by petr-balogh** [comment]
@achuzhoy I know that @shyRozen was involved in SNO, and I know we have for now this production configuration file:
https://github.com/red-hat-storage/ocs-ci/blob/39aab8f3401b5f82257824167aecf5b7315c782d/conf/deployment/vsphere/upi_1az_rhcos_vsan_1mw.yaml

Only on vSphere where I see only 1 MW is defined and we have the `sno: true` .

Not sure if there are some checks changed based on if this value is set to true. @shyRozen might know more.

I will DM Shay with request to take a look here.

**Comment by petr-balogh** [comment]
I had some discussion with Shay, and the SNO deployment is supported only with LVMO. The config file I pointed out in previous comment. So looks like you are also mixing some completely different configuration files:
--ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml \
--ocsci-conf=conf/ocsci/mcg_only_deployment.yaml \

And talking about SNO.

The ODF was never supported on SNO deployment, so can you please clarify what you are trying to achieve here?

**Comment by flaper87** [comment]
@petr-balogh hi :) thanks for getting back to us on this. Let me summarize what we are doing (which is aligned to what you are suggesting):

- We are deploying LVMO
- Then deploy ODF with MCG/Noobaa
- This is on a SNO cluster

Is there any information we can gather to help debug this issue? Any hint that could help us understand whether this is our doing? or whether there's something else happening? :smile:

**Comment by ebenahar** [comment]
H @flaper87 ODF deployment on SNO is supported with LVMO only. 
It's unclear what you are trying to achieve and what it means to deploy LVMO and then ODF.
