### ISSUE TITLE
Update setup.py with modules supporting m1 chips

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#6680]
"gevent==20.9.0" does not support arm64 arch and can not be installed on Macbooks with m1 chip. Requires update to newest ver
"greenlet<1.0.0" does not support arm64 arch and can not be installed on Macbooks with m1 chip. Requires update to newest ver

**Comment by AviadP** [comment]
Hi Daniel, its working fine on my m1 machine,
with `gevent==20.9.0` and `greenlet==0.4.17`

**Comment by DanielOsypenko** [comment]
Issue fixed
