### ISSUE TITLE
OCS-CI is searching for wrong resource names while running on an external mode environment

### ISSUE THREAD

**Issue by tyichye19** [red-hat-storage/ocs-ci#6696]
**Setup**:
* RedHat ODF installed on a cluster with IBM FlashSystem StorageSystem (as a result, the CEPH StorageSystem created automatically)
* Running OCS-CI with flag external_mode=true (as we running on IBM FlashSystem)

**Problem**:
Multiple tests failed due to searching for resource names with an `external` prefix in their names, while on the cluster these objects exist but without the `external` prefix. See [BZ ticket 2103664](https://bugzilla.redhat.com/show_bug.cgi?id=2103664) opened for RedHat ODF developers team to verify it is expected behavior. 

**Example**:
* Test case: `tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node`
* Test failure: `ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc get storageclass ocs-external-storagecluster-ceph-rbd -o yaml.  Error is Error from server (NotFound): storageclasses.storage.k8s.io "ocs-external-storagecluster-ceph-rbd" not found`
* Object exist on cluster without `external` prefix: 
`[root@ocp-installer ~]# oc get storageclass ocs-storagecluster-ceph-rbd`
`ocs-storagecluster-ceph-rbd        openshift-storage.rbd.csi.ceph.com         Delete          Immediate           true                   22h`

**Comment by ebenahar** [comment]
Hi @tyichye19 is this still relevant following our meeting last week?

**Comment by tyichye19** [comment]
Hi @ebenahar, this issue can be closed as we concluded we should run the tests with `external_mode=false`, as we are installed in combine mode as you said.
Thanks.
