### ISSUE TITLE
Tests tests.ui.test_pvc_ui.TestPvcUserInterface are failed with memory allocation error

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#6705]
Tests in [tests.ui.test_pvc_ui.TestPvcUserInterface](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/6576/270445/270712) are failing with the following error:

```
Message: failed on setup with "OSError: [Errno 12] Cannot allocate memory"
Type: None
```

Test run: ocs-ci results for OCS4-11-Downstream-OCP4-12-AZURE-IPI-3AZ-RHCOS-3M-3W-tier1-or-tier_after_upgrade-post-upgrade (RUN ID: 1669323050)

**Comment by am-agrawa** [comment]
@rachael-george I don't think it's an ui automation issue. The test failed at setup, caused by some other test for that run. Probably bcz of multi-threading we use in ocs-ci. WDYT?

**Comment by am-agrawa** [comment]
This issue is no longer seen. Feel free to re-open if you think otherwise.
