### ISSUE TITLE
test_unidirectional_bucket_object_change_replication failed with failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#6738]
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7364/320363/320416/320420/log
Run ID: 1670509372
Test Case: test_unidirectional_bucket_object_change_replication
ODF Build: 4.12.0-130
OCP Version: 4.12
Job name: IBM Cloud IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6343/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-005ici3c33-t1/j-005ici3c33-t1_20221208T130227/logs/

Failure Details:
```
Message: failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"
Type: None

Text:
def uls_cleanup():
        for cloud, uls_set in all_created_uls.items():
            client = ulsMap.get(cloud)
            if len(uls_set) == 0 or client is None:
                continue
            all_existing_uls = client.get_all_uls_names()
            for uls in uls_set:
                if uls in all_existing_uls:
                    log.info(f"Cleaning up uls {uls}")
>                   client.delete_uls(uls)

ocs_ci/ocs/resources/cloud_uls.py:115: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/ocs/resources/cloud_manager.py:129: in delete_uls
    self.internal_delete_uls(name)
ocs_ci/ocs/resources/cloud_manager.py:414: in internal_delete_uls
    bucket.delete_blobs(bucket.list_blobs())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Bucket: gcp-uls-ed3b02b8b77a4eb297c659930fb89097>
blobs = <google.api_core.page_iterator.HTTPIterator object at 0x7f920d6eac70>
on_error = None, client = None, preserve_generation = False, timeout = 60
if_generation_match = None, if_generation_not_match = None
if_metageneration_match = None, if_metageneration_not_match = None
retry = <google.cloud.storage.retry.ConditionalRetryPolicy object at 0x7f91e6b4feb0>

    def delete_blobs(
        self,
        blobs,
        on_error=None,
        client=None,
        preserve_generation=False,
        timeout=_DEFAULT_TIMEOUT,
        if_generation_match=None,
        if_generation_not_match=None,
        if_metageneration_match=None,
        if_metageneration_not_match=None,
        retry=DEFAULT_RETRY_IF_GENERATION_SPECIFIED,
    ):
        """Deletes a list of blobs from the current bucket.
    
        Uses :meth:`delete_blob` to delete each individual blob.
    
        By default, any generation information in the list of blobs is ignored, and the
        live versions of all blobs are deleted. Set `preserve_generation` to True
        if blob generation should instead be propagated from the list of blobs.
    
        If :attr:`user_project` is set, bills the API request to that project.
    
        :type blobs: list
        :param blobs: A list of :class:`~google.cloud.storage.blob.Blob`-s or
                      blob names to delete.
    
        :type on_error: callable
        :param on_error: (Optional) Takes single argument: ``blob``.
                         Called once for each blob raising
                         :class:`~google.cloud.exceptions.NotFound`;
                         otherwise, the exception is propagated.
    
        :type client: :class:`~google.cloud.storage.client.Client`
        :param client: (Optional) The client to use.  If not passed, falls back
                       to the ``client`` stored on the current bucket.
    
        :type preserve_generation: bool
        :param preserve_generation: (Optional) Deletes only the generation specified on the blob object,
                                    instead of the live version, if set to True. Only :class:~google.cloud.storage.blob.Blob
                                    objects can have their generation set in this way.
                                    Default: False.
    
        :type if_generation_match: list of long
        :param if_generation_match:
            (Optional) See :ref:`using-if-generation-match`
            Note that the length of the list must match the length of
            The list must match ``blobs`` item-to-item.
    
        :type if_generation_not_match: list of long
        :param if_generation_not_match:
            (Optional) See :ref:`using-if-generation-not-match`
            The list must match ``blobs`` item-to-item.
    
        :type if_metageneration_match: list of long
        :param if_metageneration_match:
            (Optional) See :ref:`using-if-metageneration-match`
            The list must match ``blobs`` item-to-item.
    
        :type if_metageneration_not_match: list of long
        :param if_metageneration_not_match:
            (Optional) See :ref:`using-if-metageneration-not-match`
            The list must match ``blobs`` item-to-item.
    
        :type timeout: float or tuple
        :param timeout:
            (Optional) The amount of time, in seconds, to wait
            for the server response.  See: :ref:`configuring_timeouts`
    
        :type retry: google.api_core.retry.Retry or google.cloud.storage.retry.ConditionalRetryPolicy
        :param retry:
            (Optional) How to retry the RPC. See: :ref:`configuring_retries`
    
        :raises: :class:`~google.cloud.exceptions.NotFound` (if
                 `on_error` is not passed).
        """
        _raise_if_len_differs(
>           len(blobs),
            if_generation_match=if_generation_match,
            if_generation_not_match=if_generation_not_match,
            if_metageneration_match=if_metageneration_match,
            if_metageneration_not_match=if_metageneration_not_match,
        )
E       TypeError: object of type 'HTTPIterator' has no len()

venv/lib64/python3.8/site-packages/google/cloud/storage/bucket.py:1735: TypeError

```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7015/292448/292491/292494/log
Run ID: 1670007275
Test Case: test_unidirectional_bucket_object_change_replication
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: AZURE IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6280/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-004zi3c33-uba/j-004zi3c33-uba_20221202T083924/logs/
Error Message: ```failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6998/291593/291640/291646/log
Run ID: 1669980540
Test Case: test_unidirectional_bucketclass_replication
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier2
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6270/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-003bu1cni30-t2/j-003bu1cni30-t2_20221202T102339/logs/
Error Message: ```failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6976/290813/290865/290871/log
Run ID: 1669952976
Test Case: test_unidirectional_bucket_object_change_replication
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI ENCRYPTION 1AZ RHCOS VSAN LSO VMDK 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6273/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-003vue1cslv33-uba/j-003vue1cslv33-uba_20221201T230828/logs/
Error Message: ```failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6959/290051/290105/290109/log
Run ID: 1669936593
Test Case: test_unidirectional_bucket_object_change_replication
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: RHV IPI 1AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6267/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-011ri1c33-t1/j-011ri1c33-t1_20221201T222122/logs/
Error Message: ```failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6949/289361/289413/289419/log
Run ID: 1669941053
Test Case: test_unidirectional_bucket_object_change_replication
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI KMS VAULT V1 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6276/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-078vukv11cs33-t1/j-078vukv11cs33-t1_20221201T233022/logs/
Error Message: ```failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6942/289052/289099/289104/log
Run ID: 1669937787
Test Case: test_unidirectional_bucket_object_change_replication
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6269/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-016bu1cni30-t1/j-016bu1cni30-t1_20221201T223415/logs/
Error Message: ```failed on teardown with "TypeError: object of type 'HTTPIterator' has no len()"```

**Comment by sagihirshfeld** [comment]
These failed test cases are covered in #6837
