### ISSUE TITLE
test_nsfs_object_integrity failed with ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-d3f153ab967643-85797d6db8-qtwk7 chmod -R 777 /nsfs.

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#6741]
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7364/320363/320460/320461/log
Run ID: 1670509372
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-130
OCP Version: 4.12
Job name: IBM Cloud IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6343/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-005ici3c33-t1/j-005ici3c33-t1_20221208T130227/logs/

Failure Details:
```
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-d3f153ab967643-85797d6db8-qtwk7 chmod -R 777 /nsfs.
Error is chmod: changing permissions of '/nsfs': Permission denied
chmod: cannot read directory '/nsfs': Permission denied
command terminated with exit code 1
Type: None

Text:
self = <tests.manage.mcg.test_nsfs.TestNSFSObjectIntegrity object at 0x7f91e19b2970>
nsfs_bucket_factory = <function nsfs_bucket_factory_fixture.<locals>.nsfs_bucket_factory_implementation at 0x7f91e5565430>
awscli_pod_session = <ocs_ci.ocs.resources.pod.Pod object at 0x7f91e61dca30>
test_directory_setup = SetupDirs(origin_dir='test_nsfs_object_integrity[OC-20Gi-Export]/origin', result_dir='test_nsfs_object_integrity[OC-20Gi-Export]/result')
nsfs_obj = NSFS(method='OC', pvc_name=None, pvc_size=20, sub_path=None, fs_backend=None, mount_existing_dir=True, existing_dir_mo...ted_bucket_path=None, s3_creds=None, nss=<ocs_ci.ocs.resources.namespacestore.NamespaceStore object at 0x7f91e29b80d0>)

    @pytest.mark.polarion_id("OCS-3735")
    @pytest.mark.parametrize(
        argnames="nsfs_obj",
        argvalues=[
            pytest.param(
                NSFS(
                    method="CLI",
                    pvc_size=25,
                ),
                marks=[tier1],
            ),
            pytest.param(
                NSFS(
                    method="OC",
                    pvc_size=20,
                    mount_existing_dir=True,
                ),
                marks=[tier1],
            ),
        ],
        ids=[
            "CLI-25Gi",
            "OC-20Gi-Export",
        ],
    )
    def test_nsfs_object_integrity(
        self, nsfs_bucket_factory, awscli_pod_session, test_directory_setup, nsfs_obj
    ):
        """
        Test NSFS object integrity -
        1. Write to the NSFS bucket
        2. Read the objects back
        3. Compare their checksums
        4. Also compare the checksums of the files that reside on the filesystem
    
        """
>       nsfs_bucket_factory(nsfs_obj)

tests/manage/mcg/test_nsfs.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:5274: in nsfs_bucket_factory_implementation
    nsfs_interface_pod.exec_cmd_on_pod(f"chmod -R 777 {nsfs_obj.mount_path}")
ocs_ci/ocs/resources/pod.py:175: in exec_cmd_on_pod
    return self.ocp.exec_oc_cmd(
ocs_ci/ocs/ocp.py:163: in exec_oc_cmd
    out = run_cmd(
ocs_ci/utility/utils.py:474: in run_cmd
    completed_process = exec_cmd(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cmd = ['oc', '-n', 'openshift-storage', 'rsh', 'deployment-nsfs-interface-d3f153ab967643-85797d6db8-qtwk7', 'chmod', ...]
secrets = None, timeout = 600, ignore_error = False, threading_lock = None
silent = False, kwargs = {}
masked_cmd = 'oc -n openshift-storage rsh deployment-nsfs-interface-d3f153ab967643-85797d6db8-qtwk7 chmod -R 777 /nsfs'
completed_process = CompletedProcess(args=['oc', '-n', 'openshift-storage', 'rsh', 'deployment-nsfs-interface-d3f153ab967643-85797d6db8-qt...s': Permission denied\nchmod: cannot read directory '/nsfs': Permission denied\ncommand terminated with exit code 1\n")
masked_stdout = ''
masked_stderr = "chmod: changing permissions of '/nsfs': Permission denied\nchmod: cannot read directory '/nsfs': Permission denied\ncommand terminated with exit code 1\n"

    def exec_cmd(
        cmd,
        secrets=None,
        timeout=600,
        ignore_error=False,
        threading_lock=None,
        silent=False,
        **kwargs,
    ):
        """
        Run an arbitrary command locally
    
        If the command is grep and matching pattern is not found, then this function
        returns "command terminated with exit code 1" in stderr.
    
        Args:
            cmd (str): command to run
            secrets (list): A list of secrets to be masked with asterisks
                This kwarg is popped in order to not interfere with
                subprocess.run(``**kwargs``)
            timeout (int): Timeout for the command, defaults to 600 seconds.
            ignore_error (bool): True if ignore non zero return code and do not
                raise the exception.
            threading_lock (threading.Lock): threading.Lock object that is used
                for handling concurrent oc commands
            silent (bool): If True will silent errors from the server, default false
    
        Raises:
            CommandFailed: In case the command execution fails
    
        Returns:
            (CompletedProcess) A CompletedProcess object of the command that was executed
            CompletedProcess attributes:
            args: The list or str args passed to run().
            returncode (str): The exit code of the process, negative for signals.
            stdout     (str): The standard output (None if not captured).
            stderr     (str): The standard error (None if not captured).
    
        """
        masked_cmd = mask_secrets(cmd, secrets)
        log.info(f"Executing command: {masked_cmd}")
        if isinstance(cmd, str):
            cmd = shlex.split(cmd)
        if threading_lock and cmd[0] == "oc":
            threading_lock.acquire()
        completed_process = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            timeout=timeout,
            **kwargs,
        )
        if threading_lock and cmd[0] == "oc":
            threading_lock.release()
        masked_stdout = mask_secrets(completed_process.stdout.decode(), secrets)
        if len(completed_process.stdout) > 0:
            log.debug(f"Command stdout: {masked_stdout}")
        else:
            log.debug("Command stdout is empty")
    
        masked_stderr = mask_secrets(completed_process.stderr.decode(), secrets)
        if len(completed_process.stderr) > 0:
            if not silent:
                log.warning(f"Command stderr: {masked_stderr}")
        else:
            log.debug("Command stderr is empty")
        log.debug(f"Command return code: {completed_process.returncode}")
        if completed_process.returncode and not ignore_error:
            if (
                "grep" in masked_cmd
                and b"command terminated with exit code 1" in completed_process.stderr
            ):
                log.info(f"No results found for grep command: {masked_cmd}")
            else:
>               raise CommandFailed(
                    f"Error during execution of command: {masked_cmd}."
                    f"\nError is {masked_stderr}"
                )
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-d3f153ab967643-85797d6db8-qtwk7 chmod -R 777 /nsfs.
E               Error is chmod: changing permissions of '/nsfs': Permission denied
E               chmod: cannot read directory '/nsfs': Permission denied
E               command terminated with exit code 1

ocs_ci/utility/utils.py:637: CommandFailed

```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7100/296186/296241/296242/log
Run ID: 1670263326
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: AWS UPI Disconnected 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6300/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-066aud3c33-ua/j-066aud3c33-ua_20221205T121524/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-1d01783638294d-67cf46bb6d-cs4c6 chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6959/290051/290149/290150/log
Run ID: 1669936593
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: RHV IPI 1AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6267/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-011ri1c33-t1/j-011ri1c33-t1_20221201T222122/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-f06628818e264a-85b5d984b4-fdkz6 chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6949/289361/289459/289460/log
Run ID: 1669941053
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI KMS VAULT V1 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6276/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-078vukv11cs33-t1/j-078vukv11cs33-t1_20221201T233022/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-07a01839b8ff48-7848ff4bf6-92hv4 chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6942/289052/289143/289144/log
Run ID: 1669937787
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6269/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-016bu1cni30-t1/j-016bu1cni30-t1_20221201T223415/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-f026d48bd64947-54c96d656b-rhlz5 chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6790/280850/280946/280948/log
Run ID: 1669734217
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-120
OCP Version: 4.13
Job name: AWS IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6183/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-157ai3c33-uo/j-157ai3c33-uo_20221129T063027/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-a19f63be0ee34a-5758cb44d7-d2t7j chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6782/280211/280308/280309/log
Run ID: 1669734250
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-120
OCP Version: 4.13
Job name: AZURE IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6204/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-164zi3c33-uo/j-164zi3c33-uo_20221129T092725/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-be1cc5471a754b-7444f4d987-44wdt chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6773/279533/279629/279631/log
Run ID: 1669717720
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI ENCRYPTION 1AZ RHCOS VSAN LSO VMDK 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6203/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-092vue1cslv33-t1/j-092vue1cslv33-t1_20221129T092854/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-d1b2d0f4b5ba4d-5cfcb8666-xdhqd chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6756/278740/278836/278838/log
Run ID: 1669694775
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: AWS IPI 3AZ RHCOS 3M 3W 3I tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6188/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-212ai3c333-t1/j-212ai3c333-t1_20221129T030853/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-4dc39bfa3d9b46-799c7f559c-2x96d chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6753/278441/278537/278539/log
Run ID: 1669701100
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS EXTERNAL 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6192/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-173vu1ce33-t1/j-173vu1ce33-t1_20221129T045757/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-26813822fff34b-56b96f5d49-9c4p2 chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6551/269495/269539/269540/log
Run ID: 1669297981
Test Case: test_nsfs_object_integrity_with_wrong_permissions
ODF Build: 4.12.0-116
OCP Version: 4.12
Job name: VSPHERE6 UPI Disconnected 1AZ RHCOS VSAN 3M 3W tier3
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6122/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vud1cs33-t3/j-001vud1cs33-t3_20221124T120321/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-6d5d25015ab740-6b69d76f4b-mlmvr chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6539/268961/269016/269017/log
Run ID: 1669152584
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-114
OCP Version: 4.12
Job name: VSPHERE6 UPI Disconnected 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6117/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vud1cs33-t1/j-001vud1cs33-t1_20221122T193952/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-8187ffb2cfe640-594cbc48b7-57w6d chmod -R 777 /nsfs.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6289/256499/256595/256596/log
Run ID: 1668069131
Test Case: test_nsfs_object_integrity
ODF Build: 4.12.0-91
OCP Version: 4.12
Job name: AWS IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6029/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-060ai3c33-t1/j-060ai3c33-t1_20221110T073408/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/mcg-cli account create nsfs-integrity-test-45 --full_permission=True --default_resource nsfs-ns-store-374a22e8282948c794e5807130 --uid 5678 --gid 1234 --new_buckets_path / --nsfs_only=False --nsfs_account_config=True -n openshift-storage.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6269/254781/254829/254830/log
Run ID: 1668071897
Test Case: test_nsfs_object_integrity_with_wrong_permissions
ODF Build: 4.12.0-91
OCP Version: 4.12
Job name: VSPHERE6 IPI 1AZ RHCOS VSAN 3M 3W tier3
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6026/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-036vi1cs33-t3/j-036vi1cs33-t3_20221110T073434/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-26f9ba6fdf8240-d9997bff9-5nztr chmod -R 777 /nsfs.```

**Comment by sagihirshfeld** [comment]
The underlying issues have been classified into the following:
- #6601 (PR fix)
- #6826
- #6834
