### ISSUE TITLE
Provide a way to consume openshift SVT project

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#676]
openshift svt is a Performance, Scalability and Capacity project for openshift that ocs-ci can leverage from. 
link to the repo: https://github.com/openshift/svt

For eg., to load openshift-logging with a lot of pods that generate logs, we could simply run ```python cluster-loader.py --kubeconfig=<path_to_kubeconfig> -f config/ocp-logtest.yaml``` to get the job done. 

Raising this issue to provide a way for ocs-ci to call and make use of SVT project.

**Comment by keesturam** [comment]
@vikasmulaje has implemented this in https://github.com/red-hat-storage/ocs-ci/pull/1298

**Comment by PrasadDesala** [comment]
#1298 is already merged, Closing this issue.
