### ISSUE TITLE
test_bucket_creation failed with failed on teardown with "KeyError: 'volumeName'"

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#6766]
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6633/272793/272796/272801/log
Run ID: 1669598191
Test Case: test_bucket_creation
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS MCG Only Deployment 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6146/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-005vu1rmcg33-t1/j-005vu1rmcg33-t1_20221128T003211/logs/

Failure Details:
```
Message: failed on teardown with "KeyError: 'volumeName'"
Type: None

Text:
def backingstore_cleanup():
        for backingstore in created_backingstores:
            try:
>               backingstore.delete()

ocs_ci/ocs/resources/backingstore.py:366: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.ocs.resources.backingstore.BackingStore object at 0x7f4d480377c0>
retry = True

    def delete(self, retry=True):
        """
        Deletes the current backingstore by using OC/CLI commands
    
        Args:
            retry (bool): Whether to retry the deletion if it fails
    
        """
        log.info(f"Cleaning up backingstore {self.name}")
        # If the backingstore utilizes a PV, save its PV name for deletion verification
        if self.type == "pv":
            try:
                backingstore_pvc = OCP(
                    kind=constants.PVC,
                    selector=f"pool={self.name}",
                    namespace=config.ENV_DATA["cluster_namespace"],
                ).get()["items"][0]
            except IndexError:
                log.error(
                    f"Could not find the OCP object for {self.name}, proceeding without removal"
                )
                return True
            except Exception as e:
                raise e
>           pv_name = backingstore_pvc["spec"]["volumeName"]
E           KeyError: 'volumeName'

ocs_ci/ocs/resources/backingstore.py:82: KeyError

```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6433/263940/263943/263947/log
Run ID: 1668626119
Test Case: test_bucket_creation
ODF Build: 4.12.0-113
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS MCG Only Deployment 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6085/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-008vu1rmcg33-ua/j-008vu1rmcg33-ua_20221116T143051/logs/
Error Message: ```failed on teardown with "KeyError: 'volumeName'"```

**Comment by sagihirshfeld** [comment]
These failures were fixed in https://github.com/red-hat-storage/ocs-ci/pull/6801
