### ISSUE TITLE
Enable complete debug output from openshift-installer in Jenkins run

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#678]
We currently print just the INFO level in jenkins run which is not helpful in debugging or when filing an issue,  Must-gather was also broken before but along with must-gather we need to print out the full debug output to better understand the failures.

**Comment by clacroix12** [comment]
I believe INFO was chosen for jenkins runs because we were hitting issues with the jenkins console. The log FILES however should be DEBUG already to help with troubleshooting.

**Comment by vasukulkarni** [comment]
I am not sure whether its a Jenkins issue then, I tried to sort by date and check the logs but cannot find the debug logs, link below

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/132/testReport/tests.ecosystem.deployment/test_ocs_basic_install/test_cluster_is_running/

**Comment by vasukulkarni** [comment]
+ broken logs link http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/pr677

**Comment by vasukulkarni** [comment]
@dahorak can you check if rebuild is causing logs to be broken, with new deployment build I can see the debug logs but the above jenkins run (which was rebuild) I dont see them.

**Comment by dahorak** [comment]
Should be fixed for all new builds of PR validation job.
