### ISSUE TITLE
Extend NodesBase.restart_nodes_by_stop_and_start_teardown by BaremetalNodes(NodesBase)

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#6790]
Having: 
![image](https://user-images.githubusercontent.com/61454420/207297160-db9c88e2-91b6-466e-9dba-ba0993d93a48.png)

Assumption: we already have an implementation of the NodesBase.restart_nodes_by_stop_and_start_teardown, having BaremetalNodes.restart_nodes_teardown.

If assumption is correct, rename the method BaremetalNodes.restart_nodes_teardown to NodesBase.restart_nodes_by_stop_and_start_teardown
Else implement BaremetalNodes.restart_nodes_by_stop_and_start_teardown

**Comment by prsurve** [comment]
Failed testcase test_hugepages_post_odf_deployment
