### ISSUE TITLE
Multi-arch image quay.io/ocsci/warp

### ISSUE THREAD

**Issue by tuan-hoang1** [red-hat-storage/ocs-ci#6802]
Quite similar to https://github.com/red-hat-storage/ocs-ci/issues/6791

The test is `tests/e2e/scale/noobaa/test_warp.py`. Above image also does not seem to support multi arch.

**Comment by tuan-hoang1** [comment]
Instead of downloading the pre-built binary in the Dockerfile, we can build from source instead:

```
FROM fedora:36

WORKDIR /home/warp

RUN dnf -y install wget tar xz unzip git golang && \
    dnf clean all && \
    mkdir -p /home/warp && \
    go install github.com/minio/warp@v0.6.2 && \
    cp -f /root/go/bin/warp /home/warp/warp && \
    rm -rf /root/go

CMD ["/bin/bash"]

```

**Comment by PrasadDesala** [comment]
@Akarsha-rai Please take a look

**Comment by prsurve** [comment]
@Akarsha-rai @PrasadDesala let me know if you need help to have multi-arch images

**Comment by tuan-hoang1** [comment]
Confirmed working with above Dockerfile. Tested on s390x.

**Comment by PrasadDesala** [comment]
Thank you, Pratik for creating the multi-arch image.
