### ISSUE TITLE
oc login fails on ibm_cloud

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#6807]
oc login fails on ibm cloud platform. Using `oc login -u apikey -p <pass>` no longer works.

e.g. https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6359/

**Comment by petr-balogh** [comment]
@fbalak this is the IPI IBM Cloud deployment.    Maybe this worked on managed IBM ROKS Cluster.

As this is IPI deployment of OpenShift, here should be used the same method like on other IPI platform like AWS.

Might this be the issue?
