### ISSUE TITLE
Maven compilation fails due to limited internet access in test_s3_upload_with_java

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#6845]
In disconnected and proxy OCP deployments, Maven fails to compile due to limited/no internet access while setting up the JavaSDK pod for the test:

`Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh session-java-s3-3aff179c1cd84d65a38bebc2 mvn clean compile.
Error is command terminated with exit code 1`

RP links:
1. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/7100/296186/296248/296250/log
2. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/7100/296186/296248/296249/log
3. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6805/281880/281989/281990/log
4. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6805/281880/281989/281991/log

**Comment by sagihirshfeld** [comment]
We're still seeing these types of errors in Proxy deployments:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/10823/480200/480306/480307/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/10823/480200/480306/480309/log

**Comment by sagihirshfeld** [comment]
Fixed by https://github.com/red-hat-storage/ocs-ci/pull/8301

**Comment by tiffanyn108** [comment]
Issue is seen on 4.12:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/19509/948107/948195/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/19509/948107/948196/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/19499/947527/947616/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/19499/947527/947617/log

**Comment by sagihirshfeld** [comment]
Closing this since the fix has been backported up to 4.13
