### ISSUE TITLE
Failing to purge bucket with versioning at the teardown of test_versioning_parallel_ops[True]

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#6849]
While the teardown seems to work fine in ODF 4.10 and 4.11, the following error is received when trying to delete the uls bucket via boto3.s3.Bucket(<bucketname>).delete() at ocs-ci/ocs_ci/ocs/resources/objectbucket.py::MCGS3Bucket::internal_delete:

`Message: failed on teardown with "botocore.exceptions.ClientError: An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty. You must delete all versions in the bucket."`

RP links:
1. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6545/269251/269305/269306/log
2. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6898/286901/286978/286980/log
3. https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6998/291593/291665/291666/log

Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2111544
Original PR: https://github.com/red-hat-storage/ocs-ci/pull/6460

**Comment by keesturam** [comment]
@sagihirshfeld do we need an automation fix here? we are going to have this fixed on the product.

**Comment by sagihirshfeld** [comment]
This was encountered recently in 4.13 as well:

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/9550/422479/422551/422552/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DPASSED%252CFAILED%252CSKIPPED%252CINTERRUPTED%26filter.cnt.name%3Dtest_versioning_parallel_ops%26page.page%3D1

**Comment by mashetty330** [comment]
I will work on this issue this week
