### ISSUE TITLE
WA for BZ 1747388 with WARN too few PGs

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#687]
We need to create the WA and once it will be fixed we need to remove this WA. Please don't close this issue till the WA is deleted.

**Comment by mbukatov** [comment]
Upstream references:
* https://github.com/rook/rook/issues/560
* https://github.com/rook/rook/pull/3745
* https://github.com/rook/rook/pull/3769

**Comment by vasukulkarni** [comment]
Can be closed now?

**Comment by petr-balogh** [comment]
yes, I thought it will be closed automatically as I mentioned this issue in PR message.
