### ISSUE TITLE
MCG tests fail to access external resources in Proxy Deployments

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#6924]
Examples:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8214/362303/362386/362394/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8214/362303/362386/362397/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8214/362303/362386/362399/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8214/362303/362402/362404/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6805/281880/281960/281967/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6805/281880/281960/281968/log

**Comment by tiffanyn108** [comment]
Same issue is seen on https://github.com/red-hat-storage/ocs-ci/issues/3338
There is issue with pull S3 region creds during test run.

**Comment by tiffanyn108** [comment]
Closed as duplicated of #3338
