### ISSUE TITLE
Errors in the cluster destroy do not propagate and destroy steps continue after failure

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#6943]
Example: https://url.corp.redhat.com/23aba6e

The cluster destroy command times out and we log the traceback but we don't actually _raise_ the exception so we continue to perform subsequent destroy steps. Those steps generally depend on the cluster being fully destroyed so it doesn't make sense for us to continue on if we receive errors during the cluster destroy. 

The example is from an IBM IPI deployment. Cluster destroy times out and then we continue on in the [destroy logic](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/ibmcloud.py#L181-L185) to clean up other resources created for the deployment (external to the actual cluster).

**Comment by petr-balogh** [comment]
@clacroix12 please, have you already opened OCP bug for it? If so, please link here.

**Comment by clacroix12** [comment]
I reported the destroy timeout issue here: https://url.corp.redhat.com/10025a5
