### ISSUE TITLE
tests/ecosystem/upgrade/test_noobaa.py::test_upgrade_mcg_io is falling after upgrading ODF 4.11.4 to 4.12.0 on IBM-Z. 

### ISSUE THREAD

**Issue by sujoykr1** [red-hat-storage/ocs-ci#6946]
_____________________________ test_upgrade_mcg_io ______________________________

mcg_workload_job = <ocs_ci.ocs.resources.ocs.OCS object at 0x3ff87183e80>

    @post_upgrade
    @skipif_managed_service
    @pytest.mark.polarion_id("OCS-2207")
    @bugzilla("1874243")
    @red_squad
    def test_upgrade_mcg_io(mcg_workload_job):
        """
        Confirm that there is MCG workload job running after upgrade.
        """
>       assert wait_for_active_pods(
            mcg_workload_job, 1
        ), f"Job {mcg_workload_job.name} doesn't have any running pod"
E       AssertionError: Job mcg-workload doesn't have any running pod
E       assert False
E        +  where False = wait_for_active_pods(<ocs_ci.ocs.resources.ocs.OCS object at 0x3ff87183e80>, 1)

tests/ecosystem/upgrade/test_noobaa.py:181: AssertionError

**Comment by sujoykr1** [comment]
Logs attached in the BZ https://bugzilla.redhat.com/show_bug.cgi?id=2162306

**Comment by keesturam** [comment]
@tiffanyn108 can you please take a look at this issue

**Comment by keesturam** [comment]
pls see - https://github.com/red-hat-storage/ocs-ci/issues/7754
