### ISSUE TITLE
In the test "test_noobaa_sts_host_node_failure" with IBM Z, after stopping the noobaa-db node the noobaa-db pod does not reach the Running state

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#6951]
In the test "test_noobaa_sts_host_node_failure" with the IBM Z platform, after stopping the noobaa-db node, the noobaa-db pod rescheduled on a new node but does not reach the Running state.

**Comment by yitzhak12** [comment]
After powering on the worker node, the pods recovered successfully.

**Comment by yitzhak12** [comment]
[test-noobaa-sts-host-node-failure-true-1.log](https://github.com/red-hat-storage/ocs-ci/files/10458328/test-noobaa-sts-host-node-failure-true-1.log)

**Comment by yitzhak12** [comment]
@AaruniAggarwal Are you running the test from the cli? To be sure it's not a timeout issue, can you try changing the line https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/mcg/test_host_node_failure.py#L193: `timeout=800 if noobaa_sts == constants.NOOBAA_DB_STATEFULSET else 60,` to `timeout=1200 if noobaa_sts == constants.NOOBAA_DB_STATEFULSET else 120,` and rerun the test?

**Comment by AaruniAggarwal** [comment]
I made the suggested changes and reran the test case. But test case failed again. Attaching the log file: 
[test-noobaa-sts-host-node-failure-true-120.log](https://github.com/red-hat-storage/ocs-ci/files/10477263/test-noobaa-sts-host-node-failure-true-120.log)

**Comment by yitzhak12** [comment]
Okay, thanks @AaruniAggarwal. 
@sidhant-agrawal Do you have any suggestions regarding the failure above?

**Comment by yitzhak12** [comment]
@ebenahar @keesturam, Is someone from the Red squad can take this issue?
