### ISSUE TITLE
Fail to Bound PVC during timeout after WORKER drained. test_node_maintenance

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#6953]
Test steps:

OCS-1269/OCS-1272:
        - Maintenance (mark as unscheduable and drain) 1 worker/master node
        - Check cluster functionality by **creating resources**
          (pools, storageclasses, PVCs, pods - both CephFS and RBD)
        - Mark the node as scheduable
        - Check cluster and Ceph health

On the step of creating resources the test fails PVC fails to reach status bound causing failure

`2023-01-11 23:23:40  21:23:40 - MainThread - ocs_ci.ocs.ocp - ERROR  - Wait for PersistentVolumeClaim resource pvc-test-58a23346164f4ecf9390d244faa0450 at column STATUS to reach desired condition Bound failed, last actual status was Pending
2023-01-11 23:23:40  21:23:40 - MainThread - ocs_ci.helpers.helpers - ERROR  - PersistentVolumeClaim pvc-test-58a23346164f4ecf9390d244faa0450 failed to reach Bound`

Description of the resource on the time of failure is: 
      2023-01-11 23:23:40  21:23:40 - MainThread - ocs_ci.ocs.ocp - WARNING  - Description of the resource(s) we were waiting for:
      2023-01-11 23:23:40  Name:          pvc-test-58a23346164f4ecf9390d244faa0450
      2023-01-11 23:23:40  Namespace:     namespace-test-40830713a86b43cfa9b4da45b
      2023-01-11 23:23:40  StorageClass:  ocs-storagecluster-cephfs
      2023-01-11 23:23:40  Status:        Pending
      2023-01-11 23:23:40  Volume:        
      2023-01-11 23:23:40  Labels:        <none>
      2023-01-11 23:23:40  Annotations:   volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
      2023-01-11 23:23:40                 volume.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
      2023-01-11 23:23:40  Finalizers:    [kubernetes.io/pvc-protection]
      2023-01-11 23:23:40  Capacity:      
      2023-01-11 23:23:40  Access Modes:  
      2023-01-11 23:23:40  VolumeMode:    Filesystem
      2023-01-11 23:23:40  Used By:       <none>
      2023-01-11 23:23:40  Events:
      2023-01-11 23:23:40    Type    Reason                Age               From                         Message
      2023-01-11 23:23:40    ----    ------                ----              ----                         -------
      2023-01-11 23:23:40    Normal  ExternalProvisioning  6s (x5 over 60s)  **persistentvolume-controller  waiting for a volume to be created, either by external provisioner "openshift-storage.cephfs.csi.ceph.com" or manually created by system administrator**

In the same time must-gather logs state that pvc with name **pvc-test-58a23346164f4ecf9390d244faa0450 has been bound latest 2m20s after creation of the PVC**. 

NAMESPACE                                  NAME                                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
bg-fio-load-6763b                          pvc-test-632f4b61f3504874aac4795c7ab4e5d    Bound    pvc-84af41ea-8221-45f1-8c88-63e6729a6fb9   7Gi        RWO            ocs-storagecluster-ceph-rbd   8h
namespace-test-40830713a86b43cfa9b4da45b   pvc-test-3b55e4a218824042af47a8b3b40d2d2    Bound    pvc-86cae5e2-d721-4a5d-ae3f-7895740b9f7e   3Gi        RWO            ocs-storagecluster-ceph-rbd   2m41s
**namespace-test-40830713a86b43cfa9b4da45b   pvc-test-58a23346164f4ecf9390d244faa0450    Bound    pvc-495e1572-49d1-4b2f-9fe9-ba93cc59fe69   3Gi        RWO            ocs-storagecluster-cephfs**     **2m20s**
...

See [/ocsci-jenkins/openshift-clusters/j-253vuf1cs33-t1/j-253vuf1cs33-t1_20230111T115745/logs/failed_testcase_ocs_logs_1673441794/test_node_maintenance[worker]_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-1d2e3b562c65a633844855c65f0017e18d735d22ef3fbd51ff6fbb258ff23497/namespaces/all/pvc_all_namespaces](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-253vuf1cs33-t1/j-253vuf1cs33-t1_20230111T115745/logs/failed_testcase_ocs_logs_1673441794/test_node_maintenance%5bworker%5d_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-1d2e3b562c65a633844855c65f0017e18d735d22ef3fbd51ff6fbb258ff23497/namespaces/all/pvc_all_namespaces)

Full must-gather log: [link](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-253vuf1cs33-t1/j-253vuf1cs33-t1_20230111T115745/logs/failed_testcase_ocs_logs_1673441794/test_node_maintenance%5bworker%5d_ocs_logs/ocs_must_gather/)

Report portal: [OCS4-12-Downstream-OCP4-12-VSPHERE6-UPI-FIPS-1AZ-RHCOS-VSAN-3M-3W-tier1-jenkins ](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8083/355723/355990/355991/log?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1h7tquhpjupuu%252Cti_u7ukrfvrt1yu%252Cti_qxkzvw4t6ipf%252Cti_1h7u8s8jf8tvb) 

Test fails 9 times logged in Report Portal, but never failed running from local computer (5 test runs performed). Failures happened priorly - earliest 2022-10-19

Therefore 60 sec for PVC creation after node drain is not enough and in the same time there is no clear requirement if PVC should be created and bound in 60 sec after node Drain. We need to decide what timeout between 60s and 2m20s meets requirement and set a new timeout for PVC Create & Bound after node drain.  

If decision to prolongate timeout will be taken it is proposed to extend function ocs-ci/ocs_ci/helpers/sanity_helpers.py:create_resources or pvc_factory to take timeout parameter. 

Links to other Report Portal occurrences:

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8178/361568/361845/361847/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8175/361258/361533/361534/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8148/359492/359760/359761/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8144/359135/359405/359406/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8118/357719/357987/357988/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8102/356826/357082/357083/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8086/356026/356281/356282/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8080/355418/355688/355690/log

**Comment by DanielOsypenko** [comment]
@ebenahar since you're the author of the test, WDYT about timeout?

**Comment by DanielOsypenko** [comment]
discussed with @ebenahar and @am-agrawa, decided to open BZ. Link - https://bugzilla.redhat.com/show_bug.cgi?id=2162504

**Comment by am-agrawa** [comment]
resolvedby #7008
