### ISSUE TITLE
UI tests are failing with TimeoutException at the setup

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#6955]
Refer- https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8267/364217/364508/364509/log

**Comment by am-agrawa** [comment]
@OdedViner Can you pls link the PR which fixes this issue?

**Comment by OdedViner** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/6959
https://github.com/red-hat-storage/ocs-ci/pull/6896

**Comment by am-agrawa** [comment]
> #6959 #6896

Closing this issue as it's fixed by these 2 PR's.
