### ISSUE TITLE
Create config for production with m5.4xlarge

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#696]
It was discussed on staff mtg that we should create such config and use it for production runs.
Also align with: https://jira.coreos.com/browse/KNIP-821

**Comment by clacroix12** [comment]
Is this for workers only or both master and worker nodes?

**Comment by petr-balogh** [comment]
In the ticket that mentioned nodes where OCS is running, which are worker nodes if I understand correctly.
