### ISSUE TITLE
Approve any Pending CSRs if "tls: internal error" received

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#6964]
During test_node_maintenance_restart_activate[worker] test got an error when trying execution of command: oc -n openshift-storage rsh noobaa-operator-5bcbbc7d8d-t7nqd bash -c "md5sum /usr/local/bin/noobaa-operator".

stderr: Error is Error from server: error dialing backend: remote error: tls: internal error

previously we had bz opened and closed as Not a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1736286

We need to correct our test framework in order to approve any Pending CSRs. See instructions in knowledgebase https://access.redhat.com/solutions/4307511

function exec_cmd() should be covered with retry decorator in the body of which we need to execute:
`for i in `oc get csr |grep Pending |awk '{print $1}'`; do oc adm certificate approve $i; done`

**Comment by am-agrawa** [comment]
Check if it's similar to issue #6724
