### ISSUE TITLE
TestDynamicPvc failures - ODF 4.11

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#6969]
Version:
local-storage-operator.4.11.0-202212070335
mcg-operator.v4.11.4
ocs-operator.v4.11.4
odf-csi-addons-operator.v4.11.4
odf-operator.v4.11.4
OCP: 4.11.20

sh-4.4$ ceph status
  cluster:
    id:     1fd884bf-801b-472c-bded-25d360eb6380
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 9d)
    mgr: a(active, since 9d)
    mds: 1/1 daemons up, 1 hot standby
    osd: 9 osds: 9 up (since 9d), 9 in (since 9d)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   11 pools, 417 pgs
    objects: 25.54k objects, 53 GiB
    usage:   164 GiB used, 916 GiB / 1.1 TiB avail
    pgs:     417 active+clean
 
  io:
    client:   1.4 KiB/s rd, 21 KiB/s wr, 2 op/s rd, 1 op/s wr

=========================== short test summary info ============================
FAILED tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Retain]
FAILED tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Delete]
FAILED tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Retain]
FAILED tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Delete]
FAILED tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Retain]
FAILED tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Delete]

**Comment by achuzhoy** [comment]
Full run logs [logs.tar.gz](https://github.com/red-hat-storage/ocs-ci/files/10482943/logs.tar.gz)

**Comment by ebenahar** [comment]
@achuzhoy seems to be similar to https://github.com/red-hat-storage/ocs-ci/issues/6973#issuecomment-1401611919
