### ISSUE TITLE
TestClone failures - ODF 4.11

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#6973]
Version:
local-storage-operator.4.11.0-202212070335
mcg-operator.v4.11.4
ocs-operator.v4.11.4
odf-csi-addons-operator.v4.11.4
odf-operator.v4.11.4
OCP: 4.11.20

sh-4.4$ ceph status
cluster:
id: 1fd884bf-801b-472c-bded-25d360eb6380
health: HEALTH_OK

services:
mon: 3 daemons, quorum a,b,c (age 9d)
mgr: a(active, since 9d)
mds: 1/1 daemons up, 1 hot standby
osd: 9 osds: 9 up (since 9d), 9 in (since 9d)
rgw: 1 daemon active (1 hosts, 1 zones)

data:
volumes: 1/1 healthy
pools: 11 pools, 417 pgs
objects: 25.54k objects, 53 GiB
usage: 164 GiB used, 916 GiB / 1.1 TiB avail
pgs: 417 active+clean

io:
client: 1.4 KiB/s rd, 21 KiB/s wr, 2 op/s rd, 1 op/s wr

=========================== short test summary info ============================
FAILED tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]
FAILED tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephFileSystem]

**Comment by achuzhoy** [comment]
cc @petr-balogh

**Comment by ebenahar** [comment]
Looks like the issue is with reaching to deb.debian.org:80 for running `apt-get` on the pods used for some of tests

```
10:48:42 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n namespace-test-1f30243837d640d7a2022c030 rsh pod-test-rbd-fd1eae72ac8e4e37b1210603885 apt-get update
10:48:43 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Could not connect to deb.debian.org:80 (199.232.82.132). - connect (111: Connection refused)
 Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:54::644). - connect (101: Network is unreachable)
```

From my laptop `deb.debian.org:80` is reachable. @achuzhoy could you please check why it's unreachable from the test execution?

**Comment by achuzhoy** [comment]
I'm still seeing all the same failures I reported above - even with the disconnected flag set to true.

run-ci tests/ -m "acceptance" --html logs/report.html --self-contained-html --cluster-path "/home/kni/ocs-ci/cluster/" --cluster-name "spk-factory-0" --ocs-version "4.11" --ocp-version "4.11" --collect-logs --collect-logs-on-success-run --junit-xml logs/junit.xml --ocsci-conf=ocs_ci/framework/conf/default_config.yaml --ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml --ocsci-conf=conf/ocsci/mcg_only_deployment.yaml --ocsci-conf=conf/custom.yaml 2>&1 |tee -a "logs/test_odf_output.log"

cat conf/custom.yaml:
REPORTING:
  default_ocs_must_gather_latest_tag: '4.11'
ENV_DATA:
  ocs_version: '4.11'
RUN:
  log_dir: "/home/kni/ocs-ci/logs"
DEPLOYMENT:
  ocs_csv_channel: "stable-4.11"
  disconnected: true

=========================== short test summary info ============================
FAILED tests/lvmo/test_lvm_clone_base.py::TestLvmSnapshot::test_create_clone_from_pvc[Filesystem-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_clone_base.py::TestLvmSnapshot::test_create_clone_from_pvc[Block-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_clone_base.py::TestLvmSnapshot::test_create_clone_from_pvc[Filesystem-Immediate]
FAILED tests/lvmo/test_lvm_clone_base.py::TestLvmSnapshot::test_create_clone_from_pvc[Block-Immediate]
FAILED tests/lvmo/test_lvm_multi_clone.py::TestLvmMultiClone::test_create_multi_clone_from_pvc[Filesystem-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_multi_clone.py::TestLvmMultiClone::test_create_multi_clone_from_pvc[Block-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_multi_clone.py::TestLvmMultiClone::test_create_multi_clone_from_pvc[Filesystem-Immediate]
FAILED tests/lvmo/test_lvm_multi_clone.py::TestLvmMultiClone::test_create_multi_clone_from_pvc[Block-Immediate]
FAILED tests/lvmo/test_lvm_multi_snapshot.py::TestLvmMultiSnapshot::test_create_multi_snapshot_from_pvc[Filesystem-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_multi_snapshot.py::TestLvmMultiSnapshot::test_create_multi_snapshot_from_pvc[Block-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_multi_snapshot.py::TestLvmMultiSnapshot::test_create_multi_snapshot_from_pvc[Filesystem-Immediate]
FAILED tests/lvmo/test_lvm_multi_snapshot.py::TestLvmMultiSnapshot::test_create_multi_snapshot_from_pvc[Block-Immediate]
FAILED tests/lvmo/test_lvm_snapshot_base.py::TestLvmSnapshot::test_create_snapshot_from_pvc[Filesystem-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_snapshot_base.py::TestLvmSnapshot::test_create_snapshot_from_pvc[Block-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_snapshot_base.py::TestLvmSnapshot::test_create_snapshot_from_pvc[Filesystem-Immediate]
FAILED tests/lvmo/test_lvm_snapshot_base.py::TestLvmSnapshot::test_create_snapshot_from_pvc[Block-Immediate]
FAILED tests/lvmo/test_lvm_snapshot_bigger_than_disk.py::TestLvmSnapshotBiggerThanDisk::test_create_snapshot_from_pvc_bigger_than_disk[Filesystem-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_snapshot_bigger_than_disk.py::TestLvmSnapshotBiggerThanDisk::test_create_snapshot_from_pvc_bigger_than_disk[Block-WaitForFirstConsumer]
FAILED tests/lvmo/test_lvm_snapshot_bigger_than_disk.py::TestLvmSnapshotBiggerThanDisk::test_create_snapshot_from_pvc_bigger_than_disk[Filesystem-Immediate]
FAILED tests/lvmo/test_lvm_snapshot_bigger_than_disk.py::TestLvmSnapshotBiggerThanDisk::test_create_snapshot_from_pvc_bigger_than_disk[Block-Immediate]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephFileSystem]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephBlockPool]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephFileSystem]
FAILED tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool
FAILED tests/manage/rgw/test_bucket_creation.py::TestRGWBucketCreation::test_bucket_creation[3-RGW-OC]
FAILED tests/manage/rgw/test_bucket_deletion.py::TestBucketDeletion::test_bucket_delete[3-RGW-OC]
ERROR tests/manage/mcg/test_write_to_bucket.py::TestBucketIO::test_write_file_to_bucket[DEFAULT-BACKINGSTORE]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephBlockPool-Delete]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwo_dynamic_pvc[CephFileSystem-Delete]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Retain]
ERROR tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Delete]
FAILED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node[CephFileSystem]
FAILED tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py::TestPVCDeleteAndVerifySizeIsReturnedToBackendPool::test_pvc_delete_and_verify_size_is_returned_to_backend_pool
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Delete]
ERROR tests/manage/pv_services/test_raw_block_pv.py::TestRawBlockPV::test_raw_block_pv[Retain]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]
ERROR tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephFileSystem]
ERROR tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephBlockPool]
ERROR tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephFileSystem]
SKIPPED tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacityLSO::test_add_capacity_lso_cli
= 27 failed, 7 passed, 6 skipped, 895 deselected, 17 errors in 3941.57s (1:05:41) =
