### ISSUE TITLE
Support test test_non_ocs_taint_and_tolerations for external mode 

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#6995]

**Comment by PrasadDesala** [comment]
This is a valid scenario for external mode. I would suggest to not skip it.
The test can be run on external mode with some little adjustments.

**Comment by Shrivaibavi** [comment]
This issue is marked as stale, any progress on this issue ??

**Comment by am-agrawa** [comment]
> This issue is marked as stale, any progress on this issue ??

Removed the label. No progress yet.
