### ISSUE TITLE
For disconnected cluster pod postgres-0  is stuck on 'Pending' state

### ISSUE THREAD

**Issue by vkathole** [red-hat-storage/ocs-ci#7005]
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8465/375692/375703/375704/log
Run ID: 1674231409  
ODF Build: 4.12.0-167
OCP Version: 4.12

Failure Details:

```
Message: ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 3600s running get("", True, "app=postgres")
Type: None


Text:
self = <test_pgsql_pvc_clone.TestPvcCloneOfWorkloads object at 0x7fda85527f10>
pgsql_factory_fixture = <function pgsql_factory_fixture..factory at 0x7fda665ba0d0>
pvc_clone_factory = <function pvc_clone_factory_fixture..factory at 0x7fda66756820>
pgsql_teardown = None


@skipif_ocs_version("<4.6")
@skipif_ocp_version("<4.6")
@pytest.mark.polarion_id("OCS-2342")
def test_pvc_clone(self, pgsql_factory_fixture, pvc_clone_factory, pgsql_teardown):
    """
    1. Deploy PGSQL workload
    2. Create multiple clone of same PVC when the PVC usage is different
    3. Attach a new pgsql pod to it.
    4. Create pgbench benchmark to new pgsql pod
    """
    pgsql_teardown

    # Deploy PGSQL workload
    log.info("Deploying pgsql workloads")

  pgsql = pgsql_factory_fixture(replicas=1)

tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py:139: 



tests/conftest.py:3006: in factory
    pgsql.setup_postgresql(replicas=replicas, sc_name=sc_name)
ocs_ci/ocs/pgsql.py:90: in setup_postgresql
    self.pod_obj.wait_for_resource(
ocs_ci/ocs/ocp.py:729: in wait_for_resource
    raise (ex)
ocs_ci/ocs/ocp.py:619: in wait_for_resource
    for sample in TimeoutSampler(



self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7fda7f8a2340>


def __iter__(self):
    if self.start_time is None:
        self.start_time = time.time()
    while True:
        self.last_sample_time = time.time()
        if self.timeout <= (self.last_sample_time - self.start_time):

          raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 3600s running get("", True, "app=postgres")



ocs_ci/utility/utils.py:1176: TimeoutExpiredError

```

**Comment by nagendra202** [comment]
Mirrored image isn't picked for all components in disconnected mode. Identified the root cause. Need to update the Deployment YAML file with mirrored image instead of Quay.io. And pass the same updated values in setup_amq_cluster_operator function.

**Comment by nagendra202** [comment]
Pgsql: Similar issue for test_pvc_clone as it is trying to pull the mirrored image of pgsql and failing

2023-10-08 01:42:49,416 - ThreadPoolExecutor-21_0 - INFO - ocs_ci.utility.utils.exec_cmd.622 - Executing command: podman login --authfile /tmp/authfile_roou_bbo ocs-qe-proxy-dc-eco.usersys.redhat.com:5000 -u ***** -p ***** --tls-verify=false
2023-10-08 01:42:49,726 - ThreadPoolExecutor-21_0 - INFO - ocs_ci.utility.utils.exec_cmd.622 - Executing command: podman image pull quay.io/rhceph-dev/ocs-must-gather:latest-4.14 --authfile /tmp/authfile_roou_bbo

**Comment by nagendra202** [comment]
> Mirrored image isn't picked for all components in disconnected mode. Identified the root cause. Need to update the Deployment YAML file with mirrored image instead of Quay.io. And pass the same updated values in setup_amq_cluster_operator function.

Changes need to be done in below function

def is_amq_pod_running(
        self, pod_pattern, expected_pods, namespace=constants.AMQ_NAMESPACE
    ):


-----------------------------------------------------------------
Issue hit in 4.15 as well:

tests/functional/workloads/test_new_sc_rbd_e2e_workloads.py:58: 



tests/conftest.py:3512: in factory
    amq.setup_amq_cluster(
ocs_ci/ocs/amq.py:924: in setup_amq_cluster
    self.setup_amq_kafka_persistent(sc_name, size, replicas)
ocs_ci/ocs/amq.py:261: in setup_amq_kafka_persistent
    if self.is_amq_pod_running(
ocs_ci/ocs/amq.py:193: in is_amq_pod_running
    for pod in TimeoutSampler(
----------------------------------------------------------------

RP: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/18671/904587/904700/log
