### ISSUE TITLE
Fix creating dc pods in the test "tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py" with IBMCloud platform

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7029]
When running the test "tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py" with the IBMCloud platform, it failed to create the dc pods, as we can see here: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6514/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity_entry_exit_criteria/TestAddCapacity/test_add_capacity_10_/. Maybe we need to modify the fixture `multi_dc_pod` or use another method for creating dc pods with IBMCloud platform.

**Comment by am-agrawa** [comment]
Failed on baremetal too- RUN ID: 1674640067
Also failing on VMware- https://chat.google.com/room/AAAATLp3XsQ/LPoRjTYjoeQ

**Comment by am-agrawa** [comment]
As per Prasad, this test should be applicable for all platforms to say which minor modifications in the test.
