### ISSUE TITLE
Wait for node deletion before powering OFF the VM for test_nodereplacement_proactive

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#7069]
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/407/8281/364646/364667/364669/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED

Test fails bcz there are 3 CSR's in total, out of which 1 is for the old node which is getting deleted. The other 2 are for the new node which is fine.

Discussed with OCP team- https://redhat-internal.slack.com/archives/CJARLA942/p1675689335679539 and the suggestion is to wait for the node deletion before powering OFF the VM. Since the node is not deleted by this time, that would have generated a new CSR which is eventually failing the test.

In actual, there should only be 2 CSR's for the new node, one for client credentials, one for its serving certificate. However, if we don't approve those CSRs within 15 minutes, it will retry and create another.

This function `def remove_nodes(nodes):` doesn't wait for node deletion, so we will have to see if we still hit the isue when node is deleted before powering OFF the VM.

**Comment by petr-balogh** [comment]
I know we are currently using the terraform to handle the creation of new nodes which can then makes troubles when trying to delete resource and it's still int terraform tf state file.  I am curious why we don't utilize MachineSet like we do in IPI deployments on different platforms also for UPI, based on this article, it should be supported from 4.5: https://access.redhat.com/solutions/5307621 so maybe we can observe this option and completely rework add node here.

**Comment by am-agrawa** [comment]
> I know we are currently using the terraform to handle the creation of new nodes which can then makes troubles when trying to delete resource and it's still int terraform tf state file. I am curious why we don't utilize MachineSet like we do in IPI deployments on different platforms also for UPI, based on this article, it should be supported from 4.5: https://access.redhat.com/solutions/5307621 so maybe we can observe this option and completely rework add node here.

Sure Petr, we will try to do that as part of issue #7172
