### ISSUE TITLE
MCG (NooBaa) tests should be running

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#707]
All MCG tests are currently skipped. 
Now that we deploy clusters using OCS operator, these tests should not be skipped

**Comment by ebenahar** [comment]
@parikshithb @MeridianExplorer let's remove the skip now that the instance type has been increased

**Comment by MeridianExplorer** [comment]
On it

**Comment by MeridianExplorer** [comment]
Taken care of in [PR718](https://github.com/red-hat-storage/ocs-ci/pull/718/files) 
Just waiting for approvals

**Comment by MeridianExplorer** [comment]
PR #718 Merged
