### ISSUE TITLE
test_add_capacity_pre_upgrade is failing with "Data re-balance failed to complete" error

### ISSUE THREAD

**Issue by pintojoy** [red-hat-storage/ocs-ci#7075]
Message: AssertionError: Data re-balance failed to complete
Type: None

Text:
self = <tests.manage.z_cluster.cluster_expansion.test_add_capacity.TestAddCapacityPreUpgrade object at 0x7fe48f653d90>
reduce_and_resume_cluster_load = None

def test_add_capacity_pre_upgrade(self, reduce_and_resume_cluster_load):
    """
    Test to add variable capacity to the OSD cluster while IOs running
    """

  add_capacity_test()

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py:177: 

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py:94: in add_capacity_test
    check_ceph_health_after_add_capacity(ceph_rebalance_timeout=3600)

ceph_health_tries = 119, ceph_rebalance_timeout = 6600

def check_ceph_health_after_add_capacity(
    ceph_health_tries=80, ceph_rebalance_timeout=1800
):
    """
    Check Ceph health after adding capacity to the cluster

    Args:
        ceph_health_tries (int): The number of tries to wait for the Ceph health to be OK.
        ceph_rebalance_timeout (int): The time to wait for the Ceph cluster rebalanced.

    """
    if config.RUN.get("io_in_bg"):
        logger.info(
            "Increase the time to wait for Ceph health to be health OK, "
            "because we run IO in the background"
        )
        additional_ceph_health_tries = int(config.RUN.get("io_load") * 1.3)
        ceph_health_tries += additional_ceph_health_tries

        additional_ceph_rebalance_timeout = int(config.RUN.get("io_load") * 100)
        ceph_rebalance_timeout += additional_ceph_rebalance_timeout

    ceph_health_check(
        namespace=config.ENV_DATA["cluster_namespace"], tries=ceph_health_tries
    )
    ceph_cluster_obj = CephCluster()

  assert ceph_cluster_obj.wait_for_rebalance(
        timeout=ceph_rebalance_timeout
    ), "Data re-balance failed to complete"
E       AssertionError: Data re-balance failed to complete

ocs_ci/ocs/cluster.py:2070: AssertionError

**Comment by pintojoy** [comment]
There was one PR in the past (https://github.com/red-hat-storage/ocs-ci/pull/4752/)

**Comment by yitzhak12** [comment]
I see that most(or even all the failures) failed with the error: "Message: AssertionError: Data re-balance failed to complete", having the param: `IO_IN_BACKGROUND` in the Jenkins job, like this one https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/426/9462/418305/418337/418338/log?logParams=history%3D418338%26page.page%3D1 for example.

**Comment by pintojoy** [comment]
Observed this issue in https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/13855/630549/630635/630638/log
