### ISSUE TITLE
Fix the function "wait_for_nodes_status" to ignore "CommandFailed" exception

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7086]
As you can see in the failed test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6613/testReport/tests.manage.z_cluster.cluster_expansion.test_verify_ceph_csidriver_runs_on_non_ocs_nodes/TestCheckTolerationForCephCsiDriverDs/test_ceph_csidriver_runs_on_non_ocs_nodes/, it failed because of the "CommandFailed" exception in the function `wait_for_nodes_status`. 
The error occurred in the line https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/node.py#L148: 
`if node.ocp.get_resource_status(node.name) == status:` when getting the node status. 
We must ensure we ignore the `CommandFailed` exception here(One way to do it is with `try` and `except`).

**Comment by am-agrawa** [comment]
Let's try to replicate the issue and fix it if needed.
