### ISSUE TITLE
Removal of custom test runner framework code

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#71]
As we complete our transition to utilizing pytest we will want to remove any code that was only applicable to our custom test runner. This should be done once test execution and all features we utilized with our custom runner are supported through pytest.

Items to remove (not limited to):
- TestStatus
- TestCase Class
- run.py
- several utility functions

**Comment by clacroix12** [comment]
The work for this has been done in #269 and ﻿#277 so far. Additional cleanup of legacy (ceph-ci) code that is no longer of use to us will be done in a separate issue/PR.

**Comment by gklein** [comment]
Is there any more work required on this issue or should we close it?

**Comment by clacroix12** [comment]
Yes, I think we can close this out. I initially wanted to keep it open for the review/removal of additional code but we can open a new ticket if we define anything that needs to be cleaned up.
