### ISSUE TITLE
Fix the test "test_check_mds_cache_memory_limit" to retry getting the value in case of a CommandFailed exception with the 'ENOENT' message

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7101]
We can see in the failed test here https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6575/testReport/tests.manage.z_cluster.test_ceph_default_values_check/TestCephDefaultValuesCheck/test_check_mds_cache_memory_limit/, that the test failed because it throws a CommandFailed exception: `Error is Error ENOENT: no config state for daemon mds.ocs-storagecluster-cephfilesystem-a`. I remember that we tried to add retry in the test to retrieve the values multiple times. 
I see two things we need to fix in the test above:

1. Delete the first line https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/test_ceph_default_values_check.py#L149: `mds_cache_memory_limit = get_mds_cache_memory_limit()` as it redundent.
2. Add a CommandFailed exception in the test `test_check_mds_cache_memory_limit` so we catch IOError and CommandFailed exceptions multiple times if needed.

**Comment by am-agrawa** [comment]
Also tagging @AviadP if you can help fixing this test.

**Comment by yitzhak12** [comment]
From the comment here: https://github.com/red-hat-storage/ocs-ci/issues/4637#issuecomment-1404372291, this issue was already observed when running an upgrade from version 4.11 to 4.12.

**Comment by yitzhak12** [comment]
The issue still exists: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/15776/741363/741370/741371/log.
