### ISSUE TITLE
Update the test "tests/manage/z_cluster/nodes/test_node_replacement_proactive.py" for "baremetal" platform

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7186]
The test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6720/testReport/tests.manage.z_cluster.nodes.test_node_replacement_proactive/TestNodeReplacementTwice/test_nodereplacement_twice/, failed because it didn't find the `baremetal` platform option in the function `delete_and_create_osd_node`. 
So, it continued to the verification steps without adding a new node.

The test `tests/manage/z_cluster/nodes/test_node_replacement_proactive.py` currently does not support the `baremetal` platform. We need to update the test to support this option. It may be the same steps as LSO, but we need to figure out that.

**Comment by am-agrawa** [comment]
Closing this as duplicate of issue #7196 . Pratik is already assigned to 7196.
