### ISSUE TITLE
Enable log FileHandlers per test function

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#72]
Currently with our ocs-ci custom test runner we create a log FileHandler for every test case. We would like to replicate this behavior with pytest. One way of getting after this that sounds fairly straight forward is implementing a function level fixture that creates and removes the handlers for every test.

https://stackoverflow.com/questions/41400722/pytest-implementing-a-logfile-per-test-method

**Comment by vavuthu** [comment]
Assigning to myself.

**Comment by clacroix12** [comment]
#159
