### ISSUE TITLE
Update the test "test_pdb_check_simultaneous_node_drains" to support or skip 6 worker nodes

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7216]
The test "test_pdb_check_simultaneous_node_drains" currently fails when we use 6 worker nodes, as you can see here: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/9215/408320/408350/408353/log.
It failed because when we have 6 worker nodes, it doesn't reach the line https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/nodes/test_nodes_maintenance.py#L530: `schedule_nodes([node_A])`, and `node_A` stays unscheduled at the end of the test. This may be fixed when we schedule `node_A` before the last step `Check cluster and Ceph health`. Or if this test is aimed for 3 worker nodes, we can skip it if we have 6 worker nodes.

**Comment by am-agrawa** [comment]
I think it would be good to support it for 6 worker notes, rather than skipping it.

**Comment by pintojoy** [comment]
Existing test passes with http://pastebin.test.redhat.com/1096716
OCP 4.12.0-0.nightly-2023-03-25-132813
ODF stable-4.12

**Comment by am-agrawa** [comment]
Test failure seen here on ODF 4.12.2- https://url.corp.redhat.com/3df34c6
Re-opening after discussing with Joy.

**Comment by pintojoy** [comment]
@Shrivaibavi Did you get any chance to go over this issue
