### ISSUE TITLE
test_toleration fails as the toolbox pod doesn't have toleration

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#7228]
Run ID: 1676676006 || Suite: tier4c || ODF 4.12.1-13, OCP 4.12, vsphere
`tests/manage/z_cluster/nodes/test_toleration.py::TestTaintAndTolerations::test_toleration`

2023-02-18 09:39:49  04:09:49 - MainThread - ocs_ci.ocs.resources.pod - ERROR  - The pod rook-ceph-tools-external-57db64774c-l44ks is in Pending state. Expected = Running

status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-18T04:04:40Z"
    message: '0/6 nodes are available: 3 node(s) had untolerated taint {node-role.kubernetes.io/master:
      }, 3 node(s) had untolerated taint {node.ocs.openshift.io/storage: true}. preemption:
      0/6 nodes are available: 6 Preemption is not helpful for scheduling.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending

**Comment by am-agrawa** [comment]
Assigning to Vaibhavi based upon discussion in Brown squad triage call and Elad's input.

**Comment by am-agrawa** [comment]
@vavuthu @petr-balogh Looks like we need to add tolerations to toolbox pod in external mode. Could someone from ecosystem team take it up?
@Shrivaibavi ^^

**Comment by amr1ta** [comment]
Currently this test is failing due to, https://github.com/red-hat-storage/ocs-ci/issues/9172 
Closing this issue.
