### ISSUE TITLE
Add OBC support for 4.10 UI testing

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#7249]
The `views.py::locators.4.10` dict doesn't have an `obc` entry so `	
test_obc_creation_and_deletion` fails with a KeyError while trying to initialize ObcUI:

```
class ObcUI(PageNavigator):
    """
    A class representation for abstraction of OBC-related OpenShift UI actions

    """

    def __init__(self, driver):
        super().__init__(driver)
        ocs_version = f"{version.get_ocs_version_from_csv(only_major_minor=True)}"
        self.obc_loc = locators[ocs_version]["obc"]
...
...
Message: KeyError: 'obc'
``` 

Runs:
[test_obc_creation_and_deletion[openshift-storage.noobaa.io-noobaa-default-bucket-class-Actions]-02/24/2023](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/432/9240/409505/409641/409643/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1h7tquhpjupuu%252Cti_u7ukrfvrt1yu%252Cti_qxkzvw4t6ipf%252Cti_1h7u8s8jf8tvb)
[test_obc_creation_and_deletion[openshift-storage.noobaa.io-noobaa-default-bucket-class-three_dots]-02/24/2023](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/432/9240/409505/409641/409642/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1h7tquhpjupuu%252Cti_u7ukrfvrt1yu%252Cti_qxkzvw4t6ipf%252Cti_1h7u8s8jf8tvb)
[test_obc_creation_and_deletion[openshift-storage.noobaa.io-noobaa-default-bucket-class-Actions]-02/25/2023](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/432/9273/411686/411822/411824/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1h7tquhpjupuu%252Cti_u7ukrfvrt1yu%252Cti_qxkzvw4t6ipf%252Cti_1h7u8s8jf8tvb)
[test_obc_creation_and_deletion[openshift-storage.noobaa.io-noobaa-default-bucket-class-three_dots]-02/25/2023](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/432/9273/411686/411822/411823/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1h7tquhpjupuu%252Cti_u7ukrfvrt1yu%252Cti_qxkzvw4t6ipf%252Cti_1h7u8s8jf8tvb)

**Comment by DanielOsypenko** [comment]
covered with https://github.com/red-hat-storage/ocs-ci/pull/7319
