### ISSUE TITLE
Add nodes failing on Azure Platform

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#7315]
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/446/9373/414810/415028/415029/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/446/9373/414810/415030/415031/log

Looks like the new nodes 3 (app,worker) has been added successfully, But fails with Resource exception errors

http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-187zi3c33-uo/j-187zi3c33-uo_20230301T102148/logs/failed_testcase_ocs_logs_1677702009/test_add_ocs_node_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-2a0e67a84ae60d7773497056615dad3228c949e32c35c3901a553a6e7cd6bcd1/cluster-scoped-resources/oc_output/get_nodes_-o_wide_--show-labels

Do we need to increase the timeout ???

**Comment by yitzhak12** [comment]
Yes, increasing the timeout with the Azure platform will be a good idea. See, for example, the failure here: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/9373/414810/415028/415029/log?item1Params=page.page%3D2&logParams=history%3D415029%26page.page%3D1
