### ISSUE TITLE
test_bidirectional_bucket_replication[AWStoAZURE-BS-OC] failed with InternalError ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh s3cli-0 sh -c "AWS_CA_BUNDLE=/cert/service-ca.crt AWS_ACCESS_KEY_ID=* AWS_SECRET_ACCESS_KEY=* AWS_DEFAULT_REGION=us-east-2 aws s3 --endpoint=***** sync /test_objects/ s3://oc-bucket-a908de6444c345ec92c3d98d6a2d51".

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#7337]
Run details:
Build URL: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/7213/
Cluster version: 4.9.0-0.nightly-2023-02-28-091622
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-252ai3c33-ua/j-252ai3c33-ua_20230316T065536/logs/

Error message:

Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh s3cli-0 sh -c "AWS_CA_BUNDLE=/cert/service-ca.crt AWS_ACCESS_KEY_ID=* AWS_SECRET_ACCESS_KEY=* AWS_DEFAULT_REGION=us-east-2 aws s3 --endpoint=***** sync /test_objects/ s3://oc-bucket-a908de6444c345ec92c3d98d6a2d51".
Error is upload failed: ../test_objects/steve.webm to s3://oc-bucket-a908de6444c345ec92c3d98d6a2d51/steve.webm An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 2): We encountered an internal error. Please try again.
upload failed: ../test_objects/enwik8 to s3://oc-bucket-a908de6444c345ec92c3d98d6a2d51/enwik8 An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 2): We encountered an internal error. Please try again.
command terminated with exit code 1
Type: None

**Comment by mashetty330** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2168867
