### ISSUE TITLE
test_disable_nb_lb is failing on IBM power for OCS 4.13

### ISSUE THREAD

**Issue by AbhishekMundada** [red-hat-storage/ocs-ci#7342]
tests/manage/mcg/test_s3_routes.py::TestS3Routes::test_disable_nb_lb testcase is failing on IBM Power for OCS 4.13 with the following error.
Error:
```
E           AssertionError: Failed: s3 type LoadBalancer
E           assert 'LoadBalancer' == 'ClusterIP'
E             - ClusterIP
E             + LoadBalancer
```

**Comment by AbhishekMundada** [comment]
Text Failure :
`
_______________________ TestS3Routes.test_disable_nb_lb ________________________

self = <tests.manage.mcg.test_s3_routes.TestS3Routes object at 0x7fffa057a190>
revert_lb_service = None

    @tier3
    @skipif_external_mode
    @skipif_ibm_cloud
    @skipif_managed_service
    @bugzilla("1954708")
    @pytest.mark.polarion_id("OCS-4653")
    @skipif_ocs_version("<4.10")
    def test_disable_nb_lb(self, revert_lb_service):
        """
        Validates the functionality of disableLoadBalancerService param
        """
        nb_obj = ocp.OCP(
            kind=constants.NOOBAA_RESOURCE_NAME,
            namespace=defaults.ROOK_CLUSTER_NAMESPACE,
            resource_name=constants.NOOBAA_RESOURCE_NAME,
        )
        lb_param = (
            '[{"op": "add", "path": "/spec/disableLoadBalancerService", "value": true}]'
        )
        logger.info("Patching noobaa resource to enable disableLoadBalancerService")
        nb_obj.patch(params=lb_param, format_type="json")

        nb_mgmt_svc_obj = ocp.OCP(
            kind=constants.SERVICE,
            namespace=defaults.ROOK_CLUSTER_NAMESPACE,
            resource_name="noobaa-mgmt",
        )
        nb_s3_svc_obj = ocp.OCP(
            kind=constants.SERVICE,
            namespace=defaults.ROOK_CLUSTER_NAMESPACE,
            resource_name="s3",
        )
        sleep(10)
        logger.info("Validating service type changed to ClusterIP")
        if version.get_semantic_ocs_version_from_config() < version.VERSION_4_12:
            assert (
                nb_mgmt_svc_obj.data["spec"]["type"]
                and nb_s3_svc_obj.data["spec"]["type"] == "ClusterIP"
            ), (
                f'Failed: noobaa-mgmt type: {nb_mgmt_svc_obj.data["spec"]["type"]}, '
                f's3 type {nb_s3_svc_obj.data["spec"]["type"]}'
            )
        else:
>           assert (
                nb_s3_svc_obj.data["spec"]["type"] == "ClusterIP"
            ), f'Failed: s3 type {nb_s3_svc_obj.data["spec"]["type"]}'
E           AssertionError: Failed: s3 type LoadBalancer
E           assert 'LoadBalancer' == 'ClusterIP'
E             - ClusterIP
E             + LoadBalancer

tests/manage/mcg/test_s3_routes.py:234: AssertionError

`

**Comment by AbhishekMundada** [comment]
ClusterVersion : 
Cluster version is 4.13.0-0.nightly-ppc64le-2023-03-13-152806

ODF version : 
[root@rdr-kms-sao01-bastion-0 ~]# oc get csv odf-operator.v4.13.0-98.stable -n openshift-storage -o yaml |grep full_version
    full_version: 4.13.0-98

**Comment by vavuthu** [comment]
this issue should be fixed by PR https://github.com/red-hat-storage/ocs-ci/pull/7657
