### ISSUE TITLE
Resources leftovers is shown when the pod is respinned "Resources added and resources removed"

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#737]
Observed that when pods are respinned the environmental check is failing with error "resources are added and resources are removed". 

Few of the scenarios where we hit the issue. 
1. When setting RBAC permission the pod gets respinned, that is shown in environmental check(when installing openshift-logging)
2. When rebooting the master
3. When draining the worker nodes the pods are respinned.

For now we can use @ignore_leftovers markers, But It is good to have an enhancement for this.

Please share your inputs.

**Comment by vasukulkarni** [comment]
It makes sense to disable this by default and only enable for tests that need the verification.

**Comment by petr-balogh** [comment]
> It makes sense to disable this by default and only enable for tests that need the verification.

What about opposite way? Have it enabled by default but for problematic tests like mentioned in the issue have the way to disable this check?

**Comment by clacroix12** [comment]
> What about opposite way? Have it enabled by default but for problematic tests like mentioned in the issue have the way to disable this check?

Isn't that the current functionality with `@ignore_leftovers`?

**Comment by petr-balogh** [comment]
Yep, it is. So do not think that we should by default skip this leftover check.
