### ISSUE TITLE
test_nodereplacement_proactive fails with Health: HEALTH_WARN 1/3 mons down, quorum a,c; 1 osds down; 1 host (1 osds) down; 1 rack (1 osds) down

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#7390]
Run details:

Run ID: 1670222569
Test Case: test_nodereplacement_proactive
ODF Build: 4.12.0-125
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS LOWERREQ VSAN 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6298/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/vavuthulwreq-t4a/vavuthulwreq-t4a_20221205T051247/logs/
Error Message: failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum a,c; 1 osds down; 1 host (1 osds) down; 1 rack (1 osds) down; Degraded data redundancy: 861/2583 objects degraded (33.333%), 133 pgs degraded, 353 pgs undersized"

**Comment by am-agrawa** [comment]
@vavuthu Also this one, do you think this will also be fixed by your recent PR?

**Comment by vavuthu** [comment]
> @vavuthu Also this one, do you think this will also be fixed by your recent PR?

yep
