### ISSUE TITLE
Add custom parser arguments for cluster config, suite config, and cluster path

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#74]
We have CLI arguments for specifying a cluster configuration, suite configuration, as well as the path to an existing cluster directory in the event you want to run tests against an established cluster. We need to create custom parser arguments so we may do the same through pytest, as well as implement the necessary functionality to support them in our tests.

This issue might be broken up into several based on the scope of things, but I wanted to capture the need for all three. 

- [x] cluster_config
- [x] cluster_path
- [ ] suite_config

**Comment by petr-balogh** [comment]
Working on it in my PR bud still WIP and didn't submit latest changes, will update soon

**Comment by petr-balogh** [comment]
Partially covered in #61

**Comment by petr-balogh** [comment]
@vasukulkarni  @RazTamir @clacroix12  We need to discuss this suite config on our mtg what do we think of it in pytest way.

**Comment by petr-balogh** [comment]
Closing this one and in case some config for suite is still relevant for pytest we can open new issue with more details.
