### ISSUE TITLE
RHEL deployment is failing with: 'resolvelib<0.9.0,>=0.5.3' distribution was not found

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#7423]
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n default rsh rhel-ansible ansible-playbook -i /hosts --private-key=/openshift-dev.pem /usr/share/ansible/openshift-ansible/playbooks/scaleup.yml.
E               Error is [WARNING]: Skipping plugin (/usr/share/ansible/openshift-
E               ansible/roles/openshift_node/callback_plugins/aa_version_requirement.py) as it
E               seems to be invalid: The 'resolvelib<0.9.0,>=0.5.3' distribution was not found
E               and is required by ansible-core
E               command terminated with exit code 2

Failed here:
 https://url.corp.redhat.com/12be7d7

**Comment by shylesh** [comment]
This is because of the issue: https://url.corp.redhat.com/scaleoutissue

**Comment by petr-balogh** [comment]
let's close this issue then.
