### ISSUE TITLE
Jenkins workload testcases failing withocs_ci.ocs.exceptions.UnexpectedBehaviour: jax-rs-build-1 did not reach to Complete state after 900 sec

### ISSUE THREAD

**Issue by vkathole** [red-hat-storage/ocs-ci#7435]
RP Launch URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/10069/442349/442378

Test cases : tests/e2e/workloads/app/jenkins/test_jenkins.py

**Comment by PrasadDesala** [comment]
@vkathole The original issue tracking this issue was fixed. Lets open a new issue for the recent jenkins workload failure.
