### ISSUE TITLE
Improve ceph side check for tests.manage.z_cluster.nodes.test_node_replacement_proactive.TestNodeReplacement

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#7436]
RP link:- https://url.corp.redhat.com/87bbee9

Drain and deleted node name was `compute-1` and new node name was also `compute-1` so verification failed 

old_node_name = 'compute-1', new_node_name = 'compute-1'

**Comment by am-agrawa** [comment]
@vavuthu Would this issue be handled by the PR you are currently working on?

**Comment by am-agrawa** [comment]
Fixed by #7510
