### ISSUE TITLE
Consume KUBEADMIN and KUBECONFIG environment variables by default

### ISSUE THREAD

**Issue by rabin-io** [red-hat-storage/ocs-ci#7498]
Hi, 

As part of concertizing the tests, can you please refactor the code to use KUBEADMIN & KUBECONFIG environment variables by default if the cluster dir is not defined as cli argument?

This addition allows us to use the image in CI systems which inject this variables as part of the OCP installation process.

**Comment by petr-balogh** [comment]
I will bring it out to tomorrow automation meeting. For now assigning to @OdedViner  :)

**Comment by rabin-io** [comment]
@OdedViner What do you think?
