### ISSUE TITLE
Adjust the test "test_hugepages_post_odf_deployment" to run on IBMCloud

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7504]
Currently, when running on IBMCloud, the test `test_hugepages_post_odf_deployment` is failing with the error: 

> E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc get MachineConfigPool worker -o yaml.
E               Error is Error from server (NotFound): machineconfigpools.machineconfiguration.openshift.io "worker" not found

As you can see, for example, in the test: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/427/10433/463335/463487/463489/log?logParams=history%3D463488%26page.page%3D1. The error occurred when calling the function `wait_for_machineconfigpool_status`. We need to adjust the function above for IBMCloud.

**Comment by ebenahar** [comment]
following a discussion with @prsurve and the brown squad, looks like we will need to disable the test over IBM ROKS
