### ISSUE TITLE
Test validating basic must-gather functionality

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#754]
Create test validating basic must-gather functionality which will be integrated with already implemented must-gather usage:

* the test is executed after the must-gather data are fetched
* would explicitely log must gather image versions
* would check that some minimal set of files are present and not empty
* for selected important files, it will check that the content of must-gater files follows expected structure (eg. file is at least this big, has a line which matches a regexp, ...)

Based on BZ 1751802. This should also be aligned with KNIP-732.

**Comment by gklein** [comment]
This [PR](https://github.com/red-hat-storage/ocs-ci/pull/949) was merged recently to cover must-gather testing
