### ISSUE TITLE
Many post upgrade tests did not check ceph health at the setup

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#7540]
Console url- https://url.corp.redhat.com/
Run ID: 1678710990

While debugging `test_pod_log_after_upgrade`, it was found that osd-3 and a mon was not ready. So the test should have skipped at setup because of ceph health not being ok.

This pattern is found is many post upgrade runs, however, a few tests did check the ceph health at setup and skipped running in the same run.

Kindly refer the console logs for this test in a sequential order to find out the pattern.

**Comment by am-agrawa** [comment]
@petr-balogh Could someone from ecosystem team look at this issue pls?

**Comment by petr-balogh** [comment]
@OdedViner do you want to take this?

**Comment by am-agrawa** [comment]
Linked pr #7552 is already merged.
