### ISSUE TITLE
ceph_size_varying fix in test_pvc_delete_verify_size_is_returned_to_backendpool.py

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#757]
def check_ceph_used_space():
        """
        Check for the used space in cluster
        """
        ct_pod = pod.get_ceph_tools_pod()
        ceph_status = ct_pod.exec_ceph_cmd(ceph_cmd="ceph status")
        assert ceph_status is not None
        used = ceph_status['pgmap']['bytes_used']
        used_in_gb = used / constants.GB
        global used_space
        if used_space and used_space == used_in_gb:
            return used_in_gb
        used_space = used_in_gb
        raise UnexpectedBehaviour(
>           f"In Ceph status, used size is varying"
        )
E       ocs_ci.ocs.exceptions.UnexpectedBehaviour: In Ceph status, used size is varying

This test case passes consistently in local setup. But it is flaky in jenkins, may be because of the environment, leftovers from other test cases which affects the used_size, etc.
 
Reason:
"ceph status" or any ceph commands which returns the used_size does not show exact size immediately after creating/deleting rbd-images/pools etc.
For ex: In this test case we used to create a pvc and write 10GB of data after attaching a pod. In Ceph backend, it stores 30 GB (10*repliication(3)) on OSDs. Ceph status keeps on updating this used_size in intervals, we query "ceph status" for used_size(it varies in bytes) and after reaching max retries it errors out saying "used size is varying".

Solutions:
1. Increasing the delay/retires - Not recommended, since it is not possible to predict when the ceph status exact used size. As the number of tier1 test cases which creates pvc/pods increases, delay would vary. 

2. Reduce the IOs written on pod in this script: Reducing the IOs on pod results in quicker deletion and reflects the size sooner. Reducing the IOs does not impact the functionality. 

3. Changing from "ceph status" to "rados df -p <pool-name>": Based on my testing, using the later command is more accurate since it negates other pools created by different tests.

**Comment by parikshithb** [comment]
Implemented 2nd and 3rd solutions.

**Comment by RazTamir** [comment]
Well done!
Great analysis
