### ISSUE TITLE
Add steps to get 4.2 / 4.3 package manifests for operatorsource object in openshift-logging

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#763]
Need to collect the package manifest, images manually for the object operatorsource in openshift-logging.

**Comment by Shrivaibavi** [comment]
To  update the images of openshift-logging from 4.1 to 4.2, we can make use of these scripts. 

To run these scripts we need account in quay.io and we need to have access to the repositories mentioned below. The access to the repositories can be given by the OCP team.

* rh-osbs-operators
* redhat-operators-stage
* redhat-operators-art1.

1. https://github.com/openshift-qe/v3-testfiles/blob/master/logging/tools/getOperatorSourceMetadata.sh
2. https://github.com/openshift-qe/v3-testfiles/blob/master/logging/tools/sync_images_to_internal_registry.sh
3. https://github.com/openshift-qe/v3-testfiles/blob/master/logging/tools/use_downstream_operatorresource.sh

Then validate to check whether the images are updated to 4.2 by running

Validate the images are listed after running the 1st script
1. cat OperatorSource_Images_Labels.txt

Validate after running the 2nd script ( To check logging images are synced to the internal image registry successfully )
2. oc get is -n openshift |grep -e logging  -e elastic -e oauth 

Validate the csv images have changed to 4.2 running the 3rd script
3. oc get csv -n openshift-logging


Automation for the above mentioned steps are in progress.

**Comment by Shrivaibavi** [comment]
The PR #837 is in review

**Comment by Shrivaibavi** [comment]
We can keep this issue open to track the same process in OCP 4.3

**Comment by PrasadDesala** [comment]
This issue can be closed as the changes are already implemented in ocs-ci
