### ISSUE TITLE
When running the acceptance tests, the test leaves some S3 leftovers in our AWS account

### ISSUE THREAD

**Issue by rabin-io** [red-hat-storage/ocs-ci#7761]
After each run of the acceptance tests, against a manual deployed cluster (on AWS) with ODF installed, there are S3 buckets leftovers, 

```
nb.1686156464384.release-ci.cnv-qe.rhood.us
nb.1686217962571.release-ci.cnv-qe.rhood.us
```

These buckets should be removed after the test are done.

**Comment by sagihirshfeld** [comment]
It looks like we have some incomplete assumptions regarding the name of these buckets in this cleanup function:
https://github.com/red-hat-storage/ocs-ci/blob/2b1956672bc7ec0b14f40bd249a5eff9aa8778f8/ocs_ci/utility/aws.py#L2089

Most buckets that are used in OCS-CI tests are created with a different pattern that's generated by
https://github.com/red-hat-storage/ocs-ci/blob/2b1956672bc7ec0b14f40bd249a5eff9aa8778f8/ocs_ci/helpers/helpers.py#L54-L69

and so far I couldn't find where such buckets with the `nb.` prefix are being created in OCS-CI. I'm currently waiting for a response from colleagues who might be able to shed some light on the matter.

**Comment by rabin-io** [comment]
Just to clarify things, the cluster and ODF are deployed separately via our own CI, and we run the tests against the cluster.

**Comment by shyRozen** [comment]
@rabin-io If that is the case I think you should add the commands that you mentioned in the ticket or some other cleanup in the end of the run.

**Comment by rabin-io** [comment]
@shyRozen so the buckets above are not leftovers from the tests, but from the deployment?

**Comment by sagihirshfeld** [comment]
Apparently these buckets are created by ODF/MCG as the underlying storage for the noobaa-default-backing-store when we install ODF on AWS OCP clusters:
```
$ oc get backingstore noobaa-default-backing-store -o yaml | grep -A6 awsS3                   
  awsS3:
    region: me-central-1
    secret:
      name: noobaa-aws-cloud-creds-secret
      namespace: openshift-storage
    targetBucket: nb.1683211027489.apps.shirshfe-aws0405f.qe.rh-ocs.com
  type: aws-s3
  ``` 
 Now that we know the cause, we can safely assume the prefix and postfix of these buckets and modify the cleanup pattern accordingly to accept other strings beside "apps" in between the run ID and the cluster name:
 
 ```
 f"nb\\.(\\d+)\\.?(?!\\.)(\\w*).{cluster_name}.{base_domain}"
 # (?!\\.): ensures there are no consecutive dots after the digits
 ```
 
 I'll create a PR shortly

**Comment by sagihirshfeld** [comment]
@rabin-io I suppose you're also using your own teardown implementation for the cluster? If that's the case then unfortunately this change can't fix your issue, and you'll have to add your own cleanup for the leftover that was left by MCG.

**Comment by rabin-io** [comment]
Yes, we have a teardown on the cluster level, but nothing is tracking the extra buckets used by ODF deployment, we will need to resolve this in our CI.

Thx :)
