### ISSUE TITLE
Fix getting the reboot events with vSphere IPI

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7783]
In the function `restart_nodes` in the file https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py, when checking the reboot events with vSphere IPI using the command 

> "get events -A --field-selector involvedObject.name="
                    f"{node.name},reason=Rebooted -o yaml

the reboot events before reboot are the same as after rebooting the node.
This is how the error looks in one of my local tests: 

> 12:23:57 - MainThread - ocs_ci.utility.utils - INFO  - Going to sleep for 3 seconds before next iteration
12:24:00 - MainThread - ocs_ci.ocs.platform_nodes - ERROR  - ikave-vm5-ipi413-495cf-master-0: reboot events before reboot are 0 and reboot events after reboot are 0
FAILED

**Comment by yitzhak12** [comment]
As we discussed, I am running the node restart tests without checking the reboot events, since this is not a high priority. We may continue working on this issue when we have time.

**Comment by amr1ta** [comment]
As per discussion in the sync up call we can close this issue for now and keep an eye for future runs.
