### ISSUE TITLE
Prevent cluster deployment in case a cluster with the same kerberos ID already exists

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#779]
The idea here is not to block people from deploying additional clusters when they already have one, because they can simply deploy with another name. 
In some cases, like when we hit a bug that needs further investigation with a running cluster, we would like to keep the running cluster and to deploy an additional one.

The motivation is to raise the awareness of having multiple clusters, which causes limitation issues and extra costs.

**Comment by gklein** [comment]
While this [PR](https://github.com/red-hat-storage/ocs-ci/pull/780) is already merged, is there any other work needed here or this issue can be closed?

**Comment by petr-balogh** [comment]
Do not think so :) closing
