### ISSUE TITLE
After PR 7740 / 7770 OCS deployment to non-AWS cluster is broken

### ISSUE THREAD

**Issue by schaefm-ibm** [red-hat-storage/ocs-ci#7793]
After the icsp related PRs we observe OCS deployment failing because `ocs-ci/data/pull-secret` not found. According to current doc https://ocs-ci.readthedocs.io/en/latest/getting_started.html#pull-secret this is only needed for Openshift clusters on AWS, but now for baremetal clusters, OCS deployment does no longer work. It fails in `ocs_ci/utility/utils.py`, executing the `oc image extract....` command initiated in the new `get_and_aply_icsp_from_catalog` function in `ocs_ci/deployment/deployment.py`.

**Comment by petr-balogh** [comment]
It's wrongly documented as we initially started only with AWS platform. For deployment of OCP and then continue with ODF deployment via OCS-CI it's needed for openshift installer to propagate this pull secret so we will have access to needed images. 

I've discussed with @vavuthu and what we can do is to download pull secret from existing cluster if it doesn't exist in ./data/pull-secret .

And update the doc as well accordingly.
