### ISSUE TITLE
ocs_ci.ocs.exceptions.ResourceInUnexpectedState: CSV: ocs-operator.v0.0.1 is not in expected phase: Succeeded

### ISSUE THREAD

**Issue by shreekarSS** [red-hat-storage/ocs-ci#782]
ocs-operator is taking little longer to get into Succeeded. 15 seconds after ocs_ci.ocs.exceptions.ResourceInUnexpectedState, ocs-operator.v0.0.1 got into Succeded for me. Should increase timeout

**Comment by petr-balogh** [comment]
Reopening since new update in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1757013 . 

Will try to increase the timeout and we will see, also raised the question in BZ about what is the reasonable timeout here.
