### ISSUE TITLE
MDR deployment fails with latency error

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#7823]
`ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/community/general/versions/2.4.0/': <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)>`

Failed 1/2 times. here: https://url.corp.redhat.com/21fc875

**Comment by parikshithb** [comment]
Issue is not observed again. Will reopen if seen.

**Comment by hnallurv** [comment]
ok
