### ISSUE TITLE
Configuring submariner for mdr deployments is not required. 

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#7824]
<img width="492" alt="Screenshot 2023-06-15 at 11 35 47 AM" src="https://github.com/red-hat-storage/ocs-ci/assets/16042162/8f36cece-6d5e-4999-bbd9-c0eb58566c4b">

Not sure if this is a dummy param for mdr jobs or whether actual code is ran to configure submariner. But still should be removed as this is applicable only for RDR.

**Comment by petr-balogh** [comment]
The RDR and MDR job has the same base, and then based on some conditions we can skip or add some parameters.

Probably doesn't block anything at the moment but we can for sure remove it from MDR job if it's not needed, but please open the issue in here:
https://url.corp.redhat.com/f436ffd

As it has nothing to do with ocs-ci repo.

**Comment by parikshithb** [comment]
ack
