### ISSUE TITLE
RDR Multicluster job starts test execution without deploying all ODF and DR components

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#7825]
Tried to use `Pipeline Trigger: MultiCluster RDR VSPHERE IMPORT CLUSTERS` [here](https://url.corp.redhat.com/594a50d)
and observed that the job starts executing test cases without deploying all the components.
I saw there was an error in `test_acm_import` during must-gather collection due to missing subcl binary, but after that it starts test execution without configuring submariner, ODF, DR operators, etc.
This causes all test cases to fail due to incomplete deployment and missing resources.

**Comment by petr-balogh** [comment]
This probably more belongs to jenkins job repository here:
https://url.corp.redhat.com/a2b8955

Can you rather open issue there please?
@shylesh  can you please take a look once you are back from PTO next week?
