### ISSUE TITLE
Tests in tests.e2e.kcs.test_maintenance_pod.TestMaintenancePod fails due to "Error is flags cannot be placed before plugin name: --kubeconfig" error

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#7833]
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc rook-ceph -n openshift-storage -o openshift-storage debug start rook-ceph-osd-0.
Error is flags cannot be placed before plugin name: --kubeconfig
Type: None

Runs:
https://url.corp.redhat.com/bc22c98

**Comment by mashetty330** [comment]
```python
def exec_cmd(
    cmd,
    secrets=None,
    timeout=600,
    ignore_error=False,
    threading_lock=None,
    silent=False,
    use_shell=False,
    cluster_config=None,
    **kwargs,
):
    """
    Run an arbitrary command locally

    If the command is grep and matching pattern is not found, then this function
    returns "command terminated with exit code 1" in stderr.

    Args:
        cmd (str): command to run
        secrets (list): A list of secrets to be masked with asterisks
            This kwarg is popped in order to not interfere with
            subprocess.run(``**kwargs``)
        timeout (int): Timeout for the command, defaults to 600 seconds.
        ignore_error (bool): True if ignore non zero return code and do not
            raise the exception.
        threading_lock (threading.Lock): threading.Lock object that is used
            for handling concurrent oc commands
        silent (bool): If True will silent errors from the server, default false
        use_shell (bool): If True will pass the cmd without splitting
        cluster_config (MultiClusterConfig): In case of multicluster environment this object
                will be non-null
```

**Comment by shylesh** [comment]
> ```python
> def exec_cmd(
>     cmd,
>     secrets=None,
>     timeout=600,
>     ignore_error=False,
>     threading_lock=None,
>     silent=False,
>     use_shell=False,
>     cluster_config=None,
>     **kwargs,
> ):
>     """
>     Run an arbitrary command locally
> 
>     If the command is grep and matching pattern is not found, then this function
>     returns "command terminated with exit code 1" in stderr.
> 
>     Args:
>         cmd (str): command to run
>         secrets (list): A list of secrets to be masked with asterisks
>             This kwarg is popped in order to not interfere with
>             subprocess.run(``**kwargs``)
>         timeout (int): Timeout for the command, defaults to 600 seconds.
>         ignore_error (bool): True if ignore non zero return code and do not
>             raise the exception.
>         threading_lock (threading.Lock): threading.Lock object that is used
>             for handling concurrent oc commands
>         silent (bool): If True will silent errors from the server, default false
>         use_shell (bool): If True will pass the cmd without splitting
>         cluster_config (MultiClusterConfig): In case of multicluster environment this object
>                 will be non-null
> ```
> 
> `cluster_config (MultiClusterConfig): In case of multicluster environment this object will be non-null` this is not true. Its a non null object even when the cluster is not multicluster

If its not a multicluster env then I don't think caller should pass the cluster_config object , because we will be operating default context which is single cluster.

**Comment by mashetty330** [comment]
> > ```python
> > def exec_cmd(
> >     cmd,
> >     secrets=None,
> >     timeout=600,
> >     ignore_error=False,
> >     threading_lock=None,
> >     silent=False,
> >     use_shell=False,
> >     cluster_config=None,
> >     **kwargs,
> > ):
> >     """
> >     Run an arbitrary command locally
> > 
> >     If the command is grep and matching pattern is not found, then this function
> >     returns "command terminated with exit code 1" in stderr.
> > 
> >     Args:
> >         cmd (str): command to run
> >         secrets (list): A list of secrets to be masked with asterisks
> >             This kwarg is popped in order to not interfere with
> >             subprocess.run(``**kwargs``)
> >         timeout (int): Timeout for the command, defaults to 600 seconds.
> >         ignore_error (bool): True if ignore non zero return code and do not
> >             raise the exception.
> >         threading_lock (threading.Lock): threading.Lock object that is used
> >             for handling concurrent oc commands
> >         silent (bool): If True will silent errors from the server, default false
> >         use_shell (bool): If True will pass the cmd without splitting
> >         cluster_config (MultiClusterConfig): In case of multicluster environment this object
> >                 will be non-null
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `cluster_config (MultiClusterConfig): In case of multicluster environment this object will be non-null` this is not true. Its a non null object even when the cluster is not multicluster
> 
> If its not a multicluster env then I don't think caller should pass the cluster_config object , because we will be operating default context which is single cluster.

@shylesh caller is not passing cluster_config object. please check the block of code below:
```python
    def debug_start(self, deployment_name, alternate_image=None, timeout=800):
        """
        This starts the debug mode for the deployment

        Args:
            deployment_name (str): Name of the deployment that you want
            it to be in debug mode i.e, either Mon or OSD deployments

            alternate_image (str): Alternate image that you want to pass

        Returns:
              True: if debug start is successful

        """

        if deployment_name in self.deployment_in_debug.keys():
            raise Exception(
                f"[Error] Deployment {deployment_name} seems to be already in debug mode!"
            )

        command = self.cmd
        command += f" debug start {deployment_name}"
        if alternate_image:
            self.alternate_image = alternate_image
            command += f" --alternate-image {self.alternate_image}"
        OCP().exec_oc_cmd(command=command, timeout=timeout, out_yaml_format=False)
        logger.info(f"{deployment_name} is successfully in mainetenance mode now!")

```
