### ISSUE TITLE
Some MCG tests are failing in Proxy deployments while connecting external endpoints or resources

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#7853]
In 4.13 proxy deployments, we have seen many MCG test failures especially when we need to connect to external endpoints or resources:

https://url.corp.redhat.com/93fa6c6
https://url.corp.redhat.com/93888cc
https://url.corp.redhat.com/2c7ca2c

**Comment by sagihirshfeld** [comment]
The [last proxy run](https://url.corp.redhat.com/710538a) from two months ago also had this issue, so unfortunately it still requires a fix

**Comment by sagihirshfeld** [comment]
A new form of this issue was found in https://url.corp.redhat.com/5b85ebb:
