### ISSUE TITLE
Allow nodes related tests to be executed on any type of platform

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#788]
This could be achieved by having an abstract layer for platform nodes to be called from the test/setup so a specific platform type (AWS, VMWare, etc.) will be initialized and used.

**Comment by ebenahar** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/789

**Comment by gklein** [comment]
Given that this [PR](https://github.com/red-hat-storage/ocs-ci/pull/789) is now merged, is there any extra work needed on this issue?

**Comment by ebenahar** [comment]
Right, closing
