### ISSUE TITLE
RDR Multicluster Job test results report doesn't contain version details for all components

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#7904]
Test results report generated when running tests via Regional DR MultiCluster Job doesn't contain version details about following components:

From Hub cluster:
- Openshift DR Hub Operator
- ODF Multicluster Orchestrator
- RHACM
- GitOps

From Managed clusters:
- Openshift DR Cluster Operator
- Submariner
- VolSync
- GitOps
- OADP

One such report generated during tier1 run: https://url.corp.redhat.com/33c3704

**Comment by petr-balogh** [comment]
DR operator version - for MDR - multicluster orchestrator

**Comment by petr-balogh** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/9956 got merged, closing
