### ISSUE TITLE
Run OCP and ODF must gather in parallel for all ocs-ci tests

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#7960]

**Comment by am-agrawa** [comment]
Assigning to Elad as per discussion in Brown squad syncup.

**Comment by ebenahar** [comment]
@ebenahar reminder to myself to update / implement the change

**Comment by shylesh** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/1034

**Comment by shylesh** [comment]
Addressed in the PR https://github.com/red-hat-storage/ocs-ci/pull/1034
