### ISSUE TITLE
Check searching for already existing clusters with the same prefix fails when old cluster has been just  destroyed

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#798]
When I execute a teardown a cluster and then immediately deploy a new one, new check searching for already existing clusters with the same prefix fails:

```
E               ocs_ci.ocs.exceptions.SameNamePrefixClusterAlreadyExistsException: Cluster with name prefix mbukatov* already exists. Please destroy the existing cluster for a new cluster deployment
```

**Comment by ebenahar** [comment]
@mbukatov we can check for the status of the instances and in case they are 'Terminating', allow deployment. WDYT?

**Comment by mbukatov** [comment]
@ebenahar That could help.
