### ISSUE TITLE
Templating dirs

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#80]
Right now we have every yaml in "templates/ocs-deployment", based on the classes we need to separate the deployment yaml's from other class based yaml's so that organization is clear.

**Comment by clacroix12** [comment]
Are there specific yaml templates in `templates/ocs-deployment` that we want to move out? I thought the idea of having the `ocs-deployment` directory was to do exactly this.

**Comment by vasukulkarni** [comment]
@clacroix12 the deployment yamls can go there, but PV/Filesystem etc and other test operation related  should be kept outside deployment templates.

**Comment by clacroix12** [comment]
I agree. We should identify which yaml templates do not belong under `ocs-deployment` and come up with a directory structure for templates that makes sense.

**Comment by RazTamir** [comment]
+1 on that,
We can create new dir under templates for other resources (e.g. PersistentVolumes/pv.yaml)

**Comment by petr-balogh** [comment]
This was my initial plan, I created directory for ocs-deployment just for templates related to deployment test.

**Comment by clacroix12** [comment]
Are there any templates under `ocs-deployment` that we need to relocate or can we close this as it seems like we're already have a plan to organize templates accordingly.

**Comment by vasukulkarni** [comment]
@clacroix12 I will keep this open for few days, I see PR's coming in with yaml's and checking the directory, I see the need to reorganize them.

**Comment by clacroix12** [comment]
@vasukulkarni Looks like we addressed this in #164 can we close this?

**Comment by vasukulkarni** [comment]
Thanks Closing
