### ISSUE TITLE
Message: ocs_ci.ocs.exceptions.CommandFailed: FIO execution results: . while the execution of "test_rbd_space_reclaim"

### ISSUE THREAD

**Issue by keemano** [red-hat-storage/ocs-ci#8078]
Message: ocs_ci.ocs.exceptions.CommandFailed: FIO execution results: .
Type: None

Text:
self = <test_rbd_space_reclaim.TestRbdSpaceReclaim object at 0x7f00416d69a0>

@polarion_id("OCS-2741")
@tier1
@skipif_external_mode
@skipif_managed_service
def test_rbd_space_reclaim(self):
    """
    Test to verify RBD space reclamation

    Steps:
    1. Create and attach RBD PVC of size 25 GiB to an app pod.
    2. Get the used size of the RBD pool
    3. Create two files of size 10GiB
    4. Verify the increased used size of the RBD pool
    5. Delete one file
    6. Create ReclaimSpaceJob
    7. Verify the decreased used size of the RBD pool

    """

    pvc_obj = self.pvc[0]
    pod_obj = self.pod[0]

    fio_filename1 = "fio_file1"
    fio_filename2 = "fio_file2"

    # Fetch the used size of pool
    cbp_name = self.sc_obj.get().get("parameters").get("pool")
    used_size_before_io = fetch_used_size(cbp_name)
    log.info(f"Used size before IO is {used_size_before_io}")

    # Create two 10 GB file
    for filename in fio_filename1, fio_filename2:
        pod_obj.run_io(
            storage_type="fs",
            size="10G",
            runtime=120,
            fio_filename=filename,
            end_fsync=1,
        )

      pod_obj.get_fio_results()

tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py:95: 

self = <ocs_ci.ocs.resources.pod.Pod object at 0x7f0041815400>, timeout = 600

def get_fio_results(self, timeout=FIO_TIMEOUT):
    """
    Get FIO execution results

    Returns:
        dict: Dictionary represents the FIO execution results

    Raises:
        Exception: In case of exception from FIO
    """
    logger.info(f"Waiting for FIO results from pod {self.name}")
    try:
        result = self.fio_thread.result(timeout)
        if result:
            return yaml.safe_load(result)

      raise CommandFailed(f"FIO execution results: {result}.")
E           ocs_ci.ocs.exceptions.CommandFailed: FIO execution results: .

ocs_ci/ocs/resources/pod.py:147: CommandFailed

2023-07-19 17:51:51

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/493/12897/590964/591195/591196/log
jenkins - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/8398/

**Comment by paraggit** [comment]
Seen Same Issue on RUN: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/13848/629888/630091/630093/log?logParams=history%3D630093%26page.page%3D1

**Comment by jilju** [comment]
Reproduced in another test test_change_reclaim_policy_of_pv[CephBlockPool-Delete]
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/15199/707492/707668/707669/log

**Comment by yitzhak12** [comment]
I also had a similar error with the GCP platform: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/6242/testReport/tests.manage.z_cluster.nodes.test_worker_nodes_network_failures/TestWorkerNodesFailure/test_all_worker_nodes_short_network_failure_CephFileSystem_/
