### ISSUE TITLE
Replace ClusterLoad FIO image and increase the FIO file size

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#8087]
@prsurve"
```We might need to look for image that's available in quay as we might get rate limit also the image is 8 year old```

I will look for alternatives

Increase the FIO file size:
https://github.com/red-hat-storage/ocs-ci/pull/7604/files#r1268136511

**Comment by prsurve** [comment]
I checked on the image it only supports `amd64` platform . I can create a new image with multi-arch if required

**Comment by prsurve** [comment]
I have created container image's here https://url.corp.redhat.com/6c30bf9
