### ISSUE TITLE
cherrypick pr 7592 to older versions

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#8088]
https://github.com/red-hat-storage/ocs-ci/pull/7592

**Comment by DanielOsypenko** [comment]
I think this is related: https://github.com/red-hat-storage/ocs-ci/issues/8081

**Comment by DanielOsypenko** [comment]
added PR #8090

**Comment by DanielOsypenko** [comment]
added PRs https://github.com/red-hat-storage/ocs-ci/pull/8090 and https://github.com/red-hat-storage/ocs-ci/pull/8092 and https://github.com/red-hat-storage/ocs-ci/pull/8093 ---> Done
