### ISSUE TITLE
Validate OCS pods backed by PVC post cluster deployment

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#810]
In order to spot cases like reported in https://bugzilla.redhat.com/show_bug.cgi?id=1754786, we should validate that OCS pods like mons, osds, noobaa and others, are indeed backed by a PVC

**Comment by ebenahar** [comment]
Here is an example for the PVCs that should back the pods:

NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
example-deviceset-0-zph7h     Bound    pvc-02fb1c5e-dde3-11e9-818d-069cd11d2536   100Gi      RWO            gp2                  22h
example-deviceset-1-s8n9n     Bound    pvc-02fce869-dde3-11e9-818d-069cd11d2536   100Gi      RWO            gp2                  22h
example-deviceset-2-p7s4g     Bound    pvc-02fea1f0-dde3-11e9-818d-069cd11d2536   100Gi      RWO            gp2                  22h
logdir-noobaa-core-0          Bound    pvc-a3c92938-dde2-11e9-8e0e-0a63c11b0c34   10Gi       RWO            rook-ceph-ceph-rbd   22h
mongo-datadir-noobaa-core-0   Bound    pvc-a3c3d7b3-dde2-11e9-8e0e-0a63c11b0c34   50Gi       RWO            rook-ceph-ceph-rbd   22h
rook-ceph-mon-a               Bound    pvc-b935e399-dde2-11e9-818d-069cd11d2536   10Gi       RWO            gp2                  22h
rook-ceph-mon-b               Bound    pvc-bc50de98-dde2-11e9-818d-069cd11d2536   10Gi       RWO            gp2                  22h
rook-ceph-mon-c               Bound    pvc-bf50aa2b-dde2-11e9-818d-069cd11d2536   10Gi       RWO            gp2                  22h

**Comment by ebenahar** [comment]
We can create a new method in cluster.py and call it from below this line https://github.com/red-hat-storage/ocs-ci/blob/cb1f775a6365ab3d2892edb60d353ef721aad239/ocs_ci/deployment/deployment.py#L384

**Comment by nehaberry** [comment]
Taking this UP. Will try to send first PR tomorrow for review.

**Comment by nehaberry** [comment]
@ebenahar For nooba pods, nooba-core takes long enough time to come to running state, so either we have to wait for the both nooba pods to be up and then validate OR we can just test mon and osds for now.

Please share your views.

**Comment by ebenahar** [comment]
@nehaberry I guess noobaa-core is required for running our noobaa tests. @MeridianExplorer @parikshithb, please confirm. If not, can we add a test for validating its state?
If this is the case, we can skip its validation and in case this pod is in a problematic state, we'll spot that by the noobaa test failure

**Comment by nehaberry** [comment]
Did not add check for nooba yet as we are not aware of its actual usage.

@parikshithb won't nooba with AWS S3 bucket be used for OCS 4.2 ? In that case, whats the use of nooba pods and PVCs to be backed by ceph for AWS IPI ?
