### ISSUE TITLE
Update test_detach_attach_worker_volume and test_detach_attach_2_data_volumes for IBM

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#8117]
Both the tests need to be first manually executed to understand the behaviour and then adjust it for regression runs.
The chances are that the re-attachment of disks could be slower when compared to that of AWS, and thus more timeout would be needed.

RP- https://url.corp.redhat.com/abc391a

Relevant discussion- https://redhat-internal.slack.com/archives/CUEMQ631C/p1690523423044569

**Comment by am-agrawa** [comment]
This failure is consistent- https://url.corp.redhat.com/fa47803
ODF 4.12.8-2

**Comment by ebenahar** [comment]
The test is now disabled on IBM Cloud. Closing
