### ISSUE TITLE
Separate worker nodes for workloads 

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#813]
@ramkiperiy brought this point in todays meeting,  We need separate worker nodes(non ocs) and should be running the fio/sql/etc and all client workloads on those pods.  I haven't seen anything in the document on how to setup using cli but is quite important to fix this asap.

**Comment by vasukulkarni** [comment]
@ramkiperiy FYI

**Comment by petr-balogh** [comment]
@ramkiperiy @vasukulkarni as I promised here is the [example](https://github.com/red-hat-storage/ocs-ci/pull/874) of the config with you will achieve this.
Basically for OCS you will label and taint some amount of nodes to be used by OCS, and the rest will be used for workload (non OCS nodes). So I guess nothing else needs to be done here as it's already possible to do that.  So we can close this, we don't have to merge the PR above or we can do as an example.
