### ISSUE TITLE
`test_public_website` fails with AccessDenied due to a race condition

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#8156]
The attempt to use `s3_get_object` on the bucket by the unprivileged accounts is made too soon after the appliance of the bucket policy that's supposed to make it publicly accessible.

According to the devs, waiting a few seconds for the change to get processed by MCG should fix this.

**Comment by sagihirshfeld** [comment]
The test still fails with the same issue on all versions. If waiting a few more seconds won't fix this, we should reopen the original BZ.

**Comment by udaysk23** [comment]
The Test is still failing on latest build. Reopening this issue again 
RP link: https://url.corp.redhat.com/ab3e379

**Comment by sagihirshfeld** [comment]
> The Test is still failing on latest build. Reopening this issue again RP link: https://url.corp.redhat.com/ab3e379

This run used the release-4.13 OCS-CI branch so it didn't use the fix #8477. Since it was merged on September 27th it looks like this issue didn't occur on 4.14 that uses the master branch ([last 4.14 failure](https://url.corp.redhat.com/0892ed6) was on Sept 24th).

I'll create the backport PRs and close this issue once they're merged.

**Comment by sagihirshfeld** [comment]
Closing this since the PRs have been merged.
