### ISSUE TITLE
Cluster with name prefix ocs* already exists when not passing --cluster-name

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#820]
I am attempting to execute a deployment without passing `--cluster-name` and therefore using the default constructed `cluster_name`. I am seeing the below Exception being raised, apparently due to the prefix `ocs*` already being used.

By default `cluster_name = f"ocs-ci-{getuser()[:8]}"`. This entire string should be used to find non-terminated instances and not just `ocs`. As it currently works, if there is a cluster up and running in AWS that used the default `cluster_name`, no one will be able to execute a deployment using the default `cluster_name`. 

```
self = <ocs_ci.deployment.aws.AWSIPI object at 0x10b6ea908>, log_cli_level = 'INFO'

    def deploy_ocp(self, log_cli_level='DEBUG'):
        """
        Deployment specific to OCP cluster on this platform

        Args:
            log_cli_level (str): openshift installer's log level
                (default: "DEBUG")
        """
        if not config.DEPLOYMENT.get('force_deploy_multiple_clusters'):
            cluster_name = config.ENV_DATA['cluster_name']
            prefix = cluster_name.split("-")[0] + '*'
            if self.check_cluster_existence(prefix):
                raise SameNamePrefixClusterAlreadyExistsException(
>                   f"Cluster with name prefix {prefix} already exists. "
                    f"Please destroy the existing cluster for a new cluster deployment"
                )
E               ocs_ci.ocs.exceptions.SameNamePrefixClusterAlreadyExistsException: Cluster with name prefix ocs* already exists. Please destroy the existing cluster for a new cluster deployment

ocs_ci/deployment/aws.py:151: SameNamePrefixClusterAlreadyExistsException
```

**Comment by dahorak** [comment]
I think, it will be better to change the default cluster name - put the username at the beginning.

**Comment by gklein** [comment]
In order to elimination any collisions and human errors,  wouldn't it make sense to remove the default cluster name from the code and make it a mandatory argument to be provided by each user?

**Comment by petr-balogh** [comment]
@andrewschoen @zmc  do you pass in your automation the cluster name or using the default?

**Comment by zmc** [comment]
@petr-balogh We set the cluster name - configs are available in each build's artifacts
