### ISSUE TITLE
Move running commands from ceph-tool-box to monitor

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#821]
This came up in https://bugzilla.redhat.com/show_bug.cgi?id=1755187#c15

so 
a) Either use the steps to deploy toolbox on top of our operator
b) Move to ceph-mon to execute commands, but something is missing on those monitor nodes which needs to be looked into

**Comment by petr-balogh** [comment]
Commented here: https://github.com/red-hat-storage/ocs-ci/pull/823/files#r328521698

We should take rook image dynamically and not from config as when deploying via operator only one version we should use is REGISTRY_IMAGE and the rest of the versions are taken from CSV.
