### ISSUE TITLE
Don't use project switching in ocs-ci code, 

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#822]
Right now, we are using feature of `oc` command (which ocs-ci uses to perform most of ocp related actions) which allows one to specify a default project which is used if no project or namespace is specified to a oc command from the command line. This is a useful, syntactic sugar for humans.

But it doesn't make any sense to use it in automated tests, for the following reasons:

- log lines with oc commands doesn't contain full information, one needs to check what project/namespace has the test switched to previously
- we are introducing additional hidden state (of oc command) which we need to track in ocs-ci code anyway (to prevent running commands in a wrong namespace)
- this is error prone (eg. when something breaks either in product or ocs-ci)
- for the reasons listed above, it has a potential of increasing cost of debugging

On the other hand, I see no added value of using project/namespace switching approach. Quite the contrary, because we had to implement additional plumbing code in ocs-ci to make it work.

**Comment by RazTamir** [comment]
I'm not sure I understand where the issue is.
We have the option to:
1) switch to a different namespace
and we have the option to:
2)"specify a default project which is used if no project or namespace is specified to a oc command from the command line"

Which one is it?

**Comment by mbukatov** [comment]
> Which one is it?

Neither. We should explicitly specify a project/namespace every time we need so for a `oc` command, without relaying on command line sugar feature of an "implicit" namespace.

**Comment by RazTamir** [comment]
Ah, so when executing oc command we need to ensure to pass -n <namespace>.

regarding the title - switching to the default project is still needed as when you create a new project, sometimes you are using 'oc new-project' which create and switch to the new project

**Comment by gklein** [comment]
It make sense to me to always prefer explicit namespaces for automated tests.

I've tried to map the work needed and mainly found, switch_to_project()  (2 times) which is only used by an helper method, switch_to_default_rook_cluster_project() (9 times).

```
▶ ack -hc "switch_to_project"
2
▶ ack -hc "switch_to_default_rook_cluster_project"
9
```

Are you aware of any other areas namespace switching may occur in the code?
