### ISSUE TITLE
run-ci does not work on aws-machine.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#827]
This used to work on aws in the past.  It still works on my laptop.

> (venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ 
> (venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ ls /home/ec2-user/wusui
> ls: cannot access '/home/ec2-user/wusui': No such file or directory
> (venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ run-ci -m deployment --cluster-conf conf/ocs_basic_install.yml --cluster-name wusui-name-i-never-used-before-ever --cluster-path /home/ec2-user/wusui tests/ --deploy
> The kubeconfig file /home/ec2-user/wusui/auth/kubeconfig doesn't exist!
> ============================= test session starts ==============================
> platform linux -- Python 3.6.8, pytest-5.1.3, py-1.8.0, pluggy-0.13.0
> rootdir: /home/ec2-user/ocs-ci, inifile: pytest.ini
> plugins: reportportal-1.0.5, logger-0.5.1, metadata-1.8.0, html-2.0.0, marker-bugzilla-0.9.3
> collecting ... 
> ----------------------------- live log collection ------------------------------
> 20:14:48 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get Node  --selector=node-role.kubernetes.io/worker -o yaml
> collected 183 items / 182 deselected / 1 selected                              
> 
> tests/ecosystem/deployment/test_deployment.py::test_deployment 
> -------------------------------- live log setup --------------------------------
> 20:14:48 - MainThread - tests.conftest - INFO - All logs located at /tmp/ocs-ci-logs-1569528887
> 20:14:48 - MainThread - ocs_ci.deployment.factory - INFO - Deployment key = aws_ipi
> 20:14:48 - MainThread - ocs_ci.deployment.factory - INFO - Current deployment platform: aws,deployment type: ipi
> 20:14:48 - MainThread - ocs_ci.utility.utils - INFO - Downloading openshift client (4.2.0-0.nightly-2019-09-25-233506).
> 20:14:52 - MainThread - ocs_ci.utility.utils - INFO - Executing command: tar xzvf openshift-client.tar.gz oc kubectl
> 20:14:53 - MainThread - ocs_ci.utility.utils - INFO - Executing command: /home/ec2-user/ocs-ci/bin/oc version
> 20:14:53 - MainThread - ocs_ci.utility.utils - INFO - OpenShift Client version: Client Version: openshift-clients-4.2.0-201909221318
> 20:14:53 - MainThread - ocs_ci.ocs.openshift_ops - INFO - Testing access to cluster with /home/ec2-user/wusui/auth/kubeconfig
> 20:14:53 - MainThread - ocs_ci.ocs.openshift_ops - WARNING - The kubeconfig file /home/ec2-user/wusui/auth/kubeconfig doesn't exist!
> 20:14:53 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
> 20:14:53 - MainThread - ocs_ci.deployment.aws - ERROR - Non terminated EC2 instances with the same name prefix were found: ['i-0b16b2a1cbec1b425', 'i-041fe2dfe5b32dbba', 'i-04bf2f2ea4c02faaf', 'i-04313d6b772c2119a', 'i-096dcaad10f8700e2', 'i-08aeaf5a7be73cf96', 'i-00cb5492fb274e90d']
> ERROR                                                                    [100%]
> 
> ==================================== ERRORS ====================================
> ______________________ ERROR at setup of test_deployment _______________________
> 
> request = <SubRequest 'cluster' for <Function test_deployment>>
> log_cli_level = 'INFO'
> 
>     @pytest.fixture(scope="session", autouse=True)
>     def cluster(request, log_cli_level):
>         """
>         This fixture initiates deployment for both OCP and OCS clusters.
>         Specific platform deployment classes will handle the fine details
>         of action
>         """
>         log.info(f"All logs located at {ocsci_log_path()}")
>     
>         teardown = config.RUN['cli_params']['teardown']
>         deploy = config.RUN['cli_params']['deploy']
>         factory = dep_factory.DeploymentFactory()
>         deployer = factory.get_deployment()
>     
>         # Add a finalizer to teardown the cluster after test execution is finished
>         if teardown:
>             def cluster_teardown_finalizer():
>                 deployer.destroy_cluster(log_cli_level)
>             request.addfinalizer(cluster_teardown_finalizer)
>             log.info("Will teardown cluster because --teardown was provided")
>     
>         # Download client
>         force_download = (
>             config.RUN['cli_params'].get('deploy')
>             and config.DEPLOYMENT['force_download_client']
>         )
>         get_openshift_client(force_download=force_download)
>     
>         if deploy:
>             # Deploy cluster
> >           deployer.deploy_cluster(log_cli_level)
> 
> tests/conftest.py:712: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ocs_ci/deployment/deployment.py:67: in deploy_cluster
>     self.deploy_ocp(log_cli_level)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <ocs_ci.deployment.aws.AWSIPI object at 0x7ff637b28828>
> log_cli_level = 'INFO'
> 
>     def deploy_ocp(self, log_cli_level='DEBUG'):
>         """
>         Deployment specific to OCP cluster on this platform
>     
>         Args:
>             log_cli_level (str): openshift installer's log level
>                 (default: "DEBUG")
>         """
>         if not config.DEPLOYMENT.get('force_deploy_multiple_clusters'):
>             cluster_name = config.ENV_DATA['cluster_name']
>             prefix = cluster_name.split("-")[0] + '*'
>             if self.check_cluster_existence(prefix):
>                 raise SameNamePrefixClusterAlreadyExistsException(
> >                   f"Cluster with name prefix {prefix} already exists. "
>                     f"Please destroy the existing cluster for a new cluster deployment"
>                 )
> E               ocs_ci.ocs.exceptions.SameNamePrefixClusterAlreadyExistsException: Cluster with name prefix wusui* already exists. Please destroy the existing cluster for a new cluster deployment
> 
> ocs_ci/deployment/aws.py:151: SameNamePrefixClusterAlreadyExistsException
> ======================= 182 deselected, 1 error in 5.91s =======================
> sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=12, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.0.0.180', 39488), raddr=('52.95.16.2', 443)>
> sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.0.0.180', 39490), raddr=('52.95.16.2', 443)>
> (venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ ls /home/ec2-user/wusui
> (venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ ls -lsd !$
> ls -lsd /home/ec2-user/wusui
> 0 drwxrwxr-x. 2 ec2-user ec2-user 6 Sep 26 20:14 /home/ec2-user/wusui
> (venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ 
> 
(venv) [ec2-user@ip-10-0-0-180 ocs-ci]$ 

Upon further review,  it appears that there is a search for  a cluster with the prefix wusui.  I have a cluster up named wusui-ocs-cluster-n7-...   Apparently the existence of this cluster is messing up run-ci because the following command seemed to get farther:

> run-ci -m deployment --cluster-conf conf/ocs_basic_install.yml --cluster-name foo-name-
> i-never-used-before-ever-cmhahtd --cluster-path /home/ec2-user/aardvark tests/ --deploy

Note -- my cluster here starts with foo.

**Comment by clacroix12** [comment]
@wusui this is intentional to stop people from accidentally deploying multiple clusters to AWS. See #780

**Comment by wusui** [comment]
So if I start another cluster I just need to make sure that it starts with a different name than another cluster that I have up.
