### ISSUE TITLE
Data reduction is insufficient in test_mcg_data_deduplication[AWS-OC-1]

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#8274]
Test case failed due to AssertionError: Data reduction is insufficient
Logs: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/13495/617229/617357/617366/log

Message: AssertionError: Data reduction is insufficient. 2454 bytes reduced out of 90363194.
Type: None
Text:
self = <ocs_ci.ocs.resources.mcg.MCG object at 0x7fa154d0f0d0>
bucketname = 'oc-bucket-b925afafb15143539616635af90bc6'
expected_reduction_in_bytes = 90363194

def check_data_reduction(self, bucketname, expected_reduction_in_bytes):
    """
    Checks whether the data reduction on the MCG server works properly
    Args:
        bucketname: An example bucket name that contains compressed/deduped data
        expected_reduction_in_bytes: amount of data that is supposed to be reduced after data
        compression and deduplication.

    Returns:
        bool: True if the data reduction mechanics work, False otherwise

    """

    def _retrieve_reduction_data():
        resp = self.send_rpc_query(
            "bucket_api", "read_bucket", params={"name": bucketname}
        )
        bucket_data = resp.json().get("reply").get("data").get("size")
        bucket_data_reduced = (
            resp.json().get("reply").get("data").get("size_reduced")
        )
        logger.info(
            "Overall bytes stored: "
            + str(bucket_data)
            + ". Reduced size: "
            + str(bucket_data_reduced)
        )

        return bucket_data, bucket_data_reduced
-----------
    try:

      for total_size, total_reduced in TimeoutSampler(
            140, 5, _retrieve_reduction_data
        ):
assert False, (
            "Data reduction is insufficient. "
            f"{total_size - total_reduced} bytes reduced out of {expected_reduction_in_bytes}."
        )
E           AssertionError: Data reduction is insufficient. 2454 bytes reduced out of 90363194.

**Comment by udaysk23** [comment]
Test case seems passing on latest version
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/603/14749/680290/680422

**Comment by tiffanyn108** [comment]
Still see the issue on ODF4.13 automation run: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/15474/723940/724066/724081/log
