### ISSUE TITLE
Need a function to automatically determine ceph tool box pod name and send ceph commands

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#83]
While writing test cases, We may have to run ceph commands to get to know something about the ceph cluster - health, size, pools, etc. So in our test framework, I expect a function I can call and this will internally go find the ceph toolbox pod's name, convert it into 'oc exec <tool-box> <cmd>' and give me the output in json format which can be parsed.

**Comment by RazTamir** [comment]
Taking this FRE

**Comment by RazTamir** [comment]
@keesturam , please provide a sample flow of executing a basic command so I will be able to test:
- How can I determine the pod holds the ceph-tool-box?
- how can I connect to it? (oc rsh?) not sure what is the command
- what command to execute once connected to the pod?

**Comment by keesturam** [comment]
1) oc get pods and grep for pods with name 'ceph-tools'
2) run the command 'oc rsh -n <name_space> <toolbox_name> <ceph command> --format pretty-json'
For eg., 'rsh -n rook-ceph rook-ceph-tools-78db69f57c-hz6df ceph -s --format pretty-json' 
The command should be dynamic. i.e., Test author should have the flexibility to send any ceph command. 
3) function to return the json value

pls let me know if this is clear or I should give more info.

**Comment by RazTamir** [comment]
regarding (2):
'rsh -n rook-ceph rook-ceph-tools-78db69f57c-hz6df ceph -s --format pretty-json <command for ceph goes here?>'

**Comment by keesturam** [comment]
> regarding (2):
> 'rsh -n rook-ceph rook-ceph-tools-78db69f57c-hz6df ceph -s --format pretty-json <command for ceph goes here?>'
ah, my bad. it goes after the toolbox name.
 'oc rsh -n <name_space> <toolbox_name> <ceph_comand> --format pretty-json'

**Comment by RazTamir** [comment]
Thanks!
Any availability from @ebenahar to implement this as this already demonstrated in the live session today?
(I can take care of it as well, just let me know)

**Comment by ebenahar** [comment]
@RazTamir @keesturam yes, I can take it from here

**Comment by clacroix12** [comment]
@RazTamir isn't this going to be covered by our OCS cluster object? I don't see the value in having a separate function to handle retrieving the tools pod when we are trying to capture the entire cluster in objects which can be used for this purpose.

**Comment by RazTamir** [comment]
@clacroix12 , yeah I this will be implemented in OCS cluster object.
@ebenahar thoughts?

**Comment by shylesh** [comment]
We already have a way to do this but may not be well polished. https://github.com/red-hat-storage/ocs-ci/blob/master/tests/test_pod_exec.py . Also there is scope for improvement.

**Comment by shylesh** [comment]
Also, just to iterate on future scope of this kind of functionality, usually there could be necessity to run commands on mons, osds, clients broadly I can say based on roles. 
From cluster objects you should be able to extract pod object based on roles like 
```client1 =cluster.get_pod(role)``` and run command on this like ```client1.execute_command(cmd)```.

Also I see a need to run commands on application pods where PVs or CephFS volumes will be attached. Of course this one is possible as of now just that you need to figure out pod name based on selectors and create a pod object rest should work as per the example I pointed out. ```app_pod.execute_command(cmd="mountpoint -q /mnt/foo") ``` to check whether mount point exists or something like that.

**Comment by ebenahar** [comment]
Thanks @shylesh, test_pod_exec.py could be enhanced probably to be suitable for all these purposes.

@clacroix12 @RazTamir The implementation will be along with https://github.com/red-hat-storage/ocs-ci/issues/84

**Comment by RazTamir** [comment]
@shylesh , BTW, I think the functionality of pods in openshift_ops should move to /ocs/pod.py

**Comment by RazTamir** [comment]
@ebenahar just 1 comment about https://github.com/red-hat-storage/ocs-ci/issues/83#issuecomment-494912409 --> test_pod_exec.py is a test not a functionality

**Comment by ebenahar** [comment]
@RazTamir right :) 
will convert it

**Comment by ebenahar** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/94

**Comment by ebenahar** [comment]
@keesturam Here is an example for a Ceph command execution:

INFO:utility.utils:Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ocs-ci-ebenahar-63293/auth/kubeconfig rsh rook-ceph-tools-75867b94fc-nqj9q ceph status --format json-pretty
2019-05-25 01:47:39,003 - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ocs-ci-ebenahar-63293/auth/kubeconfig rsh rook-ceph-tools-75867b94fc-nqj9q ceph status --format json-pretty
DEBUG:utility.utils:CMD output: 
{
    "fsid": "bdb9367c-495e-405a-8677-7fe82e323065",
    "health": {
        "checks": {},
        "status": "HEALTH_OK"
    },
    "election_epoch": 12,
...

**Comment by keesturam** [comment]
Thanks @ebenahar This is what I had written for my test case. 

`
def ceph_storage_capacity(ceph_tools_pod):
    pods = run_cmd(f'oc rsh -n openshift-storage {ceph_tool} ceph status --format json')
    pods_json = json.loads(pods)
    avail_cap = pods_json['pgmap']['bytes_total']
    avail_cap_gb = avail_cap/(1024*1024*1024)
    return avail_cap_gb

def find_cephtool():
    v1_pods = dyn_client.resources.get(api_version='v1', kind='Pod')
    out = v1_pods.get(namespace='openshift-storage', label_selector='app=rook-ceph-tools')
    return out['items'][0]['metadata']['name']
`

**Comment by ebenahar** [comment]
@keesturam Great! 
I didn't use the label selector, if you don't mind, I'll use it in my next commit for https://github.com/red-hat-storage/ocs-ci/pull/94 :)

**Comment by keesturam** [comment]
> @keesturam Great!
> I didn't use the label selector, if you don't mind, I'll use it in my next commit for #94 :)

I'm glad that you found it useful.

**Comment by RazTamir** [comment]
@keesturam @ebenahar we already have this right?
Can we close?

**Comment by ebenahar** [comment]
@RazTamir @keesturam Closing
