### ISSUE TITLE
test_create_new_project_to_verify_logging is failing on 4.14

### ISSUE THREAD

**Issue by vkathole** [red-hat-storage/ocs-ci#8317]
RP : https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/13691/624086/624106/624107/log

 ```
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-logging delete ClusterLogging instance.
Error is error: the server doesn't have a resource type "ClusterLogging"
```

**Comment by PrasadDesala** [comment]
The issue could be temporary; the test ran successfully without any issues or errors when executed locally on the 4.14 BM cluster.
Hence, closing this issue.
