### ISSUE TITLE
test_cephfs_capacity_workload_alerts fails, test missed CephClusterNearFull alert

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#8323]
After filling up to near 90% and having 266734186496 bytes (266 Gb)  we already got a CephClusterNearFull and CephClusterCriticallyFull, but workload_fio_storageutilization started a new fio job attempting to fill up 77 Gb more (why 77 GB?)
and during this operation CephClusterNearFull and CephClusterCriticallyFull has not been captured, because they where firing before this operation and the second operation 

19:36:28 - MainThread - ocs_ci.ocs.fiojob - INFO  - 77 Gi of 77 Gi (PVC size) seems already reclaimed
19:37:03 - MainThread - ocs_ci.ocs.fiojob - INFO  - Storage for the PVC was at least 90% reclaimed.

after this line test Finished with Failure

E       AssertionError: Incorrect number of CephClusterNearFull alerts (0 instead of 2 with states: ['pending', 'firing']).
E       Alerts: []
 
-------------

Debug log 
[part 1](http://pastebin.test.redhat.com/1107912)
[part 2](http://pastebin.test.redhat.com/1107913)

CephClusterNearFull -Warning missed

![image](https://github.com/red-hat-storage/ocs-ci/assets/61454420/ad576e3d-3b65-4b7d-a504-c7430a67d179)

![image](https://github.com/red-hat-storage/ocs-ci/assets/61454420/e563b1e3-3530-4a44-8983-3664c02d9a38)

**Comment by DanielOsypenko** [comment]
@fbalak ideas / suggestions? For now I did not understand why test attempts to run fio 2 times during workload_storageutilization_97p_cephfs? Thanks

**Comment by DanielOsypenko** [comment]
After additional analysis I am vague on opening bug or not, so I add details without opening BZ for now. Requesting your opinion @fbalak @keesturam 
Emphasising that test passes on 4.11, 4.12 but on latest 4.13, and 4.14 seems like we have temporary stopped prometheus server. After ~8 min alerts appear and visible on management-console. From test executions it looks like a regression. Is it worth for opening bug this tmp halting or to adjust the test to query prometheus several times more? 
------------

Description of problem (please be detailed as possible and provide log
snippests):

During the test test_cephfs_capacity_workload_alerts storage was filled up to CephClusterCriticallyFull error, but CephClusterNearFull was not captured.
During the measurement time the monitoring halted, management-console showed storage as 0 Byte, no Alerts or alert rules where visible, no metrics. After the job finished and data removed prometheus request was sent. No CephClusterNearFull was in json load. 

video of the management-console - https://url.corp.redhat.com/video1

After additional 5 minutes at 19:35 CephClusterNearFull appeared showing that it was firing from 19:28.

resp from prometheus without alerts is http://pastebin.test.redhat.com/
Cluster is still available: https://url.corp.redhat.com/cluster-link



Version of all relevant components (if applicable):

OC version:
Client Version: 4.13.4
Kustomize Version: v4.5.7
Server Version: 4.13.0-0.nightly-2023-08-11-101506
Kubernetes Version: v1.26.6+6bf3f75

OCS verison:
ocs-operator.v4.13.2-rhodf              OpenShift Container Storage   4.13.2-rhodf   ocs-operator.v4.13.1-rhodf              Succeeded

Cluster version
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.nightly-2023-08-11-101506   True        False         9h      Cluster version is 4.13.0-0.nightly-2023-08-11-101506

Rook version:
rook: v4.13.2-0.b57f0c7db8116e754fc77b55825d7fd75c6f1aa3
go: go1.19.10

Ceph version:
ceph version 17.2.6-100.el9cp (ea4e3ef8df2cf26540aae06479df031dcfc80343) quincy (stable)


Does this issue impact your ability to continue to work with the product
(please explain in detail what is the user impact)?

no

Is there any workaround available to the best of your knowledge?

no

Rate from 1 - 5 the complexity of the scenario you performed that caused this
bug (1 - very simple, 5 - very complex)?

3

Can this issue reproducible?

3/3

Can this issue reproduce from the UI?

no

If this is a regression, please provide more details to justify this:

ODF Versions 4.11 and 4.12 test passes. Versions 4.13 and 4.14 test does not pass

Steps to Reproduce:
1. Fill up storage up to 97% verify Alerts CephClusterNearFull and CephClusterCriticallyFull appeared in timely manner 
2.
3.


Actual results:
CephClusterNearFull does not appear

Expected results:

CephClusterNearFull appears due to prometheus rules

Additional info:
Similar test on ODF 4.12 and ODF 4.11 is stably Passes

**Comment by keesturam** [comment]
@DanielOsypenko since this is seen on both 4.13 and 4.14, let's open a bug as regression.

**Comment by DanielOsypenko** [comment]
newly deployed 4.12.6 

tests test_rbd_capacity_workload_alerts and test_cephfs_capacity_workload_alerts passes
alerts found manually:

-openshift-monitoring.apps.dosypenk-238.qe.rh-ocs.com/api/v1/alerts | jq '.data.alerts[].labels.alertname'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9114    0  9114    0     0  12543      0 --:--:-- --:--:-- --:--:-- 12640
"ClusterNotUpgradeable"
"CephClusterWarningState"
"AlertmanagerReceiversNotConfigured"
"CannotRetrieveUpdates"
"CephClusterNearFull"
"CephClusterCriticallyFull"
"CephOSDCriticallyFull"
"CephOSDCriticallyFull"
"CephOSDCriticallyFull"
"CephOSDNearFull"
"CephOSDNearFull"
"CephOSDNearFull"
"Watchdog"

**Comment by DanielOsypenko** [comment]
I have opened a bugzilla since Prometheus gets unresponsive for 4 -5 minutes
https://bugzilla.redhat.com/show_bug.cgi?id=2237742
