### ISSUE TITLE
test_crashcollector_pod_existence_on_ceph_pods_running_nodes fails with didn't find the node rack/zone after 120 seconds

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#8326]
RP- https://url.corp.redhat.com/b08e435 (ODF 4.13)

We see that the rack exists for the new node in the node output- http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-046vi1cs33-t2/j-046vi1cs33-t2_20230807T125415/logs/failed_testcase_ocs_logs_1691416926/test_crashcollector_pod_existence_on_ceph_pods_running_nodes_ocs_logs/j-046vi1cs33-t2/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-5b535f9b4e2a1eba94806a3af2e7f4bb7fb2be275c68b9b86c428037a90189f9/cluster-scoped-resources/oc_output/get_nodes_-o_wide_--show-labels

```
j-046vi1cs33-t2-27bg9-worker-0-bz9h4   Ready    worker                 4m35s   v1.26.6+73ac561   10.1.113.109   10.1.113.109   Red Hat Enterprise Linux CoreOS 413.92.202307311416-0 (Plow)   5.14.0-284.25.1.el9_2.x86_64   cri-o://1.26.4-2.rhaos4.13.git7b43407.el9   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=vsphere-vm.cpu-16.mem-64gb.os-unknown,beta.kubernetes.io/os=linux,cluster.ocs.openshift.io/openshift-storage=,kubernetes.io/arch=amd64,kubernetes.io/hostname=j-046vi1cs33-t2-27bg9-worker-0-bz9h4,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=vsphere-vm.cpu-16.mem-64gb.os-unknown,node.openshift.io/os_id=rhcos,topology.rook.io/rack=rack0
```

 Re-triggered it but the test failed again with the same reason in the new run- https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/28439/testReport/junit/tests.manage.z_cluster.cluster_expansion.test_crashcollector_pod_existence_on_ceph_pods_running_nodes/TestAddNodeCrashCollector/test_crashcollector_pod_existence_on_ceph_pods_running_nodes/

**Comment by am-agrawa** [comment]
Assigning to Itzhak after offline discussion.

**Comment by am-agrawa** [comment]
Needs backport on 4.12- https://url.corp.redhat.com/c821dbc

**Comment by yitzhak12** [comment]
The error above happens because in the `TimeoutSampler` function

> sample = TimeoutSampler(
            timeout=timeout,
            sleep=10,
            func=self.is_node_rack_or_zone_exist,
            node_obj=get_node_objs([new_node_name])[0],
            failure_domain=failure_domain,
        )

we get the node object only once, and then keep checking if the node rack or zone exists with the same node object every time instead of getting the updated node.

The fix will be to change the method `is_node_rack_or_zone_exist` to get the node name and retrieve the node object from the node name inside the method `is_node_rack_or_zone_exist`.
