### ISSUE TITLE
ocs-ci does not handle the couchbase admission.yaml 

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#834]
` cb_admission = templating.load_yaml(
     constants.COUCHBASE_ADMISSION_YAML
)`

The above code snippet should load the COUCHBASE_ADMISSION_YAML  which I have defined to be ocs_ci/templates/workloads/couchbase/server/admission.yaml 

Running 'oc create -f ocs-ci/templates/workloads/couchbase/server/admission.yaml works fine:

(venv) [ec2-user@ip-10-0-0-208 ocs-ci]$ oc create -f ocs_ci/templates/workloads/couchbase/server/admission.yaml 
serviceaccount/couchbase-operator-admission created
clusterrole.rbac.authorization.k8s.io/couchbase-operator-admission created
clusterrolebinding.rbac.authorization.k8s.io/couchbase-operator-admission created
secret/couchbase-operator-admission created
deployment.apps/couchbase-operator-admission created
service/couchbase-operator-admission created
mutatingwebhookconfiguration.admissionregistration.k8s.io/couchbase-operator-admission created
validatingwebhookconfiguration.admissionregistration.k8s.io/couchbase-operator-admission created

However, running a test that contains this code produces the following output:

-------------------------------- live log setup --------------------------------
11:13:48 - MainThread - tests.conftest - INFO - All logs located at /tmp/ocs-ci-logs-1569669222
11:13:48 - MainThread - ocs_ci.deployment.factory - INFO - Deployment key = aws_ipi
11:13:48 - MainThread - ocs_ci.deployment.factory - INFO - Current deployment platform: aws,deployment type: ipi
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Executing command: /home/ec2-user/ocs-ci/bin/oc version
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - OpenShift Client version: Client Version: openshift-clients-4.2.0-201909221318
                                                      Server Version: 4.2.0-0.nightly-2019-09-27-191818
                                                      Kubernetes Version: v1.14.6+9cc959c
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - The rook directory /home/ec2-user/ocs-ci/data/rook already exists, ocs-ci will skip the clone of rook repository.
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Fetching latest changes from rook repository.
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Executing command: git fetch --all
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Checkout rook repository to specific branch: master
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Executing command: git checkout master
11:13:48 - MainThread - ocs_ci.utility.utils - WARNING - Command warning: Already on 'master'
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Reset branch: master with latet changes
11:13:48 - MainThread - ocs_ci.utility.utils - INFO - Executing command: git reset --hard origin/master
11:13:48 - Dummy-1 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get Pod  -A -o yaml
11:13:48 - Dummy-2 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get StorageClass  -A -o yaml
11:13:48 - Dummy-3 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get CephFileSystem  -A -o yaml
11:13:48 - Dummy-4 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get CephBlockPool  -A -o yaml
11:13:48 - Dummy-5 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get PersistentVolume  -A -o yaml
11:13:48 - Dummy-6 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get PersistentVolumeClaim  -A -o yaml
11:13:48 - Dummy-7 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get Namespace  -A -o yaml
11:13:59 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc new-project my-ripsaw
11:13:59 - MainThread - ocs_ci.ocs.ripsaw - INFO - cloning ripsaw in /tmp/ripsaw_4t5m82cg
-------------------------------- live log call ---------------------------------
11:14:00 - MainThread - tests.e2e.test_couchbase - INFO - Deploying Couchbase

>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>
> /home/ec2-user/ocs-ci/ocs_ci/ocs/ripsaw.py(163)setup_couchbase()
-> developer = self.create_oc_user('developer')
(Pdb) list
158  	        """
159  	        Deploy Couchbase server
160  	        """
161  	        try:
162  	            import pdb; pdb.set_trace()
163  ->	            developer = self.create_oc_user('developer')
164  	            cb_admission = templating.load_yaml(
165  	                constants.COUCHBASE_ADMISSION_YAML
166  	            )
167  	            cb_crd = templating.load_yaml(
168  	                constants.COUCHBASE_CRD_YAML
(Pdb) b 167
Breakpoint 1 at /home/ec2-user/ocs-ci/ocs_ci/ocs/ripsaw.py:167
(Pdb) cont

>>>>>>>>>>>>>>>>>>>>> PDB continue (IO-capturing resumed) >>>>>>>>>>>>>>>>>>>>>>
FAILED                                                                   [100%]
------------------------------ live log teardown -------------------------------
11:14:23 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc delete project my-ripsaw
11:14:24 - MainThread - ocs_ci.ocs.ocp - INFO - Switching to project openshift-storage
11:14:24 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc project openshift-storage
11:14:24 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get namespace my-ripsaw -o yaml
11:14:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get namespace my-ripsaw -o yaml
11:14:30 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get namespace my-ripsaw -o yaml
11:14:30 - MainThread - ocs_ci.ocs.ocp - INFO - namespace my-ripsaw got deleted successfully
11:14:30 - Dummy-8 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get Pod  -A -o yaml
11:14:30 - Dummy-9 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get StorageClass  -A -o yaml
11:14:30 - Dummy-1 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get CephFileSystem  -A -o yaml
11:14:30 - Dummy-7 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get CephBlockPool  -A -o yaml
11:14:30 - Dummy-5 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get PersistentVolume  -A -o yaml
11:14:30 - Dummy-10 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get PersistentVolumeClaim  -A -o yaml
11:14:30 - Dummy-6 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ec2-user/wusui/auth/kubeconfig get Namespace  -A -o yaml

=================================== FAILURES ===================================
_____________ TestCouchbaseWorkload.test_couchbase_workload_simple _____________

self = <tests.e2e.test_couchbase.TestCouchbaseWorkload object at 0x7fd2f0717748>
ripsaw = <ocs_ci.ocs.ripsaw.RipSaw object at 0x7fd2ec60f2b0>

    def test_couchbase_workload_simple(self, ripsaw):
        """
        This is a basic ycsb workload
        """
        log.info("Deploying Couchbase")
>       ripsaw.setup_couchbase()

tests/e2e/test_couchbase.py:44: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/ocs/ripsaw.py:165: in setup_couchbase
    constants.COUCHBASE_ADMISSION_YAML
ocs_ci/utility/templating.py:159: in load_yaml
    return loader(fs)
../venv/lib64/python3.6/site-packages/yaml/__init__.py:162: in safe_load
    return load(stream, SafeLoader)
../venv/lib64/python3.6/site-packages/yaml/__init__.py:114: in load
    return loader.get_single_data()
../venv/lib64/python3.6/site-packages/yaml/constructor.py:41: in get_single_data
    node = self.get_single_node()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <yaml.loader.SafeLoader object at 0x7fd2ec60f9e8>

    def get_single_node(self):
        # Drop the STREAM-START event.
        self.get_event()
    
        # Compose a document if the stream is not empty.
        document = None
        if not self.check_event(StreamEndEvent):
            document = self.compose_document()
    
        # Ensure that the stream contains no more documents.
        if not self.check_event(StreamEndEvent):
            event = self.get_event()
            raise ComposerError("expected a single document in the stream",
                    document.start_mark, "but found another document",
>                   event.start_mark)
E           yaml.composer.ComposerError: expected a single document in the stream
E             in "/home/ec2-user/ocs-ci/ocs_ci/templates/workloads/couchbase/server/admission.yaml", line 2, column 1
E           but found another document
E             in "/home/ec2-user/ocs-ci/ocs_ci/templates/workloads/couchbase/server/admission.yaml", line 8, column 1

../venv/lib64/python3.6/site-packages/yaml/composer.py:43: ComposerError
---------------------------- Captured stderr setup -----------------------------
Cloning into 'ripsaw'...
----------------------------- Captured stderr call -----------------------------
Updating password for user developer
--------------------------- Captured stderr teardown ---------------------------
error: the path "resources/crd/" does not exist
error: the path "resources/operator.yaml" does not exist
error: the path "deploy" does not exist
============================== 1 failed in 53.52s ==============================
Exception ignored in: <async_generator object _ag at 0x7fd2fcbc5c10>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/types.py", line 27, in _ag
  File "/usr/lib64/python3.6/bdb.py", line 53, in trace_dispatch
  File "/usr/lib64/python3.6/bdb.py", line 79, in dispatch_call
  File "/usr/lib64/python3.6/bdb.py", line 176, in break_anywhere
  File "/usr/lib64/python3.6/bdb.py", line 36, in canonic
AttributeError: 'NoneType' object has no attribute 'abspath'

**Comment by clacroix12** [comment]
Just to update here for anyone else, `admission.yaml` is a multi-document yaml file and as such we need to pass `multi_document=True` to `templating.load_yaml()`

Closing this for now but if other issues come up with this feel free to reopen.
