### ISSUE TITLE
Hierarchy design implemetation

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#84]
We should implement the hierarchy design we will agree on.
This was raised by @RazTamir along with few design options:
https://docs.google.com/drawings/d/1Esc0zexs9Oe8BaKQA71LuV5-K1dAJSSluWq_aCieGrM/edit
https://docs.google.com/drawings/d/1SUbmE-TITkgWNruiKcFwrl52ULEuO_rDUtY4guIz2UY/edit

**Comment by RazTamir** [comment]
I will take this issue and try to come up with something that will satisfy @shylesh design

**Comment by shylesh** [comment]
@ebenahar 
I can take this up if you are okay.

Thanks,
Shylesh

**Comment by ebenahar** [comment]
@shylesh Ok, NP, assigning to you

**Comment by petr-balogh** [comment]
Hi, @shylesh  can you please update us if you had time to start looking at it?  Thanks

**Comment by shylesh** [comment]
@petr-balogh ,

I refined the design further https://docs.google.com/drawings/d/1xb_zl3fsbBiftOeZ7_gFU7NkJ40D2EaDHUMyHitWAVg/edit?usp=sharing.  However I will soon submit the PR with skeleton classes and methods. Its fast evolving as and when our understanding of kubernetes is growing and expected to change further.

I see the need for these classes very much as users have started submitting testcase PRs and everybody is in need of supporting functionalities. I am working on priority.

Thanks,
Shylesh

**Comment by shylesh** [comment]
some of the pieces are already in Vijay's PR https://github.com/red-hat-storage/ocs-ci/pull/40/files. We are collaborating on how to put it in place and implement remaining.

**Comment by vasukulkarni** [comment]
This is addressed!
