### ISSUE TITLE
Update jenkins test PR job to use downstream_config.yaml

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#840]
Since we are using downstream_config to run testing, please update jenkins test PR job to support both upstream/downstream configs, (dropdown box maybe)

**Comment by petr-balogh** [comment]
ppl can now pass whatever config they want by this jenkins CLUSTER_CONF so they can pass conf/ocsci/downstream_config.yaml to use downstream installation. So do not think it's high priority and not sure if even issue when it's possible to do now.  We have more config files, and this way I should do matrix of all possible config which I don't think is necessary.
So removing hig priority label here and maybe we can close.
