### ISSUE TITLE
bad yaml for bg-fio-load

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#8445]
Message: failed on teardown with "ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n bg-fio-load-f6ffd create -f /tmp/DeploymentConfigposf5qb3 -o yaml.
Error is Error from server (BadRequest): error when creating "/tmp/DeploymentConfigposf5qb3": DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string"
Type: None

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/12975/594597/594598/594600/log

**Comment by ebenahar** [comment]
It's fixed with https://github.com/red-hat-storage/ocs-ci/pull/7604 but only in the master branch.
I will backport it

**Comment by ebenahar** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/8471
https://github.com/red-hat-storage/ocs-ci/pull/8472
https://github.com/red-hat-storage/ocs-ci/pull/8473
https://github.com/red-hat-storage/ocs-ci/pull/8474

**Comment by ebenahar** [comment]
> #8471 #8472 #8473 #8474

All PRs got merged
