### ISSUE TITLE
In the test "test_ceph_osd_stopped_pd" it failed to find the incident of the CephOSDDiskUnavailable

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#8501]
When running the test `tests/manage/monitoring/pagerduty/test_deployment_status.py::test_ceph_osd_stopped_pd`, it failed to find the incident of the CephOSDDiskUnavailable. 
Here is the link to the test failure: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/1946/testReport/tests.manage.monitoring.pagerduty/test_deployment_status/test_ceph_osd_stopped_pd/, 
and the relevant output from the console output https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/1946/consoleFull:

> 023-09-14 14:48:12  -------------------------------- live log call ---------------------------------
2023-09-14 14:48:12  11:48:10 - MainThread - /home/jenkins/workspace/qe-odf-multicluster/ocs-ci/ocs_ci/utility/pagerduty.py - INFO - C[ikave-mpl70-pr] - Looking for incidents with summary CephOSDDiskUnavailable and urgency high
2023-09-14 14:48:12  11:48:10 - MainThread - /home/jenkins/workspace/qe-odf-multicluster/ocs-ci/ocs_ci/utility/pagerduty.py - INFO - C[ikave-mpl70-pr] - No incidents with summary CephOSDDiskUnavailable and urgency high were found
2023-09-14 14:48:12  FAILED

**Comment by yitzhak12** [comment]
After looking again in the console output https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/1946/consoleFull, I saw that the warning we search in the incident is different from the pagerduty logging. In the pagerduty logging, we log the warning `CephOSDDiskNotResponding`: 

> {'incident_number': 153334, 'title': '[FIRING:1] CephOSDDiskNotResponding (openshift-storage osd.2 23084142-eecf-4973-a744-c4a93fc7092d mgr /dev/nvme2n1 2 http-metrics ip-10-206-42-222.us-east-2.compute.internal 10.206.42.222:9283 rook-ceph-mgr ocs-storagecluster openshift-storage rook-ceph-mgr-a-544bc78f5b-kxwvj openshift-storage/managed-ocs-prometheus rook-ceph-mgr critical)', 'description': '[FIRING:1] CephOSDDiskNotResponding (openshift-storage osd.2 23084142-eecf-4973-a744-c4a93fc7092d mgr /dev/nvme2n1 2 http-metrics ip-10-206-42-222.us-east-2.compute.internal 10.206.42.222:9283 rook-ceph-mgr ocs-storagecluster openshift-storage rook-ceph-mgr-a-544bc78f5b-kxwvj openshift-storage/managed-ocs-prometheus rook-ceph-mgr critical)'

And we search for the incident `CephOSDDiskUnavailable`.

**Comment by yitzhak12** [comment]
I am unsure if there is a good reason that we expect the warning `CephOSDDiskUnavailable`, not `CephOSDDiskNotResponding`. We need to check if both notifications are valid in this case.

**Comment by fbalak** [comment]
Both alerts provide similar information to sre and are valid for the test. We can check that at least one of them is raised when a valid scenario is encountered.
