### ISSUE TITLE
test_validate_ceph_config_values_in_rook_config_override I Failed  after BZ#2218116 in 4.14

### ISSUE THREAD

**Issue by suchita-g** [red-hat-storage/ocs-ci#8505]
It's a newly added config in ODF 4.14 for Regional DR. refer bzhttps://bugzilla.redhat.com/show_bug.cgi?id=2218116. OCS-ci Need to adjust for the same

test_validate_ceph_config_values_in_rook_config_override I Failed with  
`error The Ceph config, set by rook-config-override is different than the expected `  
This Test case compares the cluster's config values of Ceph, set by ceph-config-override configMap, with the static set of configuration saved in ocs-ci
In 4.14 The ceph config set by rook-config-override contains 1 more item: i.e. 'bluestore_prefer_deferred_size_hdd = 0'  than expected. 

It's a newly added config in ODF 4.14 for Regional DR. You can refer https://bugzilla.redhat.com/show_bug.cgi?id=2218116

Hence ocs-ci need to adjust for the same. ( similar to the adjustment for the earlier version in ROOK_CEPH_CONFIG_VALUES_x in https://github.com/red-hat-storage/ocs-ci/blob/49c0a3b8a49d01c70176d69a5cd1e777c4019838/ocs_ci/ocs/constants.py#L1876)

**Comment by am-agrawa** [comment]
PR is already merged
