### ISSUE TITLE
s3-cli-with-test-objects-multiarch:2.0 throws exec format error on s390x

### ISSUE THREAD

**Issue by schaefm-ibm** [red-hat-storage/ocs-ci#8594]
Several MCG related tests are failing on s390x (and possibly other platforms but x86, as well?) since PR https://github.com/red-hat-storage/ocs-ci/pull/8175. It seems the referred image quay.io/ocsci/s3-cli-with-test-objects-multiarch:2.0 is not really multiarch.

**Comment by ebenahar** [comment]
@sagihirshfeld could you please take a look?
