### ISSUE TITLE
test_recovery_from_volume_deletion is failing with TypeError: Required field "device" not provided (not @optional) over VMWare UPI

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#8630]
PR #8137 was expected to fix the test due to changes in PV yaml to fetch the volume ID, but the test is failing elsewhere.

PR validation- https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/30063/testReport/junit/tests.manage.z_cluster.nodes.test_disk_failures/TestDiskFailures/test_recovery_from_volume_deletion/

TypeError: Required field "device" not provided (not @optional)

>       osd_operations.osd_device_replacement(nodes)

tests/manage/z_cluster/nodes/test_disk_failures.py:225: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/ocs/osd_operations.py:105: in osd_device_replacement
    nodes.detach_volume(backing_volume, osd_node)
ocs_ci/ocs/platform_nodes.py:429: in detach_volume
    self.vsphere.remove_disk(
ocs_ci/utility/vsphere.py:727: in remove_disk
    virtual_disk_spec.device = virtual_disk_device
venv/lib64/python3.8/site-packages/pyVmomi/VmomiSupport.py:663: in __setattr__
    CheckField(self._GetPropertyInfo(name), val)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

info = <pyVmomi.VmomiSupport.LazyObject object at 0x7f4f273983d0>, val = None

    def CheckField(info, val):
       with _lazyLock:
          valType = Type(val)
          if val is None or (isinstance(val, list) and len(val) == 0):
             # If type of the property is an Any. We should allow this to have
             # unset items
             if not (info.flags & F_OPTIONAL) and info.type is not object:
>               raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
E               TypeError: Required field "device" not provided (not @optional)

venv/lib64/python3.8/site-packages/pyVmomi/VmomiSupport.py:1041: TypeError

**Comment by ebenahar** [comment]
Looks like the issue happens when `virtual_disk_device` is None. In that case, a warning is printed:

```2023-10-02 15:48:30  12:48:19 - MainThread - ocs_ci.utility.vsphere - WARNING  - Volume with volume_path 290639f2-3a21-4c8b-b0b3-c21cc98c2d18 for compute-1 could not be found```

but the function doesn't raise an exception and just continues, which causes the next assignment to fail:

```python
virtual_disk_spec.device = virtual_disk_device
```
