### ISSUE TITLE
test_obc_creation_and_deletion bucket class selection failed

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#8635]
Should be this page:

![image](https://github.com/red-hat-storage/ocs-ci/assets/61454420/e47fdab6-293c-41fd-8563-ff66732cdd21)

-----
Message: selenium.common.exceptions.TimeoutException: Message: Failed to find the element (css selector,input[placeholder="Select BucketClass"],input[class="pf-c-form-control pf-m-search"])
Type: None

Text:
self = ObjectBucketClaimsTab Web Page
locator = ('input[placeholder="Select BucketClass"],input[class="pf-c-form-control pf-m-search"]', 'css selector')
text = 'noobaa-default-bucket-class', timeout = 30

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/15035/697589/697743/697744/log

**Comment by shyRozen** [comment]
Not failing everytime. Could some timing issue. Please check @ebondare
