### ISSUE TITLE
In the test "test_rolling_nodes_restart" with vSphere external mode it failed to create resources after the rolling nodes restart completed

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#8648]
In the test `test_rolling_nodes_restart` when using vSphere external mode, after the rolling nodes restart was completed, it failed to create resources and run IO. There is a chance that waiting more time before creating the resources will solve the problem, but I don't think this is the expected behavior.
See more details here: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/15162/705063/705116/705117/log.

**Comment by yitzhak12** [comment]
There is another error with the vSphere external cluster when creating the resources: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/16235/772705/772758/772759/log: 

> Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n namespace-test-f7c128e5a5134c829100a2805 create -f /tmp/POD_9pynbxpx -o yaml.
Error is Error from server (Forbidden): error when creating "/tmp/POD_9pynbxpx": pods "pod-test-rbd-5f3163aabc704e189f3e89f2a0d" is forbidden: error fetching namespace "namespace-test-f7c128e5a5134c829100a2805": unable to find annotation openshift.io/sa.scc.uid-range
Type: None

**Comment by am-agrawa** [comment]
It could be similar to issue #8796 , kindly check
