### ISSUE TITLE
Destroy cluster implementation for pytest

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#87]
We need to move our current implementation of --destroy  to pytest way to allow us to run it via pytest.

**Comment by clacroix12** [comment]
We can address #53 as a part of this. @petr-balogh what is the preferred way we execute the cluster destroy. Do we create a test with a particular mark (destroy?) that reads in the `--cluster-path` value?

**Comment by petr-balogh** [comment]
@clacroix12 yep, we can do it like this for now. Than we can decide on different approach later on.

**Comment by petr-balogh** [comment]
Fixed in #140
