### ISSUE TITLE
Test `test_delete_rbd_pool_attached_to_sc_UI[3-aggressive-Immediate-Bound]` looking for non-existing key

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#8751]
Test : `tests/manage/storageclass/test_delete_rbd_pool_attached_to_sc.py::TestDeleteRbdPool::test_delete_rbd_pool_attached_to_sc_UI[3-aggressive-Immediate-Bound]`

Error: 
```
>               self.bp_loc["pool_cannot_be_deleted_warning"][::-1]
            )
E           KeyError: 'pool_cannot_be_deleted_warning'
```

Description: it looks like the test is looking for a non-existing key from the alert.

Test log : [test_delete_rbd_pool_attached_to_sc_UI-3-aggressive-Immediate-Bound.log](https://github.com/red-hat-storage/ocs-ci/files/13175811/test_delete_rbd_pool_attached_to_sc_UI-3-aggressive-Immediate-Bound.log)

**Comment by ebenahar** [comment]
@paraggit can you please take a look?

**Comment by paraggit** [comment]
I ran the same test with the latest ocs-ci changes, and it passed without any errors. Additionally, I can see the mentioned missing key in the [view.py](https://github.com/red-hat-storage/ocs-ci/blob/326778a5387162ed52100605409817fe3a1bef6e/ocs_ci/ocs/ui/views.py#L1021) file.

Test Logs:  https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/30889/console

@abdulkandathil Can you try with the latest ocs-ci changes ?

**Comment by abdulkandathil** [comment]
Hi @paraggit ,
 I can confirm that the test is now passing with latest changes from ocs-ci and freshly installed odf cluster.

cc @ebenahar

**Comment by abdulkandathil** [comment]
closing the issue..
