### ISSUE TITLE
Remove workaround for BZ 1759947: Deploying cluster with persistent storage for monitoring pods

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#878]
When BZ 1759947 is fixed, we should remove the workaround introduced in https://github.com/red-hat-storage/ocs-ci/pull/479

The easiest way to remove the workaround would be to change default value of `persistent-monitoring` option to `false`.

**Comment by mbukatov** [comment]
Note that his is not a new development, as I noted in code review of #479 pull request [on Aug 23](https://github.com/red-hat-storage/ocs-ci/pull/479#discussion_r317074859):

> Right now, neither monitoring nor it's persistent configuration is enabled by default. But when the OCS operator is ready and the OCS setup is finalized, both monitoring and it's persistent setup will be enabled by default, without an option to have it disabled.

**Comment by gklein** [comment]
It seems the the mentiond [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1759947#c5) was closed as NOTABUG.

As it seems we can't remove the workaround without a fix, what should we do with this issue?

**Comment by mbukatov** [comment]
This issue stays here until the original problem is fixed in the product. Having such open issues with a workaround tag help us with tracking the workaround currently present in the code.

In this particular case, decision on BZ 1759947 needs to be reviewed during next planning phase and based on the results we can proceed.

**Comment by vasukulkarni** [comment]
I think this can be closed
