### ISSUE TITLE
Upload failed: with An error occurred (InvalidBucketState) when calling the UploadPart operation: The request is not valid with the current state of the bucket.

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#8789]
Upload failed: ../test_objects/danny.webm to s3://oc-bucket-e5c32f2f12424a65aeb765edc1385c/danny1.webm An error occurred (InvalidBucketState) when calling the UploadPart operation: The request is not valid with the current state of the bucket.

Test case: tests.manage.mcg.test_write_to_bucket.TestBucketIO[test_mcg_data_deduplication[AWS-OC-1]
Logs: 
[http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-088bu1cni33-t1/j-088bu1cni33-t1_20231019T142439/logs/ocs-ci-logs-1697729498/tests/manage/mcg/test_write_to_bucket.py/TestBucketIO/test_mcg_data_deduplication-AWS-OC-1/logs](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-088bu1cni33-t1/j-088bu1cni33-t1_20231019T142439/logs/ocs-ci-logs-1697729498/tests/manage/mcg/test_write_to_bucket.py/TestBucketIO/test_mcg_data_deduplication-AWS-OC-1/logs)

```
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh s3cli-0 sh -c "AWS_CA_BUNDLE=/cert/service-ca.crt AWS_ACCESS_KEY_ID=vgL0SAH3AyrRtk6iJ8PF AWS_SECRET_ACCESS_KEY=pYOnOF1Mtd06110QscRiSWThkx8j4uKh6gY4RB5W AWS_DEFAULT_REGION=us-east-2 aws s3 --endpoint=[https://s3.openshift-storage.svc:443](https://s3.openshift-storage.svc/) cp /test_objects/danny.webm s3://oc-bucket-e5c32f2f12424a65aeb765edc1385c/danny1.webm".
Error is upload failed: ../test_objects/danny.webm to s3://oc-bucket-e5c32f2f12424a65aeb765edc1385c/danny1.webm An error occurred (InvalidBucketState) when calling the UploadPart operation: The request is not valid with the current state of the bucket.
command terminated with exit code 1
Type: None

```

**Comment by tiffanyn108** [comment]
Issue seen with 4.13.5-10
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-090vi1cs33-uba/j-090vi1cs33-uba_20231122T213739/logs/ocs-ci-logs-1700720424/tests/manage/mcg/test_write_to_bucket.py/TestBucketIO/test_mcg_data_deduplication-IBMCOS-OC-1/logs

**Comment by Pooja-Soni78** [comment]
test_mcg_data_deduplication[AWS-OC-1] is failing for ODF 4.15 also with the same error on IBM Power.
