### ISSUE TITLE
test_nodes_restart[True] fails on external mode cluster with error Error is Error from server (ServiceUnavailable): the server is currently unable to handle the request (get projectrequests.project.openshift.io)

### ISSUE THREAD

**Issue by pintojoy** [red-hat-storage/ocs-ci#8796]
tests/manage/z_cluster/nodes/test_nodes_restart.py:95: 

ocs_ci/helpers/sanity_helpers.py:76: in create_resources
    pvc_obj = pvc_factory(interface)
tests/conftest.py:1067: in factory
    project = project or active_project or project_factory()
tests/conftest.py:917: in factory
    proj_obj = helpers.create_project(project_name=project_name)
ocs_ci/helpers/helpers.py:489: in create_project
    assert project_obj.new_project(namespace), f"Failed to create namespace {namespace}"
ocs_ci/ocs/ocp.py:484: in new_project
    exec_output = run_cmd(
ocs_ci/utility/utils.py:484: in run_cmd
    completed_process = exec_cmd(

cmd = ['oc', 'new-project', 'namespace-test-6c9790ce8d3c4784854db67b7']
secrets = None, timeout = 600, ignore_error = False, threading_lock = None
silent = False, use_shell = False, cluster_config = None, kwargs = {}
masked_cmd = 'oc new-project namespace-test-6c9790ce8d3c4784854db67b7'
completed_process = CompletedProcess(args=['oc', 'new-project', 'namespace-test-6c9790ce8d3c4784854db67b7'], returncode=1, stdout=b'', std...erviceUnavailable): the server is currently unable to handle the request (get projectrequests.project.openshift.io)\n')
masked_stdout = ''
masked_stderr = 'Error from server (ServiceUnavailable): the server is currently unable to handle the request (get projectrequests.project.openshift.io)\n'

def exec_cmd(
    cmd,
    secrets=None,
    timeout=600,
    ignore_error=False,
    threading_lock=None,
    silent=False,
    use_shell=False,
    cluster_config=None,
    **kwargs,
):
    """
    Run an arbitrary command locally

    If the command is grep and matching pattern is not found, then this function
    returns "command terminated with exit code 1" in stderr.

    Args:
        cmd (str): command to run
        secrets (list): A list of secrets to be masked with asterisks
            This kwarg is popped in order to not interfere with
            subprocess.run(``**kwargs``)
        timeout (int): Timeout for the command, defaults to 600 seconds.
        ignore_error (bool): True if ignore non zero return code and do not
            raise the exception.
        threading_lock (threading.RLock): threading.RLock object that is used
            for handling concurrent oc commands
        silent (bool): If True will silent errors from the server, default false
        use_shell (bool): If True will pass the cmd without splitting
        cluster_config (MultiClusterConfig): In case of multicluster environment this object
                will be non-null

    Raises:
        CommandFailed: In case the command execution fails

    Returns:
        (CompletedProcess) A CompletedProcess object of the command that was executed
        CompletedProcess attributes:
        args: The list or str args passed to run().
        returncode (str): The exit code of the process, negative for signals.
        stdout     (str): The standard output (None if not captured).
        stderr     (str): The standard error (None if not captured).

    """
    masked_cmd = mask_secrets(cmd, secrets)
    log.info(f"Executing command: {masked_cmd}")
    if isinstance(cmd, str) and not kwargs.get("shell"):
        cmd = shlex.split(cmd)
    if cluster_config and cmd[0] == "oc" and "--kubeconfig" not in cmd:
        kubepath = cluster_config.RUN["kubeconfig"]
        cmd = list_insert_at_position(cmd, 1, ["--kubeconfig"])
        cmd = list_insert_at_position(cmd, 2, [kubepath])
    if threading_lock and cmd[0] == "oc":
        threading_lock.acquire()
    completed_process = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        stdin=subprocess.PIPE,
        timeout=timeout,
        **kwargs,
    )
    if threading_lock and cmd[0] == "oc":
        threading_lock.release()
    masked_stdout = mask_secrets(completed_process.stdout.decode(), secrets)
    if len(completed_process.stdout) > 0:
        log.debug(f"Command stdout: {masked_stdout}")
    else:
        log.debug("Command stdout is empty")

    masked_stderr = mask_secrets(completed_process.stderr.decode(), secrets)
    if len(completed_process.stderr) > 0:
        if not silent:
            log.warning(f"Command stderr: {masked_stderr}")
    else:
        log.debug("Command stderr is empty")
    log.debug(f"Command return code: {completed_process.returncode}")
    if completed_process.returncode and not ignore_error:
        masked_stderr = bin_xml_escape(filter_out_emojis(masked_stderr))
        if (
            "grep" in masked_cmd
            and b"command terminated with exit code 1" in completed_process.stderr
        ):
            log.info(f"No results found for grep command: {masked_cmd}")
        else:

          raise CommandFailed(
                f"Error during execution of command: {masked_cmd}."
                f"\nError is {masked_stderr}"
            )
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc new-project namespace-test-6c9790ce8d3c4784854db67b7.
E               Error is Error from server (ServiceUnavailable): the server is currently unable to handle the request (get projectrequests.project.openshift.io)

**Comment by yitzhak12** [comment]
I also see this error with a non-external mode cluster.
