### ISSUE TITLE
Come up with approach to execute deployment, test execution, cleanup in one run.

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#88]
We can use [pytest ordering](https://pytest-ordering.readthedocs.io/en/develop/) plugin to make sure that deployment test is running as the first one test, and the destroy cluster will be run at the end of the execution.  We can specify execution for example like: `pytest -m "deployment or (tier1 and manage) or destroy"` to run deployment, then tier1 tests of manage team and destroy the cluster.

**Comment by andrewschoen** [comment]
I think the deployment phase would be nicely done as a pytest fixture with a scope of session. This way the cluster can be created at the start of the test run and tore down when the tests complete. I've used this pattern in the past to create databases that are used during the test run and discarded afterwards. 

He's a link to some pytest docs about this: https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session

This is is an example of how I've done this in the past for a shared test database: https://github.com/ceph/shaman/blob/master/shaman/tests/conftest.py#L101

I'd be happy to start the work here if we think it's an approach worth exploring.

**Comment by vasukulkarni** [comment]
Even I think session based scope fits better,  but we also want this to be optional when using existing cluster.  probably its better to discuss in meeting how to fix the ordering part.

**Comment by andrewschoen** [comment]
> Even I think session based scope fits better, but we also want this to be optional when using existing cluster. probably its better to discuss in meeting how to fix the ordering part.

I'd be happy to discuss this in a meeting. I think we'd handle using a existing cluster exactly how it's currently done. We can test to see if cluster information was given and if we can connect to it or not. https://github.com/red-hat-storage/ocs-ci/blob/master/tests/ecosystem/deployment/test_ocs_basic_install.py#L27-L33
