### ISSUE TITLE
nsfs  failed cannot access '/nsfs': No such file or directory

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#8809]
Test case: test_nsfs_object_integrity_with_wrong_permissions[CLI-20Gi] failed with error:
Logs:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/16404/785603/785668/785669/log
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-013vud1cs33-t3/j-013vud1cs33-t3_20231103T065608/logs/ocs-ci-logs-1698998622/tests/manage/mcg/test_nsfs.py/TestNSFSObjectIntegrity/test_nsfs_object_integrity_with_wrong_permissions-CLI-20Gi/logs

```
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh noobaa-endpoint-569b69b6d8-pjfmz chmod -R 777 /nsfs.
Error is chmod: cannot access '/nsfs': No such file or directory
command terminated with exit code 1
Type: None
```

**Comment by sagihirshfeld** [comment]
Recently seen again in 4.14 runs that included the fix:
- https://url.corp.redhat.com/973a589
- https://url.corp.redhat.com/749b667
- https://url.corp.redhat.com/aefe7cd
