### ISSUE TITLE
An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS access key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#8811]
Test case: [tests.manage.mcg.test_log_based_bucket_replication.TestLogBasedBucketReplication]
test_deletion_sync_after_instant_deletion

Logs:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/16091/764834/764893/764894/log
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vup1cs33-t3/j-001vup1cs33-t3_20231023T102548/logs/ocs-ci-logs-1698060423/tests/manage/mcg/test_log_based_bucket_replication.py/TestLogBasedBucketReplication/test_deletion_sync_after_instant_deletion/logs

```
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh s3cli-0 sh -c "AWS_CA_BUNDLE=/cert/service-ca.crt AWS_ACCESS_KEY_ID=eM1TWJlOArECgAn2C1we AWS_SECRET_ACCESS_KEY=z4XBqbXvejVjC1DWAlD1FdsQcR22ypkC+JRuq4t7 AWS_DEFAULT_REGION=us-east-2 aws s3 --endpoint=[https://s3.openshift-storage.svc:443](https://s3.openshift-storage.svc/) cp /test_objects/airbus.jpg s3://oc-bucket-bc570be1832a40bdaa8186b1861207/airbus.jpg".
Error is upload failed: ../test_objects/airbus.jpg to s3://oc-bucket-bc570be1832a40bdaa8186b1861207/airbus.jpg An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS access key Id you provided does not exist in our records.
command terminated with exit code 1
Type: None 

```

**Comment by sagihirshfeld** [comment]
Looking at the must-gather logs of one of these failures show that the s3 credentials in the S3 command don't match the credentials at the noobaa-admin secret. 

One of the previous tier3 tests must have made the change, but because we're using mcg_obj_session we're using the credentials from before the change.

**Comment by sagihirshfeld** [comment]
A closer inspection reveals that during tier3 runs `test_noobaa_rebuild` resets the noobaa-admin credentials, thus invalidating the credentials that were saved in the session-scoped mcg_obj fixture that were previously set in `test_noobaa_db_backup_and_recovery`. Using the session_scoped mcg_obj fixture in this test and updating its credentials during the test should resolve this.
