### ISSUE TITLE
test_unidirectional_bucket_replication failed with AssertionError: Objects don't match

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#8821]
Test case: test_unidirectional_bucket_replication[AWStoAZURE-BS-OC]
Run: [https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/16391/784088/784156/784158/log](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/16391/784088/784156/784158/log)
Logs: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-321vuf1cs33-t1/j-321vuf1cs33-t1_20231102T101514/logs/ocs-ci-logs-1698923659/tests/manage/mcg/test_bucket_replication.py/TestReplication/test_unidirectional_bucket_replication-AWStoAZURE-BS-OC/logs

**Comment by udaysk23** [comment]
Above issue is product bug in noobaa component.
https://bugzilla.redhat.com/show_bug.cgi?id=2248997
