### ISSUE TITLE
In the test "test_automated_recovery_from_failed_nodes_IPI_reactive[rbd-shutdown]" it failed to create the rbd dc pod test

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#8831]
In the test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/6038/testReport/tests.manage.z_cluster.nodes.test_automated_recovery_from_failed_nodes_reactive_IPI/TestAutomatedRecoveryFromFailedNodes/test_automated_recovery_from_failed_nodes_IPI_reactive_rbd_shutdown_/, 
it failed to create the rbd dc pod test. From the error, I see this message: 

> E             Type     Reason              Age                From                     Message
> E             ----     ------              ----               ----                     -------
> E             Normal   Scheduled           13m                default-scheduler        Successfully assigned namespace-test-d33f9971d9654512b1ce4b290/pod-test-rbd-2958150165b94c709c7e43f2018-1-44spx to ikave-gcp414-s9h7k-worker-d-vh2zj
> E             Warning  FailedAttachVolume  13m                attachdetach-controller  Multi-Attach error for volume "pvc-48530606-3d64-4714-b1ea-d2749ab38aa4" Volume is already used by pod(s) pod-test-rbd-2958150165b94c709c7e43f2018-1-8v4xv
> E             Warning  FailedMount         19s (x6 over 11m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[fedora-vol], unattached volumes=[fedora-vol], failed to process volumes=[]: timed out waiting for the condition

**Comment by yitzhak12** [comment]
It seems to be similar to the error: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/14625/672413/672453/672456/log.

**Comment by yitzhak12** [comment]
I saw a similar issue in my local: 

Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Warning  FailedScheduling    19m                default-scheduler        0/6 nodes are available: 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 3 node(s) had untolerated taint {node.kubernetes.io/unreachable: }. preemption: 0/6 nodes are available: 6 Preemption is not helpful for scheduling..
  Normal   Scheduled           15m                default-scheduler        Successfully assigned namespace-test-a96c803c73e044428064475e3/pod-test-rbd-da335d41aeaf4dd9b3ecf885e45-1-z2xk5 to ikave-gcp7-414-sc29w-worker-d-twwds
  Warning  FailedAttachVolume  15m                attachdetach-controller  Multi-Attach error for volume "pvc-e74baed0-6fc1-4815-a2cb-42ddf92085bf" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount         21s (x7 over 13m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[fedora-vol], unattached volumes=[fedora-vol], failed to process volumes=[]: timed out waiting for the condition

**Comment by amr1ta** [comment]
This test is not failing with this error now instead failing with a different error, 

E       AttributeError: 'NoneType' object has no attribute 'name'
TFA-R[Similar_Results] https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/7573/332133/log , 97.431 , https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/8181/361917/log , 97.256 , https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/8181/361915/log , 96.985
