### ISSUE TITLE
We need to fix the test "test_automated_recovery_from_failed_nodes_IPI_reactive" when using Cloud platform

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#8832]
In the test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/6038/testReport/tests.manage.z_cluster.nodes.test_automated_recovery_from_failed_nodes_reactive_IPI/TestAutomatedRecoveryFromFailedNodes/test_automated_recovery_from_failed_nodes_IPI_reactive_cephfs_terminate_/, we can see that if failed to create a new worker node. This failure is not because of not creating a new node but because the machineset replica count was not equal to the ready replica count. 
Currently, the test is suitable for vSphere IPI, but we need to modify the test to run on the other cloud platforms. 
Two actions we might need to do:

- modifying the teardown part.
- Delete the machine of the terminated worker node(in case we terminate the node).

**Comment by amr1ta** [comment]
Working on the fix
