### ISSUE TITLE
Stabilize test_recovery_from_volume_deletion for all supported ODF versions

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#8839]
The test was failing with volume dettach and re-attach which was fixed by PR #8632 but is now failing at later steps and we need to stabilize it as the test is critical to be covered as part of regression runs. 

Recent failure (RP)- https://url.corp.redhat.com/2723127

**Comment by yitzhak12** [comment]
We need to wait for the BZ https://bugzilla.redhat.com/show_bug.cgi?id=2248833 to be fixed before we make further changes. For now, we may need to skip or implement some workaround.

**Comment by yitzhak12** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/8864

**Comment by am-agrawa** [comment]
@yitzhak12 Could you pls take a look?

**Comment by yitzhak12** [comment]
This issue should be fixed now, as the two backport PRs: https://github.com/red-hat-storage/ocs-ci/pull/8964, https://github.com/red-hat-storage/ocs-ci/pull/8962 have been merged.
