### ISSUE TITLE
MDR deployment unsuccessful on OCP 4.12 with fileNotFoundError

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#8898]
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-mdr-setup/165/console
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/31381/console

```
2023-11-20 09:00:10  FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/conf/ocsci/multicluster_active_acm_cluster.yaml'
```
```2023-11-20 15:01:56  FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/workspace/qe-mdr-setup/ocs-ci/conf/ocsci/multicluster_mode_mdr.yaml'```

**Comment by petr-balogh** [comment]
Do you need to install with OCP 4.12?  Do we support MDR for this version?

**Comment by Shrivaibavi** [comment]
yes we support, we are currently supporting OCP 4.12.z, ODF 4.12.10, ACM 2.7.9
