### ISSUE TITLE
Require function to copy files into OCP nodes

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#892]
Require function to copy files into OCP nodes, which will be useful in-case of copy `kubeconfig` files to OCP node and run `oc` commands

Another Requirement for copying files: Image-registry has dependency in copying certificate files to OCP node, the certificate file will be used in running `podman` commands.

**Comment by petr-balogh** [comment]
@ramkiperiy the rsync can currently copy just folders. See doc [here](https://docs.openshift.com/container-platform/3.9/dev_guide/copy_files_to_container.html).  So I came up with this function which allow you to do rsync from local to the node and vice versa.
