### ISSUE TITLE
Require option to customize osd size

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#894]

**Comment by gklein** [comment]
I think this is less critical for 4.2 as it expected to be a fixed size, but we should handle it for 4.3 according to the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1772742)

**Comment by gklein** [comment]
Should be handled by this:

https://github.com/red-hat-storage/ocs-ci/pull/975/

**Comment by prsurve** [comment]
Already Achived
