### ISSUE TITLE
test_dashboard_validation_ui some locators changed on ODF 4.15

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#8967]
https://url.corp.redhat.com/bf9d983

**Comment by DanielOsypenko** [comment]
it is one of the most stable tests in UI 
![image](https://github.com/red-hat-storage/ocs-ci/assets/61454420/2c5312f2-f7c6-4631-a03c-4d3d08a97bac)

This issue was not closed but the PR removing "acceptence" mark was merged long ago.
Do we want return acceptance? - if to vote, I am in favor of it.

@ebenahar

**Comment by am-agrawa** [comment]
> it is one of the most stable tests in UI ![image](https://private-user-images.githubusercontent.com/61454420/316780803-2c5312f2-f7c6-4631-a03c-4d3d08a97bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDUxODQsIm5iZiI6MTcxMTQ0NDg4NCwicGF0aCI6Ii82MTQ1NDQyMC8zMTY3ODA4MDMtMmM1MzEyZjItZjdjNi00NjMxLWEwM2MtNGQzZDA4YTk3YmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NzQzMmQyYzQwMWY0ZDcwNjkzYjNiNTU1NzgwMTg5ZDNmMzliNDFlMDQ2NDQ2YTRkMzljMmMwNDA0Y2ZmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HsyrQSn3ZcdakBbn3gOb9ikNWiS8wuinmME3XKzr6fI)
> 
> This issue was not closed but the PR removing "acceptence" mark was merged long ago. Do we want return acceptance? - if to vote, I am in favor of it.
> 
> @ebenahar

ack, closing it. Thanks!
