### ISSUE TITLE
test_ceph_metrics_presence_when_osd_down fail, no Threading lock used

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#9023]
test_ceph_metrics_presence_when_osd_down
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/17038/827152/827232/827235/log

--------
TIME
Message: failed on setup with "ocs_ci.ocs.exceptions.NoThreadingLockUsedError: using threading.Lock object is mandatory for PrometheusAPI class"
Type: None

Text:
measurement_dir = '/tmp/pytest-of-jenkins/pytest-0/measurement_results'
threading_lock = <unlocked _thread.RLock object owner=0 count=0 at 0x7f129295e360>

@pytest.fixture
def measure_stop_ceph_osd(measurement_dir, threading_lock):
    """
    Downscales Ceph osd deployment, measures the time when it was
    downscaled and alerts that were triggered during this event.

    Returns:
        dict: Contains information about `start` and `stop` time for stopping
            Ceph osd pod
    """
    oc = ocp.OCP(
        kind=constants.DEPLOYMENT,
        namespace=config.ENV_DATA.get("cluster_namespace"),
        threading_lock=threading_lock,
    )
    osd_deployments = oc.get(selector=constants.OSD_APP_LABEL).get("items")
    osds = [deployment.get("metadata").get("name") for deployment in osd_deployments]

    # get osd deployments to stop, leave even number of osd
    osd_to_stop = osds[-1]
    logger.info(f"osd disks to stop: {osd_to_stop}")
    logger.info(f"osd disks left to run: {osds[:-1]}")

    def stop_osd():
        """
        Downscale Ceph osd deployments for 11 minutes. First 1 minutes
        the alert CephOSDDiskNotResponding should be in 'Pending'.
        After 1 minute the alert turns into 'Firing' state.
        This configuration of osd can be observed in ceph-mixins which
        is used in the project:
            https://github.com/ceph/ceph-mixins/blob/d22afe8c0da34490cb77e52a202eefcf4f62a869/config.libsonnet#L21
        There should be also CephClusterWarningState alert that takes 10
        minutest to be firing.

        Returns:
            str: Names of downscaled deployments
        """
        # run_time of operation
        run_time = 60 * 16
        nonlocal oc
        nonlocal osd_to_stop
        logger.info(f"Downscaling deployment {osd_to_stop} to 0")
        oc.exec_oc_cmd(f"scale --replicas=0 deployment/{osd_to_stop}")
        logger.info(f"Waiting for {run_time} seconds")
        time.sleep(run_time)
        return osd_to_stop

    test_file = os.path.join(measurement_dir, "measure_stop_ceph_osd.json")
    if config.ENV_DATA["platform"].lower() in constants.MANAGED_SERVICE_PLATFORMS:
        # It seems that it takes longer to propagate incidents to PagerDuty.
        # Adding 3 extra minutes
        measured_op = measure_operation(
            stop_osd,
            test_file,
            minimal_time=60 * 19,
            pagerduty_service_ids=[get_pagerduty_service_id()],
        )
    else:

      measured_op = measure_operation(stop_osd, test_file)

tests/manage/monitoring/conftest.py:278: 

ocs_ci/utility/workloadfixture.py:107: in measure_operation
    alert_subscriber = PrometheusAlertSubscriber(
ocs_ci/utility/prometheus.py:727: in init
    self.prometheus_api = PrometheusAPI(threading_lock=threading_lock)

self = <ocs_ci.utility.prometheus.PrometheusAPI object at 0x7f1286420610>
user = None, password = None, threading_lock = None

def __init__(self, user=None, password=None, threading_lock=None):
    """
    Constructor for PrometheusAPI class.

    Args:
        user (str): OpenShift username used to connect to API
    """
    if threading_lock is None:

      raise NoThreadingLockUsedError(
            "using threading.Lock object is mandatory for PrometheusAPI class"
        )
E           ocs_ci.ocs.exceptions.NoThreadingLockUsedError: using threading.Lock object is mandatory for PrometheusAPI class

ocs_ci/utility/prometheus.py:334: NoThreadingLockUsedError

2023-12-03 03:42:40
Message: failed on setup with "ocs_ci.ocs.exceptions.NoThreadingLockUsedError: using threading.Lock object is mandatory for PrometheusAPI class"
Type: None

Text:
measurement_dir = '/tmp/pytest-of-jenkins/pytest-0/measurement_results'
threading_lock = <unlocked _thread.RLock object owner=0 count=0 at 0x7f129295e360>

@pytest.fixture
def measure_stop_ceph_osd(measurement_dir, threading_lock):
    """
    Downscales Ceph osd deployment, measures the time when it was
    downscaled and alerts that were triggered during this event.

    Returns:
        dict: Contains information about `start` and `stop` time for stopping
            Ceph osd pod
    """
    oc = ocp.OCP(
        kind=constants.DEPLOYMENT,
        namespace=config.ENV_DATA.get("cluster_namespace"),
        threading_lock=threading_lock,
    )
    osd_deployments = oc.get(selector=constants.OSD_APP_LABEL).get("items")
    osds = [deployment.get("metadata").get("name") for deployment in osd_deployments]

    # get osd deployments to stop, leave even number of osd
    osd_to_stop = osds[-1]
    logger.info(f"osd disks to stop: {osd_to_stop}")
    logger.info(f"osd disks left to run: {osds[:-1]}")

    def stop_osd():
        """
        Downscale Ceph osd deployments for 11 minutes. First 1 minutes
        the alert CephOSDDiskNotResponding should be in 'Pending'.
        After 1 minute the alert turns into 'Firing' state.
        This configuration of osd can be observed in ceph-mixins which
        is used in the project:
            https://github.com/ceph/ceph-mixins/blob/d22afe8c0da34490cb77e52a202eefcf4f62a869/config.libsonnet#L21
        There should be also CephClusterWarningState alert that takes 10
        minutest to be firing.

        Returns:
            str: Names of downscaled deployments
        """
        # run_time of operation
        run_time = 60 * 16
        nonlocal oc
        nonlocal osd_to_stop
        logger.info(f"Downscaling deployment {osd_to_stop} to 0")
        oc.exec_oc_cmd(f"scale --replicas=0 deployment/{osd_to_stop}")
        logger.info(f"Waiting for {run_time} seconds")
        time.sleep(run_time)
        return osd_to_stop

    test_file = os.path.join(measurement_dir, "measure_stop_ceph_osd.json")
    if config.ENV_DATA["platform"].lower() in constants.MANAGED_SERVICE_PLATFORMS:
        # It seems that it takes longer to propagate incidents to PagerDuty.
        # Adding 3 extra minutes
        measured_op = measure_operation(
            stop_osd,
            test_file,
            minimal_time=60 * 19,
            pagerduty_service_ids=[get_pagerduty_service_id()],
        )
    else:

      measured_op = measure_operation(stop_osd, test_file)

tests/manage/monitoring/conftest.py:278: 

ocs_ci/utility/workloadfixture.py:107: in measure_operation
    alert_subscriber = PrometheusAlertSubscriber(
ocs_ci/utility/prometheus.py:727: in init
    self.prometheus_api = PrometheusAPI(threading_lock=threading_lock)

self = <ocs_ci.utility.prometheus.PrometheusAPI object at 0x7f1286420610>
user = None, password = None, threading_lock = None

def __init__(self, user=None, password=None, threading_lock=None):
    """
    Constructor for PrometheusAPI class.

    Args:
        user (str): OpenShift username used to connect to API
    """
    if threading_lock is None:

      raise NoThreadingLockUsedError(
            "using threading.Lock object is mandatory for PrometheusAPI class"
        )
E           ocs_ci.ocs.exceptions.NoThreadingLockUsedError: using threading.Lock object is mandatory for PrometheusAPI class

ocs_ci/utility/prometheus.py:334: NoThreadingLockUsedError

**Comment by Pooja-Soni78** [comment]
Following test cases are also failing on ODF4.15 on IBM Power -
```
tests/manage/monitoring/prometheus/test_deployment_status.py::test_ceph_manager_stopped
tests/manage/monitoring/prometheus/test_deployment_status.py::test_ceph_monitor_stopped
tests/manage/monitoring/prometheus/test_deployment_status.py::test_ceph_mons_quorum_lost[True]
tests/manage/monitoring/prometheus/test_deployment_status.py::test_ceph_osd_stopped
tests/manage/monitoring/prometheus/test_rgw.py::test_rgw_unavailable 
```
Error being - 
```
   def __init__(self, user=None, password=None, threading_lock=None):
        """
        Constructor for PrometheusAPI class.

        Args:
            user (str): OpenShift username used to connect to API
        """
        if threading_lock is None:
>           raise NoThreadingLockUsedError(
                "using threading.Lock object is mandatory for PrometheusAPI class"
            )
E           ocs_ci.ocs.exceptions.NoThreadingLockUsedError: using threading.Lock object is mandatory for PrometheusAPI class

ocs_ci/utility/prometheus.py:334: NoThreadingLockUsedError
```
