### ISSUE TITLE
[UI] adjust test test_obc_creation_deletion to find bucket class dropdown by locator, not placeholder

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#9027]
ODF 4.13 - ODF 4.15
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/16982/821874/822031/822032/log

![image](https://github.com/red-hat-storage/ocs-ci/assets/61454420/c5f76ce5-dd10-4c2b-b47c-cd9cf49ae294)

**Comment by ebondare** [comment]
Resolved with https://github.com/red-hat-storage/ocs-ci/pull/9617
