### ISSUE TITLE
downstream installation: ocs-ci needs to check whether the versions installed are correct and are from downstream only.

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#904]
downstream installation: ocs-ci needs to check whether the versions installed are correct and are from downstream only. This is to avoid the bugs like: https://bugzilla.redhat.com/show_bug.cgi?id=1762267.

**Comment by vasukulkarni** [comment]
@hnallurv this should be addressed by https://github.com/red-hat-storage/ocs-ci/pull/185,  there is one more github issue for this one at https://github.com/red-hat-storage/ocs-ci/issues/903

**Comment by hnallurv** [comment]
closing this based on above comment from Vasu
