### ISSUE TITLE
test_unprivileged_user_odf_access always fail on VSPHERE6-UPI-ENCRYPTION-1AZ-RHCOS-VSAN-LSO-VMDK-3M-3W

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#9059]
test always fails to run toolbox commands on this type of deployments with encryption

Message: failed on setup with "subprocess.TimeoutExpired: Command '['oc', '--kubeconfig', '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig', '-n', 'openshift-storage', 'rsh', 'rook-ceph-tools-5b6f847876-9rkwk', 'ceph', 'health']' timed out after 120 seconds"
Type: None

**Comment by shyRozen** [comment]
@mashetty330 Can you check this failure?

**Comment by DanielOsypenko** [comment]
fresh failures ODF 4.13
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17898/878606/878911/878912/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17901/878938/879258/879259/log -FIPS
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17890/877789/878095/878096/log

**Comment by DanielOsypenko** [comment]
Adding another frequent failure on encrypted clusters, test test_odf_cephblockpool_compression_status

Message: failed on setup with "ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage get consoles.config.openshift.io cluster -ojsonpath='{.status.consoleURL}'.
Error is error: error loading config file "/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig": yaml: line 79: could not find expected ':'"
Type: None

**Comment by DanielOsypenko** [comment]
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17901/878938/879268/879269/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17901/878938/879268/879271/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17901/878938/879268/879270/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17901/878938/879258/879259/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/17890/877789/878095/878096/log
