### ISSUE TITLE
test_mon_data_avail_warn testcase is failing on ODF4.15 for IBM Power

### ISSUE THREAD

**Issue by Pooja-Soni78** [red-hat-storage/ocs-ci#9127]
Following Tier 2 test case is failing on IBM Power - 

tests/manage/z_cluster/test_mon_data_avail_warn.py::TestMonDataAvailWarn::test_mon_data_avail_warn

with error - 

```
            self.mon_pod = pod.get_pod_obj(
>               name=mon_pods_info[0]["metadata"]["name"],
                namespace=config.ENV_DATA["cluster_namespace"],
            )
E           IndexError: list index out of range

tests/manage/z_cluster/test_mon_data_avail_warn.py:73: IndexError
```

**Comment by Pooja-Soni78** [comment]
Logs -
[test_mon_data_avail_warn.log](https://github.com/red-hat-storage/ocs-ci/files/13868767/test_mon_data_avail_warn.log)

**Comment by prsurve** [comment]
@Pooja-Soni78 do you have must-gather from the test run

**Comment by veerareddylucky** [comment]
Following Tier 2 test case is failing on IBM Power -
ODF 4.19
tests/manage/z_cluster/test_mon_data_avail_warn.py::TestMonDataAvailWarn::test_mon_data_avail_warn

with error - `self = <tests.functional.z_cluster.test_mon_data_avail_warn.TestMonDataAvailWarn object at 0x7ffe83e129d0>

    def get_used_percentage(self):
        """
        Get used percentage on /var/lib/ceph/mon/ceph-[a/b/c]
    
        Returns:
            int: Used space percentage
    
        """
        path = f"/var/lib/ceph/mon/ceph-{self.mon_suffix}"
        if config.DEPLOYMENT.get("local_storage"):
            path = "/etc/hosts"
        cmd = f"df -Th | grep {path}"
        mount_details = self.mon_pod.exec_sh_cmd_on_pod(command=cmd, sh="sh")
>       used_percent = mount_details.split()[5].replace("%", "")
E       IndexError: list index out of range

tests/functional/z_cluster/test_mon_data_avail_warn.py:104: IndexError`

[test_mon_data_avail_warn.log](https://github.com/user-attachments/files/20795994/test_mon_data_avail_warn.log)
