### ISSUE TITLE
The condition of skipping RGW tests on non on-prem deployments is broken ever since the tests restructure

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#9224]
The condition here https://github.com/red-hat-storage/ocs-ci/blob/75f5674565047250b07e299647a1056ca8a98ff3/tests/functional/object/rgw/conftest.py#L23 should have the new path following the restructuring of our tests

**Comment by leelavg** [comment]
@ebenahar is this the only path that's missed? At times I see 4.14 upgrade run is failing w/ `Timed out after 600s running get("", True, "app=rook-ceph-exporter")` this should've been fixed as part of https://github.com/red-hat-storage/ocs-ci/issues/9155 afaik.
