### ISSUE TITLE
The bucket_factory fixture fails to verify AWS buckets creation via boto3 due to the upgrading of ocs-ci packages

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#9250]
https://github.com/red-hat-storage/ocs-ci/blob/bf2b7dc2ac41eaf8c9466e583c5b0c39bf654220/ocs_ci/ocs/resources/cloud_manager.py#L283-L301

Results in the following error due to the attempt to use head_bucket at line 296:

self.client.meta.client.head_bucket(Bucket=uls_name)
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/ocs-ci/venv/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/private/path/to/ocs-ci//venv/lib/python3.8/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (301) when calling the HeadBucket operation: Moved Permanently
```

This seems to be in result of upgrading the virtual envs after the merging of https://github.com/red-hat-storage/ocs-ci/pull/9139 and https://github.com/red-hat-storage/ocs-ci/pull/9125 since at first I only saw this on Jenkins runs, and once I upgraded my local venv I also got the same error.

**Comment by sagihirshfeld** [comment]
As a side effect that we might need to address as its own issue, AWS buckets that were created but failed to be verified in this manner are not cleaned up by OCS-CI because the cloud_uls_factory fixture crushes after their creation but before adding them to the "buckets to delete" list.

**Comment by sagihirshfeld** [comment]
Downgrading boto3 from 1.34.14 to 1.20.2 seems to fix this, but might cause other side effects.

1.20.2 was chosen arbitrarily between the original 1.14.7 and the current 1.34.14 since the original was incompatible with other packages that were updated. 

If we can't find a workaround in our usage of boto3 and we must downgrade, then we should probably look for the latest boto3 version that fixes the issue.

**Comment by sagihirshfeld** [comment]
After some binary-search like exploration, I found that the latest version that fixes this is 1.24.96

**Comment by petr-balogh** [comment]
Are we passing correctly the region? I see they mention something related to region here:
https://stackoverflow.com/questions/45338550/unable-to-access-s3-from-ec2-instance-in-cloudformation-a-client-error-301

**Comment by sagihirshfeld** [comment]
We're seeing this again due the latest boto3 version bump (https://github.com/red-hat-storage/ocs-ci/pull/12321)

RP references:
- https://url.corp.redhat.com/4bc4332
- https://url.corp.redhat.com/b3346ae
- https://url.corp.redhat.com/0a4025c
- https://url.corp.redhat.com/1f82ce5
