### ISSUE TITLE
aws_platform_required marker checks only upper-case 'AWS'

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#926]
Marker `aws_platform_required` expects value of `platform` to be set in upper-case `AWS`, but on some other places it is used as lower-case.

The definition of the [aws_platform_required](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/pytest_customization/marks.py#L62:L65) looks like this:
```python
aws_platform_required = pytest.mark.skipif(
    config.ENV_DATA['platform'] != 'AWS',
    reason="Tests are not running on AWS deployed cluster"
)
```
In [deployment/ocp.p](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/ocp.py#L29) it is used as `config.ENV_DATA['platform'].lower()` and also in some configuration files is *platform* set to `aws` (lower-case), e.g.: 
* [ocs_basic_install.yml](https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocs_basic_install.yml#L7)
* [aws_ipi.yaml](https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocsci/aws_ipi.yaml#L3)
* [production-aws-ipi.yaml](https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocsci/production-aws-ipi.yaml#L3)

So the marker will not work properly.

**Comment by MeridianExplorer** [comment]
Thanks for noticing and bringing this up - fixed :)
