### ISSUE TITLE
Add the IBMCloud Bare Metal login credentials

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#9295]
I was trying to run a node test from the Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/33188/console, but got this error:

> 2024-01-30 18:46:50  16:46:50 - MainThread - /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/ibmcloud_bm.py - INFO  - Logging to IBM cloud
> 2024-01-30 18:46:50  16:46:50 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: ibmcloud login --apikey ***** -c 1f5a3d52d3b44518a0159f73beaf616b -r us-east
> 2024-01-30 18:46:54  16:46:54 - MainThread - /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/ibmcloud_bm.py - INFO  - Successfully logged in to IBM cloud
> 2024-01-30 18:46:54  16:46:54 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: ibmcloud sl hardware list --output json
> 2024-01-30 18:46:54  16:46:54 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: Error: Failed to get hardware servers on your account.
> 2024-01-30 18:46:54 
> 2024-01-30 18:46:54  SoftLayer_Exception: Token received with no IMS account id, required for a TrustedProfile (HTTP 500)
> 

This is because when using the account in the credentials for IBM Cloud: `ibm_cloud_odf-qe` we don't have the permissions to get the server list. 
I created a new credentials file `ibm_cloud_bm_odf-qe` in my local with my personal API key, and it works fine, because I have the permissions. 
We need to create a similar file in Jenkins with a new API key that has the permissions.

**Comment by yitzhak12** [comment]
To create the API key from the IBM cloud UI, we can use this page: https://cloud.ibm.com/iam/apikeys. As I mentioned, we need the permissions for getting the server list for the account.

**Comment by dahorak** [comment]
We have to confirm which account is assigned to the `ibm_cloud_odf-qe` credential conf (I already pinged Coady with this question) and then we have to update the permission for the account to allow access to the Classic infrastructure.

**Comment by dahorak** [comment]
We can't use the original `ibm_cloud_odf-qe` secret for accessing Classic Infrastructure, because it is assigned to Service ID and it is not possible to use Service ID to access Classic Infrastructure.
So the approach is to have separated secret file - `ibm_cloud_classic_infra_odf_qe` - this API Key is assigned to Functional ID and is working with the `ibmcloud sl ...` command.
The new API key was added as part of [MR!1687](https://url.corp.redhat.com/58ecca9).
@yitzhak12 could you please confirm that the new key is working as expected, so we can close this ticket?

**Comment by yitzhak12** [comment]
We can see from the Jenkins job here that the issue was fixed correctly: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/34376/console.
