### ISSUE TITLE
Install the ibmcloud "sl" plugin before running the HCI Provider tests

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#9297]
For running node tests using the HCI Provider with IBMCloud Bare Metal, we need to install ibmcloud `sl` plugin using the command `ibmcloud plugin install sl`.
We can do it in two ways:

- Run the command `ibmcloud plugin install sl` in the ocs-ci when running the node tests using the HCI Provider with IBMCloud Bare Metal
- Install it when preparing the Jenkins slave.

**Comment by yitzhak12** [comment]
If we go on option 2: "Install it when preparing the Jenkins slave", I will need help from the ecosystem team.

**Comment by dahorak** [comment]
I'll handle this in the Ansible playbook/role where we are installing the `ibmcloud` tool and other plugins.

**Comment by yitzhak12** [comment]
Okay, thanks.

**Comment by dahorak** [comment]
The [MR!1685](https://url.corp.redhat.com/95b6c85) was merged.
