### ISSUE TITLE
Reduce timeout on ocs-catalogsource check

### ISSUE THREAD

**Issue by shyRozen** [red-hat-storage/ocs-ci#933]
In deployment, there is a check "oc -n openshift-marketplace --kubeconfig /home/srozen/f2cluster/auth/kubeconfig get CatalogSource ocs-catalogsource -n openshift-marketplace -o yaml" and it is waiting for ready state. 
There was a problem in the state and the check kept on going for 20 minutes till I stopped it manually. I think we need to reduce it to something like 5 minutes top.

**Comment by gklein** [comment]
Looking at the code, the check for the CatalogSource readiness is 5 minutes long with 4 retries which means it can take 20 minutes in case the pod is not ready till the deployment will quit. 

https://github.com/red-hat-storage/ocs-ci/blob/2e20ba815ae93e512eb479574177b545636846e6/ocs_ci/ocs/resources/catalog_source.py#L110

Do you think it would be safe to remove the retry and keep only one cycle of 5 minutes?

**Comment by gklein** [comment]
I see there was some work done around this areas recently.

It is documented in this [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1770192) and a recent [PR](https://github.com/red-hat-storage/ocs-ci/pull/1021) just made it in.

If we need to wait at least 8 minutes for wait_for_state(), I think we can at least reduce the number of retries, so the deployment will be able to quit faster, in case of 1-2 failure.

**Comment by shyRozen** [comment]
@gklein Sorry I missed that for some reason :). Ok I'm closing the issue.
