### ISSUE TITLE
[IBM Z] - [ODF 4.15] : Test "test_scale_obc_create_delete_time" is failing

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#9334]
Testcase:
tests/e2e/scale/noobaa/test_scale_obc_create_delete.py::TestScaleOCBCreateDelete::test_scale_obc_create_delete_time is failing. 

getting following error ->

                    log.info("Waited for more than 10 mins but still no data")
>                   raise UnexpectedBehaviour(
                        f"There is no obc creation data in noobaa-operator logs for {no_data}"
                    )
E                   ocs_ci.ocs.exceptions.UnexpectedBehaviour: There is no obc creation data in noobaa-operator logs for ['obc-test-6a323fab02084eecb8858bfe398a99f', 'obc-test-c4818d8b38d2425a9cd838ba2b350cc', 'obc-test-53aa84501dcf459e86aee1cafbfaa5a', 'obc-test-95edd2f540d04cbc92407205d28ce42', 'obc-test-4ab00b63a5414165b36412d12cacea2', 'obc-test-d1a5ce47eacb4a1ea55b32e8f949dec', 'obc-test-45c691c3503b4013a674231d0a9dee7', 'obc-test-91573d5625dc402983d94691e1b5e0c', 'obc-test-c54c5547d0834abba200b406d96ac14', 'obc-test-3777b98dafe64883b35352e6bedd2a6', 'obc-test-be11f850ca8d4f00b250e35ade4f93c', 'obc-test-e5692a2fa314415c8185c54094e77b3', 'obc-test-7e87293381de443bb1f9976e1decdc6', 'obc-test-6cef3b2f5ecc49328c4bdf706de9075', 'obc-test-2c0c534feaaa45f5b97414f5921a03e', 'obc-test-87d60f1a56a54f90a937d497001f8ea', 'obc-test-53dc8ef6f2c34b58946ed39ed8eab58', 'obc-test-0d18cc85bdef4b53a9677a6c97c6e7d', 'obc-test-f12c1d05a5984ac8b51b375c9ac50f1', 'obc-test-04ce7f78c60a430aa4e19342c02b868', 'obc-test-e964010e4b5847aaa42f8190fc1135c', 'obc-test-524008723ef1435e9a51857b08dbecf', 'obc-test-9257aa9e5ca8485c860aaa59df847ff', 'obc-test-edf6a2c3b70f462e86ec218cbe00974', 'obc-test-3b4dcacb491346c1a83b4eba377588a', 'obc-test-d9577e0b30ce43acba359584b3b43a8', 'obc-test-9a0508bca48a4c8eb38e18f2029cf2d', 'obc-test-21abb2993c7942d985618bb4a63e4f1', 'obc-test-983c8ed047014358a05996365e8890e', 'obc-test-576fed5e5963408fab29c241e5b9abe', 'obc-test-a6e8244620d44d67a7d3c8cda3ffb34', 'obc-test-84c3f85de35a483597ea51156bc1be0', 'obc-test-0a0c013dc586445894cb1a30cbee31a', 'obc-test-6f29dbd794004641924500e745457c0', 'obc-test-20047af0607349afaf2e095e869c409', 'obc-test-f90fdecd66804489b0a7e18ad374fb8', 'obc-test-c84980c368b5491099ccb479cf94823', 'obc-test-b8122e06382c4ec4a9816c443cd23f8', 'obc-test-1257bae352eb414ab9cae2f510a211f', 'obc-test-db3a0ecb66bd4428893710d705d35ba', 'obc-test-5f5582bb84e74f2a88acd2e16feb6e7', 'obc-test-3e25d1ac55b341df9e712cefa2fc014', 'obc-test-858a21e9b1d145bc964013bda304a37', 'obc-test-7c58c4131fac47f3b676081f3af21a7', 'obc-test-8598b1a1f7c64e2cb32c4e5c428a56f']

ocs_ci/ocs/scale_noobaa_lib.py:227: UnexpectedBehaviour

**Comment by abdulkandathil** [comment]
An issue existed before got autoclosed..
https://github.com/red-hat-storage/ocs-ci/issues/6692

**Comment by Shilpi-Das1** [comment]
The test case failed with same error in 4.16 [IBM Power] as well
