### ISSUE TITLE
update test_amq_streamer_creation.py  and change the storage class use rook-ceph-cephfs sc instead

### ISSUE THREAD

**Issue by SvetlanaRedHat** [red-hat-storage/ocs-ci#934]
https://github.com/red-hat-storage/ocs-ci/pull/849 it this PR Kartcik mentioned a comment that I should address

**Comment by gklein** [comment]
> #849 it this PR Kartcik mentioned a comment that I should address

I see that the mentioned PR was merged: https://github.com/red-hat-storage/ocs-ci/pull/849

Could we close this issue?
