### ISSUE TITLE
test_monitoring_reporting_ok_when_idle fails on buckets workloads 

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#9366]
test_monitoring_reporting_ok_when_idle

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/18639/903234/903278/log
 
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod ip-10-0-0-245us-east-2computeinternal-debug -n openshift-storage -o yaml.
E               Error is Error from server (NotFound): pods "ip-10-0-0-245us-east-2computeinternal-debug" not found
------
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/18656/903910/903954/log

botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketVersioning operation: Access Denied

========
workarounds
https://stackoverflow.com/questions/62940394/clienterror-an-error-occurred-accessdenied-when-calling-the-listobjects-opera
https://repost.aws/questions/QUsxEFx6_tQxi3CfQzeM5SXA/an-error-occurred-accessdenied-when-calling-the-listobjectsv2-operation-access-denied

**Comment by sagihirshfeld** [comment]
Closing in favor of https://github.com/red-hat-storage/ocs-ci/issues/9381

[The failed test-case above](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/18639/903234/903278/log) was the last test in the run, so the bucket_factory_session teardown failure got attributed to it.
