### ISSUE TITLE
oc delete project baremetal-debug-ns. Error is Error from server (NotFound): projects.config.openshift.io "baremetal-debug-ns" not found"

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#9372]
failed on setup with "ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc delete project baremetal-debug-ns.
Error is Error from server (NotFound): projects.config.openshift.io "baremetal-debug-ns" not found"

Job:
https://url.corp.redhat.com/5ce54d6

In BM Multus deployment on 4.15.

**Comment by prsurve** [comment]
when deleting project oc used project api from `projects.config.openshift.io` and here it did not found the project so it failed. oc should have used `projects.project.openshift.io`
