### ISSUE TITLE
test_create_scale_pods_and_pvcs_using_kube_job failed on AWS due to AttributeError

### ISSUE THREAD

**Issue by nagendra202** [red-hat-storage/ocs-ci#9476]
test_create_scale_pods_and_pvcs_using_kube_job failed in multiple runs with below attribute error.

RP1: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/18428/894774/895017/log
RP2: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/18560/899992/900238/log
RP3: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/18913/919664/919919/log
RP4: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/19388/942028/942282/log
RP5: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/19045/925645/925899/log
RP6: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/18701/905879/906129/log

machine_set = None

```def get_replica_count(machine_set):
    """
    Get replica count of a machine set

    Args:
        machine_set (str): Name of a machine set to get replica count

    Returns:
        replica count (int): replica count of a machine set
    """
    machinesets_obj = OCP(
        kind=constants.MACHINESETS, namespace=constants.OPENSHIFT_MACHINE_API_NAMESPACE
    )```


` return machinesets_obj.get(resource_name=machine_set).get("spec").get("replicas")`

E       AttributeError: 'NoneType' object has no attribute 'get'

**Comment by PrasadDesala** [comment]
Fixed with #9698
