### ISSUE TITLE
test_node_maintenance_restart[provider] TEST failed to skip on non hcp standard vsphere platform

### ISSUE THREAD

**Issue by suchita-g** [red-hat-storage/ocs-ci#9517]
/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/tests/functional/z_cluster/nodes/test_nodes_restart_ms.py:220: Test runs ONLY on cluster with managed service or HCI provider-client platform

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/18644/903287/903328/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/632/19247/934907/934949/log

**Comment by ebenahar** [comment]
@yitzhak12 please update / send a fixing PR
