### ISSUE TITLE
get method in ocp class should handle negative scenarios

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#96]
There are cases where one might need to use ocp.get method to check if a resource is already available. The get method fails with CMD error if the resource is not available. If the method returns False, get method can be used to check if a resource is available before trying to create it again. 

For eg., I want to create a new project and I'd like to check if the project already exists in the cluster. 

This is how I'd like to check. 

```
 	def create_namespace(**kwargs):
  	    pdb.set_trace()
  	    project_name = (kwargs['project_name'])
  	    **if NAMESPACE.get(project_name):**
  	        log.info(f'project {project_name} exists, using the existing namespace  ')
  	        return True
```

**Comment by RazTamir** [comment]
I believe this should be fixed when this https://github.com/red-hat-storage/ocs-ci/pull/70/files#diff-ef93c603b643a8362ba61f8d9797bac2R656 will be merged and than you can do something like:

```python
def create_namespace(**kwargs):
  	    pdb.set_trace()
  	    project_name = (kwargs['project_name'])
  	    try:
                if NAMESPACE.get(project_name):
  	        log.info(f'project {project_name} exists, using the existing namespace  ')
  	        return True
            except exceptions.CommandError:
                log.info(f'Creating new project {project_name}')
                NAMESPACE.create(project_name)
```

**Comment by keesturam** [comment]
Perfect, Thanks @RazTamir . As a workaround, I'm doing this for now.

```python

    project_name = (kwargs['project_name'])
    sc_get = NAMESPACE.get()
    namespaces = []
    for i in range(len(sc_get['items'])): namespaces.append(sc_get['items'][i]['metadata']['name'])
    log.info(f'checking id project {project_name} already exists')
    if project_name in namespaces:
        log.info(f'project {project_name} exists, using the existing namespace  ')
        return True
    else:
        log.info(f'creating a new project {project_name}')
        return run_cmd(f'oc new-project {project_name}')

```

**Comment by gklein** [comment]
Is there any work required on this issue or can we close it?

**Comment by keesturam** [comment]
closing this pretty old PR. This feature was made available already.
