### ISSUE TITLE
Execution fails before ODF installation step with StaleElementReferenceException on running RDR MultiCluster Job

### ISSUE THREAD

**Issue by keemano** [red-hat-storage/ocs-ci#9622]
Exception
`E       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
2024-04-03 12:48:52  E         (Session info: chrome-headless-shell=123.0.6312.105)
2024-04-03 12:48:52  
2024-04-03 12:48:52  venv/lib64/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: StaleElementReferenceException`

Job details - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-rdr-setup/658/console

**Comment by am-agrawa** [comment]
> [RDR] Enable ACM observability for DR monitoring dashboard on RHACM console #9646

It's failing at a different place this time, should be fixed by this [commit](https://github.com/red-hat-storage/ocs-ci/pull/9646/commits/1a158dc57dfc0f4dd21354c5a6edac4f5036fab8).
