### ISSUE TITLE
google-auth requires setuptools which is >=40.3.0

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#970]
Upon installing requirement.txt, below error is seen

Processing /home/vavuthu/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511/pycparser-2.19-py2.py3-none-any.whl
ERROR: google-auth 1.7.0 has requirement setuptools>=40.3.0, but you'll have setuptools 39.0.1 which is incompatible.

**Comment by thabang077** [comment]
How to fix this error?
