### ISSUE TITLE
test_nsfs_object_integrity is failing on ODF 4.16 on IBM Power

### ISSUE THREAD

**Issue by Pooja-Soni78** [red-hat-storage/ocs-ci#9724]
Below test cases are failing on IBM Power - 
```
tests/functional/object/mcg/test_nsfs.py::TestNSFSObjectIntegrity::test_nsfs_object_integrity[CLI-25Gi]
tests/functional/object/mcg/test_nsfs.py::TestNSFSObjectIntegrity::test_nsfs_object_integrity[OC-20Gi-Export]
```
Error being -
```
        nsfs_obj.interface_pod = Pod(
>           **get_pods_having_label(
                f"app={deployment_app_label}",
                ocsci_config.ENV_DATA["cluster_namespace"],
            )[0]
        )
E       IndexError: list index out of range

tests/conftest.py:5704: IndexError
```

**Comment by Pooja-Soni78** [comment]
log file -
[test_nsfs_object_integrity[CLI-25Gi].log](https://github.com/red-hat-storage/ocs-ci/files/15093752/test_nsfs_object_integrity.CLI-25Gi.log)
[test_nsfs_object_integrity[OC-20Gi-Export].log](https://github.com/red-hat-storage/ocs-ci/files/15093753/test_nsfs_object_integrity.OC-20Gi-Export.log)

**Comment by shrinivas-sidral** [comment]
**test_nsfs_object_integrity is failing on ODF 4.17 on IBM Power**

Below test cases are failing on IBM Power -
tests/functional/object/mcg/test_nsfs.py::TestNSFSObjectIntegrity::test_nsfs_object_integrity[CLI-25Gi]
tests/functional/object/mcg/test_nsfs.py::TestNSFSObjectIntegrity::test_nsfs_object_integrity[OC-20Gi-Export]
Error being -

        nsfs_obj.interface_pod = Pod(
>           **get_pods_having_label(
                f"app={deployment_app_label}",
                ocsci_config.ENV_DATA["cluster_namespace"],
            )[0]
        )
E       IndexError: list index out of range

tests/conftest.py:5704: IndexError

log files -
[test_nsfs_object_integrity[CLI-25Gi].log](https://github.com/user-attachments/files/16781742/test_nsfs_object_integrity.CLI-25Gi.log)
[test_nsfs_object_integrity[OC-20Gi-Export].log](https://github.com/user-attachments/files/16781744/test_nsfs_object_integrity.OC-20Gi-Export.log)
