### ISSUE TITLE
mcg obc bucket creation with OC need update storage class name

### ISSUE THREAD

**Issue by waynesun09** [red-hat-storage/ocs-ci#981]
In the mcg obc template, the storage class name is: noobaa-storage-class

https://github.com/red-hat-storage/ocs-ci/blob/8d30a9f15f7964f5f9776e4a488cd975b4daa8ce/ocs_ci/templates/mcg/ObjectBucketClaim.yaml#L8

while in the latest downstream ocs the storage class name is: openshift-storage.noobaa.io

When run the test_bucket_creation.py OC cases, all the obc will be at pending status.

**Comment by MeridianExplorer** [comment]
Addressed in PR #1000

**Comment by waynesun09** [comment]
@MeridianExplorer PR #1000 did not include fix for this issue.

As this is a OBC name change which I'm not sure whether it will different with upstream, downstream, various release, so I did not update it.

While it will fail https://github.com/red-hat-storage/ocs-ci/issues/1010 , because it try to write files to a new OBC created by OC command, which will be in pending status as storage class name not exist.

For current status I think it's fine to include the fix:
https://github.com/red-hat-storage/ocs-ci/pull/1010/commits/b9c8b04ed8ff8bf5e4635581d39bd4ea0de498d9

into PR #1010 , please help check.

**Comment by MeridianExplorer** [comment]
@waynesun09 - My bad, sorry. I meant to say it was addressed in #995.

**Comment by MeridianExplorer** [comment]
Closed in #995
