### ISSUE TITLE
test_monitoring_shutdown_mgr_pod is failing on 4.14 with TypeError

### ISSUE THREAD

**Issue by vkathole** [red-hat-storage/ocs-ci#9816]
RP : https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/20778/996095/996141/log

`self = <tests.e2e.workloads.ocp.monitoring.test_monitoring_on_negative_scenarios.TestMonitoringBackedByOCS object at 0x7f989d68aca0>
pods = [<ocs_ci.ocs.resources.pod.Pod object at 0x7f987afe21c0>, <ocs_ci.ocs.resources.pod.Pod object at 0x7f9899b30d90>, <oc...6d0>, <ocs_ci.ocs.resources.pod.Pod object at 0x7f989dcf0ee0>, <ocs_ci.ocs.resources.pod.Pod object at 0x7f9881506f40>]
threading_lock = <unlocked _thread.RLock object owner=0 count=0 at 0x7f992eb89840>

@pytest.mark.polarion_id("OCS-1535")
def test_monitoring_shutdown_mgr_pod(self, pods, threading_lock):
    """
    Montoring backed by OCS, bring mgr down(replica: 0) for some time
    and check ceph related metrics
    """
    # Check ceph metrics available

  assert (
        check_ceph_metrics_available()
    ), "failed to get results for some metrics before Downscaling deployment mgr to 0"
E       TypeError: check_ceph_metrics_available() missing 1 required positional argument: 'threading_lock'

tests/e2e/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py:629: TypeError`

**Comment by PrasadDesala** [comment]
Fixed with #9817
