### ISSUE TITLE
ERROR - Wait for Pod resource  to reach desired condition Running failed, last actual status was ['Running']

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#992]
I got this message (which does not make sense (Running is the desired condition and current state -- why fail?))

This was when I tried deploying the latest ocs-ci (e4c1ca5164b9adc85933a81f79e51b3f9a85c044)

19:08:11 - MainThread - ocs_ci.ocs.ocp - ERROR - Wait for Pod resource  to reach desired condition Running failed, last actual status was ['Running']
FAILED                                                                   [100%]

=================================== FAILURES ===================================
_______________________________ test_deployment ________________________________

    @destroy
    @deployment
    def test_deployment():
        deploy = config.RUN['cli_params'].get('deploy')
        teardown = config.RUN['cli_params'].get('teardown')
        if not teardown or deploy:
            log.info("Verifying OCP cluster is running")
            assert is_cluster_running(config.ENV_DATA['cluster_path'])
            if not config.ENV_DATA['skip_ocs_deployment']:
>               ocs_install_verification()

tests/ecosystem/deployment/test_deployment.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/ecosystem/deployment/test_deployment.py:78: in ocs_install_verification
    assert pod.wait_for_resource(
ocs_ci/ocs/ocp.py:435: in wait_for_resource
    raise(ex)
ocs_ci/ocs/ocp.py:385: in wait_for_resource
    timeout, sleep, self.get, resource_name, True, selector
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7f48ae9384a8>

    def __iter__(self):
        if self.start_time is None:
            self.start_time = time.time()
        while True:
            self.last_sample_time = time.time()
            try:
                yield self.func(*self.func_args, **self.func_kwargs)
            except Exception:
                pass
    
            if self.timeout < (time.time() - self.start_time):
>               raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed Out: (0,)

ocs_ci/utility/utils.py:729: TimeoutExpiredError
================ 1 failed, 231 deselected in 2357.90s (0:39:17) ================

**Comment by wusui** [comment]
All the openshift-storage pods look okay.

(venv) [wusui@localhost ocs-ci]$ oc -n openshift-storage get pods
NAME                                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-9rjk7                                            3/3     Running     0          35m
csi-cephfsplugin-hndfx                                            3/3     Running     0          35m
csi-cephfsplugin-provisioner-58cd567669-p6xnv                     3/3     Running     0          35m
csi-cephfsplugin-provisioner-58cd567669-zshvs                     3/3     Running     0          35m
csi-cephfsplugin-z4f6l                                            3/3     Running     0          35m
csi-rbdplugin-ctnwf                                               3/3     Running     0          35m
csi-rbdplugin-nljhz                                               3/3     Running     0          35m
csi-rbdplugin-provisioner-68cfdd8784-g946z                        4/4     Running     0          35m
csi-rbdplugin-provisioner-68cfdd8784-zzlv8                        4/4     Running     0          35m
csi-rbdplugin-q4827                                               3/3     Running     0          35m
local-storage-operator-5cfddfbf89-n9l5q                           1/1     Running     0          36m
noobaa-operator-59ffd58895-brhcq                                  1/1     Running     0          35m
ocs-operator-57848699d5-ckggt                                     1/1     Running     0          35m
rook-ceph-drain-canary-ip-10-0-137-140-9c47496bf-fqpdk            1/1     Running     0          32m
rook-ceph-drain-canary-ip-10-0-148-55-7799484cdd-x99zl            1/1     Running     0          32m
rook-ceph-drain-canary-ip-10-0-174-238-6b6b956fb4-9cdt4           1/1     Running     0          32m
rook-ceph-mds-ocs-storagecluster-cephfilesystem-a-79bf579dclc5z   1/1     Running     0          31m
rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-564d6dd9l2f7p   1/1     Running     0          31m
rook-ceph-mgr-a-b7f9cbf95-grnsh                                   1/1     Running     0          33m
rook-ceph-mon-a-7bfbfdf886-sppjd                                  1/1     Running     0          34m
rook-ceph-mon-b-6fdf5fd6f8-ctnck                                  1/1     Running     0          33m
rook-ceph-mon-c-695cd949b5-cs9w2                                  1/1     Running     0          33m
rook-ceph-operator-76b49d6d5-c7npv                                1/1     Running     0          35m
rook-ceph-osd-0-844bbb4b6-9r7qw                                   1/1     Running     0          32m
rook-ceph-osd-1-5b7fbf55bf-9htxg                                  1/1     Running     0          32m
rook-ceph-osd-2-9bcd46bb4-jq5wg                                   1/1     Running     0          32m
rook-ceph-osd-prepare-ocs-deviceset-0-0-dvht4-dvbqg               0/1     Completed   0          32m
rook-ceph-osd-prepare-ocs-deviceset-1-0-kdtst-4s9gk               0/1     Completed   0          32m
rook-ceph-osd-prepare-ocs-deviceset-2-0-w9fq7-j2rxw               0/1     Completed   0          32m
rook-ceph-rgw-ocs-storagecluster-cephobjectstore-a-55b9697pd8dd   1/1     Running     0          31m
rook-ceph-tools-684c555cff-ld4ft                                  1/1     Running     0          31m

**Comment by petr-balogh** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1771844 so I think that it's not a issue of ocs-ci but of the OCS itself.

**Comment by mbukatov** [comment]
Please note that the important piece of the log is what it was looking for exactly before it timeouted, not the timeout exception itself.

**Comment by petr-balogh** [comment]
This is not our issue but bug in the product, so closing.
