### ISSUE TITLE
test_run_pod_local_image is failing due to image pull issue in disconnected mode

### ISSUE THREAD

**Issue by nagendra202** [red-hat-storage/ocs-ci#9985]
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: podman image pull fio --authfile /tmp/authfile_9a1_30sl.
E               Error is Error: short-name resolution enforced but cannot prompt without a TTY

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/22191/1058656/1058882/log?logParams=history%3D1015665%26page.page%3D1

**Comment by PrasadDesala** [comment]
This was fixed with #10720
